docs/tests/use-cases/ci-cd-for-go-project/complete-ci-cd/dagger.cue, docs/tests/use-cases/ci-cd-for-go-project/image.cue.fragment, docs/tests/use-cases/ci-cd-for-go-project/push.cue.fragment, docs/tests/use-cases/ci-cd-for-go-project/test.cue.fragment, docs/use-cases/1219-go-docker-hub.md
=> docs: Improve wording on “Go on Docker Hub” use case

docs/getting-started/1201-ci-environment.md
Hey, here's how I managed to get dagger to run on Gitlab-CI
Related to #1677
=> docs: add getting started gitlab ci configuration

docs/use-cases/1211-go-docker-swarm.md, website/src/css/custom.scss
After discussion with @grouville, use h2 title instead of h3 + fix css
=> [Docs] - Use cases Docker Swarm HTML semantics

docs/getting-started/1220-vs.md, website/sidebars.js
Signed-off-by: kgb33 <keltonbassingthwaite@gmail.com>
Closes #1981
Closes #1960
I made a copy of  `introduction/1002-vs.md` 
mirroring the copies of `learn/1005-what_is_cue.md` and `core-concepts/1215-what-is-cue.md`
=> Copied "Dagger vs. Other Software" doc to Europa.

website/docusaurus.config.js
Closes https://github.com/dagger/dagger.io/issues/168
=> Remove navbar schedule link

.goreleaser.yml
This hooks into the PRs and their authors.
=> ci: Use github for the changelog

docs/use-cases/1211-go-docker-swarm.md
=> Update 1211-go-docker-swarm.md: tiny typo

.goreleaser.yml
Credit to @gerhard in https://github.com/dagger/dagger/pull/2019#issuecomment-1087466687
=> ci: Add full changelog to release notes

pkg/universe.dagger.io/docker/cli/client.cue
Fixes #1886
Moving the `if`s inside the fields avoids some issues.
=> Fix mounts in `cli.#Run`

.github/workflows/auto-release.yml
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>
=> ci: fix auto-release secrets

docs/getting-started/1200-local-dev.md
=> docs: add tip for support symlink with git on Windows

.github/workflows/dagger-ci.yml, .github/workflows/lint.yml, Makefile, ci.cue, ci/cue/lint.cue, ci/golangci/lint.cue, ci/markdownlint/markdownlint.cue, ci/shellcheck/shellcheck.cue
- `Makefile` now uses `dagger do lint` to lint
- GHA uses dagger to lint
=> ci: lint dagger using dagger

CODEOWNERS
/cc @slumbering @gerhard @shykes
=> ci: Use default CODEOWNERS for docs sidebar

pkg/dagger.io/dagger/core/fs.cue, pkg/universe.dagger.io/docker/build.cue
Signed-off-by: yuyicai <yuyicai@hotmail.com>
=> chore: Fix typo

docs/guides/1223-custom-buildkit.md, docs/guides/1224-self-signed-certificates.md, docs/guides/1225-pushing-plan-dependencies.md, website/sidebars.js
Adding some new content to the guide docs + fixing some previous pages hidden
=> New content to guide docs

plan/task/clientfilesystemread.go
Signed-off-by: rrylee <rrylee1994@gmail.com>
=> remove dup code when judge filesystem target isFS

website/docusaurus.config.js, website/src/css/custom.scss
Use a modern web font with a better render on non-retina display.
Thanks to @alireza-ahmadi for his report.
=> website: update code blocks font

cmd/dagger/cmd/common/common.go
Signed-off-by: Nick Flückiger <nick.flueckiger@renuo.ch>
This pr converts the src/dest in cache options from home relative paths e.g. ~/path to absolute paths.
Example:
`./cmd/dagger/dagger do build --cache-from type=local,src=~/cc `
is being interpreted as 
./cmd/dagger/dagger do build --cache-from type=local,src=/Users/liberatys/cc (/Users/liberatys being my home-dir)
Fixes #2003
=> Convert home relative paths for cache options

docs/learn/1008-aws-cloudformation.md, website/docusaurus.config.js
this will throw an error if docusaurus find any broken links
=> website: Increase broken links checking

docs/getting-started/1201-ci-environment.md
=> docs: Add Jenkins CI doc. Fixes #2067

pkg/universe.dagger.io/python/python.cue, pkg/universe.dagger.io/python/test/test.cue
Closes #2114
Signed-off-by: Adam Smith <adamsmith@nottheeconomist.com>
=> universe: python: allow custom path to python

pkg/universe.dagger.io/x/teddylear@protonmail.com/lua/fmtCheck.cue, pkg/universe.dagger.io/x/teddylear@protonmail.com/lua/test/data/hello/example.lua, pkg/universe.dagger.io/x/teddylear@protonmail.com/lua/test/fmtCheck.cue, pkg/universe.dagger.io/x/teddylear@protonmail.com/lua/test/test.bats
Creating lua package for fmt and linting part 1 adding stylua command
I can add a negative test case as well, but I'm not sure how. Any help with that or any other changes I should make please let me know. 
#2137
=> Creating lua package for fmt

.gitignore, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/container.cue, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/image.cue, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/publish.cue, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test.cue, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/data/Greeting.Tests/Greeting.Tests.csproj, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/data/Greeting.Tests/Greeting_Should.cs, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/data/Greeting/Greeting.cs, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/data/Greeting/Greeting.csproj, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/data/hello/Program.cs, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/data/hello/hello.csproj, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/image.cue, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/publish.cue, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/test.bats, pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/test.cue
Targets to support .NET "publish" and "test" commands on same way like Golang build and test works.
~Marked as draft because unit test(s) to verify "test" command is not yet implemented.~
=> feat: support .NET

cmd/dagger/cmd/project/init.go, cmd/dagger/cmd/project/update.go
=> fix: explicit dagger project usage

cmd/dagger/cmd/do.go, go.mod, pkg/universe.dagger.io/aws/cli/test/test.bats, pkg/universe.dagger.io/aws/test/test.bats, plan/action.go, plan/action_test.go, plan/plan.go, tests/plan.bats, tests/plan/do/do_flags.cue, tests/tasks.bats
Had to recreate #1902 because of private -> public transition
=> `dagger do` action options flags

plan/task/export.go
This is for better visibility into the contents of tag.
=> chore: Quote value in error

pkg/universe.dagger.io/netlify/deploy.sh
Closes #1924
Signed-off-by: Stavros Panakakis [stavrospanakakis@gmail.com](mailto:stavrospanakakis@gmail.com)
=> universe: netlify: replace curl-based wrapper with cli

pkg/universe.dagger.io/x/vgjm456@qq.com/helm/image.cue, pkg/universe.dagger.io/x/vgjm456@qq.com/helm/install.cue, pkg/universe.dagger.io/x/vgjm456@qq.com/helm/test/test.cue
Signed-off-by: vgjm <vgjm456@qq.com>
=> feat: support helm

docs/administrator/1013-operator-manual.md, docs/guides/1223-custom-buildkit.md
Signed-off-by: rrylee <rrylee1994@gmail.com>
=> docs: update opentracing doc, using opentelemetry

docs/core-concepts/1202-plan.md, docs/core-concepts/1213-dagger-cue.md, docs/getting-started/1200-local-dev.md, docs/getting-started/1201-ci-environment.md, docs/references/1222-core-actions-reference.md, docs/references/1234-dagger-types-reference.md, docs/update-version.sh
=> docs: Update version

cmd/dagger/cmd/common/common.go, plan/task/clientfilesystemread.go, plan/task/clientnetwork.go, plan/task/exec.go, plancontext/context.go, plancontext/service.go, solver/socketprovider.go, solver/socketprovider_unix.go
Signed-off-by: Andre Passos <andrebritopassos@gmail.com>
=> Renamed service to socket

docs/core-concepts/1215-what-is-cue.md
=> docs: Add embedding explanation

pkg/universe.dagger.io/x/contact@kjuulh.io/rust/container.cue, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/image.cue, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/publish.cue, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/test.cue, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/test/data/hello/Cargo.toml, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/test/data/hello/src/main.rs, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/test/image.cue, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/test/publish.cue, pkg/universe.dagger.io/x/contact@kjuulh.io/rust/test/test.bats
Basically adding the official rust image to universe actions.
=> Add Rust to universe community

docs/core-concepts/1215-what-is-cue.md
Follow up on #2046 to add sample link
=> docs: Add embedding sample

docs/getting-started/1201-ci-environment.md
- Update Jenkinsfile
- Embed youtube video tutorial
=> docs: Update Jenkins docs content

cmd/dagger/cmd/do.go, plan/action.go
Signed-off-by: Andre Passos <andrebritopassos@gmail.com>
Bug: dagger do causes seg fault when running in directory with no actions #2245
=> [bug] dagger do causes seg fault when running in directory with no actions

pkg/universe.dagger.io/bash/bash.cue
=> universe: Set bash.#Run entrypoint to `/bin/bash`

plan/validate.go
Improve error messages when pointing to an invalid structure reference
Before:
```
failed to load plan: client.filesystem."./bin".write: non-concrete value struct
```
After:
```
failed to load plan: "client.filesystem.\"./bin\".write" is not set
```
=> plan validation: abort if structures are not concrete

.github/workflows/dagger-ci.yml, .github/workflows/test-integration.yml, .github/workflows/test-universe.yml, cmd/dagger/cmd/common/common.go, pkg/universe.dagger.io/bats_helpers.bash, tests/helpers.bash
=> ci: scope cache to enhance speed

pkg/dagger.io/dagger/plan.cue
=> fix: Fix generated attributes

docs/core-concepts/1221-action.md
Signed-off-by: Marco Abis <marco.abis@gmail.com>
=> link to core actions reference docs rather than repo

docs/getting-started/1200-local-dev.md
Signed-off-by: Marco Abis <marco.abis@gmail.com>
=> updated references to v0.2.8

docs/tests/core-concepts/secrets/plans/sops.cue
=> docs: Fix reference in example

plan/validate.go, tests/plan.bats, tests/plan/concrete/struct_or_other.cue
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>
=> plan validation: fix structure navigation

pkg/dagger.io/dagger/core/secrets.cue
=> Fix DecodeSecret output type

docs/references/1234-dagger-types-reference.md
Signed-off-by: Berry Phillips <berryphillips@gmail.com>
=> docs: fix broken core/image.cue link

pkg/universe.dagger.io/x/hardy4yooz@gmail.com/notify/discord/discord.cue, pkg/universe.dagger.io/x/hardy4yooz@gmail.com/notify/discord/parameter.cue, pkg/universe.dagger.io/x/hardy4yooz@gmail.com/notify/discord/test/test.cue
Signed-off-by: hardy4yooz <hardy4yooz@gmail.com>
=> feat:add discord webhook support

docs/getting-started/1201-ci-environment.md
=> docs: Replace Youtube link with HD video

docs/core-concepts/1202-plan.md, docs/core-concepts/1213-dagger-cue.md, docs/getting-started/1201-ci-environment.md, docs/references/1222-core-actions-reference.md, docs/update-version.sh
Another manual update until #2351 lands
=> docs: bump dagger version in docs

pkg/universe.dagger.io/x/wangwei27494731@gmail.com/kustomize/image.cue, pkg/universe.dagger.io/x/wangwei27494731@gmail.com/kustomize/kustomize.cue, pkg/universe.dagger.io/x/wangwei27494731@gmail.com/kustomize/test/test.cue, pkg/universe.dagger.io/x/wangwei27494731@gmail.com/kustomize/test/testdata/deployment.yaml, pkg/universe.dagger.io/x/wangwei27494731@gmail.com/kustomize/test/testdata/kustomization.yaml, pkg/universe.dagger.io/x/wangwei27494731@gmail.com/kustomize/test/testdata/pod.yaml
Signed-off-by: wangwei <434533508@qq.com>
=> feat: add kustomize package

pkg/dagger.io/dagger/plan.cue, tests/plan/client/network/valid.cue
This allows unblocking:
- #2037 
More context:
- #2196 
=> feat: Use `client: network` address as a default

.github/workflows/dagger-ci.yml, .github/workflows/lint.yml
follow-up https://github.com/dagger/dagger-for-github/pull/56#issuecomment-1111730526
cc @sipsma 
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> ci: invoke dagger directly through its GitHub Action

cmd/dagger/cmd/do.go
From https://github.com/dagger/dagger/issues/1351, didn't rebase after https://github.com/dagger/dagger/pull/2321.
=> Fix unrebased merge

docs/introduction/1236-community.md
might be too soon in which case feel free to reject!
Signed-off-by: Marco Abis <marco.abis@gmail.com>
=> new community page

cmd/dagger/cmd/do.go
Doesn't allow to send unknown flags to `do` command.
Fixes #2297
=> Fail if unknown flag is specified

docs/guides/1227-contributing.md
=> docs: Add new commits prefix `fix` and `feat`

pkg/universe.dagger.io/x/david@rawkode.dev/kubernetes/example.cue, pkg/universe.dagger.io/x/david@rawkode.dev/kubernetes/kubectl.cue
This feels like it should work, but when it runs it fails and I can't work out how to get further debugging information.
```
9:53AM DBG actions.rawkode.apply._exec | #6 Exec ["kubectl", "apply", "--kubeconfig", "/kubeconfig", "-f", "/work"]
9:53AM DBG actions.rawkode.apply._exec | #6 sha256:c676aabdc1af55ae8852a03a5a7e25a92009e466a0ae932db97e4ce140e19827
9:53AM ERR actions.rawkode.apply._exec | failed: process "kubectl apply --kubeconfig /kubeconfig -f /work" did not complete successfully: exit code: 1
duration=400ms
9:53AM INF actions.rawkode.apply._exec | #6 0.372 error: error loading config file "/kubeconfig": open /kubeconfig: permission denied
9:53AM DBG actions.rawkode.apply._exec | #6 ERROR: process "kubectl apply --kubeconfig /kubeconfig -f /work" did not complete successfully: …
```
=> feat: initial kubectl apply

docs/core-concepts/1202-plan.md, docs/core-concepts/1213-dagger-cue.md, docs/getting-started/1200-local-dev.md, docs/getting-started/1201-ci-environment.md, docs/guides/1230-persistent-cache.md, docs/references/1222-core-actions-reference.md, docs/update-version.sh
=> Update docs to 0.2.9

.github/workflows/dagger-ci.yml, .github/workflows/lint.yml, .github/workflows/todoapp.yml, docs/guides/1237-persistent-cache.md, docs/learn/1009-github-actions.md, docs/tests/getting-started/github-actions.yml, docs/use-cases/1211-go-docker-swarm.md
=> ci: bump github action to latest

pkg/universe.dagger.io/python/image.cue, pkg/universe.dagger.io/python/python.cue, pkg/universe.dagger.io/python/test/test.cue
closes #2169
Signed-off-by: Adam Smith <adamsmith@nottheeconomist.com>
=> universe: python: Use official python image

.github/workflows/test-integration.yml, .github/workflows/test-unit.yml, .github/workflows/test-universe.yml, ci.cue
This is easier to read than JSON format.
=> ci: set log format to plain

compiler/value.go, pkg/dagger.io/dagger/plan.cue, plan/action.go, plan/task/clientfilesystem.go, plan/task/clientfilesystemread.go, plan/task/clientfilesystemwrite.go, plan/task/util.go, plan/validate.go, plancontext/tempdir.go, tests/plan.bats, tests/plan/client/filesystem/conflict/test.cue, tests/plan/client/filesystem/read/file/test.cue, tests/plan/client/filesystem/read/fs/dynamic/fail_load.cue, tests/plan/client/filesystem/read/fs/dynamic/fail_path_exists.cue, tests/plan/client/filesystem/read/fs/invalid_fs_input/test.cue, tests/plan/client/filesystem/read/fs/invalid_fs_type/test.cue, tests/plan/client/filesystem/read/fs/multiple/test.cue, tests/plan/client/filesystem/write/multiple/test.cue
Resolves #2196
The ability to write multiple times to the same path has come up a few times. Reading as well. We ourselves have resorted to the hack of reading from `.` and `./` in the same plan (in CI), to allow different `include`/`exclude` patterns. Using `core.#Copy` to filter down a bigger `dagger.#FS` from the host isn't always appropriate because you'll load more than you need, depending on your target action.
Also, the fact that you can't use a dynamic path in `client: filesystem` has come up a lot too. Users want to use paths from environment variables for better portability and reusability.
Allow overriding `client: filesystem` path in the action's field, using the CUE path as a default.
Simply using the CUE path as a default, allowing to override explicitly. This is backwards …
=> feat: Use `client: filesystem` path as a default

docs/getting-started/1200-local-dev.md
For the page: https://docs.dagger.io/1200/local-dev
Related to #2259
=> docs: Add more installation options for Windows

docs/core-concepts/1202-plan.md, docs/core-concepts/1213-dagger-cue.md, docs/getting-started/1200-local-dev.md, docs/getting-started/1201-ci-environment.md, docs/guides/1237-persistent-cache.md, docs/references/1222-core-actions-reference.md, docs/update-version.sh
=> docs: bump dagger version to v0.2.11

docs/guides/1226-coding-style.md
=> doc: document cue fmt -s in the package coding style

cmd/dagger/cmd/do.go, tests/plan.bats
=> fix: Default to json when printing action outputs in a non-tty environment

pkg/universe.dagger.io/x/solomon@dagger.io/yarn/test/test.bats, pkg/universe.dagger.io/x/solomon@dagger.io/yarn/test/test.cue, pkg/universe.dagger.io/x/solomon@dagger.io/yarn/yarn.cue
Simplify API and implementation.
=> experimental: fix and improve custom yarn package

api/api.go, api/auth/auth.go, cmd/dagger/cmd/apitest.go, cmd/dagger/cmd/login.go, cmd/dagger/cmd/logout.go, cmd/dagger/cmd/root.go, go.mod, go.sum
=> primitive auth support

pkg/universe.dagger.io/docker/test/image.cue
=> fix(docker.#Image): correctly verify files

docs/faq/1240-core-source.md, website/sidebars.js
Resolves #2342
👀 [Rendered](https://deploy-preview-2525--devel-docs-dagger-io.netlify.app/1240/core-source)
=> docs: Explain how to use `core.#Source`

website/src/css/custom.scss
Close to https://github.com/dagger/dagger.io/issues/328
=> make code in hyperlinks visible

client/client.go, telemetry/event/action.go
=> Add event to push action logs to Dagger Cloud

docs/guides/code/1241-field-shadowing.md
=> docs(faq): explain field shadowing

cmd/dagger/cmd/do.go
=> bugfix: don't send 'run started' event on 'dagger do --help'

docs/guides/code/1226-coding-style.md
=> docs: link back to Source faq

pkg/universe.dagger.io/bash/bash.cue
Signed-off-by: Kambui Nurse <siafudev@gmail.com>
fixes #2638
=> fix: add additional flags to command

CODEOWNERS
=> Add alpha and beta paths

docs/core-concepts/1202-plan.md
Added missing word to sentence to make it more readable.
Signed-off-by: Pico Geyer <picogeyer@gmail.com>
=> docs: Minor grammar fix for core concepts

docs/guides/docker/1216-docker-cli-load.md, docs/plans/docker-cli-load/local_windows.cue
=> docs: Add windows example in `cli.#Load` using socket

docs/guides/actions/1239-making-reusable-package.md, mod/repo.go
=> docs: Clarify git tag format when installing a package

docs/core-concepts/1202-plan.md, docs/core-concepts/1213-dagger-cue.md, docs/getting-started/1201-ci-environment.md, docs/getting-started/1240-install.md, docs/guides/buildkit/1237-persistent-cache.md, docs/references/1222-core-actions-reference.md
=> chore: bump dagger patch version from 0.2.11 to 0.2.19 in docs

pkg/universe.dagger.io/go/build.cue, pkg/universe.dagger.io/go/test/build.cue
Signed-off-by: Joaquin Fernández Campo <jfcampo@gmail.com>
=> fix: added a variable to customize the binary in go.#Build

docs/guides/logdebug/1241-dagger-cloud-debugging.md
Signed-off-by: user.email <jf@dagger.io>
=> docs: add dagger cloud url to docs

docs/guides/actions/1239-making-reusable-package.md
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2678"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: correct GitHub camel case

telemetry/telemetry.go
This speeds up telemetry upload considerably. This is an initial
approach before moving into more advanced solutions like using http2
streams or forking the process to handle this in the background. So far
the performance has been acceptable, so we can say it's good enough for
a simple solution for the moment.
=> Use a worker pool to send telemetry data

docs/index.md
=> fix: Correct docs routes

pkg/universe.dagger.io/alpha/kubernetes/helm/install.cue
Signed-off-by: Jeremy Adams <3187222+jpadams@users.noreply.github.com>
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Correct case for private definition per style

pkg/universe.dagger.io/alpha/php/composer/composer.cue, pkg/universe.dagger.io/alpha/php/composer/composer.sh, pkg/universe.dagger.io/alpha/php/composer/container.cue, pkg/universe.dagger.io/alpha/php/composer/image.cue
Related to: https://github.com/dagger/dagger/pull/2620
I've worked in the feedback that @TomChv left on the related pull request.
=> universe: php: composer: Improved package extensibility

docs/guides/concepts/1241-docker.md
https://deploy-preview-2726--devel-docs-dagger-io.netlify.app/1241/docker/#build-arguments
=> docs: Fix Docker build argument name

website/netlify.toml
=> Add more permissive referrer header

pkg/universe.dagger.io/alpha/aws/cdk/python/cdk.sh, pkg/universe.dagger.io/alpha/aws/cdk/python/command.cue, pkg/universe.dagger.io/alpha/aws/cdk/python/deploy.cue, pkg/universe.dagger.io/alpha/aws/cdk/python/diff.cue, pkg/universe.dagger.io/alpha/aws/cdk/python/image.cue, pkg/universe.dagger.io/alpha/aws/cdk/python/install.cue, pkg/universe.dagger.io/alpha/aws/cdk/python/install.sh, pkg/universe.dagger.io/alpha/aws/cdk/python/test/image.cue, pkg/universe.dagger.io/alpha/aws/cdk/python/test/test.bats
This adds support for AWS CDK projects written in python.
=> feat: add python aws cdk package

cmd/dagger/cmd/doc.go
This PR restores the `dagger doc [package name]`
The whole lib generation works partially (disabled on purpose).
Closes #1872 
cc @dolanor
=> feat: restore code to generate docs from a package name

api/api.go, api/auth/auth.go
Prevents auth panic by adding a mutex in the login process since
multiple clients could be waiting to send telemetry concurrently.
=> fix: prevent auth panic and handle auth race condition

Makefile
https://github.com/dagger/dagger/pull/2749#discussion_r915350566
=> fix: remove useless GIT_REVISION

docs/tests/use-cases/node-ci/full/node-ci.cue, docs/use-cases/1227-node-ci.md
Missed a couple of things from the first merge:
- Spacing error in full pipeline
- Caveat added that my sonarqube config is only for Github
- Removed mention of License Scanning as it did not make it into the final pipeline
=> Tweak Basic CI Node use case

docs/getting-started/1240-install.md
Resolves: #2456 
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2780"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs(install): fix windows path

pkg/universe.dagger.io/alpha/go/goreleaser/image.cue, pkg/universe.dagger.io/alpha/go/goreleaser/release.cue, pkg/universe.dagger.io/alpha/go/goreleaser/test/data/hello/go.mod, pkg/universe.dagger.io/alpha/go/goreleaser/test/data/hello/goreleaser.yaml, pkg/universe.dagger.io/alpha/go/goreleaser/test/data/hello/main.go, pkg/universe.dagger.io/alpha/go/goreleaser/test/image.cue, pkg/universe.dagger.io/alpha/go/goreleaser/test/release.cue, pkg/universe.dagger.io/alpha/go/goreleaser/test/test.bats
Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>
=> feat(universe): add goreleaser to alpha

pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/kubectl.cue, pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/kustomization.cue
Since https://github.com/bitnami/bitnami-docker-kubectl/pull/43 has been merge, this PR updates the experimental package default version to latest version and adds a test.
=> universe(x/kubectl): update kustomize with latest version

pkg/universe.dagger.io/alpha/uffizzi/createPreview.cue, pkg/universe.dagger.io/alpha/uffizzi/deletePreview.cue, pkg/universe.dagger.io/alpha/uffizzi/image.cue, pkg/universe.dagger.io/alpha/uffizzi/updatePreview.cue
Add the uffizzi package to the dagger universe
=> universe: add uffizzi to dagger universe 🥳

docs/getting-started/1201-ci-environment.md
fixes #2599 
also bumps `dagger` version
tested in GitLab here: https://gitlab.com/jpadams301/test-ci/-/jobs/2749236088
=> fix: Use included wget instead of curl

.github/dependabot.yml
One for @slumbering to review & merge.
=> ci: Dependabot appends area/website label to /website bumps

pkg/universe.dagger.io/alpha/doppler/main.cue
Signed-off-by: David Flanagan <david@rawkode.dev>
=> fix: ensure doppler works with file or config

docs/getting-started/1201-ci-environment.md
=> docs: Add simple CircleCI example

docs/getting-started/1201-ci-environment.md
=> docs: Add title to GitLab yaml

docs/getting-started/1201-ci-environment.md
=> docs: Add appropriate title to Tekton YAML

docs/getting-started/1201-ci-environment.md
=> docs: Add appropriate title to Jenkinsfile

docs/core-concepts/1204-secrets.md
doc: 
- what is sops
- directions on generating `age` keypair
- directions on encrypting and editing a yaml file with `sops
Signed-off-by: Vibhav Bobade <vibhav.bobde@gmail.com>
=> doc: add directions for using sops 

Makefile, kind-dagger.yml, pkg/universe.dagger.io/alpha/kubernetes/helm/image.cue, pkg/universe.dagger.io/alpha/kubernetes/helm/install.cue, pkg/universe.dagger.io/alpha/kubernetes/helm/test/test.cue, pkg/universe.dagger.io/alpha/kubernetes/helm/test/testdata/values.base.yaml, pkg/universe.dagger.io/alpha/kubernetes/helm/test/testdata/values.staging.yaml, pkg/universe.dagger.io/alpha/kubernetes/helm/upgrade.cue
> **Note** This is a prototype implementaton. Feedback for improvement would be appreciated.
Resolves #2806 
- add  `#Upgrade` action in `universe.dagger.io/alpha/kubernetes/helm`
=> implement helm upgrade action

client/client.go, telemetry/event/action.go
=> Send telemetry data about action cache status

docs/guides/logdebug/1243-dagger-cloud-debugging.md
=> docs: clarify what data gets sent to dagger cloud

website/netlify.toml
=> update embargoes compliance only for Crimea

docs/guides/logdebug/1243-dagger-cloud-debugging.md
clarified that the Dagger support team can see their data 
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2872"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added clarification

pkg/universe.dagger.io/alpha/go/golangci/image.cue, pkg/universe.dagger.io/alpha/go/golangci/lint.cue, pkg/universe.dagger.io/alpha/go/golangci/test/test.bats
Trying to apply the patterns discussed in #2781
cc @gerhard @helderco
=> Split up action definitions into template and pre-configured image in golangci

docs/core-concepts/1215-what-is-cue.md
Fixes #2653. It explains the 4 most common CUE patterns present in our codebase.
cc @jpadams 
=> CUE docs gotchas updates

docs/core-concepts/1221-action.md
Explain how to run single actions. Closes #2554
cc @jpadams 
=> docs: explain how to run single actions

docs/guidelines/1226-coding-style.md
Fixes #2813. Shows an example of a proper use of raw strings
cc @jpadams 
=> docs: raw strings use - example

docs/core-concepts/1202-plan.md
=> docs: rename plan docs title

docs/guidelines/1227-contributing.md, website/package.json, website/yarn.lock
- docs: Make the section on links in docs clearer
- docs: Expand on how to run the linters
- docs: Fix link to PR
This should be rebase & merged after https://github.com/dagger/dagger/pull/2884
=> docs: Contributing guidelines fixes

docs/core-concepts/1221-action.md
- Clarify the use of the sub-action term
- Introduce the notion of an action's domain logic
- Explain what a universe package is, and how it relates to composite actions.
Fixes #2701 and #2879
cc @jpadams 
=> docs: explain universe packages / clarify usage of sub-action term

pkg/universe.dagger.io/alpha/azure/aks/auth/akscreds.sh, pkg/universe.dagger.io/alpha/azure/aks/auth/image.cue, pkg/universe.dagger.io/alpha/azure/aks/auth/kubeconfig.cue, pkg/universe.dagger.io/alpha/azure/auth/azlogin.sh, pkg/universe.dagger.io/alpha/azure/auth/image.cue, pkg/universe.dagger.io/alpha/azure/auth/token.cue, pkg/universe.dagger.io/alpha/azure/test/test.cue
resolve: #2860 
- generic action to get an azure token for a specific resource or scope
- action to get AKS credentials for user or admin
=> implement aks auth

pkg/universe.dagger.io/alpha/kubernetes/helm/upgrade.cue
=> fix helm login

pkg/universe.dagger.io/alpha/terraform/run.cue, pkg/universe.dagger.io/alpha/terraform/test/test.cue, pkg/universe.dagger.io/alpha/terraform/workspace.cue
Signed-off-by: Brittan DeYoung <32572259+brittandeyoung@users.noreply.github.com>
* Updated Workspace Action to be functional
* Updated the workspace field on the terraform Run action to be optional (sometimes it is preferred to manage this using the workspace commands.)
* Added tests for the workspace Action.
=> Feat: Terraform Workspace Action

docs/dgr18-overview.mdx
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2933"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added button to tutorial card

docs/getting-started/1242-install.mdx, website/src/components/molecules/tutorialCard.js, website/src/css/atoms/button.module.scss, website/src/css/molecules/tutorialCard.module.scss
This will fix anchor tags with odd behavior and make the Tutorial Card more consistent with the rest of the design.
=> [Docs] Fix Tutorial Card and Buttons

docs/README.md
This will add a section in /website/README.md that explains how to export a redirection config file and how it works.
Closes #2911 
=> [Docs] Update README explaining new UUID generation

pkg/universe.dagger.io/alpha/go/goreleaser/release.cue, pkg/universe.dagger.io/alpha/go/goreleaser/test/release.cue
Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>
=> refactor: use base pattern in goreleaser

.github/workflows/test-experimental-universe.yml, .github/workflows/test-universe.yml, ci/bats/bats.cue, cmd/dagger/cmd/do.go, pkg/universe.dagger.io/bats_helpers.bash, tests/helpers.bash, tests/package.json, tests/plan.bats, tests/yarn.lock
Fixes #2582 
`dagger do` will print:
```
Usage: 
dagger do <action> [subaction...] [flags]
```
Signed-off-by: Tuong Le <tuongaz@gmail.com>
=> fix: dagger do help should indicate where to insert action name #2582

docs/guides/concepts/4dhu9-api-customizable-image.md, docs/tests/guides/customizable-image/image_configurable.cue, docs/tests/guides/customizable-image/image_pip.cue, docs/tests/guides/customizable-image/image_simple.cue, docs/tests/guides/customizable-image/run.cue, docs/tests/guides/customizable-image/run_base.cue, website/static/_redirects
Doc explaining the best design pattern to create actions with customizable images
cc @jpadams 
Closes #2677.
Related to #2781
=> docs: design pattern - how to build actions with customizable images

README.md
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2953"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> added a release section

pkg/universe.dagger.io/alpha/aws/sam/README.md
Signed-off-by: Tanguy ⧓ Herrmann <928722+dolanor@users.noreply.github.com>
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2954"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: make the URL work in github and locally

docs/core-concepts/1220-vs.md, docs/core-concepts/1221-action.md, docs/getting-started/f44rm-how-it-works.mdx
This will update bottom pagination between the How It Works and Core Concepts sections.
Closes #2958 
=> [Docs] Update Bottom Pagination

docs/README.md
=> [Docs] Add Debugging Section to the README

website/src/css/atoms/button.module.scss, website/src/css/custom.scss, website/src/css/molecules/tutorialCard.module.scss, website/src/css/overview.module.scss
This will make changes in the UI based on internal feedback.
=> [Docs] Docs UI Feedback Implementation

website/src/css/custom.scss
This will change static and hovering colors on the navbar when the viewport is small, on both light and dark modes.
=> [Docs] Fix Navbar Styling on Mobile Devices

website/docusaurus.config.js, website/package.json, website/yarn.lock
A new project "Docs" as been created on Posthogs.
=> use Posthogs to get users analysis path

pkg/universe.dagger.io/alpha/jreleaser/README.md, pkg/universe.dagger.io/alpha/jreleaser/commands.cue, pkg/universe.dagger.io/alpha/jreleaser/container.cue, pkg/universe.dagger.io/alpha/jreleaser/image.cue
Adds JReleaser as a package to alpha.
Signed-off-by: Andres Almiray <aalmiray@gmail.com>
=> feat(universe): add jreleaser to alpha

pkg/universe.dagger.io/alpha/azure/aks/auth/kubeconfig.cue, pkg/universe.dagger.io/alpha/azure/aks/helm/image.cue, pkg/universe.dagger.io/alpha/azure/aks/helm/test/test.cue, pkg/universe.dagger.io/alpha/azure/aks/helm/test/testdata/values.base.yaml, pkg/universe.dagger.io/alpha/azure/aks/helm/test/testdata/values.staging.yaml, pkg/universe.dagger.io/alpha/azure/aks/helm/upgrade.cue, pkg/universe.dagger.io/alpha/azure/auth/token.cue, pkg/universe.dagger.io/alpha/azure/test/test.cue
resolve: #2913 
- aks helm upgrade action
=> feat: aks specific helm action

pkg/universe.dagger.io/alpha/azure/auth/azlogin.sh, pkg/universe.dagger.io/alpha/azure/vault/get-secret.sh, pkg/universe.dagger.io/alpha/azure/vault/image.cue, pkg/universe.dagger.io/alpha/azure/vault/secret.cue, pkg/universe.dagger.io/alpha/azure/vault/test/test.cue
resolves: #2986
- Curl based action to fetch secrets from azure vault
- azure auth base script scope and resource args
=> feature: fetch azure vault secret

docs/dgr18-overview.mdx, docs/getting-started/1242-install.mdx, docs/getting-started/f44rm-how-it-works.mdx, docs/introduction/1000-what_is.md, website/docusaurus.config.js, website/package.json, website/src/components/atoms/linkCTA.js, website/src/components/molecules/tutorialCard.js, website/yarn.lock
As per discussed in #2981
The medium-zoom plugin could improve the user experience when reading diagrams that are wider than the page layout.
=> docs: Add Docusaurus medium-zoom plugin

README.md, docs/unxpq-introduction.md
- No more early access
- Tweaked intro
=> Clean up README

core/core.go, core/core.schema.go, core/filesystem/image.go, core/integration/old_core.schema_test.go
Not a particularly beautiful solution, but gets the bug fixed for the moment and the better solution is coming soon with the new api work.
Fixes #3170 
cc @vito just want to squash that bug to unblock @vikram-dagger. Hopefully at least the test case code will be useful when we have the real solution, but I'm guessing the rest will be mostly throwaway.
The reason the solution looks so weird is that `Cmd` and `Entrypoint` don't propagate automatically along with `llb.State`, so I just do a dumb thing where I store the whole image config in the llb state metadata and pass that along.
=> Pull+push all image config.

internal/buildkitd/buildkitd.go
Got the error "exit status 1" when my docker daemon was not running, it took me longer than needed to figure out why I had this message...
Also minor code simplification in the if/else logic while walking through the error checking.
Fixes #3015
=> Fix error msg

core/integration/project_test.go, internal/testutil/query.go, project/gogenerate.go
Fixes #3019
A lot of this is going to change soon anyways, but getting the fix in now since it's pretty straightforward and quite annoying when hit. The test case should hopefully not be throwaway in the long term either.
cc @kralicky not 100% sure but this sounds like what you mentioned in the community call earlier today.
=> Handle case where workdir and extension/script subdir are same.

core/schema/README.md
=> Fix paths for schema files

core/container.go, core/directory.go, core/file.go, core/git.go
Should fix the problems when running from macos.
Opened an issue for automating that: https://github.com/dagger/dagger/issues/3225
But for now verified by running directly from macos. 
This will also be a little bit of setup for integration the multiplatform PR w/ the new API, so no throwaway here hopefully.
@vito the rebase w/ your PRs will be painful sadly. I had one important comment on your PR ([here](https://github.com/dagger/dagger/pull/3205#discussion_r986333125)), but let's try to merge that first then I'll do the rebase on this one if possible.
=> Propagate platform to all marshals.

docs/unxpq-introduction.md
- New intro
- Simpler diagrams
- Terminology: tried to use less words, and simpler words
Feedback welcome!
=> Docs: tweak intro & messaging

sdk/python/dagger/src/dagger/client.py, sdk/python/dagger/src/dagger/server.py
- Implements FSID and SecretID types
- Fixes a typo in the logger
- Implements json serialization in case the resolver returns a custom type
=> Python SDK improvements

TESTING.md
"How to run tests" is a FAQ and also not immediately obvious (see this issue: https://github.com/dagger/dagger/pull/3261#issuecomment-1269226363) .
=> Barebones TESTING.md

.github/workflows/test.yaml, TESTING.md, package.json, sdk/nodejs/test/index.mjs
=> Add barebones nodejs sdk test.

core/directory.go, core/integration/container_test.go, core/integration/directory_test.go, core/integration/suite_test.go, core/schema/directory.go, core/schema/directory.graphqls
closes #3179
* add withoutFile
* add withoutDirectory
* add diff
* remove secret (redundant with directory.file.secret)
=> finish initial `Directory` API

docs/unxpq-introduction.md
=> Add link for kapp extension

package.json, sdk/nodejs/test/index.mjs, yarn.lock
=> Use mocha for nodejs SDK testing

core/container.go, core/integration/container_test.go, core/shim/cmd/main.go
=> container.exec: support stdin + stdout/stderr redirects

core/integration/container_test.go, core/schema/container.go, core/schema/container.graphqls, go.mod, go.sum, magefile.go, sdk/go/dagger/api/api.gen.go
still figuring out how to return envVariables as [EnvVariable!]!
=> refactor(core): rename variable -> envVariable

sdk/go/dagger/querybuilder/querybuilder.go
=> Remove stray debug print of query.

docs/v0.2/getting-started/1242-install.mdx
=> chore: Use 0.2 branch for 0.2 examples

docs/v0.2/getting-started/1242-install.mdx
=> chore: Align branch names dagger<>examples

examples/python/client-simple/README.md, examples/python/client-simple/async_query.py, examples/python/hello/main.py, sdk/python/dagger/pyproject.toml, sdk/python/dagger/src/dagger/cli.py, sdk/python/dagger/src/dagger/client.py, sdk/python/dagger/src/dagger/engine.py, sdk/python/dagger/src/dagger/server.py
Fixes #3300
Notice: `Engine` needs a bit more work. Specifically running an async subprocess.
=> Python: Support async resolvers and client

core/container.go, core/integration/container_test.go, core/integration/testdata/codetoschema/main.go, core/schema/container.go, core/schema/container.graphqls, sdk/go/dagger/api/api.gen.go
=> replace ContainerAddress with String, publish returns fully qualified ref

README.md, docs/v0.3/sdk/go/8g34z-get-started.md, docs/v0.3/sdk/go/fssrz-index.md
* New SDK-aware messaging in README
* Improved and expanded Go SDK intro
=> Update README and Go SDK docs

sdk/cue/README.md
This is the first task of #3471
=> sdk/cue: adds README

pkg/pkg.go
- In preparation for https://github.com/dagger/dagger/pull/3486
=> Reset the version check to 0.1.0

.github/workflows/mirror-go-sdk.yml
Mirror Go SDK into https://github.com/dagger/dagger-go-sdk
=> ci: mirror go sdk

go.mod
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>
=> go.mod: bump sdk version

docs/current/partials/_install-sdk-go.md
=> Don't tidy; pull latest.

docs/current/partials/_install-sdk-go.md
=> Clarify go install instructions needs to be in a go mod.

docs/current/sdk/go/959738-get-started.md, website/sidebars.js
=> Update sdk reference links

docs/current/partials/_install-sdk-go.md
cc @marcosnils @kpenfound @jpadams
=> Add note about tidy

docs/current/543069-index.md
=> changed the SDK request link to the typeform page

README.md
=> updated docs link

pkg/pkg.go
=> chore: dagger to dagger-cue

docs/current/sdk/cue/core-concepts/151357-what-is-cue.md, docs/current/sdk/cue/core-concepts/667572-dagger-fs.md, docs/current/sdk/cue/getting-started/526369-install.mdx, docs/current/sdk/cue/getting-started/tutorial/470907-local-dev.md, docs/current/sdk/cue/getting-started/tutorial/665980-ci-environment.md, docs/current/sdk/cue/guides/concepts/937034-api-customizable-image.md, docs/current/sdk/cue/references/112043-dagger-env-reference.md, docs/current/sdk/cue/use-cases/493789-aws-sam.md
=> docs: Fixed links to previous version doc pages

docs/current/sdk/cue/604916-index.md, docs/current/sdk/go/440319-index.md
=> docs: Fix punctuation in lists, update diagram

docs/current/partials/_install-sdk-go.md
=> Add note about why go mod replace is needed.

docs/current/162770-faq.md
=> docs: Point to sdk docs and typeform

.github/workflows/lint.yml
**Issue:**
The lint Github Action is failing.
**Error:**
**Resolution:**
remove errant spacing.
Signed-off-by: Sean Alexander <self@seannalexander.com>
=> fix lint.yml yaml validation errors

.github/workflows/lint.yml, .github/workflows/test.yml, magefile.go
- feat: use the current version of dagger for code generation
- build: build dagger with mage
=> Dogfood dagger with mage

package.json, sdk/nodejs/dagger/dist/engine.js
=> Enable newer versions of node to use the node SDK

website/docusaurus.config.js
Closes [#1079](https://github.com/dagger/dagger.io/issues/1079)
=> docs: Add icon to docs pages for social sharing

cmd/cloak/dev.go, cmd/cloak/main.go
`dagger dev --log-output /dev/stderr` to get the previous behaviour
=> feat(cli): dev can choose where to output log

core/container.go, core/integration/container_test.go
=> fix building container from subdirectory

.github/workflows/test.yml, core/container.go, core/integration/container_test.go, core/integration/platform_test.go, core/integration/project_test.go, core/integration/suite_test.go, core/schema/base.go, core/schema/container.go, core/schema/container.graphqls, core/schema/directory.graphqls, core/schema/fs.go, core/schema/platform.go, core/schema/platform.graphqls, router/errors.go, router/router.go, router/schema.go, sdk/go/api.gen.go
See comment on simplified design based on new API here: https://github.com/dagger/dagger/pull/3119#issuecomment-1295416978
Followups ups (after PR)
=> Multiplatform support

RELEASING.md
This should be automated -- but in the meantime, at least it's somewhat documented.
=> add releasing instructions

core/integration/git_test.go, core/schema/git.go, core/schema/git.graphqls, sdk/go/api.gen.go
=> API: git { commit }

docs/current/partials/_install-sdk-cue.md
This commit updates the installation commands for the CUE SDK for Linux, Windows and macOS.
=> docs: Update the dagger-cue installation steps

sdk/python/.flake8, sdk/python/pyproject.toml, sdk/python/src/dagger/api/base.py, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/cli.py, sdk/python/src/dagger/connection.py, sdk/python/src/dagger/connectors/base.py, sdk/python/src/dagger/connectors/http.py, sdk/python/src/dagger/server/__init__.py, sdk/python/src/dagger/server/cli.py, sdk/python/src/dagger/server/converter.py, sdk/python/tests/api/test_codegen.py, sdk/python/tests/api/test_integration.py
=> sdk: python: Revert to black’s default max line length

core/integration/git_test.go, core/schema/git.go, core/schema/git.graphqls, sdk/go/api.gen.go
https://github.com/dagger/dagger/issues/3657
=> feat: add keep git dir to go sdk client git

.github/workflows/lint.yml, .github/workflows/test.yml, go.mod, go.sum, internal/mage/sdk/all.go, internal/mage/sdk/go.go, internal/mage/sdk/python.go, internal/mage/util/util.go, sdk/python/src/dagger/api/gen.py, sdk/python/tests/api/test_integration.py
[BASED ON TOP OF #3706]
Partially addresses https://github.com/dagger/dagger/issues/3678
- Adds lint/test/generate
- integrated into CI
=> ci: basic Python support

examples/python/client-simple/say.py, sdk/python/README.md, sdk/python/src/dagger/cli.py, sdk/python/src/dagger/connection.py, sdk/python/src/dagger/connectors/__init__.py, sdk/python/src/dagger/connectors/base.py, sdk/python/src/dagger/connectors/docker.py, sdk/python/src/dagger/connectors/http.py, sdk/python/tests/api/test_integration.py
Fixes #3686
Credit to @sipsma for the implementation 🙌. 
Note: I converted to `sync` code to reuse in upcoming `sync` support. There's follow up work in #3687 to fix this.
=> sdk: python: Fix provisioner

.github/workflows/test.yml, sdk/python/tests/api/test_integration.py
Don’t know what changed in engine, tests were failing with the Go SDK.
=> sdk: python: Revert test optimization

examples/python/client-simple/say_sync.py, internal/mage/sdk/all.go, internal/mage/sdk/go.go, internal/mage/sdk/python.go, sdk/python/pyproject.toml, sdk/python/src/dagger/__init__.py, sdk/python/src/dagger/api/base.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/cli.py, sdk/python/src/dagger/codegen.py, sdk/python/src/dagger/connection.py, sdk/python/src/dagger/connectors/base.py
=> sdk: python: Add sync support

sdk/python/pyproject.toml
=> sdk: python: Quick pyproject update

.github/workflows/publish-engine.yml, RELEASING.md, go.mod, go.sum, internal/mage/engine.go
**There are a few parts of the instructions I'd like to automate ASAP (before official release ideally), will comment on them. Just writing out the instructions as is for now.**
=> Add engine release instructions.

go.mod, go.sum, sdk/go/go.mod, sdk/go/go.sum, sdk/go/internal/engineconn/dockerprovision/container.go
Fixes https://github.com/dagger/dagger/issues/3737, thanks @aluzzardi for finding the problem!
=> Don't unlink docker-container tmpbin after process starts.

.readthedocs.yaml, sdk/python/.gitignore, sdk/python/README.md, sdk/python/docs/api.rst, sdk/python/docs/conf.py, sdk/python/docs/connection.rst, sdk/python/docs/index.rst, sdk/python/poetry.lock, sdk/python/pyproject.toml, sdk/python/src/dagger/__init__.py, sdk/python/src/dagger/api/base.py, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/codegen.py, sdk/python/src/dagger/connection.py
=> sdk: python: Add reference docs

docs/current/sdk/python/628797-get-started.md, docs/current/sdk/python/866944-install.md
This commit updates the Python SDK installation instruction to support the pre-release package.
Relates to #3639
=> docs: Updated Python SDK installation step

docs/current/sdk/python/628797-get-started.md
=> docs: Minor addition to get started guide

docs/current/sdk/python/628797-get-started.md
=> docs: indicate that config is optional

docs/current/sdk/python/628797-get-started.md, docs/current/sdk/python/866944-install.md
=> docs: remove --pre from pip install

core/container.go
=> Deal with Scratch correctly

.github/workflows/test.yml
There's a small chance this might be helpful for debugging this issue: https://github.com/dagger/dagger/issues/3784
And in general it doesn't hurt to have this in case we run into other weird issues in the future.
=> Include kernel logs in gha output.

sdk/go/client_test.go
Go SDK was facing a race condition on the `TestConnectOption` test:
- Replaces the buffer to a Pipe, to make sure the write buffer is closed when the read occurs
Co-authored-by: @marcosnils 🙏 
cc @sipsma @aluzzardi
=> fix(race): TestConnectOption racing on buffer's write

sdk/python/README.md, sdk/python/docs/index.rst, sdk/python/pyproject.toml
=> sdk: python: Update project links

sdk/python/src/dagger/connectors/base.py, sdk/python/src/dagger/server/cli.py
=> sdk: python: Chain exceptions properly

sdk/python/src/dagger/connectors/docker.py, sdk/python/tests/api/test_integration.py, sdk/python/tests/connectors/test_docker.py
=> sdk: python: Avoid shadowing built-ins

sdk/nodejs/provisioning/docker-provision/image.ts
=> Fail when session binary copy command fails.

docs/current/sdk/nodejs/722802-index.md, docs/current/sdk/nodejs/783645-get-started.md, docs/current/sdk/nodejs/835948-install.md, docs/current/sdk/nodejs/snippets/get-started/step3/build.ts, docs/current/sdk/nodejs/snippets/get-started/step4/build.ts, docs/current/sdk/nodejs/snippets/get-started/step5/build.ts, website/sidebars.js
This commit contains the documentation for the Node.js SDK.
Closes #3640
=> docs: Add Node.js SDK docs

.github/workflows/test.yml, internal/mage/sdk/nodejs.go
Follow-up to:
- https://github.com/dagger/dagger/pull/3783
=> Revert GitHub action dagger for test / sdk / nodejs

sdk/nodejs/provisioning/docker-provision/image.ts
=> Normalize os+arch names in nodejs sdk.

.github/dependabot.yml
=> chore(pyhon): Add dependabot

docs/current/162770-faq.md
=> docs: Add FAQ entry for container registry auth

docs/current/sdk/nodejs/783645-get-started.md, docs/current/sdk/nodejs/835948-install.md, examples/nodejs/package.json, examples/nodejs/say.ts, sdk/nodejs/README.md
Collection of Feedback regarding node SDK
Signed-off-by: Benjamin Strasser <bp.strasser@gmail.com>
=> Node Feedback

internal/mage/sdk/all.go
- `mg.Deps` has some weird quircks and sometimes doesn't run
- switched to a simple errgroup
=> ci: fix `sdk:all:*` target

codegen/generator/nodejs/templates/src/header.ts.tmpl, sdk/nodejs/api/client.gen.ts
Relates to https://github.com/dagger/dagger/pull/3832#issuecomment-1318185095
=> sdk: nodejs: Fixed typo in codegen

docs/current/sdk/nodejs/783645-get-started.md, docs/current/sdk/nodejs/snippets/get-started/step3/build.js, docs/current/sdk/nodejs/snippets/get-started/step4/build.js, docs/current/sdk/nodejs/snippets/get-started/step5/build.js
=> docs: Tabs for JavaScript & TypeScript

sdk/nodejs/connect.ts
=> sdk: nodejs: Remove cloak from comment

docs/current/sdk/nodejs/722802-index.md
=> docs: Fix typos in Node.js SDK index page

codegen/generator/nodejs/templates/src/header.ts.tmpl, sdk/nodejs/.eslintrc.cjs, sdk/nodejs/api/client.gen.ts
Also fix typescript linting issue
=> NodeJS SDK: Lint generated client file

sdk/nodejs/api/client.gen.ts
Two conflicting PRs made the linter fail
=> sdk: nodejs: fix linter

core/integration/container_test.go, core/integration/directory_test.go, core/integration/secret_test.go, core/schema/directory.graphqls, docs/current/sdk/go/snippets/embed-directories/main.go, sdk/go/api.gen.go, sdk/go/client_test.go, sdk/go/examples_test.go, sdk/nodejs/api/client.gen.ts, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py
Fixes #3884
/cc @vikram-dagger @kpenfound @helderco @dolanor
=> api: directory.withNewFile: make `contents` mandatory

sdk/python/src/dagger/api/.gitattributes, sdk/python/src/dagger/cli.py
=> sdk: python: Fix .gitattributes

docs/current/sdk/python/snippets/get-started/step1/test.py, docs/current/sdk/python/snippets/get-started/step3/test.py, docs/current/sdk/python/snippets/get-started/step4a/test.py, docs/current/sdk/python/snippets/get-started/step4b/test.py, docs/current/sdk/python/snippets/multi-builds/build.py, docs/current/sdk/python/snippets/private-repositories/clone.py, internal/mage/docs.go, internal/mage/sdk/python.go, sdk/python/examples/client-simple/README.md, sdk/python/pyproject.toml
Fixes #3893
Made other small tweeks to make snippets more consistent between each other.
=> docs(python): Lint doc snippets

sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/codegen.py
=> sdk: python: Allow passing objects in params named `id`

docs/current/sdk/python/628797-get-started.md, docs/current/sdk/python/guides/648384-multi-builds.md, docs/current/sdk/python/snippets/get-started/step3/test.py, docs/current/sdk/python/snippets/get-started/step4a/test.py, docs/current/sdk/python/snippets/get-started/step4b/test.py, docs/current/sdk/python/snippets/multi-builds/build.py
=> docs(python): Fix id usage

sdk/python/.flake8, sdk/python/pyproject.toml, sdk/python/src/dagger/__init__.py, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/codegen.py
=> sdk: python: Import API types into global namespace

internal/mage/engine.go, sdk/go/internal/engineconn/bin/bin.go, sdk/go/internal/engineconn/dockerprovision/container.go, sdk/go/internal/engineconn/dockerprovision/image.go, sdk/nodejs/provisioning/docker-provision/image.ts, sdk/python/src/dagger/connectors/bin.py, sdk/python/src/dagger/connectors/docker.py
cc @helderco @marcosnils @aluzzardi
=> Still set DAGGER_RUNNER_HOST from SDKs for now.

internal/mage/engine.go
=> ci: fix publish engine flow

internal/mage/util/util.go
Fixes https://github.com/dagger/dagger/issues/3950
=> Include linux engine-session bins in local dev engine.

core/schema/README.md
=> ci: trigger engine push

README.md
=> add community call

sdk/python/pyproject.toml
=> chore(python): Trivial formatting cleaning

sdk/python/src/dagger/connectors/.gitattributes
=> sdk: python: Add .gitattributes file for engine version

sdk/python/examples/client-simple/say.py, sdk/python/examples/client-simple/say_sync.py
=> sdk: python: Fix examples

sdk/python/experimental/hello/main.py, sdk/python/experimental/hello/requirements.txt, sdk/python/poetry.lock, sdk/python/pyproject.toml, sdk/python/src/dagger/__init__.py
Fixes #3966 
Helps unlock #3942
=> sdk: python: Make strawberry dependency optional

internal/engine/docker.go
User report that the provisioner doesn't work w/ nerdctl: https://discord.com/channels/707636530424053791/1046845155761733713/1046845155761733713
I don't really love playing whack-a-mole with these error messages but I don't know of a better way of checking for this particular error that doesn't end up being the same game in a different form.
=> Check for already used error in nerdctl format too.

sdk/python/poetry.lock, sdk/python/pyproject.toml, sdk/python/src/dagger/connectors/http.py, sdk/python/src/dagger/transport/httpx.py
=> sdk: python: Migrate to httpx

examples/nodejs/package.json, examples/nodejs/say.ts, examples/nodejs/yarn.lock
=> Node.js SDK - Update sdk example

cmd/dagger/listen.go, cmd/dagger/run.go
=> make dagger run use a random path for DAGGER_SESSION_URL

cmd/dagger/run.go
=> fix dagger run alias

sdk/python/poetry.lock
Should fix https://github.com/dagger/dagger/pull/3774#issuecomment-1332062083
=> chore(deps): Update sdk/python

cmd/dagger/run.go
=> Fix typo in dagger run help.

docs/current/api/254103-build-custom-client.md, docs/current/api/snippets/build-custom-client/step2/client.php, docs/current/api/snippets/build-custom-client/step2/main.rs, docs/current/cli/979595-reference.md, docs/current/sdk/nodejs/reference/modules.md, website/yarn.lock
=> docs: update docs with DAGGER_SESSION_TOKEN.

sdk/nodejs/api/test/api.spec.ts
=> Node.js SDK - increase Mocha test timeout

codegen/generator/nodejs/templates/src/object_comment.ts.tmpl, codegen/generator/nodejs/templates/src/object_comment_test.go, codegen/generator/nodejs/templates/src/type_test.go, sdk/nodejs/api/client.gen.ts
=> Update ref docs by showing types

RELEASING.md
cc @slumbering @grouville @gerhard
=> Add warning about releasing engine before SDKs.

cmd/dagger/do.go, cmd/dagger/main.go
=> docs: add dagger do warning message

codegen/generator/nodejs/templates/src/method_solve.ts.tmpl, codegen/generator/nodejs/templates/src/objects_test.go, sdk/nodejs/api/client.gen.ts, sdk/nodejs/api/test/api.spec.ts, sdk/nodejs/api/utils.ts
=> Node.js SDK - Always return a immutable object

RELEASING.md
chore: Improve RELEASING.md based on today's interactions
+ Improve release notes with @slumbering, e.g.
https://github.com/dagger/dagger/releases/tag/sdk%2Fnodejs%2Fv0.2.0
+ Help public promotion of releases cc @mircubed
> **Note**
> For a good reviewing experience:
> <img width="1441" alt="Screenshot 2022-12-01 at 18 22 03" src="https://user-images.githubusercontent.com/3342/205130655-48f996e8-9383-4db6-a95a-e4486be1a774.png">
=> chore: Improve RELEASING.md based on today's interactions

docs/current/sdk/cue/getting-started/470907-get-started.md
Signed-off-by: Thomas Boni <thomas@r2devops.io>
Resolve #4093
=> docs: Fix GitLab CI configuration

docs/current/sdk/nodejs/snippets/get-started/step4/build.js, docs/current/sdk/nodejs/snippets/get-started/step4/build.ts, docs/current/sdk/nodejs/snippets/get-started/step5/build.js, docs/current/sdk/nodejs/snippets/get-started/step5/build.ts
> **Note**
> This should be merged once the new Node.js SDK 0.3 release has been cut.
related to PR #4005
=> Update Node.js SDK optionals arguments

docs/current/sdk/nodejs/snippets/get-started/step4/build.js, docs/current/sdk/nodejs/snippets/get-started/step4/build.ts, docs/current/sdk/nodejs/snippets/get-started/step5/build.js, docs/current/sdk/nodejs/snippets/get-started/step5/build.ts
=> Update container optional arguments

docs/current/543069-index.md
=> update SDK request form URL

docs/current/sdk/go/275922-guides.md, docs/current/sdk/go/guides/768421-go-ci.md, docs/current/sdk/go/snippets/go-ci/Jenkinsfile, docs/current/sdk/go/snippets/go-ci/actions.yml, docs/current/sdk/go/snippets/go-ci/circle.yml, docs/current/sdk/go/snippets/go-ci/gitlab.yml, docs/current/sdk/nodejs/947203-guides.md, docs/current/sdk/nodejs/guides/114934-nodejs-ci.md, docs/current/sdk/nodejs/snippets/nodejs-ci/Jenkinsfile, docs/current/sdk/nodejs/snippets/nodejs-ci/actions.yml, docs/current/sdk/nodejs/snippets/nodejs-ci/circle.yml, docs/current/sdk/nodejs/snippets/nodejs-ci/gitlab.yml, docs/current/sdk/python/234291-guides.md, docs/current/sdk/python/guides/454108-python-ci.md, docs/current/sdk/python/snippets/python-ci/Jenkinsfile, docs/current/sdk/python/snippets/python-ci/actions.yml, docs/current/sdk/python/snippets/python-ci/circle.yml, docs/current/sdk/python/snippets/python-ci/gitlab.yml
first three checkboxes of #3918
tested these manually. automated testing to come.
=> CI examples

internal/mage/engine.go, internal/mage/util/util.go
Thank you @jlongtine for noticing and finding the fix!
=> ./hack/dev: export dagger binary for host platform

docs/current/sdk/nodejs/snippets/nodejs-ci/Jenkinsfile, docs/current/sdk/nodejs/snippets/nodejs-ci/actions.yml, docs/current/sdk/nodejs/snippets/nodejs-ci/circle.yml, docs/current/sdk/nodejs/snippets/nodejs-ci/gitlab.yml
cc @vikram-dagger @slumbering @crjm
=> chore: use index.mjs for file name

.github/workflows/provision.yml
Temporarily disable CI provision tests, until follow-up issue gets merged
Following remark from solomon: https://discord.com/channels/707636530424053791/1003718839739105300/1052279981373407343
cc @gerhard @sipsma
=> chore: temporarily disable provision test

README.md
remove "weekly" and add "demo" request form 
=> update community call CTA

website/docs-graphql/data/examples/queries/socket/gql.md
fixes #4174
cc @vikram-dagger @crjm
=> add toplevel socket query example

cmd/dagger/listen.go
=> cli: print complete GraphQL URL to stdout when listening

docs/current/cli/698277-index.md
=> docs: add reference to custom api clients from cli overview

sdk/nodejs/common/errors/DaggerSDKError.ts, sdk/nodejs/common/errors/DockerImageRefValidationError.ts, sdk/nodejs/common/errors/EngineSessionConnectParamsParseError.ts, sdk/nodejs/common/errors/EngineSessionConnectionTimeoutError.ts, sdk/nodejs/common/errors/EngineSessionEOFErrorOptions.ts, sdk/nodejs/common/errors/GraphQLRequestError.ts, sdk/nodejs/common/errors/InitEngineSessionBinaryError.ts, sdk/nodejs/common/errors/TooManyNestedObjectsError.ts, sdk/nodejs/common/errors/UnknownDaggerError.ts, sdk/nodejs/common/errors/errors-codes.ts
Signed-off-by: Benjamin Strasser <bp.strasser@gmail.com>
=> nodesdk/errors: added types to error names and error codes

core/container.go, core/directory.go, core/integration/directory_test.go, core/schema/container.go, core/schema/container.graphqls, core/schema/directory.go, core/schema/directory.graphqls, sdk/go/api.gen.go, sdk/nodejs/api/client.gen.ts, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py
Fixes #3167
I didn't write tests for the Container APIs because they're currently using the Directory APIs... let me know if you all think I should change that.
=> Add file/folder permissions to Directory and Container APIs

codegen/generator/nodejs/templates/functions.go, codegen/generator/nodejs/templates/functions_test.go, codegen/generator/nodejs/templates/src/type.ts.tmpl
Fixes https://github.com/dagger/dagger/issues/4258
=> fix(codegen/nodejs): make input type field generation ordered/stable

sdk/nodejs/api/test/api.spec.ts, sdk/nodejs/api/utils.ts
Details in https://github.com/dagger/dagger/issues/4257#issuecomment-1367121945
Resolves: #4257
=> fix: NodeSDK correctly solves subqueries

sdk/nodejs/api/utils.ts
Clean up code to improve performances and maintainability.
=> style: improve NodeSDK utils code

cmd/shim/main.go, core/integration/dind_test.go, project/project.go
=> setup nested session in the shim instead of the executor

internal/mage/sdk/python.go
=> Python: Update Poetry in CI

sdk/nodejs/README.md, sdk/nodejs/package.json
=> update local development section in the README

sdk/nodejs/connect.ts
Related to the issue https://github.com/dagger/dagger/issues/3952
cc @jpadams 
=> improve connect doc reference

.github/workflows/publish.yml, .readthedocs.yaml, docs/current/sdk/python/628797-get-started.md, docs/current/sdk/python/snippets/get-started/step1/test.py, internal/mage/sdk/python.go, sdk/python/src/dagger/connection.py
=> Update default python version

.github/workflows/publish-sdk-go.yml, .github/workflows/publish.yml
=> ci: avoid running publish workflows in forks

core/schema/cache.graphqls, core/schema/container.graphqls, core/schema/directory.graphqls, core/schema/file.graphqls, core/schema/git.graphqls, core/schema/host.graphqls, core/schema/http.graphqls, core/schema/platform.graphqls, core/schema/secret.graphqls, core/schema/socket.graphqls, sdk/go/api.gen.go, sdk/nodejs/api/client.gen.ts, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/codegen.py
Add context on some parameters.
Enhance explanations.
Add examples when parameters are unclear.
Related to: #4089
=> docs: improve GraphQL schema doc

internal/mage/sdk/nodejs.go, sdk/nodejs/yarn.lock
=> docs: add linting support for node snippets

README.md
Signed-off-by: kpenfound <kyle@dagger.io>
Closes https://github.com/dagger/dagger/issues/3470
=> add link to examples repo in readme

sdk/python/poetry.lock
Not using Dependabot until Poetry version is updated[^1]:
- https://github.com/dependabot/dependabot-core/pull/6302
This supersedes the following:
- https://github.com/dagger/dagger/pull/4309
Will close that after this one is merged.
[^1]: There's changes to the lock format.
=> deps(python): Package updates

core/docs/d7yxc-operator_manual.md
User was asking about connecting to podman container here: https://discord.com/channels/707636530424053791/1062413462082420757/1062415636124418058
=> Document more runner conn types.

codegen/generator/go/templates/src/object.go.tmpl, sdk/go/api.gen.go
fix https://discord.com/channels/707636530424053791/1003718839739105300/1062863448221941862
=> fix(codegen/go): pass the GQL client to the returned client

docs/current/sdk/nodejs/783645-get-started.md, docs/current/sdk/nodejs/835948-install.md, docs/current/sdk/nodejs/guides/620941-github-google-cloud.md
=> docs: Update Node.js SDK installation command

core/container.go, core/schema/git.go
- core: pipeline support for container.rootfs
- core: pipeline support for git.tree
=> Pipeline fixes for RootFS and Git

website/docusaurus.config.js
=> change posthog analytics URL to minimize ad-blockers

docs/current/sdk/nodejs/guides/620941-github-google-cloud.md
=> Add live demo link

.github/workflows/add-issues-to-backlog.yml
Attempt to solve the broken workflow, just bumped the version to the latest.
cc @mircubed
=> chore: bump version of actions/add-to-project

sdk/python/docs/conf.py, sdk/python/poetry.lock, sdk/python/src/dagger/engine/download.py, sdk/python/tests/engine/test_download.py
Related: https://github.com/dagger/dagger/pull/4440
=> deps(python): Update ruff

website/src/css/custom.scss
=> Fix code tags css in dark mode

sdk/python/src/dagger/api/base.py, sdk/python/tests/api/test_integration.py, sdk/python/tests/api/test_integration_sync.py
=> Python: Fix sequence of objects not being converted to ids

.github/workflows/test.yml
So that we can troubleshoot when logs & traces don't make sense.
- https://github.com/dagger/dagger/pull/4478
- https://github.com/dagger/dagger/pull/4340
=> Upload journal.log & comment.md as artifacts

docs/current/quickstart/349011-quickstart-build.mdx, docs/current/quickstart/593914-quickstart-hello.mdx, docs/current/quickstart/635927-quickstart-caching.mdx
This commit adds various quickstart fixes
=> Adds minor fixes to quickstart

.github/workflows/test.yml
> **Warning** Merge after https://github.com/dagger/dagger/pull/4498
This was not worth failing the `engine / test` job for:
https://github.com/dagger/dagger/actions/runs/4068033458/jobs/7006095804#step:9:38
=> ci: Pass "engine / test" job if otel-collector fails

internal/mage/engine.go
- Added entrypoint script to enable cgroupv2 nesting
=> add entrypoint to engine image

docs/current/quickstart/120918-quickstart-setup.mdx
If applied, this commit updates the quickstart example application repository URL.
Closes #4479
=> docs: Updated quickstart example repository URL

core/integration/directory_test.go
Signed-off-by: Joel Longtine <joel@longtine.io>
=> Fix TestDirectoryWithTimestamps for non-ext4 filesystems

.github/workflows/lint.yml, .github/workflows/publish-sdk-go.yml, .github/workflows/publish-sdk-nodejs.yml, .github/workflows/publish-sdk-python.yml, .github/workflows/publish.yml, .github/workflows/test.yml, Dockerfile, core/integration/container_test.go, go.mod, internal/mage/go.mod, internal/mage/util/util.go, project/goruntime.go, sdk/go/go.mod
=> bump engine and go SDK golang to 1.20

sdk/nodejs/connect.ts
=> fix: remove workdir & configPath default values.

sdk/nodejs/api/test/api.spec.ts
=> Create a test for nested arguments

sdk/python/src/dagger/engine/download.py, sdk/python/src/dagger/exceptions.py
=> Python: Add custom exception for errors during CLI download

docs/current/quickstart/628381-quickstart-sdk.mdx, docs/current/sdk/python/866944-install.md, sdk/python/README.md
=> docs(python): Update install instructions

docs/current/quickstart/593914-quickstart-hello.mdx, docs/current/quickstart/snippets/hello/main.go, docs/current/quickstart/snippets/hello/main.py
This commit fixes an error in the quickstart code snippet comments.
=> docs: Fixed quickstart code snippets

sdk/python/poetry.lock, sdk/python/pyproject.toml, sdk/python/src/dagger/api/base.py, sdk/python/src/dagger/exceptions.py, sdk/python/src/dagger/session.py, sdk/python/tests/api/test_connection_errors.py, sdk/python/tests/api/test_execute_errors.py, sdk/python/tests/api/test_integration.py, sdk/python/tests/api/test_integration_sync.py, sdk/python/tests/engine/test_cli.py
Related to #3805
Also refactored a bit from #4629 and added more tests.
=> Python: Add custom exception for establishing client connection

core/integration/remotecache_test.go
@vito let me know if this actually fixes it this time, it didn't happen after running with `-count=20` last time for me locally
=> Disable networking before spinning up engine in remotecache test.

docs/current/guides/snippets/multi-builds/build.py, docs/current/guides/snippets/private-repositories/clone.py
Changes:
- Removed catching exceptions when running as a simple script
- Replaced _rich_ with streaming engine logs to be more consistent
Improvements will be addressed in:
- #4706 
- #4707
=> docs(python): Make snippets more consistent

website/plugins/docusaurus-plugin-guides/index.js, website/src/components/molecules/guideIndex.js, website/src/css/molecules/guideIndex.module.scss, website/src/css/molecules/tag.module.scss
This will add the possibility to filter tags at the top of the guide index.
>**Warning**
>Making this a draft PR as it's possible some UX changes have to be made before reviewing.
Closes #4670
=> docs: add tag search to guide index

RELEASING.md
After going through the Engine + CLI v0.4.0 release, as well as all SDKs & docs, these improvements made sense:
- last updated badge
- new high-level diagram
- convert 👉 action items to [x] checklist items
- optimise for top to bottom consumption
The only contentious item might be the removal of post-release checks, i.e. https://github.com/dagger/dagger/pull/4461 . The manual checks are so simple - checking the `dagger version` output - that if we messed that up in our release process, we should add checks that would prevent a release from going through if that was to happen. Let's discuss this further in the PR.
=> Improve releasing instructions post v0.4.0

website/netlify.toml
=> docs: proxy embed to avoid third party errors

.github/workflows/lint.yml, .github/workflows/publish-sdk-go.yml, .github/workflows/publish-sdk-nodejs.yml, .github/workflows/publish-sdk-python.yml, .github/workflows/publish.yml, .github/workflows/test-publish.yml, .github/workflows/test.yml
Signed-off-by: Andrea Luzzardi <al@dagger.io>
=> telemetry: rotate cloud token

docs/current/543069-index.md, docs/current/cli/698277-index.md, docs/current/partials/_how_does_dagger_work.md, docs/current/quickstart/319191-quickstart-basics.mdx, docs/current/sdk/go/440319-index.md, docs/current/sdk/nodejs/722802-index.md, docs/current/sdk/python/459708-index.md
Revert "how it works" diagram back to how it was. Happy to discuss changes to our tech marketing, but I want to be consulted first.
=> Docs: fix diagram

core/integration/container_test.go, core/schema/container.go
=> fix: withRegistryAuth uses secret.Store for getting plaintext

core/integration/host_test.go, core/schema/file.graphqls, core/schema/host.graphqls, sdk/go/api.gen.go, sdk/nodejs/api/client.gen.ts, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py
Getting rid of previous secret API.
cc @shykes
=> feat!: deprecate HostVariable.secret in favor of setSecret

docs/current/guides/899944-aws-cdk-ecs.md
This commit updates the AWS CDK guide to make the pre-requisites clearer.
=> docs: updated requirements for AWS CDK guide

cmd/engine/main.go
Doesn't hurt to be more verbose here since it's not directly user facing, and can help quite a bit with debugging problems related to startup.
=> Add more debug log lines to engine start.

RELEASING.md
Make it easier to copy/paste the right commands.
I keep thinking about the automation that will be built using these docs as the source of truth.
=> Improve instructions while releasing v0.4.1

RELEASING.md, internal/mage/go.mod, internal/mage/go.sum
=> ci: bump dagger version in mage targets

RELEASING.md
This is exactly what we did - worked like a charm.
=> Improve release instructions during v0.5.0

sdk/python/src/dagger/api/base.py, sdk/python/tests/api/test_integration.py
Python implementation for:
- https://github.com/dagger/dagger/issues/3885
This using a generic implementation in the base class instead of duplicating in codegen.
=> Python: Implementation for `with_(…)` convenience

sdk/nodejs/api/test/api.spec.ts
=> tests: add additional test on chain operations

sdk/python/poetry.lock, sdk/python/pyproject.toml
=> Python: Fix dependency issue

docs/current/guides/757394-use-service-containers.md
=> docs: Added note in services guides

docs/current/guides/723462-use-secrets.md
=> docs: Added note to secrets guide

engine/cache/manager.go
Noticed a lot of these were accumulating in a long running engine I was testing (1 per minute)...
=> Fix goroutine leak in cache import.

internal/mage/util/engine.go
=> ci: set proper octal notation file permissions

internal/tui/keys.go
Added as alternative bindings with current arrows.
=> fix(tui): added h and l as alt collapse/expand bindings

docs/current/162770-faq.md
=> docs: Updated FAQ

core/gateway.go
In the code for obtaining stdout/stderr of a failed exec, we were passing the context to the deferred Release of the gateway container that is used for all the other calls. This context had a failsafe 30 second timeout so that obtaining stdout/stderr didn't inadvertently block for excessive amounts of time.
If that context ended up cancelled, the Release call would not actually happen, which meant that all the cache refs for the created container would continue to be held open in the engine even after the container fully exited.
We also were previously including all mounts in this container, including any cache mounts. If the cache mount was mode LOCKED, it was entirely possible for that timeout to be hit while the container waited for the cache mount to become available.
The end result …
=> Use background context to release gateway containers.

docs/current/guides/145912-ci.md, docs/current/guides/snippets/ci/go/actions.yml, docs/current/guides/snippets/ci/python/Jenkinsfile, docs/current/guides/snippets/ci/python/actions.yml, docs/current/guides/snippets/ci/python/circle.yml, docs/current/guides/snippets/ci/python/gitlab.yml
=> docs: Updated CI guide

internal/tui/item.go, internal/tui/vterm.go
Also fixes the scroll % indicator.
=> TUI: support PgUp/PgDn/Home/End in log output

engine/cache/manager.go
Noticed during some load tests that the engine was accumulating tons of RSS that was never released. Then noticed that buildkit's cache was full of refs that were not prunable even after all clients disconnected. This fixes one source of the leak. There's another leak happening due to an issue upstream: https://github.com/moby/buildkit/pull/3815
With this plus the upstream fix all cache refs are prunable and the engine's RSS stays much lower and a consistent value between runs.
=> engine/cache: release refs after push

RELEASING.md, internal/mage/go.mod, internal/mage/go.sum
These are the exact steps that we followed during this release.
The doc now explains why we are doing these improvements during the release.
=> Improve releasing during v0.5.1

docs/current/sdk/nodejs/783645-get-started.md, docs/current/sdk/nodejs/snippets/.eslintrc.cjs, docs/current/sdk/nodejs/snippets/get-started/step2/build.js, docs/current/sdk/nodejs/snippets/get-started/step2/build.mjs, docs/current/sdk/nodejs/snippets/get-started/step2/build.mts, docs/current/sdk/nodejs/snippets/get-started/step3/build.js, docs/current/sdk/nodejs/snippets/get-started/step3/build.mjs, docs/current/sdk/nodejs/snippets/get-started/step3/build.mts, docs/current/sdk/nodejs/snippets/get-started/step4/build.js, docs/current/sdk/nodejs/snippets/get-started/step4/build.mjs, docs/current/sdk/nodejs/snippets/get-started/step4/build.mts
This commit updates the Node.js get started guide to include additional TypeScript packages for new users unfamiliar with configuring Node.js' TypeScript support.
=> docs: Updated Node.js get started guide

auth/registry_test.go
Added a quick test to at least test the most basic functionality in `RegistryAuthProvider`.
At some point I think it would be good to test the Docker auth provider fallback and cover errors too.
Wandering if exposing `dockerAuthProvider` (turning it into `DockerAuthProvider` so that the test can override it) and allowing the test to set a mocked auth provider could work, or perhaps there's an easy way to initialize something like that in memory and cover the functionality.
Other tests could become subtests inside `TestRegistryAuthProvider`.
=> Add initial test for RegistryAuthProvider

docs/current/quickstart/730264-quickstart-publish.mdx
=> docs: quickstart, fix Go publish snippet

go.mod, go.sum
https://github.com/moby/buildkit/commit/9122e57919acf52ae4fc1f64be19b83d56b05442
=> Upgrade to buildkit commit with fix for cache ref leak.

sdk/CONTRIBUTING.md
In the interest of incremental progress, this provides the first version for #5095.
More follow-ups will come later.
=> Add SDK contribution guide

codegen/generator/functions.go, codegen/generator/go/templates/functions.go, codegen/generator/go/templates/src/object.go.tmpl, codegen/generator/nodejs/templates/functions.go, codegen/generator/nodejs/templates/src/method_solve.ts.gtpl, core/integration/container_test.go, core/schema/container.go, core/schema/container.graphqls, sdk/go/api.gen.go, sdk/nodejs/api/client.gen.ts, sdk/nodejs/api/test/api.spec.ts, sdk/python/src/dagger/api/base.py, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/codegen.py, sdk/python/tests/api/test_integration.py, sdk/python/tests/api/test_integration_sync.py
Initial implementation for https://github.com/dagger/dagger/issues/5065
Just `Container` for now, can add more types later.
=> Add `Container.sync` field to force evaluation

core/container.go, core/integration/container_test.go, core/util.go
Merge environments and labels from previous container to the new one on call to merge and build.
Resolves: #4588
=> feat: build and from keep previous configuration.

cmd/shim/main.go
=> Fix error handling in truncation notice

docs/current/guides/541047-alternative-runtimes.md
This commit explains how to use Dagger with nerdctl when invoked via lima. 
Context: https://discord.com/channels/707636530424053791/1108492190369456218
Closes DAG-1580
=> docs: Added lima+nerdctl solution to alternatives guide

cmd/engine/main.go, engine/cache/manager.go, engine/cache/service.go
=> mc: add auth token via env var to cacheservice

cmd/shim/main.go
Taking this change into its own PR, based on @sipsma comment [here](https://github.com/dagger/dagger/pull/5149#discussion_r1203311042).
PR #5149 will only impact the logic inside the `else` block here.
=> Initialize secret scrubbing logic only when secrets are set

cmd/dagger/listen.go
=> fix `dagger listen` TUI integration

engine/engine.go
Since we can't trust the XDG runtime dir to be writable due to arguably widespread OS misconfiguration, let's just use os.TempDir. Surely it's always writable, right?
The previous fix was fine, just trying to aggressively simplify this so we don't need warnings/fallbacks/etc.
=> simplify progrock socket location

internal/mage/sdk/elixir.go
* run `./hack/make sdk:elixir:bump 0.6.1`
* File `./sdk/elixir/lib/dagger/engine_conn.ex` will update to:
```diff
$ git diff
diff --git a/sdk/elixir/lib/dagger/engine_conn.ex b/sdk/elixir/lib/dagger/engine_conn.ex
index 90d151b4..415708c1 100644
--- a/sdk/elixir/lib/dagger/engine_conn.ex
+++ b/sdk/elixir/lib/dagger/engine_conn.ex
@@ -3,7 +3,7 @@ defmodule Dagger.EngineConn do
defstruct [:port, :token, :session_pid]
-  @dagger_cli_version "0.6.0"
+  @dagger_cli_version "0.6.1"
@dagger_bin_prefix "dagger-"
@dagger_default_cli_host "dl.dagger.io"
=> sdk(elixir): Implements ./hack/make sdk:elixir:bump

docs/current/sdk/go/440319-index.md, sdk/go/README.md
* Improve introduction in the Go SDK README
* Adjust corresponding docs page for consistency
=> Go SDK: improve introduction

go.mod, go.sum
Contains fix for https://github.com/moby/buildkit/issues/3921 (fix: https://github.com/moby/buildkit/pull/3937)
=> bump buildkit for 'unknown blob' fix

cmd/engine/debug.go
=> Fix metrics typo

internal/tui/tree.go
indexOf was all wrong. I blame ChatGPT. Now its implementation is similar to nth.
=> interactive tui: fix follow mode

website/src/components/molecules/guideIndex.js, website/src/css/molecules/guideIndex.module.scss
This PR increases input size and styles the guides tag search so it's easier to click and touch.
=> fix(docs): increase guides tag search size

core/host.go, core/integration/host_test.go, core/schema/host.go, core/schema/host.graphqls, sdk/go/api.gen.go, sdk/nodejs/api/client.gen.ts, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py
Add new query to GraphQL schema.
Generate Schema.
Add resolver.
Add tests
Resolves #4745
=> feat: add host file query

sdk/elixir/lib/dagger/internal/engine/downloader.ex
@wingyplus @shykes 
Add checksum_map for collect checksum data from checksum url
Add checksum verify in extract_cli
While adding the verify, I wanted to re-write a few lines, but I did not intervene because I did not understand why exactly. This pr will be a good start both for introduction to sdk and for better understanding. Please do not hesitate to give harsh feedback If there are lines or codes that you think would be better.
ref: #5330
=> elixir-sdk/verify checksum

docs/current/guides/snippets/aws-cdk-ecs/aws.go, docs/current/sdk/nodejs/783645-get-started.md, docs/current/sdk/nodejs/snippets/get-started/step3/build.js, docs/current/sdk/nodejs/snippets/get-started/step3/build.mjs, docs/current/sdk/nodejs/snippets/get-started/step3/build.mts, docs/current/sdk/nodejs/snippets/get-started/step4/build.js, docs/current/sdk/nodejs/snippets/get-started/step4/build.mjs, docs/current/sdk/nodejs/snippets/get-started/step4/build.mts, docs/current/sdk/python/628797-get-started.md, docs/current/sdk/python/snippets/get-started/step3/test.py, docs/current/sdk/python/snippets/get-started/step4a/test.py, docs/current/sdk/python/snippets/get-started/step4b/test.py
Part of https://github.com/dagger/dagger/issues/5065
=> Replace exitCode with sync in docs

sdk/python/src/dagger/api/base.py, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/codegen.py, sdk/python/src/dagger/server/_converter.py, sdk/python/tests/api/test_codegen.py
Follow up to #5300 to fix a hack.
=> Fix hacks in project commands and sync

core/container.go, core/integration/container_test.go
I went down a bit of a rabbit hole after looking into [this problem related to running dagger tests w/ magicache](https://github.com/dagger/dagger/pull/5359#issuecomment-1605009066).
That rabbit hole is an extension of previous rabbit holes when [similar issues were hit w/ Airbyte](https://github.com/airbytehq/airbyte/issues/26085) and when [trying to do an upgrade the other week](https://github.com/dagger/dagger/pull/5223#issuecomment-1569286964).
The important takeaways from the most recent investigation:
1. `vnd.docker.image.rootfs.diff.tar.zstd` has never been a thing ever outside of buildkit, afaict it's the only place that string even exists? I now think the fact that buildkit ever exports using those might actually just be a bug rather than a feature. The only zstd media type that …
=> core: improve image publish/export format compatibility.

sdk/elixir/README.md
=> sdk(elixir): fix code example in README.md not working

sdk/python/pyproject.toml, sdk/python/src/dagger/api/base.py, sdk/python/src/dagger/api/gen.py, sdk/python/src/dagger/api/gen_sync.py, sdk/python/src/dagger/codegen.py, sdk/python/tests/api/test_codegen.py, sdk/python/tests/api/test_integration.py, sdk/python/tests/api/test_response.py
Python fix for #3457
Same approach as taken in Go (https://github.com/dagger/dagger/pull/4683). There's a bit of refactoring in `codegen.py` but reviewer can focus on generated changes (`gen.py`) and tests.
Reference docs updated from:
To:
=> Python: Fix returning lists of objects
