- .github/workflows/test-integration.yml
- .github/workflows/test-universe.yml
Any cue file created in the docs triggered these tests. It shouldn't.
Contributor: @dolanor 
> Exclude docs from universe and integration tests

- pkg/universe.dagger.io/go/image.cue
- pkg/universe.dagger.io/go/test/image.cue
- pkg/universe.dagger.io/go/test/test.bats
Minor changes to the `DefaultVersion` definition in the go package.
- Change the default go version (1.16 -> 1.18)
- Hid the `#_DefaultVersion` field
- Changed the bats test name (bash -> go)
> Update go pkg DefaultVersion

- docs/use-cases/1211-go-docker-swarm.md
it was highlighting the wrong keywords (test, do)
> remove the bash syntax highlighting

- CODEOWNERS
CODEOWNERS is a tool to encode PR approval rules.
When a PR is opened, at least one code owner is required to approve it
before being merged.
It does **not**:
- Limit reviewers: Everyone is welcome and encouraged to review any PR.
But at least one CODEOWNER must approve before merging.
- Limit contributions or ownership: Every maintainer is responsible for
the entire project. CODEOWNERs are there to review PRs for
consistency.
By default, any maintainer can approve any PR. There's a couple of
exceptions for consistency/specialty:
- Core API: The core API must be consistent and changes are hard
to reverse
- Universe API: Similar to the Core API, it must be kept consistent. In
the future, we will have specialized code owners (e.g. universe/aws)
- Docs website: Requires specialized …
> ci: add CODEOWNERS

- docs/1001-install.md
As the homebrew formula also supports Linux, I suggest the following updates in the installation procedure.
See https://github.com/dagger/homebrew-tap/blob/main/dagger.rb#L29.
> Update install procedure to support Homebrew on Linux

- docs/getting-started/1200-local-dev.md
It removes the curl dependency, so it simplifies the install on Windows.
Fixes #1946
> docs: Remove curl dependency when installing on Windows

- website/package.json
- website/src/css/custom.scss
while dependabot automatically bump up docusaurus core, the package preset-classic is ignore.
> bump up docusaurus preset classic theme

- plan/task/clientfilesystemread.go
- tests/plan.bats
- tests/plan/client/filesystem/read/fs/invalid/test.cue
- tests/plan/client/filesystem/read/fs/invalid_fs_input/test.cue
- tests/plan/client/filesystem/read/fs/invalid_fs_type/test.cue
Errors out in the PreRun phase of the clientfilesystemreader task since
otherwise, dagger execution would hang
Fixes #1977
> Prevents files to be used as input of dagger.#FS

- .goreleaser.yml
This allows running Dagger in armv7 32 bit architectures.
Fixes #2007
> Adds support for 32bit armv7 devices.

- pkg/universe.dagger.io/go/image.cue
- pkg/universe.dagger.io/go/test/image.cue
This adds git to the default `go.#Image` image so that 1.18 "just
works".
Fixes https://github.com/dagger/dagger/issues/1965
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> universe: go: add git by default in go.#Image

- .goreleaser.yml
For tasks that souldn’t be in the changelog but don’t match the other stuff.
> ci: Add changelog exclusion for chores

- docs/getting-started/1200-local-dev.md
In the installer instruction for Windows it is claimed that the dagger binary is placed inside the System32 folder if permissions allow it, which seems to be no longer part of the install.ps1 script (and seems like a bad idea anyways).
> Remove incorrect installer documentation

- client/client.go
- plan/plan.go
- plancontext/context.go
- plancontext/platform.go
Query Buildkit's daemon and fetch available platform. Additionally try
to match the user's native platform if possible or fallback to
buildkit's outputs
> Automatically detect target platform based on buildkit worker

- .goreleaser.yml
If there's a change that requires migrations from users, an easy thing we can do right now is to make them clear in the changelog. In Python, I'm used to read the release notes for packages before updating them.
The convention, according to https://www.conventionalcommits.org is to add a `!` before the `:`:
- `chore!: Move packages to core`
- `feat!: Rename field X`
1. I thought about using  `break:` instead, but decided to go with the convention above in case we decide to adhere more to it later. WDYT?
2. Not sure about the title for the "other" group: _Changes_. We need to consider there will be logs without breaking changes, so it needs to make sense on its own.
3. We could also group by features and bug fixes, but I think we need to have the discipline to add these prefixes to all …
> ci: Group changelog entries for breaking changes

- pkg/universe.dagger.io/python/python.cue
- pkg/universe.dagger.io/python/test/data/helloworld.py
- pkg/universe.dagger.io/python/test/test.bats
- pkg/universe.dagger.io/python/test/test.cue
Update some API references that had fallen out of use.
Notably this no longer ran, since docker.#Run now asks for an "input" not an "image," alpine.#Image became alpine.#Build and you have to reference its output. Additionally, fix up the FIXME tag in the simplest way possible, though a better solution may exist.
> Fix broken API references in universe/python

- ci/cue/lint.cue
Regression -- we were linting only top-level files
> ci: cue linter: include all CUE files

- client/client.go
- tests/plan.bats
Before this change, if BUILDKIT_HOST was set to an invalid value that
resulted in the connection of the grpc client to the server to fail,
then deadlock occured waiting for the `eventsCh` to be closed.
This happened because the call to the buildkit client's Build method
returned an error before the provided callback was executed, which is
where the `eventsCh` gets closed.
This change places the creation of `eventsCh` inside the Build callback,
which avoids the increment of the WaitGroup and thus the deadlock in
this error path.
I realized this deadlock was the more fundamental issue behind #2000. This PR doesn't add any timeouts or extra logging as mentioned in that issue originally. I am going to update that issue with more details on whether …
> client: fix deadlock when connect to buildkitd fails

- docs/core-concepts/1221-action.md
- docs/references/1222-core-actions-reference.md
The docs **must** link to `.md` files, rather than relative HTTP path.
This lets the compiler figure out the link URLs at compile time and fail the build if it cannot be resolved.
The link "it all begins with a plan" on "Dagger Actions" was broken (https://docs.dagger.io/1221/action#integration), leading to a 404.
/cc @dagger/maintainers 
Fixes #2111
> docs: Link to markdown files

- cmd/dagger/cmd/root.go
- go.mod
fixes #1689
encounter this issue while making a review for the GitHub Action: https://github.com/dagger/dagger-for-github/pull/47
```
/opt/hostedtoolcache/dagger/0.2.6/x64/dagger do test --log-format plain
time="2022-04-13T00:09:40Z" level=warning msg="commandConn.CloseWrite: commandconn: failed to wait: signal: terminated"
time="2022-04-13T00:09:40Z" level=warning msg="commandConn.CloseRead: commandconn: failed to wait: signal: terminated"
time="2022-04-13T00:09:40Z" level=warning msg="commandConn.CloseWrite: commandconn: failed to wait: signal: terminated"
12:09AM INF actions.test.script._write | computing
12:09AM INF actions.test.image._dag."0"._op | computing
12:09AM INF actions.test.script._write | completed    duration=0s
```
for now filter out `commandConn.CloseWrite` warning …
> filter out useless commandConn.CloseWrite warning message

- docs/guides/1227-contributing.md
- docs/guides/1228-handling-outputs.md
- docs/tests/core-concepts/client/plans/output_marshal.cue.fragment
- docs/tests/core-concepts/client/plans/output_simple.cue.fragment
- website/sidebars.js
Add a guide which highlights how to handle action's outputs by writing
them to the client filesystem and using CUE's integrations to marshal
them as JSON.
cc @helderco @jpadams
> docs: Add guide to showcase handling outputs

- docs/getting-started/1200-local-dev.md
This supersedes https://github.com/dagger/dagger/pull/1998. We appreciate the contribution @sauzy34 and want to get it merged. Thank you!
> docs: Mention macOS ARM vs Intel Homebrew dagger install path diff

- docs/tests/getting-started/github-actions.yml
With the upcoming release of our GitHub Actions, `args` has been replaced with `cmds` input allowing multi dagger commands within a single step.
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
> docs: update github actions workflow example

- .github/workflows/todoapp.yml
Thanks to a great community contribution, we are improving the GitHub Actions integration further. We should probably do the same for the GitLab integration doc as a follow-up to this.
This should be merged **after** https://github.com/dagger/dagger/pull/1962. Maybe @ekinbarut wants to take a look at it 👋🏻
> ci: Deploy todoapp with dev dagger AND ALSO latest 0.2.x release

- cmd/dagger/cmd/project/init.go
- cmd/dagger/cmd/project/template.go
- cmd/dagger/cmd/project/templates/hello.cue
- tests/package.json
- tests/project.bats
Adds the ability to select a template which will create a new file
in the CWD with the template name. Templates present in the
"cmd/dagger/project/templates" directory are automatically embedded in the dagger
binary when building and then listed in the `dagger project init` help output.
Usage:
dagger project init -t <template_name>
One idea that we had while pairing on this is to eventually try
improving this UX by extending the `dagger project` command by adding
sub-commands like `dagger project templates [list, new, output, ...]`.
Pair: gerhard
> Allow to specify template when running `dagger project init`

- pkg/dagger.io/dagger/plan.cue
- pkg/dagger.io/dagger/types.cue
BREAKING CHANGE: don’t use `dagger.#Address`.
Related to #1997
> chore!: Make `dagger.#Address` private

- client/client.go
As reported on Discord
> Hello - I'm trying to use Dagger without Docker installed and instead using Buildkit running on podman. When I attempt to use BUILDKIT_HOST set as podman-container://buildkitd , I see Dagger throw errors about Error while dialing dial podman-container: unknown network podman-container . Would anyone have suggestions on things to try towards troubleshooting this? For context, I've verified buildctl is able to run okay referencing buildkitd from podman. Thanks in advance!
> enable kubernetes and podman connection drivers

- pkg/dagger.io/dagger/core/fs.cue
Defaulting to 0o600 makes the file inaccessible to `core.#Exec` actions
running with a `user` field.
Ideally `#WriteFile` should support user/group in addition to
permissions.
> core.#WriteFile: default permissions to 0o644

- docs/references/1222-core-actions-reference.md
- docs/references/1234-dagger-types-reference.md
- pkg/dagger.io/dagger/types.cue
- pkg/dagger.io/dagger/values.cue
- website/sidebars.js
Resolves #1997
About the _Data structures_ section, you shouldn't need the definitions directly, but it's useful to know which fields are there (e.g., `#ImageConfig` and `#HealtchCheck` when using the `config` field in `docker.#Set`).
> docs: Add types reference

- docs/core-concepts/1221-action.md
The Dagger `Core Concepts` > `Dagger Actions` page shows a hello world example dependent on two packages (main + hello) but this is confusing if the reader doesn't understand how packaging works.  https://docs.dagger.io/1221/action
Packaging has yet to be explained: [#2220](https://github.com/dagger/dagger/issues/2220). We should avoid showing this too early in the documentation.
> Avoid multiple packages in examples

- cmd/dagger/logger/plain.go
- cmd/dagger/logger/tty.go
- plan/runner.go
- plan/task/dockerfile.go
- plan/task/task.go
- plancontext/fs.go
- util/progressui/display.go
- util/progressui/printer.go
Creates a generic "system" group in the tty output similarly to the plain one which captures
buildkit events that report a non-dagger vertex name. This happens
currently when using core.#Dockerfile actions since Dagger delegates the
LLB generation to buildkit through it's frontend and we don't get
meaningful events that we can correlate from Dagger's side. 
Given the following dockerfile:
```Dockerfile
FROM node:10-alpine
RUN apk update
RUN some_error
```
Old output :
```
dagger do hello
[✔] client.filesystem.".".read                                                                         0.0s
[✗] actions.hello                                                                                      6.9s
0.8s
5:18PM FTL failed to execute plan: task failed: actions.hello._build: process …
```
> Improve tty error logging when buildkit vertex is unknown

- docs/faq/1232-chain-actions.md
I was confused by [this FAQ](https://docs.dagger.io/1232/chain-actions) until I realised it had misleading code. This is a tiny PR to fix the misleading code.
> docs: fixed misleading example code in FAQ

- Makefile
- ci.cue
- pkg/universe.dagger.io/go/image.cue
This moves the go unit test from the Makefile to the dagger Plan. The issue was the GCC dependency and CGO. I added build dependencies to the base image, I was tempted to add a `packages` key to `go.#Container` but I don't want to leak alpine-specific package names in the higher api (we could technically build Go apps without Alpine). Also I think it makes sense to have access to the build packages in a container image that's only used for building.
> ci: run go unit tests from the dagger plan

- ci/cue/lint.cue
So we can see/grep more clearly what is the issue from the CI log.
**Before**
```
11:42AM INF actions.lint.cue._dag."4"._exec | #22 1.983 cue fmt -s ./ci/cue/lint.cue
11:42AM INF actions.lint.cue._dag."4"._exec | #22 1.993 cue fmt -s ./ci/markdownlint/markdownlint.cue
11:42AM INF actions.lint.cue._dag."4"._exec | #22 1.994 cue fmt -s ./ci/golangci/lint.cue
11:42AM INF actions.lint.cue._dag."4"._exec | #22 1.999 cue fmt -s ./ci/shellcheck/shellcheck.cue
11:42AM INF actions.lint.cue._dag."4"._exec | #22 2.045 real	0m 1.88s
11:42AM INF actions.lint.cue._dag."4"._exec | #22 2.045 user	0m 7.36s
11:42AM INF actions.lint.cue._dag."4"._exec | #22 2.045 sys	0m 2.00s
11:42AM ERR actions.lint.cue._dag."4"._exec | failed: process "bash --norc -e -o pipefail /bash/scripts/run.sh" did not complete …
```
> ci: add lint error header in log

- cmd/dagger/cmd/root.go
follow-up #2161
forgot to also filter out `commandConn.CloseRead` in previous PR: https://github.com/dagger/dagger-for-github/runs/6092884799?check_suite_focus=true#step:3:14
```
/opt/hostedtoolcache/dagger/0.2.7/x64/dagger do test
time="2022-04-20T10:01:52Z" level=warning msg="commandConn.CloseRead: commandconn: failed to wait: signal: terminated"
10:01AM INF actions.test.script._write | computing
10:01AM INF actions.test.image._dag."0"._op | computing
10:01AM INF actions.test.script._write | completed    duration=0s
10:01AM INF actions.test.image._dag."0"._op | completed    duration=1.7s
10:01AM INF actions.test.image._dag."1"._exec | computing
...
```
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
> filter out commandConn.CloseRead warning log message

- docs/administrator/1013-operator-manual.md
Adds documentation for podman and kube-pod to operator-manual. Resolves #1959
Signed-off-by: Jonathan Dickinson <jdickinson@cmgx.io>
> docs: add connhelper instructions

- docs/faq/index.md
Quick fix for FAQ link URLs that currently have `/faq` in them, which is causing broken links. This commit removes that string in the URL.
> Fix FAQ broken links

- README.md
This pull request fixes the contributing link in the `README.md`. The contributing guide has been moved to the documentation website by https://github.com/dagger/dagger/pull/2134
Signed-off-by: kevinpollet <pollet.kevin@gmail.com>
> docs: Fix contributing guide link in README

- docs/tests/guides/container-images/multi-stage/dagger.cue
- docs/tests/guides/container-images/multi-stage/src/go.mod
- pkg/universe.dagger.io/go/test/build.cue
- pkg/universe.dagger.io/go/test/data/hello/go.mod
- pkg/universe.dagger.io/go/test/data/hello/main.go
They create conflict in gopls (for the govim plugin)
> fix: rename duplicates Go modules

- cmd/dagger/cmd/do.go
Handles the action flags parsing separately so we don't have to call
`Parse()` multiple times on the main FlagSet as it has some issues with
StringArrays as described here https://github.com/spf13/pflag/issues/244
Also fixes #2240 
cc @jlongtine
> Avoid duplicate StringSlices when parsing flags

- compiler/build.go
- compiler/compiler.go
- compiler/value.go
- pkg/dagger.io/dagger/core/exec.cue
- pkg/dagger.io/dagger/core/fs.cue
- pkg/dagger.io/dagger/core/git.cue
- pkg/dagger.io/dagger/core/http.cue
- pkg/dagger.io/dagger/core/image.cue
- pkg/dagger.io/dagger/core/secrets.cue
- pkg/dagger.io/dagger/plan.cue
- pkg/universe.dagger.io/alpine/test/test.cue
- pkg/universe.dagger.io/aws/cli/cli.cue
- pkg/universe.dagger.io/docker/run.cue
- plan/plan.go
- plan/validate.go
- plancontext/fs.go
- tests/plan.bats
- tests/plan/concrete/definition.cue
- tests/plan/concrete/docker_image.cue
- tests/plan/concrete/fs.cue
- tests/plan/concrete/multitype.cue
- tests/plan/concrete/reference.cue
- tests/plan/concrete/task.cue
- tests/plan/concrete/yarn.cue
- tests/plan/do/actions.cue
- tests/plan/do/do_flags.cue
- tests/plan/with/with.cue
Related to #613
This attempts to validate plan concreteness (e.g. missing fields) before execution.
The objective is to provide nicer errors when fields are missing: instead of complaining about low-level task fields (e.g. `foo._bar._exec.input`), this will provide the "source" error (e.g. `foo.source`).
There are some heuristics in place:
- Recursively walk the entire tree (avoiding definitions and optional fields)
- Scalars (`string`, `bool`, etc): Make sure they're concrete, or have default values, or is a reference
- Core types (`#FS`, `#Secret`, etc): Make sure they're references
- Core actions (e.g. `core.#ReadFile`): validate, but skip generated fields
Given this config:
```cue
#Test: {
required: string
_op: core.#Pull & {
source: required
}
}
dagger.#Plan & {
actions: test: #Test …
```
> validate plan concreteness before execution

- plan/task/writefile.go
Now could show clear errors why contents is not set
```shell
11:20AM FTL system | failed to execute plan: task failed: actions.k3s.amd64._airgap._export._kubepkg_spec_json_file: kubepkg.json: WriteFile contents is not set:
actions.k3s.amd64._airgap._export.spec.spec.manifests.registry.deployments."container-registry".spec.template.spec.containers.0.image: invalid interpolation: unresolved disjunction "latest" | string | "93f3e3d" (type string):
components/kubepkg/registry.cue:43:21
```
> fix: should show cue error details when WriteFile contents not set

- ci.cue
Without this change my PR CI runs are getting errors like these: https://github.com/dagger/dagger/runs/6164267748?check_suite_focus=true
> ci: fix typo in bin output field

- pkg/dagger.io/dagger/core/image.cue
- pkg/universe.dagger.io/docker/pull.cue
- plan/task/pull.go
This exposes the LLB pull policy to `core.#Pull`. This allows the build script to explicitly indicate whether a new image should be downloaded. Only `preferLocal` is tested, as the other two options are not deterministic. Example:
```cue
core.#Pull & {
source: "myimage:latest"
resolveMode: "preferLocal"
}
```
The three options are `default`, `preferLocal`, and `forcePull`.
Signed-off-by: Jonathan Dickinson
> feat: add resolveMode for `core.Pull`

- .github/workflows/dagger-ci.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-universe.yml
There was a typo in `Sets env var on push to main` on condition statement.
Branch was checked with `github.base_ref == 'main'` but the correct condition
was `github.ref == 'refs/heads/main'`
CI should now works on main and in PR
Related to: #2305 
Tested on:  https://github.com/TomChv/jsonrpc2/runs/6173846049?check_suite_focus=true
> ci: fix cache key creation on main

- solver/solver.go
- tests/plan.bats
- tests/plan/client/filesystem/write/test.cue
This is a simple fix for the issue of logs being duplicated when an
export is performed. The issue is caused by Buildkit's behavior of
"backfilling" newly connected clients on the progress so far of vertices
referenced by their build. This addresses it in the simplest way
possible by just filtering out progress log events from these separate
builds.
This works but is fragile. It works because we currently always set
Evaluate to true when running solves, which means that any progress logs
will already have been sent to the main solve channel and any that are
sent to the separate channel created for the export must be duplicates.
If we ever want to enable Evaluate being set to false, we will need a
different fix. I wrote that fix out, but it's a tangled web of
synchronization and to fully …
> solver: fix duplicate logs on export

- cmd/dagger/logger/tty.go
I hit this issue when I was manually testing #2294.
For more details, see : https://github.com/dagger/dagger/issues/1728#issuecomment-1109727011
By adding a condition when `maxLines` goes negative, I didn't hit that issue anymore. 
Resolves: #1728
> Fix tty log panic issue

- .goreleaser.yml
This excludes `build(deps-dev)` in addition to `build(deps)` commits
from the changelog. `deps-dev` affect yarn (`package.json`) dev
dependencies (i.e. the docs website)
> ci: goreleaser: exclude `deps-dev` commits from changelog

- client/client.go
- plan/task/dockerfile.go
- plan/task/pull.go
- plan/task/util.go
This change replaces the use of `@<component name>@-<name>` for tracking
which cue fields progress status updates from Buildkit should be logged
with. Now, the ProgressGroup metadata field is used to track the
component part (i.e. cue field) and the vertex name can just be the name
again.
This fixes the issue where Dockerfile builds showed up under the
"system" group. It also is more performant as statuses don't all need to
be parsed anymore.
The only exception that remains are the progress logs written for
ResolveImageConfig calls. This Buildkit API is missing support for
ProgressGroup right now, so it still uses the '@%s@' mechanism as
before. This can be fixed once Buildkit has been updated upstream to
support the field.
This exception includes our own call to ResolveImageConfig but …
> Use progress group to track components of vertices.

- client/client.go
- tests/tasks.bats
- tests/tasks/newsecret/newsecret.cue
Before this, a secret which ended up being set to an empty string would
still be "redacted" using strings.ReplaceAll, which has the (surprising)
behavior of putting the replacement chars around+between every char in
the string being replaced.
This meant that if you ended up with an empty secret, then all your logs
would look like `***t***h***i***s***`.
This change just skips redacting if the string is "". I also considered
whether it should be an error for a secret to be an empty string, but
that's backwards incompatible and I can imagine scenarios where users
could want that to not be an error. E.g. they try to read a secret from
somewhere, it ends up empty and they then fallback to a secret from a
different source.
Noticed this while working …
> Don't redact secret if it's an empty string.

- pkg/universe.dagger.io/bash/bash.cue
Revert #2289
Flags were broken because they are inserted between `name` and `args`. To ignore an entrypoint from image config, just override with an empty entrypoint. Don’t move the command `name` there.
> Remove entrypoint from `bash.#Run`

- cmd/dagger/logger/tty.go
- plan/task/task.go
This adds a group counter used to mark log groups as completed.
The problem is when having `actions.test._a` and `actions.test_b`, as
soon as one completes it will mark the entire `actions.test` as
completed.
This can be repro'ed using our own CI (e.g. `dagger do test`)
> tty logger: fix group status for hidden sub-actions

- cmd/dagger/cmd/common/common.go
- tests/plan.bats
Before this change, we were using code from the buildx repo that
silently removed GHA from cache options if the GHA token and/or url were
not set. This made it very non-obvious that a mistake was being made,
with the only evidence being that cache import/export just never ran.
This commit updates to use the buildctl code for parsing cache options
(which is better since it is tied to the version of buildkit we are
using, unlike buildx). We need to layer the GHA token+url checks on top
ourselves because buildctl lacks those checks, but that's fairly
straightforward.
Noticed this while working on some simplifications to our CI caching
> cache: Error out if GHA used w/out token or url.

- plan/runner.go
- plan/task/dockerfile.go
- plan/task/task.go
After the changes introduced by sipsma in
https://github.com/dagger/dagger/commit/86e798a36bc93d19ac33631d0cb466ab771fa164
Dockerfile logs are now displaying correctly and don't require the
system hack. Additionally, I'm removing the CanTransition method and
going back to the previous behavior since it's not required anymore and
it also introduces a bug when displaying logs for actions that contain
hidden sub-actions.
> Revert specific case to handle dockerfile actions

- website/docusaurus.config.js
- website/src/css/custom.scss
“system” fonts matches what the current OS uses, so it can be a comfortable look.
Reduce main container width to improve readability
Signed-off-by: user.email <jf@dagger.io>
> use default system font

- .github/workflows/dagger-ci.yml
- .github/workflows/lint.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-universe.yml
- pkg/universe.dagger.io/package.json
- tests/package.json
If an error happened, the buildkitd logs could be helpful in debugging.
Trying to debug the `failed to execute plan: error detecting platform failed to list workers: Unavailable: connection closed before server preface received` error we've been getting.
> ci: print Buildkitd logs on failure

- pkg/universe.dagger.io/x/solomon@dagger.io/yarn/test/data/bar/package.json
- pkg/universe.dagger.io/x/solomon@dagger.io/yarn/test/data/foo/package.json
- pkg/universe.dagger.io/x/solomon@dagger.io/yarn/test/test.bats
- pkg/universe.dagger.io/x/solomon@dagger.io/yarn/test/test.cue
- pkg/universe.dagger.io/x/solomon@dagger.io/yarn/yarn.cue
An experimental alternative to the official `yarn` package. This is based on my work spinning out and cleaning up [our todoapp example](https://github.com/dagger/dagger/tree/main/pkg/universe.dagger.io/examples/todoapp). For now, that work is happening [on a personal repo](https://github.com/shykes/todoapp). This package is extracted from that repo, with some light clean up + tests.
> Experimental: improved yarn package

- pkg/universe.dagger.io/package.json
- tests/package.json
- util/buildkitd/buildkitd.go
Before this, there was a race condition where parallel dagger clients
could race while checking+starting buildkitd, which sometimes lead to
one removing the buildkitd container created by the other.
Now a lock file is used to ensure the process of checking+starting
buildkitd is transactional.
This doesn't fix the case where dockerd is remote and clients are
running on parallel machines, but that's more obscure and much tougher
to fix as dockerd doesn't appear to have any mechanisms for idempotently
creating a container.
The lock file is under ~/.config/dagger for now. Technically, the
correct place to put this according to the FHS would be /var/lock, but
in my experience /var/lock doesn't always exist and I want to avoid
having to create a directory under /var if possible for now.
Also, …
> client: use lock file to dedupe buildkitd creation.

- cmd/dagger/cmd/do.go
- cmd/dagger/logger/tty.go
- plan/plan.go
- plan/runner.go
- plan/task/task.go
Fixes https://github.com/dagger/dagger/issues/2299
Related to https://github.com/dagger/dagger/issues/2331
This adds an experimental `--dry-run` **experimental** flag to `dagger do` that doesn't actually execute tasks. Can be used to validate the plan.
```console
$ dagger do build --experimental --dry-run
[✔] client.filesystem.".".read
[✔] actions.build.go.container
[✔] actions.version
[✔] client.platform
[✔] client.filesystem."./".read
[✔] actions.build.docker
[✔] actions.build.go.container.export
[✔] client.filesystem."./bin".write
```
> experimental `do --dry-run` mode

- client/client.go
- pkg/dagger.io/dagger/core/exec.cue
- plan/task/exec.go
- solver/container.go
- solver/solver.go
- tests/tasks.bats
- tests/tasks/exec/start_stop_exec.cue
This adds a new task type called AsyncExec which has a similar interface
as Exec, but unblocks once the exec has started rather than waiting for
it to complete. A separate type, StopAsyncExec, can be used to stop it
explicitly. If it isn't stopped, then it will be killed once the dagger
client shutsdown.
This is intended for creating ephemeral services used by other tasks in
the DAG, such as a DB against which tests can be run in different tasks.
AsyncExecs cannot output state and any state they create while running
will be thrown away once the DAG finishes executing. The only exception
is if they use a shared cache mount, in which case state will be applied
to the cache mount and accessible by other Execs, async or not.
There is currently an issue with Buildkit where if the dagger client …
> Support for async execs.

- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/apply.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/destroy.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/fmt.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/image.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/init.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/plan.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/run.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/test/data/resource.tf
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/test/test.bats
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/test/test.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/validate.cue
- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/workspace.cue
Signed-off-by: Ezequiel Foncubierta <ezequiel@foncubierta.com>
I know there is another contribution for a Terraform package ([#2110](https://github.com/dagger/dagger/pull/2110)), but this one we are currently using and implementing at work, and supports a lot more features. The approach is similar to Nico's implementation, so feel free to merge it into his package, or the other way around, if necessary.
There is a `terraform.#Run` action to wrap the Terraform command and run it within the official Terraform container image, from Hashicorp. You can set the Terraform command you want to run (i.e. plan, apply), the arguments (i.e. -var-file, -var), and environment variables. For common environment variables or arguments, there is a field in `terraform.#Run` you can use. For example, the …
> universe: Add Terraform package

- docs/guides/1230-permanent-cache.md
- docs/guides/1230-persistent-cache.md
- docs/tests/guides/persistent-cache/build.cue
- docs/tests/guides/persistent-cache/go.mod
- docs/tests/guides/persistent-cache/main.go
- website/sidebars.js
Add documentation on export cache, it still requires improvement and work before merge but local cache is complete
> docs: Add documentation on local cache export

- pkg/universe.dagger.io/aws/test/test.bats
- pkg/universe.dagger.io/docker/test/test.bats
- pkg/universe.dagger.io/go/test/test.bats
- pkg/universe.dagger.io/x/contact@kjuulh.io/rust/test/test.bats
- pkg/universe.dagger.io/x/olli.janatuinen@gmail.com/dotnet/test/test.bats
- tests/plan.bats
- tests/tasks.bats
Even though we export to GHA using per-test scopes, there are often
multiple invocations of dagger do within a single test, each of which
will use the same export target and thus overwrite each other's cache
manifests.
This meant that we would pay the price to export cache (quite expensive
for large blobs), eat up our bandwidth limit uploading that cache
(causing more throttles) and then never actually reuse the cache
because the manifest got overwritten.
For one example, the ./container.cue test in the go universe package
would take ~8 seconds to execute w/out cache hits, but then spend ~30
seconds exporting cache. If you run the test on its own in GHA so that
the cache manifest doesn't get overwritten, it will only take 3 seconds
to run. So in this single test case we were wasting ~37 …
> ci test: split each dagger do to own test name

- ci.cue
Speeds up CI considerably.
/cc @marcosnils @crazy-max 
I did see the history of this here https://github.com/dagger/dagger/pull/2288#pullrequestreview-951005783 but I didn't quite understand.
We were ending up uploading the context twice with different excludes, the other upload not excluding `node_modules` which is pretty massive
> ci: use same source everywhere

- plan/plan.go
When specifying actions with quoted identifiers in the plan such as:
actions: "build-image": _
The help of dagger do will be:
Available Actions:
build
"build-image"
...
Which is a bit strange for a CLI action.
This patch will try to unquote action names if they are.
Signed-off-by: Jean-Philippe Braun <eon@patapon.info>
> plan: unquote actions names

- pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/apply.cue
- pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/kubectl.cue
- pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/apply.cue
- pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/data/hello-pod/hello.yaml
- pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/kubectl.cue
Related to #1951
- Add `#Kubectl`
- Add `#Apply`
- Add tests for both
```shell
dagger do -p ./apply.cue test apply url           
[✔] [✔] actions.test.apply.url                                                                                                                                        
[✔] actions.test.apply.url                                                                                                                                        0.7s
[✔] client.filesystem."./kubeconfig".read                                                                                                                         0.0s
kubectl get pods                       
NAME          READY   STATUS             RESTARTS     AGE
hello-world   0/1     CrashLoopBackOff   1 (8s ago)   9s
```
See issue …
> universe: Add kubernetes package

- .gitignore
- Makefile
- ci.cue
- ci/bats/bats.cue
- ci/cue/lint.cue
- tests/project.bats
- This PR moves all the bats tests in the `./tests` dir to the ci.cue dagger plan
- Yarn is not needed anymore
- It adds a new constraint which is that all integration tests must be self-contained (cannot call files outside of `./tests`) - only one test was using an external file, I had to disable it
- The speed is the same as `make core-integration`, we don't lose any performance (at least from my local tests)
The next step is to port universe tests and find a way to parallelize without `parallel`, it should speed things up.
> ci: move integration tests from yarn to dagger plan

- .github/workflows/test-gitpod.yml
- .gitpod.Dockerfile
- .gitpod.yml
- .vscode/settings.json
- ci.cue
- ci/gitpod/test.cue
Signed-off-by: Berry Phillips <berryphillips@gmail.com>
Closes #2347
This environment includes all Gitpod supported languages and tools, as well as some additional terminal tools that are popular.
I went back and forth on using the full base image vs. the slimmer Go image. The full image contains all supported languages and tools - including Docker ([see here](https://github.com/gitpod-io/workspace-images/tree/main/chunks)) - whilst the Go image contains just Go. Using a custom Docker file to install Docker and other desirable tools just adds to load times and complexity. I also think there is merit in having other languages and tools available to devs in the environment. So, I opted for the full image.
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#htt …
> feat: add Gitpod support

- pkg/universe.dagger.io/docker/run.cue
- pkg/universe.dagger.io/docker/test/run.cue
`docker.#Run` can use `export` field to export files or directories from the
container.
With this commit, it will also be possible to export `#Secret`.
This will simplify action, like onepassword in #2395.
Resolves #2428
> feat: export secrets with `docker.#Run`

- cmd/dagger/cmd/project/update.go
- mod/file.go
- mod/mod.go
- mod/require.go
Fixes https://github.com/dagger/dagger/issues/2413
I've been assuming that:
1. `dagger project update` installs both built-in and external packages
2. When installing an external package that's already in `dagger.sum` the checksum is being checked
It's how I think it should work and both turned out be wrong, as I've realized in:
- https://github.com/dagger/dagger/issues/2315#issuecomment-1119706942
- **`dagger project update`**
- Copies built-ins from binary to `cue.mod/pkg`
- Does not install external packages
- **`dagger project update -u`**
- unreachable code
- checksum not being checked when installing a package with a version that matches `dagger.mod`
- Install both built-in and external packages in `dagger project update`
- Recover `dagger project update -u` which updates all …
> fix: Course correct on `project update` consistency

- ci.cue
The DAGGER_CACHE_{FROM,TO} env vars are set by a GHA step and
previously were just passed transparently to our integ tests. However,
after updating those tests to run in dagger, they were not being passed
along anymore.
This just updates ci.cue to explicitly pass them to the integ test
invocation.
In the long-term, it would probably be better to move the setting of
these env vars from a GHA step to within ci.cue. However, right now
since porting the universe tests to run inside dagger is still WIP it's
probably cleaner to just leave that in GHA rather than maintain it in
two places. Once everything's in dagger, it can migrate to ci.cue.
cc @samalba
> ci: Pass cache env vars through to integ tests.

- docs/guides/1238-project-file-organization.md
- docs/guides/1239-making-reusable-package.md
- website/sidebars.js
Fixes #2220
Fixes #2186
Fixes #2340
Doc explaining how to install/update dagger/external packages.
It contains 4 docs all inter-related. This should give our users enough knowledge on the subject to be autonomous
> docs: splitting a dagger plan / exporting packages

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/post-install.sh
- docs/guides/1227-contributing.md
Signed-off-by: Berry Phillips <berryphillips@gmail.com>
Closes #2216
The configs are auto-generated by Visual Studio Code and I have added additional configuration to support the basic needs of this repository. I added a section in the FAQ for this. I don't know if that's the best place or if there should be a dedicated doc for this 🤷🏻‍♂️
Spin up a new Codespace from my branch and ensure the following:
* Visual Studio Code loads without errors or warnings
* The `dagger` and `cue` commands are available in the terminal and are the correct versions (`dagger` should be compiled from the branch source and `cue` should be the same version as specified in `go.mod`)
* `.cue` files have syntax highlighting and can be auto formatted
* You can run dagger commands that interact with buildkit
> feat: add GitHub Codespaces support

- docs/getting-started/1200-local-dev.md
On the Getting Started article [CI/CD in your local dev](https://docs.dagger.io/1200/local-dev), running the `git clone` command on Windows may yield a `Permission denied` error (it did for me). I appended a short note to the tip under that command telling the reader to run their terminal with elevated privileges.
Signed-off-by: Gyen Abubakar <indehyde@gmail.com>
> docs: Bypass `Permission denied` error on Windows when cloning the dagger repo

- ci/gitpod/test.cue
More recent versions of git include extra safety checks on the owner of
directories before doing any operations on them. This meant that various
calls to git would fail due to being copied from the host, where the
source code is most often not owned by root (the user in the container).
This fixes the issue by just telling git it's okay to use the /src
directory anyways.
> gitpod: mark /src directory as safe to use

- pkg/universe.dagger.io/x/berryphillips@gmail.com/onepassword/example/plan.cue
- pkg/universe.dagger.io/x/berryphillips@gmail.com/onepassword/onepassword.cue
- pkg/universe.dagger.io/x/berryphillips@gmail.com/onepassword/read.cue
- pkg/universe.dagger.io/x/berryphillips@gmail.com/onepassword/read.sh
Signed-off-by: Berry Phillips <berryphillips@gmail.com>
This adds support for pulling secret values from 1Password vaults. Requires 1Password subscription and currently only supports reading single secrets. Future updates would provide more flexibility in the types of data returned (e.g. multiple secrets).
> feat: Add 1password package

- pkg/universe.dagger.io/x/cpuguy83@gmail.com/apt/install.cue
- pkg/universe.dagger.io/x/cpuguy83@gmail.com/apt/test/test.bats
- pkg/universe.dagger.io/x/cpuguy83@gmail.com/apt/test/test.cue
This packages is fairly similar in interface to the alpine package.
Some specific features of this over a standard ubuntu install:
1. Configured to cache packages
2. Stores apt cache in cache mounts
3. For the purposes of installing packages specified, it undoes some of
the built-in apt configs that help keep the image smaller since these
are not needed when using cache mounts and messes up the cache.
4. Some optimizations so that `apt-get update` is only run when the apt
cache is older than 60 minutes (or non-existent).
> feature: Add apt package to universe

- Makefile
- pkg/universe.dagger.io/package.json
This adds a makefile `UNIVERSE_TESTDIR` variable which, when set, will
be passed to `find` to filter the tests.
Example:
```
make universe-test UNIVERSE_TESTDIR=x
```
This will filter out anything under under the `x` dir in universe.
One can also set something like `UNIVERSE_TESTDIR=x/<email>` to test
only packages under a certain author or just `UNIVERSE_TESTDIR=alpine`
to test the main alpine pacakge.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
> feature: Add ability to filter universe tests

- analytics/analytics.go
- analytics/git.go
- analytics/git_test.go
- cmd/dagger/cmd/common/track.go
- cmd/dagger/cmd/do.go
- docs/learn/tests/helpers.bash
- pkg/universe.dagger.io/bats_helpers.bash
This is to avoid confusion with telemetry data (e.g. we need to use the package name `telemetry` for other stuff)
/cc @marcosnils @gerhard @shykes
> rename telemetry to analytics

- pkg/universe.dagger.io/yarn/test/test.cue
- pkg/universe.dagger.io/yarn/yarn.cue
- tests/plan/validate/concrete/yarn.cue
This is a rewrite of the official yarn package. It is based on my experimental version (`universe.dagger.io/x/solomon@dagger.io/yarn`).
NOTE: this PR depends on #2480 , please merge that first.
Improvements include:
* Usable by the example todoapp plan (which includes a custom inline implementation with hacks). See #2482
* More granular API
* `#Script` to run a yarn script (`yarn run ...`)
* `#Install` to install dependencies (`yarn install`)
* `#Command` to run any command (`yarn ...`)
* Proper use of yarn cache, configurable with project name
* App source code is mounted instead of copied (more efficient)
* Action container can be customized, including with custom image (to run a custom `yarn` binary)
* Tests are improved and self-contained (use `core.#Source`)
Note: one small breaking …
> Universe: new and improved yarn package

- Makefile
For reasons that are not clear to me at this time, when using the
dagger-debug binary to run universe tests, the new yarn test is
incredibly slow and usually times out after 30 minutes. But when using
the default dagger binary, it's relatively fast.
This needs to be understood better, but for now, running the universe
tests with the default binary will unblock our CI (which currently fails
on this yarn test consistently).
---
@shykes The timeout you were getting in your PR for the new yarn package has continued and is causing all PRs rebased on it to fail. After trying a few things I finally noticed that I could reproduce the timeout when I ran with the `dagger-debug` binary locally. This is really really weird to say the least, but switching …
> ci: use prod dagger binary in universe tests

- Makefile
- ci.cue
- ci/bats/bats.cue
- pkg/universe.dagger.io/age_key.txt
- pkg/universe.dagger.io/bats_helpers.bash
- pkg/universe.dagger.io/secrets_sops.yaml
This is a follow-up of PR #2284
It adds integration tests for:
- documentation
- universe packages
Closes #1522
> ci: moving universe and docs integration tests to the dagger CI plan

- .github/workflows/test-experimental-universe.yml
- Makefile
- ci.cue
- pkg/universe.dagger.io/package.json
Closes #2375 
A new workflow has been created to run the experimental packages "x" inside "universe.dagger.io".
This workflow is named `test-experimental-universe.yml` and its based on `test-universe.yml`.
The `package.json` in the "universe.dagger.io" folder has been modified to add another script to only test the experimental packages and the original "test" script now ignores the tests in folder "x".
Main `Makefile` has been modified to add a new task for this.
After reviewing and merging this PR when all is ready, we need to ensure that in the repo settings, in "Branch protection rules", the "Status checks that are required" does not contain this workflow, so PRs can be merged when this tests fail:
Signed-off-by: piraces <raul.piraces@gmail.com>
> ci: Split Experimental tests from Universe tests

- util/buildkitd/buildkitd.go
This will provide us with much more information that can be helpful for
debugging buildkit related problems. I don't expect that many users are
looking at these logs anyways, so I don't think there is much downside
to including extra information there.
> Enable debug logs for the default buildkitd-worker.

- docs/getting-started/1200-local-dev.md
- docs/getting-started/1240-install.md
- website/sidebars.js
Closes #2129
New page will be available at https://docs.dagger.io/install
> Standalone install docs page

- cmd/dagger/cmd/do.go
- telemetry/context.go
- telemetry/event/action.go
- telemetry/event/event.go
- telemetry/event/event_test.go
- telemetry/event/log.go
- telemetry/event/run.go
- telemetry/telemetry.go
This defines:
- Strongly typed, versioned telemetry events
- Event format (base properties and event-specific properties)
- A few events as example
- Contextual plumbing to be able to push telemetry events from anywhere
- **NOTE**: this defines the plumbing and API for typed events, it's not actually pushing anything
Example to send an event:
```go
// telemetry is available through the context (just like the logger)
tm := telemetry.Ctx(ctx)
// pushing a (strongly typed) event
tm.Push(ctx, event.ActionFailed{
Name:  v.Path().String(),
Error: err.Error(),
})
```
The event format is as follows:
```json
{
"name": "action.failed",
"data": {
"action_name": "actions.test.integration.core",
"error": "command yarn failed with exit code 123"
},
"engine": {
"id": "XXX",
"version": "devel", …
```
> telemetry: event type system

- pkg/universe.dagger.io/docker/image.cue
- pkg/universe.dagger.io/docker/test/image.cue
This adds a premade `FROM SCRATCH` image to the docker package. 
```cue
#Scratch: #Image & {
rootfs: dagger.#Scratch
config: {}
}
```
The idea came from @helderco in [this discussion](https://github.com/dagger/dagger/discussions/2517#discussioncomment-2828726). I personally find it helpful, and think it could be good to have in the package.
It's useful in builds like this:
```cue
_build_docker: docker.#Build & {
steps: [
docker.#Copy & {
input: docker.#Scratch & {}
contents: _build_exe.export.directories."/server"
dest: "/"
},
...
]
}
```
Or, you can make it into a first build step like:
```cue
_build_docker: docker.#Build & {
steps: [
{output: docker.#Scratch&{}},
...
]
}
```
Sorry that I didn't add a test, but I am not really sure how to do it. In real life, I just check that the image …
> Add `docker.#Scratch` image

- docs/core-concepts/1203-client.md
- docs/core-concepts/1213-dagger-cue.md
- docs/references/1222-core-actions-reference.md
- docs/tests/core-concepts/client/plans/file_export.cue
- pkg/dagger.io/dagger/core/fs.cue
Fixes #2249
I ended up making the updates to the client docs since it seems more important there. The handling outputs guide is mostly focused on exporting what should always be plain text data; the most relevant section is at the end and links to the client docs anyways.
Preview here: https://deploy-preview-2526--devel-docs-dagger-io.netlify.app/1203/client
> Clarify how to safely export binary data in docs.

- pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/kustomize.cue
- pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/kustomization.cue
Add experimental `#Kustomize` to experimental kubernetes package.
This definition handle `url`, `directory`, `inline` and `manual` configuration.
> feat(universe): add experimental kustomization

- website/src/css/custom.scss
Quoted text is barely visible in dark mode: https://docs.dagger.io/1226/coding-style#use-top-to-match-anything
This fix makes the text white as the rest of the body.
> website: make quotes visible in dark mode

- pkg/dagger.io/dagger/core/exec.cue
- plan/task/exec.go
- solver/container.go
- solver/solver.go
- tests/tasks.bats
- tests/tasks/exec/start_stop_exec.cue
This adds a new core.SendSignal task that enables arbitrary signals to
be sent to an async Start exec. It also adds related support to
core.Stop for specifying a timeout to wait for the exec to exit on its
own before sending SIGKILL.
The main goal here is to support ending Start execs gracefully instead
of being forced to always just SIGKILL them as part of core.Stop. It
should be useful in general for any other use cases that call for
signals to be sent to these execs (i.e. SIGWINCH for future tty
support).
Among other things, this is needed to support running Jaeger via
core.Start (without a graceful stop, its data gets corrupted).
> Support signaling core.Start execs.

- cmd/dagger/cmd/do.go
- cmd/dagger/logger/cloud.go
- telemetry/telemetry.go
Base64 encodes the plan using the %#v fmt.State into a `plan` logger
key.
Additionally moved the "running plan" event after the plan has been
evaluated to avoid unecessary logging.
Last change has been grouping all environment attributes into an
`environtment` key so we can dynamically add fields later.
> Initial support for logging the plan

- pkg/universe.dagger.io/x/david@rawkode.dev/pulumi/pulumi.cue
- pkg/universe.dagger.io/x/david@rawkode.dev/pulumi/up.sh
This adds support to the pulumi package for obtaining stack outputs, which is very useful for getting the values of resources created by pulumi, e.g. an AWS Lambda URL.
There also appears to have been a typo in up.sh in the pulumi package where a
non-existent env var "STACK_NAME" was referenced. This fixes it to what
was likely intended, "PULUMI_STACK".
> x/pulumi: add support for stack outputs 

- cmd/dagger/logger/plain.go
Changes log level field names:
"FTL" -> "FATAL"
"DBG" -> "DEBUG"
...
fixes #2079
> fix: make log level field names explicit

- pkg/universe.dagger.io/docker/pull.cue
Logs will now show:
```
6:59PM INF actions._alpine._dag."0"._pull | completed duration=3.7s
```
rather than the less self-evident
```
6:59PM INF actions._alpine._dag."0"._op | completed duration=3.7s
```
Resolves #2536
> fix: rename _op to _pull for better log UX

- pkg/universe.dagger.io/x/ezequiel@foncubierta.com/terraform/run.cue
This PR adds the "always" field to terraform.#Run, which will be passed through to its internal usage of docker.#Run.
> Add 'always' field to terraform.#Run

- docs/guides/logdebug/1241-dagger-cloud-debugging.md
Fixes https://github.com/dagger/dagger.io/issues/432
> docs: move dagger cloud under logdebug docs section

- CONTRIBUTING.md
This copies the line about checking with maintainers before pursuing
large changes from the website to our CONTRIBUTING.md. This is a
very important point to emphasize, so it doesn't hurt to make it clear
in as many places as possible.
> Add blurb about large changes to CONTRIBUTION.md

- pkg/universe.dagger.io/alpha/go/golangci/lint.cue
- pkg/universe.dagger.io/alpha/go/golangci/test/data/hello/go.mod
- pkg/universe.dagger.io/alpha/go/golangci/test/data/hello/main.go
- pkg/universe.dagger.io/alpha/go/golangci/test/lint.cue
This PR adds GolangCI linter to alpha universe.
@jpadams originally suggested to add it under `universe.dagger.io/alpha/go/lint.cue`, but Go has a plethora of lint tools (including the now deprecated, but official golint), so it didn't seem fair to make golangci THE linter and therefor I moved under a subdirectory.
Let me know what you think.
> feat: add golangci to alpha universe

- docs/guides/concepts/1241-docker.md
> docs: Improve explanations in the docker guide's export admonitions

- docs/guides/logdebug/1241-dagger-cloud-debugging.md
This is not necessary anymore as the engine will always send events once
authenticated
> docs: remove log-level insturctions for dagger cloud

- go.mod
This broke github workflows, from #2290.
> fix: reverse `go.mod` change in merged PR

- docs/1001-install.md
- install.sh
Use an optional environment variable BIN_DIR to customize the final
install directory of the dagger binary.
Update documentation to show how to use the environment variable
Signed-off-by: Connor Kelly <connor.r.kelly@gmail.com>
> feat: Add install directory customization

- pkg/universe.dagger.io/alpha/kubernetes/helm/install.cue
- pkg/universe.dagger.io/alpha/kubernetes/helm/test/test.cue
This PR contains three changes:
1. Using `helm upgrade --install` instead of `helm install` because it support both new installation and upgrade scenarios.
2. Let user define custom namespace and Helm create it if needed.
3. Using correct package in test.
FYI @vgjm
> feat: Support Helm upgrade and custom namespace

- docs/core-concepts/1203-client.md
- docs/tests/core-concepts/client/plans/cmd.cue
- docs/tests/core-concepts/client/plans/cmd_secret.cue
- docs/tests/core-concepts/client/plans/cmd_stderr.cue
- docs/tests/core-concepts/client/plans/cmd_stdin.cue
- docs/tests/core-concepts/client/plans/platform.cue
Resolves #1890
👀 [Preview](https://deploy-preview-2668--devel-docs-dagger-io.netlify.app/1203/client#running-commands)
> docs: Provide more examples on `client: commands` and `platform`

- telemetry/telemetry.go
prints the dagger cloud URL when starting plan if the CLI is authenticated.  Example:
```
marcos:Projects/dagger (main) (⎈ |kind-kind)$ ./cmd/dagger/dagger do version
Dagger Cloud URL: https://dagger.cloud/runs/72a52e3c-ad33-468d-97f4-623572632806
[✔] actions.version                                                                                                       3.1s
[✔] client.filesystem.".".read                                                                                            1.2s
Field   Value
output  "39bfe53e"
marcos:Projects/dagger (main) (⎈ |kind-kind)$```
> Print Dagger Cloud URL when starting plan

- website/src/css/custom.scss
This will fix how codeblocks inside hyperlinks are rendered inside
admonitions.
The underline for the hyperlink is removed as it does not render well in Firefox.
From [#328](https://github.com/dagger/dagger.io/issues/328)
> [Docs] Fix hyperlinks rendering inside admonitions

- website/src/css/custom.scss
- website/src/theme/DocCard/index.d.ts
- website/src/theme/DocCard/index.js
- website/src/theme/DocCard/styles.module.css
- website/src/theme/DocCardList/index.d.ts
- website/src/theme/DocCardList/index.js
This will modify the spacing and font weight of the sidebar categories.
It will also convert the cards on each category index page to a list.
From [#486](https://github.com/dagger/dagger.io/issues/260)
> [Docs] Categories UI improvement

- docs/guidelines/1227-contributing.md
Noticed that there is an extra word `help` on `Contributing to Dagger` doc. This may be a minor thing, but there was a spacing on the markdown file, but since it was not rendered showing a space on the website, I only remove the extra space on the Markdown file.
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
> (docs) Removed extra word `help` on `Contributing to Dagger` doc

- docs/guides/logdebug/1241-dagger-cloud-debugging.md
I've changed all dagger cloud links to remove attribute "noreferrer".
> docs: remove noreferrer from dagger cloud links

- pkg/universe.dagger.io/alpha/codecov/image.cue
- pkg/universe.dagger.io/alpha/codecov/test/image.cue
- pkg/universe.dagger.io/alpha/codecov/upload.cue
This PR adds Codecov uploader to the alpha channel of universe as seen in [my blog post](https://dev.to/sagikazarmark/building-a-ci-pipeline-for-a-go-library-with-dagger-2an7).
The uploader comes with a lot more option, but I thought I'd open a PR first and more options later as required.
```
-B, --branch                  Specify the branch manually
-b, --build                   Specify the build number manually
-c, --clean                   Move discovered coverage reports to the trash
[boolean] [alapértelmezett: false]
-C, --sha                     Specify the commit SHA mannually
--changelog, --CL         Display a link for the current changelog
-d, --dryRun                  Don't upload files to Codecov
[boolean] [alapértelmezett: false]
-e, --env                     Specify …
```
> feat(universe): add codecov uploader to alpha

- pkg/universe.dagger.io/bash/bash.cue
- pkg/universe.dagger.io/bash/test/test.cue
* `bash.#SimpleImage` is a simple container image capable of running bash. It is meant for convenience and is not customizable, on purpose.
* `bash.#RunSimple` is a version of `bash.#Run` that uses `#SimpleImage`. Ideally, this would be implemented with a default value to `bash.#Run`, but because of [limitations in how CUE handles default values](https://github.com/dagger/dagger/discussions/857), that is not possible.
> universe: bash: #RunSimple

- cmd/dagger/cmd/do.go
- compiler/build.go
- compiler/compiler.go
- telemetry/event/run.go
This uses cue's build.Instace struct and sends all the
ast.File found during CUE parsing as well as the corresponding
error that highlights the error while evaluating the plan
> Send telemetry event when plan does not evaluate

- cmd/dagger/cmd/do.go
> Manually flush events in case of exiting without returning from function.

- website/src/css/custom.scss
This will improve UX by adding space between sidebar categories,
and by increasing the category title font weight and size.
From [#260](https://github.com/dagger/dagger.io/issues/260)
> [Docs] Sidebar UX Improvement

- cmd/dagger/cmd/do.go
Fixes an issue when trying to get feedback about 0.1 plans which are not
supported. Telemetry was trying to create an empty run which is not
currently possible.
> Fix regression when printing 0.1 compat error msg

- plan/task/exec.go
- tests/tasks.bats
- tests/tasks/exec/http_proxy.cue
Adds support for HTTP and HTTPS Proxy. It translates the right env vars to LLB Run options.
- Closes #2053 
- Closes #1369
> feat: add support for HTTP, HTTPS proxy

- .goreleaser.yml
- version/version.go
This is now picked up from Go's 1.18 debug.Buildinfo.
Keep the short git SHAs in the version.
Follow-up to https://github.com/dagger/dagger/pull/2749
> chore: Remove Revision from GoReleaser

- cmd/dagger/cmd/do.go
- telemetry/event/run.go
Before this commit, if user has an invalid Dagger plan and runs `dagger
do` without any arguments, they'll get an error and the execution won't be uploaded to Dagger Cloud. This allows uploading the user's plan even though it's invalid.
This change will very likely help new users trying to create plans
without too much knowledge of the dagger CUE specific definitions.
> Allow sending to DC invalid dagger plans that don't evaluate.

- cmd/dagger/cmd/doc.go
- go.mod
- go.sum
We can create dedicated style if we want (derive Dagger design color?)
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2779"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: use glamour in doc markdown rendering

- docs/guides/logdebug/1241-dagger-cloud-debugging.md
- docs/includes/_dagger-cloud-cta.md
- docs: Fix Dagger Cloud CTA link
- docs: Add how to disconnect the CLI from Cloud
- docs: Remove tip dupe from Dagger Cloud docs
- docs: Minor Dagger Cloud page rewords
- docs: Fix Dagger Cloud discussion link in CTA
> docs: How to disconnect CLI from Dagger Cloud

- pkg/universe.dagger.io/bash/bash.cue
There's a sort of convention that if a package has a default image, then it's accessible as `<package>.#Image`.
> universe: Use `bash.#Image` convention

- go.mod
- go.sum
- pkg/dagger.io/dagger/core/exec.cue
- pkg/dagger.io/dagger/core/start.cue
- plan/task/exec.go
- plan/task/startExec.go
- solver/container.go
- solver/solver.go
- tests/tasks.bats
- tests/tasks/exec/start_stop_exec.cue
Before this, core.Start output was just dropped entirely. Now, its
stdout and stderr are logged in the same way core.Exec output is
logged.
This requires importing some Buildkit code that it uses for collecting
and publishing log streams efficiently (internally uses a circular
buffer). The interface is a bit clunky but gets us parity between
core.Start and core.Exec.
Note: this also has a separate commit that refactors the code to split it amongst separate files, as requested in a previous PR: https://github.com/dagger/dagger/pull/2460
Will be somewhat easier to review by looking at the `Log core.Start output` commit by itself.
Fixes #2469
> Log core.Start output. 

- pkg/pkg.go
- tests/project.bats
It confuses users and is only needed in an advanced case.
> chore: Don’t create `cue.mod/usr` on init

- website/netlify.toml
This change in the Netlify.toml will redirect https://docs.dagger.io/1241/dagger-cloud/ to https://docs.dagger.io/1243/dagger-cloud/
> [Docs] Redirect deprecated Dagger Cloud page

- pkg/universe.dagger.io/alpha/aws/cdk/python/test/image.cue
CI seems to be broken due to a test on the `universe/alpha/aws/cdk/python` package: https://github.com/dagger/dagger/runs/7408582632?check_suite_focus=true#step:8:1327
* It checks the python version with `python version` command which doesn't seem to exist.
* the node version retrieved from apt just got upgraded
Peer: @gerhard 
> fix: broken CI due to alpha/aws/cdk test

- pkg/universe.dagger.io/docker/run.cue
Partially resolves #2802.
Transforms the `export` key of `docker.#Run` from `rootfs: dagger.#FS & _exec.output` to `rootfs: _exec.output`.
The previous unification made Cue not return any selector for the given expression.
To give more context, the below plan, with or without the first `bar` key commented, retrieves the same `refPath`. However, one has `Selectors`, the other is `nil`:
```
dagger.#Plan & {
actions: test: #Foo & {
// commenting this line fixes the error
bar: #Bar
}
}
#Foo: {
bar: #Bar
}
#Bar: {
_image: alpine.#Build
_run: docker.#Run & {
input: _image.output
command: name: "date"
}
}
```
The issue seems to come from the `docker.#Run.export` field. The unification in the assignment `rootfs: dagger.#FS & _exec.output` makes the evaluator not consider it as a value containing …
> fix: Validator not detecting an edge case with valid FS reference

- go.mod
- go.sum
https://github.com/moby/buildkit/blob/v0.10.3/go.mod#L62-L68
Otherwise we can introduce data races and other weird behaviour:
- (jaeger v1.6.0) data races https://github.com/dagger/dagger/runs/7359366602?check_suite_focus=true#step:8:1433
- (jaeger v1.8.0) conflicting Schema URLs https://github.com/dagger/dagger/runs/7358945187?check_suite_focus=true#step:8:2066
Also mentioned in https://github.com/dagger/dagger/pull/2446#issuecomment-1126377411
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2808"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Keep go.opentelemetry.io/otel versions in sync with BuildKit

- cmd/dagger/cmd/do.go
Refactored "runcompleted" login so it now better tracks different exit
points in the program and allowing to display more accurate information
in DC
> Mark runs failed when action cannot be found in plan

- docs/guides/concepts/1244-docker.md
- pkg/dagger.io/dagger/core/image.cue
- plan/task/pull.go
- tests/tasks.bats
- tests/tasks/pull/pull_auth_env.cue
Add global `dockerhub_auth_user` and `dockerhub_auth_password` env variables, to enable login to docker hub (only) and avoid being limited by rate-limiting free accounts.
Fixes #2804 
> feat: Add global auth env variables to `core.#Pull`

- README.md
It pointed to the Dagger 0.1 docs. 
I didn't find the "build from source" content on the new install page, so I didn't change that link yet. 
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2834"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> updated the install link

- pkg/universe.dagger.io/go/image.cue
- pkg/universe.dagger.io/go/test/build.cue
- pkg/universe.dagger.io/go/test/image.cue
This commit revert a change of API in `universe/go`.
A recent PR added 2 fields: `name` and `repository` to customize the image to
pull when calling `go.#Image`.
The problem is that change does not fit with the purpose of `go.#Image`, this
one should be used as default image to cover simple workflow with the simplest
possible API. That's why it's usually only possible to configure some packages
and a version of the official image.
If the user want to provide a custom image, he can override the field `input`
(or image sometime) of other definition.
To do so, he can use `docker.#Pull` or create his own definition to cover his
proper use case.
> universe(go): revert of part of #2632

- docs/core-concepts/1202-plan.md
- docs/getting-started/1200-local-dev.md
- docs/getting-started/1201-ci-environment.md
- docs/guides/buildkit/1237-persistent-cache.md
- website/docusaurus.config.js
- website/plugins/docusaurus-plugin-dagger-version/index.js
- website/src/components/DaggerVersionLatestReleased.js
This will fetch the version from https://dl.dagger.io/dagger/latest_version and template it in all doc pages on deploy.
Resolves https://github.com/dagger/dagger/issues/1854
Resolves https://github.com/dagger/dagger/issues/2205
Resolves https://github.com/dagger/dagger/issues/2351
The only thing which remains is to figure out how to template this version in the YAML snippets, e.g. https://github.com/dagger/dagger/pull/2369/files#diff-e309255ddd52101788f3de79596d0b93496c72d4b04059e44154f9e12b63e4d0R134
> docs: Resolve Dagger version dynamically

- cmd/dagger/cmd/lsp.go
- go.mod
- go.sum
- Change hidden Dagger subcommand to `dagger cuelsp`.
- Update LSP imports
- Update server Mode initialization to work with functional server initialization paradigm + server initialization error management
> feat(lsp): update lsp import + fix incompatibilities

- ci/golangci/lint.cue
- docs/plans/go-ci/plan.cue
- pkg/universe.dagger.io/alpha/go/golangci/lint.cue
- pkg/universe.dagger.io/alpha/go/goreleaser/release.cue
- pkg/universe.dagger.io/alpha/go/goreleaser/test/release.cue
- pkg/universe.dagger.io/go/build.cue
- pkg/universe.dagger.io/go/container.cue
- pkg/universe.dagger.io/go/test.cue
- pkg/universe.dagger.io/go/test/build.cue
- pkg/universe.dagger.io/go/test/container.cue
- pkg/universe.dagger.io/go/test/data/hello/go.mod
- pkg/universe.dagger.io/go/test/data/hello/go.sum
- pkg/universe.dagger.io/go/test/data/hello/greeting/greeting_test.go
- pkg/universe.dagger.io/go/test/data/hello/internal/testutil/result_file.go
- pkg/universe.dagger.io/go/test/data/hello/math/algebra.go
- pkg/universe.dagger.io/go/test/data/hello/math/algebra_test.go
- pkg/universe.dagger.io/go/test/test.cue
The idea is to have `go.#Test.packages` that can accept either a string, or an array of string so we can do
```cue
go.#Test & {
packages: "./..."
}
```
```cue
go.#Test & {
packages: ["./pkg1", "./pkg2"]
}
```
- match the `go test` better (we can use multiple packages)
- can confuse the user (is it a string? is it an array?)
> feat: change go.#Test.package -> packages and can be string or [...string]

- website/package.json
- website/yarn.lock
This will avoid the CLI from complaining about different versions between Docusaurus and @docusaurus/preset-classic. The presets [allow configuring dependencies in a centralized way](https://docusaurus.io/docs/using-plugins#using-presets).
> [Docs] bump docusaurus-preset-classic version

- website/package.json
- website/yarn.lock
Also add a yarn task that is able to update it automatically. I was getting warnings when running this locally before the update.
npx is required for `browserlist --update-db` to work.
> chore: Update caniuse yarn dep

- go.mod
- go.sum
Bump of the LSP version to latest release:
- LSP used to break on aliased imports. One open-source contributor made an awesome PR 🙏  ([#82](https://github.com/dagger/cuelsp/pull/82))
- Also adds a better error message on single file opening ([#83](https://github.com/dagger/cuelsp/pull/83))
> fix: LSP aliased import + single file error handling

- .github/workflows/auto-release.yml
This explains why we need to do it separately, on top of GoReleaser updating our Homebrew tap:
- https://github.com/dagger/dagger/issues/2823#issuecomment-1190792261
- https://github.com/Homebrew/homebrew-core/pull/105746#issuecomment-1190522063
Closes https://github.com/dagger/dagger/issues/2823
> ci: Open a homebrew-core PR when we release

- .github/workflows/auto-release.yml
- .github/workflows/test-auto-release.yml
Since this runs on the main branch, the `github.ref` value will be set to `refs/heads/main` and the
https://github.com/mislav/bump-homebrew-formula-action will fail as we have seen in this run: https://github.com/dagger/dagger/runs/7651780409?check_suite_focus=true#step:9:13
This sets the tag-name value explicitly which should fix it according to https://github.com/mislav/bump-homebrew-formula-action#manual-trigger
Follow-up to https://github.com/dagger/dagger/pull/2888
> Set tag-name explicitly for homebrew-core PR

- docs/core-concepts/1215-what-is-cue.md
Hey,
There were a small typo in this page.
Cheers
> docs: fix typo in what-is-cue docs 

- docs/getting-started/f44rm-how-it-works.mdx
The `How-it-works` page has some bad redirects. This is the fix
> docs: fix broken links

- api/auth/auth.go
Set the correct `AuthStyle` to avoid undesired behavior from the oauth2
library when polling to check that the device code has been validated
> fix: use correct oauth auth style

- api/auth/auth.go
> fix: remove unnecessary left oauth2 comment

- .github/workflows/auto-release.yml
Autorelease #49 failed due to missing gh token. When implementing the homebrew autorelease feature, a command using the `gh` CLI was moved to a job without copying the GITHUB_TOKEN env var.
cc @gerhard @dolanor 
> fix: autorelease missing gh secret

- docs/guides/actions/1241-field-shadowing.md
Quick typo fix,  `shodowing` => `shadowing`
> docs: fix typo, shadowing not shodowing

- pkg/universe.dagger.io/README.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX10Pft3mJ0qSFVpTuyNObgh95BUS8bzh48%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=s9LDGu6)
Signed-off-by: Avinash Upadhyaya <avinashupadhya99@gmail.com>
Fix link to the todoapp example in the universe README since the examples were moved out of the universe directory
> Fix link to todoapp example in universe

- pkg/universe.dagger.io/docker/run.cue
- pkg/universe.dagger.io/docker/test/run.cue
Unsure if this is a desired or not, but thought I would propose it.
I got stuck using `docker` package, after assuming `export` would resolve relative to `workdir`.
I started a little thread in the [help](https://discord.com/channels/707636530424053791/709803368318632038/1007931064876019753) channel in discord for my issue.
Eventually, I figured out what I was doing wrong and solved it with an absolute path.
This change updates `files`, `directories` and `secrets` within `export` to resolve any relative paths against the `workdir` base.
> fix(universe/docker): support exporting relative to working directory

- docs/guidelines/1227-contributing.md
Add directions on how to retrieve the sops_age_key file and use
`sops` to add a new secret to tests/secrets_sops.yaml.
> docs/faq: Add FAQ on tests/secrets_sops.yaml

- docs/getting-started/tutorial/1200-local-dev.md
Added a step in the getting started docs to indicate that running `dagger project update` is expected in order to get the example app running after initial download. I also made this same update to the example app readme file and have an open PR on that repo.
Closes: #2438
Signed-off-by: Brittan DeYoung <32572259+brittandeyoung@users.noreply.github.com>
> docs: Add project update to local dev docs

- pkg/universe.dagger.io/go/configure.cue
- pkg/universe.dagger.io/go/test/configure.cue
- pkg/universe.dagger.io/go/test/test.bats
A helpful action to add go to any image.
Expects the caller to pass in a rootfs that already has go init that we
can extract and put into the passed in image.
> Add go action to install/configure go into image

- cmd/dagger/cmd/project/init.go
`dagger project init example` will provide the following information:
`Project initialized in "example"! To install dagger packages, go to subfolder "example" and run "dagger project update"`
> fix: dagger project init <something> does not display useful command information

- ci/cue/lint.cue
- ci/git/worktree.cue
- ci/golangci/lint.cue
Inside git worktrees, linter is not working, as the `.git` directory is located elsewhere.
Extend the `ci` library with new `git.#Worktree` package that creates a git repo (if we `dagger do lint` from a `git worktree`) to avoid breaks
> fix: linter not working in git-worktrees

- docs/guides/logdebug/1243-dagger-cloud-debugging.md
> [docs] - Typo fix for dagger cloud documentation

- pkg/universe.dagger.io/alpha/jreleaser/README.md
Docs for the jreleaser package were missing "alpha" in import statements.
Signed-off-by: Andres Almiray <aalmiray@gmail.com>
> docs: update reference to jreleaser package

- install.sh
For now, it works on debian derived system.
I need people to test on Mac OS to tell me if that works as well.
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2950"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feature: install completion script for bash, zsh and fish

- api/auth/auth.go
> Remove stdout tty check since dagger supports headless auth.

- api/container.gql
- api/directory.gql
- api/file.gql
- api/host.gql
- api/http.gql
- api/root.gql
- api/secret.gql
Correct some syntax (e.g. missing colons), type names (e.g. Integer -> Int) to make things 
consistent.
Adds a root.gql with an empty Query (needed to be without {} like this 
https://stackoverflow.com/questions/54322029/graphqljs-query-root-type-must-be-provided).
> Schema fixes for new API

- docs/getting-started/1242-install.mdx
<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/3142"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: Use brew install from core instead of tap

- cmd/dagger/cmd/project/info.go
- docs/getting-started/1242-install.mdx
- docs/references/13ec8-dagger-env-reference.md
- plan/plan.go
- tests/project.bats
I found the following documentation with [TODO commented out](https://github.com/dagger/dagger/blob/main/cmd/dagger/cmd/project/info.go#L33). Therefore, I added a function to output Plans in the following format.
example: For a dagger.cue file
input
```cue
package todoapp
import (
"dagger.io/dagger"
"dagger.io/dagger/core"
"universe.dagger.io/netlify"
"universe.dagger.io/yarn"
)
dagger.#Plan & {
actions: {
// Load the todoapp source code 
source: core.#Source & {
path: "."
exclude: [
"node_modules",
"build",
"*.cue",
"*.md",
".git",
]
}
// Build todoapp
build: yarn.#Script & {
name:   "build"
source: actions.source.output
}
// Test todoapp
test: yarn.#Script & {
name:   "test"
source: actions.source.output
// This environment variable disables watch mode
// in "react-scripts test".
// We …
```
> feat(project info): output available plans

- ci.cue
- docs/tests/core-concepts/client/plans/file_export.cue
- docs/tests/use-cases/ci-cd-for-go-project/complete-ci-cd/dagger.cue
This merge request removes usage of the deprecated field `package` from universe/go.
The `package` field is removed, besides in the tests to keep backward compatibility in check.
> Remove usage of go.#Test.package and go.#Build.package

- .gitignore
before I accidentally commit it one day :)
context: `Session.vim` is the default filename used by [vim-obsession](https://github.com/tpope/vim-obsession), a tool for saving/restoring vim editor sessions (buffers, splits, etc.)
> ignore Session.vim

- core/core.go
- core/core.schema.go
- core/filesystem/filesystem.go
- core/filesystem/image.go
- core/integration/core.schema_test.go
fixes #3066
supersedes https://github.com/dagger/cloak/pull/220 which had a totally different approach
Introduces a new intermediate type, `filesystem.Image`, which encodes to/from `FSID`. (Name bikeshedding welcome.) This type pairs the LLB definition with an OCI image config (`{"Env":[...],"Dir":"...",...}`). It can be converted to and from an `llb.State` via the `Env`/`Dir` fields stored within. `llb.Image` is now passed `llb.WithMetaResolver` in order to populate these fields.
I'm not sure if this is considered backwards-incompatible; within a single engine session nothing should break, but the structure of `FSID` has changed, so any previously-generated `FSID`s won't work with this new code (and vice versa),
TODO:
> propagate image env/dir to `exec`

- .github/workflows/auto-release.yml
We want to fail auto-releases on purpose if there have been no changes since the previous release. While this can happen, it is rare and we should take notice of it, hence the failure.
For more context, see this Discord thread:
https://discord.com/channels/707636530424053791/796905486145683506/1022141805468328027
My intention has been to update this to Dagger for a long time now. It kept getting trumped by other priorities, and while now is the wrong time to do it, every time I have to touch this YAML, I sigh and tell myself: "one day...". Not today though.
I checked that this works as expected via https://github.com/gerhard/dagger/actions/runs/3103289111/jobs/5026460988
FWIW, these are the temporary changes which I used for that check:
```diff
diff --git …
```
> Fail auto-release if no changes since previous release

- core/core.go
- core/core.schema.go
- core/exec.schema.go
- core/git.schema.go
- core/integration/core.schema_test.go
- core/integration/git.schema_test.go
* Implement `{ query { git } }` from [new core API](./api/git.gql)
* Keep backwards compat with old `{ query { core { git } } }`
* Simplify passing of ssh auth socket across schemas
* ~~The git "builtin" now lives in a sub-directory. A small first step towards modularizing the core api into "built extensions"~~ (*removed from this PR to keep diff minimal*)
> [cloak] Implement git core API

- core/integration/core.schema_test.go
- core/integration/old_core.schema_test.go
Pushing this first to make sure I'm interpreting the new API correctly before I go off and implement it.
Safe to merge. All new tests are skipped since the API isn't actually implemented.
I copied the current tests to a new file and then changed the original in-place so you can see a diff. I'd like to rename `core.schema_test.go` to `container.schema_test.go` but then GitHub just shows it as a whole new file, so I'll do that later.
> core API: translate integration tests 1:1 to new API

- core/core.go
- core/core.schema.go
- core/dockerbuild.schema.go
- core/exec.schema.go
- core/filesystem.schema.go
- core/filesystem/filesystem.go
- core/git.schema.go
- core/project.schema.go
- core/secret.schema.go
- core/util.go
- project/config.go
- project/project.go
- router/schema.go
This is just a first batch of conversions; I will convert the rest of our resolvers once I've gotten confirmation everyone else is on board.
Found this approach during multiplatform (turned out to not be strictly necessary there so I separated it out). Basically lets us use actual types in our resolver methods and convert each of them to the graphql resolver type by just wrapping them in `router.ToResolver`. That `ToResolver` helper is an ugly generic function, but go's type inference is just powerful enough that it's the only place generics are needed; users don't have to specify params when using it.
This makes it much easier+safer to write resolvers since there's no more having to manually cast+convert types when accessing parents and args. …
> Initial conversion to use typed resolver methods.

- core/core.go
- core/directory.go
- core/file.go
- core/filesystem.schema.go
- core/git.go
- core/integration/core.schema_test.go
- core/integration/directory_test.go
- core/integration/file_test.go
- core/integration/git_test.go
- core/integration/old_core.schema_test.go
- core/integration/suite_test.go
- core/schema/directory.graphqls
- core/schema/file.graphqls
- core/schema/fs.go
- core/schema/git.graphqls
- core/secret.schema.go
- core/util.go
- router/schema.go
Implements the following portions of the API:
```graphql
directory(id: DirectoryID)
type Directory {
id: DirectoryID!
contents(path: String!): String!
file(path: String!): File!
withNewFile(path: String!, contents: String): Directory!
withCopiedFile(path: String!, source: FileID!): Directory!
directory(path: String!): Directory!
withDirectory(path: String!, directory: DirectoryID!): Directory!
}
type File {
id: FileID!
contents: String!
size: Int!
}
```
The rest of the spec is stubbed out to return errors. Also changes `git { tree }` to return a `Directory!` instead of a `Filesystem!`.
Also introduces some utilities for encoding/decoding IDs and defining ID scalar types in the schema. I went a little ham with generics here, probably didn't need to, but they're shiny.
> initial `Directory` + `File` implementations

- router/schema.go
Without some description, it requires some back and forth to get the
role of P, A and R types.
> doc(router): add description to ToResolver

- core/container.go
- core/directory.go
- core/file.go
- core/integration/container_test.go
- core/integration/old_core.schema_test.go
- core/schema/container.graphqls
- core/util.go
part of #3183
* Track the exec metadata mount point (`/dagger`) in a separate field within `ContainerID` since its lifecycle differs from regular mounts
* Add `Container { withMountedDirectory }` and propagate changes to mounts from parent `Container` to child
* Respect sub-directory configuration within source `DirectoryID`
* Make `Container { stdout, stderr }` nullable (same reason `exitCode` is nullable)
* Allow `container { from }` to propagate mounts
> Add `Container { withMountedDirectory }`

- .gitignore
It was ignoring the whole cmd/cloak directory
> .gitignore: fix cloak path

- core/cache.go
- core/container.go
- core/integration/cache_test.go
- core/integration/container_test.go
- core/integration/suite_test.go
- core/schema/base.go
- core/schema/cache.go
- core/schema/cache.graphqls
- core/schema/container.go
- core/schema/container.graphqls
- core/schema/fs.go
fixes #3270 
Implements the following:
```graphql
"A global cache volume identifier"
scalar CacheID
extend type Query {
"Construct a cache volume from its ID"
cache(id: CacheID!): CacheVolume!
"Create a new cache volume identified by an arbitrary set of tokens"
cacheFromTokens(tokens: [String!]!): CacheVolume!
}
"A directory whose contents persist across runs"
type CacheVolume {
id: CacheID!
}
extend type Container {
withMountedCache(path: String!, cache: CacheID!, source: DirectoryID): Container!
}
```
(Bikeshedding welcome.)
Prior discussions were in Discord, crystallized in this comment: https://github.com/dagger/dagger/pull/3217#discussion_r988029723
The basic idea is to re-introduce `CacheID` but with an API for creating them rather than having the user provide such a low-level and …
> add `CacheID` and `CacheVolume`

- package.json
- yarn.lock
Require Node.js v16 LTS in dev & everywhere else. We want to pin to the current Node.js LTS version - Oct. 2022.
This is a follow-up to https://github.com/dagger/dagger/pull/3292#issuecomment-1273546614
> Pin Node.js version for TypeScript SDK

- cmd/dagger/do.go
- cmd/dagger/main.go
- core/container.go
- core/file.go
- core/integration/file_test.go
- core/integration/secret_test.go
- core/schema/base.go
- core/schema/container.go
- core/schema/file.go
- core/schema/file.graphqls
- core/schema/fs.go
- core/schema/secret.go
- core/schema/secret.graphqls
- core/secret.go
- engine/engine.go
- examples/queries/queries_test.go
- examples/queries/secret.graphql
- internal/testutil/query.go
- secret/store.go
part of #3178
closes #3183
Unlike the other core API PRs, **this is a breaking change** as it replaces the old secret schema.
Removed:
```graphql
core {
secret(id: SecretID!): String!
addSecret(plaintext: String!): SecretID!
}
```
Added:
```graphql
secret(id: SecretID!): Secret!
container {
withSecretVariable(name: String!, secret: SecretID!): Container!
withMountedSecret(path: String!, source: SecretID!): Container!
}
file {
secret: Secret!
}
```
This initial PR only supports loading secrets from files, but it has internal scaffolding in place for loading secrets from host env. There just isn't an API representation for it yet, since pulling on that thread leads me to the `Host` API, which leads to possibly a bunch more work which I'm currently investigating. (tl;dr: `Host` is a touch …
> add `Secret` core API

- core/container.go
- core/integration/container_test.go
- core/integration/secret_test.go
- core/integration/suite_test.go
- core/schema/container.go
- core/schema/container.graphqls
fixes #3266 
Symmetrical to `directory`; retrieves a `File` by looking through all mount points.
> Container: add `file`

- .gitignore
- examples/python/client-simple/README.md
- examples/python/client-simple/cloak.yaml
- sdk/python/dagger/src/dagger/client.py
- sdk/python/dagger/src/dagger/engine.py
We want to fail if the "wrong" dagger is used. Versions prior to 0.3.x will not have commands that these SDKs depend on.
Follow-up to https://github.com/dagger/dagger/pull/3285
Part of https://github.com/dagger/dagger/issues/3176
> Guard against wrong dagger binary in Python SDK

- codegen/generator/generator.go
- codegen/generator/templates/lint_name.go
- codegen/introspection/visitor.go
- sdk/go/dagger/api/api.gen.go
This removes all limits to codegen, will also generate old API bindings.
> sdk: go: codegen all types

- examples/python/hello/__main__.py
- examples/python/hello/cloak.yaml
- examples/python/hello/main.py
- examples/python/hello/schema.graphql
- project/pythonruntime.go
- sdk/python/dagger/README.md
- sdk/python/dagger/pyproject.toml
- sdk/python/dagger/src/dagger/__init__.py
- sdk/python/dagger/src/dagger/cli.py
- sdk/python/dagger/src/dagger/converter.py
- sdk/python/dagger/src/dagger/log.py
- sdk/python/dagger/src/dagger/server.py
Fixes #3296
No more need for crafting a `schema.graphql` file nor manually generating before commit. Python extensions can declare GraphQL schemas purely in code.
You need a `server: dagger.Server` instance in a `main.py` file at the root of the extension.
```diff
-if __name__ == '__main__':
-    s = dagger.Server()
-    s.run()
+schema = strawberry.Schema(query=Query)
+server = dagger.Server(schema)
```
I wanted to keep the strawberry code as untouched as possible so you can use examples from the [docs](https://strawberry.rocks/docs) or from the [playground](https://play.strawberry.rocks/) with just a small addition, just like any [integration](https://strawberry.rocks/docs/integrations/aiohttp). 
Example from playground, you just copy the code do your extension and make a small change …
> Python: Code-only schema

- core/integration/project_test.go
- core/integration/testdata/extension/main.go
- core/integration/testdata/extension/schema.graphql
- project/project.go
- sdk/go/dagger/server.go
This was one of the last functional uses of FSID (besides the existing extensions+examples). Also realized there was a bug with the codefirst schema parsing of these inputs, fixed that and the existing test we had for that.
Updated this issue with the followups needed in the long term to clean this up: https://github.com/dagger/dagger/issues/3074
> Remove automount use of FSID. 

- core/cache.go
- core/integration/cache_test.go
- core/integration/suite_test.go
- core/schema/cache.go
- core/schema/cache.graphqls
- sdk/go/dagger/api/api.gen.go
follow-up to https://github.com/dagger/dagger/pull/3287 which has a lot of discussion that led to the following changes:
* ~~`cacheFromTokens` -> `cache { withKey }`; we can use this to "chain" keys from an initial scope, currently global~~
* `cacheFromTokens` -> `cacheVolume(key: String!)` - no scoping at the moment, but easy to add later
* switch from a list of tokens to a single key; a list doesn't help much at API level since it's already a separate query so you can't just reuse a param from something else
* there's still a list of keys (formerly tokens) internally, but now it's an implementation detail
> Second iteration of new caching API

- .github/workflows/release-v0.3.x.yml
- .goreleaser.yml
This is the beginning of v0.3.x release automation. We start by producing pre-releases (a.k.a. technical preview releases), specifically `v0.3.0-alpha.N`.
I have setup a parallel AWS S3 & GitHub & Homebrew tap to test how this works together. This is the successful run that produced an **unofficial** `v0.3.0-alpha.1` release in this parallel stack: https://github.com/gerhard/dagger/actions/runs/3244062096
This is what we end up with in AWS S3:
Here is the **unofficial** GitHub pre-release: https://github.com/gerhard/dagger/releases/tag/v0.3.0-alpha.1
The **unofficial** Homebrew tap is here: https://github.com/gerhard/homebrew-tap/blob/main/dagger%400.3.rb
This is what happened when I installed it via `brew install gerhard/tap/dagger@0.3`:
Notice that the alpha binary is available via …
> Add workflow for v0.3.x pre-releases

- codegen/generator/templates/src/header.go.tmpl
- codegen/generator/templates/src/object.go.tmpl
- codegen/generator/templates/src/scalar.go.tmpl
- core/integration/examples_test.go
- examples/alpine/main.go
- sdk/go/dagger/api/api.gen.go
- sdk/go/dagger/server.go
- Add support in extension API to directly return a codegen'd type
- Convert alpine to the new SDK
> examples: alpine: use new Go SDK

- core/integration/examples_test.go
- examples/yarn/index.ts
- examples/yarn/schema.graphql
Also has commit from @aluzzardi PR here just so that alpine (used by yarn) returns container type: https://github.com/dagger/dagger/pull/3392
> Update yarn to new API. 

- examples/python/client-simple/dagger.json
- examples/python/client-simple/query.py
- examples/python/hello/dagger.json
- examples/python/hello/main.py
- examples/python/hello/requirements.txt
Needed so we can remove the old one.
Note: Took the chance to give an example on using the query builder. We will replace these examples later with something more useful and using the forthcoming codegen api.
> Python: update examples to new API

- sdk/go/dagger/client.go
Otherwise, you might get some codegen that seems to not work.
It implies that you have Go installed, but I guess if you need to do that, there is a big chance that it is the case.
> feat: use the current version of dagger for code generation

- core/container.go
- core/directory.go
- core/file.go
- core/host.go
- project/dockerfileruntime.go
- project/goruntime.go
- project/project.go
- project/pythonruntime.go
- project/tsruntime.go
This same refactor has already been applied to Container because one day we needed to add another value to return. The Go linter complains (justifiably) once you hit 4 non-error return values.
Another refactor I'm starting on will result in needing another value in the File and Directory payloads, so this just does an initial structural refactor in preparation of that.
> core: refactor away from multi-return-value `Decode()`

- internal/buildkitd/buildkitd.go
Today, when running the `dagger` cli and providing a graphql query, if
it's a fresh environment without buildkit running, a buildkit container
will be started and a message will be emitted to stdout telling you so
which pollutes the following json output from the graphql query.
This commit sends those startup messages to stderr instead of stdout,
so things work on the first run instead of failing.
Example below:
`dagger.sh`
```
RUN="/usr/local/bin/dagger do -f ./queries.graphql"
WORKFS=$($RUN Workdir)
echo $WORKFS | jq -r '.host.workdir.read.id'
```
`queries.graphql`
```
query Workdir {
host {
workdir {
read {
id
}
}
}
}
```
output from jenkins test
```
No buildkitd container found, creating one... { "host": { "workdir": { "read": { "id": …
```
> fix: send buildkit startup msgs to stderr

- core/container.go
- core/integration/container_test.go
- core/schema/container.go
- core/schema/container.graphqls
- sdk/go/dagger/api/api.gen.go
fixes #3340 
I ended up needing this because I need to be able to pass `Stdin` but that results in setting `RedirectStdout` and `RedirectStderr` to an empty string because the `ExecOpts` struct wasn't a zero-value. Without this change I would get this from the shim:
```
15: [0.11s] panic: open : no such file or directory
15: [0.11s]
15: [0.11s] goroutine 1 [running]:
15: [0.11s] main.run()
15: [0.11s] 	/src/main.go:47 +0xad9
15: [0.11s] main.main()
15: [0.11s] 	/src/main.go:91 +0x19
```
So this promotes these params to `exec` params, removing the nesting, and removes the `""` vs. `nil` distinction for stdin, redirectStdout, and redirectStderr.
I don't think there was any difference between `stdin: ""` and `stdin: nil` before anyway; one would set it to an empty file, and the other would …
> flatten ExecOpts into container.exec params

- core/directory.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/examples_test.go
- core/schema/directory.go
- core/schema/directory.graphqls
- sdk/go/dagger/api/api.gen.go
- sdk/go/dagger/client_test.go
> Directory: rename `contents` to `entries`

- core/container.go
- core/integration/container_test.go
- core/schema/container.go
- core/schema/container.graphqls
- sdk/go/dagger/api/api.gen.go
needed for #3210 
Implements the following API, based on #3151:
```graphql
extend type Container {
build(context: DirectoryID!, dockerfile: String): Container!
}
```
* I decided to go with `context` and `dockerfile` for the param args since they felt a bit more descriptive. They are both terms described in the [Docker docs](https://docs.docker.com/engine/reference/commandline/build/#description).
* I decided to have this live on `Container` instead of `Directory`. It's true that it always takes a `Directory`, but I like the symmetry with `container.from` and `container.withFS` as the final goal is to build a `Container`, just like them.
Also, moved `container.from` implementation to `(*core.Container).From` for consistency.
> Container: add `build`

- docs/new.sh
Rationale: the non-numerical IDs look like garbled words,. my brain keeps trying to parse them which trips me up ever so slightly each time I glance at the url.
> Chore: generate numerical IDs for docs articles

- docs/v0.3/sdk/go/8g34z-get-started.md
Casting is no longer required with https://github.com/dagger/dagger/commit/3cc1b24a6afbc35b56b214eec642eb4acaedb2a3
Signed-off-by: kpenfound <kyle@dagger.io>
> getting-started guide: api.ContainerAddress cast no longer needed in Container.From

- cmd/dagger/dev.go
- engine/engine.go
- sdk/go/client.go
- sdk/go/client_test.go
- sdk/go/internal/engineconn/embedded/embedded.go
- sdk/go/internal/engineconn/engineconn.go
It is configurable programmatically with `engine.Config` passed in the `engine.Start`.
> feat(engine): discard log buildkit progress by default

- website/docusaurus.config.js
The PR #3434 has been merged accidentally and the docs is now using the new api key polluting analytics. 
Next step will be to recreate a new api key in Posthog and recreate a new PR that has to be merged for the launch to capture GO SKD docs analytics.
> Update Posthog apiKey with an old one

- .github/workflows/lint.yml
- .github/workflows/test.yml
Only run the test workflow when Go-related files change
Also JS files in the `sdk/nodejs` dir.
We don't want to run this unnecessarily.
We also don't want to run this on tags. If we tagged something that was not linted correctly, something is very wrong in our release workflow and should be addressed. FWIW:
https://github.com/dagger/dagger/blob/77eed15d356836981e4c0975920674069e315edf/.github/workflows/release-v0.3.x.yml#L87-L95
We want to run on larger runners so we learn quicker about potential errors.
Added a note to keep the node-version in sync with package.json. The test will fail anyways (because of the engine constraint), but the comment will hopefully make the fix more obvious.
> Only run lint & test when specific files change

- website/docusaurus.config.js
After this change, the remark-code-import plugin will permit importing files from outside the website root.
Closes #3491
> docs: Update code import plugin configuration

- docs/current/sdk/cue/232322-guides.md
- docs/current/sdk/cue/852645-usage-examples.md
Some of the page URLs in the CUE SDK docs did not begin with /sdk/cue. This commit corrects those URLs.
Closes #3493
> docs: Update the URLs for certain CUE SDK pages

- website/sidebars.js
This change creates a new "Overview" node in the navigation tree for each SDK's docs.
Closes #3492
> docs: Create distinct Overview pages for each SDK

- .github/workflows/release-dagger-cue.yml
- .goreleaser.yml
- client/client.go
- cmd/dagger/cmd/do.go
- cmd/dagger/cmd/project/info.go
- cmd/dagger/cmd/project/init.go
- cmd/dagger/cmd/project/update.go
- cmd/dagger/cmd/root.go
- cmd/dagger/cmd/version.go
- compiler/build.go
- install.ps1
- install.sh
- plan/plan.go
- plan/runner.go
- util/buildkitd/buildkitd.go
This PR is:
- part of https://github.com/dagger/dagger/issues/3471
- supersedes https://github.com/dagger/dagger/pull/3483
- partial follow-up to https://github.com/dagger/dagger/pull/3356
It changes the `release-v0.2.x.yml` workflow to publish `dagger-cue` binaries.
Linux `install.sh` & Windows `install.ps1` have been updated too. The Linux variant has been tested.
**Help wanted for the Windows one**.
This was tested via https://github.com/gerhard/dagger/actions/runs/3316263177/jobs/5477850676 & it published:
Tested with `./install.sh`
Tested with `brew install gerhard/tap/dagger-cue`
---
---
FWIW we ended up upgrading to GoReleaser Pro with @aluzzardi so that we get the monorepo support. It has a bunch of other useful features too that we might want to look into …
> Prepare to publish dagger-cue artefacts

- docs/current/543069-index.md
- docs/current/sdk/go/440319-index.md
`Directed Acrylic Graph (DAG)` -> `Directed Acyclic Graph (DAG)`
> chore(typo): fix typo in DAG acronym

- pkg/pkg.go
- https://github.com/dagger/dagger/pull/3506
- https://github.com/dagger/dagger/pull/3486
We are reverting the dagger & universe modules checks back in preparation for publishing `v0.2.232`
Once we merge this PR and publish `v0.2.232`, this should work:
```
dagger-cue do hello
1:04AM ERROR system | failed to load plan: this plan requires dagger 0.2.36 or newer. Run `dagger version --check` to check for latest version
this plan requires dagger 0.2.36 or newer. Run `dagger version --check` to check for latest version
```
Thank you @jpadams for reporting this. cc @shykes @aluzzardi for being part of the conversation 🐴
---
[Why `.232`?](https://www.youtube.com/watch?v=099cHWSbAL8)
> Make dagger-cue compatible with existing dagger packages

- .github/workflows/release-dagger-cue.yml
Otherwise we will not be able to trigger it manually
Add a condition so that this workflow only runs from the `cue-sdk` branch. We do not want to release `dagger-cue` from any other branch.
- https://github.com/dagger/dagger/pull/3532
cc @shykes @aluzzardi @samalba @jpadams @mircubed
> ci: Add release-dagger-cue GHA workflow to the main branch

- docs/current/sdk/cue/getting-started/526369-install.mdx
Today there are `dagger` install pkgs in Scoop and Chocolatey. There are not yet `dagger-cue` pkgs. This PR removes instructions for install via Scoop and Choco from `current` docs for now until we have `dagger-cue` pkgs. The `v0.2.x` version of docs is still correct for users of `dagger`. 
https://github.com/dagger/dagger/issues/3484#issuecomment-1290649686
> Remove scoop & choco until `dagger-cue` pkgs exist

- sdk/go/README.md
- sdk/go/examples_test.go
Adds some examples for common use cases of the Dagger Go SDK. The examples will run as part of `go test` and let us know if the "Output:" magic comments become a lie. Pretty cool stuff! ([more info](https://go.dev/blog/examples))
Please nitpick the examples, since they might have a strong influence on how people write Dagger code.
Also adds a README. Note that this README will show up in the generated Godocs ([example](https://pkg.go.dev/github.com/moby/buildkit#section-readme)); suggestions welcome.
> add initial godoc examples + README

- codegen/generator/templates/src/header.go.tmpl
- codegen/generator/templates/src/object.go.tmpl
- codegen/generator/templates/src/scalar.go.tmpl
- sdk/go/api.gen.go
I did this for objects for forgot the scalars.
Since client and api are the same package now, there's no need for
the interface to export public functions anymore.
> sdk: go: make scalar marshallers private

- core/container.go
- core/shim/cmd/main.go
Fixes https://github.com/dagger/dagger/issues/3407
Could also add verification in the code that users don't mount over this I suppose, but the name is obscure enough now that I don't think anyone would do it accidentally, so probably not worth it IMO.
> Use more obscure name for shim meta mount.

- .github/workflows/lint.yml
- magefile.go
markdown linting via dagger, works locally (`mage lint:markdown`)
> ci: lint using dagger

- codegen/generator/templates/functions.go
- sdk/go/client.go
Without this a field that accepted a list of custom scalars would never be generated as a slice in Go
> Handle lists of scalars in codegen. 

- core/directory.go
- core/host.go
- core/integration/directory_test.go
- core/integration/host_test.go
- core/integration/suite_test.go
- core/schema/directory.go
- core/schema/directory.graphqls
- core/schema/host.go
- core/schema/host.graphqls
- sdk/go/api.gen.go
Adds `include`/`exclude` filters to the following APIs:
```graphql
type Directory {
withDirectory(path: String!, directory: DirectoryID!, exclude: [String!], include: [String!]): Directory!
}
type Host {
workdir(exclude: [String!], include: [String!]): Directory!
directory(path: String!, exclude: [String!], include: [String!]): Directory!
}
```
> add include/exclude support 

- docs/current/sdk/go/959738-get-started.md
After this commit, the Go get started will display the reference on Dagger.Connect() to its package.
Closes [#3580](https://github.com/dagger/dagger/issues/3580)
> issue 3580: ref link to Dagger.Connect()

- cmd/cloak/dev.go
- engine/engine.go
closes #3218
also adds StartAndDisplay for preserving the previous behavior and updates all existing call sites to use it instead.
by making this configurable, other projects can use their own progress UI by reading from the channel.
> engine: make progress configurable

- core/container.go
- core/integration/container_test.go
fixes #3551
* propagate mounts from the result of running the command with every mount, rather than one at a time as we iterate, which meant each mount technically had a different llb state.
* remove stacking semantics as Buildkit currently assumes mount targets are unique (see second commit message)
> fix mount propagation causing repeated runs

- core/directory.go
- core/integration/directory_test.go
- core/schema/README.md
- core/schema/directory.go
- core/schema/directory.graphqls
- magefile.go
- sdk/go/api.gen.go
fixes #3588 
fixes #3567
* rename `withCopiedFile` to `withFile`, now consistent with `withDirectory`
* add `withNewDirectory` for the mkdir use case, consistent with `withNewFile`
via https://github.com/dagger/dagger/issues/3567#issuecomment-1294368392, here's the new convention:
> * `withDirectory`, `withFile`: copy a directory/file (source always required)
> * `withNewDirectory`, `withNewFile`: create a new directory/file
> Directory: consistent terminology for file/dir creation vs copying

- codegen/generator/templates/functions.go
- codegen/generator/templates/src/header.go.tmpl
- codegen/generator/templates/src/input.go.tmpl
- codegen/generator/templates/src/object.go.tmpl
- codegen/generator/templates/src/scalar.go.tmpl
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/host_test.go
- core/integration/platform_test.go
- magefile.go
- sdk/go/api.gen.go
- sdk/go/client.go
- sdk/go/examples_test.go
- sdk/go/go.mod
- sdk/go/internal/querybuilder/marshal.go
- sdk/go/internal/querybuilder/marshal_test.go
- sdk/go/internal/querybuilder/querybuilder.go
- sdk/go/internal/querybuilder/querybuilder_test.go
- sdk/go/server.go
Partial implementation of #3558. Example:
**Before**:
```go
modules := c.Directory()
for _, f := range []string{"go.mod", "go.sum", "sdk/go/go.mod", "sdk/go/go.sum"} {
fileID, err := workdir.File(f).ID(ctx)
if err != nil {
return err
}
modules = modules.WithCopiedFile(f, fileID)
}
```
**After**:
```go
modules := c.Directory()
for _, f := range []string{"go.mod", "go.sum", "sdk/go/go.mod", "sdk/go/go.sum"} {
modules = modules.WithCopiedFile(f, workdir.File(f))
}
```
See our changes to `magefile.go` and various tests for other examples.
**Caveats**
- Some arguments are named `id` in the API (e.g. `id FileID`), but they're not IDs in the SDK (e.g. `id *File`)
- Currently it doesn't work on optional fields, because they're structures. I don't know yet how to get around that without recursive …
> Go SDK: Pass objects by reference instead of ID

- core/container.go
- core/directory.go
- core/file.go
- core/host.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/file_test.go
- core/integration/host_test.go
- core/integration/suite_test.go
- core/schema/base.go
- core/schema/container.go
- core/schema/container.graphqls
- core/schema/directory.go
- core/schema/file.go
- core/schema/file.graphqls
- sdk/go/api.gen.go
Adds the following schema:
```graphql
extend type Container {
"Export the container an OCI tarball to the destination path."
export(path: String!): Boolean!
}
extend type File {
"Write the file to a directory on the host"
export(path: String!): Boolean!
}
```
Side note: I thought about supporting `export(path: String!, address: ContainerAddress!)` so you can set a name for the exported image, but supporting that isn't possible with the OCI exporter until Buildkit ships a new version (possibly v0.11?) with annotation support (https://github.com/moby/buildkit/pull/2879).
> Add Container/File `export` and check for workdir escaping

- .github/workflows/add-issues-to-backlog.yml
GitHub deprecated an API, breaking the action version we were using.
This change bumps it to the latest version.
> ci: update add-issues-to-backlog workflow

- docs/current/sdk/go/275922-guides.md
- docs/current/sdk/go/guides/421437-work-with-host-filesystem.md
- docs/current/sdk/go/snippets/work-with-host-filesystem/export-dir/main.go
- docs/current/sdk/go/snippets/work-with-host-filesystem/list-dir-exclude/main.go
- docs/current/sdk/go/snippets/work-with-host-filesystem/list-dir-include/main.go
- docs/current/sdk/go/snippets/work-with-host-filesystem/list-dir/main.go
- docs/current/sdk/go/snippets/work-with-host-filesystem/mount-dir/main.go
- docs/current/sdk/go/snippets/work-with-host-filesystem/set-workdir/main.go
- website/sidebars.js
When applied, this commit adds a guide for the new host API.
It  also adds a sidebar node named "Guides" to the navigation tree and a guides index page.
Closes #3593
> docs: Add guide for new host API

- docs/current/sdk/go/275922-guides.md
- docs/current/sdk/go/guides/110632-embed-directories.md
- docs/current/sdk/go/snippets/embed-directories/example/foo.go
- docs/current/sdk/go/snippets/embed-directories/main.go
Little docs following a question from Alvise on `help` channel:
- explains how to recusively copy a directory to container
With warning, until we implement the corresponding API call
!! Rebased on top of `git-login` branch !!
>  docs(guide-go): copy embed directories to container (Go-SDK)

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .golangci.yml
- core/container.go
- core/directory.go
- core/schema/container.graphqls
- engine/engine.go
- internal/mage/docs.go
- internal/mage/engine.go
- internal/mage/sdk/go.go
- internal/mage/util/util.go
- project/project.go
- project/proxy.go
- sdk/go/api.gen.go
- sdk/go/client_test.go
- sdk/go/examples_test.go
- sdk/go/internal/engineconn/unix/unix.go
Add the `ExperimentalPrivilegedNesting` flag to `Exec()` which sets a valid `DAGGER_HOST` inside the container, allowing to communicate back to the same engine instance.
In short, this means that it's possible to run a program that uses the Go SDK within Dagger itself -- `dagger.Connect()` will automagically work out of the box.
This PR also enables to to run dagger tests using dagger in our own CI.
/cc @helderco
> support dagger in dagger

- core/shim/cmd/main.go
- sdk/go/client.go
- sdk/go/internal/engineconn/embedded/embedded.go
- sdk/go/internal/engineconn/engineconn.go
- sdk/go/internal/engineconn/http/http.go
- sdk/go/internal/engineconn/unix/unix.go
Will automatically rewrite a `DAGGER_HOST` from `unix://` to `http://`
This removes the need for SDKs to implement unix socket support.
/cc @helderco @slumbering @TomChv
> shim: unix->tcp API proxy

- internal/buildkitd/buildkitd.go
fixes https://github.com/dagger/dagger/issues/3723
Note: this will affect the whole process, so it prevents us from using logrus and it means anyone importing engine will be impacted. However, we don't expect engine to be imported a lot anymore since it's no longer imported by the sdk (https://github.com/dagger/dagger/pull/3724) so I think this is okay.
The alternatives would be:
1. Fix upstream - this is not a buildkit library but a docker/cli one, so it may be easier said than done to both get a fix merged and to actually get that fix into our dependency tree
2. Write our own connhelper that is the same as buildkit's but without any logrus usage. Essentially requires forking a little bit of buildkit code and the commandconn implementation …
> Disable logrus to prevent library spam.

- .github/workflows/publish-sdk-python.yml
This was triggered by a push to `main` which is not what we want: https://github.com/dagger/dagger/actions/runs/3428027315
Only tags starting with sdk/python/v tags should trigger this workflow
> ci: Only publish Python SDK when there is an sdk/python tag

- docs/current/partials/_install-sdk-cue.md
I saw that in the documentation they talk about `DAGGER_VERSION` to specify the version to install. But it doesn't work. 
After reading the script, I saw that the parameter was renamed to `VERSION`. Probably when renaming dagger to dagger-cue. 
So I'm making a small PR to correct the documentation.
> Fix dagger-cue installation doc DAGGER_VERSION to DAGGER

- sdk/go/go.mod
- sdk/go/go.sum
- sdk/go/internal/engineconn/dockerprovision/dockerprovision.go
- sdk/go/provision_test.go
Main goal here is to automate provision testing. As part of that I found I was occasionally getting `text busy` errors trying to exec the `engine-session` binary.
After investigation this turned out to be incredibly obscure and highly specific to what the test case was doing. It could happen when:
1. The engine-session binary was not already provisioned
2. There are many fork/execs happening in parallel with the provisioning
It's actually a unsolved problem in Go and Linux in general apparently: https://github.com/golang/go/issues/22315
It's a bit annoying to workaround but worth it so we can have this test case if nothing else.
> Add test for docker image provision. 

- docs/current/sdk/python/snippets/get-started/step1/test.py
Without this change:
```
python test.py #wait 10 to 30 seconds with no feedback
Hello from Dagger and Python 3.10.8
```
With this change:
```
python test.py #near immediate feedback
#1 resolve image config for docker.io/library/python:3.10-slim-buster
#1 DONE 1.7s
#2 mkfile /Dockerfile
#2 DONE 0.0s
#3 mkfile /main.go
#3 DONE 0.0s
#4 [internal] load metadata for docker.io/library/golang:1.18.2-alpine
#4 DONE 0.9s
...
#14 python -V
#0 0.077 Python 3.10.8
#14 DONE 0.1s
Hello from Dagger and Python 3.10.8
```
Instead could use the code in Step 3 of Getting Started right away:
```
async with dagger.Connection(dagger.Config(log_output=sys.stderr)) as client:
```
Could also add a comment to say this is optional:
```
log = dagger.Config(log_output=sys.stderr)
```
Signed-off-by: Jeremy Adams …
> docs: Make first example give immediate feedback

- .github/workflows/lint.yml
- .github/workflows/publish-sdk-go.yml
- .github/workflows/publish-sdk-python.yml
- .github/workflows/test.yml
- hack/make
- internal/mage/main.go
- Run `./hack/make X` instead of `mage X`
- Use vendored version of mage instead of binary
/cc @gerhard @sipsma @vito
> ci: mage -> ./hack/make

- core/directory.go
- core/integration/directory_test.go
- core/integration/suite_test.go
Allow a user to specify wildcards in their paths for `(dir *Directory) Without()`. 
I need _at least_ this for `dagger-cue`. Even better would be the ability to turn it on/off, but that would require an API change. 
If we are up for that, I'd suggest this as the new API.
```
type Directory {
withoutDirectory(path: String!, disableWildcards: bool): Directory!
}
```
I can make that change, if we're cool with it. 
Another possibility is adding this API:
```
type Directory {
without(pattern: String!): Directory!
}
```
> Add `WithAllowWildcard` to `(dir *Directory) Without()`

- .github/workflows/release-v0.3.x.yml
- .github/workflows/test.yml
- .readthedocs.yaml
- internal/mage/engine.go
- internal/mage/sdk/go.go
/cc @gerhard @sipsma @vito 
Low urgency. Experimented with moving our CI to self-hosted to harness buildkit cache.
> ci: limit usage of large runners 

- RELEASING.md
https://github.com/dagger/dagger/releases/tag/sdk%2Fpython%2Fv0.1.1 was the trial run.
Related to https://github.com/dagger/dagger/issues/3667
> chore: Add release & changelog for releasing Python SDK

- .github/workflows/publish-engine.yml
Follow-up to #3786
This should not have failed (or even be triggered) https://github.com/dagger/dagger/actions/runs/3447101778/jobs/5752758900#step:5:1127
> ci: Do not bump SDK Engine Deps on push to main

- sdk/python/tests/connectors/test_docker.py
Same thing as for Go, but in Python now: https://github.com/dagger/dagger/pull/3761
---
NOTE: this test won't yet run in CI because when we use dagger-in-dagger DAGGER_HOST gets overridden, so right now this test is only useful for us when running manually directly on hosts. I'm gonna fix this for both go+python+future-sdks in a follow up so it can also run in CI.
---
Also note: the ETXTBSY issue hit in Go (https://github.com/golang/go/issues/22315) is not an issue here ***yet*** because our provisioner implementation is fully sync (and thus closes all file descriptors before they could end up in a forked process). However, that issue is a general Linux flaw and you can find people using pretty much any language hitting+complaining about it …
> Add docker image provisioner test.

- core/container.go
Since this code gets executed in the client machine through the session
helper and then gets sent to the engine, the path should always be in
unix format.
User confirmed this works here: https://discord.com/channels/707636530424053791/1040348875287957554
> Fix dockerfile path join in windows

- go.mod
- go.sum
- internal/mage/engine.go
- follow-up to https://github.com/dagger/dagger/pull/3797
Tags are the only ones that are semver valid. All other engine references (e.g. `main`) will NOT trigger SDK engine version bumps.
https://github.com/dagger/dagger/actions/runs/3462838805 should not have triggered engine bumps in SDKs. FWIW, NodeJS SDK engine bump is not yet implemented: https://github.com/dagger/dagger/pull/3783#issuecomment-1311833703
> ci: Only bump engine version in SDKs if publishing a tag

- sdk/python/pyproject.toml
Linter was complaining because of mixed types in list.
> sdk: python: Fix linter on poe task

- sdk/python/README.md
- sdk/python/examples/client-simple/say.py
- sdk/python/examples/client-simple/say_sync.py
Example had a wrong reference to the old `Result` wrapper.
Removed comments with `log_output` tip because it’s easy to miss and it’s covered in the getting started guide on the documentation site. Added progress status instead to keep terminal clean.
Kept the version in README.md as simple as possible. That’s just a carrot, the proper example is in the `examples` directory and in the docs.
> sdk: python: Fix README.md example

- sdk/nodejs/.eslintrc.cjs
- sdk/nodejs/package.json
- sdk/nodejs/provisioning/http/http.ts
Linter was not failing with warnings. Fixed a couple of issues.
Codegen code throws errors and was disabled, logged this: #3865
> sdk: nodejs: make sure linting errors actually fail

- sdk/python/src/dagger/api/base.py
- sdk/python/src/dagger/connectors/docker.py
- sdk/python/src/dagger/exceptions.py
Improves error messages when dagger is not installed or not running.
Also creates the catch all (`DaggerExecption`) mentioned in #3805.
Discord thread: https://discord.com/channels/707636530424053791/1041044357345718282/1041044783155654766
```
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```
```
dagger.connectors.docker.ProvisionError: Command 'docker' not found.
```
```
dagger.connectors.docker.ProvisionError: Failed to copy engine session binary: None
```
```
dagger.connectors.docker.ProvisionError: Failed to copy engine session binary: docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```
```
ValueError: invalid literal for int() with base 10: ''
```
``` …
```
> Python: Improve error messages

- docs/current/sdk/nodejs/783645-get-started.md
- docs/current/sdk/nodejs/835948-install.md
This commit reformats the Node.js SDK installation instructions using tabs.
Relates to #3640
> docs: Format Node SDK  instructions using tabs

- website/sidebars.js
This commit adds the Node.js SDK docs to the site navigation sidebar.
Relates to #3640 
> docs: Add sidebar for Node.js SDK docs

- docs/current/sdk/nodejs/783645-get-started.md
- docs/current/sdk/nodejs/snippets/get-started/step4/build.ts
- docs/current/sdk/nodejs/snippets/get-started/step5/build.ts
Signed-off-by: kpenfound <kyle@dagger.io>
This shows off `Directory(exclude=[])` to exclude the local node_modules from the test/build environment. As this is definitely a best practice, this is a great place to demonstrate this pattern
> ts getting started: ignore node_modules

- docs/current/partials/_private-git-repository_first.md
- docs/current/partials/_private-git-repository_second.md
- docs/current/sdk/go/guides/710884-private-repositories.md
- docs/current/sdk/python/234291-guides.md
- docs/current/sdk/python/guides/683293-private-repositories.md
- docs/current/sdk/python/snippets/private-repositories/clone.py
- Port the private registry docs to python, to have a common basis
- Add it to guides list
It might be worth to have a better architecture other than copy-pasting ? I have several guides on-the-way that are worth being ported to python / go
cc @vikram-dagger 
> docs(python): port private registry docs to python

- sdk/nodejs/connect.ts
- sdk/nodejs/provisioning/docker-provision/image.ts
- sdk/nodejs/provisioning/engineconn.ts
* Fixes: https://github.com/dagger/dagger/issues/3836
* I noticed while working on this that the logging actually wasn't configurable at all outside of just the provisioning-related interface, so I went ahead and did that.
* Fixes: https://github.com/dagger/dagger/issues/3833
* I also noticed that the nanosecond timestamp was really just a second-timestamp, so I fixed that here too
> NodeJS Provisioning Follow ups 

- codegen/generator/nodejs/templates/src/class_comment.ts.tmpl
- codegen/generator/nodejs/templates/src/header.ts.tmpl
- codegen/generator/nodejs/templates/src/method.ts.tmpl
- codegen/generator/nodejs/templates/src/object.ts.tmpl
- codegen/generator/nodejs/templates/src/object_comment.ts.tmpl
- codegen/generator/nodejs/templates/src/object_comment_test.go
- codegen/generator/nodejs/templates/src/object_test.go
- codegen/generator/nodejs/templates/src/objects_test.go
- codegen/generator/nodejs/templates/src/type_test.go
- codegen/generator/nodejs/templates/templates.go
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/provisioning/test/provisioner.spec.ts
- Add @hidden (equivalent to @ignore in JSDoc) tag to remove symbol that should never appear in the documentation.
- Export every classes otherwise they will not appear in documentation. 
I've tried to use `typedoc-plugin-missing-exports` in docusaurus but gets some conflicts during the build.
> NodeJS SDK: Update codegen templates for docs references

- docs/current/543069-index.md
This commit adds links to the Node.js SDK documentation in the usage grid on the index page.
> docs: Add the Node SDK to the docs index page

- codegen/generator/go/templates/functions.go
- codegen/generator/go/templates/src/object.go.tmpl
- codegen/generator/nodejs/templates/functions.go
- codegen/generator/nodejs/templates/src/method.ts.tmpl
- codegen/generator/nodejs/templates/src/method_comment.ts.tmpl
- codegen/generator/nodejs/templates/src/method_solve.ts.tmpl
- codegen/generator/nodejs/templates/src/objects_test.go
- codegen/introspection/introspection.go
- core/container.go
- core/integration/container_test.go
- core/integration/platform_test.go
- core/integration/testdata/codetoschema/main.go
- core/schema/container.go
- core/schema/container.graphqls
- docs/current/sdk/go/snippets/multiplatform-support/build-images-cross-compilation/main.go
- docs/current/sdk/go/snippets/multiplatform-support/build-images-emulation/main.go
- docs/current/sdk/go/snippets/multiplatform-support/non-linux-support/main.go
- docs/current/sdk/go/snippets/multistage-build/main.go
- internal/mage/sdk/nodejs.go
- internal/mage/util/util.go
- router/compile.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/docs/_ext/dagger_ext.py
- sdk/python/docs/conf.py
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- sdk/python/src/dagger/codegen.py
- Add support for `@deprecated` GraphQL directive in the API
- Add support for handling `@deprecated` fields in the Go SDK codegen
- Renamed `fs` -> `rootfs` and `withFS` -> `withRootfs`
- Kept backward compat with deprecated `fs` / `withFS` fields
@helderco @slumbering @dolanor: The same `@deprecated` support needs to be added to Python and NodeJS as well. We're going to have a bunch like this.
> replace FS by RootFS

- sdk/python/src/dagger/connectors/docker.py
More background on this case in the previous PR here (and in the comment included in the code of this PR): https://github.com/dagger/dagger/pull/3763
Apparently despite our expectations that being sync would stop this, @grouville hit it, so may as well just handle the error the same as we do in the Go SDK.
> Handle etxtbsy error in python sdk.

- cmd/engine-session/main.go
- cmd/shim/main.go
- core/container.go
- core/integration/container_test.go
- core/integration/platform_test.go
- core/runnerproxy.go
- engine/engine.go
- internal/engine/client.go
- internal/mage/engine.go
- internal/mage/sdk/go.go
- internal/mage/sdk/nodejs.go
- internal/mage/sdk/python.go
- internal/mage/util/util.go
- project/project.go
- project/sessionproxy.go
- sdk/go/client.go
- sdk/go/internal/engineconn/bin/bin.go
- sdk/go/internal/engineconn/bin/bin_linux.go
- sdk/go/internal/engineconn/bin/bin_nolinux.go
- sdk/go/internal/engineconn/dockerprovision/container.go
- sdk/go/internal/engineconn/dockerprovision/dockerprovision.go
- sdk/go/internal/engineconn/dockerprovision/image.go
- sdk/go/internal/engineconn/unix/unix.go
- sdk/nodejs/provisioning/bin/bin.ts
- sdk/nodejs/provisioning/bin/index.ts
- sdk/nodejs/provisioning/provisioner.ts
- sdk/python/src/dagger/cli.py
- sdk/python/src/dagger/connectors/__init__.py
- sdk/python/src/dagger/connectors/bin.py
- sdk/python/src/dagger/connectors/docker.py
Get engine session nesting fully working, which enables tests of dagger-in-dagger that involve local dirs. Now, when running dagger-in-dagger a new engine session is started up (the same as when outside dagger) and local directories refer to directories local to the container (not the host).
**Pros:**
1. Dagger-in-dagger works fully, including localdir stuff.
3. Dagger-in-dagger is actually safe-ish now? It's no longer directly possible for an exec using dagger-in-dagger to access host resources
* There are still roundabout ways that they might be able to do this due to the fact that buildkitd internally has a bunch of codepaths that will try "any connected session", however that's an independent issue we were always going to need to solve …
> Support full isolated sessions w/ dagger-in-dagger. 

- internal/mage/sdk/nodejs.go
- sdk/nodejs/package.json
Temporary hack to manually format the generated code, until we generate
formatted code.
Without this, every time I call `sdk:all:generate`, I have explicitly to
cd into `sdk/nodejs` and run `yarn fmt` to fix it.
Signed-off-by: Andrea Luzzardi <al@dagger.io>
> sdk: nodejs: format generated code

- cmd/shim/main.go
This is a follow up to [the change yesterday](https://github.com/dagger/dagger/pull/3913) which simplifies the architecture significantly.
It also sets up cleaner integration with the [nested session change](https://github.com/dagger/dagger/pull/3787), which I'll do in another follow up to this PR (that should likely be the one that enables us to move dagger-in-dagger out of experimental mode).
```mermaid
graph LR;
subgraph outershim[oci wrapper]
outershimNote["Update OCI runtime bundle to include dagger shim"]
end
subgraph innershim[dagger shim]
innershimNote["Proxy stdio, write exit code, etc."]
end
buildkitd --> outershimNote --> runc --> innershimNote--> userexec["user executable"]
```
```mermaid
graph LR;
subgraph shim[dagger shim]
shimNote["Proxy stdio, write exit code, etc."]
end …
```
> Simplify shim setup by running shim outside of container

- cmd/shim/main.go
- core/integration/container_test.go
Realized that [this commit](https://github.com/dagger/dagger/commit/dfee9e47f9a33b30f8bda249ffe758c46eea5868) partially broke redirecting of stdout/stderr, specifically in the case where the redirect points to a non-root mount. Was missed because we didn't have a test case covering that (added one now).
This is fixable without having to revert that change, but the fix will involve some complexity (the cleanest fix is probably to use a containerd worker backend instead of runc) and we want to do a release tomorrow, so I'm just going to revert that change for now.
The reverted change's only benefit was simpler internal architecture, so it's not a huge loss to temporarily revert it. We still retain all the benefits of the oci runtime wrapper without it.
> Fix redirect of stdio to non root mount.

- cmd/shim/main.go
- core/container.go
- internal/mage/engine.go
- internal/mage/sdk/go.go
- internal/mage/sdk/nodejs.go
- internal/mage/sdk/python.go
Originally was planning on making dagger-in-dagger the default with this PR, but we decided to wait for other still-moving architecture pieces to settle before doing that, just so we can minimize the occurrence of any breaking changes.
So now I reduced the scope of this and it just updates the `ExperimentalPrivilegedNesting` flag to result in the engine-session binary automatically being mounted in from the engine image rather than requiring the user to provide it.
The remaining steps needed before enabling dagger-in-dagger by default:
1. Make the "single-session-per-connect" behavior the default for dagger-in-dagger execs (this commit results in the "separate session" behavior being the default.
* Requires merging the engine-session functionality into the shim, fairly straightforward
2. …
> Automatically mount in engine-session binary from host when dagger-in-dagger enabled.

- internal/mage/sdk/python.go
- sdk/python/poetry.lock
- sdk/python/pyproject.toml
- sdk/python/src/dagger/connectors/bin.py
- sdk/python/src/dagger/connectors/docker.py
- sdk/python/tests/connectors/test_bin.py
- sdk/python/tests/connectors/test_docker.py
Follow up to PR #3825 
The test names could probably use some work, let me know if there is a standard format you'd like to use and I'll fix them up. 
Maybe something like `test_raises_EXCEPTION_when_CONDITION`?
Also If I missed any test paths let me know!
> Python: Add tests for improved Provisioning Error Messages

- internal/engine/docker.go
- sdk/go/internal/engineconn/bin/bin.go
Previously unless you configured log output, no errors that occur in the engine-session binary would be visible to the end user, they would just get `EOF` as an error and nothing else, which is extremely confusing. This made it much harder to debug issue encountered in this PR for example: https://github.com/dagger/dagger/pull/3774
Now, even when log output is not set, the contents of stderr are temporarily buffered during provisioning and included in the error message if something goes wrong.
This should go well nicely with a similar change in the Python SDK: https://github.com/dagger/dagger/pull/3825/files
> Go SDK: include stderr in provisioning error.

- cmd/engine-session/main.go
- internal/engine/docker.go
- sdk/go/internal/engineconn/dockerprovision/image.go
This is a partial revert of 18458978b8a94a5d09a2b78066ce8ecffb4c1158.
The SDKs will for now continue to use image digests instead of git commits. The CLI will also temporarily just continue using the Go SDK and thus pick up this same change.
In the longer term, SDKs will switch to obtaining the CLI/engine-session bin from S3 rather than from the engine image. Additionally, the CLI will no longer use the Go SDK and instead just call engine.Start directly. It will then obtain the engine image based on the burned in vcs information (at least git tag, maybe git commit too).
> Continue using engine image ref digests for now.

- .github/workflows/lint.yml
- .github/workflows/publish-sdk-go.yml
- .github/workflows/publish-sdk-nodejs.yml
- .github/workflows/publish-sdk-python.yml
- .github/workflows/test.yml
- https://github.com/dagger/dagger/pull/3897#issuecomment-1323917409
The TL;DR is that we want to keep as little logic in the GitHub Actions workflows as possible, and keep as much as we can in Dagger (especially the caching part).
The only other change that this introduces is running engine tests with race detection in parallel. We want to optimise for the entire test pipeline finishing as soon as possible, which means running everything in parallel. Before this change, regular tests would need to pass first before the tests with race detection would run. cc @vito
> ci: Always run test & lint workflows

- docs/v0.1/1001-install.md
This commit corrects an error in the file path for the docs deprecation notice on the 0.1 installation page: https://docs.dagger.io/1001/install/
Relates to #3904 and #3915.
> docs: Fix error in path of docs deprecation note

- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/api/utils.ts
When users pass strings for `client.directory().withNewFile()` or even to `container.withExec()`, this is removing all whitespace and breaking entrypoints, commands, and scripts.
fixes #3990
> fix: don't trim all whitespace

- .github/workflows/publish.yml
- .goreleaser.yml
- internal/mage/cli.go
- internal/mage/engine.go
- internal/mage/util/util.go
Closes https://github.com/dagger/dagger/issues/4002
- ci: Extend existing publish-engine workflow to include the CLI
- chore: Require DAGGER_ENGINE_IMAGE to be declared via env var
- chore: Skip GoReleaser validation
- chore: Remove examples/** from published CLI binaries
- chore: Disable changelog creation when publishing via GoReleaser
- chore: Publish unversioned brew tap
- chore: Make install.sh use the latest published CLI version
We captured all the interesting details in each commit, they will be visible in the final commit message, part of **Squash and merge**
> ci: Publish CLI & Engine at the same time

- .github/workflows/publish.yml
- internal/mage/cli.go
- internal/mage/dagger.go
- internal/mage/engine.go
Follow-up to:
- https://github.com/dagger/dagger/pull/4012
We trigger the `publish.yml` workflow on push to `main`. We do not want to publish a new CLI when that happens. This might change in the future when we might want to have an edge/dev version always built from `main`. Out of scope for now.
Adds:
- Fixes (my) bad refactor
- Mentions when & why we skip SDKs image bump
> ci: Do not publish non semver CLI

- cmd/dagger/listen.go
- cmd/dagger/run.go
Following the stripe approach of using the username: https://stripe.com/docs/api/authentication?lang=curl
---
Happy case:
```console
go run $(pwd)/cmd/dagger run -- sh -c 'curl -v \
-u $DAGGER_SESSION_TOKEN: \
-H "content-type:application/json" \
-d "{\"query\":\"{container{id}}\"}" $DAGGER_SESSION_URL'
*   Trying 127.0.0.1:32921...
* Connected to localhost (127.0.0.1) port 32921 (#0)
* Server auth using Basic with user '4501c97d-ba4d-437c-b089-1730179d1161'
> POST / HTTP/1.1
> Host: localhost:32921
> Authorization: Basic NDUwMWM5N2QtYmE0ZC00MzdjLWIwODktMTczMDE3OWQxMTYxOg==
> User-Agent: curl/7.85.0
> Accept: */*
> content-type:application/json
> Content-Length: 27
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: …
```
> Use HTTP basic auth for dagger session token.

- docs/current/api/282105-playground.md
- docs/current/api/975146-concepts.md
This commit corrects some page "slugs" that are missing the unique numeric ID.
> docs: Fixed some page slugs

- website/src/css/atoms/button.module.scss
This fix will make the API Playground CTA in the docs render correctly.
Signed-off-by: Julián Cruciani <julian@dagger.io>
> docs: fix API Playground button style

- website/sidebars.js
If applied, this commit will add navigation links for the API and CLI documentation to the sidebar.
> docs: Add API/CLI links to sidebar

- core/integration/directory_test.go
- core/schema/directory.go
- core/schema/directory.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Implement 'directory { dockerBuild }' as an alias to 'container { build }'
Fixes #4015
> feat: api: directory { dockerBuild }

- codegen/generator/nodejs/templates/functions.go
- codegen/generator/nodejs/templates/src/header.ts.tmpl
- codegen/generator/nodejs/templates/src/method_solve.ts.tmpl
- codegen/generator/nodejs/templates/src/objects_test.go
- docs/current/sdk/nodejs/783645-get-started.md
- docs/current/sdk/nodejs/snippets/get-started/step3/build.js
- docs/current/sdk/nodejs/snippets/get-started/step3/build.ts
- docs/current/sdk/nodejs/snippets/get-started/step4/build.js
- docs/current/sdk/nodejs/snippets/get-started/step4/build.ts
- docs/current/sdk/nodejs/snippets/get-started/step5/build.js
- docs/current/sdk/nodejs/snippets/get-started/step5/build.ts
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/api/utils.ts
- sdk/nodejs/yarn.lock
Give the ability to pass the client as an argument without the needs of using its id.
Before
```ts
const cacheVolumeId = await client.cacheVolume("cache_key").id()
const image = await client 
.container()
.from("alpine")
.withMountedCache("/root/.cache", cacheVolumeId)
.withExec(["echo", "foo bar"])
.stdout()
```
After
```ts
const image = await client 
.container()
.withMountedCache("/root/.cache", client.cacheVolume("cache_key"))
.withExec(["echo", "foo bar"])
.stdout()
```
Tasks list:
> Node.js SDK: Nested queries

- docs/current/api/990050-index.md
This commit adds a "technical preview" badge to the API index page in the docs.
Signed-off-by: vikram-dagger <112123850+vikram-dagger@users.noreply.github.com>
> docs: Add tech preview badge to API page

- RELEASING.md
Used for creating:
- https://github.com/dagger/dagger/releases/tag/sdk%2Fnodejs%2Fv0.1.0
- https://github.com/dagger/dagger/releases/tag/sdk%2Fnodejs%2Fv0.1.1
> docs: Add releasing instructions for Node.js SDK changelog

- docs/current/api/254103-build-custom-client.md
This commit adds a security warning regarding the session token as requested in
https://github.com/dagger/dagger/pull/4052#pullrequestreview-1199979551 and performs a minor copy edit of the text.
> docs: Adds security note for session token

- website/docs-graphql/config.yml
- website/docs-graphql/custom-theme/views/partials/layout/page.hbs
This will make the GraphQL API Reference Dagger logo a link that takes you to `docs.dagger.io`.
Closes #4054
Signed-off-by: Julián Cruciani <julian@dagger.io>
> docs: add link to docs in api reference logo

- docs/current/api/282105-playground.md
This commit changes the title of the Playground page.
> docs: Add API to Playground title

- docs/current/sdk/go/guides/544174-multistage-build.md
- docs/current/sdk/go/snippets/multistage-build/main.go
Signed-off-by: kpenfound <kyle@dagger.io>
Updates the multistage guide to use `WithFile` introduced in https://github.com/dagger/dagger/pull/3827
> docs: update go multistage guide to 0.4.2

- sdk/nodejs/connect.ts
- sdk/nodejs/index.ts
The `CallbackFct` was not exported by the nodejs sdk.
I exported it so we can have some minimal documentation in the reference doc.
> Nodejs add callbackfct to doc

- codegen/generator/nodejs/templates/functions.go
- codegen/generator/nodejs/templates/functions_test.go
- codegen/generator/nodejs/templates/src/args_test.go
- codegen/generator/nodejs/templates/src/method.ts.tmpl
- codegen/generator/nodejs/templates/src/method_comment.ts.tmpl
- codegen/generator/nodejs/templates/src/method_solve.ts.tmpl
- codegen/generator/nodejs/templates/src/object_test.go
- codegen/generator/nodejs/templates/src/objects_test.go
- codegen/generator/nodejs/templates/src/type.ts.tmpl
- codegen/generator/nodejs/templates/src/type_field_comment.ts.tmpl
- codegen/generator/nodejs/templates/src/type_test.go
- codegen/generator/nodejs/templates/templates.go
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/test/connect.spec.ts
Now we can use best of both world:
- required params are available directly in the function params
- optional params are available through an object that lets you mix and match the options you want
```diff
- withExec(args: string[], stdin?: string, redirectStdout?: string, redirectStderr?: string, experimentalPrivilegedNesting?: boolean): Container {
-
+ export type ContainerWithExecOpts = {
+   stdin?: string
+   redirectStdout?: string
+   redirectStderr?: string
+   experimentalPrivilegedNesting?: boolean
+ }
+ withExec(args: string[], opts?: ContainerWithExecOpts): Container {
```
> NodeJS SDK required + optional types

- website/README.md
- website/STYLE_GUIDE.md
This commit adds the first draft of a style guide for documentation authors. The purpose is to help content authors produce more consistent documentation.
Closes #3641.
> docs: Add first draft of style guide

- website/package.json
mdx-js/react seems to be not used anymore.
> remove what seems to be an unused package

- docs/current/543069-index.md
remove YAML use case since we don't need to use cases pointing to CUE SKD and add CUE warning since it requires the old engine 
> remove YAML use case and add CUE warning

- core/directory.go
- core/file.go
- core/integration/directory_test.go
- core/integration/file_test.go
- core/integration/suite_test.go
- core/schema/directory.go
- core/schema/directory.graphqls
- core/schema/file.go
- core/schema/file.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
fixes #4104
Adds the following API:
```graphql
extend type Directory {
"This directory with all file/dir timestamps set to the given time, in seconds from the Unix epoch"
withTimestamps(timestamp: Int!): Directory!
}
extend type File {
"This file with its created/modified timestamps set to the given time, in seconds from the Unix epoch"
withTimestamps(timestamp: Int!): File!
}
```
Bikeshedding opportunities:
* `withTimestamps` name
* `timestamp` param name
* `timestamp` param type (should we have a `UnixSeconds` scalar? or just rename the param to `unixSeconds`?)
In hindsight there might be a less confusing name - we've got a plural `withTimestamps` yet a singular `timestamp` param. The name is plural because it modifies the contents recursively to a single timestamp.
One caveat: when …
> Directory+File: add `withTimestamps` for normalizing file/dir timestamps

- .goreleaser.yml
- cmd/client-gen/main.go
- cmd/dagger/engine.go
- cmd/dagger/version.go
- cmd/engine-session/main.go
- codegen/generator/generator.go
- codegen/generator/nodejs/templates/functions_test.go
- internal/engine/version.go
Fixes #4131
Same update as made to the dagger cli, but now to client-gen. Required moving the engine version stamp to a shared internal package so it could be reuse by both dagger and client-gen.
> Update client-gen to use engine.Start directly.

- cmd/dagger/run.go
- cmd/dagger/session.go
- cmd/shim/main.go
Localhost is often configured with entries for both ipv4 (127.0.0.1) and ipv6 entries (::1). Which one clients resolve to is inconsistent, so I found that sometimes nodejs would end up trying to connect to the ipv6 endpoint when the session was being listened to on ipv6.
Now we just consistently listen on 127.0.0.1. Technically it's possible for hosts to be ipv6 only or for a different loopback interface to be pointed to by /etc/hosts (e.g. 127.0.1.1), but these cases are extremely obscure to my knowledge so I think they can be dealt with later if needed.
> Use 127.0.0.1 instead of localhost for sessions.

- cmd/shim/main.go
- core/container.go
- core/gateway.go
- core/integration/container_test.go
- core/schema/base.go
- go.mod
- go.sum
Fixes https://github.com/dagger/dagger/issues/3025
I looked a bit into the upcoming build history API in buildkit v0.11 but realized the way its implemented makes it very hard to use for this case (it's all the progress for the whole build, not just one exec), so I think the approach in this pr, while inherently ugly, to be the only viable way.
We use a secret feature of buildkit that lets you obtain the mounts of a failed exec and use them in `NewContainer` calls. We then create a NewContainer with the meta mount of the failed exec and tell our shim to just output the contents of it.
Example error message:
```
container.from.withExec.exitCode process "sh -c echo Z29vZGJ5ZSwgY3J1ZWwgd29ybGQ= | base64 -d >&2; exit 1" did not complete …
```
> Include output of failed exec in error message.

- docs/current/sdk/nodejs/snippets/github-google-cloud/main.mjs
@vikram-dagger I've removed the awaited that are actually not running a Graphql query. 
The rule of thumb is to await a query that will execute a GraphQL query and return something. 
Maybe I'm wrong but the console.log seems to use the old syntax with `.publish`.
> Node.js GitHub + Google Cloud guide: remove awaited + fix the console.log

- sdk/python/poetry.lock
- sdk/python/pyproject.toml
- sdk/python/src/dagger/api/base.py
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- sdk/python/src/dagger/codegen.py
- sdk/python/tests/api/test_codegen.py
- sdk/python/tests/api/test_inputs.py
Fixes #3772
This helps detect some typos or mistakes during runtime.
Since type checking is optional, it's possible that the IDE doesn't complain in some cases and Python won't fail to execute in any case. So if you had the wrong type in a parameter, you'd get an _AST_ conversion error and only during query execution, which is harder to debug.
With this change, you'll get an earlier error (during query building) with a more useful error message.
Let's say you still use an ID value:
```python
repo_id = await client.git(repo_url).branch("master").tree().id()
...
ctr.with_mounted_directory("/src", repo_id)
```
This will show the following error **in Python 3.11**:
```console
File "/Users/helder/Projects/dagger-examples/test_simple.py", line 24, in test
.with_mounted_directory("/src", …
```
> sdk: python: Check input types at runtime

- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- sdk/python/src/dagger/codegen.py
Fixes #4191
- `Container.with_rootfs(id)` no longer accepts a `DirectoryID`. Only a `Directory` object.
- Top level fields that have an `id` argument and return its object, no longer accept an object as argument. Only an *ID*.
```diff
- def file(id: FileID | File) -> File
+ def file(id: FileID) -> File
```
See PR's diff for all changes.
> sdk: python: Fix inconsistencies in passing IDs to fields

- cmd/dagger/version.go
- internal/engine/version.go
- router/router.go
This allows to know which engine version is being used while serving
/query requests
> cli: expose x-dagger-engine version with dagger listen

- codegen/generator/nodejs/templates/src/type.ts.tmpl
- codegen/generator/nodejs/templates/src/type_test.go
type.ts.tpml now supports input types and
generates its Typescript representation.
Resolves: #4216
> feat: NodeSDK generate input from GQL schema.

- website/docs-graphql/data/examples/queries/socket/gql.md
The current example uses `/run/docker.sock` which is fine for Linux, but other platforms like MacOS use `/var/run/docker.sock` which also works via symlinks on Linux, so we should use the more general example in case somebody uses this as-is.
old:
```
echo eyJob3N0X3BhdGgiOiIvcnVuL2RvY2tlci5zb2NrIn0= | base64 -D
{"host_path":"/run/docker.sock"}%
```
new:
```
echo -n eyJob3N0X3BhdGgiOiIvdmFyL3J1bi9kb2NrZXIuc29jayJ9 | base64 -D
{"host_path":"/var/run/docker.sock"}%
```
> docs: Use /var/run/docker.sock base64

- core/container.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/schema/container.go
- core/schema/container.graphqls
- core/schema/directory.go
- core/schema/directory.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- sdk/python/src/dagger/codegen.py
Resolves #3574 
Signed-off-by: Joel Longtine <joel@longtine.io>
> Add build args to Dockerfile build

- docs/current/partials/_private-git-repository_first.md
- docs/current/sdk/go/snippets/private-repositories/main.go
- docs/current/sdk/nodejs/947203-guides.md
- docs/current/sdk/nodejs/guides/560223-private-repositories.md
- docs/current/sdk/nodejs/reference/modules.md
- docs/current/sdk/nodejs/snippets/private-repositories/clone.ts
- docs/current/sdk/python/snippets/private-repositories/clone.py
Unix socket implementation changed the behavior to connect to private repositories. This updates the docs accordingly + adds a Node example 😇
> docs: update private repo docs + add Node SDK example

- sdk/nodejs/package.json
- sdk/nodejs/provisioning/bin.ts
- sdk/nodejs/yarn.lock
- $XDG_CACHE_HOME (~/.cache by defaulte) on linux
- ~/Library/Caches/dagger on MacOS
- %LOCALAPPDATA%\dagger\Cache
https://www.npmjs.com/package/env-paths
It was already an indirect dependency.
> fix(sdk/nodejs): use OS user cache path with "env-paths"

- .goreleaser.common.yml
- .goreleaser.nightly.yml
- .goreleaser.yml
- sdk/go/internal/engineconn/cli.go
- sdk/nodejs/provisioning/bin.ts
- sdk/python/src/dagger/engine/bin.py
Recent changes accidentally introduced a small change in how we name archives:
```
before: dagger/releases/0.3.7/dagger_v0.3.7_linux_arm64.tar.gz
after:  dagger/releases/0.3.7/dagger_0.3.7_linux_arm64.tar.gz
```
Noticed here: https://github.com/dagger/dagger/pull/4255#pullrequestreview-1229367604
I think the newer name scheme is nicer in that it's more consistent, however It's easier to just go back to the previous naming scheme than it is to try updating install.sh to be compatible with both schemes, so this just goes back to the previous one.
Goreleaser is a little annoying because we can't use `Tag` in nightly, so have to split that out into the separate configs, but should work.
> Make archive names consistent with previous naming scheme.

- sdk/python/src/dagger/api/base.py
- sdk/python/src/dagger/config.py
- sdk/python/src/dagger/exceptions.py
- sdk/python/src/dagger/session.py
- sdk/python/tests/api/test_integration.py
- sdk/python/tests/api/test_integration_sync.py
Fixes #4111
Dagger pipelines can take a long time to run. There’s no good default here so it’s better not to timeout unless the user says so.
> sdk: python: Don’t timeout by default

- codegen/generator/nodejs/templates/src/header.ts.tmpl
- codegen/generator/nodejs/templates/src/method_solve.ts.tmpl
- codegen/generator/nodejs/templates/src/objects_test.go
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/api/utils.ts
Use a more appropriate name. This function is actually computing queries.
Related to issue #4059  cc@TomChv 
> Node.js SDK -  rename queryBuilder func

- website/docusaurus.config.js
- website/src/css/custom.scss
Update css only for node.js docs reference page. Use the latest Dagger UI Library 
- Bring back font family Montserrat only for Title
- Enhance title spacing
- Enhance code readability
Before:
After:
> Node.js SDK - Improve ref docs readability

- sdk/nodejs/README.md
Add a section "Local Development" to the NodeSDK README to explain how use the local library in any Typescript project.
> docs: explain how use local NodeSDK library.

- sdk/nodejs/common/errors/DockerImageRefValidationError.ts
- sdk/nodejs/common/errors/EngineSessionConnectParamsParseError.ts
- sdk/nodejs/common/errors/EngineSessionConnectionTimeoutError.ts
- sdk/nodejs/common/errors/EngineSessionEOFErrorOptions.ts
- sdk/nodejs/common/errors/GraphQLRequestError.ts
- sdk/nodejs/common/errors/InitEngineSessionBinaryError.ts
- sdk/nodejs/common/errors/TooManyNestedObjectsError.ts
- sdk/nodejs/common/errors/UnknownDaggerError.ts
- sdk/nodejs/common/errors/errors-codes.ts
Just some small improvement on errors by adding a const variable ERROR_NAMES holding all possible error names.
> nodesdk: added typesafe error names

- sdk/python/poetry.lock
- sdk/python/pyproject.toml
- sdk/python/src/dagger/engine/download.py
Fixes #4179
Uses [platformdirs](https://pypi.org/project/platformdirs/) to fallback to platform appropriate defaults if `XDG_CACHE_HOME` environment variable isn't set.
Examples:
| Platform | Fallback |
| -- | -- |
| Linux | `/home/acme/.cache/dagger` |
| macOS | `/Users/acme/Library/Caches/dagger` |
| Windows | `C:\\Users\\acme\\AppData\\Local\\dagger\\Cache` |
> Python: Use platform dependent cache dirs

- cmd/dagger/run.go
- cmd/dagger/session.go
- cmd/shim/main.go
- core/integration/dind_test.go
- docs/current/api/254103-build-custom-client.md
- docs/current/api/snippets/build-custom-client/step2/client.php
- docs/current/api/snippets/build-custom-client/step2/main.rs
- docs/current/cli/979595-reference.md
- sdk/go/internal/engineconn/engineconn.go
- sdk/go/internal/engineconn/env.go
- sdk/go/provision_test.go
- sdk/nodejs/connect.ts
- sdk/nodejs/provisioning/bin.ts
- sdk/nodejs/test/connect.spec.ts
- sdk/python/src/dagger/config.py
- sdk/python/src/dagger/engine/conn.py
- sdk/python/src/dagger/session.py
- sdk/python/tests/engine/test_cli.py
- sdk/python/tests/engine/test_download.py
Related to: https://github.com/dagger/dagger/issues/3830 (see `DAGGER_SESSION_PORT or DAGGER_SESSION_URL?` section of issue description)
Slight tweak which results in our SDKs only ever being expected to connect over 127.0.0.1
> Switch session url to port

- sdk/go/internal/engineconn/cli.go
- sdk/nodejs/package.json
- sdk/nodejs/provisioning/bin.ts
- sdk/nodejs/yarn.lock
Part of https://github.com/dagger/dagger/issues/3830
Windows CLI archives use zips instead of .tar.gz, so we need to handle that in each SDK. Python already had support added in a recent PR, this just updates go+nodejs.
> Add zipfile cli download support for windows.

- cmd/dagger/main.go
- cmd/dagger/session.go
SDKs will soon forward stderr from session binary (if not already). Current `dagger session` command had noise.
When trying to fix the printed errors on stopped engine container, we realized that:
- dagger session errors were double printed
- usage was being printed on stderr, whenever it exited with a code != 0
Context here: https://discord.com/channels/707636530424053791/1003718839739105300/1060253378816520252
As you were the one the `fmt.Fprintf(os.Stderr, "Error: %v\n", err)` line from the main dagger command @marcosnils, do you see any reason we shouldn't just pull our printing of the error?
PS: fixes blocker for  #4284 
cc @jlongtine @sipsma
> fix: session usage and double error prints

- codegen/generator/nodejs/templates/functions.go
- sdk/nodejs/api/client.gen.ts
We forgot to add this in the NodeJS SDK when adding socket API.
It shows we really need to harmonize Go and NodeJS SDK to share more functionalities in the template functions. cf: #4032
> feat(codegen/nodejs): improve Socket SDK object reusability

- internal/engine/docker.go
- internal/mage/engine.go
Related to the docs updates here: https://github.com/dagger/dagger/pull/4232/files#diff-0c99ecf7ccd8b4b55d5e0f38e908be1c2aee1ecf9cad1199170e7b6990b70668R119
Allows us to be dagger specific, not tied to external defaults we don't control.
> Change buildkit config+state to be dagger specific.

- internal/engine/client.go
- internal/engine/docker.go
Part of https://github.com/dagger/dagger/issues/3830
Enables use of the rest the engine connection types we get from buildkit. This includes specific user requests such as `tcp://` support [here](https://github.com/dagger/dagger/issues/3830#issuecomment-1335783010).
> Support the rest of the default buildkitd conns.

- sdk/python/docs/connection.rst
> docs(python): Hide internal member from reference

- internal/engine/client.go
Each SDK handles error messages differently: some of them are unclear, especially the connection errors from `dagger session`.
> Rebased on top of #4303, which removed usage + duplicates output.
1. Followed @sipsma's recommendations.
We now just output the last error sent by Buildkit, which gives enough context to hint users on the way to fix their issue.
This is what it will look like, once the PR gets merged:
2. ⚠️ Only Go SDK is currently impacted by this change, as both Python SDK and Node SDK do not forward stderr for now.
_Next step:_ Creating follow-up PRs, so that SDK owners can add it to their milestones (following discussion with @helderco yesterday)
> feat: improve error message on `dagger session` connection failures

- RELEASING.md
- core/docs/d7yxc-operator_manual.md
Fixes: https://github.com/dagger/dagger/issues/4215
Related: https://github.com/dagger/dagger/issues/3830
Just putting this in the internal docs for now, so it'll only be in markdown on the github repo. Can migrate to official website if desired but after thinking about it more given this is only meant for power users right now it's probably better to leave it off there until it's been more polished+solidified.
> Add docs for custom provisioning and the session interface

- internal/engine/version.go
When using -X to override a variable at link time, this caveat is important:
> This is only effective if the variable is declared in the source
> code either uninitialized or initialized to a constant string
> expression. -X will not work if the initializer makes a function
> call or refers to other variables.
Now we set Version to DevelopmentVersion in an init func instead, which allows it to be uninitialized and thus usable w/ -X.
Test manually on my local machine (need a direct automated test too, but will save for follow up):
```
sipsma@dagger_dev:~/repo/github.com/sipsma/dagger$ go build -ldflags='-s -w -X github.com/dagger/dagger/internal/engine.Version=0.3.8
sipsma@dagger_dev:~/repo/github.com/sipsma/dagger$ ./dagger-test version
dagger …
```
> Fix linktime override of Version var.

- .github/workflows/lint.yml
- .github/workflows/test.yml
Should fix the problem mentioned in `2` [here](https://github.com/dagger/dagger/pull/4338#issuecomment-1376171223) that was noticed during the release. There were duplicated runs for test+lint, one for `pull_request` and one for `push` because we ran the checks against a push to any branch, which includes the branch that the engine bump PR is opened against (`bump-engine`)
> Only runs test+lint on push to main branch.

- cmd/dagger/engine.go
- cmd/dagger/session.go
- engine/engine.go
Add support for `_EXPERIMENTAL_DAGGER_JOURNAL`. This will dump raw
events to a log file, useful for post analysis.
Currently this will only be used internally and is subject to removal.
Related: #4248
> Journal file support

- sdk/nodejs/provisioning/bin.ts
If XDG_CACHE_HOME not set fallback to the system default.
Close to 
- https://github.com/dagger/dagger/issues/3963
> Node.js SDK - use XDG_CACHE_HOME env by default

- .github/workflows/test.yml
- hack/dev
- internal/mage/engine.go
- internal/mage/util/util.go
Because it is a dev dagger-engine that was built from the current source code.
My first instinct was to rename this to `dagger-engine-dev`, similar to `dagger-engine-<SHA>`, but there is garbage collection that uses the `dagger-engine-` prefix, and I didn't want to refactor that in this context. Yes, I was effectively side-stepping that problem since I didn't want to be pulling too much change at once. That is due a refactoring soon, so no point in digging into it now.
By the way, if you have an existing test-dagger-engine running, you will need to remove it manually. You will also need to prune the volume. I recommend:
docker rm -f test-dagger-engine
docker volume prune
---
This is related to a discussion we had with @sipsma in the context of https://github.com/dagger/dagger/pull/4300
> chore: Rename test-dagger-engine to dagger-engine.dev

- internal/mage/sdk/nodejs.go
- internal/mage/sdk/python.go
- internal/mage/util/util.go
`WithDevEngine` implies that the wrapped container will use the dev engine. This is misleading and results in surprising behaviour, as described in https://github.com/dagger/dagger/pull/4300#issuecomment-1379391184
`AdvertiseDevEngine` is more accurate: the dev engine is being advertised for any component that is interested in using it, but nothing is enforced. As we discovered, some components will continue using the engine in which they already run (this used to be the stable engine). The link above goes into more detail - it includes screenshots & diagrams that explain the state better than text alone.
---
⚠️ This should be rebased on top of `main` & merged after https://github.com/dagger/dagger/pull/4371 is merged.
> chore: Rename WithDevEngine to AdvertiseDevEngine

- website/src/css/custom.scss
- Use the new typo size relative to the Dagger style guide.
- Change `code` tags background colors.
> Enhance docs typo readability

- sdk/python/src/dagger/engine/cli.py
- sdk/python/src/dagger/exceptions.py
- sdk/python/tests/engine/test_cli.py
Fixes #4321
`dagger.exceptions.ProvisionError: Dagger engine failed to start`
`dagger.exceptions.SessionError: Dagger engine failed to start: Command '/Users/helder/Library/Caches/dagger/dagger-0.3.9 session' returned non-zero exit status 1. Error: failed to run container: docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.`
> Python: Show errors from session CLI

- sdk/nodejs/.gitattributes
- sdk/nodejs/provisioning/bin.ts
This addresses the issue found in #4389.
Did the following:
- separate cli-downloader functionality from `Bin` class and move it into its own class, `CliDownloader`
- updates tests
> Bugfix: CLI Download for Node.js SDK on Windows

- website/docs-graphql/custom-theme/data/index.js
- website/docs-graphql/custom-theme/helpers/spanWrap.js
- website/docs-graphql/custom-theme/views/partials/graphql/kinds/_fields.hbs
- website/docs-graphql/custom-theme/views/partials/graphql/name-and-type.hbs
This will add an HTML id attribute to each field in each type, and wrap them in an anchor tag to make the fields clickable and shareable.
Closes #4305 
Signed-off-by: Julián Cruciani <julian@dagger.io>
> [GraphQL Reference] add ids and anchor tags to each field

- go.mod
- go.sum
- internal/mage/engine.go
- internal/mage/go.mod
- internal/mage/go.sum
- engine: bump buildkit to v0.11.1
- ci: bump go sdk to 0.4.3
> bump buildkit to v0.11.1

- core/integration/container_test.go
- core/schema/container.go
- core/schema/container.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Closes https://github.com/dagger/dagger/issues/4245
Closes https://github.com/dagger/dagger/issues/3887
Allows user to have the complete control over the labels of a given container:
- Add a label (`withLabel` API)
- Remove a label (`withoutLabel` API)
- Print the value of a single label (`label` API)
- Print all the labels of a container (`labels` API)
Adds corresponding graphQL tests, SDK codegen and graphQL docs.
The terminology is consistent with other APIs (cf. envVariable), and will help solving inherent docker issue https://github.com/moby/moby/issues/3465
> Implement label API

- core/docs/d7yxc-operator_manual.md
The state path changed recently, this catches up the doc with it. Hit by user here: https://discord.com/channels/707636530424053791/1065955877678501919/1066073015307223101
> Fix engine state path in operator manual.

- core/schema/container.graphqls
- core/schema/platform.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Close to #4434 
Curly braces were generating warnings while generating reference documentation.
> GraphQL comments - Replace curly braces with square brackets

- sdk/nodejs/package.json
- sdk/nodejs/yarn.lock
This library was used in a previous SDK version
It's not used anymore
> Node.js SDK - Remove axios dependency

- docs/current/sdk/nodejs/snippets/get-started/step3/build.js
- docs/current/sdk/nodejs/snippets/get-started/step3/build.mjs
- docs/current/sdk/nodejs/snippets/get-started/step3/build.mts
- docs/current/sdk/nodejs/snippets/get-started/step4/build.js
- docs/current/sdk/nodejs/snippets/get-started/step4/build.mjs
- docs/current/sdk/nodejs/snippets/get-started/step4/build.mts
I ran through these quickly after a release and couldn't compile the typescript version due to the `node` var not being of type string when provided as the `id` of a `container`.
Fixing this by just not using IDs; you can just use `node` directly.
> Fix container use in nodejs get started guide.

- sdk/nodejs/common/errors/EngineSessionErrorOptions.ts
- sdk/nodejs/common/errors/errors-codes.ts
- sdk/nodejs/common/errors/index.ts
- sdk/nodejs/provisioning/bin.ts
Close to https://github.com/dagger/dagger/issues/4322
Buildkit sessions errors should be displayed with and without `LogOutput` config parameter
> Fix session error handling

- core/host.go
Closes #4458
When using `.Export()`, workdir scope is checked using `strings.HasPrefix()`.
However, on Windows:
`workdir` and `dest` have different separators, making this comparison break.
We now rely on `filepath.ToSlash` to make sure `dest` and `wd + "/"` are resolving to the comparable path
Given this repro, on Windows:
```go
package main
import (
"context"
"fmt"
"os"
"dagger.io/dagger"
)
func main() {
ctx := context.Background()
client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stdout))
if err != nil {
fmt.Printf("Error connecting to Dagger Engine: %s\n", err)
os.Exit(1)
}
defer client.Close()
// src := client.Host().Directory(".")
golang := client.Container().From("golang:latest")
// golang = golang.WithMountedDirectory("/src", src).WithWorkdir("/src")
// path := "build/" …
```
> engine: fix Export on Windows (workdir verification)

- website/docusaurus.config.js
- website/env.example
- website/netlify.toml
- website/package.json
- website/src/theme/DocPage/index.js
- website/yarn.lock
Amplitude has been replaced by Posthog and should be completely removed from the docs website.
> Docs website - Replace Amplitude with Posthog

- core/container.go
Fixes https://github.com/dagger/dagger/issues/4085
Merges existing env vars with the container env vars.
> fix: Merge container from env vars with existing env vars

- website/package.json
- website/yarn.lock
This commit upgrades Docusaurus to 2.3.0 and fixes errors in the yarn.lock file arising from the auto-upgrade of the mermaid component by dependabot. See https://discord.com/channels/707636530424053791/1070067396196454481 and https://github.com/dagger/dagger/commit/ba9b44256337d68f2cfd9f55ffc7103eaed212c2
> Fixed docusarus versions in yarn lock file

- docs/current/quickstart/349011-quickstart-build.mdx
- docs/current/quickstart/429462-quickstart-build-dockerfile.mdx
- docs/current/quickstart/472910-quickstart-build-multi.mdx
- docs/current/quickstart/628381-quickstart-sdk.mdx
- docs/current/quickstart/635927-quickstart-caching.mdx
- docs/current/quickstart/730264-quickstart-publish.mdx
- docs/current/quickstart/947391-quickstart-test.mdx
- Remove step to cd into the `ci` directory since it's not required
cc @vikram-dagger @kpenfound 
We're removing this since it can be done from the repo root directory and could confuse users as they `cd` into the `ci` directory and then trying to run their pipelines will fail because they need to run it from the repo root.
LMKWYT.
> Add quickstart fixes

- cmd/otel-collector/main.go
- cmd/otel-collector/traces.go
- hack/make
- internal/mage/util/util.go
`./hack/make engine:dev` and `./hack/make engine:test` feeding data into the same `journal.log` resulted in spans that didn't make sense. Some spans would switch to a later group (i.e. `engine:test`), yet the started & completed timestamps would clearly belong to a former group (i.e. `engine:dev`).
When we did update the started & completed timestamps, we realised that we were overwriting previous vertices, the uncached ones, with cached timings, which also didn't make sense.
The easiest thing is to only track the first vertex, the uncached version, and ignore the cached ones. This means that once a vertex is solved in i.e. `engine:dev`, we don't show it again in `engine:test`, since it's cached and less significant timing-wise (it rounds down to 0 micros).
In order to do this better, we …
> ci: Improve how we handle cached vertices

- codegen/generator/nodejs/templates/src/testdata/type_test_scalar_want.ts
- codegen/generator/nodejs/templates/src/type.ts.tmpl
- sdk/nodejs/api/client.gen.ts
This utilises distinct empty types in TS to make the TS compiler recognise custom scalar types as distinct. For example,
```ts
type ContainerID = string & {__ContainerID: never}
```
Will result in a type error if a user passes a regular string into a function accepting this type (the dagger SDK has since changed its arg, but the type benefit works the same way):
```ts
async function container(id?: ContainerID): Promise<Container> {}
container('alpine:latest') // this will throw a type error
container('alpine:latest' as ContainerID) // only explicit typing allows users to pass this arg
```
Since these kind of types require explicit type assertion, they are extremely useful for types that we only expect to be passed between dagger functions (passing the output of one function to the input …
> Generate strictly typed scalars for improved type safety

- docs/current/api/254103-build-custom-client.md
- docs/current/api/975146-concepts.md
- website/docusaurus.config.js
Fix some things in GraphQL API docs
-  Enable syntax highlighting of PHP & Rust in docusaurus which is not enable by default (https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages). The code blocks of these languages are here (https://docs.dagger.io/api/254103/build-custom-client#step-2-create-an-api-client).
- Fix schema of one of the GraphQL response
Signed-off-by: Rahul Modpur <rmodpur@gmail.com>
> docs: Fix Rust,PHP syntax highlight and API response in GraphQL docs

- sdk/go/internal/engineconn/session.go
Without this the child proc became a zombie, which isn't good if lots of clients are being made in a long-running process.
Additionally, this may fix an issue where it seems that the Go GC is collecting the stdin pipe object for the child process before the process has closed.
***Might*** fix https://github.com/dagger/dagger/issues/4538 (running tests locally to see if I can reproduce it still with this change, have not so far).
Either way though, we want to merge this change anyways since it stops zombies, so good to review right away.
Hypothesis: the problem in https://github.com/dagger/dagger/issues/4538 occurs when you have a pipeline like `c.Container().From(...).WithExec(...).ExitCode(ctx)` but you have no more references to `c` after …
> go sdk: Wait on session child processes.

- RELEASING.md
Noticed a few things during the release today:
1. We need a note in the instructions about the engine bump PR workflows not running automatically
2. The SDK tests being run manually have been automated on both macos and linux, there's no need to run them anymore
3. We didn't have any explicit instructions on verifying the sdk publishes worked, added those
> Update RELEASING.md instructions on testing

- .github/workflows/test-publish.yml
- internal/mage/engine.go
Fixes the publish errors happening in main right now: https://github.com/dagger/dagger/actions/runs/4128172221/jobs/7133047657
There's a cross-compilation issue when building runc due to its use of CGO. Instead of setting up the cross compilation tool chains I opted to just download the official release as it's highly unlikely we will need to use anything besides an officially release runc binary.
This wasn't caught before merge because our PR workflows only built an engine image for the host platform, so I also added a quick extra workflow that verifies the engine builds for each platform too.
> Download runc binary instead of building it. 

- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- RELEASING.md
since GHA workflows don't run for PR's created with the default
$GITHUB_TOKEN, we're opening the PR in `draft` state instead and then
triggering the worklow based on the `review_requested` event type.
closes #4050
> ci: simplify step to run workflows for bump PR

- .github/workflows/test-publish.yml
- engine/remotecache/cache.go
- internal/engine/docker.go
- internal/mage/cli.go
- internal/mage/util/util.go
Code imported by the CLI was importing a constant from the new
remotecache package in dagger, but that created a transitive dependency
on some containerd packages which only build for Linux. This was causing
builds of the CLI for darwin to fail.
This works around that issue by reversing the import dependency so that
the remotecache package imports from `internal/engine` instead.
---
Also adding a workflow so we catch this in PRs going forward. This wasn't caught before because PRs only ever built the CLI for their own host platform. Now we test each one that we want to release for.
> Remove import dependency of CLI on containerd packages. 

- core/integration/remotecache_test.go
- engine/remotecache/cache.go
> Use comma instead of semicolon for cache config separator.

- cmd/dagger/main.go
- internal/engine/client.go
This was causing problems because the init ended up in our new cmd/engine/main.go imports and thus disabled all logrus outputs for the daemon.
Fix is to just relocate the disabling of the log output to only exactly where we need it in our cli's main func.
> Disable logrus output only in CLI main.

- codegen/generator/nodejs/templates/src/object.ts.tmpl
- codegen/generator/nodejs/templates/src/testdata/object_test_want.ts
- codegen/generator/nodejs/templates/src/testdata/objects_test_want.ts
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/api/test/api.spec.ts
Close to the issue: 
- https://github.com/dagger/dagger/issues/3885
This first iteration is using  the pattern proposed by @sipsma. 
```ts
func AddAFewMounts(c *dagger.Container) *dagger.Container {
return c.
WithMountedDirectory("/foo", c.Host().Directory("foo").
WithMountedDirectory("/bar", c.Host().Directory("bar")
}
func main() {
output, err := Container().
From("alpine").
WithWorkdir("/foo").
With(AddAFewMounts).
Exec("blah").Stdout().Contents()
...
}
```
@dolanor I know that you're doing some refactoring with the codegen so I'll leave you this part (talking about adding the `with()` method). You can directly push on this PR. Thanks
> Create `with()` method to chain objects

- sdk/python/poetry.lock
- sdk/python/pyproject.toml
These dependencies were installed via some other package. graphql-core by gql and rich by typer. If the project uses them directly then they should be required explicitly.
> chore(python): Explicitly add dependencies used directly in codebase

- core/docs/d7yxc-operator_manual.md
- internal/engine/version.go
This is a follow-up to https://github.com/dagger/registry-redirect/pull/1.
Merging this is a requirement for https://github.com/dagger/dagger.io/pull/1756 (private repo).
> Pull engine image from registry.dagger.io

- core/directory.go
- core/integration/directory_test.go
This wasn't working with non-"root" directories, i.e. directories with a sub-dir, as they often are when coming from a container, which is often when you would want to tweak the timestamps.
> fix Directory.WithTimestamps with subdir

- sdk/python/src/dagger/__init__.py
- sdk/python/src/dagger/api/base.py
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- sdk/python/src/dagger/codegen.py
- sdk/python/src/dagger/exceptions.py
- sdk/python/tests/api/test_integration.py
- sdk/python/tests/api/test_integration_sync.py
Related to #3805
With typo in:
https://github.com/dagger/dagger/blob/a1d08f36e8f7af26757038e827a05b111ca24d0d/sdk/python/examples/client-simple/say.py#L14
```diff
-      .from_("python:alpine")
+      .from_("python:alpines")
```
```console
...
raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'docker.io/library/python:alpines: not found', 'locations': [{'line': 3, 'column': 5}], 'path': ['container', 'from']}
```
```console
...
raise QueryError(
dagger.exceptions.QueryError: docker.io/library/python:alpines: not found
```
Exception can be captured easily from the `dagger` package:
```python
try:
anyio.run(main)
except dagger.QueryError as e:
```
Or on a specific query:
```python
try:
result = await ctr.stdout()
except dagger.QueryError as e:
```
Added a …
> Python: Add custom exception for query errors

- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
#4629 was rebased in GitHub when it should have been done locally. Even though there were no merge conflicts, it's easy to forget about auto-generated files.
> fix python linter

- cmd/shim/main.go
- cmd/shim/secret_scrub.go
- cmd/shim/secret_scrub_test.go
- core/container.go
- core/file.go
- core/integration/host_test.go
- core/integration/secret_test.go
- core/integration/services_test.go
- core/secret_scrub.go
This PR provides a way to get the 0.2 feature that would scrub secrets from logs in case if it leaks.
For now, I only handle env var, and the scrub writer is heavily mocked. Also, the files need to be moved around, there will be a refactor later in the PR advancement.
I'll update this description along the implementation.
> Scrub secrets

- core/integration/remotecache_test.go
- engine/engine.go
- engine/remotecache/cache.go
- engine/remotecache/combined.go
- engine/remotecache/s3.go
- go.mod
- go.sum
The code needs cleaning up, thrown together to enable testing of the idea, but it seems to work. Included an integ test that
1. spins up a local s3 implementation (minio)
2. spins up 5 dagger engines that each do cache exports to that s3 endpoint with different execs
3. and finally spins up another new engine that reruns each of the execs from the previous 5 engines and verifies they are cached
Crucially, all 6 of the engines have the exact same cache config settings, all the additive magic is taken care of by our dagger cache exporter.
There's two other commits with related fixes that ensure cache config settings propagate to buildkit correctly and that we don't run cache exports for "subsessions" used to export images.
cc @jlongtine if you want to give this a try. The "additive cache" …
> Additive caching support for S3 backend

- docs/_README.md
- docs/current/quickstart/349011-quickstart-build.mdx
- docs/current/quickstart/429462-quickstart-build-dockerfile.mdx
- docs/current/quickstart/472910-quickstart-build-multi.mdx
- docs/current/quickstart/593914-quickstart-hello.mdx
- docs/current/quickstart/635927-quickstart-caching.mdx
- docs/current/quickstart/730264-quickstart-publish.mdx
- docs/current/quickstart/947391-quickstart-test.mdx
- website/src/components/atoms/embed.js
- website/src/components/molecules/quickstartDoc.js
- website/src/css/atoms/embed.module.scss
- website/src/css/custom.scss
- website/src/css/molecules/quickstartDoc.module.scss
This will add a new layout to the Quickstart as previously thought on #4419.
The idea behind it is to improve the UX by allowing the user to scroll while maintaining the content and the editor in the same viewport.
Before making this change, we must modify every `.mdx` file in the quickstart, as the PoC is only implemented in the `quickstart-publish.mdx` file.
BTW took my time to ship this one as I wanted to maintain the current sidebar + avoid breaking the current structure of the `.mdx` files as having the ability of writing the docs in markdown is key.
Signed-off-by: Julián Cruciani <julian@dagger.io>
> docs: add new layout to quickstart

- cmd/dagger/listen.go
- cmd/dagger/run.go
- cmd/engine/debug.go
- cmd/shim/main.go
- core/container.go
- core/directory.go
- internal/mage/engine.go
- internal/mage/sdk/go.go
- sdk/go/provision_test.go
Decoupling this from #4615; I needed it for a brief period where I was using Go 1.20 features (`errors.Join`). Might as well get the bump out of the way for the future.
Most of these "fixes" are actually disabling `gosec` lints for various places that we spin up a HTTP server. I don't _think_ we're worried about those instances, but I was a bit rushed trying to get the linter happy for my other PR. We can give it more thought here.
> bump golangci-lint, fix lints

- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- sdk/python/src/dagger/codegen.py
#4505 reverted a `codegen.py` change due to an outdated merge in [aad86c7](https://github.com/dagger/dagger/pull/4505/commits/aad86c7cd0e471da4e7297679ba7dcaa4d5e5a40#diff-456e93caaf55f83fa963bff05f16413d26c0bfc01505ee73c7753b915ff22a55).
> chore(python): Revert reversion from outdated merge

- core/integration/git_test.go
- core/integration/http_test.go
- core/integration/services_test.go
- core/integration/suite_test.go
- core/schema/base.go
- core/schema/container.go
- core/schema/container.graphqls
- core/schema/util.go
- engine/engine.go
- internal/engine/docker.go
- internal/mage/engine.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
* Follow-up to #4505 
* Work around for #4652 until we can find a fix
To enable services you'll now need to `export _EXPERIMENTAL_DAGGER_SERVICES_DNS=1`, re-provision the engine, and keep that env var set anywhere you use the client.
Changes:
* only mess with `/etc/resolv.conf` if enabled
* only configure CNI + bridge networking if enabled
* all service related APIs return an error if not enabled
I suspect DNS is the issue (seems always a safe bet), but let's assume the worst and just disable the whole CNI stack so we don't need to do multiple releases.
> Make services feature opt-in

- cmd/dnsname/config.go
- internal/mage/engine.go
Previously we had a kind of wonky `dnsmasq` + `resolv.conf` setup that seemed to work in local testing but appears to cause problems in other environments. (#4652)
I haven't reproduced those issues, but a few potential weird things stuck out that this commit fixes:
* get rid of `search dns.dagger` - we always use qualified domains for container-to-container addresses, so this was unnecessary
* relocate original `resolv.conf` mount to `resolv.conf.upstream` so that updates can propagate without engine restart, rather than copying the contents once at boot
* point `dnsmasq` to `resolv.conf.upstream` instead of `resolv.conf` to avoid any weirdness with dnsmasq finding itself as an upstream server
* put _only_ `dnsmasq` in resolv.conf so we can be sure that it's the source of truth, but …
> Better resolv.conf/dnsmasq setup

- cmd/engine/config.go
- cmd/engine/main.go
- go.mod
- go.sum
- internal/mage/engine.go
- network/network.go
* Follow-up to #4657
* Fixes #4652
Now we handle Buildkit config defaults in `cmd/engine/` on start. We'll load the user-provided config, apply our defaults on top, and then apply the Buildkit defaults.
It also detects the MTU of the default interface and sets the same value in the `bridge` plugin, which should fix #4652
> Apply Dagger engine config defaults at runtime, configure MTU that matches default interface

- cmd/engine/config.go
- core/integration/git_test.go
- core/integration/http_test.go
- core/integration/services_test.go
- core/integration/suite_test.go
- core/schema/container.graphqls
- core/schema/util.go
- engine/engine.go
- internal/mage/engine.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Now that there are no known issues (#4652 is fixed) we can probably make services on by default, with opt-out still available.
I thought about just removing the feature flag, but we might as well give users the option to disable it for the first release or two while all the scaffolding is already in place, just in case something else comes up (as tends to happen with anything networking related).
We should include something like this in the services docs; cc @vikram-dagger:
> The new services feature changes Dagger's entire network stack. If something seems to have broken, you can disable it by setting the following environment variable prior to running the engine:
>
> ```sh
> export _EXPERIMENTAL_DAGGER_SERVICES_DNS=0
> ```
>
> Please report an issue if this is the case!
> Invert services feature flag (opt-out, not opt-in)

- core/pipeline/label.go
- go.mod
- go.sum
Detects data available from within a GitHub Actions run and adds it to the root pipeline labels:
* `github.com/actor` - the `$GITHUB_ACTOR`, usually a user login but this could be a GitHub app too
* `github.com/event.name` - the event name, e.g. `pull_request`
* `github.com/event.action` - the event action, e.g. `synchronize`
* `github.com/pr.number` - PR number, e.g. `4672`
* `github.com/pr.title` - the PR title, e.g. `add labels for github metadata from actions run`
* `github.com/pr.url` - HTML url, e.g. `https://github.com/dagger/dagger/pull/4672`
Confirmed that these labels are detected by temporarily wrapping our test run in `./hack/dev`: [search `!!` in the logs](https://discord.com/channels/707636530424053791/1024352844884738229/1080557663848505414)
> add labels for github metadata from actions run

- core/pipeline/label.go
Adds two more labels when running in GHA:
* `github.com/workflow.name`: `$GITHUB_WORKFLOW`
* `github.com/workflow.job`: `$GITHUB_JOB`
Via the [docs](https://docs.github.com/en/actions/learn-github-actions/variables):
Variable | Description
-- | --
GITHUB_WORKFLOW | The name of the workflow. For example, My test workflow. If the workflow file doesn't specify a name, the value of this variable is the full path of the workflow file in the repository.
GITHUB_JOB	| The [job_id](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_id) of the current job. For example, greeting_job.
> Add GitHub workflow/job name to root pipeline labels

- core/integration/remotecache_test.go
This is not a problem with the services setup so much as it is the remotecache test case where we needed to spin up multiple engines in the same network namespace. There are better fixes noted in the comment of the code but this is a quick harmless unblock.
> Disable CNI for remotecache tests to address flake.

- engine/engine.go
Previously if you had both the console output and journal file sinks enabled, the journal would end up containing vertices with their `Name` stripped down from the JSON CustomName encoding to just the "naked" name. This was happening because the console log consumer was mutating the `*Vertex`. Now we'll make a copy.
> Fix mutating vertex name with LogOutput set

- cmd/engine/config.go
- cmd/engine/main_oci_worker.go
- core/container.go
- core/docs/d7yxc-operator_manual.md
- core/integration/container_test.go
- core/schema/container.graphqls
- engine/engine.go
- internal/engine/client.go
- internal/mage/engine.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
This adds a new bool flag called `InsecureRootCapabilities` to `WithExec` options that enables privileged execution of containers. [See discussion here](https://github.com/dagger/dagger/issues/3874#issuecomment-1452750360) for reasoning behind allowing this to be set in the engine (though the field itself defaults to `false`). The operator manual is also updated with instructions on disabling it if needed.
Went with the name `InsecureRootCapabilities` because it conveys that it's inherently insecure (security onus is on the user) and technically accurate in that it results in root capabilities being inherited by the process (whereas "privileged" is somewhat more ambiguous). Feel free to bikeshed away though.
In the longer run it would be great to give users fine grain settings for which …
> Support privileged executions.

- internal/mage/engine.go
This should fix the macOS publish build failures.
Note: no external impact since this is unreleased code, changed after v0.3.13.
> Fix `grep -v` in entrypoint causing early exit

- core/container.go
- core/errors.go
- core/integration/container_test.go
- core/integration/services_test.go
- core/schema/container.go
- core/schema/container.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Previously `exitCode`, `stdout`, and `stderr` would simply return null if a container had not been executed yet, i.e. a container that's really just an image. Worse, this would actually get turned into the zero-value for each in the Go SDK (`0`, `""`) making it look like a successful exec.
Additionally, it was easy to accidentally use an un-exec'd container as a service, e.g. by running an off-the-shelf `redis` or `postgres` image without including `WithExec(nil)`. You'd get a weird error with an empty hostname.
Now in all cases we'll raise an error when trying to use a container that has never exec'd.
fixes #4668
> Raise error when using container has not been executed

- sdk/python/src/dagger/engine/cli.py
Fixes #4708 
This will lead to more system calls but also more reactive output in the terminal.
> Python: Don’t buffer output from engine

- core/container.go
- core/pipeline/label.go
- engine/engine.go
* Load Git and GitHub labels independently, logging whichever one failed
* Use `go-github.ParseWebHook` since it deals with all the different event payload types
> Fix loading GitHub labels for push events

- docs/current/guides/757394-use-service-containers.md
This commit updates the services guide to use the new feature name "service containers". Note this also updates the URL of the guide page.
> docs: Updated title and content to reflect the final feature name

- engine/remotecache/s3.go
From some brief testing this seemed to reduce the time to prepare layers for remote cache export, with one case previously taking 5 seconds now taking 1 second. This isn't surprising given zstd is generally considered faster than zlib (what underlies gzip, the previous default) in almost all cases.
> Use zstd compression for s3 cached layers.

- website/netlify.toml
- website/src/components/atoms/embed.js
This will add a redirect in the `netlify.toml` to circumvent [this issue](#4640) related to third party cookies in Chrome browsers.
This error appears because Chrome does not allow an `iframe` with different domain to read `localstorage`. Currently, the iframes in the doc point to `play.dagger.cloud`.
Basically, we are changing to `docs.dagger.io` as the source of the iframe, and setting a rule in the `netlify.toml` for the `/embed` path to redirect to the real  `play.dagger.cloud`. This way, we maintain the same origin and the Chrome issue is gone.
> docs: add origin as embed domain

- cmd/engine/main.go
- cmd/engine/operatorClient.go
- core/integration/remotecache_test.go
- core/schema/container.go
- engine/remotecache/cache.go
- engine/remotecache/mountsync.go
- engine/remotecache/s3.go
- internal/engine/client.go
Starting simple here:
1. When the engine starts, it checks its remote cache config for any
cache mount names it should synchronize.
2. If there are any, it checks the s3 bucket (same used for remote layer
caching) for any backups of the cache mount from this engine or any
others in the pool. If it finds any, it synchronizes that locally to
the cache mount.
3. At engine shutdown, it synchronizes the contents of these cache
mounts back to s3, making it available to any other engines in the
pool.
Current caveats:
1. Each engine uploads its backup of the cache mount under its own
prefix in the pool. This prevents any problems with synchronizing the
contents of the same cache mount from differents hosts. This however
means that currently all of these files are persisted separately,
even when …
> Cache mount import/export

- cmd/engine/main.go
- engine/remotecache/cache.go
- engine/remotecache/s3.go
Before this if an async cache export tried to push content that was GC'd by buildkit since the export was requested, then an error could occur. Now we get a lease on the content for that time to prevent GC from deleting it until we no longer need it.
---
Fixes https://github.com/dagger/dagger/issues/4748
Testing this was not straightforward. I only managed to reproduce it reliably by overriding the engine GC config to be `{All: true, KeepBytes: 1}` and also adding a `time.Sleep(30*time.Second)` to the beginning of an export. Otherwise it was hard to even hit this. I can't actually automate that in our integ tests, so for now there's just manual verification of the fix by me running with those temp changes and verifying it no longer reproduced with this PR.
I think in the longer run if we …
> Prevent GC of content pending export.

- core/pipeline/label.go
Author/committer name and email are distinct labels, so in total there are four labels for author/committer:
* `dagger.io/git.author.name`
* `dagger.io/git.author.email`
* `dagger.io/git.committer.name`
* `dagger.io/git.committer.email`
Collects only the first line of the commit message, aka the "title" (verified that this name is accurate via [git docs](https://git-scm.com/docs/git-commit#_discussion)).
* `dagger.io/git.title`
Also silences the noisy default label collection log when not running in repo.
> Collect more git labels, silence noisy log

- core/integration/services_test.go
Per the tin, adds `t.Parallel()` to each test added with services, which speeds up our tests quite a bit.
> Run services tests in parallel

- core/container.go
- core/integration/container_test.go
- core/integration/secret_test.go
- core/integration/services_test.go
- core/schema/base.go
- core/schema/file.graphqls
- core/schema/secret.go
- core/schema/secret.graphqls
- core/secret.go
- engine/engine.go
- engine/remotecache/mountsync.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- secret/store.go
This PR adds a top level query `setSecret(name: String!, plaintext: String!): Secret!` that will associate a user defined secret `name` to a `plaintext` value.
At the same time, we deprecate `file.secret()` as it leaks secrets in the cache. It is not a breaking change, yet. But as it is insecure, I thought of actually breaking the `file.secret()` implementation (especially the one bringing the secret in) by always returning an error. We wouldn't want people to use it nonetheless and have important secrets leaked.
=> viewed with @jlongtine : we keep backwards compatibility, no breaking change
The only information going into the container information would be the secret id which is a base64 of the name of the secret and the sha256(plaintext). It should bust the cache if we change the …
> feat: add dynamic secret API

- website/src/css/custom.scss
This will fix guides rendering, as right now the Table of Contents is being shifted to the bottom of the page because of flex properties.
> docs: fix guides rendering

- .github/workflows/lint.yml
- .github/workflows/publish-sdk-go.yml
- .github/workflows/publish-sdk-nodejs.yml
- .github/workflows/publish-sdk-python.yml
- .github/workflows/publish.yml
- .github/workflows/test-publish.yml
- .github/workflows/test.yml
- internal/mage/go.mod
- internal/mage/go.sum
Sprinkled the cloud token everywhere that we use `./hack/make` and had everything also upload the `journal.log` for debugging.
> wire up v0.4.1 engine journal delivery

- docs/current/543069-index.md
- docs/current/cli/698277-index.md
- docs/current/partials/_how_does_dagger_work.md
- docs/current/quickstart/120918-quickstart-setup.mdx
- docs/current/quickstart/319191-quickstart-basics.mdx
- docs/current/quickstart/429462-quickstart-build-dockerfile.mdx
- docs/current/quickstart/481031-quickstart-conclusion.mdx
- docs/current/quickstart/593914-quickstart-hello.mdx
- docs/current/quickstart/628381-quickstart-sdk.mdx
- docs/current/quickstart/730264-quickstart-publish.mdx
- docs/current/sdk/go/440319-index.md
- docs/current/sdk/nodejs/722802-index.md
- docs/current/sdk/python/459708-index.md
- docs: Reword a few things in the Quickstart
- might be subjective, feel free to reject anything that doesn't stick
- docs: Fix typo
- docs: Make diagram accurate
- the Dagger Engine **is** the OCI container runtime. All pipeline ops run inside the Dagger Engine.
- docs: Drop @latest from the package
- In the case of Go, this will default to the latest published package version, which is what we want. Versioned is unlikely to break in the future, while `latest` is a moving target. In this context, moving targets usually lead to unexpected breakages. I never regretted pinning my dependencies. I consider it good advice at this point, but feel free to drop this commit if you think otherwise.
> docs: Quickstart improvements

- sdk/go/internal/engineconn/session.go
- sdk/nodejs/provisioning/bin.ts
Remote cache export currently still packs layers up synchronously. For particularly large number/size of layers, this can take quite a while (30s has been seen in relatively modest real world cases).
The problem is that this doesn't start until the session has begun to close (specifically, a result has been returned for the `Solve`) but if the client forcibly ends the session while it's happening it will fail (you will see context cancelled errors in the engine logs for the layer packing functions).
The Go and NodeJS SDKs had relatively small timeout settings for how long they would wait after sending SIGTERM/closing stdin before they would send SIGKILL, which meant that it was easy to cause cache exports to fail. The Python SDK however doesn't seem to have a timeout, it will just wait …
> Lower chance of failed cache export by increasing sdk waits.

- codegen/generator/functions.go
- codegen/generator/go/generator.go
- codegen/generator/go/templates/functions.go
- codegen/generator/go/templates/src/object.go.tmpl
- codegen/generator/schema.go
- sdk/go/api.gen.go
- sdk/go/client_test.go
- sdk/go/internal/querybuilder/querybuilder.go
Extends Go template capabilities.
Store scalar type private field to return it if it's set by a list execution.
Add test on list of objects.
Add Schema setter and getter to fetch global GQL
types.
Add utility functions to the Go template.
Improve query builder to also parse a list of objects.
This feature has a simple concept but is actually really hard to implement.
The purpose is to make possible to fetch list of objects.
For the whole context: See #3457.
That implies multiple constraints:
1. How build the GQL query?
Our current way of building GQL query is simple, each method called adds a level of depth.
For instance: `container.ID(ctx)` will build the query `{ query { container { id } } }`.
But it's different for array: you cannot do `container.EnvVariables(ctx).Name(ctx)`.
For 2 …
> feat: improve Go SDK to fetch list of objects

- website/src/css/custom.scss
This will render wider codeblocks inside the guides, as they are too narrow now, and they affect UX.
Closes #4783
> docs: widen guides codeblocks

- website/src/theme/DocTagDocListPage/index.js
- website/src/theme/DocTagsListPage/index.js
With this PR, visiting the `docs.dagger.io/tags` & `docs.dagger.io/tags/{tag}` pages, will return the 404 Not Found default page, behaving the same as with other not found resources.
Closes #4761
> docs: remove default tags pages

- core/gateway.go
- engine/engine.go
Before this, a session with a particularly enormous number of refs being solved could create a CombinedResult that would be greater than the grpc default message size of 16MB. This would cause builds to fail at the very end while trying to return the result to buildkit.
This was in part due to the fact that by just combining every individual ref from each vertex of the dag we were duplicating a ton of LLB.
The new approach instead uses MergeOp to combine all the solved refs together. A MergeOp result will be a cache hit for any individual input to it, so it serves the same purpose as before. But now when we call Marshal on the MergeOp the builtin deduplication of LLB kicks in which greatly reduces the size of what we are trying to send to Buildkit and thus makes it much harder to hit the …
> engine: Use MergeOp to optimize size of CombinedResult.

- cmd/engine/main_oci_worker.go
- cmd/engine/main_test.go
This was already configurable via the config file but a flag is often more convenient to use.
> Add flag for configuring max parallel execs in engine.

- core/pipeline/label.go
- core/pipeline/label_test.go
This label is needed so we can distinguish from `dagger.io/git.ref` which points to a merge commit for PRs. This is the value that should be shown in the UI and tied to a commit status.
> collect `github.com/pr.head` label

- docs/current/guides/757394-use-service-containers.md
This commit corrects variable names in the service containers guide and also rearranges the code tabs to be consistent with other guides. 
Relates to https://github.com/dagger/dagger/pull/4825
> docs: Update service containers guide

- docs/current/sdk/nodejs/783645-get-started.md
This commit adds an instruction for how to create a `tsconfig.json` file for TypeScript users.
Closes #4865
> docs: Added tsc instruction to Node get started

- docs/current/guides/757394-use-service-containers.md
- docs/current/guides/snippets/use-services/use-db-service/index.ts
- docs/current/guides/snippets/use-services/use-db-service/main.go
- docs/current/guides/snippets/use-services/use-db-service/main.py
This commit adds an example of standing up a just-in-time database service for unit testing a PHP application to the service containers guide.
Closes #4866
> docs: Added database example to services guide

- website/sidebars.js
- website/src/css/custom.scss
There's a current issue where the external links in the menu are not rendered correctly.
Docusaurus adds an SVG at the end of these links, but they have an absolute position. This makes the SVG appear at the top of the sidebar (after scrolling up), as it's shown here.
This PR also adds a chain icon next to the `Reference` link for the GraphQL reference for consistency with the remaining references.
> docs: fix external link icons

- docs/current/guides/snippets/use-secrets/sdk/main.py
Remove the extra character from the `.with_registry_auth()` statement
> fix(secrets): remove 'r' from .with_registry_auth statement

- docs/STYLE_GUIDE.md
This commit updates an inaccurate statement in the style guide.
Relates to https://github.com/dagger/dagger/issues/4857#issuecomment-1490035824
> docs: Updated style guide for embeds

- internal/mage/cli.go
We were hitting some errors related to use of generics in a dependency due to the fact that the previous goreleaser image was still on go 1.19.
---
Error was encountered here: https://github.com/dagger/dagger/actions/runs/4598492189/jobs/8122598929#step:5:861
> Upgrade go releaser image to pick up go 1.20.

- sdk/python/src/dagger/api/base.py
- sdk/python/tests/api/test_inputs.py
- sdk/python/tests/api/test_integration.py
Fixes Python bug when using an empty string as an envirnoment variable: https://github.com/dagger/dagger/issues/4821#issuecomment-1491999494
Object to ID resolution had a bug in type checking if an input sequence needed to be resolved into IDs. As strings are also sequences, the `""` was being converted into `[]`, failing GraphQL validation in `withEnvVariable`, which expects a string as value.
> Python: Fix type checking in object id resolution

- docs/current/quickstart/429462-quickstart-build-dockerfile.mdx
- docs/current/quickstart/snippets/build-dockerfile/index.mjs
- docs/current/quickstart/snippets/build-dockerfile/main.go
- docs/current/quickstart/snippets/build-dockerfile/main.py
Use `Directory { dockerBuild }` rather than `Container { build }`, following user feedback that the former is less confusing than the latter.
> Docs: tweak quickstart examples

- website/src/css/custom.scss
Fixes #4878 
Reference: https://docusaurus.io/docs/markdown-features/code-blocks#:~:text=You%20can%20set%20your%20own%20background%20color%20for%20highlighted%20code
> docs: Highlight for better readability on code blocks

- core/container.go
- core/integration/services_test.go
- core/service.go
A small fix so that `withExposedPort` actually sets the `EXPOSE` equivalent config in the resulting container.
> `withExposedPort` also exposes port in OCI image config

- cmd/engine/operatorClient.go
Without this you can get a nil pointer exception when trying to use a secret w/ the cache mount synchronization code paths (currently only when running in k8s w/ `AWS_WEB_IDENTITY_TOKEN_FILE` set)
---
I'll also send out a followup that refactors the code so session initialization is shared between `engine/engine.go` and `cmd/engine/operatorClient.go` which will prevent future problems w/ trying to make sure they are both updated equivalently, but this change is a quick fix in the meantime.
> Set secret store in engine internal session.

- docs/current/api/254103-build-custom-client.md
This commit adds information on how to install and get started with Rust and PHP to the "custom GraphQL client" tutorial.
Closes #4477
> docs: Updated requirements for PHP/Rust tutorial

- sdk/python/src/dagger/engine/conn.py
Follow up to #4892
Async wasn't correctly being detected. Always false.
> Python: fix async detection in session label

- sdk/nodejs/provisioning/bin.ts
Close to the issue: #4823 
After starting to run a pipeline and when users hit ctrl+c early, the child process is killed as it should.
However, as long as the pipeline start to pull an image for instance, the SIGINT is not handle correctly.
The PR should fix that by updating the configuration for the pipes that are established between the parent and child process
> SDK - Node.js - Pipe SIGINT to child process

- core/integration/http_test.go
- core/schema/http.go
Buildkit internally stores some cache metadata of etags and http checksums using an id based on this name, so setting it to the URL maximizes our chances of following more optimized cache codepaths.
The codepaths in Buildkit are here:
1. A hash is used to lookup any possible etag/url-hash metadata from previous http sources: https://github.com/sipsma/buildkit/blob/cf2698c0e4b708127c3aa86c49d51532feee6b82/source/http/httpsource.go#L128-L134
2. That hash is based in part on this getFileName function: https://github.com/sipsma/buildkit/blob/cf2698c0e4b708127c3aa86c49d51532feee6b82/source/http/httpsource.go#L91
3. getFileName will default to just using the llb.Filename if explicitly set: https://github.com/sipsma/buildkit/blob/cf2698c0e4b708127c3aa86c49d51532feee6b82/source/http/httpsource.go# …
> Set HTTP source filename to be URL.

- core/container.go
- core/integration/container_test.go
- core/schema/container.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Allows an exec to skip the entrypoint. This allows folks to implement Dockerfile semantics (e.g. `RUN`, which skips entrypoint) without having to collect the current value, remove it, and add it back afterwards.
[Example use case](https://github.com/vito/bass/blob/0888230999825a59b110f9de2ad9a152519111ad/pkg/runtimes/dagger.go#L342-L364)
> Container: add `withExec(skipEntrypoint: Boolean)`

- sdk/nodejs/provisioning/bin.ts
To keep consistency with all SDK labels name, use nodejs as label instead of node.
Following request from @gerhard https://github.com/dagger/dagger.io/pull/2145
> sdk: nodejs: consistent label name

- core/pipeline/label.go
- core/pipeline/label_test.go
Also: avoid putting a useless 'HEAD' value in `dagger.io/git.branch` when running on a detached HEAD.
> collect `github.com/pr.branch` label

- cmd/engine/main_oci_worker.go
- cmd/engine/main_test.go
- cmd/engine/operatorClient.go
- core/pipeline/label.go
- engine/engine.go
- internal/engine/client.go
When working with a lot of engine instances and clients that may end up connecting to any one of them it can be extremely useful to know which engine a given client connected to.
The engine can be configured w/ a name via a `_EXPERIMENTAL_DAGGER_ENGINE_NAME` env, otherwise it will just default to the hostname. Clients will now log that when they connect to it.
---
I updated the PR to have the client print the name of the engine it connects to while also including the engine name in the root labels for that pipeline so it can theoretically become part of the progress output too @aluzzardi @vito
> Add ability for clients to print which engine they are connected to.

- sdk/go/internal/engineconn/engineconn.go
Fixes #4586 
This seems to be caused by multiple calls to `defaultHTTPClient` on every request.
`DisableKeepAlives` on the existing code also seemed to fixed the issue but I think it's better to avoid creating the transports over and over.
Test output with the fix:
```sh
% go test -run TestLeak -v
=== RUN   TestLeak
2023/04/14 05:11:00 goroutines: 2
2023/04/14 05:11:04 goroutines: 4
2023/04/14 05:11:04 goroutines: 5
2023/04/14 05:11:04 goroutines: 5
STATUS OK
2023/04/14 05:11:05 run: 1	ip: 10.87.0.113/16	elapsed: 1.444526s	goroutines: 7
STATUS OK
2023/04/14 05:11:06 run: 2	ip: 10.87.0.114/16	elapsed: 2.136249917s	goroutines: 7
STATUS OK
2023/04/14 05:11:07 run: 3	ip: 10.87.0.115/16	elapsed: 2.786011667s	goroutines: 7
STATUS OK
2023/04/14 05:11:07 run: 4	ip: 10.87.0.116/16	elapsed: …
```
> Fix goroutine leak for CLI sessions in Go SDK

- cmd/engine/main_oci_worker.go
@marcosnils pointed out this would be useful in the engine logs too
> Print engine name to it's own logs

- docs/current/api/254103-build-custom-client.md
- docs/current/guides/128409-build-test-publish-php.md
- docs/current/guides/snippets/build-test-publish-php/dagger.php
- docs/current/partials/_run_api_client.md
This commit adds a guide about creating a Dagger CI pipeline for a PHP framework application using PHP and a GraphQL client.
Closes https://github.com/dagger/dagger.io/issues/1769
> docs: Added Dagger with PHP and Laravel guide

- internal/mage/util/util.go
Until now, we didn't use a cache for Go modules download in our CI, resulting in a lot of wasteful downloads.
Now, it's loaded directly from the cache.
> ci: use mounted cache for go modules download

- core/integration/directory_test.go
Working on #4971 , I found a mistake in the test for `directory.dockerBuild`. `container.Build` was tested instead.
Here is a quick fix
cc: @jlongtine
> test: fix test for directory.dockerBuild

- go.mod
- go.sum
- internal/mage/util/util.go
See https://github.com/dagger/graphql-go-tools/pull/3
This should improve our test run time pretty significantly, and also improve `dagger run` start time and anything else that creates a Dagger session.
> Bump graphql-tools-go for session start performance fix

- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/api/utils.ts
Closes [#4821](https://github.com/dagger/dagger/issues/4821)
This PR addresses two issues found in the buildArgs function:
- **Empty string values were not processed**: The function was using the if (value) condition, which is falsy for empty strings, causing the code block to be skipped for empty string values. To fix this, the condition has been updated to explicitly check for undefined and null:
```javascript
if (value !== undefined && value !== null) {
// ...
}
```
This change ensures that empty strings are processed correctly.
- **args parameter is undefined or null**: There was no check to handle the case when the args parameter is undefined or null, causing a TypeError when trying to use Object.entries(args). To fix this, a check has been added at the beginning of the function to …
> fix: sdk/nodejs: Handle empty strings and undefined/null args in buildArgs function

- engine/cache/manager.go
Was originally including this fix with a bunch of other updates to the cache mount import/export, but need it on a shorter time frame now.
> Flush cache mounts on cache manager close.

- cmd/dnsname/config.go
- cmd/dnsname/main.go
- network/cni.go
- network/paths.go
Previously we would lock the addnhosts file itself, which in hindsight doesn't make a lot of sense because we also atomically write to it via renaming. This was causing service related tests to hang because concurrent updates weren't synchronizing properly.
> fix flock usage for addnhosts

- core/container.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/schema/container.go
- core/schema/container.graphqls
- core/schema/directory.go
- core/schema/directory.graphqls
- core/secret.go
- core/util.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Now you can pass secrets to a Dockerfile build like in docker with
```Dockerfile
RUN --mount=type=secret,id=xxx,dst=/run/secrets/xxx
```
```
docker build --secret id=xxx,src=/my/file .
```
You can use
```graphql
type Container {
build(dockerfile: [String], platform: [Platform], buildArgs: [BuildArg!], target: String, secrets: [SecretID!]): Container!
}
type Directory {
dockerBuild(dockerfile: [String], platform: [Platform], buildArgs: [BuildArg!], target: String, secrets: [SecretID!]): Container!
}
```
It will mount in `/run/secrets/<secret-id>`, you cannot decide the target mount point with this current API.
It could be improved later on and discussed on how the API should look like.
> feat: pass secrets to Container.Build and Directory.Build

- docs/current/guides/110632-embed-directories.md
Related to https://github.com/dagger/dagger/issues/4574
Adds more context around the https://docs.dagger.io/110632/embed-directories/ docs.
After this PR, readers will know:
- what embedding is
- why is there an example just in Go
> docs: improve Copy Embedded Directories into a Container

- core/container.go
- core/schema/container.graphqls
- core/schema/directory.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
This is breaking the Netlify build. We should probably just HTML escape all these, but this is a quicker fix.
> avoid using HTML chars in doc string

- engine/engine.go
This one's pretty straightforward. Previously we would concurrently write to all event readers, but that meant rapid writes to the same reader could be delivered out-of-order. This was especially likely to happen to vertexes that quickly start and finish.
It looks like the goal was to prevent one slow consumer from blocking all the rest, but I think we're fine; the TUI has an infinitely buffered pipe, and the telemetry is also pushed into a queue and sent in batches, so in practice it should be OK to just block.
> fix out-of-order event delivery

- .golangci.yml
- core/container.go
- core/directory.go
- core/integration/container_test.go
- core/integration/testdata/hello.go
- core/schema/container.go
- core/schema/container.graphqls
- core/schema/directory.go
- core/util.go
- sdk/go/api.gen.go
- sdk/go/internal/querybuilder/marshal.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
fixes #4739
Adds `owner: String` to the following APIs:
```graphql
type Container {
withMountedDirectory(..., owner: String): Container!
withMountedFile(..., owner: String): Container!
withDirectory(..., owner: String): Container!
withFile(..., owner: String): Container!
withNewFile(..., owner: String): Container!
withMountedCache(..., owner: String): Container!
withMountedSecret(..., owner: String): Container!
withUnixSocket(..., owner: String): Container!
}
```
~The `String` type is a bit nebulous and might warrant its own scalar~ (edit: nevermind - https://github.com/dagger/dagger/pull/4932#issuecomment-1508494191). The following formats are supported:
```
user:group # set uid/gid by name
1234:4321  # set uid/gid
user       # same as user:user
1234       # same as 1234:1234
```
This …
> Support configuring ownership (almost) everywhere

- core/cache.go
- core/container.go
- core/directory.go
- core/file.go
- core/host.go
- core/integration/container_test.go
- core/integration/project_test.go
- core/schema/cache.go
- core/schema/container.go
- core/schema/directory.go
- core/schema/file.go
- core/schema/host.go
- core/schema/secret.go
- core/schema/socket.go
- core/secret.go
- core/service.go
- core/socket.go
- core/util.go
- engine/sshsock.go
- project/dockerfileruntime.go
- project/goruntime.go
- project/project.go
- project/pythonruntime.go
- project/tsruntime.go
- router/schema.go
- secret/store.go
Currently every schema type has a set of types like this:
```go
type File struct {
ID FileID `json:"id"`
}
type FileID string
func (id FileID) decode() (*fileIDPayload, error) { ... }
type fileIDPayload struct {
LLB *pb.Definition `json:"llb"`
File string `json:"file"`
}
func (*fileIDPayload) ToFile() (*File, error) { ... }
```
Methods live on `*File` but they constantly have to convert back and forth from their inner `FileID` and the `fileIDPayload`.
This is really clunky, but the goal was to keep the `*File` type immutable. I drafted this out on day 1 on Dagger and never went back to refactor it. Now that the code has grown a bit I've seen quite a few places where we constantly decode/encode/decode/encode within a single code path, which feels grossly inefficient.
So this PR refactors …
> `/core`: refactor away from `fooIDPayload` pattern

- cmd/engine/debug.go
- go.sum
Heap is useful for hunting down memory leaks. Goroutines are useful for general debugging when you want a full stack trace of the entire engine but don't want to send SIGQUIT (which shuts the engine down).
> Add some more debug endpoints to the engine process.

- core/container.go
- core/integration/container_test.go
Empty caches have 755 permissions, so we should be consistent with that when changing ownership.
see https://github.com/dagger/dagger/pull/4932#discussion_r1174164399
> keep 755 perms for cache with changed owner

- sdk/go/internal/querybuilder/querybuilder.go
It's a minor improvement to `querybuilder` performance, given this benchmark:
```go
func BenchmarkBuilder(b *testing.B) {
for i := 0; i < b.N; i++ {
var contents string
root := Query().
Select("foo").
Select("bar").Arg("hello", "world").
Select("field").Arg("test", "test").Bind(&contents)
root.build(context.Background())
_, _ = Query().
Select("a").Arg("arg", "one").
Select("b").Arg("arg", "two").
build(context.Background())
}
}
```
`benchcmp` results:
```
% benchcmp old new 
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                      old ns/op     new ns/op     delta
BenchmarkBuilder-8     11363         10839         -4.61%
benchmark                      old allocs     new allocs     delta
BenchmarkBuilder-8     88 …
```
> Use strings.Builder for querybuilder build method

- core/container.go
A bug seems to be leading to a gigantic `pb.Definition` value which exceeds the gRPC message size. I ran into this when trying to run Bass's tests in Dagger:
```sh
cd bass/
dagger run ./bass/test -i src=./
```
It's really slow for other reasons; more PRs coming! But it should reliably trigger the bug.
I tried to investigate why this was happening, and attempted a fix in Buildkit (changed something from an `x.ys = append(x.ys, ys)` to just `x.ys = ys`), but my fix broke the tests, so I'm not sure if it's right.
Here's a gist for the gigantic `pb.Definition` and the "fixed" one: https://gist.github.com/vito/be84c33a40f243ad472e63b88cce5658
Basically Buildkit is repeatedly adding the same source information hundreds of times. I think this is partly caused by the fact that we propagate mounts …
> strip sourcemap from Dockerfile builds

- codegen/generator/go/templates/functions.go
- codegen/generator/go/templates/src/object.go.tmpl
- sdk/go/api.gen.go
- sdk/go/client_test.go
Refactor Go codegen to pass memory address of fields directly to Objects.
Otherwise, we would only return references to the values of the last object in the list
Example: 
Let's see the behavior of `EnvVariables()`:  it used to return n times the last env var encountered.
_Prior fix_
```shell
go run .
len: 5
{q:<nil> c:<nil> name:0x140001a01a0 value:0x140001a01b0}
var [tutu:titi]
{q:<nil> c:<nil> name:0x140001a01a0 value:0x140001a01b0}
var [tutu:titi]
{q:<nil> c:<nil> name:0x140001a01a0 value:0x140001a01b0}
var [tutu:titi]
{q:<nil> c:<nil> name:0x140001a01a0 value:0x140001a01b0}
var [tutu:titi]
{q:<nil> c:<nil> name:0x140001a01a0 value:0x140001a01b0}
var [tutu:titi]
```
We see that each object points to the same memory address
_After fix_
```shell
go run .
len:3, total: |[{q:<nil> c:<nil> …
```
> fix: Go SDK: returned list of objects have same memory address

- cmd/dnsname/files.go
- cmd/engine/main.go
- network/dnsmasq.go
This fixes a couple of issues:
* Occasional `connection refused` errors, caused by configuring `bind-dynamic`
* Buggy atomic write implementation leading to missing/empty/partially-written `addnhosts` file
* Fixed up the setup sequence to avoid noisy red-herring error logs
It also changes `dnsmasq` to just run in the foreground and send its logs to the engine logs, rather than daemonizing.
> dnsmasq: stability improvements + greater debuggability

- cmd/engine/main.go
- cmd/engine/operatorClient.go
- core/integration/engine_test.go
- core/integration/remotecache_test.go
- hack/dev
- internal/mage/engine.go
Those signals were resulting in graceful shutdown before but the engine still exited non-zero because some errors were set to context canceled.
This also adds a test case and some associated plumbing so that the tests that spin up an additional engine work with ./hack/dev too.
---
cc @jlongtine was able to make good use of all the new setup from your recent refactorization here, also tweaked it to make the nested engine tests work with ./hack/dev
> Ensure engine exits 0 when it receives SIGTERM/SIGINT.

- cmd/engine/main.go
- core/integration/engine_test.go
- network/dnsmasq.go
@vito the engine exit test caught something with the dnsmasq changes, just needed to update the child proc to use CommandContext
> engine: Ensure that dnsmasq subprocess is killed

- docs/current/quickstart/349011-quickstart-build.mdx
- docs/current/quickstart/429462-quickstart-build-dockerfile.mdx
- docs/current/quickstart/472910-quickstart-build-multi.mdx
- docs/current/quickstart/593914-quickstart-hello.mdx
- docs/current/quickstart/635927-quickstart-caching.mdx
- docs/current/quickstart/730264-quickstart-publish.mdx
- docs/current/quickstart/947391-quickstart-test.mdx
This commit fixes inconsistent tab labels in code snippets, from `Node` to `Node.js`.
Closes #4935
> docs: Fixed inconsistent Node.js tab labels

- docs/current/sdk/python/628797-get-started.md
This commit adds additional optional instructions for creating a Python virtual environment in the Python SDK get started guide.
Closes #5027
> docs: Clarified Python get started steps

- core/container.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/remotecache_test.go
- core/integration/services_test.go
- core/schema/container.go
- core/schema/container.graphqls
- docs/current/guides/snippets/use-services/persist-service-state/index.ts
- docs/current/guides/snippets/use-services/persist-service-state/main.go
- docs/current/guides/snippets/use-services/persist-service-state/main.py
- docs/current/guides/snippets/use-services/test-service-lifecycle-1/index.ts
- docs/current/guides/snippets/use-services/test-service-lifecycle-1/main.go
- docs/current/guides/snippets/use-services/test-service-lifecycle-1/main.py
- docs/current/guides/snippets/use-services/test-service-lifecycle-2/index.ts
- docs/current/guides/snippets/use-services/test-service-lifecycle-2/main.go
- docs/current/guides/snippets/use-services/test-service-lifecycle-2/main.py
- docs/current/guides/snippets/use-services/test-service-lifecycle-3/index.ts
- docs/current/guides/snippets/use-services/test-service-lifecycle-3/main.go
- docs/current/guides/snippets/use-services/test-service-lifecycle-3/main.py
- docs/current/guides/snippets/use-services/use-db-service/index.ts
- docs/current/guides/snippets/use-services/use-db-service/main.go
- docs/current/guides/snippets/use-services/use-db-service/main.py
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Fixes #4833, DAG-282
You had to add an unintuitive `WithExec(nil)` to execute the *`entrypoint` + `defaultArgs`*, otherwise a *“no command has been executed”* error would be returned. This was confusing to some users.
```diff
_, err := client.Container().
Build(src).
+   WithExec(nil).
ExitCode(ctx)
```
```diff
db := client.Container().From("postgres").
WithExposedPort(5432).
+    WithExec(nil)
ctr := app.WithServiceBinding("db", db)
```
Using `ExitCode`, `Stdout`, `Stderr` and `WithServiceBinding` will now implicitly add the `WithExec(nil)` to run default command:
```go
// ✅ ExitCode → needs execution so use default exec
_, err := c.Container().From("alpine").ExitCode(ctx)
```
```go
// ✅ WithServiceBinding → needs execution so use default exec
db := …
```
> core: Implicitly call `entrypoint` + `defaultArgs` when needed

- cmd/dagger/debug.go
- cmd/dagger/main.go
This is lifted straight from `cmd/engine/main.go`. Needed it because I was trying to profile a process that was running out of memory and churning CPU, but profiles weren't being saved because I had to kill the process.
> add `--pprof` flag for serving net/http/pprof handlers

- cmd/engine/debug.go
- cmd/engine/logger.go
- cmd/engine/main.go
- cmd/engine/main_oci_worker.go
- cmd/engine/main_test.go
- cmd/upload-journal/main.go
- core/integration/engine_test.go
- engine/engine.go
- go.mod
- go.sum
- internal/mage/engine.go
- telemetry/telemetry.go
Cloud endpoint is ready and did some load tests, they generated ~50k engine log events over ~30 mins (~28 events/sec) without any obvious performance issues.
Also added a separate commit for logging cpu/mem/disk metrics once a minute
> Add support for pushing engine logs to cloud

- engine/cache/manager.go
- engine/cache/mountsync.go
- engine/cache/service.go
For certain settings, S3 pre-signed URLs will sign the URL with the setting name and value, but doesn't include it in the URL as a query string. It's expected that the user of the URL include it as a header with the same value when actually making the request.
Previously, this was just Content-Length, which we handled as a special case but it turns out another such header is `x-amz-acl`, which we currently need to use in order to ensure that uploading to a cross-account bucket will work. This only due to the fact that the cache service still runs on-prem; once it's in the cloud then the generator of the pre-signed URL will always be the owner of the bucket. But until that time, this is required.
Implemented this by having the cache service just give the engine a set of extra headers to …
> cache: Support extra headers for pre-signed URLs

- docs/create_embed_qs.sh
- docs/current/quickstart/349011-quickstart-build.mdx
- docs/current/quickstart/429462-quickstart-build-dockerfile.mdx
- docs/current/quickstart/472910-quickstart-build-multi.mdx
- docs/current/quickstart/593914-quickstart-hello.mdx
- docs/current/quickstart/635927-quickstart-caching.mdx
- docs/current/quickstart/730264-quickstart-publish.mdx
- docs/current/quickstart/947391-quickstart-test.mdx
- docs/current/quickstart/snippets/publish/main.go
This commit updates the quickstart embed creation script to use the repo at github.com/dagger/hello-dagger as source and also updates the embeds and their IDs.
Closes DAG-921
> docs: Updated embeds to use correct repo

- cmd/shim/main.go
- core/gateway.go
- core/integration/container_test.go
This is primarily needed to workaround an issue in Buildkit where a series of bugs can result in container stdout/stderr resulting in runc getting blocked trying to write to its output pipes and never exit.
That needs an upstream fix but we can make it much rarer by reducing the amount of output our shim can send in the case where its printing stdout/stderr after an exec failure, which is the main place we hit the bug previously.
We were already truncating that output anyways, but we were doing it in the session. This updates the truncation to happen in the shim itself, which is slightly more complicated but avoids the bug and is technically more performant in general anyways.
---
Upstream issue: https://github.com/moby/buildkit/pull/3832
The actual error is flaky to reproduce and …
> Truncate stdout/stderr from shim rather than session.

- cmd/engine/logger.go
- telemetry/event.go
- telemetry/telemetry.go
[not to be merged before making API changes]
This makes the `run_id` event field optional.
> telemetry: make run_id optional

- cmd/dagger/run.go
`dagger help run` after fix:
```
Examples:
Run a Dagger pipeline written in Go:
dagger run go run main.go
Run a Dagger pipeline written in Node.js:
dagger run node index.mjs
Run a Dagger pipeline written in Python:
dagger run python pipeline.py
. . .
```
Before fix:
> fix: Correct help output examples for dagger run

- docs/current/guides/541047-alternative-runtimes.md
This commit adds a guide on using Docker alternatives with Dagger.
Closes #5017
> docs: Added guide on Docker alternatives

- website/sidebars.js
This commit removes the CUE SDK links from the `current` docs website navbar.
> docs: Removed CUE SDK links from navbar

- docs/current/quickstart/635927-quickstart-caching.mdx
- docs/current/quickstart/snippets/caching/main.py
This commit fixes an error in the code snippet for the quickstart Python caching example, to match the other caching examples.
> docs: Fixed error in quickstart caching embed (py)

- sdk/python/src/dagger/config.py
This allows using a `anyio.Path` instead of `pathlib.Path`, or similar "path-like" objects.
This change is only noticeable in the IDE.
> python: Broaden `Path` type in `Config`

- docs/current/quickstart/349011-quickstart-build.mdx
- docs/current/quickstart/429462-quickstart-build-dockerfile.mdx
- docs/current/quickstart/472910-quickstart-build-multi.mdx
- docs/current/quickstart/593914-quickstart-hello.mdx
- docs/current/quickstart/635927-quickstart-caching.mdx
- docs/current/quickstart/730264-quickstart-publish.mdx
- docs/current/quickstart/947391-quickstart-test.mdx
After #5087 I realized the Node tabs in Quickstart weren't working. It was because of an incomplete change in:
- #5018.
> docs: Fix quickstart Node.js tabs

- .github/dependabot.yml
**Configure Dependabot to bump dependencies `monthly`** because `daily` results in too much noise. It makes it more difficult to spot "real" contributions vs. "noisy ones".
With a reduced frequency (monthly instead of daily), this gives us the chance to update the things that we care about ourselves. It is known for some updates to result in breakages further down the pipeline, e.g. https://github.com/dagger/dagger/pull/4850
FTR: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
**Append extra labels to Dependabot PRs**. We were missing a few dependency update areas, e.g. `engine`, `cli`, `tooling`.
**Configure Dependabot to ignore patch updates**. FTR: https://docs.github.com/en/code-security/dependabot/dependabot-version …
> tooling: Reduce frequency of Dependabot PRs

- sdk/go/internal/querybuilder/marshal_test.go
- Adds test coverage for additional marshalling functionality [here](https://github.com/dagger/dagger/blob/main/sdk/go/internal/querybuilder/marshal.go#L67) and [here](https://github.com/dagger/dagger/blob/main/sdk/go/internal/querybuilder/marshal.go#L144).
> Minor test coverage improvement for marshalling functions

- core/file.go
- core/gateway.go
- core/integration/file_test.go
- core/integration/suite_test.go
This PR implements a chunked reader for the `File.Contents` method. A maximum chunk size constant is used to overcome the issue with default gRPC message size (`MaxFileContentsChunkSize`), this chunk size is fixed and currently set around 95% of the default gRPC message size (`0.95 * 16777221`) to leave some margin for any PB overhead (from a quick inspection seems this is pretty lightweight and there seems to be a single field in the message [here](https://github.com/moby/buildkit/blob/1e725ca8da95782188e6e5ae4dac3c07afaf4511/frontend/gateway/pb/gateway.proto#L185)). This can probably be optimized on a future iteration.
A `MaxFileContentsSize` constant is introduced so that we error on files that are too big (current magic number suggested by @sipsma is 128 MB).
I've added a two-step …
> Implement chunked reader for File.Contents

- website/sidebars.js
- website/src/css/custom.scss
This commit makes the left sidebar menu collapsible so that the entire menu is visible without scrolling.
Closes #4934
Closes DAG-917
> docs: Made sidebar menu collapsible

- internal/engine/version.go
A few things went wrong here:
* Homebrew sets [Version=v1.2.3](https://github.com/Homebrew/homebrew-core/blob/e7bbc68273847775d450f47a5d69da09c961c2cd/Formula/dagger.rb#L31)
* GoReleaser sets [Version=1.2.3](https://github.com/dagger/dagger/blob/7327f3381fe914f0acc754a024176dcc506a703f/.goreleaser.common.yml#L14)
* ImageRef had an accidentally inverted `if !semver.IsValid(Version) {`
* But it "worked" because when Version was `1.2.3` the condition would fail because it was missing the "v" prefix.
As a result, the Homebrew Dagger formula is actually using the `:main` tag, while our Goreleased binaries work fine, but for the wrong reasons.
I decided to normalize Version to semver format (with v prefix) rather than the other way around. We'll start getting `x-dagger-engine: v1.2.3` headers …
> fix Version handling

- sdk/go/internal/engineconn/engineconn.go
This should make failures/weird behavior more obvious when using `dagger run`.
The problem is that all `dagger.Connect` configs are ignored when connecting to an existing session. Over time these options should all be removed, but for now we'll raise an error and try to tell the user what to do instead.
Status of all the config options, for posterity:
* `WithConfigPath`: already has `--project` (and no one should be using it anyway)
* `WithNoExtensions`: I don't think I've ever seen this used
* `WithLogOutput`: replaced by TUIs (or generally ways to process/redirect output in the CLI)
* `WithWorkdir`: replaced with `--workdir` and/or using absolute paths + `host.directory`
In practice `WithWorkdir` is the only one to worry about, since it breaks code. The rest are either unused or …
> raise an error for WithWorkdir + existing session

- core/cachemap.go
- core/cachemap_test.go
- core/container.go
- core/schema/container.go
Builds on #5013 to use IDs as cache keys for expensive API requests.
This has by far the largest performance improvement for `dagger run ./bass/test -i src=./` because I use OCI archives for images everywhere. Without this, every single call to `Container.Import` imports the same file every time I run something, spending tens of seconds on redundant I/O that's invisible to the user.
I think it's important for these caches to live on the Dagger side because it frees the API consumer to structure their code however they want. I applied these same optimizations in Bass a couple of weeks ago for the same reason.
> Cache results for Container.Import and Container.Build

- core/integration/directory_test.go
- core/integration/file_test.go
- core/integration/git_test.go
- core/integration/host_test.go
- core/integration/secret_test.go
- Minor improvement, adds `t.Parallel` to some tests that weren't using it.
> Extend parallelization of integration tests

- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/index.ts
To properly use typescript with the Node.js SDK, it should export more types.
In order to fix the cookbook PR #5139, this PR will only cover `Container` type.
Additional PRs will be developed subsequently to accommodate other types.
> NodeJS SDK - Export Container type

- core/pythonruntime.go
- demos/python-entrypoints/main.py
- demos/python-entrypoints/requirements.txt
- sdk/python/experimental/hello/requirements.txt
- sdk/python/src/dagger/__main__.py
- sdk/python/src/dagger/server/__main__.py
Follow-up to https://github.com/dagger/dagger/pull/5060
Python had initial support for entrypoints but because of publishing to Conda, since we didn't publish the extensions code, it was easier to just remove the entrypoint executable from the SDK (in https://github.com/dagger/dagger/pull/4399, `sdk/python/pyproject.toml`):
```diff
- [tool.poetry.scripts]
- # FIXME: uncomment when extensions become available
- # dagger-server-py = "dagger.server.cli:app"
- dagger-py = "dagger.cli:app"
```
This PR recovers `__main__.py` to enable calling with `python -m`, without creating the `dagger-server-py` entrypoint. That executable did allow replacing the entrypoint shell wrapper in the runtime image, apart from needing `cd` to change the workdir when running the runtime entrypoint. But it also …
> Recover app bootstrapping in Python entrypoints

- docs/current/742989-cookbook.md
- docs/current/cookbook/snippets/environment-variables/index.ts
- docs/current/cookbook/snippets/environment-variables/main.go
- docs/current/cookbook/snippets/environment-variables/main.py
Fixes:
- https://github.com/dagger/dagger/issues/4835
This PR introduces a new utility function `env_variables` that can be used to set multiple environment variables. It relies on the `with()` helper that users can rely on to implement their own API wrapper.
> docs: withEnvVariables examples

- cmd/dagger/do.go
- cmd/dagger/engine.go
- cmd/dagger/listen.go
- cmd/dagger/query.go
- cmd/dagger/run.go
- cmd/dagger/session.go
- cmd/shim/main.go
- core/container.go
- core/project.go
- core/schema/base.go
- core/schema/container.go
- core/schema/project.go
- engine/engine.go
- go.mod
- go.sum
- internal/tui/item.go
- internal/tui/model.go
- internal/tui/style.go
- internal/tui/tree.go
- internal/tui/util.go
This PR extracts the TUI setup from `dagger run` and implements it for all other commands that start an engine.
It also does a few other things:
* The inline TUI is now on by default, and the  `_EXPERIMENTAL_DAGGER_TUI` env has been removed.
* The interactive tree TUI is now behind a `_EXPERIMENTAL_DAGGER_INTERACTIVE_TUI` env.
* The interactive tree TUI has been converted to read from a Progrock event stream instead of Buildkit.
* When stdout and stderr are both a non-TTY, the Buildkit console output format will be used instead. This should be replaced with a Progrock equivalent in the future, but this is a cheap stopgap in the meantime.
* `--debug` is no longer required to see console output. It seems a little odd to me to be completely silent by default when there's no TTY, but maybe …
> use TUI for `dagger do`, `dagger query`, `dagger listen`

- cmd/shim/main.go
- core/gateway.go
- core/integration/container_test.go
Fixes https://github.com/dagger/dagger/issues/5077
Related to https://github.com/dagger/dagger/issues/4979
Should show output in error like this:
<pre>
input:1: pipeline.pipeline.container.from.withExec.stdout process "sh -c echo xxxxxxx... && exit 1" did not complete successfully: exit code: 1
Stdout:
<b>[omitting 2412132 bytes]...</b>xxxxxxx....
Stderr:
Please visit https://dagger.io/help#go for troubleshooting guidance.
</pre>
> Prepend truncated error output with notice

- core/gateway.go
- core/integration/container_test.go
Related to https://github.com/dagger/dagger/issues/4979
Increasing the truncation limit hopefully makes it less necessary to add a flag for full output in an error.
\cc @aluzzardi
> Increase truncation limit on error output

- sdk/python/src/dagger/api/base.py
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/codegen.py
- sdk/python/tests/api/test_integration.py
Follow up to https://github.com/dagger/dagger/pull/5071 and part of https://github.com/dagger/dagger/issues/5065
Adds a convenience to `await` on an object directly:
```python
await client.container().from_("alpine").with_exec(["true"])
```
> Python: Add convenience to await on an object that has `.sync()`

- .github/workflows/publish-sdk-rust.yml
We do this just for the Go SDK so that we sync this repository with https://github.com/dagger/dagger-go-sdk, all other SDKs only trigger on tag.
Follow-up to:
- https://github.com/dagger/dagger/pull/5148
> ci: Do not publish Rust SDK on push to `main`

- docs/current/cookbook/snippets/cache-invalidation/main.py
This commit improves the Python cache miss recipe first added in https://github.com/dagger/dagger/pull/5168.
Relates to DAG-1579
> docs: Improved cache miss recipe for Python

- core/integration/container_test.go
- core/schema/container.go
- core/schema/container.graphqls
- core/util.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Fixes https://github.com/dagger/dagger/issues/5140
**Note:** This only applies to `withEnvVariable`.
Common example is to prepend to `$PATH`:
```go
WithEnvVariable("VIRTUAL_ENV", "/opt/venv").
WithEnvVariable(
"PATH",
"${VIRTUAL_ENV}/bin:$PATH",
dagger.ContainerWithEnvVariableOpts{
Expand: true,
},
).
```
In Python:
```python
ctr
.with_env_variable("VIRTUAL_ENV", "/opt/venv")
.with_env_variable("PATH", "${VIRTUAL_ENV}/bin:$PATH", expand=True)
```
> Add expand option when adding environment variables

- core/schema/secret.go
- router/schema.go
Fixes https://github.com/dagger/dagger/issues/5171
Problem before was that we'd serialize all the graphql args and values for every resolver, which included the secret plaintext value.
The fix here is an attempt to give a slightly more general+reusable solution than just putting in a hardcoded `if` in the progrock related code to check for this fieldname+argname pair. It makes the type of the plaintext in our code to be `type SecretPlaintext string` and gives that a `MarshalText` method so progrock shows that instead of the actual value.
--- 
I had a previous version of this that used reflection directly instead of doing another json marshal-unmarshal cycle, but it ended up being way more convoluted: https://github.com/sipsma/dagger/commit/e45690cda3d61a9a24fb329599c333acad79c7e6
So I …
> Scrub secret plaintext arg from progrock vertex.

- sdk/rust/crates/dagger-sdk/src/core/cli_session.rs
I found during reading SDK CONTRIBUTING.md. The rust SDK doesn't set label `dagger.io/sdk.name` and `dagger.io/sdk.version` to the `dagger session`. This changes start by adding the SDK name label to it.
> Add SDK label to rust

- core/integration/container_test.go
First attempt at reducing the performance impact during tests from:
- https://github.com/dagger/dagger/pull/5164
Reported in:
- https://github.com/dagger/dagger/pull/5163#issuecomment-1563075893
> Reduce size of extra content in error output truncation test

- cmd/engine/debug.go
- cmd/engine/main.go
If trace logs are enabled, this can be very useful for identifying stuck or leaked goroutines.
I also tried using `debug.WriteHeapDump`, which would be even more powerful, but it was taking up more than 10GB to log and apparently includes raw memory contents of everything (including secrets), so not viable at this time...
> engine: enable full goroutine stack trace dump in trace logs.

- docs/current/quickstart/snippets/build/main.py
Fix minor spelling issue in Python build quickstart docs
> docs: Fix minor spelling issue in Python build quickstart docs

- docs/current/quickstart/947391-quickstart-test.mdx
There is only one version of the "tip" on the quickstart test page, but it should contain different method / function names for Go, Node.js, and Python. This PR places the tip in each tab with correct method names (as well as fixes one or two other typos on the page).
> docs: Fix tip content in quickstart test

- engine/engine.go
It seems it's common in dev environments running in containers for the user runtime dir to not exist and not be creatable w/out sudo, which results in permission denied errors when the tui sets up the progrock socket.
This adds a fallback to use the home cache dir in such cases. This isn't as ideal since that dir isn't a tmpfs, but is better than failing I think. A warning is printed when this happens to let users know.
> tui: Add fallback for runtime dir permission denied errors.

- engine/cache/service.go
otherwise we get a nasty nil pointer exception: 
```
time="2023-05-26T17:05:16Z" level=debug msg="using cache service at localhost:8020/magicache"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6e0fd4]
goroutine 1 [running]:
net/http.(*Client).deadline(0xc000665520?)
/usr/local/go/src/net/http/client.go:189 +0x14
net/http.(*Client).do(0x0, 0xc00064e700)
/usr/local/go/src/net/http/client.go:600 +0x225
net/http.(*Client).Do(...)
/usr/local/go/src/net/http/client.go:582
github.com/dagger/dagger/engine/cache.(*client).GetConfig(0xc000109ab8, {0x1ca7af8?, 0xc0000b6a00}, {{0xc0002b2fe0?, 0x1cb2780?}})
/app/engine/cache/service.go:261 +0x3f3
github.com/dagger/dagger/engine/cache.NewManager({0x1ca7af8?, …
```
> cache: return error if cacheservice scheme is not supported

- engine/engine.go
Follow up to https://github.com/dagger/dagger/pull/5210
Realized as I was running something else that the LogOutput can be nil, in which case we shouldn't try to write to it
> engine: handle LogOutput being nil

- docs/current/162770-faq.md
- docs/current/quickstart/730264-quickstart-publish.mdx
This commit corrects a statement in the quickstart regarding registry authentication support in Dagger.
> docs: Updated quickstart for registry auth methods

- core/integration/remotecache_test.go
- internal/mage/engine.go
I was wondering why the tests were taking so long as of late, noticed that the remote cache tests had a huge jump in execution time on [this commit](https://github.com/dagger/dagger/commit/f5f76fcbda4b772a54aecc43812bd03e51c0d62c):
* [Before](https://github.com/dagger/dagger/actions/runs/5017303368/jobs/8995255666#step:5:12833)
* [After](https://github.com/dagger/dagger/actions/runs/5025704148/jobs/9013022074#step:5:12781)
The only possible connection point I could see was nested sessions, so tried this and found it worked ([here's the new time from this PR's run](https://github.com/dagger/dagger/actions/runs/5126725502/jobs/9221586856?pr=5224#step:5:12613)), but have not debugged why the new progress forwarding would have this sort of impact @vito
> tests: fix slowness by disabling unnecessary session nesting.

- go.mod
- go.sum
- sdk/go/go.mod
- sdk/go/go.sum
- sdk/go/internal/querybuilder/marshal.go
- sdk/go/internal/querybuilder/marshal_test.go
In order to properly escape strings, especially binary data on Go SDK, we now follow graphQL's spec around strings escape. 
This fix only fixes the escape of UTF-8 unicodes, as the JSON Unmarshall of Go correctly escapes these unicodes, when unmarshalling as a String.
For the mount of binary files, we will need to follow an alternative. Discussion happening here: https://github.com/dagger/dagger/issues/5069
Thus, we expect to have, as inputs of type string, UTF-8 unicodes. Follow-ups will be implemented for other SDKs, if necessary.
This PR enables the mount / copy of exact bytes sequences inside container, for UTF-8 unicodes, for Go SDK
**main.go**
```go
package main
import (
"context"
"fmt"
"io/ioutil"
"os"
"path/filepath"
"time"
"dagger.io/dagger"
)
func main() {
// initialize Dagger …
```
> feat: follow graphQL spec when encoding UTF-8 unicodes (Go SDK)

- cmd/shim/main.go
- engine/engine.go
- go.mod
- go.sum
Fixes root cause surfaced in https://github.com/dagger/dagger/pull/5224 (verified locally)
Previously the RPC flow required clients to explicitly send a Close RPC call, which wouldn't be sent for services because they are kill -9'd.
Now the RPC flow uses gRPC under the hood and simply uses a graceful shutdown to wait for any in-flight RPC requests to finish, which accomplishes the same thing while also allowing RPC clients to suddenly disappear.
> bump progrock for gRPC + resilient draining

- core/cache.go
- core/container.go
- core/directory.go
- core/file.go
- core/progress.go
- core/util.go
Attempts to address https://github.com/airbytehq/airbyte/issues/26863 though the fixes here are purely theoretical; there's no smoking gun for where the concurrent write actually happened.
Two areas fixed: `overrideProgress` and `Container.Clone`.
This function gets called when starting a service, and previously was directly mutating the `Metadata` map that's present in container's underlying `*pb.Definition` because the map is [carried directly over](https://github.com/moby/buildkit/blob/80b91c55a47feb52a66e143a3929e614dd5c7adc/client/llb/definition.go#L99) when converting it to a `llb.State` (!).
We don't really want to mutate in this scenario anyway; it's purely a runtime concern, and should not affect the original Container, so now this helper returns a copy.
Ultimately this whole …
> Prevent concurrent/leaked mutation in a couple of spots

- sdk/go/client.go
- sdk/go/client_test.go
- sdk/go/error.go
Follow up to #5184
Instead of having to unwrap a custom error:
```go
var e *dagger.ExecError
if errors.As(err, &e) {
return e.ExitCode
}
```
This allows directly casting:
```go
if e, ok := err.(*dagger.ExecError); ok {
return e.ExitCode
}
```
> Enable casting custom errors in Go

- go.mod
- go.sum
Fixes https://github.com/dagger/dagger/issues/4152
This PR intends to test the int64 scalar transition added by https://github.com/dagger/graphql/pull/2.
If:
1. it doesn't break the tests
2. we can indeed get size of file > [2.14gb](https://github.com/dagger/dagger/issues/4152)
Then we can merge the `dagger/graphql` PR and upgrade the commit hash on this PR
It works perfectly:
```go
package main
import (
"context"
"fmt"
"os"
"time"
"dagger.io/dagger"
)
func main() {
// initialize Dagger client
ctx := context.Background()
client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
if err != nil {
panic(err)
}
defer client.Close()
container := client.Container().From("alpine:3.17")
currentTime := time.Now()
timeString := currentTime.Format("15:04:05")
out, err := container. …
```
> feat: update `dagger/graphql` import commit to rely on extended `Int64` scalar

- go.sum
In latest PR https://github.com/dagger/dagger/pull/5227, @helderco  pointed out that I forgot to update the `go.sum` with `go mod tidy`. I merged it before he had the time to add a commit. This fixes it 🙏
> chore: update `go.sum`

- cmd/dagger/engine.go
- cmd/dagger/run.go
fixes #5196 
Alternative to #5197. 
Tackles the same problem but with a different approach: if either stdout or stderr are redirected, respect the redirect rather than writing output to the TUI. I opted to not use a `MultiWriter` because that's how redirects normally work, but I don't feel too strongly about it; if someone has a good reason to also print the redirected content to the TUI I'm all ears.
> dagger run: support redirecting stdout/stderr

- cmd/dagger/engine.go
- cmd/dagger/run.go
- internal/tui/item.go
- internal/tui/tree.go
fixes #5191 
A grab bag of improvements for the interactive TUI:
* Don't exit the TUI on failure (simple regression)
* Move the command vertex back to the root of the tree
* Use vertex input ancestry to determine vertex order within a group
* In follow mode, switch to the command (i.e. root) on completion
To test:
```sh
env _EXPERIMENTAL_DAGGER_INTERACTIVE_TUI=1 dagger run sh -c 'echo hi; sleep 1; echo bye; exit 42'
```
(For a proper test with more vertices you'll need to run a failing Dagger pipeline, but I don't have one handy atm.)
> Interactive TUI: better failure handling

- sdk/rust/crates/dagger-bootstrap/Cargo.toml
- sdk/rust/crates/dagger-codegen/Cargo.toml
- sdk/rust/crates/dagger-sdk/Cargo.toml
- sdk/rust/crates/dagger-sdk/src/lib.rs
no-gen was intended to not provide generated code. However it caused trouble
with no features. As such it has been removed.
Instead --no-default-features and --feature gen are setup to work as it should.
> feat(rust): no-gen didn't work as intended

- internal/tui/vterm.go
We can use `(*bytes.Buffer).WriteString` to avoid unnecessary byte/string conversion calls and reduce allocations.
> tui: avoid unnecessary byte/string conversion

- docs/STYLE_GUIDE.md
This commit adds information about how to contribute recipes to the Dagger Cookbook.
> docs: Added recipe creation info to style guide

- internal/mage/sdk/python.go
`PATH` variable use string concatenation. But since dagger 0.6, we have shell variable expansion. So I think we should use that instead to make sure PATH variable is up-to-date.
> chore: Use expand PATH instead of string concatenation

- cmd/shim/main.go
- core/container.go
- core/gateway.go
- core/service.go
Introduces a custom internal (`--debug`) vertex for displaying health-check logs, replacing the old-and-busted `_DAGGER_DEBUG_HEALTHCHECKS` hack which just dumped them straight to stderr (which is incompatible with TUIs).
The vertex is named after the internal command used to run the healthcheck: `check HOSTNAME 1234/tcp 5678/udp`.
> show health-checks in progress UI

- core/gateway.go
This change attempts to solve one aspect of the flakiness in `TestContainerExecError` of late:
```
#11 230.3 === NAME  TestContainerExecError/truncates_output_past_a_maximum_size
#11 230.3     container_test.go:3032: 
#11 230.3         	Error Trace:	/app/core/integration/container_test.go:3032
#11 230.3         	Error:      	Should be in error chain:
#11 230.3         	            	expected: %!q(**dagger.ExecError=0xc001439718)
#11 230.3         	            	in chain: "input:1: container.from.withDirectory.withExec.sync failed to solve: process \"sh -c base64 -d encout >&1; base64 -d encerr >&2; exit 1\" did not complete successfully: exit code: 1\n\nPlease visit https://dagger.io/help#go for troubleshooting guidance."
#11 230.3         	            		"input:1: …
```
> Fix flakiness in TestContainerExecError test

- codegen/generator/go/templates/src/object.go.tmpl
- sdk/go/api.gen.go
Turns the following generated code:
```go
// Initializes this container from a Dockerfile build.
func (r *Container) Build(context *Directory, opts ...ContainerBuildOpts) *Container {
q := r.q.Select("build")
q = q.Arg("context", context)
// `dockerfile` optional argument
for i := len(opts) - 1; i >= 0; i-- {
if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
q = q.Arg("dockerfile", opts[i].Dockerfile)
break
}
}
// `buildArgs` optional argument
for i := len(opts) - 1; i >= 0; i-- {
if !querybuilder.IsZeroValue(opts[i].BuildArgs) {
q = q.Arg("buildArgs", opts[i].BuildArgs)
break
}
}
```
into:
```go
// Initializes this container from a Dockerfile build.
func (r *Container) Build(context *Directory, opts ...ContainerBuildOpts) *Container {
q := r.q.Select("build")
for i := len(opts) - 1; i …
```
> Simplify iterations for optional args in Go code

- .github/actions/experimental-setup-dagger/action.yml
- .github/workflows/lint-daggerized.yml
Found from
https://github.com/dagger/dagger/actions/runs/5147441125. The `uses`
must have `./` to point to local action. And fixes 2 issues in the
workflow:
First, fix the daggerized job to use `${{ github.ref }}` instead of
`${{ github.sha }}` when setting `DAGGER_PROJECT` because when using
sha, the dagger didn't know the sha commit when sending a Pull Request
from another repo.
Second, fix the `dagger do` argument and passing `--repo` and `--branch`
to the project.
> ci: Fix lint-daggerized.yml error

- core/container.go
- core/integration/container_test.go
- core/integration/services_test.go
- core/schema/container.go
- core/schema/container.graphqls
- core/util.go
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
Follow-up to https://github.com/dagger/dagger/issues/5052 to fix `ExposedPorts` support.
In https://github.com/dagger/dagger/issues/4588 we want to override an existing `Container`’s `Env`, `Labels` and `ExposedPorts` config when using `From` or `Build`. Everything else is completely replaced. The reasoning is that those fields have these corresponding CRUD methods:
| OCI                | Create/Update     | Delete               | List           | 
| ------------------ | ----------------- | -------------------- | -------------- |
| **`Env`**          | `WithEnvVariable` | `WithoutEnvVariable` | `EnvVariables` |
| **`Labels`**       | `WithLabel`       | `WithoutLabel`       | `Labels`       |
| **`ExposedPorts`** | `WithExposedPort` | `WithoutExposedPort` | `ExposedPorts` |
However, …
> Merge exposed ports on From and Build

- core/gateway.go
- go.mod
- go.sum
Bumps `buildkit` version for this fix: https://github.com/moby/buildkit/pull/3940
`go get` also bumped `containerd` to 1.7.2.
> Bump buildkit for ExecProcessServer mutex fix

- ci/engine.go
- ci/go.go
- internal/mage/engine.go
- internal/mage/sdk/go.go
Provides a speed improvement when running the lint pipelines. About a 40 second improvement for the sdk/go lint run.
sdk/go:
Before(4m 22s):
https://github.com/KasonBraley/dagger/actions/runs/5251099871/jobs/9485711433
With this change(3m 40s):
https://github.com/KasonBraley/dagger/actions/runs/5251069261/jobs/9485647687
> ci: Use alpine for golangci-lint image

- auth/registry_test.go
- core/cachemap_test.go
- router/merge_test.go
Like #5134, a minor improvement for tests in `auth`, `core` and `router` subpackages.
> Adds t.Parallel to auth, core and router tests

- website/sidebars.js
The Dagger public changelog is on GitHub; however, you can't easily find that fron docs.dagger.io. This change adds a new **Releases** item to the docs site sidebar. Clicking on this opens [https://github.com/dagger/dagger/releases](https://github.com/dagger/dagger/releases) as a new tab.
> Add a link to GitHub releases in the docs sidebar

- sdk/elixir/lib/dagger/engine_conn.ex
- sdk/elixir/lib/dagger/internal/engine/downloader.ex
Reducing provision complexity in `Dagger.EngineConn` into `Dagger.Internal.Engine.Downloader` and also allow download to custom cli host for future testing.
> sdk(elixir): Move download engine to a new module

- sdk/go/server.go
Couldn't find a way to hide it from pkg.go.dev other than marking it as deprecated, which doesn't feel right, so just updated the doc string.
> sdk/go: Doc that ServeCommands is experimental.

- internal/mage/sdk/elixir.go
- sdk/elixir/mix.exs
Make `HEX_DRY_RUN` to support `true` value and fix VERSION file not include when publishing package. Here is the example when publish with `HEX_API_KEY=abcd HEX_DRY_RUN=true ./hack/make sdk:elixir:publish sdk/elixir/v1.0.0`:
```
+++ dirname ./hack/make
++ cd ./hack/..
++ pwd
+ DAGGER_SRC_ROOT=/Users/thanabodee/src/github.com/dagger/dagger
+ MAGEDIR=/Users/thanabodee/src/github.com/dagger/dagger/internal/mage
+ cd /Users/thanabodee/src/github.com/dagger/dagger/internal/mage
+ exec go run main.go -w /Users/thanabodee/src/github.com/dagger/dagger sdk:elixir:publish sdk/elixir/v1.0.0
Connected to engine 93e4e6b5ead3
#1 resolve image config for docker.io/hexpm/elixir:1.14.5-erlang-25.3-debian-buster-20230227-slim
#1 DONE 0.8s
#2 generate
#2 DONE 0.0s
#3 from …
```
> sdk(elixir): fix publish package issue

- core/host.go
- core/schema/host.go
This ensures we only sync the file we want rather than the whole parent dir.
Noticed this here: https://github.com/dagger/dagger/pull/5308#discussion_r1235799768
> core: use include filter in host.file

- cmd/dagger/do.go
- core/integration/project_test.go
- core/integration/testdata/projects/go/basic/main.go
- core/integration/testdata/projects/python/basic/main.py
We were mutating a common slice across different call branches, which resulted in different call branches overwriting objects in the array underlying the slice and the wrong command sometimes being used.
---
Found by @helderco, thanks!
> cli: fix incorrect subcommand being called.

- cmd/dagger/do.go
- core/integration/project_test.go
Before this, a go command like "ThisCommand" or a python command like "this_command" would end up in the CLI as a command named thisCommand.
The camel casing always struck me as odd in a CLI interface, so this changes camel case to kebab, i.e. "this-command".
This is obviously pretty subjective, but it looks a lot better to me and was very easy to try thanks to the strcase library.
> project: convert camel command names to kebab

- ci/engine.go
- ci/main.go
- core/host.go
- core/integration/project_test.go
- core/integration/testdata/projects/go/basic/main.go
- core/integration/testdata/projects/python/basic/main.py
- core/schema/host.go
This allows you to (usually) return a File or Directory from a command
that has a Local SourceOp somewhere in its LLB DAG. This is very
important as many projects will load source code from the project dir in
order to, e.g. build binaries/containers.
It works by using the session ID setting in local source ops, plus doing
a synchronous evaluate of the local op to ensure its cached.
Technically, it's still possible for the local ref to get pruned between
time of sync and time of use, but this solution is just meant to be
better than before, which always resulted in either an error or the
wrong dir getting loaded.
The long-term robust solution will come from better session sharing.
I considered an alternative solution of having the project API code
rewrite the LLB returned by projects to …
> project: partial support for returning host dirs/files. 

- sdk/elixir/lib/dagger/codegen/elixir/function.ex
- sdk/elixir/lib/dagger/codegen/elixir/module.ex
- sdk/elixir/lib/dagger/codegen/elixir/templates/object_tmpl.ex
- sdk/elixir/lib/dagger/codegen/elixir/templates/scalar_tmpl.ex
- sdk/elixir/lib/dagger/gen/cache_id.ex
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/elixir/lib/dagger/gen/container_id.ex
- sdk/elixir/lib/dagger/gen/directory.ex
- sdk/elixir/lib/dagger/gen/directory_id.ex
- sdk/elixir/lib/dagger/gen/file_id.ex
- sdk/elixir/lib/dagger/gen/project.ex
- sdk/elixir/lib/dagger/gen/project_command_id.ex
- sdk/elixir/lib/dagger/gen/project_id.ex
- sdk/elixir/lib/dagger/gen/query.ex
- sdk/elixir/lib/dagger/gen/secret_id.ex
- sdk/elixir/lib/dagger/gen/socket_id.ex
Uses name from type when found that name is `id` with type id. And remove `get_id` out of scalar modules. Code is now much simpler.
Fixes #5331
> sdk(elixir): fix id argument render incorrectly

- sdk/elixir/README.md
Downloading from git repo requires to set `:sparse` option to get from `sdk/elixir` directory
This should solves confusing from #5326
> sdk(elixir): update README.md on how to download the package

- sdk/elixir/lib/dagger/codegen/compiler.ex
- sdk/elixir/lib/dagger/codegen/elixir/templates/object_tmpl.ex
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/elixir/lib/dagger/query_builder.ex
- sdk/elixir/test/dagger/querybuilder_test.exs
This PR will select all children when the API return list of object. And fix execute/2 to select an object in the list.
Run this code: 
```elixir
Mix.install([
{:dagger, path: "."}
])
client = Dagger.connect!()
container =
client
|> Dagger.Query.container()
|> Dagger.Container.from("nginx:alpine")
container
|> Dagger.Container.env_variables()
|> IO.inspect()
container
|> Dagger.Container.labels()
|> IO.inspect()
container
|> Dagger.Container.exposed_ports()
|> IO.inspect()
```
After run `elixir script.exs`, the result should be: 
```
[
%{
"name" => "PATH",
"value" => "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
},
%{"name" => "NGINX_VERSION", "value" => "1.25.1"},
%{"name" => "PKG_RELEASE", "value" => "1"},
%{"name" => "NJS_VERSION", "value" => "0.7.12"}
]
[
%{
"name" => …
```
> sdk(elixir): fix api that return list of object not working

- cmd/dagger/do.go
- core/integration/project_test.go
- core/integration/testdata/projects/go/basic/main.go
- core/integration/testdata/projects/python/basic/main.py
I noticed while working on user docs that my previous update to kebab command names missed that flags also need kebab-ing.
> project: also kebab flag names.

- engine/engine.go
- internal/engine/docker.go
The cache config env has not been interpreted by the engine container for a long time, it's only interpreted client-side.
> engine: remove old cache config env from autoprovision.

- internal/engine/docker.go
this allows bootstrapping the engine with a cloud cache token if
present. We should eventually refactor this to enable a more dynamic
approach which would allow to change the cloud cache configuration at
runtime.
> engine: add cloud cache token env var

- sdk/elixir/lib/dagger/query_builder.ex
The bug was introduced in https://github.com/dagger/dagger/commit/165786187c91a8cd097645b645e22670e105b3f7. It makes any functions that expected to return scalar value returns map instead. Fixes by detecting selection on the last element and handle this.
Fixes #5342
> sdk(elixir): fix sdk error when calling id function

- core/directory.go
- core/goruntime.go
- core/integration/project_test.go
- core/integration/suite_test.go
- core/project.go
- core/pythonruntime.go
- core/schema/project.go
The project runtime code was leftover from ancient times where it still used raw llb and had its own codepaths separate from WithExec.
Now it's updated to use the Dagger API types and dogfood the Container implementation.
This gives it support for all the customization in WithExec (i.e. progrock sock setup) without needing to duplicate. It also benefits from the "stickiness" of Dagger mounts (relative to llb) such that runtimes can setup their own cache mounts and retain them during resolver execution.
---
Spinning this out from https://github.com/dagger/dagger/pull/5357, where I started going down this path as part of debugging stuff there.
@helderco this fixes the problem you mentioned previously w/ not being able to use cache mounts during resolver execution.
@TomChv this unfortunately …
> project: update runtimes to use Dagger types.

- sdk/elixir/lib/dagger/query_builder.ex
Make any api that perform graphql request return in pattern of `{:ok, result} | {:error, reason}` pattern. Lets take a look at the example: 
```elixir
Mix.install([
{:dagger, path: "."}
])
client = Dagger.connect!()
client
|> Dagger.Query.container()
|> Dagger.Container.from("nginx")
|> Dagger.Container.env_variables()
|> IO.inspect()
Dagger.close(client)
```
Then run:
```
$ elixir test.exs
Connected to engine f63d9f1488ba
#1 resolve image config for docker.io/library/nginx:latest
{:ok,
[
%{
"name" => "PATH",
"value" => "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
},
%{"name" => "NGINX_VERSION", "value" => "1.25.1"},
%{"name" => "NJS_VERSION", "value" => "0.7.12"},
%{"name" => "PKG_RELEASE", "value" => "1~bookworm"}
]}
```
NOTE: this must be executed under `sdk/elixir` …
> sdk(elixir): returns {:ok, result} instead of just result

- internal/mage/sdk/rust.go
- sdk/rust/Cargo.lock
- sdk/rust/crates/dagger-codegen/src/rust/functions.rs
- sdk/rust/crates/dagger-sdk/Cargo.toml
- sdk/rust/crates/dagger-sdk/src/gen.rs
They started happening right after
https://github.com/dagger/dagger/pull/5372 got merged, even though this commit didn't change anything in the Rust SDK: https://github.com/dagger/dagger/actions/runs/5424732578/jobs/9864713099
The relevant errors:
```rust
error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`
--> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/wrapper.rs:475:33
|
475 |                 let proc_macro::LineColumn { line, column } = s.start();
|                                 ^^^^^^^^^^ not found in `proc_macro`
|
help: consider importing this struct through its public re-export
|
1   + use crate::LineColumn;
|
help: if you import `LineColumn`, refer to it directly
|
475 -                 let …
```
> Fix Rust SDK errors

- cmd/shim/main.go
- core/container.go
- core/directory.go
- core/integration/directory_test.go
We now use MergeOp as much as possible to optimize copying from one LLB state onto another. See the comments in the mergeStates function in core/directory.go for more details.
> core: Optimize *.WithDirectory and *.WithFile via MergeOp.

- docs/current/guides/723462-use-secrets.md
Fix danger tag on https://docs.dagger.io/723462/use-secrets#understand-how-dagger-secures-secrets
> Fix danger tag not rendering in 723462-use-secrets.md

- ci/engine.go
- cmd/dagger/do.go
- cmd/dagger/engine.go
- cmd/dagger/run.go
- core/bk2progrock.go
- core/container.go
- core/schema/container.go
- core/schema/container.graphqls
- engine/engine.go
- go.mod
- go.sum
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
fixes #5156 
```graphql
extend type Container {
"""
Indicate that subsequent commands should be featured more
prominently in the UI.
"""
withFocus: Container!
"""
Indicate that subsequent commands should not be featured
more prominently in the UI.
This is the initial state of all containers.
"""
withoutFocus: Container!
}
```
You would typically use this to mark the command that accomplishes the primary goal of the pipeline, such as the command that runs your tests. You can also just splice it into a call chain for troubleshooting.
```go
func GoGenerate(
ctx dagger.Context,
base *dagger.Container,
src *dagger.Directory,
) *dagger.Directory {
return base.
With(GoCache(ctx)).
With(Cd("/src", src)).
WithFocus().
WithExec([]string{"go", "generate", "./..."}).
Directory("/src")
}
```
Depends …
> Container: add `withFocus`, `withoutFocus`

- core/directory.go
- core/integration/directory_test.go
The previous MergeOp optimization missed a corner case where if the selector of the source dir was the same as the destination path, direct MergeOp could be triggered and reveal anything above the selector of the source during the merge.
This fixes it by only triggering direct merge when both src and dest paths (including any selectors) are "/".
---
Fixes #5437
Noticed this while working on Zenith, just patching quick before I forget.
> Fix corner case where WithDirectory included wrong contents.

- docs/current/partials/_install-cli.md
This changed to `DAGGER_VERSION` ~1 year ago. It was correctly updated in most places, except in this doc.
Also updated the version to LATEST-1.
> Fix VERSION variable for CLI install instructions

- .github/dependabot.yml
Dependabot opened 12 npm dep bumps in sdk/rust in the last 4 days. These are super low value contributions that we want to avoid seeing alongside the other, genuinely valuable PRs (each dep bump gets its own PR, which means a lot of noise & no signal).
> Configure dependabot to ignore npm dep updates in sdk/rust

- core/host.go
- core/integration/host_test.go
Helps make it more obvious why two copy operations that look similar are cached differently and vice versa.
> core: add include/exclude name to host dir copy name

- core/container.go
- core/integration/container_test.go
- core/schema/container.go
- core/schema/container.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
We previously made a change to default to using oci mediatypes, which helped compatibility with certain compression types that are only supported with oci types.
However, older registries ([specifically a user reported Artifactory versions from pre-2020](https://github.com/dagger/dagger/issues/5433)) don't have OCI support.
This change fixes that by leaving OCI as the default but enabling users to specify docker mediatypes to be used instead as a fallback.
---
Fixes #5433
> core: support optionally setting explicit mediatypes

- core/integration/local_test.go
We need to make sure that separate clients/sessions that happen to be loading the same path (whether they are on the same host or not) load independently rather than hitting the same cache just because the paths happen to be the same.
---
This will only pass if we include session IDs in the local LLB, which it turns out is not just needed for projects/Zenith but also in general to prevent two clients incorrectly de-duplicating local dir loads.
It passes as is on main, but only as of v0.6.3 which added session ID to the LLB, need to make sure that stays true going forward.
> core: Add test for local imports across sessions

- core/container.go
- core/digest.go
- core/host.go
- core/integration/cache_test.go
- core/integration/suite_test.go
SessionID is important to keep on host directories, because otherwise the Buildkit solver's vertex is keyed only on a local client's path, whose contents may differ when clients are running in containers with different content mounted to the same path. This primarily affects setups with a long-running external engine.
To prevent the SessionID from busting caches everywhere, hostnames are now calculated by taking a stable hash of the *pb.Definition, which is a pretty invasive process:
First it loops over the inner Ops and removes the relevant ephemeral metadata from SourceOps. This results in a new Op with a different digest, so it keeps track of the old and new digests along the way.
Next it loops over the old => new digest mapping and converts any occurrences of the old digest to the new …
> stabilize container hostnames against SessionID

- core/integration/container_test.go
Saw a single failure in CI after merging:
https://github.com/dagger/dagger/actions/runs/5563667789/jobs/10162760954
Never saw it prior to that and couldn't repro locally, so this is just a best guess. Ran the test in a loop for a while after this change and saw no failures.
> core: attempt to deflake container image load compat test.

- .changes/unreleased/Added-20230717-173825.yaml
- cmd/dagger/engine.go
Just some TUI low-hanging fruit:
via feedback from @cpdeethree :)
> inline tui: show run duration at the end

- sdk/python/pyproject.toml
- sdk/python/src/dagger/api/base.py
Fixes #4856
It makes it clearer from the reference documentation which methods need an `await`.
> Fix coroutines not showing in Python reference docs

- core/pipeline/label.go
While trying to understand who uses Dagger, we realized that some Go SDK users were periodically heavily using us. As we are currently sha256 encoding some Git Labels, we currently have no idea who, and where they are using us.
Relying on base64 instead of sha256 would help us understand better the usage of the Go SDK
cc @gerhard
> PS: this might create some noise with the current hashes
> chore: update `AppendAnonymousGitLabels()`

- core/integration/cache_test.go
Was just discussing a use-case that might potentially call for a cache volume with submounts over it; didn't see that we had tests for that case yet so verified by writing these. Figured we may as well commit them too so we have coverage.
> core: add test for cache volumes w/ submounts.

- CONTRIBUTING.md
- https://github.com/dagger/dagger/pull/5408
WDYT?
---
There is a related discussion in https://github.com/dagger/dagger/issues/5475 that you may be interested in.
> Add release notes fragment instructions

- internal/mage/sdk/python.go
- internal/mage/util/util.go
- sdk/python/pyproject.toml
This fixes an issue with the source distribution that's published in [PyPI](https://pypi.org/project/dagger-io/#files) since the [move to hatch](https://github.com/dagger/dagger/pull/5401) because of the difference in the distribution name (i.e., `dagger-io`) and importable package name (i.e, `dagger`). This was only detected when trying to release in [conda](https://github.com/conda-forge/dagger-io-feedstock/pull/18), so I've added a test in CI.
> Python: Fix sdist build

- .changes/unreleased/Fixed-20230715-131052.yaml
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/engine_test.go
- core/integration/file_test.go
- core/integration/git_test.go
- core/integration/host_test.go
- core/integration/pipeline_test.go
- core/integration/platform_test.go
- core/integration/remotecache_test.go
- core/integration/secret_test.go
- core/integration/services_test.go
- core/integration/suite_test.go
- internal/mage/util/engine.go
in a debugging session with @vito, we found out that alpine 3.16 and
3.17 has a regression where dns queries which have a "search ." in
resolv.conf are not passed to the specified nameserver accordingly.
we came across this while I was trying to run dagger tests in my local
machine which is an ubuntu based system managed by
`systemd-resolved` which by defaults adds a `search .` entry in the
/etc/resolv.conf file
> bump alpine image to fix dns resolution error

- .changes/unreleased/Breaking-20230727-115352.yaml
- core/schema/container.go
- core/schema/container.graphqls
- sdk/go/api.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/api/gen.py
- sdk/python/src/dagger/api/gen_sync.py
- sdk/python/src/dagger/codegen.py
Closes #4192
This has minimal impact since the renamed argument is required/positional in the SDKs. Will only break if someone's using the argument name directly such as in a GraphQL query string.
> Rename `id` argument in `Container.withRootfs`

- docs/current/742989-cookbook.md
- docs/current/cookbook/snippets/mount-directories-as-secrets/index.ts
- docs/current/cookbook/snippets/mount-directories-as-secrets/main.go
- docs/current/cookbook/snippets/mount-directories-as-secrets/main.py
Fixes #4896
⚠️ PUBLISH AFTER v0.8.0 RELEASE, depends on #5500 
Small cookbook example / wrapper with the `.with()` method showing how to mount directories securely
> docs: `mount dir as secret` cookbook

- sdk/go/.changes/unreleased/Fixed-20230720-184344.yaml
- sdk/go/client.go
- sdk/go/client_test.go
- sdk/go/internal/engineconn/cli.go
- sdk/go/internal/engineconn/engineconn.go
- sdk/go/internal/engineconn/session.go
- sdk/nodejs/.changes/unreleased/Fixed-20230720-184357.yaml
- sdk/nodejs/provisioning/bin.ts
Add few lines during engine loading to update user. This PR update Typescript and Go SDK.
Related to: #4820
**Example on Typescript SDK**
```shell
yarn start
yarn run v1.22.19
$ node --loader ts-node/esm ./index.mts
(node:97293) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Starting Dagger session...
Dagger session started! Establishing connection with the SDK...
Connection established with Dagger session version 0.6.3
```
**Example on Go SDK**
```shell
go run ./test.go                                                    
Starting Dagger session...
Dagger session started! Establishing connection with the SDK...
Connection established with Dagger session version 0.6.3! …
```
> feat: improve engine session loading logging

- sdk/python/.changes/unreleased/Added-20230728-182700.yaml
- sdk/python/pyproject.toml
- sdk/python/requirements.txt
- sdk/python/src/dagger/_progress.py
- sdk/python/src/dagger/config.py
- sdk/python/src/dagger/connection.py
- sdk/python/src/dagger/engine/conn.py
- sdk/python/src/dagger/engine/download.py
- sdk/python/tests/engine/test_download.py
This is the Python implementation for:
- https://github.com/dagger/dagger/issues/4456
- https://github.com/dagger/dagger/issues/4820.
It takes a slightly different approach than Go and Node.js in:
- https://github.com/dagger/dagger/pull/5488
Instead of `Message... OK!` lines written only to `log_output`, this change is less obtrusive, more animated and works even without `log_output`[^1]:
- Shows an animation which gives a better experience than a static "…", and replaces status updates in-line.
- In the end this line disappears so there’s no lingering record in the logs. It's ok because the intent is to provide interactive feedback, without polluting logs.
- Writes to `log_output` if it’s **interactive** (e.g., pseudo terminal, not a file).
- Supports an escape hatch if you need to turn …
> Python: add status updates during automatic provisioning

- codegen/generator/nodejs/templates/src/object.ts.gtpl
- sdk/nodejs/.changes/unreleased/Breaking-20230727-235539.yaml
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/connect.ts
- sdk/nodejs/index.ts
- sdk/nodejs/provisioning/bin.ts
- sdk/nodejs/provisioning/engineconn.ts
Closes #5434
Doc updates in https://github.com/dagger/dagger/pull/5518
> Node.js: Export `Client` as a named export, instead of default

- auth/registry.go
Before this, if there was s a matching domain for basic auth creds in the in-memory credential store, then we error out if one of the methods related to bearer auth is called.
Now, we instead just passthrough to the docker auth provider. Our in-mem cred store doesn't support bearer auth tokens, so there's no reason (I'm aware of) to not just forward the request.
> auth: always pass bearer auth related requests to docker auth provider.

- sdk/rust/crates/dagger-sdk/src/core/engine.rs
- sdk/rust/crates/dagger-sdk/src/core/mod.rs
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/rust/crates/dagger-sdk/tests/issues/iss_30.rs
- sdk/rust/crates/dagger-sdk/tests/issues/iss_33.rs
- sdk/rust/crates/dagger-sdk/tests/mod.rs
From the root of the rust sdk, run:
$ env _EXPERIMENTAL_DAGGER_CLI_BIN=../../bin/dagger cargo run --example first-pipeline
The sdk will use dagger binary defined in `_EXPERIMENTAL_DAGGER_CLI_BIN` to run the pipeline. And modify the engine to try running on local cli when session port & token doesn't set, if this configuration is not set, it will fallback to download cli method.
And also fix tests that failure because of using deleted apis. And re-generate code to make lint happy.
> feat: add support _EXPERIMENTAL_DAGGER_CLI_BIN to rust

- docs/current/guides/snippets/aws-codebuild-codepipeline/go.mod
- docs/current/guides/snippets/aws-codebuild-codepipeline/go.sum
- docs/current/guides/snippets/aws-lambda/go.mod
- docs/current/guides/snippets/aws-lambda/go.sum
- docs/current/guides/snippets/build-test-publish-java-spring/go.mod
- docs/current/guides/snippets/build-test-publish-java-spring/go.sum
There are 1 security vulnerabilities found in golang.org/x/sys v0.0.0-20220811171246-fbc7d0a398ab
- [CVE-2022-29526](https://www.oscs1024.com/hd/CVE-2022-29526)
Upgrade golang.org/x/sys from v0.0.0-20220811171246-fbc7d0a398ab to 0.1.0 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade golang.org/x/sys to 0.1.0

- docs/current/cli/snippets/get-started/step3/build.sh
Fix: #5423
This commit updates the documentation with the latest API reference of [Container-withDirectory](https://docs.dagger.io/api/reference/#Container-withDirectory).
> docs: updated CLI code snippet with latest API reference

- docs/current/742989-cookbook.md
- docs/current/cookbook/snippets/mount-directories-as-secrets/index.ts
- docs/current/cookbook/snippets/mount-directories-as-secrets/main.go
- docs/current/cookbook/snippets/mount-directories-as-secrets/main.py
Closes https://github.com/dagger/dagger/issues/4896
Re-opening following the [revert](https://github.com/dagger/dagger/pull/5519). Most of the context is on the [initial PR](https://github.com/dagger/dagger/pull/5502)
Small cookbook example / wrapper with the `.with()` method showing how to mount directories securely.
cc @helderco
> docs: cookbook: mount directories as secrets after v.0.8.0

- core/integration/file_test.go
- engine/buildkit/ref.go
Previously, we were using a max chunk size based on a non-grpc-default set inside the buildkit client implementation, but the actual grpc default is much smaller than that.
This didn't impact us previously because we only ever ended up hitting the codepaths where the larger max message size was used, but after the recent re-architecture we ended up sometimes using streams where the smaller grpc default was set.
This updates us to just always assume the 4MB grpc default chunk size is being enforced, which is safer at the moment than trying to play whack-a-mole to update the max size on every grpc stream we open. We can play that game in the future if there's ever a need to tune this for performance reasons.
Also added integ test coverage for this now.
---
Fixes the problem uncovered here: …
> core: fix max file chunk size

- docs/current/guides/421437-work-with-host-filesystem.md
If applied, this commit adds warnings and additional considerations when using host directories in Dagger to the "work with host filesystem" guide.
Closes DOCS-22
> docs: Added pitfalls of host directories

- .changes/unreleased/Fixed-20230803-142805.yaml
- .changes/unreleased/Fixed-20230803-142956.yaml
- core/container.go
- core/integration/container_test.go
- engine/buildkit/containerimage.go
We accidentally were exporting the config of the container that export was being called on, but meant to use the config of the platform variant in that part of the loop.
Wasn't caught because we didn't have test coverage for image config being retained for either export or publish. Added that now.
> core: fix setting image config during multiplatform export+publish

- sdk/python/docs/index.rst
Forgot this in #5558 for #4704
> Add link to Conda repository in reference docs

- sdk/elixir/lib/dagger/engine_conn.ex
If user run with local cli mode and use home directory with tilde (`~`), the SDK will always fallback to download engine method. This happens because of `System.find_executable` returns `nil` when home directory is `~`. Fixes by expand bin path before sending it to `System.find_executable`.
> fix: Elixir SDK doesn't expand tilde

- .changes/unreleased/Fixed-20230804-083720.yaml
- .changes/unreleased/Fixed-20230804-085622.yaml
- core/schema/query.go
- engine/client/client.go
- internal/mage/engine.go
- internal/mage/util/engine.go
The version is now reported from the graphql server to the client, which means we need to set the version string in the engine image too.
---
Tested manually so far by publishing to my dockerhub repo and setting `_EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-image://eriksipsma/testdagger:v0.0.999`:
I'm also going to give a quick shot at adding an automated test, but will either include here or a follow up depending on timing.
@marcosnils also put the cloud url callback after we've connected to the engine successfully 
Fixes #5572
> engine: set version stamp on engine image builds

- engine/cache/manager.go
Before this, we were providing just our remote cache import to the list of "cms" given to the combined cache manager and setting the "main" cache to the local cache.
However, it turns out that the combined cache will only query the list of cache managers provided in "cms"; it will never query the "main" cache.
Now we provide the local cache both in the list of cms and as the main cache manager so that it's queried too.
> engine: fix combined cache manager to query local cache too.

- docs/current/guides/snippets/multiplatform-support/build-images-cross-compilation/main.go
- docs/current/guides/snippets/multiplatform-support/build-images-emulation/main.go
This commit updates the multi-architecture code examples / guide to include the additional `mediatypes` parameter.
> docs: Updated multiarch examples with `mediatypes`

- .github/workflows/publish-sdk-elixir.yaml
We do not want to publish when there is a push to `main`.
This will fix the check which is currently failing on `main`.
FWIW, only the Go SDK does this since it needs to sync to the repository where users `go get` from, https://github.com/dagger/dagger-go-sdk - this is when users want to run the latest dev version of Go SDK.
> We only want to publish the Elixir SDK when there is a tag

- docs/current/cli/389936-run-pipelines-cli.md
- docs/current/sdk/go/959738-get-started.md
- docs/current/sdk/nodejs/783645-get-started.md
- docs/current/sdk/python/628797-get-started.md
- docs/current/sdk/python/snippets/get-started/step3/test.py
- docs/current/sdk/python/snippets/get-started/step4a/test.py
- docs/current/sdk/python/snippets/get-started/step4b/test.py
This commit updates the Go, Node.js, Python and CLI get started guides to use "dagger run".
> docs: Added "dagger run" to get started guides

- website/sidebars.js
This commit modifies the "Releases" link in the docs navbar to "Changelog" and modifies it to point to https://github.com/dagger/dagger/blob/main/CHANGELOG.md
> docs: Modified releases link to point to changelog

- .github/workflows/publish-sdk-elixir.yaml
To publish Elixir SDK to https://hex.pm, it require to set `HEX_API_KEY` to use for authenticate with it.
> ci: add HEX_API_KEY to publish-sdk-elixir workflow

- codegen/generator/nodejs/templates/functions.go
- codegen/generator/nodejs/templates/src/header.ts.gtpl
- codegen/generator/nodejs/templates/src/types.ts.gtpl
- sdk/nodejs/.changes/unreleased/Fixed-20230809-184725.yaml
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/api/utils.ts
GQL enumeration are sent as string without quotes, they need a special format to be sent that way by the client.
Update Node client with a custom function to check for Dagger enumeration.
Update Node query format to reformat enumeration.
Resolves: #5575
> feat: correctly handle enumeration on Node SDK

- sdk/go/go.mod
- sdk/go/go.sum
- sdk/go/internal/engineconn/cli.go
I accidentally found when using local cli mode like this:
```
$ env _EXPERIMENTAL_DAGGER_CLI_BIN=~/src/github.com/dagger/dagger/bin/dagger go run ./ci build local-version
```
And it returns:
```
Error: exec: "~/src/github.com/dagger/dagger/bin/dagger": stat ~/src/github.com/dagger/dagger/bin/dagger: no such file or directory
Please visit https://dagger.io/help#go for troubleshooting guidance.
Usage:
ci build [flags]
Flags:
--dry-run        Build an image but do not publish image to the registry
-x, --export-local   Export image into local docker engine
-h, --help           help for build
exit status 1
```
I just recognize that `exec.LookupPath` would not resolve tilde (~) into `$HOME` directory. ><) This PR fix this issue.
> fix: local cli doesn't expand tilde to home path in Go SDK

- internal/mage/sdk/all.go
Make `sdk:all` to run `sdk:elixir` tasks.
> feat: add Elixir to sdk:all task

- docs/current/cli/979595-reference.md
This commit adds examples of using `dagger run` to the CLI reference page.
Closes DOCS-48
> docs: Added dagger run examples

- core/integration/engine_test.go
- core/integration/services_test.go
- core/integration/suite_test.go
- core/integration/testdata/basic-container/main.go
- core/integration/testdata/telemetry/main.go
- core/pipeline/label.go
- engine/client/client.go
1. Backfill integration test for labels being sent to Cloud
2. Store collected labels on `Client` and include them in every `ClientMetadata`
> telemetry: fix labels not being included

- core/pipeline/label.go
Plain base64 encode repository name, no base16.
As discussed with @aluzzardi.
Follow-up to:
- https://github.com/dagger/dagger/pull/5487
> Preserve git email anonymity (one-way hash)

- engine/cache/manager.go
- engine/cache/provider.go
- engine/cache/service.go
- engine/cache/util.go
- engine/cache/util_test.go
- Assume success on HTTP 2xx (some blob providers will return 201 rather than 200)
- Dump HTTP error body on failure, stripping away any URL path to avoid leaking pre-signed URLs
> remote cache: improve http error checking

- cmd/dagger/query.go
Found from https://discord.com/channels/707636530424053791/1139744521886908416/1139744521886908416. The `exec` query already gone since 0.8 in favor of `withExec`.
> fix: fix example query in dagger query

- website/src/css/custom.scss
This fix reverts the margins on Desktop when there's an instance of the Playground within the document:
> hotfix(docs): quickstart layout width auto-expands so that playground fits better

- core/directory.go
- core/integration/pipeline_test.go
The update to use merge-op to optimize copies also resulted in us receiving tons of progress vertexes about merges. These are kind of confusing to users since merge is entirely an internal optimization and the format we receive them in can be extremely ugly due to the fact that they don't show the flattened merge that actually takes place.
Now that vertex is marked as internal and thus shouldn't show up in output by default.
cc @jpadams I believe this will stop these from polluting progress output, which I know was causing confusion recently.
> core: hide merge vertexes from output

- .changes/unreleased/Added-20230815-154334.yaml
- core/directory.go
- core/file.go
Update directory export resolver to log additional context about the export. It logs a simple message: `export directory <name of the dir> to host <path>`.
EDIT: also include this change for file export
Resolves: #5084
> feat: show export host target

- .changes/unreleased/Fixed-20230815-142820.yaml
- cmd/dagger/engine.go
- core/context.go
- core/integration/engine_test.go
- core/pipeline/label.go
- core/pipeline/pipeline.go
- core/query.go
- core/schema/http.go
- core/schema/query.go
- engine/client/client.go
- engine/opts.go
- engine/server/server.go
- go.mod
- go.sum
- sdk/elixir/lib/dagger/internal/client.ex
3 changes:
* Log a `--debug` message in the connection retry loop to make it easier to troubleshoot hangs.
* Base64-encode client metadata so fancy UTF8 letters don't cause errors
* Fix/clean up label collection flow to make more sense with the new architecture
* Fix weird server-global label cache, which really shouldn't have been there anymore, and was probably causing the first connection's labels to be used for all subsequent connections.
* Rather than putting the root labels into every single object, just let it stay on the root Group. the telemetry progrock.Writer also turns these into labels sent to Cloud, so we don't need to duplicate them anymore.
As a result of that last change, all IDs should now be much smaller, since they don't have to contain the root pipeline + labels. …
> Fix utf8 labels causing hang, clean up + fix label collection in general

- .github/workflows/_hack_make.yml
- .github/workflows/lint.yml
- .github/workflows/sdk-elixir.yml
- .github/workflows/test.yml
- sdk/elixir/lib/dagger/internal/client.ex
Tests started failing intermittently since the fix in https://github.com/dagger/dagger/pull/5628 and it's not clear why. FTR:
```diff
diff --git a/sdk/elixir/lib/dagger/engine_conn.ex b/sdk/elixir/lib/dagger/engine_conn.ex
index 9b4ed912..acd97199 100644
--- a/sdk/elixir/lib/dagger/engine_conn.ex
+++ b/sdk/elixir/lib/dagger/engine_conn.ex
@@ -16,7 +16,8 @@ defmodule Dagger.EngineConn do
_otherwise ->
case from_local_cli(opts) do
{:ok, conn} -> {:ok, conn}
-          _otherwise -> from_remote_cli(opts)
+          {:error, :no_executable} -> from_remote_cli(opts)
+          {:error, :session_timeout} -> {:error, :session_timeout}
end
end
end
@@ -41,7 +42,6 @@ defmodule Dagger.EngineConn do
start_cli_session(bin_path, opts)
else
nil -> {:error, :no_executable}
-      otherwise -> otherwise …
```
> Temporarily suspend auto-triggering the Elixir SDK workflow

- .github/workflows/sdk-elixir.yml
- sdk/elixir/.changes/unreleased/Fixed-20230816-235838.yaml
- sdk/elixir/lib/dagger/session.ex
Somehow, when running inside dagger (`internal/mage` for example), the Elixir Port didn't separate line with `\n`. This cause `Dagger.Session` cannot retrieve the session port and token, causing session timeout.
To fix that, split data that come from port with `\n` and try parsing a JSON line by line to find the session.
Fixes #5642
> fix: fix connect always timeout

- codegen/generator/nodejs/templates/functions.go
- codegen/generator/nodejs/templates/src/header.ts.gtpl
- codegen/generator/nodejs/templates/src/method.ts.gtpl
- codegen/generator/nodejs/templates/src/method_solve.ts.gtpl
- sdk/nodejs/.changes/unreleased/Fixed-20230816-184800.yaml
- sdk/nodejs/api/client.gen.ts
- sdk/nodejs/api/test/api.spec.ts
- sdk/nodejs/api/utils.ts
Include a new internal logic to get more information about type during query building.
This is a first step before moving to an actual query builder.
This internal data structure called `metadata` let the query builder knows if the value is an enum or not.
This avoids any possible type conflict.
This replaces the old enumeration handling implementation so old code has been deleted.
Include new tests to ensure no conflict is possible anymore.
Resolves: #5638
> fix: NodeJS conflict between enumeration and string

- sdk/elixir/.changes/unreleased/Added-20230816-122257.yaml
- sdk/elixir/lib/dagger.ex
- sdk/elixir/lib/dagger/engine_conn.ex
Calls `Dagger.Client.check_version_compatibility/2` against the engine
version and warning it if the result is failure. This requires
`Dagger.EngineConn` to expose engine version to make usable in
`Dagger.connect/1`.
> feat: support version compatibility check

- sdk/rust/Cargo.toml
This is how cargo workspaces resolves crates, and it v1 (default) produces a
warning on build
> feat(rust-sdk): set resolver v2

- sdk/elixir/.changes/unreleased/Fixed-20230817-221054.yaml
- sdk/elixir/lib/dagger/engine_conn.ex
When no local cli found, the engine will download stable engine and start it.
Fixes #5651
> fix: switch to stable engine only case no local cli

- .github/workflows/_hack_make.yml
- .github/workflows/sdk-elixir.yml
- .github/workflows/test.yml
So that we can find potential failures earlier, as we've learned from v0.8.0 & v0.8.3 releases. cc @sipsma @vito
Allow PRs to use both Dagger runners & paid GitHub runners (same size). It's OK if these fail for now - `continue-on-error` - since we seem to have a configuration issue on the self-hosted runners themselves (they are attempting to use the same Engine). We can follow-up with a fix. cc @jlongtine
By the way, if we like this change, we can roll it out to other jobs - supersedes https://github.com/dagger/dagger/pull/5359
---
Stop uploading journal.log. Since we are reusing workflows, we cannot easily determine the journal log file name (the same one gets overwritten by different workflows). If we use inputs.mage-targets to distinguish, this fails since it contains ':', an …
> Run Engine tests in dev Engine (on top of stable Engine)

- docs/current/cookbook.md
- docs/current/cookbook/snippets/tailscale-networking/go.mod
- docs/current/cookbook/snippets/tailscale-networking/index.mjs
- docs/current/cookbook/snippets/tailscale-networking/main.go
- docs/current/cookbook/snippets/tailscale-networking/main.py
This commit adds a cookbook recipe explaining how to use a container in a Dagger pipeline to access a Tailscale network.
> docs: Added Tailscale access recipe to cookbook

- docs/current/guides/541047-alternative-runtimes.md
This commit updates the OCI runtimes guide with information on two possible approaches to customizing Dagger Engine installation.
> docs: Updated OCI runtime guide

- sdk/nodejs/connect.ts
Same as `Go` SDK, throw an error if workdir is set while an existing session is already running
> feat: throw error on workdir config on session

- sdk/elixir/.changes/unreleased/Fixed-20230821-223927.yaml
- sdk/elixir/lib/dagger/codegen/elixir/templates/object_tmpl.ex
- sdk/elixir/lib/dagger/gen/client.ex
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/elixir/lib/dagger/gen/directory.ex
- sdk/elixir/lib/dagger/gen/git_ref.ex
- sdk/elixir/test/dagger/client_test.exs
Some functions, it has optional argument that is ID type. Before this change, if we calling that function, it will crash because that function didn't calling `id/1` to convert into ID string. This change fix that issue by calling `id/1` or iterate calling `id/1` for any function that accept list of ID type, such as, `Dagger.Directory.docker_build/2`.
> fix: calling id for any optional arguments that is ID type

- sdk/elixir/.changes/unreleased/Added-20230824-164137.yaml
- sdk/elixir/lib/dagger/engine_conn.ex
Throw `{:error, :work_configure_on_session}` when run on session mode (`dagger run`).
> feat: throw error when workdir config on session

- sdk/elixir/.changes/unreleased/Fixed-20230818-231100.yaml
- sdk/elixir/lib/dagger/engine_conn.ex
`System.fetch_env` returns `:error`. The `Dagger.EngineConn.get/0` didn't handle it causing always returns `:error` instead of connect to stable engine.
Fixes #5664
> fix: cannot connect to Dagger Engine and always raise error

- docs/current/guides/620941-github-google-cloud.md
- docs/current/guides/759201-gitlab-google-cloud.md
- docs/current/guides/snippets/ci/go/actions.yml
- docs/current/guides/snippets/ci/go/gitlab.yml
- docs/current/guides/snippets/ci/nodejs/actions.yml
- docs/current/guides/snippets/ci/nodejs/gitlab.yml
- docs/current/guides/snippets/ci/python/actions.yml
- docs/current/guides/snippets/ci/python/gitlab.yml
- docs/current/guides/snippets/github-google-cloud/github-go.yml
- docs/current/guides/snippets/github-google-cloud/github-nodejs.yml
- docs/current/guides/snippets/github-google-cloud/github-python.yml
- docs/current/guides/snippets/gitlab-google-cloud/gitlab-ci-go.yml
- docs/current/guides/snippets/gitlab-google-cloud/gitlab-ci-nodejs.yml
- docs/current/guides/snippets/gitlab-google-cloud/gitlab-ci-python.yml
This commit updates the Dagger + Google Cloud + GitHub/GitLab long-form guides to use "dagger run".
Follow-up to:
https://github.com/dagger/dagger/pull/5591
https://github.com/dagger/dagger/pull/5604
> docs: Updated some guides to use "dagger run"

- docs/current/cookbook.md
- docs/current/guides/421437-work-with-host-filesystem.md
- docs/current/guides/snippets/work-with-host-filesystem/mount-dir-export/index.mts
- docs/current/guides/snippets/work-with-host-filesystem/mount-dir-export/main.go
- docs/current/guides/snippets/work-with-host-filesystem/mount-dir-export/main.py
This commit adds an example of reading and writing a host directory from a container to the host filesystems guide and to the cookbook.
> docs: Adds host directory r/w example to guide and cookbook

- sdk/python/src/dagger/_engine/conn.py
this is a follow up of the Go SDK check made by @vito here: https://github.com/dagger/dagger/pull/5126
> sdk: python: add workdir check when session already exists
