.github/workflows/publish.yml

Fix provision tests after https://github.com/dagger/dagger/pull/5401

Fix Python provision tests

---

core/integration/container_test.go
core/integration/secret_test.go
sdk/go/client_test.go
sdk/go/examples_test.go
sdk/nodejs/api/test/api.spec.ts

We want to remove these old deprecations soon, so this is a first step to make that easier:
- https://github.com/dagger/dagger/discussions/5374#discussioncomment-6327323

Replace deprecations

---

core/integration/container_test.go
core/integration/engine_test.go
core/integration/pipeline_test.go
core/integration/platform_test.go
core/integration/secret_test.go
core/integration/services_test.go
internal/mage/cli.go
internal/mage/docs.go
internal/mage/engine.go
internal/mage/sdk/elixir.go
internal/mage/sdk/go.go
internal/mage/sdk/rust.go
sdk/nodejs/api/test/api.spec.ts
sdk/nodejs/test/connect.spec.ts

Rationale in https://github.com/dagger/dagger/issues/5124

Replace `ExitCode` usage with `Sync`

---

core/directory.go
core/integration/directory_test.go
core/integration/services_test.go
core/schema/directory.go
core/schema/directory.graphqls
sdk/go/api.gen.go
sdk/nodejs/api/client.gen.ts
sdk/python/src/dagger/api/gen.py
sdk/python/src/dagger/api/gen_sync.py
sdk/python/tests/api/test_integration.py

Part of https://github.com/dagger/dagger/issues/5065

Add `Directory.sync`

---

core/directory.go
core/file.go
core/host.go
core/integration/file_test.go
core/integration/services_test.go
core/project.go
core/schema/directory.go
core/schema/file.go
core/schema/file.graphqls
sdk/go/api.gen.go
sdk/nodejs/api/client.gen.ts
sdk/python/src/dagger/api/gen.py
sdk/python/src/dagger/api/gen_sync.py

Part of https://github.com/dagger/dagger/issues/5065

Add `File.sync`

---

docs/current/cookbook/snippets/cache-invalidation/index.mjs
docs/current/cookbook/snippets/multiple-tags/index.mjs
docs/current/cookbook/snippets/oci-annotations/index.mjs
docs/current/cookbook/snippets/secrets-vault/index.mjs
docs/current/guides/snippets/aws-codebuild-codepipeline/index.mjs
docs/current/guides/snippets/aws-lambda/index.mjs
docs/current/guides/snippets/azure-pipelines-container-instances/index.mjs
docs/current/guides/snippets/build-test-publish-java-spring/index.mjs
docs/current/guides/snippets/github-google-cloud/index.mjs
docs/current/guides/snippets/gitlab-google-cloud/index.mjs
docs/current/guides/snippets/load-images-local-docker-engine/export/index.mjs
docs/current/guides/snippets/load-images-local-docker-engine/push/index.mjs
docs/current/guides/snippets/multi-builds/index.mjs
docs/current/guides/snippets/replace-dockerfile/index.mjs
docs/current/guides/snippets/use-secrets/external/index.mjs
docs/current/guides/snippets/use-secrets/host-env/index.mjs
docs/current/guides/snippets/use-secrets/host-fs/index.mjs
docs/current/guides/snippets/use-secrets/raw/index.mjs
docs/current/guides/snippets/use-secrets/sdk/index.mjs
docs/current/guides/snippets/use-secrets/security/index.mjs
docs/current/quickstart/snippets/build-dockerfile/index.mjs
docs/current/quickstart/snippets/build-multi/index.mjs
docs/current/quickstart/snippets/build/index.mjs
docs/current/quickstart/snippets/caching/index.mjs
docs/current/quickstart/snippets/hello/index.mjs
docs/current/quickstart/snippets/publish/index.mjs
docs/current/quickstart/snippets/test/index.mjs
docs/current/sdk/nodejs/snippets/get-started/step4/build.mjs
sdk/nodejs/package.json

Follow up to https://github.com/dagger/dagger/pull/5381 as I noticed in https://github.com/dagger/dagger/pull/5421 that `.mjs` files weren't being formatted.

Fix .mjs docs lint and format

---

sdk/rust/Cargo.lock
sdk/rust/Cargo.toml
sdk/rust/crates/dagger-sdk/Cargo.toml
sdk/rust/crates/dagger-sdk/src/core/mod.rs
sdk/rust/crates/dagger-sdk/src/gen.rs

Long time coming, bumping the rust sdk to newest v0.6.2
Ran `cargo update` as well

chore(rust-sdk): bump v0.6.2

---

.changes/unreleased/Deprecated-20230718-173905.yaml
core/schema/container.graphqls
sdk/go/api.gen.go
sdk/nodejs/api/client.gen.ts
sdk/python/src/dagger/api/gen.py
sdk/python/src/dagger/api/gen_sync.py

Deprecate exitCode

---

docs/current/guides/snippets/load-images-local-docker-engine/export/main.py
docs/current/guides/snippets/load-images-local-docker-engine/push/main.py
docs/current/guides/snippets/use-secrets/sdk/main.py
docs/current/quickstart/snippets/caching/main.py
sdk/python/.changes/unreleased/Changed-20230726-105626.yaml
sdk/python/src/dagger/api/gen.py
sdk/python/src/dagger/api/gen_sync.py
sdk/python/src/dagger/codegen.py
sdk/python/tests/api/test_integration.py

Closes https://github.com/dagger/dagger/issues/4182

Python: Enforce keyword usage for optional arguments

---

.changie.yaml
sdk/go/.changie.yaml
sdk/nodejs/.changie.yaml
sdk/python/.changes/unreleased/Changed-20230726-105626.yaml
sdk/python/.changie.yaml

FWIW: https://keepachangelog.com/en/1.0.0/
- `Added` for new features
- `Changed` for changes in existing functionality
- `Deprecated` for soon-to-be removed features
- `Removed` for now removed features
- `Fixed` for any bug fixes
- `Security` in case of vulnerabilities

Add missing types of changes: Breaking, Removed & Security

---

internal/mage/engine.go

engine: fix publish

---

codegen/generator/functions.go
codegen/generator/go/templates/functions.go
codegen/generator/nodejs/generator.go
codegen/generator/nodejs/templates/functions.go
codegen/generator/nodejs/templates/src/method_solve.ts.gtpl
codegen/generator/nodejs/templates/src/object.ts.gtpl
codegen/generator/nodejs/templates/src/testdata/object_test_want.ts
codegen/generator/nodejs/templates/src/testdata/objects_test_want.ts
sdk/nodejs/.changes/unreleased/Fixed-20230801-014423.yaml
sdk/nodejs/api/client.gen.ts
sdk/nodejs/api/test/api.spec.ts

Add more common functions in Go and Node generator
Generate list of object in Node template
Update test with new generation
Regenerate Node client
Resolves: https://github.com/dagger/dagger/issues/3457

Node.js: Fix returning lists of objects

---

core/schema/query.go
core/schema/query.graphqls
go.mod
go.sum
sdk/go/.changes/unreleased/Added-20230721-172809.yaml
sdk/go/api.gen.go
sdk/go/client.go
sdk/nodejs/.changes/unreleased/Added-20230721-172820.yaml
sdk/nodejs/api/client.gen.ts
sdk/nodejs/connect.ts
sdk/python/.changes/unreleased/Added-20230731-195002.yaml
sdk/python/src/dagger/api/gen.py
sdk/python/src/dagger/connection.py
sdk/python/src/dagger/engine/conn.py
sdk/python/src/dagger/exceptions.py

Add checkVersionCompatibility endpoint.
Generate new clients.
Fixes DAG-1801

feat: check version compatibility

---

docs/current/cookbook/snippets/environment-variables/index.ts
docs/current/guides/snippets/multistage-build/index.mts
docs/current/guides/snippets/private-repositories/clone.ts
docs/current/guides/snippets/use-services/bind-services-1/index.ts
docs/current/guides/snippets/use-services/bind-services-2/index.ts
docs/current/guides/snippets/use-services/expose-ports/index.ts
docs/current/guides/snippets/use-services/persist-service-state/index.ts
docs/current/guides/snippets/use-services/test-service-lifecycle-1/index.ts
docs/current/guides/snippets/use-services/test-service-lifecycle-2/index.ts
docs/current/guides/snippets/use-services/test-service-lifecycle-3/index.ts
docs/current/guides/snippets/use-services/use-db-service/index.ts
docs/current/guides/snippets/use-services/use-hostnames-1/index.ts
docs/current/guides/snippets/use-services/use-hostnames-2/index.ts
docs/current/guides/snippets/use-services/use-hostnames-3/index.ts
docs/current/guides/snippets/work-with-host-filesystem/export-dir/index.mts
docs/current/guides/snippets/work-with-host-filesystem/list-dir-exclude-include/index.mts
docs/current/guides/snippets/work-with-host-filesystem/list-dir-exclude/index.mts
docs/current/guides/snippets/work-with-host-filesystem/list-dir-include/index.mts
docs/current/guides/snippets/work-with-host-filesystem/list-dir-parent/index.mts
docs/current/guides/snippets/work-with-host-filesystem/list-dir/index.mts
docs/current/guides/snippets/work-with-host-filesystem/mount-dir/index.mts
docs/current/sdk/nodejs/snippets/get-started/step2/build.mts
docs/current/sdk/nodejs/snippets/get-started/step3/build.mts
docs/current/sdk/nodejs/snippets/get-started/step4/build.mts

docs: Update Node.js doc imports after v0.8.0

---

.changes/unreleased/Fixed-20230803-194053.yaml
engine/client/client.go
go.mod
go.sum

This probably warrants an integration test of some kind, but I gotta head out soon, so just pushing this as a quick fix + showing the issue for now. :pray:

fix dagger run not showing command progress

---

sdk/elixir/README.md
sdk/elixir/getting_started.livemd

Update livebook file to make it compatible with current SDK.

fix: update livebook and README.md under sdk/elixir

---

sdk/go/.changes/unreleased/Fixed-20230809-200354.yaml

```console
changie new --kind "Fixed" --body "Expand tilde to home when using custom CLI path" --custom "Author=wingyplus" --custom "PR=5555"
```
Follow-up to:
- https://github.com/dagger/dagger/pull/5555

Add release note missed from previous PR

---

.changes/unreleased/Added-20230811-203749.yaml
core/container.go
core/schema/container.go
engine/client/client.go

Signed-off-by: Vasek - Tom C <tom@epitech.eu>
#Related to: #4820

feat: add more logs on dagger loading

---

internal/mage/sdk/rust.go

This was failing on Rust nightly due to internal compiler errors: https://github.com/dagger/dagger/actions/runs/5855269792/job/15872938164#step:4:1708
While this is worth knowing about & maybe even looking into, it should not result in `main` commits failing checks. Perhaps we can have a nightly test that runs periodically (every night?) so that we are not prompted to investigate investigate failing checks after a merge.
I have also taken then liberty to bump the stable Rust version to 1.71, currently latest stable. Everything passes locally & should do the same in CI since it runs the same pipeline. Let's check this assumption.

Fix sdk:rust:test running against nightly Rust

---

docs/current/guides/128409-build-test-publish-php.md
docs/current/guides/205271-replace-dockerfile.md
docs/current/guides/252029-load-images-local-docker-engine.md
docs/current/guides/710884-private-repositories.md
docs/current/guides/882813-build-test-publish-java-spring.md

This commit updates some long-form guides to use "dagger run".
Follow-up to:
- https://github.com/dagger/dagger/pull/5591

docs: Updated some guides to use "dagger run"

---

docs/current/cookbook.md
docs/current/cookbook/snippets/build-dockerfile/index.mjs
docs/current/cookbook/snippets/build-dockerfile/main.go
docs/current/cookbook/snippets/build-dockerfile/main.py

This commit adds a recipe for building using a Dockerfile and build context directory in different locations on the host.

docs: Added recipe to build Dockerfile with different build context directory

---

.github/workflows/publish.yml

Didn't catch this in the PR because this step can only run when you push to main....

gha: fix yaml error in main push scan-engine

---

.github/workflows/_hack_make.yml

Disabling this, so we don't continue to train people to ignore these errors. Let's fix the issue and re-enable after that.

Disable dagger-runner

---

zenith/README.md

Add a basic README for Project Zenith, to give the community a simple entrypoint to learn about the project and get started.

Basic Project Zenith README

---

cmd/dagger/listen.go

cli: allow to set secret session token in listen command

---

docs/current/guides/235290-troubleshooting.md

This commit updates the troubleshooting guide with the problem and solution discussed at https://discord.com/channels/707636530424053791/1138365590290038794/1138365590290038794

docs: Updates troubleshooting guide with networking problem and solution

---

sdk/rust/Cargo.lock
sdk/rust/Cargo.toml
sdk/rust/crates/dagger-sdk/Cargo.toml
sdk/rust/crates/dagger-sdk/src/core/downloader.rs

Quite simply update dependencies, and handle a single breaking change along the way

chore: update rust dependencies

---

docs/current/faq.md

This commit classifies the FAQs into sub-sections for greater readability.

docs: Adds subsections to FAQ

---

sdk/rust/crates/dagger-sdk/src/core/downloader.rs
sdk/rust/crates/dagger-sdk/src/core/engine.rs
sdk/rust/crates/dagger-sdk/src/errors.rs

Slowly chip away at removing eyre

refactor: chip away at removing eyre

---

core/pipeline/label.go
core/pipeline/label_test.go

- Unify all VCS labels
- Add Gitlab label collection + corresponding test
- Add CircleCI label collection + corresponding test
```graphQL
{
"id": "cd027b0b-4942-4db9-8286-3733c237f9bb",
"startedAt": "2023-08-31T09:48:47.082692631Z",
"labels": [
{
"dagger.io/engine": "966f5729555a",
"dagger.io/git.author.email": "xx@xxx",
"dagger.io/git.author.name": "grouville",
"dagger.io/git.committer.email": "xx@xxx",
"dagger.io/git.committer.name": "grouville",
"dagger.io/git.ref": "d5fa63f5989bb401bfc7579df1047ea177cc497c",
"dagger.io/git.remote": "gitlab.com/xx/xxx",
"dagger.io/git.title": "test",
"dagger.io/vcs.change.branch": "ok",
"dagger.io/vcs.change.head_sha": "d5fa63f5989bb401bfc7579df1047ea177cc497c",
"dagger.io/vcs.change.label": "",
"dagger.io/vcs.change.number": "1", …
```

feat: Unify VCS labels + add Gitlab and CircleCI labels

---

RELEASING.md
internal/mage/go.mod
internal/mage/go.sum

Improve releasing during v0.8.7

---

.github/workflows/publish-helm-chart.yml
.github/workflows/test.yml
helm/dagger/Chart.yaml
helm/dagger/templates/_helpers.tpl
helm/dagger/templates/engine-config.yaml
helm/dagger/templates/engine-daemonset.yaml
helm/dagger/templates/magicache-secret.yaml
helm/dagger/values.yaml
internal/mage/helm.go

Dagger Engine Helm chart

---

sdk/python/src/dagger/_codegen/cli.py
sdk/python/src/dagger/_config.py
sdk/python/src/dagger/_connection.py
sdk/python/src/dagger/_engine/conn.py

Recovered refactor from 027fd3e in #5764.

Python: Recover connection refactor 

---

docs/current/cloud/572923-get-started.md
docs/current/faq.md
docs/current/quickstart/635927-caching.mdx

This commit adds more information about caching to the Dagger Cloud and Dagger quickstarts and the FAQ

docs: Improves explanation of caching and cache volumes

---

docs/current/labs/project-zenith.md

The Zenith is now merged, it can now fetch from main branch.

docs: update zenith build from source instructions

---

core/schema/schema.go

Previously, any errors would be displayed as thousands of lines of graphql vomit.
Now, we have a nicely formatted output to indicate exactly what went wrong:
Error: failed to get loaded module ID: input:1: host.directory.asModule.serve failed to install module schema: schema validation failed: input:1813: Undefined type X.
| ...
1810 | }
1811 |
1812 | type Foo {
1813 | 	myFunction(stringArg: String!): X!
1814 | }
1815 | extend type Query {
1816 | 	foo: Foo!
| ...

feat: show graphql schema errors in context

---

docs/current/guides/421437-work-with-host-filesystem.md
docs/current/guides/snippets/work-with-host-filesystem/glob-pattern/index.mts
docs/current/guides/snippets/work-with-host-filesystem/glob-pattern/main.go
docs/current/guides/snippets/work-with-host-filesystem/glob-pattern/main.py

Solves: #5070
This PR updates the existing documentaion to show support for support of glob patterns in dagger SDKs.

docs(guides): updates examples of glob patterns supported in dagger

---

docs/current/cli/389936-run-pipelines-cli.md
docs/current/faq.md
docs/current/partials/_install-cli.md

This commit adds a note about `sudo` to the CLI download instructions.

docs: Update curl commands

---

core/docs/d7yxc-operator_manual.md

Fix for https://github.com/dagger/dagger/issues/5775#issuecomment-1760447333
cc @levlaz

core: document docker-image:// in operator manual

---

cmd/codegen/generator/go/templates/modules.go
core/integration/module_test.go

This fixes #5871.
For example, previously this would have failed, since the `Void` method was required.
```go
// foo is the module
type Foo struct{}
type X struct {
Message string `json:"message"`
}
// This function definition is required, or we don't detect and
// incorporate this into schema generation.
// func (x *X) Void() {}
func (m *Foo) MyFunction(ctx context.Context, stringArg string) X {
return X{Message: stringArg}
}
```
similarly with this example:
```go
// foo is the module
type Foo struct {
Example X
}
type X struct {
Message string `json:"message"`
}
```
With this patch, we attempt to recursively investigate function signatures, structs, etc, to try and find additional types we need to incorporate into the graphql structure defintion.

fix: add recursive type detection for the go sdk

---

docs/current/guides/snippets/use-services/expose-host-services-to-container/main.py
docs/current/guides/snippets/use-services/expose-service-containers-to-host/main.py

Tested:
docs/current/guides/snippets/use-services/expose-host-services-to-container/index.ts
docs/current/guides/snippets/use-services/expose-host-services-to-container/main.py
docs/current/guides/snippets/use-services/expose-service-containers-to-host/index.ts
docs/current/guides/snippets/use-services/expose-service-containers-to-host/main.py
docs/current/guides/snippets/use-services/start-stop-services/index.ts
docs/current/guides/snippets/use-services/start-stop-services/main.py

fix services v2 python snippets

---

cmd/dagger/functions.go
cmd/dagger/up.go
core/ids.go

fixes DEV-2780
Usage:
```sh
$ git clone https://github.com/vito/daggerverse
$ cd daggerverse/concourse
$ dagger up quickstart                   # forward all ports to random ports
$ dagger up quickstart --native          # or -n, forward all ports to same port on host
$ dagger up quickstart --port 3000:8080  # or -p, forward 3000 => 8080
```

add `dagger up` command

---

.changes/unreleased/Added-20231025-151500.yaml
ci/dagger.gen.go
core/directory.go
core/integration/directory_test.go
core/schema/directory.go
core/schema/directory.graphqls
sdk/elixir/lib/dagger/gen/directory.ex
sdk/go/dagger.gen.go
sdk/nodejs/api/client.gen.ts
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs

Support include pattern.
Support recursive option.
Add tests
Replace and complete #5686 
Related to: #5685

feat: improve entries with include and recursive

---

internal/mage/util/engine.go

Ref: https://discord.com/channels/707636530424053791/1120503349599543376/1167185105245179944

ci: update go from 1.21.2->1.21.3

---

core/modules/resolver.go

Otherwise we can get stale data.
Thankfully the new `commit` API helps us with half of this.
Continuing to use an exec-op to get the default branch is far from ideal though. The much better fix would be to move this all fully into our core api so we don't need any exec ops. But this will alleviate short term pain in the meantime.
---
Follow up issue for removing need to continue to use an exec op https://github.com/dagger/dagger/issues/5986

zenith: always run git exec ops when resolving refs

---

docs/current/guides/213240-tekton.md
docs/current/guides/snippets/tekton/dagger-task.yaml
docs/current/guides/snippets/tekton/git-pipeline-run.yaml
docs/current/guides/snippets/tekton/git-pipeline.yaml
docs/current/guides/snippets/tekton/index.mjs

This commit adds a guide about using Dagger with Tekton.

docs: Adds Tekton guide

---

sdk/java/README.md
sdk/java/dagger-java-samples/pom.xml
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/BuildFromDockerfile.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/ContainerToHostNetworking.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/CreateAndUseSecret.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/Description.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/GetDaggerWebsite.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/HostToContainerNetworking.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/ListEnvVars.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/ListHostDirectoryContents.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/Main.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/MountHostDirectoryInContainer.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/PublishImage.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/ReadFileInGitRepository.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/RunContainer.java
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/TestWithDatabase.java

* add C2H and H2C networking samples
* add image publishing sample
* add descriptions to code samples
* improve code samples build and execution

Update Java SDK code sample

---

.goreleaser.yml

This is the counterpart of dagger/nix#3 to automate releasing to the Nix repository.

Add nix package publishing to goreleaser config

---

core/integration/module_test.go

Move some tests around, but importantly add `TestModuleGoSignaturesBuiltinTypes` which checks for passing a `Directory` as a parameter directly, as a pointer, as a slice, as a variadic slice and as an `Optional`.
This works, no need for any fixes, but came across a case where I wondered if this would work so decided to backfill a test for it. Currently this works since it shares the same codepaths as passing in native types, but there's no reason for this to remain true forever - and it would be a shame to break this by accident.

Add a backfill test for various styles of passing builtin IDable types

---

cmd/codegen/main.go

This seems to have been causing cloud progress to never finish running quite often.
cc @d3rp3tt3 @kpenfound

codegen: close progrock writer

---

docs/zenith/.ruff.toml
docs/zenith/developer/821742-publishing-modules.md
docs/zenith/developer/python/419481-quickstart.md
docs/zenith/developer/python/539756-advanced-programming.md
docs/zenith/developer/python/snippets/advanced-programming/chaining/main.py
docs/zenith/developer/python/snippets/quickstart/step2/main.py
docs/zenith/developer/python/snippets/quickstart/step3a/main.py
docs/zenith/developer/python/snippets/quickstart/step3b/main.py
docs/zenith/developer/python/snippets/quickstart/trivy/main.py
docs/zenith/partials/_developer_quickstart_trivy_test.md
docs/zenith/user/quickstart/481052-conclusion.mdx
website/sidebars.js

Add zenith docs for the Python SDK

---

docs/create_embed_qs.sh
docs/current/quickstart/349011-build.mdx
docs/current/quickstart/429462-build-dockerfile.mdx
docs/current/quickstart/472910-build-multi.mdx
docs/current/quickstart/635927-caching.mdx
docs/current/quickstart/730264-publish.mdx
docs/current/quickstart/947391-test.mdx

docs: fix go snippets in quickstart

---

sdk/python/tests/engine/test_download.py

Fixes failure in main. It was failing when _INTERNAL_DAGGER_TEST_CLI_URL is set. Changed from `tmp_path` to `tmp_path_factory` to get a clean dir on every run.

Fix provision test in native OS workflow

---

docs/current/guides/128409-build-test-publish-php.md
docs/current/guides/snippets/build-test-publish-php/dagger.php

This commit improves the PHP guide by 
- improving the efficiency of the initial application image build function
- updating the `phpunit` command line for the latest PHPUnit version

docs: Improves PHP guide

---

sdk/rust/Cargo.lock

So that we fix those Dependabot security issues.
How does this look to you @kjuulh?
---
FTR: https://github.com/advisories/GHSA-c827-hfw6-qwvm

sdk(rust): Update deps

---

sdk/rust/Cargo.lock
sdk/rust/Cargo.toml
sdk/rust/crates/dagger-bootstrap/Cargo.toml
sdk/rust/crates/dagger-codegen/Cargo.toml
sdk/rust/crates/dagger-sdk/Cargo.toml

Update rust dependencies. I will follow up with a cargo release, to get the security fix out.

feat(rust-sdk): update dependencies

---

sdk/nodejs/api/client.gen.ts

Pr #6118 needed to be rebase to apply new changes on the function's method to pass tests.
Thanks @gerhard for the ping 🚀

fix: regenerate NodeJS client

---

core/integration/module_test.go

Follow-up to https://github.com/dagger/dagger/pull/6102
I actually made this right after that PR's merge, but it has been sitting in my git stash since then.

Add Python tests for id-able module types

---

engine/buildkit/filesync.go

Debugging something with a user wishing we had these logs

engine: add logs for local exports

---

sdk/python/src/dagger/_codegen/generator.py
sdk/python/src/dagger/client/_core.py
sdk/python/src/dagger/client/_guards.py
sdk/python/src/dagger/client/gen.py
sdk/python/src/dagger/mod/_converter.py
sdk/python/tests/client/test_codegen.py

Follow-up to https://github.com/dagger/dagger/pull/5881 
This is a refactor to simplify converting an ID scalar to object based on the new convention.

Python refactor: Load object from ID using new convention

---

sdk/nodejs/introspector/registry/registry.ts
sdk/nodejs/introspector/test/registry.spec.ts

Follow up #6159 to supports constructor and minor fixes
Related to DEV-3029

feat: improve registry to supports constructor

---

cmd/codegen/generator/go/templates/modules.go
core/integration/module_test.go

Fixes #5991 - the Python SDK doesn't have this issue, so we just need to do it for Go.
We can do this with our fancy new `// +private` notation on fields from #6179.
For the time being, no other pragmas are supported on fields - `optional` and `default` don't make sense at the moment, I'm not 100% sure what they would even mean.

feat: allow go modules to declare private fields

---

cmd/dagger/module.go

fixes #6066
No real UX improvement from before since it's still async and won't surface any crawl errors, but it at least does something now.

dagger mod publish: PUT /crawl instead of GET /mod

---

.changes/unreleased/Added-20231215-115147.yaml
core/integration/container_test.go
core/schema/container.go
core/schema/container.graphqls
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/nodejs/api/client.gen.ts
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs

Fixes https://github.com/dagger/dagger/issues/3284

feat: core: Add `withoutEntrypoint`, `withoutDefaultArgs`, `withoutUser` and `withoutWorkdir`

---

core/pipeline/label.go
core/pipeline/label_test.go
engine/cache/manager.go
engine/server/buildkitcontroller.go

engine: add engine label to indicate if remote cache is enabled

---

cmd/codegen/generator/go/templates/module_interfaces.go
cmd/codegen/generator/go/templates/module_objects.go
cmd/codegen/generator/go/templates/modules.go

Follow-up for previous PR that added a lot of this fairly intricate new codegen (https://github.com/dagger/dagger/pull/6254#issuecomment-1877837257)
I was a bit torn on whether to include as many concrete examples in the comments since it technically adds a small maintainance burden to keep the comments up to date whenever we change things.
However, in practice as working on this code I always ended up writing temporary throw-away comments like this (to help reason through the code to write) and also end up looking at the generated code that results. So I think keeping the comments up to date is relatively straightforward and worth the benefits they provide in terms of grounding the dense jennifer code with something less "meta" to look at.
cc @jedevc

go sdk: comment the new codegen w/ docs+examples

---

docs/ARCHIVING.md

This commit reformats and updates the archiving instructions file.

docs: Improves ARCHIVING.md

---

core/schema/container.go
core/schema/directory.go
core/schema/file.go
core/schema/git.go
dagql/dagql_test.go
dagql/objects.go
dagql/testdata/introspection.json
dagql/types.go
docs/docs-graphql/schema.graphqls
sdk/elixir/lib/dagger/gen/client.ex
sdk/elixir/lib/dagger/gen/git_ref.ex
sdk/go/dag/dag.gen.go
sdk/go/dagger.gen.go
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Just opening this PR for mostly minor things caught post-merge, will keep adding as they come up until it slows down.
So far:
* Automatically set description for deprecated args (https://github.com/dagger/dagger/pull/6297#discussion_r1452612145)
* Fixed `TypeDefinition` comments (https://github.com/dagger/dagger/pull/6405#discussion_r1452508428)

DagQL follow-ups

---

dagql/dagql_test.go
dagql/server.go

This change ensures that a non-null enumerable value always results in `[]` rather than `null` in the response. This changed with v0.9.7, affecting `Module.dependencyConfig` among other things.

dagql: fix returning `null` for empty scalar list

---

docs/current_docs/cookbook.mdx
docs/current_docs/guides/723462-use-secrets.mdx
docs/current_docs/quickstart/635927-caching.mdx

docs: Adds info about secrets and caching

---

.changes/unreleased/Added-20231204-163508.yaml
core/healthcheck.go
core/integration/services_test.go
core/net.go
core/schema/container.go
docs/docs-graphql/schema.graphqls
sdk/elixir/lib/dagger/gen/container.ex
sdk/elixir/lib/dagger/gen/port.ex
sdk/elixir/lib/dagger/gen/service.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/php/generated/Port.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/rust/crates/dagger-sdk/tests/issues/iss_33.rs
sdk/typescript/api/client.gen.ts

Closes #6160. 
I'm not sure where, if at all, the best place to test this would be. My best guess is `core/services_test.go`.
Happy to change the naming, or add documentation/cookbook examples if needed. 
~~Changie is WIP, I need the PR number from this.~~

feat: Add option to skip heathcheck on exposed ports.

---

sdk/go/internal/engineconn/session.go

It was previously possible for stderr to still be being written to while we try and get the logs for it.
This was already only possible in error-cases, but it does make the logs a lot more confusing when it happens.

fix: avoid possible datarace in startCLISession

---

engine/buildkit/client.go

Fixes #6501.
Thank goodness it's Friday, lol.
The root cause of #6501 is that every single ExecOp gets a unique digest. This means that the buildkit solver is not able to dedupe them, and instead, to ensure it only runs once, we rely on the edge merging behavior. This was kiiiinda hacky, and not super great - edge merging is supposed to be for *different* vertexes that happen to produce similar output (detected by their cache keys). We were using it for pretty much everything.
Since https://github.com/moby/buildkit/commit/e1da8b7f82f09d3e622a98961f1483f613852390 (introduced in #6481), the progress behavior changes - edge merges now duplicate the progress. This makes sense! Because edge merges are for "coincidentally" similar edges, the progress should occur for both.
The trick here is to …

fix: dedupe uncached metadata across a session

---

docs/versioned_docs/version-zenith/user/quickstart/239293-functions.mdx

This PR introduce the current output I'm getting when doing a `dagger functions`

docs: update zenith quickstart available functions

---

docs/.gitignore
docs/docusaurus.config.js
docs/versioned_docs/version-zenith/developer/typescript/506316-quickstart.mdx
docs/versioned_docs/version-zenith/user/quickstart/481052-conclusion.mdx
docs/versioned_sidebars/version-zenith-sidebars.json

docs: add typescript sdk reference on zenith

---

core/integration/module_test.go
sdk/typescript/entrypoint/entrypoint.ts
sdk/typescript/entrypoint/register.ts
sdk/typescript/introspector/scanner/scan.ts
sdk/typescript/introspector/scanner/utils.ts
sdk/typescript/introspector/test/scan.spec.ts
sdk/typescript/introspector/test/testdata/constructor/index.ts
sdk/typescript/introspector/test/testdata/multipleObjects/bar.ts
sdk/typescript/introspector/test/testdata/multipleObjects/foo.ts
sdk/typescript/introspector/test/testdata/privateMethod/helloWorld.ts
sdk/typescript/introspector/test/testdata/state/state.ts
sdk/typescript/introspector/test/utils.spec.ts

Typescript introspector now check for top level comment in the main object file.
Add unit tests and integrations tests.
Fixes DEV-3344

feat(tsSDK): supports module description

---

core/services.go

While investigating something (hopefully) unrelated to this, I found that StartBindings wasn't handling error cases well. There is an attempt to try and call `detach` on failure, but it wasn't being used.
Because we use a channel to pull the binding results, if one of the services failed to start for some reason,  we would exit early, and none of the started services would be in `running`, so when we called `detach`, none of the services would be stopped. This could easily result in dangling services.
This appears to be an older issue, and not a recent regression introduced by #6354 or #6425.

Clean up started services on StartBindings failure

---

docs/current_docs/cloud/572923-get-started.mdx

This commit fixes various formatting issues in the Dagger Cloud get started.

docs: Fixes formatting in Dagger Cloud guide

---

docs/versioned_docs/version-zenith/developer/go/457202-test-build-publish.mdx
docs/versioned_docs/version-zenith/index.mdx
docs/versioned_docs/version-zenith/quickstart/183917-daggerverse.mdx
docs/versioned_docs/version-zenith/quickstart/883939-containers.mdx

This changed in https://github.com/dagger/dagger/pull/6582
TODO:

docs: update shell -> terminal

---

cmd/codegen/generator/go/templates/modules.go
core/integration/module_python_test.go
core/integration/module_test.go

Follow up from:
- https://github.com/dagger/dagger/pull/6484
- https://github.com/dagger/dagger/pull/6529
\cc @jpadams @grouville

Go: Add support for module description

---

dagql/idtui/db.go

An unfortunate series of events can cause the TUI to rapidly consume all available memory. With whitespace. Oopsie.
1. When you call `ModuleSource.resolveDependency(gitModSource)`, it returns `gitModSource`, since there's no need to make a Git module source relative to anything else.
1. This meant the `resolveDependency` call recorded `gitModSource` as an `Output`: https://github.com/dagger/dagger/blob/5ee49b9e9a955432d688157893b299f8a6180b1d/tracing/graphql.go#L119
1. The TUI uses this output mapping to simplify IDs for more recognizable presentation. For example this lets you see `Host.directory("/path")` instead of `blob(...)`, and `bass.unit()` instead of `container.from().withDirectory().withExec()`.
1. This process is called "simplification" because it's meant to return a smaller ID …

fix runaway memory usage via wonky simplification

---

engine/client/drivers/docker.go

Started noticing some horrible output like this in my terminal logs:
Now, with an update to this printing logic:
Hopefully the multi-line warning here is alright!

chore: docker driver should avoid printing directly to stderr

---

docs/versioned_docs/version-zenith/developer/go/525021-quickstart.mdx

Follow-up to:
- https://github.com/dagger/dagger/pull/6665

docs: Clarify which main.go file to edit

---

docs/versioned_docs/version-zenith/developer/python/419481-quickstart.mdx
docs/versioned_docs/version-zenith/developer/typescript/506316-quickstart.mdx

docs: Clarifies file paths in Python and TS module guides

---

dagql/idtui/frontend.go

Receiving a simple string value from a module is a pretty common use case, and most of the time there's no trailing linebreak, so if we print it verbatim the user will either have a broken prompt or see a funny little character if their shell is polite and adds a linebreak for them.
Rather than potentially encourage module authors to add a linebreak, we'll add it ourselves, but only if stdout is a TTY, since we want piping and redirects to always "tell to the truth."
Previously: https://github.com/dagger/dagger/pull/6520#issuecomment-1916112176

idtui: print \n to tui if no trailing \n

---

cmd/codegen/codegen.go
cmd/codegen/generator/go/generator.go

All found while investigating https://github.com/dagger/dagger/issues/6706, all little minor things, but worth fixing while we're around, see commit messages for more details.

An eclectic collection of go module codegen fixes

---

cmd/dagger/functions.go
core/integration/module_functions_test.go

Fixes https://github.com/dagger/dagger/issues/6731 as described [here](https://github.com/dagger/dagger/issues/6731#issuecomment-1963062600)

cli: clarify error message when dagger functions called on non-object

---

cmd/dagger/flags.go
core/integration/module_call_test.go

The engine complains if the Host API is used with non-absolute paths. For the CLI's use case, this is not really meaningful since the user is explicitly passing paths anyways so we can safely make the paths absolute on the user's behalf automatically.
Adding to v0.10 since it's an annoying enough papercut and the fix is extremely trivial (vast majority of additions here are test code)

cli: automatically make dir+file flags absolute paths

---

docs/versioned_docs/version-zenith/quickstart/292472-arguments.mdx
docs/versioned_docs/version-zenith/quickstart/562821-hello.mdx
docs/versioned_docs/version-zenith/quickstart/853930-directories.mdx
docs/versioned_docs/version-zenith/quickstart/883939-containers.mdx

...and updates the arguments to the Go builder module

docs: Adds version numbers to quickstart module calls

---

cmd/dagger/functions.go
core/integration/module_test.go
sdk/python/src/dagger/_codegen/generator.py
sdk/python/src/dagger/mod/_arguments.py
sdk/python/src/dagger/mod/_converter.py
sdk/python/src/dagger/mod/_resolver.py
sdk/python/tests/modules/test_registration.py

Addresses Python inconsistency in:
- https://github.com/dagger/dagger/issues/6749

Zenith: Align Python with API behavior on optionals and defaults

---

docs/current_docs/index.mdx

This commit updates the text on the docs index page to match the quickstart index

docs: Updates docs index page

---

cmd/dagger/flags.go
cmd/dagger/functions.go
core/integration/module_call_test.go

Fixes https://github.com/dagger/dagger/issues/6725
This is a pre-req for a number of issues in the `v0.10.x` milestone and pretty trivial so just figured I'd get it out of the way now.

cli: add support for module(Source) args

---

cmd/codegen/generator/go/templates/module_objects.go
cmd/codegen/generator/go/templates/modules.go
core/object.go

Agh, I screwed up.
In [`fefce56` (#6750)](https://github.com/dagger/dagger/pull/6750/commits/fefce56345048b82401c7e5f210548b486fb94d1), I accidentally committed some local code, which then got missed in review.

fix: remove print statements

---

docs/current_docs/quickstart/822194-daggerize.mdx

Fix example command and update engine version.

docs: update Daggerize a project

---

docs/current_docs/developer-guide/typescript/292372-functions.mdx

This string is not formatted properly.

fix formatting

---

helm/dagger/values.yaml

Update values.yaml fixes #6891

---

.changes/unreleased/Added-20240325-132225.yaml
.changes/unreleased/Added-20240325-132338.yaml
.changes/unreleased/Added-20240325-132417.yaml
.changes/unreleased/Changed-20240325-132303.yaml

Backfilling for the release tomorrow

add changelogs for v0.10.3 release

---

sdk/rust/crates/dagger-codegen/src/rust/functions.rs
sdk/rust/crates/dagger-sdk/src/gen.rs

Remove unneeded return statement

refactor(sdk/rust): remove unneeded return statement

---

.changes/v0.11.0.md

Also edited https://github.com/dagger/dagger/releases/tag/v0.11.0 with this

chore: backfill change log for fix in v0.11.0

---

sdk/python/runtime/main.go

Fix using Python's runtime module directly

---

core/integration/module_test.go
core/schema/sdk.go

fix(core): add missing entry to generated Git files

---

.github/workflows/publish-sdk-elixir.yml
.github/workflows/publish-sdk-go.yml
.github/workflows/publish-sdk-php.yml
.github/workflows/publish-sdk-python.yml
.github/workflows/publish-sdk-rust.yml
.github/workflows/publish-sdk-typescript.yml
.github/workflows/publish.yml

Fixes failing jobs on `main` after merge of #6843 https://github.com/dagger/dagger/actions/runs/8598160866/job/23558410143.

fix: install dagger cli for publish jobs

---

docs/current_docs/manuals/developer/typescript/356352-runtime.mdx
docs/sidebars.ts

docs: add bun runtime explanations

---

sdk/typescript/runtime/main.go

- Bun cache volume should include the version number
- tsx installation should be part of the base image (so cannot be cache invalidated)
- @TomChv I think there's some more low-hanging fruit here - the pipeline here doesn't seem to cache in the expected way, we should ensure that wherever possible we can install the dependencies with as few cachebusters around as possible
- Don't mount over /opt (this breaks yarn if you try and use it)

fix: minor fixes in ts sdk

---

docs/_README.md
docs/current_docs/manuals/developer/go/snippets/custom-types/main.go
docs/current_docs/manuals/developer/typescript/snippets/custom-types/index.ts

Just a simple suggestion to change docs.

Resolve mix of British and American spelling

---

telemetry/labels.go

Fixes https://github.com/dagger/dagger/issues/6452.
Instead of messing around with a bunch of remotes, etc, we can apply this simple little trick.
`GITHUB_REF` contains the "the fully-formed ref of the branch or tag that triggered the workflow run" (see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).
Now, if the ref starts with "refs/pull/", it's a pull request. These usually end in "/merge", to indicate that this is the result of merging with the base branch. However, we can just swap this "/merge" for a "/head" to get the actual head - then we can grab all the interesting commit details from there.
What's really cool is that these should just all be available on the "origin" - GitHub automagically populates them for us.

fix: ensure we get correct data for prs

---

sdk/typescript/.eslintrc.cjs
sdk/typescript/dev/node/src/index.ts
sdk/typescript/dev/src/index.ts
sdk/typescript/runtime/template/src/index.ts

This comment is not useful for the user and pretty confusing in my opinion so I removed it

chore: remove eslint cmd from template ts module

---

core/integration/cacert_test.go

Clicked merge on the ca cert PR before refreshing the page and seeing it was out of date with main, so missed this signature needing updating.

ci: fix args to updated devEngineContainer in cacert test.

---

ci/main.go
ci/sdk.go

Just a few comments to document our own Dagger functions.

Add API documentation to our CI

---

docs/current_docs/manuals/developer/typescript/370239-module-structure.mdx

Update 370239-module-structure.mdx

Express experimental support for Bun in docs

---

helm/dagger/Chart.yaml

This updates the helm app version to the latest release engine.

Bump helm app version to latest

---

cmd/engine/main.go

move buildkit logs to extra-debug level

---

cmd/dagger/functions.go

Alternative solution to #7183
Discussed in https://github.com/dagger/dagger/issues/6943#issuecomment-2067514623.
```console
dagger -m github.com/levlaz/daggerverse/mariadb@v0.2.1 functions base --help
```
**Before**
```
Error: no function '--help' in object type 'Container'
```
**After**
```
List available functions in a module.
This is similar to `dagger call --help`, but only focused on showing the
available functions.
USAGE
dagger functions [flags] [FUNCTION]...
FLAGS
-m, --mod string   Path to dagger.json config file for the module or a directory containing that file.
Either local path (e.g. "/path/to/some/dir") or a github repo (e.g.
"github.com/dagger/dagger/path/to/some/subdir")
GLOBAL FLAGS
-d, --debug             show debug logs and full verbosity
--progress string   progress …
```

cli: Fix flag parsing when interspersed with arguments in `dagger functions`

---

docs/current_docs/manuals/user/932727-troubleshooting.mdx

This commit updates the troubleshooting guide on the basis of the discussion at https://discord.com/channels/707636530424053791/1232715125480493127
Closes #7209

docs: Updates troubleshooting guide

---

ci/README.md
ci/mage/util/dagger.go
dagger.json

This significantly improves initial directory upload speed, on my computer this goes from 4.8s to a much better 2.5s.
*Ideally*, we could also avoid uploading the git directory. This is a bit of a pain *right now* though, so we don't do it!

ci: add default view to dagger json

---

docs/current_docs/integrations/533927-argo-workflows.mdx
docs/current_docs/integrations/snippets/argo-gomodcache.yaml
docs/current_docs/integrations/snippets/argo-workflow.yaml
docs/current_docs/integrations/snippets/tekton-dagger-task.yaml

changes from https://github.com/dagger/dagger/pull/7235

add more context to dagger and ci integrations pages

---

sdk/python/runtime/main.go

Silenced output when creating/updating the `requirements.lock` file. Since we create lots of modules in our test suite this adds a lot to logs because of all the hashes.
No output:
Before, it printed ≈ 450 lines of logs. For example:
```
1	Resolved 34 packages in 931ms
2	# This file was autogenerated by uv via the following command:
3	#    uv pip compile --generate-hashes -o requirements.lock sdk/pyproject.toml pyproject.toml
4	anyio==4.3.0 \
5	    --hash=sha256:048e05d0f6caeed70d731f3db756d35dcc1f35747c8c403364a8332c630441b8 \
6	    --hash=sha256:f75253795a87df48568485fd18cdd2a3fa5c4f7c5be8e5e36637733fce06fed6
7	    # via
8	    #   gql
9	    #   httpx
10	attrs==23.2.0 \
11	    --hash=sha256:935dc3b529c262f6cf76e50877d35a4bd3c1de194fd41f47a2b7ae8f19971f30 \
12 …
```

chore: silence output from uv compile

---

.changes/unreleased/Added-20240506-103959.yaml
core/container.go
core/integration/container_test.go
core/schema/container.go
docs/docs-graphql/schema.graphqls
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Follow up to:
- https://github.com/dagger/dagger/pull/7291
- https://github.com/dagger/dagger/issues/6898#issuecomment-2004376360

api: add `Container.withoutDirectory` and `Container.withoutFile`

---

.changes/unreleased/Added-20240506-102045.yaml
core/container.go
core/integration/secret_test.go
core/schema/container.go
docs/docs-graphql/schema.graphqls
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Fixes https://github.com/dagger/dagger/issues/7274

api: add `Container.withoutSecretVariable`

---

cmd/dagger/functions.go

Discovered during #7272, when trying to make sense of some of the output.
Before, the context was not being propagated, so when loaded, all CLI args would be associated with the root, instead of under the initialize span (where it makes a lot more sense).
Before:
❯ dagger call -vv --source=. version string
✔ connect 0.9s
✔ starting session 0.2s
┃ OK!
✔ initialize 7.9s
✔ ModuleSource.resolveFromCaller: ModuleSource! 0.1s
✔ ModuleSource.asModule: Module! 0.1s
✔ Module.withSource(
source: ✔ ModuleSource.resolveFromCaller: ModuleSource! 0.0s
): Module! 0.1s
✔ ModuleSource.resolveFromCaller: ModuleSource! 0.1s
✔ ModuleSource.resolveFromCaller: ModuleSource! 0.1s
✔ upload /home/jedevc/Documents/Projects/dagger from dragon (client id: rmi44eawc8e5b1mgzkqurv8rf) (exclude: **/.git) (include: …

fix: attach cli args to initialize parent

---

ci/build/sdk.go

Attempting to revive #6248 - see discussion in discord [here](https://discord.com/channels/707636530424053791/1123687185837740053/1232844838324408402).

chore: add git to go sdk

---

cmd/dagger/functions.go

Fixes https://github.com/dagger/dagger/issues/7369

cli: don't print `<nil>`

---

README.md

updated link to community activities since it was broken

Update community link in README

---

cmd/dagger/cloud.go
docs/current_docs/reference/979596-cli.mdx

Follow-up on:
- https://github.com/dagger/dagger/pull/7125
This adjusts for conventions adopted in:
- #7170
- #7143

cli: cleanup on `dagger login`

---

docs/current_docs/integrations/533927-argo-workflows.mdx

Added Kyle's demo to the integration page as an additional resource.

Add Argo workflow demo video

---

docs/current_docs/manuals/developer/go/snippets/visibility/main.go

Reported in 
- https://github.com/dagger/dagger/issues/7455#issuecomment-2129444741

fix(docs): fix wrong visibility in Go snippet

---

cmd/dagger/functions.go
cmd/dagger/module.go

Follow-up to:
- https://github.com/dagger/dagger/pull/7418
At minimum this produces a debug level log for core functions, to reduce noise:
For module functions, it’s raised as a warning to make it more visible to module authors:
In `dagger functions`, since it’s just listing functions, it’s shown in faded color at the end of the output:
When listing functions with `dagger call` and without `--help` it’ll probably look more like `dagger functions`:
- https://github.com/dagger/dagger/issues/6515
Instead of the warning/debug log, I’ve considered adding the same faded color text to the output of `--help` itself, but I’m trying to avoid adding noise to that output and to leak more `dagger call` specific tweaks to the general template, although I plan on making that more composable at some …

cli: add feedback on skipped functions

---

.github/workflows/publish-sdk-python.yml
.github/workflows/publish-sdk-typescript.yml

ci: fix issues in publish steps

---

engine/client/client.go

This ordering issue caused a couple of issues:
- Error messages indicated telemetry issues, when actually the engine wasn't connected to properly.
- The `retry` logic has exponential backoff that isn't capped - whereas `newBuildkitClient` uses buildkit's `Wait` which has a more reasonable default of retrying every second until a connection is established (which was our previous behavior before we added this telemetry).
This is a fairly likely cause of the issue that @marcosnils was seeing with slow engine `connect` timings - even if it's not, still probably worth keeping the original order here.

fix: create buildkit client before establishing telemetry connection

---

sdk/go/internal/engineconn/session.go

Instead of just closing it immediately. This could potentially result in the child process crashing with "broken pipe" if it accidentally wrote to this file descriptor.
This is a weird edge case discovered as part of investigating https://github.com/jedevc/dagger/tree/fix-weird-stall/examples/sdk/go/repro. This could have occurred if any primary output was detected during progress rendering: https://github.com/dagger/dagger/blob/24d1dcbc591c3d29c8d9ca12ea7cbd893cf14d55/dagql/idtui/frontend.go#L251-L254

fix(go): leave and discard stdout

---

.changes/unreleased/Added-20240529-135231.yaml
core/file.go
core/integration/file_test.go
core/schema/file.go
docs/docs-graphql/schema.graphqls
sdk/elixir/lib/dagger/gen/file.ex
sdk/go/dagger.gen.go
sdk/php/generated/File.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Fixes #6474 
~~⚠️ This PR also includes @jedevc commit from [f7b3a9c](https://github.com/dagger/dagger/pull/7438/commits/f7b3a9cbb9d6ca5cc53bc280d9352cebdba97258)[f7b3a9c](https://github.com/dagger/dagger/pull/7438/commits/f7b3a9cbb9d6ca5cc53bc280d9352cebdba97258) to handle global client generation.~~ Merged by #7492 
Fixes OSS-62

feat: add `withName` function to File

---

docs/STYLE_GUIDE.md

This is a long-overdue update of the style guide.

docs: Update style guide

---

.github/dependabot.yml
.github/workflows/stale.yml

Unify dependabot and stale labels.

Update depdendabot and stale labels

---

.changes/unreleased/Fixed-20240607-221801.yaml

The #7564 already merged but I forgot to add a changelog. 🙏

Add changie log for #7564

---

engine/buildkit/linux_namespace.go

There was a race condition where contexts get canceled after a job is sent to the netns worker but before the result got read. This caused runInNetNS to exit (due to canceled context) but the result chan to never be read from. It was crucially an unbuffered chan, which resulted in the worker never being able to exit and the whole container cleanup to block indefinitely.
The fix here is just to make that chan buffered with a size of 1 so that the worker doesn't ever get blocked trying to write to it.
There's a few other related changes of making some other chans buffered and explicitly closing them with a defer (to handle panic cases) which aren't needed to fix this issue but seemed worth tidying up now.
---
I hit this on https://github.com/dagger/dagger/pull/7608, but it was very hard to …

executor: fix deadlock in service exit from netns workers

---

install.sh

Reported in discord: https://discord.com/channels/707636530424053791/1250124959406227547/1250124959406227547
Introduced in #7544.

fix: remove bashisms in install.sh

---

.github/actions/call/action.yml
.github/workflows/engine-and-cli-publish.yml
.github/workflows/sdk-go-publish.yml
.github/workflows/sdk-php-publish.yml

Follow-up to https://github.com/dagger/dagger/pull/7483.
See failing checks at https://github.com/dagger/dagger/actions/runs/9485458769/job/26137438579.

ci: fix external module calls

---

sdk/python/.changes/unreleased/Fixed-20240613-143237.yaml
sdk/python/codegen/requirements-dev.lock
sdk/python/codegen/requirements.lock
sdk/python/codegen/src/codegen/generator.py
sdk/python/src/dagger/client/gen.py

Fixes https://github.com/dagger/dagger/issues/7652

fix(sdk/python): incorrect code generation for `Self` arguments

---

ci/std/go/main.go
cmd/dagger/main.go
engine/client/client.go
engine/server/session.go
engine/telemetry/pubsub.go

Extracting from #7532 for a more minimal diff.

fix draining when clients exit uncleanly

---

ci/sdk_go.go

Follow up to #7631
This is fairly fiddly to do correctly. Essentially, we need to be able to handle at least these inputs:
- Branch names, like `main`
- Tag names, like `v0.11.7`
- Full refs, like `refs/pull/<pr>/merge`
We can't simply use `git fetch <ref>`, since that doesn't create a local ref copy. We shouldn't use a refspec that mirrors to a single name, since that strips `refs/tag/...` which means tags are lost.
The correct way to do this is using a `git fetch` refspec, to mirror all remote refs that match the target name to a local ref. Then this satisfies all the above inputs correctly.
Additionally, for dry-runs, I've added a `rev-parse` sanity check, so can check the results more easily.

ci: fix git publish tag confusion

---

dagql/idtui/frontend_plain.go

There were a couple of weird whitespace handling issues with the plain progress.
1. If a program produces logs at pace, then ExportLogs will be called on large chunks, and is not guaranteed to end with a newline. In this case, that last line should be marked as pending, and we should hold it until the rest of that line is received (flushing any unfinished lines when the span terminates).
2. If a program writes "\r" carriage return characters in the middle of a line, we were essentially writing over our prefixes, and making a mess. We can handle this by removing all content before the last "\r" in a line.

fix: improve plain progress log chunks

---

sdk/python/src/dagger/mod/cli.py

Fixes https://github.com/dagger/dagger/issues/7539

fix(sdk/python): fix import error when it's not the main module

---

install.ps1

- Add checksum validation
- Delete the file if the checksum fails
- Install-Dagger should also use $env:USERPROFILE
- fix for DaggerCommit regex, it should be optional (╯°□°）╯︵ ┻━┻

chore: improve install.ps1 part 2

---

docs/current_docs/partials/_install-cli.mdx
docs/docusaurus.config.ts

@jedevc @levlaz 
I noticed Powershell is also not style, upon further checking out docusauraus and mdx, I think we're only missing the addition of 'powershell' in the languages array, which I validated from their documentation.

docs: powershell install instructions

---

docs/current_docs/quickstart/snippets/daggerize/go/main.go
docs/current_docs/quickstart/snippets/daggerize/python/__init__.py
docs/current_docs/quickstart/snippets/daggerize/typescript/index.ts
docs/current_docs/quickstart/snippets/publish/python/__init__.py
docs/current_docs/quickstart/snippets/publish/typescript/index.ts
docs/current_docs/quickstart/snippets/simplify/python/__init__.py
docs/current_docs/quickstart/snippets/simplify/typescript/index.ts

Fixes https://github.com/dagger/dagger/issues/7677

fix(docs): fix missing await in quickstart snippets

---

docs/current_docs/manuals/administrator/engine/custom-runner.mdx

docs: fix custom CA certs path in custom runner docs

---

engine/client/drivers/docker.go

Spans that cause non-fatal errors should only appear in the logs if their parent fails out (the encapsulated behavior). Otherwise, they just contribute noise.
See the discord discussion here: https://discord.com/channels/707636530424053791/1255153783470821488/1255160804957749352

chore: some docker driver spans should be encapsulated

---

core/schema/container.go
core/schema/directory.go

Prevent Terminals from re-opening when Containers get re-evaluated

---

.changes/unreleased/Fixed-20240527-120411.yaml
core/integration/module_call_test.go
core/integration/module_config_test.go
core/schema/modulesource.go
core/schema/modulesource_test.go

* Closes https://github.com/dagger/dagger/issues/7212

fix: allow absolute paths for local module paths

---

dev/README.md

Update contributor guide to use new dev module

---

.github/workflows/changelog.yml

Fix https://github.com/dagger/dagger/pull/7772#issuecomment-2201157437.

ci: fix changelog checking pr (take 2)

---

sdk/python/.changes/unreleased/Fixed-20240702-185748.yaml
sdk/python/src/dagger/client/_session.py
sdk/python/src/dagger/mod/_module.py

Fixes https://github.com/dagger/dagger/issues/7673

fix(sdk/python): restore telemetry initialization in modules

---

docs/current_docs/integrations/kubernetes.mdx

Add link to module and resources

docs:update resources

---

core/service.go

The previous logic had a few inconsistencies:
1. It returned exit errors after stop was called, but other services didn't
2. It read exit errors from a chan every time, which caused unneeded timeouts waiting for the chan in the case where stop gets called multiple times.
Fixes https://github.com/dagger/dagger/issues/7732

core: align c2h tunnel exit handling with other services

---

network/netinst/dnsmasq.go

@matipan noticed that in some integration tests where the engine is run as a service, when SIGTERM is sent to the engine it was also being sent to dnsmasq, which caused it to shutdown quickly and interfere with the engine's attempt to gracefully shutdown (e.g. flush cache, which can rely on dnsmasq still existing).
* related discord thread: https://discord.com/channels/707636530424053791/1260319690002141286/1260319691906220082
This turned out to be due to the fact that dumb-init, by default, will forward signals to the whole process group, so when it sends SIGTERM to the engine, that signal also went to dnsmasq.
After looking around, it *seems* like forwarding signals to the whole process group is probably a better default behavior and closer to expectations (though there's certainly no …

engine: prevent dnsmasq from shutting down prematurely

---

cmd/dagger/functions.go

Previously we would just show `initialize` with nothing beneath it except for a ton of spam.
Now we'll show 3 steps beneath it which hopefully let the user know a bit more about what's going on:

add fine-grained spans beneath initialize

---

engine/server/session.go

In theory schemas should be loadable based on prior validation by the time a query that loads them gets called, but we do see errors returned on schema load sometimes.
Previously, these were just getting turned errors with the message written direct to the body of the response, but that confuses graphql clients who expect a json format.
This updates these errors to use the right format so clients see actual comprehensible errors.
---
Since it's not really expected for these errors to happen (afaict), it's hard to write an integ test for, so just went with a manual test using this diff:
```diff
// get the schema we're gonna serve to this client based on which modules they have loaded, if any
-       schema, err := client.deps.Schema(ctx)
+       // TODO:
+       // schema, err := …
```

engine: send gql errors when schema fails to load

---

cmd/dagger/module.go
docs/current_docs/reference/cli.mdx

chore: update CLI -m for expanded git support

---

docs/current_docs/adopting.mdx
docs/current_docs/quickstart/conclusion.mdx

Expand the "Adopting Dagger" page with a framework for successful adoption.

Docs: Adopting Dagger

---

docs/current_docs/manuals/developer/snippets/services/persist-service-state/go/main.go
docs/current_docs/manuals/developer/snippets/services/persist-service-state/python/main.py
docs/current_docs/manuals/developer/snippets/services/persist-service-state/typescript/index.ts
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-1/go/main.go
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-1/python/main.py
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-1/typescript/index.ts
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-2/go/main.go
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-2/python/main.py
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-2/typescript/index.ts
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-3/go/main.go
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-3/python/main.py
docs/current_docs/manuals/developer/snippets/services/service-lifecycle-3/typescript/index.ts
docs/current_docs/manuals/developer/snippets/services/start-stop-services/go/main.go
docs/current_docs/manuals/developer/snippets/services/start-stop-services/python/main.py
docs/current_docs/manuals/developer/snippets/services/start-stop-services/typescript/index.ts
docs/current_docs/manuals/user/artifacts/consumption/export.mdx
docs/current_docs/manuals/user/artifacts/production/containers.mdx
docs/current_docs/manuals/user/artifacts/production/directories.mdx
docs/current_docs/manuals/user/artifacts/production/files.mdx

Continuing from:
- https://github.com/dagger/dagger/pull/7884
TODO:

docs: update docs with breaking changes from v0.12.0 (part 2)

---

docs/current_docs/faq.mdx

I am taking this gem that @jedevc shared in discord the other day and adding it to a FAQ entry since this is a common question that we hear.
https://discord.com/channels/707636530424053791/1242180731548209293/1260175488840634448

Add Windows Container Entry to FAQ

---

internal/cloud/auth/auth.go

@marcosnils Accidentally didn't push this change for #7932. I blame the power outage. :man_facepalming:

login: tweak wording

---

engine/telemetry/pubsub.go

This is a quick band-aid; we're seeing draining issues again, possibly as a result of [`c712183` (#7735)](https://github.com/dagger/dagger/pull/7735/commits/c712183bfe1506577c2cfdbad4c620e932344025). My guess is we were relying on the child-abandoning code path (as evil as it sounds) even in the happy path, and something is causing these spans to never complete:
* https://dagger.cloud/dagger/traces/5f6ba78ea08e7c46a0e4bc14149683fb#36dd05401b560b9d ([GHA](https://github.com/dagger/dagger/actions/runs/9981275585/job/27584543245?pr=7965))
* https://dagger.cloud/dagger/traces/7125da6b26fa42452efbbaa699a64d0f#abc2036272d57dee ([GHA](https://github.com/dagger/dagger/actions/runs/9981275589/job/27584543421?pr=7965))
Rather than stare into the abyss for another month, I'm hoping to eliminate …

time out draining after 10 seconds

---

docs/current_docs/integrations/jenkins.mdx
docs/current_docs/integrations/snippets/Jenkinsfile

I got some great additional feedback from Marcos after we merged #7892 so I am adding these in here now.

docs: add feedback into Jenkins guide

---

dagql/idtui/frontend_pretty.go

As mentioned :tada: :tada:
@vito I'm sure you'll love this, but also now, I want the vim fold operators :laughing: `zo`, `zc`, all that.

feat: add vim gg/G movement operators

---

linters/dagger.json

The contents of this were moved into dev/

chore: remove the old linters dir

---

.changes/unreleased/Changed-20240719-120907.yaml
cmd/dagger/module.go
core/integration/module_config_test.go
core/integration/module_test.go
core/integration/module_typescript_test.go
docs/current_docs/reference/cli.mdx

fix: init in current directory instead of `dagger`

---

core/integration/module_test.go

Fixes a linting failure from:
- https://github.com/dagger/dagger/pull/7824

fix engine linter in main

---

docs/current_docs/integrations/google-cloud-run.mdx
docs/current_docs/integrations/java.mdx
docs/current_docs/integrations/php.mdx
docs/current_docs/manuals/developer/module-structure.mdx
docs/current_docs/quickstart/daggerize.mdx

follow-up to #7824 
Went for minimal changes here to maintain correctness. I _think_ each of these makes sense in context but could use a double check.

docs: revise for new --source=. default

---

.github/workflows/engine-and-cli-publish.yml
sdk/python/requirements.txt

Also remove `requirements.txt` since it's a zombie at this point (just points to a file that was rm'd).

switch Python publish tests to uv

---

.github/actions/call/action.yml
.github/workflows/_sdk_check.yml
.github/workflows/docs.yml
.github/workflows/engine-and-cli-publish.yml
.github/workflows/engine-and-cli.yml
.github/workflows/helm-publish.yml
.github/workflows/helm-test.yml
.github/workflows/sdk-elixir-publish.yml
.github/workflows/sdk-go-publish.yml
.github/workflows/sdk-php-publish.yml
.github/workflows/sdk-python-publish.yml
.github/workflows/sdk-rust-publish.yml
.github/workflows/sdk-typescript-publish.yml
RELEASING.md
dev/dagger.json
dev/go.mod
go.mod

Improve Releasing during v0.12.2

---

dev/main.go

The recent changes to dagger codegen (#7872) meant that locally generated `dagger.gen.go` files were overwriting the generated files. This was because `GeneratedContextDirectory` takes the entire context directory (including any local `dagger.gen.go` files), and applies it's changes on top. So if `dev/go/dagger.gen.go` was generated on an old version of dagger, then it would be applied as part of a later codegen step, e.g. from `sdk/typescript/runtime` :scream: 
The reason this happened is because we changed the dag construction to be more parallelized, instead of stacked - to do this properly though, we need to select each module directly, and compose them all together afterwards. Making it stacked is the right call - it speeds up execution - but in this form it wasn't quite right.
I …

fix: ensure dagger dev source gen works

---

core/integration/engine_test.go

This test flakes occasionally due to timeout errors (just enough to be annoying). [Looking at the traces](https://dagger.cloud/dagger/traces/5a3c0a61daf4b164dff6b580605eace2?span=53daff10b1926f68#e7124c9fee8125f1), it seems like when under heavy load the container import step just takes a while and brings it close enough to the 1 minute timeout to hit it during the test.
This updates the test case to first do a synchronous import of the engine container and only after that apply the timeout. If my understanding is correct that should ensure the existing highly generous 1 minute timeout is only being applied to the part of the test where we care about it.

tests: restructure TestExitsZeroOnSignal to avoid timeout flake

---

core/integration/module_python_test.go

Fixes https://github.com/dagger/dagger/issues/7662

fix PythonProjectLayout test flake

---

sdk/python/.changes/unreleased/Dependencies-20240731-220643.yaml
sdk/python/dev/dagger.json
sdk/python/dev/pyproject.toml
sdk/python/pyproject.toml
sdk/python/runtime/Dockerfile
sdk/python/uv.lock

Split from:
- https://github.com/dagger/dagger/pull/8055

chore: update python deps

---

dev/cli.go

When publishing commits, the Tag field will be set to a commit. We should check using git to see if the tag actually exists, and if not, set the dummy release version.

ci: fix cli publish for untagged releases

---

docs/current_docs/quickstart/daggerize.mdx

docs: change daggerize cloud title

---

docs/current_docs/integrations/jenkins.mdx

Add Jenkins demo from community call to resource page

Docs: Add Jenkins demo to resources

---

cmd/dagger/version.go

This can help manually check that it's all correctly working and everything :tada:
See https://github.com/Homebrew/homebrew-core/pull/179252#discussion_r1700461628 for the context for this.

chore: add engine tag to dagger version output

---

docs/current_docs/partials/_install-cli.mdx

docs: add view source to install instructions

---

dev/sdk_elixir.go

* Drop Elixir v1.14 and add Elixir v1.17.
* Improve Elixir version management by using map instead of slice of string. With map, we can freely manage OTP version and OS separately.
* Visualization improvement, just using `errgroup.Go` is quite hard to read on the TUI visualization. In this changes, add the tracer to it by labeling it with `test - elixir/<version>` pattern.
* Add `dagger_codegen` test by running only elixir latest version. And add tracer to separate between `dagger` SDK and `dagger_codegen` under test version.

feat(dev): improve testing in sdk elixir dev module

---

dev/docs.go
dev/sdk_go.go
dev/sdk_python.go
dev/sdk_typescript.go

Use custom spans to make traces more readable
Signed-off-by: Solomon Hykes <solomon@dagger.io>

pipelines: lint: more readable traces

---

docs/static/api/reference/index.html

When merging the new linting steps in #8118, I forgot to rebase and regenerate on top of #8114 :(
This fixes the failing job on main: https://github.com/dagger/dagger/actions/runs/10316831631/job/28559856006

docs: run docs generate

---

docs/current_docs/integrations/snippets/actions-ghcr.yml
docs/current_docs/integrations/snippets/actions.yml
docs/current_docs/integrations/snippets/google-cloud-run/main.yml

docs: Update GitHub Action syntax

---

docs/current_docs/manuals/administrator/engine/custom-registry.mdx

docs: Add clarification to custom registry docs

---

docs/current_docs/integrations/kubernetes.mdx

Add  Diego Ciangottini's community demo to Kubernetes integration page

Add Kubernetes demo to resources

---

.changes/unreleased/Fixed-20240810-021228.yaml
cmd/dagger/flags.go

Fixes https://github.com/dagger/dagger/issues/8119

fix: make retrieve secret from command works on Windows 

---

.dagger/README.md
.dagger/helm.go
.dagger/main.go
.dagger/sdk.go
.dagger/test.go
.github/workflows/helm-publish.yml
.github/workflows/helm-test.yml
dagger.json

This will help avoid issues like https://github.com/dagger/dagger/issues/7916 in the future - this took a lot of messing around to fix, so it would be good to *never* hit this again.

ci: add helm install tests

---

docs/current_docs/integrations/_integration.mdx.template
docs/current_docs/integrations/argo-workflows.mdx
docs/current_docs/integrations/jenkins.mdx
docs/current_docs/integrations/kubernetes.mdx
docs/current_docs/integrations/snippets/argo-workflow.yaml

This commit updates the Argo Workflows page to match the new template. It also makes minor improvements and copy edits to the existing Jenkins and Kubernetes integration pages.

docs: Update Argo Workflows page, improve Kubernetes and Jenkins pages

---

.changes/unreleased/Fixed-20240820-163519.yaml
.dagger/util/shell.go
cmd/dagger/module.go
core/integration/module_call_test.go

Fixes https://github.com/dagger/dagger/issues/8161.

fix: error out if local module does not exist

---

core/integration/module_test.go

#8191 may be causing a lot of failures on main and PRs based off main. Not 100% sure yet but they seem to have started with that PR being merged. Confirming by trying a revert here. Example failures:
1. https://dagger.cloud/dagger/traces/3c464d3dda1f22988df596b9595e9952
2. https://dagger.cloud/dagger/traces/05d1adca2d582b9fc1683daeefbf2f48

Revert "tests: try killing subprocesses harder if they misbehave"

---

core/integration/module_test.go
core/modulesource.go

Follow up to #7744 to point relative path to source dir instead of root dir.

fix: context dir relative path point to source dir

---

cmd/dagger/functions.go

ref: coming from https://discord.com/channels/707636530424053791/1278366709454995577

cli: improve functions init main object not found error msg

---

docs/current_docs/manuals/developer/package-managers.mdx
docs/current_docs/manuals/developer/runtimes.mdx
docs/sidebars.ts

Add `packageManager` config doc page.
Update runtime page with version configuration.

docs: add package manager config page & update runtime

---

.dagger/docs.go

The schema reference generation takes the `schema.graphqls` file as input, so each generate step effectively required two passes. This is kinda messy, so we should just feed one generation step into the next.
This is kinda neat, since the dagger engine will deduplicate the schema generation, so we don't end up computing it and generating it twice.

ci: fix schema reference generation

---

.dagger/engine.go
sdk/java/pom.xml

This should hopefully improve visibility of new vulnerabilities.
cc @gerhard @samalba

ci: run trivy on source directory

---

docs/current_docs/adopting.mdx

Add assurance for the amount of time it takes to daggerize, and link to livestream examples.

Docs: add livestream playlist to adoption page

---

.changes/unreleased/Fixed-20240906-124256.yaml
cmd/dagger/flags.go
core/integration/module_call_test.go

Fixes https://github.com/dagger/dagger/issues/8320

fix(cli): fix default value on Platform flag

---

core/integration/module_python_test.go
sdk/python/.changes/unreleased/Fixed-20240906-123348.yaml
sdk/python/src/dagger/mod/_arguments.py

Fixes https://github.com/dagger/dagger/issues/8285

fix(python): fix `dagger.Ignore` in attributes

---

core/integration/module_python_test.go
sdk/python/.changes/unreleased/Fixed-20240906-103058.yaml
sdk/python/src/dagger/mod/_converter.py
sdk/python/src/dagger/mod/_exceptions.py
sdk/python/src/dagger/mod/_module.py
sdk/python/src/dagger/mod/_utils.py

Fixes https://github.com/dagger/dagger/issues/8342

fix(python): fix use of Annotated with InitVar

---

core/integration/module_test.go
core/modulesource.go

Changes relative path root to root source dir instead of source dir based on https://discord.com/channels/707636530424053791/1280818249633890365/1282809411353575424
Adapt tests based on that.

fix: relative path in context dir now point to root source dir

---

.changes/unreleased/Changed-20240910-191026.yaml
cmd/dagger/call.go
cmd/dagger/functions.go
cmd/dagger/query.go
cmd/dagger/run.go
dagql/idtui/frontend.go
dagql/idtui/frontend_plain.go
dagql/idtui/frontend_pretty.go

chore: print the cloud trace url after progress output

---

sdk/python/.changes/v0.13.0.md
sdk/python/CHANGELOG.md
sdk/python/dev/pyproject.toml
sdk/python/runtime/Dockerfile

Follow up to:
- https://github.com/dagger/dagger/pull/8408
- https://github.com/dagger/dagger/pull/8311

chore: update uv and change log instructions

---

sdk/rust/crates/dagger-sdk/src/.gitattributes

chore: add .gitattributes to rust dagger SDK

---

engine/client/drivers/docker.go

Noticed this with when sending `CTRL+C` to a `dagger call` command during the driver initialization, and we'd see the interrupt failed to immediately kick in.
This is because we have lots of *expected* errors from certain commands - the easy way to handle this is to just check if the error was a context cancelled error, and we can just bail out at that point immediately.

chore: docker driver should exit immediately if cancelled

---

engine/cache/provider.go

instrument both layer and cachemount downloads with corresponding OTEL
spans along with their corresponding layer digest and size.

engine: add opentelemetry spans to magicache downloads

---

.dagger/build/builder.go
cmd/dagger/main.go
cmd/dagger/version.go
docs/current_docs/reference/cli.mdx
engine/distconsts/consts.go
engine/version.go

Run an update check in the background and notify if updates are available.
This is a best effort check: if not completed by the time the command completes, then the check is cancelled.
TODO:
- ~~Replace the http check with a registry check [/cc @marcosnils @gerhard]~~
- ~~Better TUI integration [/cc @vito]~~

update checks for the CLI

---

.changes/unreleased/Fixed-20240917-100238.yaml
cmd/dagger/module.go
core/integration/module_call_test.go

Fixes https://github.com/dagger/dagger/issues/8464

fix(cli): fix secret plaintext being printed on screen

---

sdk/python/.changes/unreleased/Fixed-20240917-170801.yaml
sdk/python/src/dagger/mod/_resolver.py

Noticed this from a support request in Discord.

fix(python): fix error message interpolation

---

core/integration/platform_test.go

This is all theoretical still, but the flakes we see in the test would be explained by actual expected behavior: cache mounts are best effort and free to be pruned at any time. If the cache mount used in this test is pruned in the middle of it (between execs that use it), then we'd expect to see the errors we're getting of `No such file or directory`.
This attempts to deflake the test by running an exec in the background that has the cache volume mounted throughout the test.
Other possible mitigations were even more complicated (i.e. run a separate engine with configuration that disabled cache volume pruning, etc.), so while this feels a little weird I can't think of anything better at this time other than removing the test entirely.
---
Fixes (theoretically) …

tests: deflake TestPlatform/TestCacheMounts

---

sdk/typescript/runtime/main.go

Follow-up to https://github.com/dagger/dagger/pull/7864#discussion_r1712142479

fix: remove required path in ts sdk

---

sdk/php/composer.lock
sdk/php/dev/composer.json
sdk/php/dev/composer.lock
sdk/php/dev/dagger.json
sdk/php/dev/src/PhpSdkDev.php
sdk/php/tests/Integration/GraphQl/QueryBuilderChainTest.php

Add DaggerFunction `format` to PhpSdkDev

---

sdk/php/dev/dagger.json
sdk/php/runtime/template/README.md
sdk/php/src/Command/EntrypointCommand.php
sdk/php/src/ValueObject/DaggerFunction.php
sdk/php/src/ValueObject/DaggerObject.php
sdk/php/tests/Unit/Fixture/DaggerObjectWithDaggerFunctions.php
sdk/php/tests/Unit/ValueObject/DaggerFunctionTest.php

feat: Support constructors in PHP SDK

---

core/schema/modulesource.go

Given how parseRefString works, it could happen that the ref parsed
yields to a `StatCallerHostPath` failure and also be a local ref as
well. This commit shorts circuits the function by exiting early and
avoiding an extra client RPC call
fixes #8398

engine: optimize parseRefString by checking for local paths first

---

engine/telemetry/labels.go

For reference:
- https://buildkite.com/docs/pipelines/environment-variables#BUILDKITE
- https://www.jetbrains.com/help/teamcity/predefined-build-parameters.html#-6f93ib_20

ci: detect Buildkite and TeamCity

---

docs/package.json
docs/yarn.lock

This commit updates the mermaidjs package to fix a broken dependency, see https://github.com/facebook/docusaurus/issues/10526

docs: Fix mermaid diagram rendering

---

.dagger/sdk_typescript.go

sdk/typescript: check that dist folder exists before publishing

---

.dagger/engine.go

Fixes https://github.com/dagger/dagger/issues/8644.

ci: use trivy public ecr mirror

---

sdk/go/telemetry/init.go

fixes #8620
when logged in, setting both 
```
export OTEL_EXPORTER_OTLP_ENDPOINT=""
export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=""
```
results in the cli still trying to emit traces, logging:
```
15:57:23 ERR failed to emit telemetry error="traces export: Post \"http:///v1/traces\": http: no Host in request URL"
```
this PR removes the `if set OTEL_*: configure traces` logic, so disabling logs doesn't incidentally enable traces. now both logging and traces and be configured somewhat independently. 
tested manually via:
```
OTEL_EXPORTER_OTLP_ENDPOINT="" OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="" go run ~/src/dagger/cmd/dagger call check
```
did my best to also verify that actually setting these variables still works, and that leaving them unset correctly defaults to dagger cloud when logged in.

rework otel config parsing so logs and traces can be simultaneously disabled

---

core/integration/container_test.go
core/schema/container.go

potentially fixes #8752 
Please do not merge yet. Needs discussion/review from @jedevc @shykes

fix(engine): ensure secret variable is expanded in WithExec

---

docs/current_docs/api/module-dependencies.mdx

docs: Add dagger install constraint

---

cmd/dagger/shell.go

change(shell): remove support for executing commands on the host

---

.changes/unreleased/Changed-20241028-220622.yaml
cmd/dagger/module.go
core/integration/module_call_test.go

Fixes https://github.com/dagger/dagger/issues/8516

change(cli): limit printing module objects to fields

---

docs/current_docs/api/clients-sdk.mdx
docs/current_docs/api/custom-functions.mdx
docs/current_docs/api/module-structure.mdx
docs/current_docs/integrations/google-cloud-run.mdx
docs/current_docs/integrations/java.mdx
docs/current_docs/integrations/php.mdx
docs/current_docs/partials/_dagger_module_init.mdx
docs/current_docs/quickstart/daggerize.mdx
docs/current_docs/quickstart/simplify.mdx

Docs follow up from:
- https://github.com/dagger/dagger/pull/8709

docs(python): update new project structure

---

cmd/dagger/shell.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/8892

fix(shell): passthrough id to argument

---

.github/main.go
.github/workflows/daggerverse-preview.gen.yml

Follow-up to:
- https://github.com/dagger/dagger/pull/8684
---
Tested in this private repo: https://github.com/dagger/dagger-alt-runners/actions/runs/11746915623

ci: Fix module reference for daggerverse-preview workflow

---

testctx/testctx.go

Saw the race detector go off in [a test run](https://dagger.cloud/dagger/traces/b536e8f790c81fd17ff163926a0e0006?span=f8747f05b83c6abb&logs). Looks like we were just appending to a slice concurrently without any locks.

tests: fix race condition in testctx error setting

---

sdk/go/internal/engineconn/session.go

I saw the race detector go off in a test run where it appeared to be saying that the Go SDK CLI session code was still finishing an io.Copy to the LogOutput for the test *after* the test was done.
That io.Copy was running in an unsynchronized goroutine, so this seems entirely plausible in the case where it is still reading some buffered data from the stderr pipe after the child process exited.
This updates the SDK client's Close method to wait for that io.Copy to finish before returning, which should ensure there's no stray writes after Close ends.
I couldn't repro this test race locally after many attempts, so this is still a bit of an educated guess. Won't know for sure it's gone until we haven't seen it in CI for a bit.
---
Saw the race detector go off …

go: wait for CLI session cmd to finish copying on close

---

.github/workflows/_dagger_on_depot_cli_provisioned.yml
.github/workflows/_dagger_on_depot_pre-provisioned_with_cache.yml

ci: Fix repository filter

---

docs/_README.md

docs: Update README for doc structure

---

docs/current_docs/adopting.mdx
docs/current_docs/integrations/ci.mdx
docs/sidebars.ts

Relates to https://github.com/dagger/dagger/pull/8768#issuecomment-2460353863

docs: Add CI sub-section to navbar

---

docs/current_docs/api/custom-types.mdx
docs/current_docs/api/enumerations.mdx
docs/current_docs/api/snippets/custom-types/typescript/index.ts
docs/current_docs/api/snippets/enums/typescript/index.ts

Follow up for #8824 (must be merged before ; this PR's branch is based on that one)

docs: TS add `type` & `enum` keyword in examples

---

cmd/dagger/shell.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/8992

shell: fix export

---

cmd/dagger/shell.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/9001

fix(shell): fix cobra to shell command conversion

---

core/integration/module_python_test.go
sdk/python/.changes/unreleased/Fixed-20241119-191420.yaml
sdk/python/runtime/discovery.go
sdk/python/runtime/python.go
sdk/python/runtime/python_test.go

Fixes https://github.com/dagger/dagger/issues/8965

python: fix module name with numbers

---

.dagger/sdk_elixir.go
sdk/elixir/dev/elixir_sdk_dev/lib/elixir_sdk_dev.ex

~⚠️ Needs #8963~
Implements `generate` function to generate SDK API. And also refactoring
the sdk dev setup to a new method.

feat(sdk/elixir): implements generate to elixir-sdk-dev

---

cmd/dagger/shell.go

Fixes https://github.com/dagger/dagger/issues/9018

shell: persist variables across interactive prompt lines

---

engine/server/session.go

this adds otel spans for cache export so we can have better visibility
about it. We're also removing the cancellation from the export context
to avoid the exporter to be cancelled by the client timeout.

engine: add otel spans for cache export

---

.dagger/build/builder.go
.dagger/build/sdk.go
.dagger/consts/versions.go

Fixes https://github.com/dagger/dagger/issues/9010.
@sipsma is there anything we can do to sanity test? It feels a bit fragile, not sure quite how to test this :thinking:

ci: cross-compile pre-built std lib

---

.changes/.next
.dagger/engine.go
.github/main.go
.github/workflows/daggerverse-preview.gen.yml
core/integration/container_test.go
core/integration/future_test.go
sdk/go/dagger.gen.go

Next release is going to be v0.15.0, with some exciting changes.

chore: bump next version to v0.15.0

---

engine/cache/manager.go

this avoids pushing layers which are not necessary to magicache as
they'll always be retrieved from the local dagger content store

engine: don't push local store layers to  magicache

---

docs/current_docs/api/module-dependencies.mdx

Based on https://github.com/dagger/dagger/pull/8745

docs: Update deps page for dagger uninstall command

---

cmd/codegen/generator/typescript/templates/src/method.ts.gtpl
cmd/codegen/generator/typescript/templates/src/testdata/object_test_want.ts
cmd/codegen/generator/typescript/templates/src/testdata/objects_test_want.ts

fix: typescript SDK codegen unit test

---

cmd/dagger/shell.go
core/integration/module_shell_test.go

Includes convenience for single required argument being a list of strings.
Closes https://github.com/dagger/dagger/issues/8969

shell: allow positional args to be interspersed with options

---

.github/workflows/trace-workflows.yml

Previous approach did not work. Workflow name needs to be exact.
Follow-up to:
- https://github.com/dagger/dagger/pull/9232

ci: Fix trace workflow pattern

---

cmd/dagger/shell.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/9201

shell: fix regression in slice flags

---

core/integration/module_typescript_test.go
sdk/typescript/.changes/unreleased/Fixed-20250106-154041.yaml
sdk/typescript/src/module/entrypoint/load.ts
sdk/typescript/src/module/introspector/dagger_module/object.ts
sdk/typescript/src/module/introspector/dagger_module/typeObject.ts

Fixes #9291
Signed-off-by: Tom Chauveau <tom@epitech.eu>

fix(ts-sdk): nested ideable type serialization

---

.changes/unreleased/Fixed-20250106-162442.yaml
dagql/idtui/frontend_pretty.go

fix(cli): fix terminal on windows

---

dagql/idtui/frontend_plain.go

cli: print CACHED operations for plain output

---

core/terminal.go

Fixes https://github.com/dagger/dagger/issues/8591
This ensures that we avoid immediately flashing the terminal message, and not showing any progress messages while we're building the service container on demand.
Ideally, the TUI would handle this by default - but currently showing the terminal just entirely suspends all progress output. This needs fixing *at some point*, but it's worth fixing with this hack now (it doesn't have any extra cost to do this).

fix: ensure container is cached before starting terminal service

---

.github/workflows/_dagger_on_magicache.yml
.github/workflows/alternative-ci-runners-3.yml
.github/workflows/trace-workflows.yml

- **ci: add magicache benchmark**
- **trigger workflow**
- **ci: add scheduled workflow run for magicache benchmark**

Alternative CI Runners 3 - Magicache benchmark

---

docs/current_docs/api/module-structure.mdx

Also related to https://github.com/dagger/dagger/issues/8711

docs: Add layout options for modules in monorepos

---

docs/current_docs/api/daggerverse.mdx

Follow up to https://github.com/dagger/dagger/pull/9310#issuecomment-2574593854

docs: Add note for Python module examples

---

docs/current_docs/api/arguments.mdx
docs/current_docs/api/snippets/functions/arguments-array/go/.gitignore
docs/current_docs/api/snippets/functions/arguments-array/go/dagger.json
docs/current_docs/api/snippets/functions/arguments-array/go/main.go
docs/current_docs/api/snippets/functions/arguments-array/python/main.py
docs/current_docs/api/snippets/functions/arguments-array/typescript/index.ts

Adds a section on the documentation about supporting arrays as arguments.

Document array arguments

---

cmd/dagger/module_inspect.go
cmd/dagger/shell.go
cmd/dagger/shell_commands.go
cmd/dagger/shell_completion.go
cmd/dagger/shell_debug.go
cmd/dagger/shell_exec.go
cmd/dagger/shell_state.go

This fixes several concurrency issues. Commits are granular.

shell: fix concurrency issues

---

cmd/codegen/generator/go/generator.go

Fixes #9361 (cc @sagikazarmark)

fix: avoid panic when no go directive provided

---

docs/current_docs/install.mdx
docs/current_docs/partials/_install-cli.mdx

docs: Add installation command for dev version

---

sdk/elixir/.changes/unreleased/Added-20250118-000042.yaml
sdk/elixir/lib/dagger/mod.ex
sdk/elixir/lib/dagger/mod/function.ex
sdk/elixir/lib/dagger/mod/object.ex
sdk/elixir/test/dagger/mod/object_test.exs
sdk/elixir/test/dagger/mod_test.exs
sdk/elixir/test/support/object_mod.ex

feat(sdk/elixir): support float type

---

dagql/dagui/spans.go

Quick PR to fix a panic affecting Cloud v3 - just making sure the commit is in the Git network so I can point to it via submodule.

prevent panic when RootSpan not collected yet

---

core/integration/module_config_test.go

Follow up for https://github.com/dagger/dagger/pull/9204#discussion_r1918811370 
My previous change had caused these to diverge, updated them now to be consistent for easier maintainability.

update integ test repos w/ fixed consistent commits

---

cmd/dagger/shell.go

This fixes a shell regression in v0.15.3, but only in interactive mode.
I don't fully understand why but `Frontend.Background` can swallow output if you don't add a newline (`fmt.Fprint` vs `fmt.Fprintln`).
Current solution isn't perfect. You may see extra newlines than intended. For example:
```
⋈ _echo hello
hello
⋈ _echo -n hello
hello
⋈
```
That happens because the `_echo` builtin, for example, sends two separate writes with `_echo hello`:
```
"hello"
"\n"
```
So on the first `"hello" we're adding a `\n`, and then the second one comes but it's still printed.
I tried another approach but didn't work out and ran out of time. Still need to find something better, maybe on bubbletea's side.

shell: fix repl output

---

docs/current_docs/configuration/engine.mdx

https://discord.com/channels/707636530424053791/1120503349599543376/1337912380176339046

docs: fix JSON booleans for insecureRootCaps

---

sdk/java/dagger-java-annotation-processor/src/main/java/io/dagger/annotation/processor/DaggerModuleAnnotationProcessor.java
sdk/java/runtime/template/src/main/java/io/dagger/modules/daggermodule/DaggerModule.java

Ensure the java object is extending the right base class and check the default constructor exists.

sdk/java: check object definition

---

docs/current_docs/api/documentation.mdx
docs/current_docs/api/snippets/documentation/php/main/composer.json
docs/current_docs/api/snippets/documentation/php/main/dagger.json
docs/current_docs/api/snippets/documentation/php/main/entrypoint.php
docs/current_docs/api/snippets/documentation/php/main/src/MyModule.php
docs/current_docs/api/snippets/documentation/php/object/composer.json
docs/current_docs/api/snippets/documentation/php/object/dagger.json
docs/current_docs/api/snippets/documentation/php/object/entrypoint.php
docs/current_docs/api/snippets/documentation/php/object/src/MyModule.php
docs/current_docs/api/snippets/documentation/python/object.py
docs/current_docs/api/snippets/documentation/typescript/object.ts

Also fix a few inconsistencies in documentation examples.

Docs: Add PHP Snippets to api/documentation

---

.github/workflows/publish.yml

I could not for the life of me figure out how to trigger publish jobs on the PR in https://github.com/dagger/dagger/pull/9650 so I went ahead and just pushed to see what happened, didn't work.
Have fixes here, but will bang my head until I can convince gh to run the job here so we don't have to repeat this loop more

Fix provision tests

---

docs/current_docs/configuration/custom-runner.mdx

All other links on this page involving an article had the article listed as normal text, so opted to follow suit.

Remove duplicate article in custom-runner.mdx

---

engine/client/drivers/docker.go

The first follow-up (I expect of several) to #9555.
This is useful, so that the named engine is always selected as a leftover (which means we'll reuse it).
Without this, dev builds were *working* but could give some very odd errors in the case of a failure.

chore: always collect the named engine

---

.dagger/build/sdk.go
.dagger/go.mod
dagger.json
sdk/typescript/runtime/go.mod
sdk/typescript/runtime/main.go
sdk/typescript/runtime/tsdistconsts/consts.go

^ in the title, this reapplies #9526.

reapply tsx bundling w/ fix for x-architecture builds

---

docs/docusaurus.config.ts

Just down to `Daggerverse | Docs`
Request from @mircubed

docs: minimal header

---

engine/distconsts/consts.go
go.mod
modules/go/main.go

chore: update go to 1.24.1

---

core/llm.go
core/llm_openai.go

Tested and it works!
Implemented according to https://github.com/openai/openai-go/tree/main?tab=readme-ov-file#microsoft-azure-openai

add support for Azure OpenAI client

---

.dagger/bench.go
.github/workflows/benchmark-engine.yml
dagger.json
engine/client/secretprovider/op.go

not yet mergeable, but need a little help configuring the discord webhook. I think I don't have enough powers on our discord server to generate a webhook, and I'd also kinda like to make a channel so these failures can't pollute #engine-dev

notify discord on benchmark failure

---

docs/current_docs/agents.mdx

Documents how to use Azure OpenAI Service with the experimental LLM feature
This is enabled here: https://github.com/dagger/dagger/pull/9808

Documentation for using LLM with Azure OpenAI Service

---

sdk/java/dagger-java-sdk/src/main/java/io/dagger/client/DaggerQueryException.java

chore: update DaggerQueryException.java

---

docs/current_docs/faq.mdx

Add community SDK maintainer requirements and add Java to list of SDKs. 
https://linear.app/dagger/issue/ECO-526/list-of-requirements-for-community-sdks

add Community SDK maintainer requirements

---

helm/dagger/.changes/unreleased/Added-20250306-103035.yaml
helm/dagger/templates/engine-daemonset.yaml
helm/dagger/templates/engine-statefulset.yaml
helm/dagger/values.yaml

This PR enables setting additional environment variables for the engine container.

helm: Enable setting environment variables for engine

---

sdk/java/dagger-java-annotation-processor/src/main/java/io/dagger/annotation/processor/DaggerModuleAnnotationProcessor.java
sdk/java/dagger-java-annotation-processor/src/test/java/io/dagger/annotation/processor/TypeDefTest.java
sdk/java/dagger-java-annotation-processor/src/test/resources/io/dagger/gen/entrypoint/entrypoint.java
sdk/java/dagger-java-annotation-processor/src/test/resources/io/dagger/java/module/DaggerJava.java

Fix when a function is returning void (so nothing):
- declare as a typedef of kind Void, optional
- do not get a value and return null

fix(sdk/java) function returning void

---

core/llm_google.go
core/llm_test.go

looks like with the streaming change the text content got dropped from being appended to the content string

llm: fix gemini text response

---

cmd/dagger/cloud.go

cli: print message at the very end of the orgs list on login

---

docs/current_docs/agents.mdx

Adds a small FAQ to get us something we can iterate on and work towards a 'getting started' / tutorial

docs: small faq for agents

---

docs/current_docs/ci/adopting.mdx
docs/current_docs/faq.mdx

docs: Add Java SDK to adopting and FAQ pages

---

docs/current_docs/configuration/cloud.mdx

Add info about Google Auth since we support it now.

docs: clarify cloud auth requirements

---

docs/current_docs/agents.mdx

Update the llm version to 10, there are issues with llm sync in version 9.

docs: update the llm version to 10

---

cmd/dagger/shell.go
core/integration/module_shell_test.go
docs/current_docs/reference/cli.mdx

Closes https://github.com/dagger/dagger/issues/9854

shell: rename `-n` to `-M`

---

docs/current_docs/api/constructors.mdx
docs/current_docs/api/documentation.mdx
docs/current_docs/api/error-handling.mdx
docs/current_docs/api/fs-filters.mdx
docs/current_docs/api/module-dependencies.mdx
docs/current_docs/api/packages.mdx
docs/current_docs/api/snippets/constructors/java/default-object/MyModule.java
docs/current_docs/api/snippets/constructors/java/simple/MyModule.java
docs/current_docs/api/snippets/dependencies/chaining/java/MyModule.java
docs/current_docs/api/snippets/documentation/java/main/MyModule.java
docs/current_docs/api/snippets/documentation/java/object/MyModule.java
docs/current_docs/api/snippets/error-handling/java/MyModule.java
docs/current_docs/api/snippets/fs-filters/post-call/java/MyModule.java
docs/current_docs/api/snippets/fs-filters/pre-call/java/MyModule.java

Add more docs regarding Java SDK

docs(sdk/java)

---

cmd/codegen/generator/go/templates/lint_name.go
cmd/dagger/llm.go
core/integration/llmtest/go-programmer/main.go
core/llm_test.go
docs/current_docs/agents.mdx
sdk/go/dag/dag.gen.go
sdk/go/dagger.gen.go

This is gonna break a bunch of stuff, but better now than later...

sdk(go): Llm -> LLM

---

docs/current_docs/api/fs-filters.mdx
docs/current_docs/api/snippets/fs-filters/post-call/php/composer.json
docs/current_docs/api/snippets/fs-filters/post-call/php/dagger.json
docs/current_docs/api/snippets/fs-filters/post-call/php/entrypoint.php
docs/current_docs/api/snippets/fs-filters/post-call/php/src/MyModule.php
docs/current_docs/api/snippets/fs-filters/pre-call/php/composer.json
docs/current_docs/api/snippets/fs-filters/pre-call/php/dagger.json
docs/current_docs/api/snippets/fs-filters/pre-call/php/entrypoint.php
docs/current_docs/api/snippets/fs-filters/pre-call/php/src/MyModule.php

docs: Add PHP snippets to api/filters

---

.github/main.go
.github/workflows/engine-cli.gen.yml

these are under development atm, and especially with https://github.com/dagger/dagger/pull/9915 we should be careful not to overload test-everything-else

seperate LLM tests into their own job

---

core/integration/container_test.go
core/integration/platform_test.go
core/integration/suite_test.go

[This test has started to flake out more often recently again](https://github.com/dagger/dagger/issues/8349). Based on test output it looks like the attempt to prevent the cache mount from being pruned wasn't even actually running by the time the test containers were running (which is possible because it works by running a separate long running container in a different goroutine, so the goroutine isn't guaranteed to be running at any particular time).
This attempts to deflake by having the long-running container work as a service depedency, which guarantees it is running and preventing cache mount pruning while the actual test containers are running.

attempt to deflake TestPlatform/TestCacheMounts

---

core/llm_env.go

Only one quick fix for now, will push any more to this PR.

LLM follow-ups for release

---

core/directory.go
core/integration/module_test.go
core/modfunc.go

Fixes #9490
Signed-off-by: Tom Chauveau <tom@epitech.eu>

feat: add directory pre call filtering

---

.dagger/go.mod
.github/actions/call-ci-alt-runner/action.yml
.github/actions/call/action.yml
.github/dagger.json
.github/main.go
.github/workflows/_dagger_on_x1_nvme.yml
.github/workflows/_dagger_on_x1_tmpfs.yml
.github/workflows/benchmark-engine.yml
.github/workflows/daggerverse-preview.gen.yml
.github/workflows/docs.gen.yml
.github/workflows/engine-cli.gen.yml
.github/workflows/github.gen.yml
.github/workflows/helm.gen.yml
.github/workflows/publish.yml
.github/workflows/sdks.gen.yml
RELEASING.md
dagger.json
go.mod
version/dagger.json
version/git.go

Better late than never, woops!
:warning: Depends on:
- https://github.com/dagger/dagger-for-github/pull/178

Improve releasing during v0.17.2

---

modules/golangci/lint.go

Eliminate FIXME in the `golangci` by using `$HOME` together with `expand` option.

refactor(modules/golangci): use $HOME instead of path.Join

---

docs/current_docs/features/llm.mdx

Adds the LLM trace for the LLM features page.

docs: add llm cloud trace

---

docs/current_docs/quickstart/agent/snippets/typescript/src/index.ts

https://github.com/dagger/dagger/pull/10031 broke CI on eslint, this should fix it.

docs: fix eslint error preventing CI to be green

---

docs/current_docs/quickstart/agent/index.mdx

fix agent quickstart file paths

---

install.ps1

fix ps1 installing latest dagger

---

cmd/dagger/mcp.go

This makes `dagger mcp` work again with the new env API

mcp: update to new env api

---

.changes/unreleased/Fixed-20250407-170256.yaml
engine/session/git.go
engine/session/git_test.go

fix error when parsing multi-line git config files

---

docs/current_docs/cookbook/cookbook.mdx
docs/current_docs/cookbook/snippets/clone-git-repository-ssh/go/main.go
docs/current_docs/cookbook/snippets/clone-git-repository/go/main.go
docs/current_docs/cookbook/snippets/clone-git-repository/php/src/MyModule.php
docs/current_docs/cookbook/snippets/clone-git-repository/python/main.py
docs/current_docs/cookbook/snippets/clone-git-repository/typescript/index.ts

docs: Make Git cloning recipes consistent in cookbook

---

.goreleaser.yml
docs/current_docs/partials/_install-cli.mdx

- add winget to goreleaser
- add winget install
- improve powershell command
- fix invalid 'development' install example

feat: Winget & Windows install docs

---

cmd/dagger/shell_commands.go
engine/buildkit/client.go
install.sh

chore: remove duplicate words

---

core/mcp.go

This is a leftover from #10003

mcp: mask currentFunctionCall

---

.goreleaser.yml

Hopefully this is the last piece of the puzzle

fix: winget add manifest path override

---

.dagger/util/prerelease.go
cmd/dagger/main.go
cmd/dagger/module_inspect.go

fix some function names in comment

chore: fix some function names in comment

---

core/mcpserver.go

Default values for arrays are still handled weirdly but pedantically by only allowing the empty value with the string "[]".

mcp: properly handle almost all types for the default value of a function argument

---

docs/current_docs/quickstart/agent/index.mdx

docs: info to highlight need for model env vars

---

cmd/dagger/llm.go

fixes this scenario:
```
│🤖 0.5s ◆ Input Tokens: 3,059 ◆ Output Tokens: 25
│ $ .withExec(args: ["go", "version"]): Container! 0.0s CACHED
│
│🤖 0.6s ◆ Input Tokens: 3,128 ◆ Output Tokens: 17
│ ✔ .stdout: String! 0.0s
│
│🤖 A Golang container was created and the command go version was run. The output is:
│ ┃
│ ┃ go version go1.24.2 linux/amd64
│ ┃
│ ┃ If you need to run additional commands or inspect this container further, let me know!
│ ┃ 1.0s
! returned error 422: {"data":null,"errors":[{"message":"Cannot query field \"id\" on type \"String\".","locations":[{"line":1,"column":1269}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}
Full trace at https://dagger.cloud/dagger/traces/ee2432a13a9bd0dd92c78dc1bb589d89
```

shell: fix assigning string result

---

core/integration/module_elixir_test.go
core/integration/testdata/modules/elixir/self-object/.formatter.exs
core/integration/testdata/modules/elixir/self-object/.gitattributes
core/integration/testdata/modules/elixir/self-object/.gitignore
core/integration/testdata/modules/elixir/self-object/dagger.json
core/integration/testdata/modules/elixir/self-object/lib/self_object.ex
core/integration/testdata/modules/elixir/self-object/mix.exs
core/integration/testdata/modules/elixir/self-object/mix.lock

This PR adds an integration test for the struct fields (https://github.com/dagger/dagger/pull/9539).

test(sdk/elixir): add return self integration test

---

dagql/dagui/db.go

This is another avenue to seeing a broken empty trace: a span just has to link to a span that doesn't exist in this trace - possibly in another trace, with engine wide caching.
Confirmed the fix here:
* https://v3-encapsulate-v3.preview.dagger.cloud/dagger/traces/256259ca0d809a4f4af4ba122b97e9ae
* vs. https://v3.dagger.cloud/dagger/traces/256259ca0d809a4f4af4ba122b97e9ae
* (If this is working it means I already merged the frontend side, which points to this PR.)

dagui: avoid sending stub snapshots

---

docs/current_docs/api/interfaces.mdx
docs/current_docs/api/snippets/interfaces/declarations/python/main.py
docs/current_docs/api/snippets/interfaces/implementations/python/main.py
docs/current_docs/api/snippets/interfaces/usages/python/main.py

Depends on:
- https://github.com/dagger/dagger/pull/8097

docs: add Python interfaces

---

.dagger/sdk_rust.go
sdk/rust/Cargo.toml
sdk/rust/crates/dagger-sdk/examples/publish-the-application/main.rs

sdk: bump rust Cargo.toml when releasing new versions

---

core/integration/cross_session_test.go
core/postcall.go

v0.18.4 has a bug w/ secrets where:
1. Session A calls a function that dynamically creates a secret at runtime w/ `setSecret` and provides that to a git repo via `withAuthToken`
2. Session A is still running, meanwhile Session B calls a different function (or same function w/ different args) that makes the same call to the same git repo w/ an auth token
3. The functions return a container that has the git repo mounted (or otherwise returns some value that has the git repo in the DAG)
4. Session B gets a cache hit on the git repo tree because it's content hashed, but the returned cache hit value includes the auth token from Session A
5. Session B tries to transfer the secret to the caller, but its function doesn't actually know about it and errors out with `secret plaintext not found` …

add integration test for cross-session content-hash cache hit w/ secrets

---

core/integration/llmtest/allow-llm.golden
core/integration/llmtest/api-limit.golden
core/integration/llmtest/hello-world.golden
core/mcp.go

This is a bit of a grab-bag now fixing various issues @kpenfound ran into for https://github.com/kpenfound/hello-dagger/pull/2

llm: fix handling of optional ID args

---

docs/docusaurus.config.ts
docs/src/components/VideoPlayer.tsx

This commit updates the app URL for Posthog events and adds debug logging to the component.

docs: Update PostHog config

---

core/git.go

This was introduced accidentally in https://github.com/dagger/dagger/pull/10286. See a failure [here](https://v3.dagger.cloud/dagger/traces/c182470d705fb2b31605f0ff98a725d9?listen=36730ef52ad51bb3&listen=61afda7889796fe6&listen=4c36044466e847f5&listen=bd38492670464eeb&listen=33f73fed1f96162f&span=343fca9c46b84919#4c36044466e847f5:L19):
```
Error Trace:    /app/core/integration/suite_test.go:335
/app/core/integration/cross_session_test.go:487
/app/core/integration/cross_session_test.go:523
/go/pkg/mod/github.com/dagger/testctx@v0.0.4/testctx.go:295
/go/pkg/mod/github.com/dagger/testctx/oteltest@v0.0.3/log.go:37
/go/pkg/mod/github.com/dagger/testctx/oteltest@v0.0.3/trace.go:83
/go/pkg/mod/github.com/dagger/testctx@v0.0.4/middleware.go:25 …
```

fix: ensure git does not skip remote repo access

---

helm/dagger.json

bumping k3s module to fix helm check CI workflow

ci: fixes helm check

---

core/integration/cross_session_test.go

This test started flaking in [this PR](https://github.com/dagger/dagger/pull/10327). Didn't repro but looking at it seems like it could be explained by the cache getting pruned while the test is running (which would cause the assertions of cache re-use to fail).
The update uses nested execs to run commands, which ensures that the session stays open for the duration of the test case assertions and thus should prevent the cache from getting pruned until the test is done.

make `TestCrossSessionSecretURICaching` resilient to cache prunes

---

docs/current_docs/api/arguments.mdx
docs/current_docs/api/secrets.mdx
docs/current_docs/cookbook/cookbook.mdx

Follow-up for https://github.com/dagger/dagger/pull/10311 to explain how secrets impact cache (now, as of v0.18.6) and how the cache behavior can be customized.
Let me know if it's comprehensible as is or if it would benefit from more examples/explanation.

add docs for secret caching behavior

---

core/integration/cross_session_test.go
core/integration/module_config_test.go
core/integration/module_test.go
core/integration/proxy_test.go
core/schema/git.go

Fixes https://github.com/dagger/dagger/issues/10339.

fix: use `DefaultTransport` for git requests to preserve proxy settings

---

cmd/dagger/.dagger/main.go

Goreleaser needs these files :)
Follow-up from #10296 - this should work now, I've dry-runned locally.

ci: fix missing files from publish

---

core/integration/provision_test.go

We can just disable the version check here - we're just doing a `dagger query` here, it's super super unlikely we break this fully (and even when we do, we can get a way better error message).

tests: fix broken provision tests

---

core/llm_anthropic.go
go.mod
go.sum

Follow-up from https://github.com/dagger/dagger/pull/10354#issuecomment-2872184816.

chore: bump anthropic-sdk-go to v0.2.0-beta.3

---

cmd/dagger/shell.go
cmd/dagger/shell_exec.go
engine/buildkit/containerfs/fs.go

Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: replace HasPrefix+TrimPrefix with CutPrefix

---

docs/current_docs/partials/_install-cli.mdx

docs: lead with winget install for windows

---

dagql/idtui/frontend_pretty.go

fixes #10152
[![asciicast](https://asciinema.org/a/XShnrUQOLXKiAhpW1Ku3Uxx0O.svg)](https://asciinema.org/a/XShnrUQOLXKiAhpW1Ku3Uxx0O)

shell: auto-switch between shell/nav mode

---

dagql/idtui/frontend_pretty.go

shell: don't exit from q/Ctrl+C in nav mode

---

sdk/python/.changes/unreleased/Fixed-20250521-235558.yaml
sdk/python/codegen/src/codegen/generator.py
sdk/python/dev/src/python_sdk_dev/main.py
sdk/python/src/dagger/client/gen.py
sdk/python/tests/client/test_integration.py
sdk/python/tests/codegen/test_generator.py

Fixes https://github.com/dagger/dagger/issues/10447

python: fix incorrect client bindings for Service start and stop

---

sdk/elixir/lib/dagger/mod/object.ex

This changeset attempts to fix the flaky test issue by moving `Nestru.Decoder` that set hint at compile-time to runtime.
Fixes #10360

fix(sdk/elixir): move Nestru.Decoder to explicit implementation

---

core/schema/container.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

Self-explanatory, the wording was slightly off.

docs: Fix wording in "withServiceBinding"

---

core/integration/module_elixir_test.go
core/integration/testdata/modules/elixir/defaults/lib/defaults.ex
sdk/elixir/.changes/unreleased/Added-20250531-232117.yaml
sdk/elixir/lib/dagger/mod/object.ex
sdk/elixir/lib/dagger/mod/object/defn.ex
sdk/elixir/lib/dagger/mod/object/function_def.ex
sdk/elixir/lib/dagger/mod/object/meta.ex
sdk/elixir/test/dagger/mod/object_test.exs

This adds support for default value argument as mentionned in #9744 
Also achieved the TODO left in `TestOptionalValue` integration test by @wingyplus ( c.f #9742 )

feat(sdk/elixir): Support default value argument 

---

core/integration/secretprovider_test.go

Something broke recently on `main` (I guess from a new package change in alpine). The tests just need updating with some broader permissions. Not *entirely* sure what changed, but also, I do not really want to spend the time debugging this very obscure little test.
Failure here:
https://github.com/dagger/dagger/actions/runs/15392465818/job/43304862516
https://dagger.cloud/dagger/traces/f04c67d229c80214bf1850b486e4c77e
```
22  : [17.4s] | + sh -c 'echo c2VjcmV0eTE2Zm43Mm1rY3Z1Z24zMWF6eWxhaG8ybw== | base64 -d | secret-tool store --label=mysecret abc xyz'
22  : [17.4s] | dbus-daemon[17]: [session uid=0 pid=17 pidfd=5] Activating service name='org.freedesktop.secrets' requested by ':1.0' (uid=0 pid=27 comm="secret-tool store --label=mysecret abc xyz" label="kernel")
22  : [17.4s] | …
```

tests: fix gnome-keyring test

---

core/sdk.go

Don't really know why this came from here. My bad!

chore: remove accidentally committed Init interface

---

core/integration/module_elixir_test.go
core/integration/testdata/modules/elixir/objects/.formatter.exs
core/integration/testdata/modules/elixir/objects/.gitattributes
core/integration/testdata/modules/elixir/objects/.gitignore
core/integration/testdata/modules/elixir/objects/dagger.json
core/integration/testdata/modules/elixir/objects/lib/objects.ex
core/integration/testdata/modules/elixir/objects/lib/objects/a.ex
core/integration/testdata/modules/elixir/objects/lib/objects/b.ex
core/integration/testdata/modules/elixir/objects/mix.exs
core/integration/testdata/modules/elixir/objects/mix.lock
sdk/elixir/lib/dagger/mod.ex
sdk/elixir/lib/dagger/mod/module.ex
sdk/elixir/lib/dagger/mod/object.ex
sdk/elixir/lib/dagger/mod/registry.ex
sdk/elixir/lib/dagger/mod/scope.ex
sdk/elixir/test/dagger/mod/registry_test.exs
sdk/elixir/test/support/object_mod.ex

In this changeset, it allows the module to add more objects and returning from a function to chain the object.

feat: support object chaining

---

docs/.dagger/main.go
docs/static/api/reference/index.html

Fixes the currently failing docs job on `main`. And also, just good to keep this up-to-date.

ci: bump spectaql

---

modules/golangci/lint.go

Two tweaks:
* Mount a cache volume to `/root/.cache/golangci-lint` - lints are incredibly slow + expensive so this should help.
* Log the lint errors instead of putting them all in the error message. Errors are meant to be one-liners with somewhat low cardinality; they're not meant to contain arbitrarily long text.

modules/golangci: enable caching, fix giant errors

---

cmd/codegen/generator/go/templates/module_funcs.go
cmd/codegen/generator/go/templates/module_objects.go
cmd/codegen/generator/go/templates/modules.go
cmd/codegen/generator/go/templates/modules_test.go
core/integration/module_test.go
docs/current_docs/api/fs-filters.mdx
sdk/go/.changes/unreleased/Added-20250616-172942.yaml

Fix for https://github.com/dagger/dagger/issues/8383.

feat(go): allow multiline pragmas

---

modules/alpine/main.go

For some reason Wolfi has been occasionally publishing APKINDEX files where the latest version of ld-linux specifies a hard dependency on an exact version of glibc which is not present in the APKINDEX yet. It goes away within an hour usually, but it's frustrating in the meantime to not be able to build the engine obviously.
For now, attempting to resolve this by just specifying glibc, ld-linux and libcrypt1 versions that are pinned to the current epoch. I repro'd the problem by manually constructing an APKINDEX with the missing glibc version (got the exact same error we see) and verified this approach fixed it. We will see if it works in the real world too.

pin wolfi glibc and related packages to workaround broke APKINDEXes

---

.changes/unreleased/Fixed-20250702-185241.yaml
core/container.go
core/integration/container_test.go
engine/buildkit/client.go

Encountered one of these in the wild, and realized our secret translation could not handle an optional secret!

fix: allow building dockerfiles with optional secrets

---

sdk/go/dagger.gen.go

A few PRs got merged that changed the Go SDK and the end merged result on main was out of sync, just needs a regen

Regen go sdk

---

.changes/unreleased/Fixed-20250809-124915.yaml
cmd/dagger/shell_exec.go
cmd/dagger/shell_state.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/10696

shell: fix state mutability issue when chaining functions

---

docs/current_docs/api/cache-volumes.mdx
docs/current_docs/api/secrets.mdx

docs: Add note about secret/cache volume scoping

---

releaser/main.go

Oops. My bad.
I introduced this in #10731.

chore: fix linting of releaser module

---

docs/current_docs/reference/glossary.mdx
docs/current_docs/reference/index.mdx
docs/sidebars.ts

Improve reference page index and sidebar

---

docs/docusaurus.config.ts
docs/src/css/custom.scss

This adds a new banner to let users know they can visit the old docs, it also has some small styling/spacing tweaks.

docs: add banner for new docs, small style tweaks

---

modules/go/main.go

PR #10999 seems to have left an unnecessary comment, just nit but it's a 1 min change on my end
cc @TomChv

chore: remove unnecessary comment

---

.changes/unreleased/Breaking-20250912-171018.yaml
core/integration/git_test.go
core/integration/legacy_test.go
core/integration/suite_test.go
core/schema/git.go

Fixes https://github.com/dagger/dagger/issues/10961.

fix: make git ref accessors stricter

---

core/git.go
core/integration/git_test.go

:cry: sigh.
We were never testing this behavior, but as of https://github.com/dagger/dagger/pull/11030, I wanted to start relying on it.
We technically had subtly different behavior for checking out refs and checking out SHAs directly; the former included tags in the history, the latter didn't.
> [!WARNING]
>
> Technically this is mergeable, but bleh, *using the tags like this is vulernable to wild consistency issues*. Need to think through the edge cases, probably using https://github.com/dagger/dagger/pull/11032 as a helper.
> - `doFetch` needs to get reset if a tag is updated remotely
> - If a `ls-remote` is captured, a tag is added, and then it's added/removed as part of the tag history for when we fetch it... we should be able to respect that? Or detect that? Don't really know.
>   - …

feat: ensure commit checkouts have tag history

---

.changes/unreleased/Breaking-20250912-171018.yaml
core/integration/client_generator_test.go
core/integration/git_test.go
core/integration/legacy_test.go
core/integration/suite_test.go
core/modulerefs.go
core/schema/git.go

Fixes https://github.com/dagger/dagger/issues/10961.
Revive https://github.com/dagger/dagger/pull/11038.

fix: make git refs strict

---

.changes/unreleased/Breaking-20250923-171403.yaml
core/integration/dockerfile_test.go
core/integration/legacy_test.go
core/schema/container.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
docs/static/reference/php/Dagger/Container.html
docs/static/reference/php/doc-index.html
docs/static/reference/php/doctum-search.json
sdk/dotnet/sdk/Dagger.SDK.Tests/ClientTest.cs
sdk/elixir/lib/dagger/gen/container.ex
sdk/elixir/test/dagger/client_test.exs
sdk/go/dagger.gen.go
sdk/go/examples_test.go
sdk/java/dagger-java-samples/src/main/java/io/dagger/sample/BuildFromDockerfile.java
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/examples/existing-dockerfile/main.rs
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts
sdk/typescript/src/api/test/api.spec.ts

See https://github.com/dagger/dagger/issues/10812 - missed this in https://github.com/dagger/dagger/pull/11115.

chore: remove `Container.build` API

---

core/llm.go
go.mod
go.sum

*sigh*
In #11145 I bumped the version that we test, but not the actual default version that we ship. :upside_down_face:

llm: bump Anthropic default

---

.changes/unreleased/Added-20251007-110337.yaml

Signed-off-by: Solomon Hykes <solomon@dagger.io>

Release note for user defaults
