dagger/dagger

- docs/current/guides/110632-embed-directories.md
- docs/current/guides/183109-aws-codebuild-codepipeline.md
- docs/current/guides/573829-aws-lambda.md
- docs/current/guides/620301-azure-pipelines-container-instances.md
- docs/current/guides/710884-private-repositories.md
- docs/current/guides/882813-build-test-publish-java-spring.md
- docs/current/guides/snippets/aws-codebuild-codepipeline/buildspec-go.yml
- docs/current/guides/snippets/aws-codebuild-codepipeline/buildspec-nodejs.yml
- docs/current/guides/snippets/aws-codebuild-codepipeline/buildspec-python.yml
- docs/current/guides/snippets/azure-pipelines-container-instances/azure-pipeline-go.yml
- docs/current/guides/snippets/azure-pipelines-container-instances/azure-pipeline-nodejs.yml
- docs/current/guides/snippets/azure-pipelines-container-instances/azure-pipeline-python.yml
- docs/current/guides/snippets/build-test-publish-java-spring/github-go.yml
- docs/current/guides/snippets/build-test-publish-java-spring/github-nodejs.yml
- docs/current/guides/snippets/build-test-publish-java-spring/github-python.yml
- docs/current/guides/snippets/ci/go/actions.yml
- docs/current/guides/snippets/ci/go/azure-pipelines.yml
- docs/current/guides/snippets/ci/go/buildspec.yml
- docs/current/guides/snippets/ci/nodejs/actions.yml
- docs/current/guides/snippets/ci/nodejs/azure-pipelines.yml
- docs/current/guides/snippets/ci/nodejs/buildspec.yml
- docs/current/guides/snippets/ci/python/actions.yml
- docs/current/guides/snippets/ci/python/azure-pipelines.yml
- docs/current/guides/snippets/ci/python/buildspec.yml
- docs/current/guides/snippets/github-google-cloud/github-go.yml
- docs/current/guides/snippets/github-google-cloud/github-nodejs.yml
- docs/current/guides/snippets/github-google-cloud/github-python.yml
This commit updates various Dagger long-form guides to use "dagger run".
Follow-up to:
https://github.com/dagger/dagger/pull/5591
https://github.com/dagger/dagger/pull/5604
https://github.com/dagger/dagger/pull/5637
> docs: Updates some guides to use "dagger run"

- RELEASING.md
As discussed in #5676, Rust will not be part of the SDK release process and will have its own pipeline. By extension, we shall not mention rust in  `RELEASING.md` steps
> chore: update release guide to remove rust.

- docs/current/quickstart/349011-build.mdx
- docs/current/quickstart/429462-build-dockerfile.mdx
- docs/current/quickstart/472910-build-multi.mdx
- docs/current/quickstart/593914-hello.mdx
- docs/current/quickstart/635927-caching.mdx
- docs/current/quickstart/730264-publish.mdx
- docs/current/quickstart/947391-test.mdx
This commit updates the Dagger quickstart to use "dagger run".
Follow-up to:
https://github.com/dagger/dagger/pull/5591
https://github.com/dagger/dagger/pull/5604
https://github.com/dagger/dagger/pull/5637
https://github.com/dagger/dagger/pull/5701
> docs: Adds "dagger run" to quickstart

- docs/current/cookbook.md
- docs/current/guides/421437-work-with-host-filesystem.md
- docs/current/quickstart/635927-caching.mdx
This commit introduces the term "Dagger pipeline operations cache" and distinguishes it from "Dagger cache volume". It also adds a note regarding invalidation of cache volumes or lack thereof. It is based on the discussion in Discord at https://discord.com/channels/707636530424053791/1143131629540364339/1143591546340520047
> docs: Adds note and information on cache types and invalidations

- core/integration/cache_test.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/engine_test.go
- core/integration/file_test.go
- core/integration/git_test.go
- core/integration/host_test.go
- core/integration/http_test.go
- core/integration/local_test.go
- core/integration/pipeline_test.go
- core/integration/platform_test.go
- core/integration/project_test.go
- core/integration/remotecache_test.go
- core/integration/secret_test.go
- core/integration/services_test.go
- core/integration/suite_test.go
I've been carrying this refactor around between various long-running branches because it's nearly impossible to grok test failure output without it.
Previously all of our tests would just dump their client logs to `os.Stdout` or `os.Stderr`, resulting in all of them interleaving so it's impossible to tell one parallel test's output from another. Now each test's client logs are sent to an `io.Writer` that writes to `t.Log`, so the client logs will show up in each individual test failure's output.
Additionally this refactors all existing tests to 1) use the `connect()` helper and 2) remove the now-redundant `defer c.Close()`.
> tests: use `connect(t)` everywhere, send logs to `t.Log`

- docs/current/sdk/go/959738-get-started.md
- docs/current/sdk/go/snippets/get-started/step5b/main.go
Currently step 5b breaks because the SDK is not compatible with Go 1.18 or 1.19. This updates step 5b to use 1.20 and 1.21
> Update Go getting started guide

- docs/current/sdk/go/959738-get-started.md
This commit updates the Go SDK get started guide with various consistency fixes to match the other get started guides, such as providing a default Go app repository to clone for the guide, clarifying some file paths, and removing the step to create a `main` Go module as this will usually already exist.
> docs: Updates Go SDK get started guide

- docs/current/guides/snippets/ci/go/Jenkinsfile
- docs/current/guides/snippets/ci/go/circle.yml
- docs/current/guides/snippets/ci/nodejs/Jenkinsfile
- docs/current/guides/snippets/ci/nodejs/circle.yml
- docs/current/guides/snippets/ci/python/Jenkinsfile
- docs/current/guides/snippets/ci/python/circle.yml
This commit updates the Jenkins and CircleCI samples in the "Use Dagger with CI" guide to use "dagger run".
Follow-up to:
https://github.com/dagger/dagger/pull/5591
https://github.com/dagger/dagger/pull/5604
https://github.com/dagger/dagger/pull/5637
https://github.com/dagger/dagger/pull/5701
https://github.com/dagger/dagger/pull/5702
> docs: Adds "dagger run" to Jenkins/Circle samples

- website/src/components/molecules/quickstartDoc.js
- website/src/css/custom.scss
This fixes the fragility of the current slug-dependent CSS selectors we are using in the quickstart docs.
As discussed in https://github.com/dagger/dagger/pull/5610, we cannot depend on slugs and docs names for CSS selectors, as it might change in the future and the layout might break.
This solution uses an [undocumented](https://github.com/facebook/docusaurus/issues/4280#issuecomment-1193800323) [Docusarus internal helper](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-common/src/utils/metadataUtils.tsx#L72) to dynamically append a class name to the HTML element and make it easy to flag pages that contain an embedded `<iframe>`.
I also took the liberty to add comments that provide a bit of context.
> fix(docs): quickstart css selectors

- cmd/engine/main.go
- core/pipeline/label.go
- core/pipeline/label_test.go
- engine/client/client.go
- engine/client/docker.go
- engine/server/buildkitcontroller.go
- telemetry/telemetry.go
this is implemented in a backwards compatible way so that old
variables will still work but will be deprecated in a future.
> engine: add DAGGERL_CLOUD_TOKEN env variable support

- cmd/engine/config.go
if `_EXPERIMENTAL_DAGGER_SERVICES_DNS` is disabled, dagger-engine crashes when starting, because the network config is nil
let's ensure that we don't fail if the network config is nil
> fix: panic if services DNS is disabled

- cmd/engine/main_oci_worker.go
it's `num-cpu`, not `num-cpus`...
> fix: engine CLI flags typo

- sdk/rust/LICENSE
Engine & CLI use the same Apache 2.0 license.
If you agree with this change @kjuulh, please:
- edit the commit message & remove this paragraph
- append your `Signed-off-by`
- commit & force push
Otherwise, let's talk!
> sdk(rust): Use same Apache 2.0 license as all other SDKs

- sdk/dotnet/LICENSE
Engine & CLI use the same Apache 2.0 license.
> sdk(dotnet): Use same Apache 2.0 license as all other SDKs

- .changes/unreleased/Fixed-20230917-170956.yaml
- sdk/elixir/getting_started.livemd
As PR title suggests, it's a small fix to the name of ENV variable.
> Fix name of TUI experimental ENV variable

- core/container.go
- core/schema/schema_test.go
- engine/cache/mountsync.go
This PR tracks the seen cache volumes at the resolver level so they
can be automatically discovered for syncronization at the engine start
/ stop time. This solution isn't ideal since it should be getting the
cache mounts from buildkit's store instead of the resolver but we
couldn't find a way to make it work with @aluzzardi. We're falling back
to this workaround until maybe @sipsma can shed some light.
> engine: record seen cache volumes at resolver level

- codegen/generator/go/templates/functions.go
- codegen/generator/go/templates/src/header.go.tmpl
- codegen/generator/go/templates/src/object.go.tmpl
- sdk/go/.changes/unreleased/Fixed-20230915-131930.yaml
- sdk/go/api.gen.go
Update Go SDK to check for nil pointer before executing the query to throw a smaller stack trace simpler to debug for the user.
The new panic error is `unexpected nil pointer`.
Add `assertNotNil` error to check for nil value.
**Example of display**
```shell
┃ panic: unexpected nil pointer                                                                                                                                                       
┃                                                                                                                                                                                     
┃ goroutine 1 [running]: …
```
> fix(go-sdk): check nil ptr.

- engine/cache/mountsync.go
this is a follow-up of https://github.com/dagger/dagger/pull/5786 where
we have introduced automatic discovery of cache mounts so it's not
needed to check if the list is empty now.
> engine: remove syncedCacheMount check for cache manager

- core/integration/http_test.go
Handles the fallout from #5806.
> Fix TestHTTP that relied on the existence of TESTING.md

- core/directory.go
- core/integration/directory_test.go
- engine/client/buildkit.go
- engine/client/client.go
- engine/sources/gitdns/gitsource.go
- engine/sources/gitdns/state.go
- engine/sources/httpdns/httpsource.go
- go.mod
- go.sum
This allow us to replace our custom logic for waiting for buildkit to be ready with the logic implemented upstream in https://github.com/moby/buildkit/pull/4200.
Additionally, we need a minor fix to ensure that `Directory.Without` continues working, since due to a bug in buildkit, allow not found was effectively always enabled (see https://github.com/moby/buildkit/pull/4051).
We also need to import some additional logic from buildkit now that the sources logic is reasonably significantly moved around, this hopefully enables the removal of the encode id hack as a follow-up.
> Update BuildKit dependency to use upstream Wait

- engine/cache/manager.go
This is used when the Cache Service returns an error (for instance, if the account doesn't support caching).
Also useful if the Cache Service is down or misbehaving.
Caveats: The check only happens at initialization time. Once it's initialized, both cache backends are used (via 	`solver.NewCombinedCacheManager`) so it's anyone's guess what happens at that time.
I believe Erik had planned to revamp that part /cc @sipsma 
/cc @grouville
> engine: cache: fallback to local cache if remote cache returns an error

- engine/server/handler.go
This can be massively helpful for debugging - especially when debugging weird failures.
The errors are only added as debug level, since these errors generally aren't actually critical to the server.
> chore: add engine logs for failed queries

- install.sh
We (+@jpadams) have noticed slow-downs when installing via `curl -L https://dl.dagger.io/dagger/install.sh | sh`
This PR changes the base URL in `install.sh` from `dagger-io.s3.amazonaws.com` to `dl.dagger.io`
Since `install.sh` file was deleted part of https://github.com/dagger/dagger/commit/5a9c772020363668c18e73472534f01a5b03b8d5, this PR also adds it back. cc @aluzzardi
- FTR https://github.com/dagger/dagger/pull/1819#issuecomment-1078511779
> install.sh uses CloudFront CDN for CLI installs

- internal/mage/sdk/java.go
- sdk/java/README.md
- sdk/java/dagger-codegen-maven-plugin/src/main/java/io/dagger/codegen/DaggerCodegenMojo.java
- sdk/java/pom.xml
This PR improves the generation of the API schema file (used by codegen phase)
- ensure the targeted version matches the CLI version
- add "devel" alias and set the current targeted version to `devel` (a specific version should be set to a stable version when releasing the library)
- infer the schema version from the CLI in sdk:java:generate build target
fixes #5823
> sdk(java): Improve schema (re)generation

- docs/current/cookbook.md
- docs/current/cookbook/snippets/cache-dependencies/index.mjs
- docs/current/cookbook/snippets/cache-dependencies/main.go
- docs/current/cookbook/snippets/cache-dependencies/main.py
This commit updates the recipes for dependency caching using cache volumes with examples for Python and Go.
> docs: Improves dependency caching recipes

- docs/current/labs/project-zenith.md
- website/sidebars.js
This commit adds a Zenith module development guide as an ephemeral page to the documentation, with appropriate notices.
> docs: Adds Zenith guide

- go.mod
- go.sum
https://github.com/moby/buildkit/compare/bbe48e778f9df07eabc7fc05023c8e97e3c5c5ce...86e25b3ad8c20fc420669949f24bb86c74082b2f
Mostly only docs and config changes, but brings in https://github.com/moby/buildkit/pull/4321, which helps to clear up `Directory.File` errors when the target path does not exist.
Before:
```
failed to get config file: lstat /tmp/buildkit-mount563380996/github/dagger.json: no such file or directory
```
After:
```
failed to get config file: lstat /github/dagger.json: no such file or directory
```
> chore: update buildkit to master@86e25b3ad8c2

- docs/current/labs/project-zenith.md
Just see that https://daggerverse.dev/ already up and running but the documentation didn't get update.
> Change Daggerverse url

- core/integration/remotecache_test.go
- engine/buildkit/filesync.go
- engine/sources/blob/blobsource.go
The blob source type we use to safely refer to local dir sync contents relies on the previous local dir sync ops to exist locally.
Before this change, there was a case where use of remote cache could result in the contents still being lazy in the remote cache rather than actually existing locally. This led to error messages like "missing descriptor handlers for lazy blobs".
This specifically happens because we need to split local dir syncs across 3 ops:
1. The actual local dir source, which does the sync
2. A copy of the state of the local dir sync, which allows us to use the snapshot contents without making the local dir snapshot immutable, which prevents it from being re-used.
3. The blob source op, which allows our LLB to simply refer to the contents of the sync in a content-addressed …
> engine: ensure blob source layers are unlazied.

- sdk/elixir/.changes/unreleased/Fixed-20231011-215344.yaml
- sdk/elixir/lib/dagger/query_builder.ex
- sdk/elixir/test/dagger/client_test.exs
- sdk/elixir/test/dagger/querybuilder_test.exs
The issue is `true` value will consider as `atom`. When passing it to `is_atom`, it returns true and convert it to GraphQL string value.
Fixes by do not let boolean value enter the `is_atom` clause.
Fixes #5836
> fix: fix Dagger.Container.with_env_variable/4 crash

- cmd/dagger/engine.go
Added this feature to Progrock and never went back and enabled it! :facepalm: 
This should reduce the need for `--focus=false` since errors will be shown regardless.
related to #5894
> Reveal errored vertices by default

- website/sidebars.js
This PR removes a duplicated GraphQL API section from the dagger.io docs sidebar.
> fix(docs): remove duplicated graphql api section

- website/.gitignore
- website/docs-graphql/README.md
- website/docs-graphql/config.yml
- website/docs-graphql/custom-theme/views/partials/graphql/_query-or-mutation-arguments.hbs
- website/package.json
- website/yarn.lock
This PR adds a deprecation notice next to the query arguments set as `@deprecated` in the schema files inside the `/core/schema` directory.
This also adds a tip in the `docs-graphql` README to improve the debugging experience a bit.
> docs(feat): mark deprecated args in graphql reference

- engine/client/buildkit.go
- engine/client/client.go
- engine/server/buildkitcontroller.go
- engine/version.go
This adds a sanity check to check that when we connect to a remote buildkit instance, that it's running the dagger engine, and not a vanilla instance of buildkit.
See https://github.com/dagger/dagger/issues/5852#issuecomment-1756568885:
> If you are trying to connect to a host that was provisioned via buildx then it's not expected to work at this time. Dagger has a bit of divergence from the buildkitd that buildx uses.
We should hard fail on this kind of scenario, since it's possible to detect this by inspecting the `Package` value from buildkit's `Info` call. However, to do this, I've had to change the meaning of `Package` to contain the go package name, and smuggle the engine name through the `Revision` field. This would make this a breaking change for users with mismatched cli and …
> feat: fail when connecting to vanilla buildkit

- internal/mage/util/engine.go
Noticed this while squashing another issue; this was accidentally pinning to an amd64 image rather than the multiplatform index.
I'm mildly confused how this went unnoticed as I previously ran `./hack/dev ./hack/make engine:test` successfully locally on my arm64 machine after the previous update, but later saw it failing due to buildctl being amd64. Possibly I had some qemu setting enabled that got reset after a reboot?
Either way, verified `./hack/dev` produces buildctl w/ right arch on my machine; CI machines are amd64 so we'll verify it works there too.
> ci: pin buildctl source image to multiplatform index

- internal/mage/sdk/python.go
We started getting flaky failures in python tests recently about corruption in the pip cache. e.g. https://github.com/dagger/dagger/pull/5915#pullrequestreview-1686180892
Helder's theory is that we need separate caches per-version of Python, so making that change to confirm it fixes.
Fixes #5917
> ci: use per-version python caches

- CONTRIBUTING.md
Could not find existing instructions to test local SDK changes. Added to the FAQ of `CONTRIBUTING.md`
> add instructions to test sdk changes locally

- cmd/codegen/generator/go/templates/modules.go
Small fixup to https://github.com/dagger/dagger/pull/5893.
If we had
```go
func (f *Foo) DoThing() *Container {
...
}
```
Then we would incorrectly generate a `WithObject` statement for `Container` even though we define no new functions for it. This patch adds a small exception for builtin types, so we only add this statement for builtin types that were extended.
> fix: don't output dagger generated types (unless overriding them)

- hack/with-dev
* adding `dagger` to `$PATH` is helpful for `./hack/dev dagger run`
* `with-dev` is a subset of `dev` that doesn't build the engine first
I usually put `with-dev` in my `$PATH` instead and just hardcode it against my `~/src/dagger` path, but might as well have a version in-repo as a reference.
> hack/dev: add dagger to $PATH, add with-dev

- core/integration/remotecache_test.go
- engine/client/client.go
- engine/opts.go
- engine/server/buildkitcontroller.go
Adds support for providing separate import/export configs for upstream remote cache and for providing multiple values of each (separated by `;`).
> core: support multiple cache configs for upstream remote cache

- engine/client/client.go
The engine client initializes its session w/ the server in a separate goroutine (due to the fact that it blocks for the duration of the session). This causes initial connection attempts to usually fail while the session is still be setup.
This creates a lot of scary-looking but harmless logs in the common case.
This changes the logic to only start printing failed connection attempts once the retry logic is going to wait over a second before the next attempt. The idea is to balance not showing useless errors but also not leave the user hanging for too long with no output and not hide errors that may useful for debugging.
Would love to have a test for this, but very hard to test timing things w/out flakes, so just manually tested so far.
One potentially better solution would be to have a …
> engine: reduce connection retry noise

- cmd/dagger/flags.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
- sdk/python/src/dagger/ext/_functions.py
This includes not sending default values in the query, showing them in `--help` and validating missing required flags.
**Example**
```python
@function
def hello(
greeting: Annotated[str, "Your greeting"],
name: Annotated[str, "The name to say hello to"] = "World!",
) -> str:
return f"{greeting}, {name}!"
```
**Showing help**
```
> dagger call hello --help
✔ running "dagger call hello" [0.00s]
┃ Usage:
┃   dagger call hello [flags]
┃
┃ Flags:
┃       --greeting string   Your greeting
┃   -h, --help              help for hello
┃       --name string       The name to say hello to (default "World!")
```
**Required argument validation**
```
> dagger call hello
Error: required flag(s) "greeting" not set
exit status 1
```
**Default value not sent**
```
> dagger call hello --greeting Bonjour
✔ …
```
> cli: handle optional arguments in module functions

- internal/mage/util/engine.go
This is better in general. It also just so happens to be enough to not cache a previous install of some libs that is likely causing us to end up with an old vulnerable version of libcurl due to our new use of shared dagger runners.
> ci: add --no-cache to alpine apk add

- internal/mage/engine.go
- internal/mage/util/engine.go
* Build the pre-loaded go sdk tarball for the specified platform, not the host platform
* Force use of gzip compression to ensure cloud cache layers that use zstd don't end up in the image; old docker versions don't support zstd
> ci: fix engine image publishing bugs

- docs/current/partials/_install-cli.md
The Linux install instructions were missing some back tics to end a code block.
Let me know if this needs an issue too.
> docs: Fix typo in cli install instructions.

- cmd/dagger/flags.go
Fixes typo in file flag value check
```
dagger call workflows run --source /Users/aweris/development/workspaces/github.com/aweris/gale --workflow-file "/Users/aweris/development/workspaces/github.com/aweris/gale/ci/workflows/job-outputs.yaml" result
✘ build "dagger call" ERROR [1.13s]
├ [0.78s] loading module
├ [0.35s] loading objects
• Engine: 61b34bf9d33e (version v0.9.0)
⧗ 2.14s ✔ 30 ∅ 12 ✘ 1
Error: parse flags: invalid argument "/Users/aweris/development/workspaces/github.com/aweris/gale/ci/workflows/job-outputs.yaml" for "--workflow-file" flag: file path cannot be empty
```
> fix: do not fail when value set to file flag

- core/function.go
- core/ids.go
- core/integration/module_test.go
- core/module.go
- core/schema/function.graphqls
- core/schema/module.go
- sdk/elixir/lib/dagger/gen/function.ex
- sdk/go/dagger.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
We are hitting some problems with IDs growing to enormous size and exceeding gRPC messages limits in relatively normal cases (i.e. 13 functions defined in a module).
I didn't fully track down exactly what was happening, but suspected that it was related to the annoyance we were dealing with internally to store ModuleID on the Function object.
That annoyance only existed in order to support the Function.call "dynamic" API. That API isn't actually used anywhere right now, so I just tried removing that API call and the associated ModuleID handling in Function and sure enough the problem w/ huge IDs went away.
This feels like the best solution for now. If a request for the Function.call API arises in the future it can be re-added but rather than adding it to the Function object, it can be put …
> core: fix huge module/func IDs by removing Function.call

- sdk/rust/Cargo.lock
- sdk/rust/crates/dagger-sdk/CHANGELOG.md
- sdk/rust/crates/dagger-sdk/Cargo.toml
- sdk/rust/crates/dagger-sdk/src/client.rs
- sdk/rust/crates/dagger-sdk/src/core/downloader.rs
- sdk/rust/crates/dagger-sdk/src/querybuilder.rs
This change changes the types internally to use + Send, Sync, for outer layers (this allows it to be moved across threads, and cpus), and internally to be moved to threads.
This is useful when you want to parallelize the rust code. This was previously not a problem, but after I moved the code to use deferred execution. I.e. ids() are only resolved at the end of the run (on syncs).
This is tricky because rust has strict compile checks around how many times a function is called and such. I've also removed some redundant Arc around external calls, which should reduce the boiler plate required
> feat: allow rust sdk to run in async context with embedded Fn

- cmd/codegen/codegen.go
- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
- core/integration/testdata/modules/go/extend/main.go
- core/integration/testdata/modules/go/namespacing/main.go
- core/schema/module.go
- docs/current/labs/project-zenith.md
We've decided to disable this ability for now since it creates hard to
solve problems w/ namespacing (simply prefixing extension functions with
Module name often creates extremely awkward names) and is unclear in
terms of benefits relative to confusion in terms of API design.
It will be possible to re-add support for this in the future if desired
and in the meantime it would still be possible for a custom SDK to
implement support for this by identifying fields in the graphql schema
that could be implemented as methods directly attached to core types.
Signed-off-by: Erik Sipsma <erik@dagger.io>
> core: disable support for modules extending core types

- core/secret.go
- core/secret_test.go
Partially resolves https://github.com/dagger/dagger/issues/5930#issuecomment-1775291664.
Having duplicate error types meant that the git llb source attempting to look for the git secrets would not get an ErrNotFound, and would instead bail after looking for the first secret. See https://github.com/moby/buildkit/blob/d5c1d785b042cf834a05b08b73479d55b6acb533/source/git/source.go#L259-L265.
This update fixes this by ensuring that we use the same error type, so we properly look for all specified secrets.
> fix: return upstream ErrNotFound from secret store

- core/secret.go
- engine/server/buildkitcontroller.go
`SecretStore.SetBuildkitClient` was not being used - it appears to be left over from a previous refactor, so we can remove it.
> chore: remove unneccessary secret store method

- cmd/dagger/module.go
- core/module.go
- core/modules/resolver.go
Fixes #5953
---
~~I'm working on adding integ test coverage right now, just verified manually so far. Will push it here or as separate commit, depending on timing of this being merged.~~
~~Integ test requires way more work than the fix itself because we need to re-add the ability to create a git repo from a module source dir and then run it as a service container that a dev engine talks to. @vito I'm going to try doing this by running the dev engine as a service that has a dependency on the git service; hopefully this should avoid the headaches of the old implementation where the dev engine had an implicit dependency on a service running in itself 🙂~~
EDIT: I didn't realize we only allowed git modules from `github.com` now, which throws a wrench into having an automated test here. We can …
> cli: set source subpath when loading git modules

- cmd/dagger/call.go
- cmd/dagger/download.go
- cmd/dagger/flags.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
- cmd/dagger/shell.go
- cmd/dagger/up.go
Follow-up to #5882
There’s more checks and validations. Also better printing with progrock, making the loading vertex unfocused and pushing `-help` and `dagger functions` to the execution vertex (focused).
> Fix several validation and presentation issues in function commands

- cmd/dagger/vcs.go
- core/integration/module_test.go
- core/schema/module.go
- docs/current/labs/project-zenith.md
- internal/mage/util/engine.go
- sdk/python/runtime/go.mod
- sdk/python/runtime/main.go
This adds support for re-generating the client with functions from dependencies, and also for `dagger mod init` and `dagger mod sync`.
> Fix python module codegen

- .changes/unreleased/Breaking-20231024-152415.yaml
- cmd/codegen/generator/go/templates/modules.go
- cmd/codegen/generator/go/templates/src/header.go.tmpl
- core/integration/module_test.go
- core/integration/testdata/modules/go/minimal/main.go
- docs/current/labs/project-zenith.md
- go.mod
- go.sum
- sdk/go/dagger.gen.go
:warning: Based on https://github.com/dagger/dagger/pull/5893
:hammer_and_wrench: Fixes https://github.com/dagger/dagger/issues/5904 https://github.com/dagger/dagger/issues/5864
This PR uses the approach detailed in https://github.com/dagger/dagger/issues/5864#issuecomment-1765040417:
> To resolve this, instead, we can just look at the Name of the struct - if it ends in "Opt" or similar, then we treat it as an opts struct.
All structs that end in "Opt"/"Opts"/"Option"/"Options" are treated as an opts-like struct, and we read parameters directly into them. However, because we're now not using the pointeriness of parameters to determine this, there's now a *bunch* of cases we need to handle - how should we handle `**Opts` or `[]Opts`, etc. These are all handled now by creating a single opts …
> fix: remove options structs in go sdk

- cmd/codegen/generator/go/generator.go
- core/integration/module_test.go
- core/schema/module.go
Calling sync isn't required there and just creates confusion, so it's better to remove it.
---
Discord discussion: https://discord.com/channels/707636530424053791/1120503349599543376/1166774396820672512
> zenith: remove .Sync from module default main.go in go sdk

- go.mod
- go.sum
- internal/mage/util/engine.go
Resolves https://github.com/dagger/dagger/pull/5605#issuecomment-1780854781.
v1.58.2 suffers from GHSA-m425-mq94-257g, so we bump the version.
The risks of such a bump are low, the difference between v1.58.2 and v1.58.3 is only the fix.
> chore: update grpc to v1.58.3

- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
Fixes #5971, introduced in #5907.
A single field can contain multiple names - in the go ast, but these are properly extracted for the types.
We need a special function to map the type indexes onto the ast indexes properly.
> fix: gracefully handle zenith shared types in go sdk

- cmd/dagger/licenses.go
- cmd/dagger/module.go
- core/integration/module_test.go
- core/modules/config.go
- go.mod
- go.sum
`dagger mod init` will now create a LICENSE file for you, defaulting to Apache-2.0.
If it finds an existing LICENSE file, searching up to the root of the repo, it won't do anything and will just log the file it found at debug level.
Note that this only happens on `init`, not `sync`, since it's perfectly valid to not want a LICENSE file if you just don't want anyone else to use your stuff.
There is a `--license` flag too which lets you specify which license you want, and it'll generate the requested license even if one is found in the upper directories, in case you want a different one.
Along the way, refactors a bunch of the `dagger mod` command/flag handling:
* replace remaining usage of `*moduleFlagConfig` with `*modules.Ref`
* pass a `moduleDir string` into `updateModuleConfig`, using …
> dagger mod init creates LICENSE if none found

- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
:cry: Woops, I added some regressions in #5893
Added a couple fixes, with more detailed descriptions below.
The previous fix to apply recursion to detect nested types (in struct fields, return parameters, etc) was too extensive.
Specifically: if a struct type X was created that contains struct type Y, code for type Y would always be generated, even if type X would not be generated (which could happen it was at the top-level and had no functions declared on it).
To avoid this, we need to *only* consider any subtypes for code generation iff the main type would be considered for code generation. Doing this is a bit tricky though, we need to remove the global extraTypes state, and instead return results back up through the function call chain - this gives us a number of subtypes for each …
> Various Go SDK recursion fixes

- cmd/codegen/generator/go/generator.go
- core/integration/module_test.go
Previously we were using the dagger module as the go module name, but that allows users to accidentally use reserved words ("go", "toolchain", "replace", etc.).
There's no harm in using a safe default like "main"; users are free to update it later if they want.
---
Ref: https://discord.com/channels/707636530424053791/1120503349599543376/1167178632557494342
Fixes https://github.com/dagger/dagger/issues/5975
> zenith: use main as default go module name

- internal/mage/util/engine.go
Fixup the hack added in https://github.com/dagger/dagger/pull/5965#issuecomment-1780892041.
BuildKit merged the gRPC update in https://github.com/moby/buildkit/pull/4341, so we no longer need our little hack to override the gRPC version from upstream to pass the scan engine checks.
> chore: remove buildctl grpc build hack

- cmd/codegen/generator/go/templates/src/header.go.tmpl
- sdk/go/dagger.gen.go
As discussed in https://discord.com/channels/707636530424053791/1120503349599543376/1167237283318071296:
> @jedevc:
>
> If you call Optional.Get then it returns the string and a bool that's true if it was set and false if it wasn't - there's also a helper .GetOr that returns the provided default if it wasn't set.
>
> These need doc comments actually, I'll do that ASAP tomorrow
This should help users use `Optional`s a bit more easily.
> chore: add docs for Optional type in go SDK

- cmd/codegen/codegen.go
- cmd/codegen/generator/generator.go
- cmd/codegen/main.go
- cmd/shim/main.go
- core/container.go
- core/file.go
- core/function.go
- core/integration/module_test.go
- core/module.go
- core/schema/container.go
- core/schema/module.go
- core/schema/schema.go
- core/schema/sdk.go
- core/service.go
- engine/buildkit/client.go
- engine/client/client.go
- engine/opts.go
- engine/server/server.go
- sdk/python/runtime/main.go
- sdk/python/src/dagger/client/_session.py
This started out as just fixing https://github.com/dagger/dagger/issues/5872, but looking into that uncovered a lot of deeper problems that needed fixes+cleanups as a pre-req.
This relates to the conversation the other day w/ @vito and @helderco: https://github.com/dagger/dagger/pull/5954#issuecomment-1776545239
I now understand *why* things seemed to mostly work before, but it turns out to have been a mildly astonishing set of coincidences rather than anything solid. Quick explanation:
1. Runtime+Codegen is executed as containers in `core/schema/sdk.go`, but those were staying lazy, not actually evaluated at the time that code is called (if you forced them to synchronously evaluate, they no longer worked as expected due to missing dependency schemas)
2. They didn't get actually evaluated …
> Sync codegen even on compilation error; fix general SDK codegen+runtime invocation problems

- internal/mage/sdk/python.go
- sdk/python/runtime/main.go
- sdk/python/src/dagger/_codegen/cli.py
- sdk/python/src/dagger/client/_session.py
This is a missing commit from https://github.com/dagger/dagger/pull/5964
With the introspection we avoid having to make a connection to the API at all, which also avoids any issue importing an incomplete or non-importable `dagger` package (due to errors).
Cleaned up the python cli in preparation for moving the `mod init` templates there. Typer would have been a better choice for sys.argv parsing but I still wanted to avoid adding a dependency just for this.
> Move python module codegen introspection to cli

- cmd/codegen/generator/functions.go
- cmd/codegen/generator/go/templates/functions.go
- cmd/codegen/generator/go/templates/modules.go
- cmd/codegen/generator/go/templates/modules_test.go
This cleans up the panic-ing behavior inside go sdk template functions. The important change is to try and recover and print a stack trace from panics during module code generation since this is the code that's most likely to actually panic.
This resolves https://discord.com/channels/707636530424053791/1120503349599543376/1167157523275579422:
> Hard to debug because I'm not getting a filename or line
The other functions *can panic*, but are much less likely to - they're also small enough that it should be more trivial to debug failures. I did try writing a more generic wrapper to wrap all the template functions to capture stack traces, but this requires re-defining lots of the custom logic for how function calls work in text/template, which I didn't really feel like re-implementing :cry:
> chore: avoid panics in go sdk template functions

- core/integration/cache_test.go
- core/integration/file_test.go
- core/integration/gpu_test.go
- core/integration/host_test.go
- core/integration/images.go
- core/integration/module_test.go
- core/integration/pipeline_test.go
- core/integration/remotecache_test.go
- core/integration/services_test.go
- core/integration/suite_test.go
- core/integration/testdata/modules/go/id/arg/main.go
- core/integration/testdata/modules/go/id/field/main.go
- core/integration/testdata/modules/go/id/fn/main.go
- core/integration/testdata/modules/python/id/arg/src/main.py
- core/integration/testdata/modules/python/id/fn/src/main.py
- core/schema/module.go
- internal/mage/util/util.go
ID is a special reserved word in our schema and before this change resulted in incomprehensible errors when trying to consume modules that used it in field names. Now we just block these modules from being loaded and return a more comprehensible error.
Ref: https://discord.com/channels/707636530424053791/1167533512652509324/1167541884785266718
> core: disallow reserved ID field in user modules

- cmd/dagger/module.go
Pretty rough start, doesn't complain about errors at all, and if you publish before pushing, Daggerverse currently caches the error forever (until it reboots). Whoopsie!
Here's how it looks:
[![asciicast](https://asciinema.org/a/LtDT5YB9ogyHdoShgbEDX29UV.svg)](https://asciinema.org/a/LtDT5YB9ogyHdoShgbEDX29UV)
> add `dagger mod publish`

- core/integration/module_test.go
- core/module.go
- core/schema/module.go
- core/schema/schema.go
We were including the full ModuleID for all deps of a Module in each ModuleID, which meant that recursive deps all got combined into a single ID for the dep and massively increased the size of the ID.
Now we remove `Dependencies` from the actual Module ID and instead just include the module refs of the deps.
To make up for the reduction in memoization of loading deps, there's a new `CacheMap` internally that de-dupes loading deps for a given module.
---
---
Ref: https://discord.com/channels/707636530424053791/1168341591606444122/1168343528183709768
cc @kpenfound
> Fix for mod deps blowing up ID size

- .github/workflows/_hack_make.yml
- .github/workflows/docs.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/helm.yml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-sdk-elixir.yml
- .github/workflows/publish-sdk-go.yml
- .github/workflows/publish-sdk-nodejs.yml
- .github/workflows/publish-sdk-python.yml
- .github/workflows/publish-sdk-rust.yml
- .github/workflows/sdk-elixir.yml
- .github/workflows/sdk-go.yml
- .github/workflows/sdk-java.yml
- .github/workflows/sdk-nodejs.yml
- .github/workflows/sdk-python.yml
- .github/workflows/sdk-rust.yml
Without this, runs will **not** appear in <https://dagger.cloud>
Since this is an org-wide secret, and secrets are not shared with PRs coming from forks, we will not see runs in <https://dagger.cloud> until the change executes in the context of our repository (most likely merge to `main`).
---
- https://github.com/dagger/dagger/pull/6019
> Add DAGGER_CLOUD_TOKEN client-side so that we get telemetry in Cloud

- cmd/dagger/module.go
- core/integration/module_test.go
- docs/current/labs/project-zenith.md
`install` is more common for this type of functionality in similar tools.
`use` remains as an alias of `install`.
> cli: rename `use` command to `install`.

- .github/workflows/engine-and-cli.yml
- internal/mage/engine.go
ci: just run testrace in CI, not it and test
Since runs get grouped together on our new CI runners, I am wondering if
the overhead of duplicating the same test suite (one w/ -race enabled,
one without) actually slows us down more relative to just running
testrace.
---
ci: only run container+module tests for testdev workflow.
These tests are painfully slow currently. They also are only needed to
ensure that the dev engine can build itself. Running the full test suite
against it is not necessary; running this important subset is more than
sufficient (may even be overkill still).
> ci: improve test workflow runtimes

- cmd/codegen/generator/go/templates/src/module.go.tmpl
- core/integration/module_test.go
Before this, if a user defined a var that called `dag`, they'd hit a panic because `dag` wasn't initialized yet.
This was because we were initializing `dag` in an `init` func, but go evaluates global vars first.
This fixes that situation by initializing `dag` as a var.
---
Ref: https://discord.com/channels/707636530424053791/1168640248666914846/1168640461460750396
> go sdk: fix user global var that references dag

- cmd/dagger/up.go
Before this, you'd get an error if you tried to call dagger up on a container type, but now we just automatically call asService on it in that case.
---
I'd like to add a test case for `dagger up` as part of this, but this fix is just a quick side quest (from writing docs), so I will either update this PR or follow-up later w/ a test depending on timing.
> cli: call asService if container provided to dagger up

- cmd/codegen/generator/go/templates/src/header.go.tmpl
- core/integration/module_test.go
- core/integration/testdata/modules/go/minimal/main.go
- sdk/go/dagger.gen.go
Fixes [DEV-2948](https://linear.app/dagger/issue/DEV-2948/go-sdk-doesnt-support-optional-string-array).
This allows making slice types (`[]any`) optional, which is permitted at the API level, but wasn't allowed at the type constraint level.
We previously used this constraint because it was assumed that a user might constraint an Optional manually, and not set `isSet`. However, this is an edge case that pokes into the private internals of `dagger.gen.go`, and we now have the `Opt` helper for this. Users doing this kind of access should be aware of what they're doing.
Additionally, to really avoid poking around the internals, we add the `OptEmpty` helper, which creates an empty optional - note that the type constraint cannot be automatically derived, at least in the current version of Go.
> fix: remove comparable constraint from Optional

- core/modules/resolver.go
The logic around `Git` refs having both `Path` and `Subpath` fields that each include the actual subpath is quite convoluted and this code all needs general refactoring/cleanup, but this fix is needed in the short term to fix problems elsewhere, so just making the smallest possible fix at this time.
> zenith: set subpath and path when parent module is git

- sdk/python/src/dagger/mod/_converter.py
- sdk/python/src/dagger/mod/_module.py
- sdk/python/src/dagger/mod/_utils.py
- sdk/python/tests/modules/test_serialization.py
There was an issue having a dagger type in `Annotated`:
```python
ctr: Annotated[dagger.Container, Doc("A container")] = mod.field()
```
Fixed in this PR.
There's a remaining issue in the _cattrs_ library for handling unions and generics in `Annotated`. Fixed but not released yet.
> Fix for annotated dagger types

- cmd/dagger/download.go
> dagger download: rename flag --export-path to --output

- cmd/codegen/main.go
This fixes [DEV-2936](https://linear.app/dagger/issue/DEV-2936/module-errors-obsfucated-by-codegen-usage) (cc @shykes).
Before:
```
1: generating go module: playground
1: generating go module: playground ERROR: generate code: template: module:59:3: executing "module" at <ModuleMainSrc>: error calling ModuleMainSrc: failed to convert method Read to function def: failed to convert param type: invalid type: invalid type
Error: generate code: template: module:59:3: executing "module" at <ModuleMainSrc>: error calling ModuleMainSrc: failed to convert method Read to function def: failed to convert param type: invalid type: invalid type
Usage:
codegen [flags]
Flags:
-h, --help                             help for codegen
--introspection-json-path string   optional path to file containing …
```
> fix: reduce verbosity of codegen errors

- cmd/dagger/call.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
- core/integration/module_test.go
```console
$ dagger -m github.com/shykes/daggerverse/supergit call remote --url https://github.com/dagger/dagger tags name
✘ dagger call remote tags ERROR [0.00s]
┃ Error: unknown command "name" for "dagger call remote tags"                        
• Cloud URL: https://dagger.cloud/runs/143cd139-e3d5-423b-8558-09a118923dd6
• Engine: 002636d876e8 (version devel ())
⧗ 2.50s ✔ 175 ∅ 4 ✘ 1
```
```console
$ dagger -m github.com/shykes/daggerverse/supergit call remote --url https://github.com/dagger/dagger tags name
✔ dagger call remote tags name [1.62s]
┃ sdk/cue/v0.1.0
┃ sdk/cue/v0.2.232
┃ sdk/elixir/v0.8.2
┃ sdk/elixir/v0.8.4
┃ sdk/elixir/v0.8.5
┃ sdk/elixir/v0.8.6
┃ sdk/elixir/v0.8.7
┃ sdk/elixir/v0.8.8
┃ sdk/elixir/v0.9.0
┃ sdk/elixir/v0.9.1
┃ sdk/go/v0.3.0
┃ sdk/go/v0.3.0-alpha.1
┃ …
```
> dagger call: fix returning a list of objects with functions

- .golangci.yml
- go.mod
- go.sum
- internal/mage/engine.go
Updates us to https://github.com/dagger/graphql/pull/3
The change there makes the return value of graphql introspection stable, which is important since it's an input to the SDK Codegen+Runtime functions.
Previously, we were re-running those SDK functions way too often, which wasted tons of time, especially in modules with larger dependency DAGs.
One of Kyle's demo's took a minimum of 25s every run due to that; now it's down to 7s with this fix in place.
> engine: update to latest graphql-go version

- cmd/dagger/flags.go
- cmd/dagger/module.go
- cmd/dagger/module_test.go
- core/integration/module_test.go
Support values include:
- `./mydir`
- `file://mydir`
- Various url schemes for git remote: `git://`, `ssh://`, `https://`, `git+ssh://`, `git+https://`
- Encode git ref in URL fragment (defaults to `main`): `https://github.com/dagger/dagger#v0.9.2`
- Not yet supported: tarball-over-https
- Not yet supported: interpret local dir as a git repo, by encoding a git ref in the fragment, eg. `file://.#main`
> CLI: support git URLs as directory arguments

- .github/workflows/_hack_make.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-sdk-elixir.yml
- .github/workflows/publish-sdk-go.yml
- .github/workflows/publish-sdk-nodejs.yml
- .github/workflows/publish-sdk-python.yml
- .github/workflows/publish-sdk-rust.yml
- .github/workflows/publish.yml
- .github/workflows/sdk-python.yml
- internal/mage/cli.go
Needed to fix failure on main: https://github.com/dagger/dagger/actions/runs/6751412649/job/18355442139
> ci: update all github workflows to go 1.21

- docs/current/cli/389936-run-pipelines-cli.md
changed container name from alpine to golang to match the code: https://github.com/dagger/dagger/blob/8f21a24e7fc2186519876093a84ac1963395c73a/docs/current/cli/snippets/get-started/step3/build.sh#L23
> fix container name in 389936-run-pipelines-cli.md

- docs/zenith/user/quickstart/120928-setup.mdx
This commit updates the repository path in the user quickstart to point to the hello-dagger repository instead of the sipsma repository
> docs: Updates repository path for example

- docs/zenith/developer/index.md
This commit adds a brief introduction to the "programming Dagger" section.
> docs: Adds Zenith programming section intro

- sdk/python/src/dagger/mod/_module.py
- sdk/python/tests/modules/test_registration.py
Fixes a bug where object fields didn't rename:
```python
@object_type
class PotatoMessage:
from_: str = field(name="from")
```
Attempting to access `from` via the API would produce the following error:
```
Cannot return null for non-nullable field PotatoMessage.from
```
> Python: Fix module field name override

- sdk/python/pyproject.toml
- sdk/python/src/dagger/client/_core.py
- sdk/python/src/dagger/client/_guards.py
- sdk/python/tests/client/test_codegen.py
- sdk/python/tests/client/test_default_client.py
- sdk/python/tests/client/test_integration.py
- sdk/python/tests/modules/test_registration.py
Fixes #5927
With this change, default values in **input object** fields are omitted.
For example:
```python
svc = dagger.host().service([dagger.PortForward(8000)])
```
Destructures now as:
```python
{"ports": [{"backend": 8000}]}
```
Previously it was destructuring with defaults included:
```python
{'ports': [{'backend': 8000, 'frontend': None, 'protocol': None}]}
```
Where `PortForward`, on server side, `frontend` is set to be equal to `backend` unless it's set. By sending the default of `None`, it was overriding that.
> Python: Fix input defaults

- core/integration/gpu_test.go
Follow up of #5605.
Improves the experience when running integration tests locally. If multi GPU integration tests ran on single GPU environments we were previously doing `t.Fatal()`, with this PR those tests are safely skipped with a log line.
In the same way, multi GPU tests should run as expected on multi GPU environments.
> core: omit execution of multi GPU tests on single GPU environments

- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
Follow-up to https://github.com/dagger/dagger/pull/5907#discussion_r1371873008, worked out a neat way to properly handle those weird edge cases.
This PR fixes (and tests for) a couple edge cases with our custom comment parsing:
- Don't read previous lines line-comments as doc-comments
```go
foo string, // this documents foo, not bar 
bar string, // this should document bar
```
- Don't read comments after the function as line-comments for the last arg
```go
func (x *X) DoThing(foo string) { // this should not document foo
```
> fix: handle more edge cases with custom comment parsing

- cmd/codegen/generator/go/generator.go
- core/integration/module_test.go
- core/integration/testdata/modules/go/roots/bad-self-dir/dagger.json
- core/integration/testdata/modules/go/roots/bad-self-dir/main.go
- core/integration/testdata/modules/go/roots/bad-sibling-dep/dagger.json
- core/integration/testdata/modules/go/roots/bad-sibling-dep/main.go
- core/integration/testdata/modules/go/roots/bad-sibling-dir/dagger.json
- core/integration/testdata/modules/go/roots/bad-sibling-dir/main.go
- core/integration/testdata/modules/go/roots/bad-sub-dir/dagger.json
- core/integration/testdata/modules/go/roots/bad-sub-dir/main.go
- core/integration/testdata/modules/go/roots/good-base/dagger.json
- core/integration/testdata/modules/go/roots/good-base/main.go
- core/integration/testdata/modules/go/roots/good-parent-dir/dagger.json
- core/integration/testdata/modules/go/roots/good-parent-dir/main.go
- core/integration/testdata/modules/go/roots/good-sibling-dep/dagger.json
- core/integration/testdata/modules/go/roots/good-sibling-dep/main.go
- core/module.go
- core/modules/config.go
- core/modules/resolver.go
This patch detects some additional edge cases when loading modules, notably:
- Fail if the server tries to load a module where the config is not under the root - this is still also checked client-side for the main module. However, by adding checks server-side, we also get this for dependencies as well.
Additionally, a few small nitpicks:
- Use `path/filepath` instead of `path`.
`path/filepath` uses OS-depedendant separators, which, while we're not using this, highlights that these are files.
- Use filepath utilities wherever possible (e.g. use `filepath.Rel` instead of `strings.TrimPrefix`).
- Check if a path is a parent to the current directory - `strings.HasPrefix(target, "..")` wasn't right, since a normal filename *can* begin with `..`.
> chore: clean up module path handling from local

- sdk/python/src/dagger/mod/_utils.py
- sdk/python/tests/modules/test_utils.py
Fixes #6096
```python
from dagger.mod import function
@function
def foo(bar: str | None = None) -> str:
return bar or "foobar"
```
Help output:
```diff
Usage:
dagger call foo [flags]
Flags:
-       --bar string   Represent a PEP 604 union type
-
-                      E.g. for int | str
+       --bar string
-h, --help         help for foo
```
> Python modules: Prevent documenting regular unions

- sdk/python/pyproject.toml
- sdk/python/src/dagger/mod/_converter.py
- sdk/python/src/dagger/mod/_utils.py
- sdk/python/tests/modules/test_utils.py
Fixes #6094 
It's recommended to use the `str | None` syntax instead of the older (and misnamed) `Optional[str]`. However, the latter should still be supported which is what this PR fixes.
The problem was a bad assumption on my part, as I thought these would be the same:
```python
>>> get_origin(str | None)
<class 'types.UnionType'>
>>> get_origin(Optional[str])
typing.Union
```
> Python modules: Allow using `Optional` in parameters

- sdk/python/.changes/unreleased/Fixed-20231113-164527.yaml
- sdk/python/src/dagger/_codegen/generator.py
- sdk/python/tests/client/test_codegen.py
> Python SDK: fix codegen docstring ending in `"`

- core/integration/module_test.go
- sdk/python/runtime/main.go
Codegen wasn't including the module's `subPath` when generating files.
```shell
dagger mod init --sdk=python --name=bare --root=..
```
```
.
├── bare
│  ├── sdk
│  ├── src
│  └── pyproject.toml
├── .gitignore
└── dagger.json
```
```
.
├── sdk
├── src
├── .gitignore
├── dagger.json
└── pyproject.toml
```
> fix: Python module codegen with different root

- cmd/codegen/generator/go/templates/modules.go
- core/function.go
- core/integration/module_test.go
- core/schema/module.go
Fixes https://github.com/dagger/dagger/issues/5860.
Essentially, we configure the Go SDK to make sure that we always request the name of the field that we want the server to send/receive from. If we ask for field "A", we should get "A" and not the camel-cased "a". As a nice effect to do this, we need to add `OriginalName` support for fields. (@helderco I remember you saying something about this *somewhere*, but I couldn't find where you mentioned it, sorry).
This is still... not great (but it's an alright stop-gap). It fixes the temporary nastiness of needing these json tags, but we still have the issue that the user might still want to use JSON tags - it would be *awesome* if we could have our own `dagger` tags. For example, I need to maintain a manual mapping of structs in one of my …
> Zenith (Go SDK): allow omitting JSON types in structs

- core/integration/services_test.go
- core/integration/suite_test.go
This makes it easier to write Dagger benchmarks and reuse test helpers like `connect`:
```go
func BenchmarkSomeFunctionality(b *testing.B) {
c, ctx := connect(b)
secretKeyReader := bytes.NewReader(secretKeyBytes)
secretValue, err := io.ReadAll(secretKeyReader)
s := c.SetSecret("key", string(secretValue))
for i := 0; i < b.N; i++ {
sec := c.Container().From(alpineImage).
WithSecretVariable("KEY", s).
WithExec([]string{"sh", "-c", "echo  -n \"$KEY " + index + "\""})
sec.Stdout(ctx)
}
}
```
[testify](https://github.com/stretchr/testify) also uses `testing.TB` so no refactors are needed for `require.NoError`, `require.Equal`, etc. in existing tests.
Also changed `gitService` to use `testing.TB` as it's referenced by `daggerCliPath`.
> refactor: use testing.TB interface in test helpers

- .github/workflows/sdk-python.yml
- core/integration/container_test.go
- docs/current/cookbook/snippets/error-handling/postmortem/main.py
- sdk/python/pyproject.toml
- sdk/python/requirements.txt
- sdk/python/src/dagger/_engine/download.py
- sdk/python/src/dagger/_managers.py
- sdk/python/tests/client/test_integration_connection.py
- sdk/python/tests/engine/test_download.py
Python tests didn't move to our dagger runners because the provisioning test has been failing when `_EXPERIMENTAL_DAGGER_CLI_BIN` is set, at least locally on macOS and on the custom runners. This test could have been skipped by adding `, "-m", "not provision"` in mage, but better to fix the test:
https://github.com/dagger/dagger/blob/1f63a3cdd6fbe861c5637f965bc3cd96e24cd9d3/internal/mage/sdk/python.go#L97
Refactored to be more fully async, and also simplified by relying on aiohttp for the async server.
> Run python tests in dagger runner

- core/integration/module_test.go
- sdk/python/src/dagger/mod/_resolver.py
- sdk/python/tests/modules/test_forward_reference.py
- sdk/python/tests/modules/test_registration.py
Allows using `Self` when creating chainable methods:
```diff
+from typing import Self
+
from dagger.mod import function, object_type
@object_type
class Foo:
name: str = "Bar"
-    def with_bar(self, name: str) -> "Foo"
+    def with_bar(self, name: str) -> Self
self.name = name
return self
```
> Python modules: allow annotating a chainable method with `Self`

- cmd/shim/secret_scrub.go
- cmd/shim/secret_scrub_test.go
Fix #5791
This was a fun exercise in processing streams in go, and an absolutely massive nerd-snipe :cry: 
Essentially, we need a custom transformer to handle *precisely* matching Reads on the underlying source with the output - we shouldn't hold output any longer than is absolutely neccessary (which was the issue with the previous implementation).
To be able to do this at all in any reasonable way, we need a trie, and handle *all* the secrets at once, instead of doing multiple passes. Multiple passes won't work, since it's possible to accidentally trim too much at each step, which would be very sad.
> e.g. imagine secrets (aaa, bbb, ccc, etc), and an input (cba)
>
> In removing secret aaa, we would trim to cb, then we'd remove bbb to trim to c, then finally trim to nothing. However, this …
> Fix secret scrubbing log latency

- engine/buildkit/filesync.go
When `LocalFileExport` is called the following operations occur. `stat` is already populated with `FileInfo`:
```go
...
file, err := os.Open(mntFilePath)
if err != nil {
return fmt.Errorf("failed to open file: %s", err)
}
defer file.Close()
stat, err := file.Stat()
if err != nil {
return fmt.Errorf("failed to stat file: %s", err)
}
...
```
It seems there's a redundant `file.Stat` call in https://github.com/matiasinsaurralde/dagger/blob/main/engine/buildkit/filesync.go#L255
This PR removes this redundant call and modifies `fileSizeLeft` so that it reuses the original `FileInfo` value that's loaded into `stat`.
Guessing this was accidentally introduced during a big merge or similar.
> fix: remove redundant file stat from LocalFileExport

- core/function.go
- core/integration/module_test.go
- core/resourceid/module_id.go
- core/schema/cache.go
- core/schema/container.go
- core/schema/directory.go
- core/schema/file.go
- core/schema/git.go
- core/schema/host.go
- core/schema/http.go
- core/schema/module.go
- core/schema/platform.go
- core/schema/query.go
- core/schema/schema.go
- core/schema/secret.go
- core/schema/service.go
- core/schema/socket.go
:warning: Depends on https://github.com/dagger/dagger/pull/6057 (marking as draft until that one is merged)
This feature allows all module declared objects to be converted to a respective ID-type using the "id" field, and converted from an ID-type using the "loadFromID" helper. This effectively makes these types fully idable.
IDs are essentially the contents of the module type's data, JSON-encoded, and then base64-encoded, similar (but not identical) to standard IDs. At the moment, they don't share exactly the same codepaths to normal modules, but this could be adapted to be so in the future. We also include a note of *what type* generated this ID - this is so we can prevent type confusion.
Essentially, this enables a number of previously impossible use cases:
1. Returning a custom object …
> feat: make module types id-able 

- website/netlify.toml
This PR removes the override for the Node version of the build in Netlify.
> fix(docs): remove node version from config file

- docs/current/quickstart/349011-build.mdx
- docs/current/quickstart/472910-build-multi.mdx
- docs/current/quickstart/635927-caching.mdx
- docs/current/quickstart/730264-publish.mdx
- docs/current/quickstart/947391-test.mdx
- docs/current/quickstart/snippets/build-multi/index.mjs
- docs/current/quickstart/snippets/build-multi/main.go
- docs/current/quickstart/snippets/build-multi/main.py
- docs/current/quickstart/snippets/build/main.py
- docs/current/quickstart/snippets/caching/index.mjs
- docs/current/quickstart/snippets/caching/main.go
- docs/current/quickstart/snippets/caching/main.py
- docs/current/quickstart/snippets/publish/index.mjs
- docs/current/quickstart/snippets/publish/main.go
- docs/current/quickstart/snippets/publish/main.py
- docs/current/quickstart/snippets/test/index.mjs
- docs/current/quickstart/snippets/test/main.go
- docs/current/quickstart/snippets/test/main.py
- sdk/python/pyproject.toml
this adds the exclude option to the proper `client.Host().Directory`
operation to avoid sending the files over the wire each time
> docs: fix exclude option for quickstart examples.

- docs/current/quickstart/349011-build.mdx
I've been observing a few Netlify build errors here: https://app.netlify.com/sites/devel-docs-dagger-io/deploys/655d6da10b815d00089336b7
Seems it's caused by a missing quote in the docs.
> docs: fix typo in quickstart build page

- sdk/java/README.md
- sdk/java/dagger-codegen-maven-plugin/src/main/resources/schemas/schema-0.9.3.json
Add generated java sdk schema for engine version 0.9.3.
> feat: add API schema for dagger 0.9.3

- core/integration/cache_test.go
- core/integration/container_test.go
- core/integration/engine_test.go
- core/integration/host_test.go
- core/integration/local_test.go
- core/integration/services_test.go
- core/integration/socket_test.go
Update integration tests to use image constants defined in [`images.go`](https://github.com/dagger/dagger/blob/main/core/integration/images.go).
> Update integration tests to use image constants

- sdk/elixir/.changes/unreleased/Fixed-20231113-215135.yaml
- sdk/elixir/lib/dagger/codegen/elixir/function.ex
- sdk/elixir/lib/dagger/codegen/elixir/module.ex
- sdk/elixir/lib/dagger/codegen/elixir/templates/object_tmpl.ex
- sdk/elixir/lib/dagger/gen/client.ex
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/elixir/lib/dagger/gen/host.ex
- sdk/elixir/test/dagger/client_test.exs
The codegen didn't convert `Service` into an id, cause user code cannot pass `service` as a `Service` struct.
Fixes #6091
> fix Elixir service binding not working

- docs/current/quickstart/947391-test.mdx
This commit is a follow-up to https://github.com/dagger/dagger/pull/5854
> docs: Fixes method names in quickstart

- sdk/java/dagger-java-sdk/src/main/java/io/dagger/client/engineconn/Connection.java
- sdk/java/dagger-java-sdk/src/test/java/io/dagger/client/engineconn/ConnectionTest.java
this PR fixes a bug:
Even if port and session token env vars were set, the SDK tried to open a connection with dynamic provisioning. This behaviour was leading to an unexpected behaviour. This PR makes the `Connection.get` does not try to dynamically provision a Dagger CLI when the env vars are already set
> fix: Do not try to use dynamic provisioning when port and session token env vars are set

- docs/current/quickstart/349011-build.mdx
- website/package.json
- website/yarn.lock
- Removed the `yarn.lock` and then run `yarn install`
- ~~Made `npx` a dev dependency~~
- ~~Does that seem right to you @crjm @slumbering?~~
- Removed `npx` since we do not need it. Thanks @slumbering!
- ~~Added `yarn-audit-fix` as a dev dependency~~
- ~~Not sure if we want it, but it seemed to work well. WDYT @crjm @slumbering?~~
- Removed so that we have fewer dependencies overall
> Fix a bunch more CVEs coming from website deps

- core/container.go
- core/directory.go
- core/file.go
From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary.
> refactor(core): remove redundant nil check

- engine/client/buildkit.go
- engine/client/client.go
- engine/client/docker.go
This patch splits out the pull step to a separate place in the progress output, which is only printed if the image is actually pulled from the registry. This is added so we can have better insight into *what* part of connecting to the dagger engine is actually taking time (currently this is very opaque).
> **Note**
>
> For a follow-up, we should look at getting progress information from the pull, so that we can implement a progress bar, which would be even better. I think this requires talking directly to the docker api though, instead of just using the docker cli.
The first simple step to this is to split out the pull step, since this is often the very slow part. Additionally, we make "starting engine" include the "docker run" and the waiting for the client to be ready.
To actually do …
> fix: split out docker pull step in progress

- docs/current/sdk/go/959738-get-started.md
This commit fixes the command sequence in the Go SDK get started guide.
> docs: Updates Go SDK get started

- CONTRIBUTING.md
- internal/mage/sdk/rust.go
(also makes some minor doc-comment updates to the mage rust scripts to be consistent with the other SDKs)
Inspired by [this discussion in discord](https://discord.com/channels/707636530424053791/1138842816219459695/1175807235222413312), when I realized we didn't actually have docs for this (thanks @felipecruz91!)
> docs: update contributing guide with info on regenerating SDKs

- cmd/codegen/generator/go/templates/src/enum.go.tmpl
- sdk/go/dagger.gen.go
Discovered while replying to https://discord.com/channels/707636530424053791/1179628240738975744/1179733881100959824:
> This depends on the above CacheSharingMode - the docs for what those all do are here: https://github.com/dagger/dagger/blob/main/core/schema/cache.graphqls#L4-L17
Not quite sure why these aren't documented in the sdk docs though, that's a bit odd and might be worth a bit of a dig (will take a look!)
Turns out we weren't outputting the comments for enums - these fields are populated, so we can add them in.
> fix: ensure go sdk generates docs for enum values

- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
We already fixed this *twice* with the arg types - but it can also occur in structs yay.
```go
type CustomType struct {
Foo, Bar string
}
```
See:
- https://github.com/dagger/dagger/pull/5972
- https://github.com/dagger/dagger/pull/6068
There definitely don't seem to be any more cases of us using `FieldList` though thankfull! :disappointed_relieved:
> fix: stop panic with packed struct fields in Go modules

- docs/current/cloud/572923-get-started.md
This commit adds a brief tip explaining how to see local runs in Dagger Cloud.
> docs: Added tip for local runs in Cloud doc

- core/container.go
Found while investigating #6163 (this isn't the root cause, but while attempting to reproduce this I had the idea to change `WithMountedDirectory` to use `llb.Readonly` - which causes the caching issue in #6163 to "go away").
This seems to have been introduced as an oversight in #5757 - we do use the `readonly bool` option in some places, so this should improve the performance of those operations.
Absolutely *no* idea how to test this :cry:
---
We were passing a boolean to indicate if mounted files/directories should be marked as read-only.
Note that this has caching implications! Content-based cache is *not* used for non-readonly directories.
> fix: ensure readonly option is correctly propagated

- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
- core/typedef.go
Depends on #6181 (also kiiiinda related to #6179)
This parses doc comments on top-level objects the same as we do for inline comments:
- Ensure that the comments are trimmed to not have spaces.
- Fallback to the line comment if no doc comment was found.
---
While doing this, I also found a bug that meant that the description for objects in the graphql API was being discarded and not appropriately set on the struct. And also found that we weren't even correctly detecting the struct comments from the go parser, from the commit message:
> Comments for go structs can either be attached to the TypeSpec, or the GenDecl - so we should fallback to the GenDecl doc comment if the TypeSpec does not have one.
> fix: parse struct comments same as inline opt structs

- cmd/codegen/generator/go/templates/modules.go
- cmd/codegen/generator/go/templates/modules_test.go
- core/integration/module_test.go
- core/integration/testdata/modules/go/minimal/main.go
Fixes https://github.com/dagger/dagger/issues/6162.
This allows defining defaults and optional parameters for Go modules using "dagger" pragmas. These are inspired in style by "go" pragmas.
Thankfully, this is actually a pretty simple patch, so we can bikeshed exact syntax - the earlier refactoring of opts through parsing args into paramSpecs makes this relatively simple to work with (also because of the way `baseType` and `paramType` are separated out, it's no extra effort to keep supporting the `Optional` generic as well, though I do think if this approach is successful, we might want to remove that at some point).
Personally, I think I prefer the more explicit `//dagger: default=abc` instead of `//+default abc`, but I also don't *realllly* have strong opinions on this. I've written the …
> feat: add go sdk pragma parsing for default and optional

- core/integration/remotecache_test.go
- engine/buildkit/filesync.go
- engine/sources/blob/blobsource.go
Fixes https://github.com/dagger/dagger/issues/6163 :tada: (cc @gerhard @marcosnils)
By prefixing the returned CacheKey with "session:" we activated the code path in buildkit that randomizes the digest to ensure that we don't get fast-cast hits (since session ids can be reused). See https://github.com/moby/buildkit/blob/06c971ffb4d3873207fe8ff7672026a718784060/solver/llbsolver/ops/source.go#L91-L94.
However, unlike LocalSources, BlobSources are not tied to a specific session (after initializing them), so we actually want to avoid this behavior.
With this change, digests aren't randomized, so we can get the fast-cache hits.
> fix: allow fast-cache hits on custom BlobSource

- sdk/python/src/dagger/_connection.py
Flagging `dagger.Connection` as legacy in favor of `dagger.connection`. I'll make an issue to update the site's docs.
> python: Update docs on the two available provisionable connections

- .changes/unreleased/Added-20231207-124744.yaml
- .changes/unreleased/Added-20231207-124852.yaml
- .changes/unreleased/Fixed-20231207-124611.yaml
In a few previous PRs, I'd forgotten to include relevant changelog entries - this patch includes those backdated entries.
Follow-ups from:
- #6034 
- #6211
- #6075
Sorry for not noticing this until now!
> chore: add my missing changelog entries

- internal/mage/cli.go
Closes https://github.com/dagger/nix/pull/4 via https://github.com/goreleaser/goreleaser/pull/4389
cc @sagikazarmark @RaitoBezarius @caarlos0
> ci: Bump GoReleaser to v1.22.1

- sdk/java/README.md
Extended the Java SDK documentation with the "Run pipeline with Dagger CLI" section.
It shows how to build the needed jars and the Dagger CLI command.
> docs: Java SDK Dagger CLI example

- core/schema/schema.go
Without this we're getting nil panics when using dagger shell.
Went unnoticed because we haven't added test coverage for dagger shell to the integ tests yet due to the fact that testing tty programs in our current testing setup is very non-obvious.
I will add whatever best test I can in a follow up to this PR, but sending the fix separately since it is quite trivial and probably an order of magnitude less time consuming than figuring out a test.
> core: set endpoint map when initializing APIServer

- cmd/dagger/shell.go
- core/integration/module_shell_test.go
- core/integration/module_test.go
- core/service.go
- core/shell.go
- engine/client/client.go
- go.mod
- go.sum
Main goal here was to add integ test coverage for dagger shell after missing a really straightforward nil panic as a result of not having coverage: https://github.com/dagger/dagger/pull/6240
We didn't have coverage before because integ testing TUI programs is not usually straightforward. The solution here uses the https://github.com/Netflix/go-expect library to drive the program and run some simple commands in an alpine shell and verify their output. It worked out reasonably well and based on local testing is not flaky. 
Along the way a few other problems were noticed+fixed (commits have details in message):
1. [shell: support shell from nested sessions](https://github.com/dagger/dagger/commit/63bd7ee01051b899ff7893d1f504005a5d95c9b4)
2. [core: fix goroutine leak in shell …
> Backfill integ tests for dagger shell + assorted fixes

- cmd/codegen/generator/go/templates/module_funcs.go
- cmd/codegen/generator/go/templates/module_objects.go
- cmd/codegen/generator/go/templates/module_types.go
- cmd/codegen/generator/go/templates/modules.go
This is a small-ish scale refactor that modifies the code we use to parse various types/functions/etc. in the go module codegen code. There should be no functional changes, just code refactor+cleanup.
The gist of the idea is that rather than having single methods that do both the type parsing and then return generated code for typedefs, we have a method that does the type parsing and then returns a type that implements an interface which has separate methods for getting the generated code and getting subtypes references by the type (with the possibility of adding more methods as needed, as is done in the interfaces work)
The main motivation is to support the interface work, where we need to use parsed type information for more than just codegen. Before this change I had just copy pasted …
> go: decouple type parsing from code generation in module

- core/integration/module_test.go
- core/schema/coremod.go
- core/schema/usermod.go
Fixes #6252 (the equivalent #6227, but for core types instead of user module types).
In #6167, it looks like we missed another `nil` check, which manifests as core module types not being set to their zero value but to an empty struct.
Additionally, it looks we regressed on #6057, and we weren't correctly converting field names back into the field names that the module requested. Thankfully, this is a pretty simple fix, and I've verified manually this works. I'm not quite sure of a test that can make this break neatly, since it didn't really (`encoding/json` "prefer[s] an exact match but also accept[s] a case-insensitive match").
> Fix various input normalization issues

- core/integration/module_test.go
- core/integration/testdata/modules/go/namespacing/main.go
- core/integration/testdata/modules/go/namespacing/sub2/main.go
- core/schema/schema.go
- core/schema/schema_test.go
This goes some way to fixing #6071 (@sipsma up to you if you want to leave it open for tracking the subpackage aspect, or splitting up core)
This allows a module "foo" to define it's own "FooContainer" type that won't be additionally namespaced into "FooFooContainer".
---
Previously, we skipped namespacing if the object was named the same as the module.
However, with this patch we can now additionally skip namespacing if the object if prefixed with the namespace.
> feat: skip namespacing when already prefixed

- engine/buildkit/filesync.go
This prevents a tiny visual glitch which is confusing in the TUI output where we get identical custom names.
I noted this in a debugging session with @marcosnils where we were seeing the same message in the TUI and in the cloud. Eventually, it would be nice to remove this, but adding this in at least helps to remove the visual confusion as to why there are duplicates.
> chore: prevent duplicate LLB names

- docs/current/cookbook/snippets/oci-annotations/index.mjs
- docs/current/cookbook/snippets/oci-annotations/main.go
- docs/current/cookbook/snippets/oci-annotations/main.py
This commit adds an example of using Docker mediatypes to the cookbook.
Ref Discord thread in https://discord.com/channels/707636530424053791/1179434337725337600/1180204397121241199
> docs: Adds note for Docker mediatypes in cookbook

- docs/current/cli/979595-reference.md
This commit updates the warning in the CLI reference to be more explicit.
> docs: Update CLI warning for hidden commands

- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
See https://github.com/dagger/dagger/issues/6272#issuecomment-1858003650:
https://github.com/dagger/dagger/commit/77760c2754575695f6a9329c79c4c6a2d6078a65#diff-42df7f581f0c9e41a3320a7be6c79027f0b373d77e57231d767b3539643a4da8L155-R152 modified the logic so that the following struct would be code-gened:
```go
type Foo struct {
X string
}
```
However, if `Foo` is not *reachable* from methods/fields on the main struct, then we should not include it on our code-gen and field declarations.
> fix: only add the main module object at the top-level

- cmd/codegen/generator/go/templates/module_funcs.go
- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
Oh look it's #6181 #5972 #6068 again (cc @vito *this* is the issue you sent me)
This behavior regressed in v0.9.4 (with #6181 lol).
Fields can have *zero* names - in which case we shouldn't accidentally discard the entire field, woops.
I've added a pretty comprehensive test for all these scenarios, getting very annoyed having to fix them all.
Also some other smallish related fixes I ran into while trying to get this working.
> More field manipulation in go

- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
Continuing my journey through the forest of a thousand go-sdk papercuts :tada: (sorry for all the small PRs, I figure they're easier to review and merge separately, and I'm just opening them as I find them and have time to fix them :cry:)
Previously, if two methods had the same name (but on different struct receivers), it was accidentally possible to confuse the two.
With this patch we now ensure that as well as matching the names, we also match the receiver name.
> fix: ensure declForFunc also matches receiver

- core/integration/module_shell_test.go
Saw while reviewing PRs that the TestModuleDaggerShell test was flaking sometimes specifically in the testdev workflow. Have never seen this flake in the other "normal" integ test workflow or locally.
From the logs I saw it looks like it is running as expected but just extremely slow, to the point that the generous timeouts weren't enough.
The testdev workflow is extra slow and overloaded for various unrelated reasons (doesn't actually run on the shared runner and doesn't have the same parallelism limits in the engine set).
Since I can't repro, this change is just an attempt at accounting for those tests being really extra slow. It:
1. Causes the Shell test to not run in parallel with the others, so it should be less bogged down by other noise.
2. Calls "functions" on the module first so …
> tests: run dagger shell test in isolation + pre-cached

- sdk/python/src/dagger/_engine/download.py
- sdk/python/tests/engine/test_download.py
Fixes https://github.com/dagger/dagger/issues/6265
I considered adding a file lock to the provisioning which would also prevent downloading the CLI multiple times, but it's not done in the other SDKs. Quick fix here is to just not complain if the file to remove doesn't exist anymore (race condition).
The synchronization primitive is not necessary to fix the issue but since I was looking at the Go implementation this matches it a bit more closely.
> Fix python provisioning test flakiness

- core/integration/module_test.go
- core/integration/testdata/modules/typescript/minimal/index.ts
- sdk/nodejs/entrypoint/entrypoint.ts
- sdk/nodejs/entrypoint/load.ts
- sdk/nodejs/entrypoint/register.ts
- sdk/nodejs/introspector/registry/registry.ts
- sdk/nodejs/introspector/test/registry.spec.ts
- sdk/nodejs/runtime/main.go
Fixes argOrder regexp when default arg is set.
Add test on overriding default arg on registry test. Set return type as optional when input type is void. 
Add tests for Typescript in `module_test.go`.
Fix ModuleRuntime to include codebase.
- This fixes the `dagger mod install` command
- This fixes using a module without `sdk` generated in the host.
Fix loading arg to handle array and strings.
Fix entrypoint to load parent state too.
Check for defined result.
Serialize fields that have identifiers.
Handle `void` return value with returnValue set to `"nul"`.
Related to DEV-3147
> feat: add tests for Node Typescript SDK

- .github/workflows/_hack_make.yml
- .github/workflows/engine-and-cli.yml
- core/pipeline/label.go
- core/pipeline/label_test.go
Fixes https://linear.app/dagger/issue/DEV-3086/pull-user-commit-message-in-a-context-pr
When collecting labels on the engine in a VCS context, sometimes, the commit head is an appended commit (from that VCS) [PR / MR]. This fix skips the merge request commit when it is the head.
Repro/test: https://gist.github.com/grouville/6cf442d86c41c0746bbef1812160e7c0
> Realization: only GitHub puts the PR in a detached HEAD with only the merge commit. GitLab keeps the git history of the branch being tested
After reviews + some testing, a few changes have been implemented:
1. Make sure that the main branch doesn't skip the merge commits. Only `pull_requests` shall be be impacted
2. Due to the realization, we need to fetch the branch and get the commits from there. However, this is an operation …
> fix: skip `head merge commits` on pull requests

- cmd/codegen/generator/go/templates/module_funcs.go
- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
- core/schema/usermod.go
Fixes https://github.com/dagger/dagger/issues/6286
Problem was that the parent value of a function call is sending the GraphQL cased field names instead of original names.
```python
from dagger import field, function, object_type
@object_type
class HelloWorld:
my_name: str = field(default="World")
@function
def message(self) -> str:
return f"Hello, {self.my_name}!"
```
So for the following query:
```graphql
{ 
helloWorld(myName: "Monde") { 
message 
} 
}
```
You got the output:
```console
Hello World!
```
Because the following call context was sent:
```python
{
"parent_name": "HelloWorld",
"parent_json": '{"greeting":"Hello","myName":"Monde"}',
"name": "message",
"input_args": "{}",
}
```
Expected `parent_json` to use `my_name` instead of `myName`, so it was ignored.
\cc @sipsma
> `FunctionCall.parent` doesn't return original field names

- .github/workflows/_hack_make.yml
this doesn't have any security implications since the token onyl has
access to send telemtry to cloud and cannot access any caching
resources. The cache access in our self-hosted runners is handled by the
`DAGGER_CLOUD_TOKEN` env var which is set at the runner level
> ci: bring back dagger cloud token so we have visibility

- examples/sdk/go/multistage/main.go
- examples/sdk/nodejs/multistage/build.js
- examples/sdk/python/multistage/pipeline.py
Follow up to https://github.com/dagger/dagger/pull/6280 for doc snippet updates.
> ⚠️ **Warning**
> To merge after or when the above is released.
> docs: Update docs on `withEntrypoint` usage 

- .github/workflows/publish.yml
- internal/mage/cli.go
This is attempt numero due to fix Nix package publishing to dagger/nix.
https://github.com/dagger/dagger/pull/6063 added Nix to the GitHub Actions workflow, but GoReleaser actually runs in Dagger using a GoReleaser Pro image.
This PR removes Nix from the GHA workflow and adds Nix to the GoReleaser image.
(Reminder: we only need `nix-prefetch-url` for GoReleaser to work, but it's not bundled with their image and installing Nix from the Alpine package repo seems to be the easiest way to get `nix-prefetch-url`)
> Fix Nix publishing

- core/integration/module_test.go
- core/integration/testdata/modules/typescript/syntax/index.ts
- sdk/nodejs/entrypoint/load.ts
- sdk/nodejs/introspector/scanner/utils.ts
Example:
```ts
function hello(msg = 'hey') {}
```
> fix: supports single quote default argument

- core/integration/container_test.go
- core/schema/container.go
- core/schema/container.graphqls
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/go/dagger.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
This implements my suggestion from https://github.com/dagger/dagger/pull/6280#issuecomment-1864269265.
`withoutEntrypoint` also modifies the entrypoint, and so should follow the same style and reset the default args (allowing toggling this behavior in the same way as `withEntrypoint`).
> feat: make withoutEntrypoint clear default args as well

- internal/mage/cli.go
Fixes https://github.com/dagger/dagger/pull/6245#issuecomment-1866175753 (cc @sagikazarmark)
The apk package for nix is only available in alpine:edge atm, and goreleaser does not use alpine:edge.
So, we can install it using the same method we were previously using in github actions - the logic is borrowed from https://github.com/cachix/install-nix-action/blob/master/install-nix.sh#L76 and https://github.com/cachix/install-nix-action/blob/master/install-nix.sh#L104.
> fix: install nix using script

- cmd/dagger/flags.go
- cmd/dagger/functions.go
- core/integration/module_test.go
Private tracker related issue: https://linear.app/dagger/issue/DEV-2944/cli-pass-secret-arguments-by-name-not-by-value
This PR changes how secrets are passed as args in the dagger CLI.
Whereas previously a function arg of type `Secret` was passed in the cli by plaintext, now secrets are passed on by specifying a source of the secret. This is intended to be much more secure and convenient to users.
This PR adds support for:
* `env:MY_TOKEN` - read the secret from the env var `MY_TOKEN`
* `file:/path/to/some/file` - read the secret from the file at path `/path/to/some/file`
* `cmd:'some-command that outputs secret to stdout'`
* `MY_TOKEN` - a shorthand convenience for `env:MY_TOKEN`
(taken from the test case included here in the PR)
Module code (highly silly, just meant to show off the …
> CLI: support secrets args by source rather than by plaintext

- docs/netlify.toml
Noticed by @gerhard during the v0.9.5 release:
> Noticed that the https://docs.dagger.io/current/sdk/nodejs/reference/modules/api_client_gen link is now broken, most likely after the Docusaurus v3.0 refactoring. The links comes from https://github.com/dagger/dagger/releases/tag/sdk%2Fnodejs%2Fv0.9.5
In #6311, I've fixed the docs link for future releases, but we should add a redirect for previous changelogs. It looks like the location for the page was changed during #6164.
> docs: add redirect for old nodejs sdk location

- core/modules/resolver.go
- sdk/python/runtime/main.go
By specifying the digest of images pulled by the core, we save network back-and-forth, which helps with performance especially on slow internet links.
> Pin images by digest for performance

- sdk/java/dagger-codegen-maven-plugin/src/main/resources/schemas/schema-0.9.4.json
- sdk/java/dagger-codegen-maven-plugin/src/main/resources/schemas/schema-0.9.5.json
Add generated java sdk schema for engine versions 0.9.4 and 0.9.5.
> feat: add Java API schema for dagger 0.9.4 and 0.9.5

- .changes/unreleased/Fixed-20240104-003032.yaml
- cmd/shim/main.go
Fixes https://github.com/dagger/dagger/issues/6266.
When an unknown command is executed, the returned error is `*exec.Error`.
Example code (Go playground: https://go.dev/play/p/ybni3fJpo46): 
```go
package main
import (
"log"
"os/exec"
)
func main() {
if err := exec.Command("foobar").Run(); err != nil {
log.Printf("%T: %+v", err, err)
}
if err := exec.Command("false").Run(); err != nil {
log.Printf("%T: %+v", err, err)
}
}
```
Output:
```
2009/11/10 23:00:00 *exec.Error: exec: "foobar": executable file not found in $PATH
2009/11/10 23:00:00 *exec.ExitError: exit status 1
```
```
./bin/dagger run --focus go run ./cmd/6266/main.go
✘ sync ERROR [1.02s]
✘ exec foobar ERROR [0.13s]
┃ panic: exec: "foobar": executable file not found in $PATH goroutine 1 [running, locked to thread]:
┃ …
```
> fix(cmd/shim): fix panic when exec-ing an unknown command

- sdk/java/.mvn/wrapper/maven-wrapper.properties
Upgrade Maven to get rid of validation issues from an old maven version.
```bash
[WARNING]  Plugin validation issues were detected in 1 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-plugin-plugin:3.7.1
[WARNING]   Declared at location(s):
[WARNING]    * org.apache.maven:maven-core:3.9.2:default-lifecycle-bindings @ line -1
[WARNING]   Used in module(s):
[WARNING]    * io.dagger:dagger-codegen-maven-plugin:1.0.0-SNAPSHOT (dagger-codegen-maven-plugin/pom.xml)
```
> feat: Java SDK upgrade maven to 3.9.6

- .changes/unreleased/Breaking-20231215-120318.yaml
- ci/main.go
- cmd/codegen/generator/nodejs/templates/functions_test.go
- core/integration/container_test.go
- core/integration/services_test.go
- core/schema/container.go
- core/schema/container.graphqls
- docs/current_docs/guides/snippets/aws-codebuild-codepipeline/index.mjs
- docs/current_docs/guides/snippets/aws-codebuild-codepipeline/main.go
- docs/current_docs/guides/snippets/aws-codebuild-codepipeline/main.py
- docs/current_docs/guides/snippets/replace-dockerfile/index.mjs
- docs/current_docs/guides/snippets/replace-dockerfile/main.go
- docs/current_docs/guides/snippets/replace-dockerfile/main.py
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/go/dagger.gen.go
- sdk/nodejs/api/client.gen.ts
- sdk/python/dev/src/main/utils.py
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
Fixes https://github.com/dagger/dagger/issues/6051
The `args` field of `Container.withDefaultArgs` is no longer optional:
```diff
- ctr = ctr.WithDefaultArgs(ContainerWithDefaultArgsOpts{Args: []string{"foo"}})
+ ctr = ctr.WithDefaultArgs([]string{"foo"})
```
To unset:
```diff
- ctr = ctr.WithDefaultArgs([]string{})
+ ctr = ctr.WithoutDefaultArgs() 
```
This also works (in practice) but it will set `CMD` to `[]` rather than truly unsetting:
```go
ctr = ctr.WithDefaultArgs([]string{}) 
```
This breaks all current `withDefaultArgs` usage, in all SDKs since it's a core change.
> BREAKING: Make default args parameter required 

- engine/cache/manager.go
Somehow ImmutableRefs can be nil - not 100% sure how this happens, but upstream buildkit does include checks in appropriate places for this case. We should probably do the same as well.
Should hopefully mitigate https://github.com/dagger/dagger/issues/6379.
> fix: skip nil cache result

- sdk/rust/crates/dagger-sdk/tests/mod.rs
Remove the flaky test, as it turns out, if you're unauthenticated and trying to pull an invalid image, you can get rate limited. It is too much of a bother to actually setup authentication for this kind of a test, as such I am just removing it.
Fixes: https://github.com/dagger/dagger/issues/6304
> fix(rust-sdk): remove flaky test

- go.mod
- go.sum
This mitigates GHSA-9763-4f94-gfch, and fixes the failing scan engine job on `main`: https://github.com/dagger/dagger/actions/runs/7460295076/job/20298322166#step:3:307.
`github.com/cloudflare/circl` is required by `go-git`:
$ go mod why -m github.com/cloudflare/circl
github.com/dagger/dagger/cmd/dagger
github.com/go-git/go-git/v5
github.com/ProtonMail/go-crypto/openpgp
github.com/ProtonMail/go-crypto/openpgp/internal/ecc
github.com/cloudflare/circl/dh/x25519
> deps: update cloudflare/circl to v1.3.7

- cmd/codegen/generator/go/templates/module_interfaces.go
- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_iface_test.go
Fixes I wrote while playing around with interfaces introduced in #6213.
The first patch makes sure that the context name is fixed to `ctx` regardless of what the interface specifies it as - this is because the context is special, and the code in the defined function below requires it to be set to `ctx`.
The second patch is a rework of https://github.com/dagger/dagger/pull/6282, to ensure that it also works with interfaces (there's a weird case we can get where we generate the function cases, but don't do the struct codegen so we reference but don't actually create the concrete `impl`). Essentially, we should traverse the tree starting *only* at the top-level and work down from there. See https://github.com/dagger/dagger/pull/6282#discussion_r1446200476 for why the previous patch is …
> Various interface fixes

- go.mod
- go.sum
- internal/mage/util/engine.go
Diffs:
- https://github.com/opencontainers/runc/compare/v1.1.9...v1.1.11
- https://github.com/opencontainers/runc/releases/tag/v1.1.10
- https://github.com/opencontainers/runc/releases/tag/v1.1.11
- https://github.com/containerd/containerd/compare/v1.7.8...v1.7.11
- https://github.com/containerd/containerd/releases/tag/v1.7.9
- https://github.com/containerd/containerd/releases/tag/v1.7.10
- https://github.com/containerd/containerd/releases/tag/v1.7.11
I started by bumping containerd (to avoid GHSA-7ww5-4wqc-m92c), and figured we could take runc updates at the same time.
The most recent containerd updates include some OTEL bumps, but note that we can't actually take advantage of this until we bump buildkit as well, which we can't do until we can upgrade buildkit (blocked till we can fix …
> deps: update containerd to v1.7.11

- .changes/unreleased/Fixed-20240111-113705.yaml
- core/schema/schema.go
Fixes a potential concurrency issue introduced in https://github.com/dagger/dagger/pull/6167 - it looks like during the lock refactors, we missed a couple cases.
In a past testdev run (https://github.com/dagger/dagger/actions/runs/7459047868/job/20294230186), the tests failed with:
fatal error: concurrent map read and map write
goroutine 569315 [running]:
github.com/dagger/dagger/core/schema.(*APIServer).ServeHTTP(0xc0197f3900, {0x1f9c9a0, 0xc0100aa460}, 0xc00eed5800)
/app/core/schema/schema.go:171 +0x119
github.com/dagger/dagger/engine/server.(*DaggerServer).ServeClientConn.(*DaggerServer).HTTPHandlerForClient.func4({0x1f9c9a0, 0xc0100aa460}, 0xc0348b3660?)
/app/engine/server/server.go:211 +0x219
net/http.HandlerFunc.ServeHTTP(0x410805?, {0x1f9c9a0?, 0xc0100aa460?}, 0xc0100aa401?) …
> fix: protect against concurrent map access in APIServer

- docs/current_docs/cloud/snippets/get-started/ci/circle.yml
Stopping the engine regardless of build status is a recommended best practice to make sure cache is always uploaded.
> Update circle.yml Example

- sdk/rust/Cargo.lock
- sdk/rust/Cargo.toml
- sdk/rust/crates/dagger-bootstrap/Cargo.toml
- sdk/rust/crates/dagger-codegen/Cargo.toml
- sdk/rust/crates/dagger-codegen/src/lib.rs
- sdk/rust/crates/dagger-codegen/src/rust/mod.rs
- sdk/rust/crates/dagger-sdk/Cargo.toml
- sdk/rust/crates/dagger-sdk/src/lib.rs
It has been a while. But here are some updates to some dependencies. The update to the version should also include some quite major improvements I didn't release in December. Such as better support for lifetimes in rust. 
Also did some minor refactoring with the dependencies, and moved them and the versions to the main `Cargo.toml`, this should make it easier in the future to bump the version, as well as holistically update dependencies.
> chore(rust-sdk): update-dependency and version

- cmd/dagger/functions.go
- cmd/dagger/module.go
- core/integration/module_functions_test.go
`dagger functions` dumps all functions available in all types for a given module, regardless of arguments. So I can't see what functions are available at a given stage of the pipeline.
Example:
```console
$ dagger -s -m github.com/shykes/daggerverse/wolfi functions
object name                                                         function name   description                                    return type
*Wolfi                                                              base            Initialize a Wolfi base configuration          WolfiConfig!
WolfiConfig                                                         packages                                                       [String!]!
WolfiConfig                                                         overlays …
```
> Improve "dagger functions"

- cmd/dagger/flags.go
- core/integration/module_call_test.go
- core/service.go
- core/services.go
- core/services_test.go
Before this, services provided as CLI flag values were not automatically started, so user module code needed to explicitly start them (or implicitly start them via a service binding), which is somewhat surprising and boilerplatey since there's not really any cases where a user wouldn't want the host service to already be running. This is debatable though.
Now, the CLI calls start on host services provided as flag args.
In order for this to work, there was also a change needed in the internal services implementation to key services by the ServerID rather than ClientID. The difference is that now the state of a service is shared across a whole session, which includes the CLI and all modules it invokes (directly or transitively). Otherwise even if the CLI auto starts the service it will …
> services: key services by server id; auto start cli service flags

- core/directory.go
- core/integration/directory_test.go
Hit a case where files weren't being deleted while working on dagger.json changes and thought I had completely lost my mind for a bit, but turns out it's just a bug that's existed since the beginning of time apparently 😮‍💨
> core: fix Directory.withoutFile to account for subdir

- core/integration/module_test.go
- core/integration/testdata/modules/typescript/minimal/index.ts
- sdk/typescript/entrypoint/entrypoint.ts
- sdk/typescript/entrypoint/load.ts
- sdk/typescript/entrypoint/register.ts
- sdk/typescript/introspector/test/scan.spec.ts
- sdk/typescript/introspector/test/testdata/optionalParameter/optionalParameter.ts
Correctly load type argument prior to value to correctly serialize it. 
Fix Quickstart issue found by @d3rp3tt3 (https://discord.com/channels/707636530424053791/1120503349599543376/1195178137101799474).
```shell
➜  ci git:(main) ✗ dagger call hello-world --count 10 --mashed
✔ dagger call hello-world [2.34s]
┃ Hello world, I have mashed 10 potatoes                                                                                                         
• Engine: c7de3eb13d57 (version devel ())
⧗ 27.72s ✔ 309 ∅ 39
```
```shell
➜  ci git:(main) ✗ dagger call hello-world --count 10         
✔ dagger call hello-world [2.42s]
┃ Hello world, I have 10 potatoes                                                                                                                
• Engine: c7de3eb13d57 …
```
> fix(typescriptSDK): fix loading type argument

- cmd/dagger/flags.go
- core/integration/module_call_test.go
This avoids a possible credential leak, in case the user accidentally passes the env variable instead of its name. This is particularly likely because until very recently, that's exactly what we told users to do. So there is a real risk of leaks for early adopters, which this change mitigates.
> Don't print the full env var name in error message.

- sdk/python/src/dagger/mod/_resolver.py
- sdk/python/tests/modules/test_registration.py
I split this off a larger WIP PR for adding a bunch more tests to Python modules.
There was a regression when adding constructor support where function descriptions from docstrings were no longer being registered. Noticed on `dagger call --help`.
> fix(python): Fix missing description from functions

- core/integration/module_test.go
- sdk/typescript/api/test/api.spec.ts
- sdk/typescript/entrypoint/entrypoint.ts
- sdk/typescript/entrypoint/invoke.ts
- sdk/typescript/entrypoint/load.ts
- sdk/typescript/entrypoint/register.ts
- sdk/typescript/introspector/registry/registry.ts
- sdk/typescript/introspector/scanner/scan.ts
- sdk/typescript/introspector/scanner/typeDefs.ts
- sdk/typescript/introspector/test/invoke.spec.ts
- sdk/typescript/introspector/test/registry.spec.ts
- sdk/typescript/introspector/test/scan.spec.ts
- sdk/typescript/introspector/test/testdata/multiArgs/index.ts
- sdk/typescript/introspector/test/testdata/state/state.ts
Updates entrypoint loading by:
- Loading args type in constructor
Fixes argument loading by:
- Correctly serializing input and parentJSON
- Fixing loadArg to correctly supports list
- Fixing loadArg to load object with ID only
- Refactor load to avoid repetition
Update invoke to:
- Order argument
- Load values, state and result
Update loader to:
- Load arguments order
- Load result
- Adapt to new scanResult data structure
Update scanner to:
- Use a new data structure based on object instead of arrays to increase
performances and maintainability on `ScanResult`.
- Scan non-exposed field
- Add `isExposed` property to `FieldTypeDef`
Update register to:
- Only register exposed field to Dagger API
- Use new data structure scanResult
- Correctly assigning constructor if there's
*Additional …
> feat(tsSDK): fix constructor registration

- sdk/typescript/tsconfig.json
It seems like https://github.com/dagger/dagger/actions/runs/7586336084/job/20664474209 was broken, due to changes in https://github.com/dagger/dagger/pull/6433/files#diff-dd39eea8d6cc5b9f8f7a2c9645c31136dbef40ad6f79b5d3860fac8bbae44ce9.
See https://docs.npmjs.com/cli/v10/commands/npm-publish#files-included-in-package for more info.
> Add npm ignore for typescript

- sdk/typescript/.changes/unreleased/Fixed-20240122-140126.yaml
- sdk/typescript/package.json
Javascript projects were broken because `typescript` became a required import from [0.9.6](https://github.com/dagger/dagger/releases/tag/sdk%2Ftypescript%2Fv0.9.6) with `scan.js` importing it.
Currently, if you try to run a JS project, you'll get the following error:
```shell
┃ node:internal/modules/esm/resolve:844                                                                                                              
┃   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);                                                                          
┃         ^                                                                                                                                          
┃ …
```
> fix: include typescript in pkg dependencies

- core/integration/module_test.go
- core/integration/testdata/modules/typescript/id/arg/index.ts
- core/integration/testdata/modules/typescript/id/field/index.ts
- core/integration/testdata/modules/typescript/id/fn/index.ts
- sdk/typescript/entrypoint/load.ts
- sdk/typescript/introspector/registry/registry.ts
- sdk/typescript/introspector/test/registry.spec.ts
- Add integration tests for constructors
- Add `Unwrap` test case
- Add `lotOfFunction` test case
- Add `ReservedWord` test case
- Add `TestModuleArgOwnType` case
- Add `IDableType` case
- Add dependencies cases
- Add `ReturnCompositeCore` case
- Add `ReturnComplexThing` case
- Add `GlobalVarDAG` case
- Add `PrivateField` case
- Add `CustomTypes` case
- Add `ReturnTypeDetection` case
- Add `ReturnObject` case
- Add `NestedObject` case
*Additional notes*
- Remove inline Eslint nolint instruction in favor of file's scope instruction
- Fixes an issue with `loadArg` when `value` is `undefined`.
Fixes DEV-3323
Fixes DEV-3324
> test(tsSDK): add integration test

- internal/mage/sdk/elixir.go
- internal/mage/sdk/go.go
- internal/mage/sdk/php.go
- internal/mage/sdk/rust.go
- internal/mage/sdk/typescript.go
Use dagger secrets for concealing secrets in SDK publish steps.
> ci: use dagger secrets during sdk publish steps

- engine/server/buildkitcontroller.go
We should avoid holding the server map lock for any long period of time. This should help to prevent a total deadlock in the case where a rogue server holds the lock for too long during shutdown (for currently unknown reasons).
By reducing our usage of the global map lock to only simple operations that won't block, we ensure that this rogue server doesn't block every operation on the controller.
However, because of this refactor, we need to introduce a more precise per-server-id lock. This lock is used to prevent multiple incoming session requests from spawning multiple servers for the same ID in parallel.
> fix: avoid holding server map lock

- engine/cache/manager.go
Before this, if there was an error when synchronously importing layer cache at engine start, the engine failed to start entirely. Now, the engine will continue running with just the local cache and retry import periodically in the background.
Additionally, that initial synchronous import did not have a timeout previously. It now has a timeout of 1 minute. If that's hit, then the above logic kicks in to gracefully handle the error.
> cache: make first synchronous import non-fatal and timed out.

- sdk/elixir/.gitattributes
- sdk/php/.gitattributes
Follow up to #6447 as I've noticed PHP and Elixir generated files still show in diffs.
Tested with [linguist](https://daggerverse.dev/mod/github.com/helderco/daggerverse/linguist@2b3439af53ac0232a39b3589dc65bf3fb171c2e4#Linguist.run):
> Fix linguist mark in php in elixir codegen

- core/integration/module_test.go
- core/module.go
- core/schema/module.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/module.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Module.php
- sdk/python/dev/src/main/__init__.py
- sdk/python/src/dagger/client/gen.py
- sdk/python/src/dagger/mod/_module.py
- sdk/python/src/dagger/mod/cli.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
We had a `Module.description` field in the schema but no way of populating it. Rather than make the main object's description the module description, we can cleanly separate those two in the SDKs. The consumer can, for example, default to the main object's description if there's no module description.
Only Python supports this for now.
Module authors simply add a [docstring to the top](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) of their `src/main.py` module (or `src/main/__init__.py` package):
```python
"""My Foo module's description."""
from dagger import object_type
@object_type
class Foo:
"""My Foo object's description."""
```
Now, from a module dir we can inspect the description from the API:
\cc @grouville @jpadams
> Add field to populate a module's description

- engine/server/buildkitcontroller.go
It's the deadlock that keeps on giving :tada:
- Bumped up some log levels from `trace` to `debug` to hopefully provide some more useful info
- Fix the really annoying `level=error msg="session call failed" ... error="wait: handleConn: %!w(<nil>)"`. We should only wrap with `fmt.Errorf` if we *actually* got an error.
> Some minor session log fixes in buildkitcontroller

- cmd/codegen/codegen.go
- cmd/codegen/main.go
- cmd/dagger/engine.go
- cmd/dagger/module.go
- cmd/shim/main.go
- core/integration/directory_test.go
- core/modfunc.go
- core/query.go
- core/schema/schema.go
- core/schema/sdk.go
- core/service.go
- dagql/idproto/id.go
- engine/buildkit/client.go
- engine/buildkit/progrock.go
- engine/client/client.go
- engine/server/buildkitcontroller.go
- engine/server/server.go
- go.mod
- go.sum
- internal/mage/docs.go
- internal/mage/sdk/go.go
- internal/mage/sdk/python.go
- internal/mage/sdk/rust.go
- internal/mage/sdk/typescript.go
- internal/mage/util/generated.go
- tracing/graphql.go
These are the necessary changes for the Zenith visualization experiments I've been working on. I figure we can sneak these out even if we don't have anything that uses them yet, just to have the ability to record a journal file and test the new UI/TUI against it.
The only real change is that Progrock now supports parent/child vertex relationships, which are analogous to parent/child spans in OpenTelemetry. The DagQL telemetry now uses this instead of the weird group-that's-really-a-vertex from before, which was also contributing to a lot of noisy output. Now when a resolver performs a self-call or runs something with Buildkit, the resulting vertices will be children of the calling vertex.
Most of the effort is just getting the parent vertex ID plumbed through all the right places for …
> propagate progrock parents

- cmd/dagger/call.go
- core/integration/module_call_test.go
- core/integration/module_test.go
Fixes #6359 
Added `--json` option.
Need to detect a scalar typedef, to exclude printing any ID. To limit that just to sync, an alternative is to check last selection in the query builder, but need to expose `q.name()`. Another alternative is to disallow selecting `sync` explicitly in favor of ending the chain in the core type. Could also generalize by activating the convenience to all types that support `sync` instead of explicitly the 3 mages.
I suggest splitting the arbitrary user objects in another issue/PR. We need changes in the query builder to allow selecting siblings.
> cli: Use more generic default output for core types in dagger call

- docs/docusaurus.config.js
This commit changes the target URL to dagger.io for clicks on the navbar logo on docs.dagger.io.
> docs: Changes logo URL

- .github/workflows/_hack_make.yml
- internal/mage/engine.go
As discussed this morning :tada:
We can have a dedicated starting engine step, which will connect to the engine, start a session, and immediately disconnect.
If the engine isn't already started, this starts it! In the future, we can use honeycomb and more quickly identify issues with too many cache volumes, etc.
> ci: split out starting engine step

- core/container.go
- core/integration/container_test.go
Previously, 0o600 was to narrow to allow non-root users to use withExec with stdin. The command silently exited without being executed.
Fixes #6510
> fix: allow non-root users to use withExec with stdin

- core/integration/container_test.go
- core/integration/module_call_test.go
- core/integration/module_functions_test.go
- core/integration/module_test.go
We should avoid calling Parallel in a sub-test *after* creating a client, since it can block for a completely indeterminate amount of time, and in that time, we can end up with a huge number of just unused clients.
Not only is this (really only a) little wasteful, it makes stack traces and dumps in the case of test timeout very hard to decipher. Are we waiting for a client because it got deadlocked? Or because it was open since the beginning of the test run.
We do this in two ways:
- Moving client initialization to right below the deepest `t.Parallel` call
- Removing instances of `t.Parallel` from calls that we do not expect to take very long
> chore: create test client at lowest Parallel level

- docs/versioned_docs/version-zenith/user/quickstart/623939-call.mdx
I think the command has to come after the `-m` flag.  When it comes before dagger can't find the module... most other places (for instance in the bottom tip)  the command is after the module flag.
>This is a tiny update, but it cost me at least 10 minutes before I found another example with them flipped and then mine started working locally.  Hope it saves someone else a few minutes!
> docs(command order)

- cmd/dagger/call.go
- cmd/dagger/main.go
This is only for next release to help users transition. Should be removed at the latest on the official modules release.
When using one of the removed commands:
- dagger download
- dagger shell
- dagger up
User is presented with an error message referencing the new one, under dagger call.
> CLI: Bring back removed CLI commands to help transition

- internal/mage/sdk/elixir.go
- internal/mage/sdk/go.go
- internal/mage/sdk/java.go
- internal/mage/sdk/php.go
- internal/mage/sdk/python.go
- internal/mage/sdk/rust.go
- internal/mage/sdk/typescript.go
Follow-up to #6463 (and related to #6488)
This PR introduces `DRY_RUN` to all SDK publish mage jobs, allowing any of them to be run and tested locally.
- Adds `DRY_RUN` to python, go, typescript and php
- Renames `HEX_DRY_RUN` to `DRY_RUN` for elixir
- Renames `CARGO_PUBLISH_DRYRUN` to `DRY_RUN` for rust
- Renames `MVN_DEPLOY_DRY_RUN` to `DRY_RUN` for java
The idea is to prevent issues like #6464 from appearing only during the release process, and instead to show up as soon as possible.
> ci: add dry-run targets for SDK publishing

- cmd/dagger/call.go
- cmd/dagger/flags.go
- cmd/dagger/functions.go
- core/integration/module_call_test.go
Fixes https://github.com/dagger/dagger/issues/6409
Prior to this PR, attempting to run a module that takes a CacheVolume in its constructor (or likely also any function) would fail with this:
```
Error: unsupported object type "CacheVolume" for flag: mod-cache 
```
The flag value is just the cache volume name. Can't think of an immediate reason for it to be any more complicated than that.
> support passing cache volumes as flag

- cmd/dagger/call.go
https://github.com/dagger/dagger/pull/6520 added a new `// nolint` comment, and it seems like CI didn't rerun after #6531 was merged.
> chore: appease nolintlint

- cmd/codegen/codegen.go
- cmd/codegen/main.go
- cmd/shim/main.go
- core/schema/schema.go
- core/schema/sdk.go
- core/service.go
- engine/buildkit/client.go
- engine/buildkit/progrock.go
- engine/client/client.go
- engine/server/buildkitcontroller.go
- engine/server/server.go
- go.mod
- go.sum
Reverts part of #6456 
Turns out this is still needed by legacy Dagger (`dagger run`, `go run` + auto-started `dagger session`, etc).
It's unfortunate to bring all this plumbing back but we obviously can't break that yet.
Kept everything as-is, including propagating parents, because #6505 prevents the cache-busting issue that we originally ripped all this out to avoid.
This reverts commit 3309a8e799e1f4d66506bdc5e540613ae4bab90a.
> Revert "rip out progrock socket plumbing"

- engine/buildkit/client.go
- engine/buildkit/progrock.go
- engine/server/server.go
The idea behind this PR is to attach the JSON representation of the underlying LLB to each vertex in the progress output. This data should be available to be ingested by the cloud service, so it can be used for better visualizations.
This piece is just the client-side part. To see an example, you can use `_EXPERIMENTAL_DAGGER_PROGROCK_JOURNAL`:
```
$ _EXPERIMENTAL_DAGGER_PROGROCK_JOURNAL=/tmp/progrock.json dagger call -m github.com/jedevc/daggerverse/hugo build --target git@github.com:gohugoio/hugoBasicExample#master
$ cat /tmp/progrock.json | grep "exec hugo" | jq
```
```json
...
{
"id": "sha256:2efaca543d1aae0cbfa350f05d048d9f3ed9149cb11482cc09cf5c73af2a7da8",
"name": "exec hugo --gc --cacheDir /cache --destination /dest",
"inputs": [ …
```
> feat: add llb to progress output

- docs/versioned_docs/version-zenith/developer/go/191108-advanced-programming.mdx
- docs/versioned_docs/version-zenith/developer/go/457202-test-build-publish.mdx
- docs/versioned_docs/version-zenith/developer/go/525021-quickstart.mdx
- docs/versioned_docs/version-zenith/developer/go/snippets/advanced-programming/constructor/main.go
- docs/versioned_docs/version-zenith/developer/go/snippets/quickstart/trivy/main.go
- docs/versioned_docs/version-zenith/developer/go/snippets/test-build-publish/step6/main.go
- docs/versioned_docs/version-zenith/developer/python/419481-quickstart.mdx
- docs/versioned_docs/version-zenith/developer/python/539756-advanced-programming.mdx
- docs/versioned_docs/version-zenith/developer/typescript/506316-quickstart.mdx
The most important updates here are in anticipation of breaking changes in the next release. There are also some more opinionated cleanups, but for now just leaving the overall structure the same.
The big breaking changes to adapt for are:
1. `dagger mod init/install/etc.` moving to be right under `dagger`
2. `dagger up` replaced by chainable `dagger call ... up`
3. `dag.Host()` being replaced with `dag.CurrentModule().Source()`
The more opinionated tweaks are:
1. Don't use raw graphql queries, only use `dagger call`
2. In Go, avoid use of `Optional` and instead center on `//+optional` and `//+default` pragmas.
One important note: the moving of `dagger mod init/install/etc.` has not been merged yet ([PR here](https://github.com/dagger/dagger/pull/6533)), so depending on how the timing …
> Update zenith dev guides with incoming breaking changes.

- core/modulesource.go
Since `Subpath` always starts with `/`, and its default value is `/`, we're currently always adding an extra `/` between the source path and the subpath. (Amusingly it looks a lot like v2 refs #6187.)
> fix up ModuleSource.asString displaying `//`

- go.mod
- go.sum
- internal/mage/util/engine.go
Our vulnerability scans started failing due to the CVE in v1.1.11, this updates to the latest release.
> update runc to v1.1.12

- core/integration/module_test.go
- core/module.go
- core/schema/sdk.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/module.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Module.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
The recent updates accidentally left in dag.Select calls that referred to old APIs in the codepath for custom (i.e. 3rd party) SDKs. We didn't catch this because we didn't have any integ tests for this feature.
This fixes the bug and adds an integ test. It also required exposing Module.Runtime as a graphql field in order to write the test case, but that seems like it will only be beneficial in general to any other SDK authors trying to do something similar to this.
> core: fix support for custom SDK modules

- .changes/unreleased/Breaking-20240131-225025.yaml
- cmd/codegen/introspection/introspection.go
- core/integration/module_test.go
- core/moddeps.go
- core/module.go
- core/schema/schema.go
- core/schema/sdk.go
- dagql/types.go
(using go syntax below, but same idea applies to all SDKs)
Previously, module containers set their working directory to the directory containing the module's source code. You could then read files from that directory with calls like `dag.Host().File("./some/file.txt")`.
Now, module containers are set to an initially empty scratch directory, so those calls will not work anymore.
To use files/directories from the module source code, you can instead:
1. Directories - `dag.CurrentModule().Source().Directory("some/subdir")`
2. Files - `dag.CurrentModule().Source().File("some/file.txt")`
Additionally, it used to technically be possible to use files/directories from anywhere in the root dir loaded for a module in the case where `"root"` was configured in `dagger.json`. This is no longer …
> Remove Host API from module SDK codegen.

- cmd/dagger/cloud.go
- cmd/dagger/functions.go
- cmd/dagger/main.go
- cmd/dagger/module.go
- cmd/dagger/query.go
- cmd/dagger/run.go
Fixes #6358
Putting individual improvements in separate commits.
Notice in the example below that if we follow #6516 and keep the first line of API descriptions up to 50 chars, that'll be short of the end of the line below "EXPERIMENTAL". Meaning that it won't wrap on this screen size.
Not all of these are focused on the core API, most impactful is the wrapping on flags and commands. I’m submitting what I have now to be cut in next release but will continue in a separate PR for general `--help` improvements.
Taking an example of a function returning a `dagger.Container` which has a lot of functions.
- **Before:** https://app.warp.dev/block/1W5uEInSvPgnwJ4dN9iC9f
- **After:** https://app.warp.dev/block/KwLaq1XtV6T19lA8M2UQle
> CLI: Improve display of core API in `--help`

- docs/current_docs/faq.mdx
- docs/current_docs/guides/294022-telemetry.mdx
- docs/versioned_docs/version-zenith/faq.mdx
This commit adds FAQ entries/a guide for Dagger telemetry. 
Note: For `zenith` version docs, all the relevant information is placed in the FAQ since we don't yet have a "Guides" section for that version (will be added in #6504)
> docs: Adds telemetry FAQ

- sdk/rust/Cargo.lock
- sdk/rust/Cargo.toml
Finally basing main versions of, of the engine. Still need to integrate the releaser.
> chore(rust-sdk): with rust 0.9.8

- core/integration/git_test.go
- core/schema/git.go
- docs/docs-graphql/schema.graphqls
- engine/sources/gitdns/gitsource.go
- sdk/elixir/lib/dagger/gen/git_repository.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/GitRepository.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-codegen/src/rust/functions.rs
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Fix #6375.
As suggested by @sagikazarmark, it feels odd to put `refs/pull/5/merge` and similar into a `commit`/`branch`/`tag` selection - it's a ref, so we should have a generic `ref` selection.
To handle the rust codegen case, we need to do some magic since `ref` is a [strict keyword](https://doc.rust-lang.org/reference/keywords.html#strict-keywords). We can resolve this using a [raw identifier](https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html). @dagger/sdk-rust I've hacked something in to get the codegen to work, but let me know if you want to take a different approach.
---
In general, it's a little bit strange that we have so many functions that all have exactly the same underlying implementation - e.g. you can put a commit ID in a `branch` and it works …
> feat: add git ref graphql field

- engine/client/client.go
A super weird find (I think this was introduced recently?)
https://github.com/dagger/dagger.io/actions/runs/7756389308/job/21153589598?pr=3359#step:4:2365
```
24: exec go test ./cmd/ci/ -v -timeout=30m
24: [244.0s] 2024/02/02 13:12:31 http: panic serving 127.0.0.1:42432: context canceled
24: [244.0s] goroutine 863 [running]:
24: [244.0s] net/http.(*conn).serve.func1()
24: [244.0s] 	/usr/local/go/src/net/http/server.go:1868 +0xb9
24: [244.0s] panic({0xfcadc0?, 0x1b79170?})
24: [244.0s] 	/usr/local/go/src/runtime/panic.go:920 +0x270
24: [244.0s] github.com/dagger/dagger/engine/client.(*Client).ServeHTTP(0xc00018c9c0, {0x133ab28, 0xc0004d62a0}, 0xc000554c00)
24: [244.0s] 	/app/engine/client/client.go:545 +0xbf2
24: [244.0s] net/http.serverHandler.ServeHTTP({0x1336c70?}, {0x133ab28?, …
```
> fix: avoid client panic on ctx cancel

- core/integration/module_shell_test.go
- core/integration/module_up_test.go
- core/schema/host.go
- core/schema/service.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/service.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Service.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
It seems in most cases we want `--native` to be the default. So this makes it the default and adds `--random` for the old behavior (choose random ports).
> Service.up: make `native` the default, add `random`

- core/integration/module_config_test.go
Coverage for this was missing. I expected going into this that it would actually not work as expected yet based on user reports but I haven't been able to repro the behavior they saw yet. Will update if any bugs are found. But in the meantime obviously need to have coverage of this either way.
> add integ test for mod init --name and --sdk required together

- core/service.go
Following dagql integration, the service start operation was not relying on a unique ID as digest anymore. This led the Cloud not showing the service start as a step in Dagger Cloud. By appending the ".start" to the id, we isolate it
We now have back:
> core: separate service start vertex

- sdk/elixir/.changes/unreleased/Fixed-20240203-105721.yaml
- sdk/elixir/lib/dagger/internal/engine/downloader.ex
Change how to detect os and architectue on Windows. For the architecture. For the architecture, it needs to strict with `amd64` since `:erlang.system_info(:system_architecture)` returns `:win32`, which not helping us to determine os architecture on Windows.
Fixes: #6540
> fix(sdk/elixir): fix auto-provision mode cannot running on Windows

- cmd/dagger/main.go
--pprof: useful for debugging dagger itself, but not for regular usage
--cpuprofile: same as above
--workdir: may be deprecated soon, hide it in the meantime
I also wanted to hide the `dagger completion`, but didn't find how. Will open a separate PR once I do.
> Hide debug and soon-to-be-deprecated flags

- core/container.go
- core/integration/module_shell_test.go
- core/schema/container.go
- core/schema/util.go
- docs/current_docs/cli/979595-reference.mdx
- docs/docs-graphql/schema.graphqls
- docs/versioned_docs/version-zenith/reference/979596-cli.mdx
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Container.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Prior discussion on GH: https://github.com/dagger/dagger/pull/6390
Recent Discord discussion: https://discord.com/channels/707636530424053791/1120503349599543376/1202998900223647804
Changes current in this PR:
* `Container.shell` is renamed to `Container.terminal`
* `--args` renamed to `--cmd`
So from the CLI you'd now do e.g.
```console
dagger call my-devenv terminal --cmd neovim
```
We also discussed some alternatives to `terminal` in the zenith call a bit ago:
* `tty`
* `open-terminal`
* `console`
* `attach`
* (more I am probably forgetting already, please chime in)
Overall, `terminal` is fine with me in that it avoids:
* some of the weirdness around `withDefaultShell` and `shell` not actually corresponding to "set value" and "get value"
* it's more generic and technically accurate …
> update container.shell to container.terminal

- engine/server/buildkitcontroller.go
There is a comment suggesting this? I'm not quite sure why it's not turned on, it definitely feels important.
This also clogs up every stack dump, with literally thousands of copies, since it never closes.
@sipsma is there a good reason to not do this? The stream connection can never outlive this `Session` call, so we should just be able to call this.
> chore: cleanup grpchijacked connections

- engine/server/buildkitcontroller.go
Reverts #6597.
See https://github.com/dagger/dagger/pull/6597#issuecomment-1930527937. I don't have the bandwidth to investigate this properly, and the leaking threads (while annoying, at least doesn't break every test run).
If we merge this, I'll open an issue and pick it up later.
> Revert "chore: cleanup grpchijacked connections"

- docs/versioned_docs/version-zenith/quickstart/883939-containers.mdx
This commit fixes an output error in the Zenith quickstart
> docs: fix minor output error in quickstart

- engine/server/buildkitcontroller.go
Hm, I didn't catch this in https://github.com/dagger/dagger/pull/6499.
It looks like I fixed it for `srv.Wait`, not actually for `handleConn` :scream:
> chore: tidy up wrapping nil error in session call

- engine/client/buildkit.go
- engine/client/drivers/dial.go
- engine/client/drivers/docker.go
- engine/client/drivers/driver.go
This patch starts to simplify the connhelpers and docker-image helper into specific engine drivers (see https://github.com/dagger/dagger/issues/5583) - adding new drivers now becomes easier.
Each driver registers itself under a name, and is called when connecting to a URL with that scheme. Additionally, during connection, we provide a set of additional parameters.
This is mostly just a refactor around the connhelpers, which we can't use directly out of the box, since we want to support a set of additional parameters as well. Since each driver just returns a net.Conn, then we can build the buildkit connection on top of it, which allow us to potentially change the connection mechanism in the future.
> feat: lay foundations for engine drivers

- core/integration/module_typescript_test.go
Merging https://github.com/dagger/dagger/pull/6537 after https://github.com/dagger/dagger/pull/6533 caused test failures from `dagger mod init` being renamed to `dagger init`.
> fix: replace typescript mod init -> init

- cmd/codegen/generator/go/templates/module_funcs.go
- cmd/codegen/generator/go/templates/modules.go
- core/integration/module_test.go
Fixes #6532 :tada:
We should explicitly check for weird contexts, instead of just charging ahead and panicking.
Also, while I was in the area, I threw in an explicit failure for foreign types (since we don't currently have anything for https://github.com/dagger/dagger/pull/6185). The code generated was completely invalid, so better to fail early with a good error message.
> fix(gosdk): gracefully handle contexts in weird places

- engine/client/buildkit.go
- engine/client/drivers/dial.go
- engine/client/drivers/docker.go
- engine/client/drivers/driver.go
See https://github.com/dagger/dagger/pull/6288#issuecomment-1931971234 - this fixes the borked provision job: https://github.com/dagger/dagger/actions/runs/7814283652/job/21315752098.
Previously, we would only connect once. However, when calling buildkit's client.Wait we might attempt multiple connections over and over. If we only have one connection, this isn't possible. Ideally, we should have some better error messages in buildkit, since this was annoying to debug.
The right call here is to clearly split up Provision and Connect steps for a driver. This separation allows us to ensure that we Provision once, but can Connect multiple times.
I've also noted that Connect can be called multiple times, but we don't need to support multiple concurrent connections. While this isn't really …
> fix: new engine drivers should allow multiple connection attempts

- cmd/codegen/generator/go/templates/module_funcs.go
- cmd/codegen/generator/go/templates/module_interfaces.go
- cmd/codegen/generator/go/templates/module_objects.go
- cmd/codegen/generator/go/templates/modules.go
- cmd/codegen/generator/go/templates/src/dagger.gen.go.tmpl
- core/integration/module_call_test.go
- core/integration/module_test.go
- core/integration/testdata/modules/go/ifaces/impl/main.go
- core/integration/testdata/modules/go/ifaces/main_test.go
- core/integration/testdata/modules/go/ifaces/test/main.go
- core/integration/testdata/modules/go/minimal/main.go
- sdk/go/dagger.gen.go
This PR just removes `Optional`. Very simple, very neat. Based on the discussion in https://discord.com/channels/707636530424053791/1203102934901071882/1203134907677675630 (and probably in other places). There's also some additional context in https://github.com/dagger/dagger/pull/6370.
I think we should try and get this in for v0.9.9:
- We shouldn't ship two mechanisms of doing optionals in v0.10.0 - breaking earlier is better, and gives us more time for feedback.
- Our docs haven't described this for a while (since https://github.com/dagger/dagger/pull/6225). We've made other breaking changes since then (including the removal of `dag.Host`), so it's likely that users who wrote modules using these docs as references will need to make other updates as well.
We could *potentially* …
> feat: remove Optional from go modules

- cmd/codegen/generator/go/generator.go
- sdk/python/runtime/template/src/main.py
- sdk/typescript/runtime/template/src/index.ts
The listed command in the previous examples didn't really help users:
$ dagger call container-echo --string-arg yo
Container evaluated. Use "dagger call container-echo --help" to see available sub-commands.
We should amend the default template command to actually print the result:
$ dagger call container-echo --string-arg yo stdout
yo
> docs: fixup module template suggested command

- .github/workflows/engine-and-cli.yml
This new worker has a second nvme drive, and mounts it to `/var/lib/docker`, so we get better performance.
Based off of the findings in #6563.
> ci: use docker-fix runner for testdev job

- sdk/java/dagger-codegen-maven-plugin/src/main/java/io/dagger/codegen/DaggerCLIUtils.java
otherwise it hangs the moment it tries to write to os.Stderr
> sdk/java: pass --silent to dagger query

- core/integration/module_up_test.go
- core/schema/service.go
Think this happened when switch up to default to `native`.
The logic was accidentally setting native to true even when ports were manually specified which resulted in each port being applied twice. In the case where the same values of frontend and backend were specified (i.e. 5000:5000) this resulted in an error since you'd try to listen on the same port twice.
Should (re-) fix https://github.com/dagger/dagger/issues/6303, though this is definitely a different root cause than the previous one because this can only happen if you use the same frontend+backend (whereas previously it happened with any use of --port)
> core: fix native always true for up even when ports are set

- internal/mage/sdk/elixir.go
This path changed the other day: https://github.com/dagger/dagger/commit/01268a5fe62067f7d5dddfb5f5d90ecf4909eac4
But it's only used in mage during engine bump PR, which only runs at release, so wouldn't have been caught til then. Noticed it because I was testing publish workflows in my fork.
> elixir: update sdk version file path in mage

- docs/versioned_docs/version-zenith/developer/go/191108-advanced-programming.mdx
- docs/versioned_docs/version-zenith/developer/go/457202-test-build-publish.mdx
- docs/versioned_docs/version-zenith/developer/go/525021-quickstart.mdx
- docs/versioned_docs/version-zenith/developer/python/419481-quickstart.mdx
- docs/versioned_docs/version-zenith/developer/python/539756-advanced-programming.mdx
- docs/versioned_docs/version-zenith/developer/typescript/506316-quickstart.mdx
- docs/versioned_docs/version-zenith/quickstart/428201-custom-modules.mdx
These changed in https://github.com/dagger/dagger/pull/6533
Just making the bare minimum changes to keep docs aligned with reality here rather than documenting any of the new features yet.
Not adding to the v0.9.9 milestone since it's not technically a blocker, just should be merged soon after that's done.
> docs: update zenith guides for new top-level init/install commands

- analytics/internal.go
- core/modfunc.go
- core/object.go
- core/schema/sdk.go
This uses a little bit of `ctx` trickery to propagate a flag through intra-engine calls to SDK modules so we can set a different caller (`internal` instead of `direct`) on module analytics.
It also uses that same flag to re-enable caching for SDK modules, which was lost with #6297.
> distinguish internal module calls from user calls

- .changes/unreleased/Added-20240201-183804.yaml
- core/container.go
- core/directory.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/schema/container.go
- core/schema/directory.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/elixir/lib/dagger/gen/directory.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Container.php
- sdk/php/generated/Directory.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Fixes: #6475 
The issue mentioned only Directory, but I also added it to Container, not sure that was a good idea. Also, this is my first contribution so I might be missing a few things.
With regards to the sdk changelog, it seems like that is something I should do after creating the PR? go through every sdk and run it?
Also a question: in Directory WithFiles, I wasn't sure whether or not I should have re-used WithFile, some feedback on that would be great :)
> feat: add WithFiles to Directory and Container

- core/integration/module_config_test.go
- core/modulesource.go
- core/schema/modulesource.go
The source root subpath of git refs were being turned into absolute paths (as opposed to local refs which always stored the source root subpath as relative). This broke the resolve dependency logic and resulted in errors when installing modules from a git ref that had a relative local dep.
> fix resolution of local dep from git module

- cmd/shim/secret_scrub.go
- cmd/shim/secret_scrub_test.go
Fix https://github.com/dagger/dagger/issues/6630.
The issue appeared when attempting to insert two keys that had similar prefixes:
- Inserting `abc`, and then inserting `abcd`,
- Inserting `abcd`, and then inserting `abc`.
This case was being handled poorly, due to the handling of the `direct` suffix value. When inserting to a node that already has a suffix, we need to take care to not just directly write there - if there's a value stored there, we need to make it into a branch node.
> Ensure correct insertion of similar keys to secret scrubber trie

- internal/mage/util/engine.go
Without this, the Go module SDK would only ever be able to build modules with the single go version that our CI had permitted - this made for a really confusing and frustrating experience when running a newer go version locally (e.g. being on a bleeding edge distro :smile).
I noticed this when using a `go.work` in my own daggerverse repo:
```
$ dagger call get-latest-release --repo="dagger/dagger" body
✘ ModuleSource.asModule: Module! 1.8s
✘ Module.withSource(
source: ✔ ModuleSource.resolveFromCaller: ModuleSource! 0.0s
): Module! 1.8s
✔ Container.import(
source: ✔ Directory.file(path: "go-module-sdk-image.tar"): File! 0.0s
): Container! 0.7s
✘ Container.directory(path: "/src"): Directory! 0.8s
✘ exec /usr/local/bin/codegen --module-context /src --module-name github --propagate-logs=true …
```
> feat: set GOTOOLCHAIN to auto for go module sdk

- cmd/dagger/module.go
`dagger mod init` is deprecated, and the example shouldn't include it.
> fix: correct the dagger init cli example

- .github/workflows/_new_release_notification.yml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-sdk-elixir.yml
- .github/workflows/publish-sdk-go.yml
- .github/workflows/publish-sdk-php.yml
- .github/workflows/publish-sdk-python.yml
- .github/workflows/publish-sdk-rust.yml
- .github/workflows/publish-sdk-typescript.yml
- .github/workflows/publish.yml
`TL;DR`
`1/3. GitHub Workflow`
`2/3. dagger call in GitHub Workflow Step`
`3/3. Discord Notification`
---
This adds notifications for the following releases:
1. 🚙 Engine + 🚗 CLI
2. 🐹 Go SDK
3. 🐍 Python SDK
4. ⬢ TypeScript SDK
5. ⚙️ Rust SDK (this is not published part of the regular release cycle)
6. 🧪 Elixir SDK
7. 🐘 PHP SDK
8. 🎡 Helm Chart (this is not published part of the regular release cycle)
We used to have a bot for this purpose: `github-release-towncrier`. It required us to:
- keep the app running all the time
- change the filtering when a new release type was added
A few other issues that we've hit with this setup:
- performing any updates during a release would miss webhooks
- if a webhook was missed, the notification would not go out
- setting up redundant instances would …
> Send Discord notifications part of releasing

- helm/dagger/Chart.yaml
Follow-up to:
- https://github.com/dagger/dagger/pull/6665
> helm: Bump default Dagger Engine version to v0.9.10

- .github/workflows/engine-and-cli.yml
- .github/workflows/helm.yml
cc @d3rp3tt3 @vikram-dagger 
We don't need to run `helm` or `engine-and-cli` (the very long ones, `test`+`testdev`) on every single docs PR.
The SDK jobs still should run on every PR, since the linting jobs can also lint the contents of the `docs/` directory I think?
> ci: skip some test jobs on pull requests

- core/integration/module_config_test.go
- core/modulesource.go
Noticed source code links on Daggerverse are broken, this should fix it.
> fix ModuleSource.htmlURL with subpath

- cmd/codegen/generator/go/templates/module_funcs.go
- core/integration/module_test.go
- core/integration/testdata/modules/go/minimal/main.go
- docs/versioned_docs/version-zenith/developer/go/snippets/advanced-programming/constructor/main.go
- docs/versioned_docs/version-zenith/developer/go/snippets/quickstart/trivy/main.go
Reference: https://discord.com/channels/707636530424053791/1150156410462679180/1207824903458398258
Also see #6651.
No more `// +default=foo` which is unclear, now we require `// +default="foo"`.
This is a zenith breaking change! cc @vikram-dagger, I've updated the docs as well.
---
Chucking this onto the v0.9.11 milestone, sooner > later. We should do another announcement in #project-zenith when we do this.
> feat: go module default arg values must all be valid JSON

- cmd/codegen/generator/go/generator.go
- core/integration/module_test.go
*Should* fix https://github.com/dagger/dagger/issues/6659 (cc @nipuna-perera).
This is a pretty common use case - we have a `go.work` at the root of a repo, and we want to create a dagger module for it with `dagger init`.
However, naively, this will actually create a dagger module that can't be called (because `go.work` doesn't include it). To resolve this, we need to add it to `go.work`.
(bleh, this took way too long to track down and work out how to fix)
> fix: add generated go modules to go.work

- docs/versioned_docs/version-zenith/quickstart/428201-custom-modules.mdx
In Zenith documentation, it need to change directory to `my-module` before initiate the module to create module to correct location.
> docs: fix incorrect init module path

- cmd/dagger/module.go
- core/integration/module_config_test.go
Fixes https://github.com/dagger/dagger/issues/6664
Based on my testing, `DependencyByName` would return the git URL from the config, and we'd assume this was a local path. `Source.Kind` check happens earlier in this function, so recursively calling the function with the un-short-named ref felt right. There may be a case I'm missing here.
> Zenith: Fix short names for remote refs

- core/integration/module_call_test.go
- core/integration/module_config_test.go
- core/integration/module_test.go
- core/modulesource.go
- core/schema/module.go
- core/schema/modulesource.go
- core/schema/sdk.go
fixes https://github.com/dagger/dagger/issues/6623
Most of the recent bugs from the last week ended up being simple things related to using git module refs, which was due to the fact that we didn't have integ test coverage of those.
We didn't have coverage previously because it's slightly less obvious than it seems due to the limitation around git modules only being allowed to be from `github.com/`. That essentially rules out authoring the tests in the repo itself (there's various shenanigans that might be possible but it gets way too complicated to be worth it).
So, until we have support for non-github module refs, we can just maintain a separate git repo that has "test fixture" modules. I created one in my org [here](https://github.com/sipsma/dagger-module-tests) for now (should be …
> backfill integ test coverage for git ref modules

- cmd/codegen/generator/go/templates/format.go
- core/integration/module_test.go
Fixes https://github.com/dagger/dagger/issues/6669.
Previously, FormatOutputType and FormatInputType wouldn't use the same capitalization as formatName. The solution is to have these functions also format the underlying names, which means we get *consistent* caps!
> fix: ensure common capitalization for go type generation

- sdk/python/src/dagger/_codegen/generator.py
- sdk/python/src/dagger/client/gen.py
- sdk/python/tests/client/test_codegen.py
- sdk/python/tests/client/test_integration.py
Noticed a performance impact in a module when iterating over a list returned by a dependent module.
The calling module was requesting a field (state), which should be returned directly by the API server, but was actually calling out (exec /runtime) on a bunch of functions that return a simple string. So these were flagged as simple fields to prefetch, even though I didn't need them, but it's the act of executing the runtime that slowed things down unnecessarily.
By loading from ID instead, it ensures that only the fields that are needed are actually requested. This is what Go does, although I think the change there was to fix a bug when lists were returned.
We could adjust the codegen to limit the prefetching selection to GraphQL fields that match Dagger module object fields, but we'd …
> Python: Refactor methods that return lists to not prefetch and select id instead

- core/integration/module_python_test.go
- sdk/python/src/dagger/mod/_converter.py
The previous error message was actually erroneous. Scalars are subtypes of strings. After handling built-in strings, this failed in validating Sequence types (lists). However, strings are sequences of characters, so it failed in a particular case for lists which is to define one without a subtype (`args: list` when it must be `args: list[str]`). 
Thus the error message wasn't correct. The fact is we don't support a ScalarKind or EnumKind in TypeDefs yet, so might as well fail early with a helpful error message.
**Before:**
```
TypeError: Expected collection type to be subscripted with 1 subtype, got 0: <class 'dagger.Platform'>
```
```
TypeError: Expected collection type to be subscripted with 1 subtype, got 0: <enum 'NetworkProtocol'>
```
**After:**
```
NotImplementedError: Scalar types …
```
> Python: Improve error message when using unsupported scalar or enums as arguments

- cmd/codegen/generator/go/generator.go
- core/integration/module_test.go
Follow-up to #6678.
I was missing an important test case that reveals I was doing this *entirely* wrong.
The condition should check for the existence of `go.work`, not it's absence, and we should actually look in the root, which is found in a configuration option.
> fix: actually add generated go modules to go.work

- core/integration/module_test.go
- core/schema/module.go
Fixes https://github.com/dagger/dagger/issues/6625.
We just need to switch from putting them into the `SourceRootSubpath` to putting them in `SourceSubpath`.
> fix: move gitattributes/gitignore files into source directory

- core/integration/pipeline_test.go
This test is super annoyingly flaky :( Potentially fixes #6697.
It seems like calling Close is racy, and sometimes we don't get the fully progress logs - to work around this for now, we can try and call service close explicitly, which should *hopefully* make this failure a bit more unlikely.
Yes, we should fix the underlying issue at some point - cc @grouville, I know you were also working on this.
> fix: close service in pipeline test

- core/integration/module_config_test.go
Just updating the repo to be [our shiny new one under the dagger org](https://github.com/dagger/dagger-test-modules) so that others on the team can contribute to it as needed.
> tests: update module test repo to one under dagger org

- core/integration/images.go
- core/integration/testdata/modules/go/basic/go.mod
- core/integration/testdata/modules/go/broken/go.mod
- core/integration/testdata/modules/go/ifaces/go.mod
- core/integration/testdata/modules/go/ifaces/impl/go.mod
- core/integration/testdata/modules/go/ifaces/test/go.mod
- core/integration/testdata/modules/go/namespacing/go.mod
- core/integration/testdata/modules/go/namespacing/sub1/go.mod
- core/integration/testdata/modules/go/namespacing/sub2/go.mod
- core/integration/testdata/nested-c2c/main.go
- docs/versioned_docs/version-zenith/developer/go/snippets/advanced-programming/constructor/go.mod
- docs/versioned_docs/version-zenith/developer/go/snippets/quickstart/step3a/go.mod
- docs/versioned_docs/version-zenith/developer/go/snippets/quickstart/trivy/go.mod
- docs/versioned_docs/version-zenith/developer/go/snippets/test-build-publish/step6/go.mod
- docs/versioned_docs/version-zenith/quickstart/snippets/create/go/go.mod
- internal/mage/go.mod
- internal/mage/util/engine.go
- sdk/typescript/runtime/go.mod
Hopefully fix https://github.com/dagger/dagger/pull/6636#issuecomment-1935917443.
This is a nice intermediate until we can bump to go 1.22: https://github.com/dagger/dagger/pull/6637 (blocked due to an upstream go/glibc issue).
See also discord conversation: https://discord.com/channels/707636530424053791/1003718839739105300/1209830653051412490.
> chore: bump go to 1.21.7

- core/schema/host.go
- core/schema/sdk.go
- docs/docs-graphql/schema.graphqls
- docs/versioned_docs/version-zenith/reference/979596-cli.mdx
- engine/buildkit/session.go
- go.mod
- internal/distconsts/consts.go
- internal/mage/go.mod
- internal/mage/go.sum
- internal/mage/util/engine.go
- sdk/elixir/lib/dagger/gen/client.ex
- sdk/go/dag/dag.gen.go
- sdk/go/dagger.gen.go
- sdk/php/generated/Client.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
@vito noticed a while back that we were spending a lot of time loading the builtin Go SDK tarball. This fixes that bottleneck by avoiding use of local imports for built-in SDKs and instead using OCI store sources, which avoid the various problems with local sources (re-importing when used in parallel, need to always re-read tarball when importing containers, etc.).
> core: speed up loading of builtin SDKs

- sdk/typescript/entrypoint/entrypoint.ts
- sdk/typescript/runtime/main.go
We display the error message instead of the whole stack trace so it's easier for the user to catch the error.
**Before**
```
(node:30) [DEP0128] DeprecationWarning: Invalid 'main' field in '/src/dagger-docs/error-handling/sdk/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:30) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
/src/dagger-docs/error-handling/src/index.ts:9
throw new Error("cannot divide by zero")
^
Error: cannot divide by zero
at HelloWorld.divide (/src/dagger-docs/error-handling/src/index.ts:9:13)
at Registry.getResult (/src/dagger-docs/error-handling/sdk/introspector/registry/registry.ts:131 …
```
> feat(ts): improve error displaying.

- cmd/dagger/module.go
- core/integration/module_test.go
- core/integration/suite_test.go
Fixes https://github.com/dagger/dagger/issues/6640
The behavior of dagger listen is supposed to be that it tries to load a local module if it exists but ignores any error and just operates without the module if it can't load one. This just fixes error handling in the case where `--disable-host-read-write` is enabled.
> fix listen disable-host-read-write with modules

- cmd/dagger/call.go
- cmd/dagger/functions.go
- cmd/dagger/main.go
- cmd/dagger/module.go
In preparation for v0.10.0, we want to open up zenith commands.
> CLI: remove experimental annotations and old commands

- core/container.go
- core/host.go
- core/integration/container_test.go
- core/integration/module_test.go
- core/query.go
- core/schema/container.go
- core/schema/secret.go
- core/secret.go
- docs/docs-graphql/schema.graphqls
- engine/buildkit/client.go
- engine/server/buildkitcontroller.go
- sdk/elixir/lib/dagger/gen/client.ex
- sdk/go/dag/dag.gen.go
- sdk/go/dagger.gen.go
- sdk/php/generated/Client.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
[Original feature request](https://linear.app/dagger/issue/DEV-3204):
> Right now the in-memory secret store is shared across a whole dagger session, which includes the original client caller and all the modules it invokes (including transitively).
>
> Instead secrets should be passable as inputs/outputs of Functions but only accessible that explicit way, not accessible via the "ambient secret store".
To achieve this isolation, we keep the same global secret store, but ensure that each secret has a "scope" - this scope split the global secret store into lots of smaller stores.
Note, this is really quite a tricky puzzle, and the requirements become more fiddly as you lay them out:
- Secrets across different sessions/modules should be allowed the same name
- Secrets shouldn't affect caching …
> Isolate secrets to each module

- cmd/codegen/generator/go/generator.go
Another fix for https://github.com/dagger/dagger/issues/6706 - we're not gonna get any full compete solution that happily manages all the go versions before v0.10, but this at least can warn users when a weird case happens.
We've already got protections for the case of making a new module from scratch (the most common case), but this adds a similar protection for creating using an existing go.mod file.
> chore: error out with too new go tooling

- cmd/codegen/generator/go/generator.go
Just focused on keeping function signatures the same for now (as they're used in docs and smoke tests) and adding short and long descriptions and appropriate comments.
The generated code in the `main.go` is unaltered after running `go fmt` on it, so it's got that going for it :)
> Zenith: Update dagger init module for Go SDK

- sdk/python/runtime/template/src/main.py
To match https://github.com/dagger/dagger/pull/6720 and #6742 
Builds on  https://github.com/dagger/dagger/pull/6729
`ruff format` seems happy.
Similar to Go and TS, I'm not putting a comment on the Class.
With `pylint` that throws
```
src/main.py:19:0: C0115: Missing class docstring (missing-class-docstring)
```
which someone could quiet down with something like this in their `.pylintrc`:
```
[MASTER]
disable=
C0115, #missing-class-docstring
```
> Zenith: Adds descriptions & comments for Python SDK init

- core/integration/module_test.go
- core/schema/host.go
- engine/buildkit/client.go
- engine/server/buildkitcontroller.go
Before this, it was technically possible for a module to make a raw graphql query to the Host.unixSocket API and gain access to any unix socket on the main client caller's host (i.e. where the CLI is running). This is due to the fact that the socket attachable currently has to be hardcoded to always refer to the main client caller (which in turn is due to relevant grpc metadata not being forwarded by buildkit yet in those codepaths).
Now we just enforce that this API can only ever be called from the main client caller. This is okay for now because we don't yet support passing unix sockets around modules. We do want to support that in the near future, but it will require some tweaks upstream in buildkit and more plumbing in our own code to carefully track which module has access to a given …
> core: only allow Host.unixSocket to be used from main client

- sdk/typescript/runtime/template/src/index.ts
To match https://github.com/dagger/dagger/pull/6720 and #6741 
passes the relevant parts of`tslint`
note: TypeScript templates use `QuickStart` as placeholder for module name.
```
./runtime/template/src/index.ts:class QuickStart {
./runtime/main.go:		// if not: copy the template and replace QuickStart with the module name
./runtime/main.go:		// If not, add the template file and replace QuickStart with the module name
```
> Zenith: Adds descriptions and comments for TypeScript SDK

- docs/current_docs/cli/389936-run-pipelines-cli.mdx
- docs/current_docs/faq.mdx
- docs/current_docs/guides/128409-build-test-publish-php.mdx
Absolute URL links create a problem when archiving the website, because the base URL is no longer the same on the archive website. This fixes such links to be filesystem links instead.
> docs: Fixes to current docs in preparation for archival

- sdk/python/docs/module.rst
Tiny fix for a broken link in zenith docs.
> docs: Add missing class in Python reference docs

- engine/server/buildkitcontroller.go
- engine/server/server.go
Fixes: https://github.com/dagger/dagger/issues/6719
See individual commit messages for explanations.
Running the full `TestModule` suite locally now shows RSS maxing out around 1GB (still high-ish but much more reasonable than 6GB). And most importantly, whereas previously the engine's RSS *stayed* high after the test suite ended (it stuck around 2-3 GB RSS), now the RSS drops down to reasonable 600MB afterwards, with `pprof` showing reasonable usage mostly from buildkit's in memory cache metadata:
```
File: dagger-engine
Type: inuse_space
Time: Feb 27, 2024 at 10:00am (PST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 38.15MB, 58.54% of 65.17MB total
Showing top 10 nodes out of 306
flat  flat%   sum%        cum   cum%
11MB …
```
> Fix goroutine and memory leaks in engine

- sdk/elixir/.changes/unreleased/Fixed-20240227-224706.yaml
- sdk/elixir/lib/dagger/core/query_builder.ex
- sdk/elixir/test/dagger/client_test.exs
This issue found during work on `wttr` module [1] that is a prototype of the Elixir for Dagger Module, the error is silent when send the output from `wttr` back to the function call. After investigate it, it has 2 issues:
1. The `execute` function silent the error. It returns ok tuple with error result, cause a function process incorrectly.
2. The graphql builder didn't escape `\` got graphql server returns 403 parse error to the client.
This patch fix those issues above.
[1] https://github.com/wingyplus/daggerverse/tree/main/wttr.
> fix(sdk/elixir): fix backslash didn't get escape

- internal/mage/engine.go
- internal/mage/sdk/elixir.go
- internal/mage/sdk/go.go
- internal/mage/sdk/java.go
- internal/mage/sdk/php.go
- internal/mage/sdk/python.go
- internal/mage/sdk/rust.go
- internal/mage/sdk/typescript.go
- internal/mage/util/engine.go
- internal/mage/util/util.go
panics can result in some bizarre error reports - for example:
failed to check version compatibility: Post "http://dagger/query": context canceled
panic: get tree hash: Post "http://dagger/query": context canceled
goroutine 51 [running]:
github.com/dagger/dagger/internal/mage/util.CIDevEngineContainer({0x90a140, 0xc0002be000}, 0xc00011a9c0, {0xc0000efb00, 0x1, 0xc00011e1d0?})
/home/jedevc/Documents/Projects/dagger/dagger/internal/mage/util/engine.go:163 +0x5db
github.com/dagger/dagger/internal/mage/util.CIDevEngineContainerAndEndpoint({0x90a140, 0xc0002be000}, 0xa?, {0xc0000efb00?, 0x0?, 0xc000285a30?})
/home/jedevc/Documents/Projects/dagger/dagger/internal/mage/util/engine.go:140 +0x2c
github.com/dagger/dagger/internal/mage/sdk.Python.Generate({}, {0x90a140, 0xc0002be000}) …
> chore: avoid panic in CI scripts

- internal/mage/engine.go
- internal/mage/sdk/go.go
Thanks @vito for the suggestion: https://github.com/dagger/dagger/pull/6759#discussion_r1504696242
This now adds linting to the engine and the go sdk for `go.mod` consistency. An error looks something like this:
```
Error: Generated code mismatch. Please run `go mod tidy`:
--- go.mod
+++ go.mod
@@ -4,12 +4,9 @@
replace dagger.io/dagger => ./sdk/go
-require (
-	dagger.io/dagger v0.10.0
-)
+require dagger.io/dagger v0.10.0
require (
-	dagger.io/dagger v0.10.0
github.com/99designs/gqlgen v0.17.41
github.com/Khan/genqlient v0.6.0
github.com/MakeNowJust/heredoc/v2 v2.0.1
exit status 1
```
> ci: add linting for go.mod

- docs/current_docs/user-guide/cloud/572923-get-started.mdx
This commit adds a note to the Dagger Cloud get started.
> docs: Adds note about module viz in Cloud get started

- internal/mage/sdk/typescript.go
- sdk/typescript/package.json
As discussed with @TomChv in #6591.
Our CI would test with
- `node:18-alpine`
- `node:20-alpine`
and not with `node:16-alpine`, which is discontinued and reached EOL.
All other tasks, such as lint, bump, publish, build, utilize the LTS version of node, which is currently 20.
Updated the `package.json` to reflect we only test for `node>=18`.
___
Node 18 is maintained until 30 Apr 2025.
Thats when we should potentially look into upgrading again.
> ci: Update Node.js version for the typescript SDK and test LTS and Maintenance versions

- .changes/unreleased/Added-20240304-100326.yaml
- cmd/dagger/flags.go
As suggested by @helderco in https://github.com/dagger/dagger/pull/6744#pullrequestreview-1902308392.
This brings it inline with how you can currently pass git directories.
Usage:
dagger call thing --file https://github.com/dagger/dagger.git#main:README.md
Or with an implicit branch:
dagger call thing --file https://github.com/dagger/dagger.git#:README.md
> feat: allow passing git files on dagger cli

- engine/cache/mountsync.go
to avoid unnecessarily long shutdown times when using the remote cache
service, we should only sync the cachemounts that have been seen by the engine
previously. This helps in the specific scenario were pipelines are
cached and cache mount re-uplodas are unnecessary.
> engine: only sync seen cachemounts on engine shutdown

- .changes/unreleased/Added-20240304-224513.yaml
- core/container.go
- core/schema/container.go
- core/terminal.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Container.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Add `ExperimentalPrivilegedNesting` args in `DefaultTerminalCmdOpts` and `TerminalOpts`.
Add `InsecureRootCapabilities` args in `DefaultTerminalCmdOpts` and `TerminalOpts`.
I did some test with a local module I made but I struggle figuring out how to test it in our integration's test.
I know we have `module_terminal_test.go` for terminal tests and `container_test.go` for inscure and nesting params but I cannot figure out a nice way to combine both because this requires extra installation and sending lines/checking return etc...
I would love to have some ideas
/cc @sipsma @vito 
Fixes #6712
> feat: support new options in terminal

- docs/current_docs/quickstart/428201-custom-function.mdx
- docs/current_docs/quickstart/822194-daggerize.mdx
There are 2 pages in the current quickstart that contain the experimental note
"Daggerize A Project" and "Write your first function"
This removes that note from those two pages
> remove experimental from two quickstart pages

- .changes/unreleased/Fixed-20240304-124800.yaml
- core/integration/container_test.go
- engine/buildkit/client.go
- engine/buildkit/llbdefinition.go
Fixes regression from #6601, see [discord discussion](https://discord.com/channels/707636530424053791/1212602528890363955). 
Essentially, it became possible to construct an input which would apply the secret accessor translation twice. If one of the frontend inputs was constructed from dagger, it could already have an accessor secret ID as part of it's build graph (if `WithExec` was used alongside a secret).
However, this input could appear inside the frontend request - which would result in double-wrapping the secret accessor to a secret that definitely can't exist, which presents the weird error.
The easiest solution to this is to just track the inputs for dagger calls to buildkit's Solve request, and to ensure that we avoid secret filtering for those inputs.
> fix: avoid duplicate secret accessor conversion

- cmd/codegen/generator/go/templates/module_interfaces.go
- cmd/codegen/generator/go/templates/src/_dagger.gen.go/defs.go.tmpl
- cmd/codegen/generator/go/templates/src/_types/object.go.tmpl
- cmd/dagger/functions.go
- core/integration/module_test.go
- sdk/go/client.go
- sdk/go/dagger.gen.go
- sdk/go/querybuilder/querybuilder.go
See discussion in discord: https://discord.com/channels/707636530424053791/1120503349599543376/1209815200023191662
https://github.com/dagger/dagger/pull/6680 made `Client` and `Query` reserved fields on all objects - but it's quite common to define `Client` on objects.
This patch is a little bit of a refactoring I've wanted to do for a while - it essentially allows binding clients to `querybuilder.Selection`s, which means we can pretty much do away with `Client`+`Query` combinations, now we only need to track `Query` (and the client gets automagically inherited).
We still have this issue for `Query`. Gonna keep thinking about this one.
> fix: remove global Client property on generated structs

- sdk/go/dagger.gen.go
Due to an undetected conflict, we added a new method BuiltinContainer, which accessed the old Client property.
This fixes the CI failure on main: https://github.com/dagger/dagger/commit/62ced562b1bdd69f35b5112d0d2736a2d2189c7a
> fix: repair dagger.gen.go access to Client

- .github/workflows/publish.yml
Following of #6685 to update the test publish job.
It's weird but some test are not run on push and so we didn't caught this erorr.
https://github.com/dagger/dagger/blob/1759f47a7c6bc8cc13380e193f6f7a1248ca6e0d/.github/workflows/publish.yml#L93
Normally this fixes works and fixes:
Btw, do we actually need these tests? Since we are using Dagger modules now, we don't have use that provisioning feature anymore.
> fix: update test-publish to node 18 

- .changes/unreleased/Fixed-20240228-155029.yaml
- core/integration/file_test.go
- engine/server/server.go
Fixes #6743.
We have a message size limit enforced by the gRPC connection - however, we then go to host a HTTP server on that connection, and we weren't performing any restrictions on the size of the `Write`s.
To resolve this, for any `Write` that is larger than (an adjusted for headers) size limit, we split it into multiple `Write` calls which will split it into several `BytesMessage`s by the `grpchijack` package.
Note: no such transformation is required for `Read`s, since go permits short-reads, but does not permit short-writes (so `grpchijack` can return under the requested number of bytes).
Arguably, this should be implemented upstream, however, it's tricky. Currently, the only upstream use of `grpchijack` is to host the session, which performs it's own message shortening procedures, …
> fix: handle calling Contents on massive files

- .changes/unreleased/Fixed-20240304-100555.yaml
- cmd/codegen/generator/go/generator.go
- core/integration/module_test.go
This effectively reverts #5983, since with go.work support we can't have duplicate module names inside a single namespace.
Thankfully though, we can avoid the original issue that this fixed (where `go` is effectively a reserved module name), by prefixing all module names with `dagger/`).
This helps for daggerverse-like repo structures, where the top-level `go.work` would ideally need to contain all the sub-modules.
> fix: change go module name to match dagger module name

- docs/current_docs/developer-guide/go/882081-module-structure.mdx
After changes in https://github.com/dagger/dagger/pull/6774, the package name has changed from `main` to `dagger/<module-name>` - the docs need updating to reflect this.
> docs: fix import name after change from main

- .github/workflows/publish.yml
Follow-up to https://github.com/dagger/dagger/pull/6819
We also need this version update for `test-provision-typescript-linux`.
> ci: fix typescript version for test provision job

- core/modulesource.go
since we were using filepath.Join instead of url.JoinPath, the symbolic
URL was not being generated correctly. It was prefixing `https:/`
instead of `https://`
> engine: fix git module source symbolic URL

- zenith/README.md
https://github.com/dagger/dagger/pull/6503 removed most of the content of the `zenith/` top-level directory, but we kept the `README.md` around to keep pointing users to the docs.
However, I don't think we're linking to this from anywhere anymore, and now that functions/modules have launched and have a permanent home in the docs, it doesn't really make sense to keep this folder anymore.
> chore: remove old zenith directory

- cmd/codegen/generator/go/templates/src/_types/object.go.tmpl
- core/integration/pipeline_test.go
- sdk/go/dagger.gen.go
Should fix https://github.com/dagger/dagger/issues/6850 (cc @morlay)
This regressed in https://github.com/dagger/dagger/pull/6716, and meant that child clients were invalid, and couldn't be called with `Do()`, as well as causing `GraphQLClient()` to return an invalid nil value.
This only previously worked because the GraphQL client and the dagger client shared the same name `client`. When this property was removed, the propagation stopped working. Now, we make this special case explicit.
---
@morlay if you have a more specific stack trace from the panic, or can somehow confirm that this fixes your issue that would be super helpful.
> fix: propagate graphql client to child clients

- cmd/codegen/generator/go/templates/module_interfaces.go
- cmd/codegen/generator/go/templates/src/_dagger.gen.go/defs.go.tmpl
- cmd/codegen/generator/go/templates/src/_types/object.go.tmpl
- sdk/go/client.go
- sdk/go/dagger.gen.go
Follow-up to https://github.com/dagger/dagger/pull/6716 - people were using `Query` as a method name, see [discord](https://discord.com/channels/707636530424053791/1120503349599543376/1215103368150917180).
This could cause name clashes and was annoying. Thankfully, there's only one legitimate need for this field to be public - interfaces.
We can provide a workaround for this with the new `WithGraphQLQuery` method on generated types, which resets the underlying type, and sets the query.
---
I did briefly consider the idea of using an `XXX` prefix for `Query`, but I prefer having a method to set the private field since then it's not possible to set the query, but not modify the cached properties, which would definitely result in weird things happening.
> fix: remove public Query field from go generated types

- docs/current_docs/developer-guide/python/snippets/first-module/step2/main.py
Trying out the python dev guide and think there is a `self` missing [here](https://docs.dagger.io/developer-guide/python/419481/first-module#step-2-create-a-simple-dagger-function).
Output without `self`:
```
dagger call hello-world       
✔ daggerPotato: DaggerPotato! 0.5s
✔ exec /runtime 0.5s
✘ DaggerPotato.helloWorld: String! 0.6s
✘ exec /runtime 0.6s
┃ ╭─ Error ──────────────────────────────────────────────────────────────────────╮                                                                   
┃ │ Function execution error: invalid method signature                           │                                                                   
┃ ╰──────────────────────────────────────────────────────────────────────────────╯ …
```
> docs: Add missing self in python step2 snippet

- .github/dependabot.yml
Follow-up on comments from https://github.com/dagger/dagger/pull/6352#discussion_r1439349557.
Getting kinda annoyed with all the dependabot spam :cry:
- By moving from once-a-month to once-a-week, we stay more on top of changes, which means there should be fewer to address all at once. Additionally, I've set the time to trigger on Monday morning - that way, we can hopefully review and merge before the next release.
- I've also used `group`s to try and ensure that each set of updates is all combined, so we don't get a complete overflow of updates. Unfortunately, we don't seem to be able to combine all the go updates together (see https://github.com/dependabot/dependabot-core/issues/7547) - so we may still get invalid PRs, since the `go.mod`s interact with each other in fun ways.
- Finally, …
> chore: improve dependabot config publish weekly with groups

- core/integration/container_test.go
- engine/buildkit/client.go
...not just the last one. Not quite sure why I missed this before, but this occurs in some test cases (that are really annoying to add test cases for some reason).
This fixes up the logic from #6809 - see the discord conversation in https://discord.com/channels/707636530424053791/1212602528890363955/1214748356472213504.
Not 100% sure why the previous fix wasn't right, but this *definitely* works, and I don't really have the time to dive into exactly what I'm misunderstanding.
> fix: avoid duplicate secret accessor for all frontend inputs

- cmd/dagger/flags.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
- core/integration/module_call_test.go
- core/integration/module_config_test.go
- core/integration/module_functions_test.go
`dagger call/install/develop/publish/functions/config` all now take into account the find-up we do of `dagger.json` so they can work from subdirs.
`dagger init` is a special case where we don't findup since it would prevent you from initializing a module from a subdir of another.
> cli: do findup of dagger.json for all relevant commands

- docs/current_docs/quickstart/428201-custom-function.mdx
- docs/current_docs/quickstart/822194-daggerize.mdx
This commit adds notes to the quickstart based on the user feedback in https://discord.com/channels/707636530424053791/1215318377329983519
> docs: Clarifies section dependency and module naming in quickstart

- docs/current_docs/user-guide/932727-troubleshooting.mdx
- docs/sidebars.ts
Transfer of content from https://archive.docs.dagger.io/0.9/235290/troubleshooting with additional information from https://discord.com/channels/707636530424053791/1213529490525917265
> docs: Adds troubleshooting page

- cmd/dagger/flags.go
Reported here: https://github.com/dagger/dagger/pull/6829#discussion_r1513464630
Based on my testing, the following did not work:
```
dagger call foo --token env:TOKEN
echo $TOKEN > token.txt
dagger call foo --token file:./token.txt
```
Breaking out the file parsing code, the `token.txt` would be parsed with a newline character at the end.
This adds `TrimSpace()` to file and cmd secret inputs. `TrimSpace()` trims leading and trailing unicode whitespace characters. I can't think of any cases where this would have unintended consequences for secrets.
> fix file and cmd secret source inputs

- .github/workflows/publish.yml
- sdk/typescript/test/connect.spec.ts
This is used by the `publish.yaml` workflow on the main branch.
If this spec does not run, that workflow fails.
Follow-up to:
- https://github.com/dagger/dagger/pull/6831
> typescript: Re-enable CLI binary test

- docs/current_docs/quickstart/883939-containers.mdx
This commit makes our examples consistent with the rest of the docs by changing the examples to use the `dagger -m $MODUDLE call` pattern.
> make dagger -m examples consistent

- docs/current_docs/developer-guide/typescript/370239-module-structure.mdx
CC https://discord.com/channels/707636530424053791/1215420048865362030
This commit updates the documentation to use functions instead of fields to access sub classes
> fix: use funcs for multiples files modules in TypeScript

- RELEASING.md
- go.mod
- internal/mage/go.mod
- internal/mage/go.sum
I have captured a bunch of things in `RELEASING.md` that we have been missing for too long. That is possibly the most important change, the rest is standard, i.e. `0.10.1` -> `0.10.2` bump.
> Improve releasing during v0.10.2

- sdk/typescript/.changes/unreleased/Fixed-20240313-092936.yaml
- sdk/typescript/entrypoint/load.ts
- sdk/typescript/introspector/test/invoke.spec.ts
- sdk/typescript/introspector/test/scan.spec.ts
- sdk/typescript/introspector/test/testdata/multipleObjectsAsFields/expected.json
- sdk/typescript/introspector/test/testdata/multipleObjectsAsFields/index.ts
- sdk/typescript/introspector/test/testdata/multipleObjectsAsFields/lint.ts
- sdk/typescript/introspector/test/testdata/multipleObjectsAsFields/test.ts
Fix https://discord.com/channels/707636530424053791/1215420048865362030
I was overriding the variable `object` in `loadResult` which broke the loop.
Instead, I use a sub variable inside the loop to store the referenced object and everything went back to normal.
> fix(tsSDK): fix object reference on object's fields

- docs/current_docs/guides/821742-publish-modules.mdx
The `Notes` update is a suggestion since they are not visible enough IMO. 
I'm using the Admonition from Docusaurus.
Let me know if you rather roll back to the original style @vikram-dagger. Thanks 🙏
> Docs - fix typo on the Daggerverse modules publish page

- .changes/unreleased/Fixed-20240313-155031.yaml
- core/container.go
- core/integration/container_test.go
Reported by user in [Discord](https://discord.com/channels/707636530424053791/1217212533354533036/1217453431229386793).
When the path to `Container.withFiles` is absolute:
```go
ctr := c.Container().
From("alpine").
WithWorkdir("/work").
WithFiles("/opt/myfiles", files)
```
The files were being copied incorrectly:
```
copy /file1 /opt/opt/myfiles/file1
copy /file2 /opt/opt/myfiles/file2
```
With this PR:
```
copy /file1 /opt/myfiles/file1
copy /file2 /opt/myfiles/file2
```
> Fix `Container.withFiles` not respecting absolute paths

- cmd/dagger/flags.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
Fixes #6897
An empty secret value produced a non-empty `":"` string representation:
```diff
Flags:
-      --access-token Secret    mastodon access token (default :)
+      --access-token Secret    mastodon access token
```
> Fix empty Secret default in CLI

- core/directory.go
- core/integration/directory_test.go
- core/schema/directory.go
- docs/docs-graphql/schema.graphqls
- engine/buildkit/filesync.go
- engine/client/client.go
- engine/opts.go
- sdk/elixir/lib/dagger/gen/directory.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Directory.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Related discord thread: https://discord.com/channels/707636530424053791/1220078037542895617/1220078037542895617
By default, exporting a directory resulted in its contents being merged into the target directory on the host, with any files that existed on the host but not in the source dir being untouched during the export.
More often than not, this is the behavior you want, but there are use cases where you'd instead like to replace the contents of the host directory entirely such that it exactly matches the source dir being exported. This enables you to e.g. load a dir from the host, delete some files from it and then export that back to the host with those deletes being reflected.
This change adds an arg to `Directory.export` to enable that behavior.
I really wanted to name the arg …
> core: add support for wipe arg to Directory.export

- .changes/unreleased/Fixed-20240319-115521.yaml
- core/directory.go
- core/integration/directory_test.go
> Fix Directory.glob on directories with a sub path

- core/integration/module_config_test.go
Introduced in https://github.com/dagger/dagger/pull/6860, causing some additional test flake.
This manifested as additional flakiness in the test, causing `out` to be written to in a racey way:
WARNING: DATA RACE
Write at 0x00c00189a6c0 by goroutine 20341:
github.com/dagger/dagger/core/integration.TestModuleDaggerDevelop.func1.1()
/app/core/integration/module_config_test.go:542 +0x9bd
testing.tRunner()
/usr/local/go/src/testing/testing.go:1595 +0x261
testing.(*T).Run.func1()
/usr/local/go/src/testing/testing.go:1648 +0x44
Previous write at 0x00c00189a6c0 by goroutine 20342:
github.com/dagger/dagger/core/integration.TestModuleDaggerDevelop.func1.1()
/app/core/integration/module_config_test.go:542 +0x9bd
testing.tRunner()
/usr/local/go/src/testing/testing.go:1595 +0x261 …
> fix: prevent variable shadow in TestModuleDaggerDevelop

- sdk/elixir/test/dagger/client_test.exs
Instead of start Dagger session when test block start executing, start it only once when test suite start except test that uses `Dockerfile` since it has failure because of `Dockerfile` not found error sometimes.
> chore(sdk/elixir): speed up client tests

- docs/current_docs/quickstart/292472-arguments.mdx
Add ' for --dir command to work using branch and subdir
At least using iterm on mac I had to add '' arround the dir flag argument.
> apostrophe around the dir flag argument

- .changes/unreleased/Fixed-20240325-145705.yaml
- core/integration/module_test.go
- engine/opts.go
The issue (found at kubecon :tada:):
```
$ pwd
/tmp/work/fooé/test
$ dagger init --sdk=go --source=.
✘ ModuleSource.resolveContextPathFromCaller: String! 0.0s
Error: failed to get configured module: failed to get local root path: input: moduleSource.resolveContextPathFromCaller resolve: failed to find up root: failed to lstat .git: failed to create diff copy client: rpc error: code = Internal desc = rpc error: code = Internal desc = header key "dir-name" contains value with non-printable ASCII characters
```
A similar issue was resolved in buildkit a while back: https://github.com/moby/buildkit/pull/3946
However, because we have our own filesync implementation, we need our own fix. To do this, I've just imported the helpers from upstream, in a copy-paste job (since they're not exported, …
> fix: avoid internal error for unicode path elements

- .github/workflows/publish.yml
- sdk/typescript/package.json
After merging https://github.com/dagger/dagger/pull/6615, various provision tests that run on `main` started failing: https://github.com/dagger/dagger/actions/runs/8433279441/job/23094090218.
We should run our bun tests in CI - to do this we need to install bun dependencies in our GitHub provision test workflows.
Additionally, we restore the old `test` script to run both the bun and nodejs tests, so that `yarn test` continues to work.
> fix: ensure typescript provision tests work

- sdk/elixir/lib/dagger/codegen/generator.ex
In https://github.com/dagger/dagger/pull/6905, we changed the HTTP client.
However, we also need to update the HTTP client usage for generate - this ensures that `./hack/make sdk:elixir:generate` can now run again.
> fix: translate elixir codegen http req

- sdk/elixir/mix.exs
Start `:ssl` application to make it work during download Dagger binary from https site. Tested by remove Dagger binary out of cache directory (`~/.cache/dagger/dagger-<version>`) then run mix test under `sdk/elixir` again.
> fix(sdk/elixir): fix SDK crash when downloading the dagger binary

- sdk/elixir/mix.exs
- sdk/elixir/mix.lock
`Nestru` is now used only in `dagger_codegen` but not for the SDK. This patch remove it out of the SDK.
> chore(sdk/elixir): remove :nestru dependency

- sdk/elixir/dagger_codegen/lib/dagger/codegen/elixir_generator/formatter.ex
- sdk/elixir/dagger_codegen/test/dagger/codegen/elixir_generator/formatter_test.exs
For example, if the type is name `do`, the codegen will normalize the name into `do_`.
Closes #6940
> feat(sdk/elixir): add _ suffix to any function name that collide with std

- core/integration/git_test.go
- core/schema/git.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/git_repository.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/GitRepository.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Fixes https://github.com/dagger/dagger/issues/3670
This allows for grabbing the default branch, according to point 1 in https://github.com/dagger/dagger/issues/3670#issuecomment-2022321233.
Potentially, we could rework the git API a bit more in the future, but that feels out-of-scope for this issue right now.
> feat: add git `Head`

- engine/client/drivers/docker.go
Should fix the currently failing provision tests on `main`: https://github.com/dagger/dagger/actions/runs/8536672759/job/23386879376
The new `traceExec` function introduced in #6835 was discarding all stdout/stderr - we need to capture this so that we can detect the case of multiple engines being spun up in parallel with each other.
> fix: traceExec in docker driver should capture stderr

- cmd/dagger/main.go
- cmd/engine/logger.go
- cmd/engine/main.go
- cmd/engine/telemetry.go
- telemetry/sdklog/logger.go
- telemetry/sdklog/otlploghttp/transform/transform.go
- telemetry/servers.go
follow-up to #6835 
* fix extra `--help` output caused by two-pass flag parsing
* fix engine inheriting `DAGGER_CLOUD_TOKEN` and sending redundant data to Cloud
* send engine logs to Cloud over OTLP
> post-OpenTelemetry clean-ups/fixes

- engine/client/drivers/docker.go
Fixes https://github.com/dagger/dagger/issues/6989, ~~confirmed with a (particularly gnarly) integ test~~ the integ test didn't work *only in the test workflow on our EKS engine* so I had to remove it but still confident this fixes it, see comments below
> engine client: fix env propagation to docker subcommand

- install.sh
> chore: gracefully handle a dagger version with a leading v prefix

- .github/workflows/publish.yml
- sdk/typescript/package.json
This fixes the currently failing typescript tests on `main`: https://github.com/dagger/dagger/actions/runs/8549788696/job/23425690833
This was the intention - but with the node/bun split, we were running *all* the tests for node, and only one of the tests for bun:
$ yarn run test:node && yarn run test:bun -g 'Automatic Provisioned CLI Binary'
The other tests aren't designed to run in this environment, so should be skipped.
> fix: only run one test for typescript provision tests

- cmd/shim/main.go
some things _only_ look for that instead of the more specific vars
> shim: set OTEL_EXPORTER_OTLP_PROTOCOL too

- ci/mage/util/dagger.go
It'll pick the right thing all on its own; no need to manually set it. This way we can still have the nice TUI in `./hack/dev`
> ci: don't set --progress=plain

- ci/build/builder.go
- ci/cli.go
- ci/engine.go
- ci/mage/cli.go
- ci/mage/engine.go
- ci/main.go
- ci/sdk_go.go
- ci/version.go
Follow-up to #6843.
Fixes:
- Broken Go SDK publish on `main`: https://github.com/dagger/dagger/actions/runs/8602295935/job/23571547672
- Due to an incorrect refactoring, we need to restore some of the original functionality
- Broken image publish on `main`: https://github.com/dagger/dagger/actions/runs/8602589466/job/23572487550
- Due to completely inconsistent handling of version data
- Instead of just applying a simple fix in the shim, we need to rework how versioning works entirely. Now it's a top-level arg in the constructor, and when that's not provided, we try and cleverly load it from git.
- By having this at the top-level now, we ensure that all of the binaries produced have the right tags specified (which they weren't really before :scream:)
> Modularize CI followups

- ci/mage/engine.go
`env:` prefix is only supported for secrets.
Agh, more: https://github.com/dagger/dagger/actions/runs/8613689129/job/23605520739
> ci: fix mage registry username

- ci/mage/engine.go
- ci/mage/util/dagger.go
- ci/mage/util/docker.go
- ci/test.go
See https://github.com/dagger/dagger/pull/6843#discussion_r1552464269 (this behavior was originally removed, this PR just restores it to the prior state)
This ensures that we use the host creds in the test container, so we don't end up maxing out our anonymous usage of docker hub.
We may be able to get rid of this once #6916 lands? But in the meantime, we're seeing a ton of ephemeral failures which are quite annoying :tada:
> ci: forward host docker dir into tests

- .github/dependabot.yml
Spotted this failure just now: https://github.com/dagger/dagger/pull/6959/checks?check_run_id=23515980223
No aliases :cry: https://github.com/dependabot/dependabot-core/issues/1582
This regression was introduced in #6811.
> ci: remove yaml aliases

- cmd/dump-id/main.go
- dagql/idtui/frontend.go
- dagql/idtui/output.go
- dagql/idtui/streaming_output.go
> feat: added support for streaming stdout when --progress=plain

- .github/workflows/_hack_make.yml
- .github/workflows/publish.yml
Came across this while working on continued modularization - ideally, we want to end up in a place where *all* of our CI is just a `dagger call` away! Then we can use https://github.com/dagger/dagger-for-github, and dogfood that more.
This step is more fiddly to modularize (which we want to do so it would show up in dagger cloud) - I think it can be done, but I think we might also just be able to remove it. It was added quite a while ago in https://github.com/dagger/dagger/pull/3785, to help debug https://github.com/dagger/dagger/issues/3784 - which now doesn't occur anymore.
I think it makes sense to just remove these now, I personally have never used them, and they just provide a little bit of friction when trying to scan for failures! If anyone *has* used them recently, I can port them …
> ci: remove kernel logs from github logs

- core/container.go
- engine/buildkit/client.go
- telemetry/attrs.go
- telemetry/graphql.go
This data allows the UI to track where lazy operations came from so we can tie them back to the call site that installed them (i.e. `withExec`). This visualization angle is super useful when you're trying to gauge the "cost" of API calls.
Something like this (note the "shadow bars" - UI subject to change):
**NOTE:** As a prerequisite, I moved the `ftp_proxy` hackery back to `Container.WithExec` instead of doing it "just-in-time" in the Buildkit client. Otherwise the span ends up with a different digest than what we return, so they can't be correlated at all. The switch from Progrock => OpenTelemetry allows us to do this, I believe; we couldn't before because we had to pass the Progrock parent vertex ID, but the OpenTelemetry equivalent is handled for us by Buildkit itself.
(edit - side …
> telemetry: record an API call's LLB op digests

- .github/workflows/_hack_make.yml
At the moment our CI costs have gotten quite high. As a way of optimizing (although we are unsure of how much this will help us) we want to reduce the amount of parallel jobs running. The current setup is allowing all jobs of all commits in a PR to complete, even when new commits have been pushed. While this can certainly be useful, it is way too costly. Each time we run jobs for a pull request in our legacy CI we are requesting approximately 64 cores and 384 Gi of memory. This is definitely excessive and until we can optimize it we believe it makes sense to allow a single parallel run per job per pull request.
This PR leverages the `mage-targets` to separate the job itself and uses the `head_ref` when in a PR to have a single instance per PR. When running in main we allow for every …
> Run a single instance of each job per pull request

- .changes/unreleased/Fixed-20240415-151604.yaml
- dagql/idtui/frontend.go
Fixes #7045 (nightmare issue yay)
Essentially, with the new TUI, we were failing to set the TUI to raw mode. The reason for this was that we were passing a non-input buffer to containerd/console (through os.Stdin). Unlike on *nix, on windows, the raw mode we were trying to set is *not* interchangeable between stdin/stdout.
Something is insanely weird about what bubbletea is doing here - it's making *loads* of funky assumptions about how terminals can be constructed, and honestly I'm not sure how it works. However, it seems like we can get the right behavior as long as we preserve the differences between input and output buffers - instead of creating one single tty to pass around, we keep two file objects around.
> fix: preserve windows output

- RELEASING.md
- install.ps1
Fix https://github.com/dagger/dagger/issues/6901.
This script was removed in https://github.com/dagger/dagger/commit/5a9c772020363668c18e73472534f01a5b03b8d5, and we still have windows install instructions, so we should probably restore this!
I've also updated the script with a few additions, like making the function names map to the same as the unix script.
> chore: restore install.ps1

- cmd/dagger/module.go
- telemetry/labels.go
Fixes https://github.com/dagger/dagger/issues/7030.
Git worktrees use a `.git/commondir` to ensure that refs and similar are shared. We need to explicitly enable this with go-git.
Technically, this change is only required in the `telemetry` package to fix the above issue, but we can also just add it everywhere that we call this function.
> fix: ensure git labels can use worktrees

- ci/mage/sdk/elixir.go
Elixir publish `--hex-apikey` had a typo:
$ dagger call --source=. sdk elixir publish --help
Publish the Elixir SDK
Usage:
dagger call sdk elixir publish [flags]
Flags:
--dry-run
--hex-apikey Secret
--tag string
Global Flags:
-d, --debug             show debug logs and full verbosity
--json              Present result as JSON
-m, --mod string        Path to dagger.json config file for the module or a directory containing that file. Either local path (e.g. "/path/to/some/dir") or a github repo (e.g.
"github.com/dagger/dagger/path/to/some/subdir")
-o, --output string     Path in the host to save the result to
--progress string   progress output format (auto, plain, tty) (default "auto")
-s, --silent            disable terminal UI and progress output
-v, --verbose count     increase …
> ci: fix elixir publish

- ci/sdk_elixir.go
Ugh, *again*. The elixir path wasn't right here, this would mean we were instead publishing v0.0.0.
> ci: fix elixir publish version

- .github/workflows/_hack_make.yml
- .github/workflows/publish-helm-chart.yml
- .github/workflows/publish-sdk-elixir.yml
- .github/workflows/publish-sdk-go.yml
- .github/workflows/publish-sdk-php.yml
- .github/workflows/publish-sdk-python.yml
- .github/workflows/publish-sdk-rust.yml
- .github/workflows/publish-sdk-typescript.yml
- .github/workflows/publish.yml
- ci/build/builder.go
- ci/consts/versions.go
- core/integration/images.go
This patch updates all the go base images to versions that have go 1.22.
Note! We can't update the version used to build runc, due to an upstream incompatability - however, because the build is separate, we can keep building it using an older version of go.
Also note, we can't *yet* bump to actually use 1.22 in our code by updating the go.mod. This is because the `ci` package must continue using 1.21 until the next release (insert elaborate codegen reasons here) - and then the `ci` package depends on the top-level package, so that must also stay at 1.21. There *is* a potential workaround that would allow us to split out `distconsts` into it's own go.mod, and then we could do this, but this can be a follow-up if we really want this.
> chore: update images to go 1.22

- ci/README.md
Required after a fresh clone.
Also:
- Bump ci module Engine version to v0.11.1
- Remove `$` from ci README code snippets
> chore: Add ci module `dagger develop` info to README

- ci/config.go
- ci/engine.go
- ci/mage/engine.go
- ci/mage/util/const.go
- cmd/engine/main.go
- engine/buildkit/client.go
- engine/server/buildkitcontroller.go
- engine/server/server.go
Right now if something goes wrong internal to the shim before all the OpenTelemetry plumbing can be wired up, you just get an `exit status 125` with no other output. (The shim currently has to manually send the command's stdout/stderr to OpenTelemetry logging, so there are extra moving parts.)
I added a "break glass to debug telemetry" bit that prints Buildkit logs to stderr, but didn't make it configurable, figuring it would only be useful to me while I bootstrap the OpenTelemetry stack.
But now, as is tradition, a user has a hit this case in production.
So with this PR, now when the engine is configured with `debug = true` it'll also print Buildkit's logs in console format to stderr like this:
```
time="2024-04-17T03:31:29Z" level=debug msg=Unauthorized header="Bearer …
```
> engine: log buildkit progress to stderr with debug enabled

- cmd/dagger/main.go
Part of the de-clutter CLI implementation: https://github.com/dagger/dagger/issues/6943#issuecomment-2021310987.
Suggested by @helderco and looks (in my sense) better. Takes inspiration from the `gh` CLI to visually break the heading sections. It relies on a helper function directly used on the template.
New style:
> cli: style headings in BOLD UPPERCASE to help break sections visually

- cmd/dagger/query.go
One of the action items discussed in https://github.com/dagger/dagger/pull/7107#issuecomment-2061525961
`dagger query` is not the main entrypoint of the dagger CLI anymore. Even though the special template made some sense, it is a code duplication to maintain. With the upcoming changes (titles in bold, etc ...) and the remaining presence of the example on the command's help, it does make sense to remove it and keep a single source of truth
```shell
./dagger query --help
Send API queries to a dagger engine.
When no document file is provided, reads query from standard input.
Can optionally provide the GraphQL operation name if there are multiple
queries in the document.
Usage:
dagger query [flags] [OPERATION]
Aliases:
query, q
Examples:
dagger query <<EOF
{
container { …
```
> cli: remove special template on query subcommand

- cmd/codegen/generator/go/templates/modules.go
- cmd/codegen/generator/go/templates/modules_test.go
Pragmas were not being correctly parsed when we had windows line endings - this fix ensures that we correctly handle these.
This was resulting in some *very* weird to debug issues where optional arguments could be detected as required instead.
> fix: parse go pragmas with CRLF line endings

- hack/dev
- hack/make
- hack/with-dev
Essentially, by calling `readlink` on the source, we can get the location without any symlinks. This allows a dev (like me) to create a symlink to these scripts, dump those in a `bin` folder somewhere on my system and then access them from anywhere.
> chore: allow symlinking to hack scripts

- core/integration/engine_test.go
- core/integration/remotecache_test.go
:tada: This fixes DaggerRun, so hopefully we can have our CI go green again! (cc @matipan @gerhard who helped investigate)
This was "introduced" in #7069, when we changed our plain progress to include colors - in conjunction with the new TUI output, this means that we don't have a plain "Container.From", instead, we have magical control codes strewn throughout it. The trick to fix this, is to just set `NO_COLOR`, and the test passes again!
However! There's another issue here - this test was always "failing". The `from` in it was *never* working, due to network issues. We weren't setting the right network/cidr range, which we *were* doing in other tests, this was likely causing some network conflict (since these are required to be unique). We need to properly set this for *every* dev …
> fix: make TestDaggerRun pass

- cmd/dagger/main.go
One of the action items discussed in https://github.com/dagger/dagger/pull/7107#issuecomment-2061525961. With added context from @helderco [here](https://github.com/dagger/dagger/pull/7107#issuecomment-2065511351)
Reposition flags below commands to find them more easily on big subcommand outputs.
```shell
./dagger -m github.com/levlaz/daggerverse/mariadb@v0.2.1 call base --help
Return MariaDB Container
USAGE
dagger call base [flags]
dagger call base [flags] [command]
FUNCTION COMMANDS
as-service                    Turn the container into a Service.
as-tarball                    Returns a File representing the container serialized to a tarball.
build                         Initializes this container from a Dockerfile build.
default-args                  Retrieves default arguments for …
```
> cli: repositioning flags below all commands

- cmd/engine/cacerts/cacerts.go
- cmd/engine/cacerts/distros.go
- cmd/engine/cacerts/fs.go
- cmd/engine/executor.go
- cmd/engine/main.go
- cmd/engine/main_oci_worker.go
- cmd/shim/main.go
- core/integration/cacert_test.go
- core/integration/images.go
Still some cleanup left, but good enough for feedback. TODOs:
* I'm personally good with this now. These codepaths only get hit when users have a custom engine w/ CA certs installed and I made the install best-effort with cleanup in case of errors. Still open to feedback from others on this though.
---
This adds support for automatic installation of custom CA certs to containers. Originally this was gonna just be the first step outlined [here](https://github.com/dagger/dagger/issues/6599) but as I started implementing the CA certs part it required enough complication that it seemed best to just implement the full support for automatic CA installation for all containers.
* https://wiki.archlinux.org/title/Transport_Layer_Security
* https://go.dev/src/crypto/x509/root_linux.go
* @vito's …
> core: support automatic installation of custom CA certs.

- telemetry/servers.go
when I want to add feature for linter  [`makezero`](https://github.com/ashanbrown/makezero) in PR https://github.com/ashanbrown/makezero/pull/15 , I run a github action for real world repos,  and github action report this bug.
I not going to add this `makezero` to your `golangci.yaml` , but I suggest to set to `enable-all: true` and add some `disable` linters.
> Fix miss makezero bug

- .changes/unreleased/Added-20240423-103802.yaml
- core/schema/query.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/client.ex
- sdk/go/dag/dag.gen.go
- sdk/go/dagger.gen.go
- sdk/php/generated/Client.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Before this, there was no way to get the version of an engine - this is *really* useful if the engine is running remotely, and you want to make a query for it to get it programatically (it's always been possible by analyzing logs, etc).
One of my main use cases is for working out what version of dagger the playground is using: https://play.dagger.cloud/playground - there's actually no way to do that right now (this PR would let you).
What feels frustrating is that `checkVersionCompatibility` is *almost* the right method call, but doesn't actually give you the raw data.
> feat: add version graphql call to get engine version

- ci/build/builder.go
- ci/build/sdk.go
Using functions that can error in `Container.With` is a bad idea. So, what we can do is to put the actual computation into an error group (which has the convenient little side-effect that they all get computed in parallel, hopefully improving build times).
This lets us remove the panic, which was crashing the binary. Because of (I think) telemetry draining, this meant that the client job hung forever on this kind of failure.
cc @helderco I know we discussed previously :tada:
> ci: avoid panic in sdk building

- ci/build/builder.go
Fixes a couple of instances where the base object is changed instead of the copy.
> ci: stick to fluent builder pattern.

- .github/workflows/_hack_make.yml
- .github/workflows/docs.yml
- .github/workflows/helm.yml
- .github/workflows/sdk-elixir.yml
- .github/workflows/sdk-go.yml
- .github/workflows/sdk-java.yml
- .github/workflows/sdk-python.yml
- .github/workflows/sdk-rust.yml
- .github/workflows/sdk-typescript.yml
The default is 360 minutes (6 hours) - at this point, something has *definitely* gone wrong for us, so we should explicitly fail.
Also, for jobs that are known to be short, we can cap at 10 minutes: specifically SDK linting + testing jobs.
This would have prevented long run-away jobs like we discovered with the failed typescript linting intersecting with a crash (causing a client hang):
- https://github.com/dagger/dagger/pull/7153
- https://github.com/dagger/dagger/pull/7154
> ci: add max timeout of 1 hour for hack/make workflows

- .golangci.yml
- ci/engine.go
- cmd/dagger/module.go
- core/modfunc.go
- core/schema/host.go
- core/schema/modulesource.go
- core/schema/query.go
- engine/buildkit/blob.go
- engine/buildkit/client.go
- engine/buildkit/containerimage.go
- engine/buildkit/filesync.go
- engine/client/client.go
- engine/opts.go
- sdk/go/internal/engineconn/session.go
Fixes #6923 #7114 (second time's the charm hopefully), follow-up to #7003.
*Right*. Descriptions are split up into commits to make it a bit easier to understand, but TL;DR, there were two main issues:
- Paths weren't being correctly decoded after being encoded on the wire - I should have caught this and didn't (my bad). The correct way to do this is to handle the encoding/decoding as close as possible in the code to sending/receiving, then it doesn't sneak everywhere through the code.
- Windows has different file-not-found message strings for `os.Stat` and `os.ReadFile` (for reasons, I have no idea). We were missing a check for the message you get from `os.ReadFile` ("The system cannot find the file specified"). Instead of adding *yet another check*, I move the check to the client with …
> fix: all paths should be encoded over-the-wire

- docs/current_docs/quickstart/292472-arguments.mdx
- docs/current_docs/quickstart/562821-hello.mdx
- docs/current_docs/quickstart/822194-daggerize.mdx
- docs/current_docs/quickstart/853930-directories.mdx
- docs/current_docs/quickstart/883939-containers.mdx
This commit improves the Go builder example in the quickstart based on the discussion at https://discord.com/channels/707636530424053791/1223010377097547857
It also fixes the shell output snippets, which in some cases were being automatically colorized by the syntax highlighter, even though the actual output seen by the user would not be colorized.
> docs: Improves Go builder example in quickstart

- cmd/dagger/call.go
- cmd/dagger/config.go
- cmd/dagger/functions.go
- cmd/dagger/gen.go
- cmd/dagger/listen.go
- cmd/dagger/main.go
- cmd/dagger/module.go
- cmd/dagger/query.go
- cmd/dagger/run.go
- cmd/dagger/session.go
- cmd/dagger/version.go
- cmd/dagger/watch.go
- docs/current_docs/reference/979596-cli.mdx
One of the action items discussed in https://github.com/dagger/dagger/pull/7107#issuecomment-2061525961. It is the first one out of 3, discussed with Helder
Branched from https://github.com/dagger/dagger/pull/7143, which needs to be merged prior this one.
1. Rename all the flag mentions to "options", as proposed by Helder in https://github.com/dagger/dagger/pull/7107#issuecomment-2061525961
2. Remove the automatic [flags] append on all commands: https://github.com/dagger/dagger/pull/7107#discussion_r1569024798
- Removed the branch out from #7143, as Helder suggested
- Implemented comments discussed below: 
- Added `<pattern>` to `add` subcommand
- Removed `[options]` from commands with just global flags.
- Fix usage of watch command also (as it touched the "removed `[options]` from …
> cli: rename `flags` to  `options`

- helm/dagger/templates/engine-daemonset.yaml
- helm/dagger/values.yaml
Allows the user to set the `priorityClassName` in the Helm Chart to avoid eviction and ensure that the Dagger engine is always present on the node.
> helm: Add `priorityClassName` to Helm Chart

- docs/current_docs/integrations/snippets/argo-workflow.yaml
This commit removes the hardcoded version in the snippet in favour of a placeholder. There were already other placeholders in the snippet, so this should not cause a major disruption. More information in https://discord.com/channels/707636530424053791/1231554152815919114/1231554152815919114
> docs: Uses version/arch placeholder in Argo Workflow snippet

- sdk/elixir/dagger_codegen/lib/dagger/codegen/elixir_generator/renderer.ex
- sdk/elixir/lib/dagger/gen/container.ex
Follow-up conversation in
https://github.com/dagger/dagger/pull/6559#discussion_r1539733323. The function in backquote should convert to snake case only deprecation message.
Fixes #6939
> fix(sdk/elixir): format function only deprecation message

- .trivyignore.yaml
- ci/engine.go
This feels insane, I'm not quite sure what is going on here. There appear to be 2 separate vulnerability advisories, one in runc and one in cri-o (which doesn't seem to be available yet).
However, this issue definitely doesn't affect us - we don't use cri-o anywhere in our stack, we're not spawning pods in the dagger engine, etc.
There's also not a version of runc we can feasibly upgrade to - 1.2.0-rc1 (as suggested in https://github.com/advisories/GHSA-c5pj-mqfh-rvc3), is a minor release, and is also an RC, so we shouldn't depend on it.
We should keep an eye on what the status of these vulnerabilities are, since disclosure still seems ongoing, but we can at least stop CI going red on these.
> ci: mark CVE-2024-3154 as a false scan positive

- dagql/idtui/types.go
Still not sure why this happens, but I'll be on PTO soon, so best to apply a band-aid for now.
So far I've only seen this happen when there's total loss of data from the `dagger-engine` otel service, indicating something went very wrong with the engine pub/sub, since that's >~90% of the data.
A log will help for now.
> avoid panic when masked parent is missing

- docs/current_docs/integrations/snippets/gitlab.yml
Fixes gitlab beore script by installing the Dagger CLI in a location that's availabe in the $PATH
> fix gitlab before_script

- core/integration/container_test.go
- core/integration/services_test.go
- sdk/go/client_test.go
- sdk/rust/crates/dagger-sdk/tests/mod.rs
- sdk/typescript/api/test/api.spec.ts
Use these newer methods instead of using `container` and `file` to load IDs, which is deprecated and *going to be removed soon*.
This is now possible because of #7038, and is a step towards #6934.
> chore: use `load*FromID` in tests

- telemetry/servers.go
We use a StringSlice for process args, so we actually hit this branch pretty often. Here's a quick and dirty attempt at handling the cases that we can handle.
> telemetry: handle more attr type conversions

- .trivyignore.yaml
Follow-up to https://github.com/dagger/dagger/pull/7215.
It looks like https://github.com/advisories/GHSA-c5pj-mqfh-rvc3 has now been withdrawn - trivy seems to have picked up on this now, so we can remove this file now :tada:
> chore: remove .trivyignore.yaml

- .github/dependabot.yml
With this typo, the yaml file was invalid and so the config failed to be applied.
I *finally* found where you can check the validity of a dependabot config - see https://github.com/dagger/dagger/network/updates.
> chore: fix yaml error in dependabot

- .changes/unreleased/Changed-20240503-160132.yaml
- cmd/dagger/main.go
One of the action items discussed in https://github.com/dagger/dagger/pull/7107#issuecomment-2061525961
Append [required] to flags that are marked as required. As proposed by Helder, this follows the behavior of Typer: https://typer.tiangolo.com/tutorial/options/required/
Required flags are shown first, then option arguments are shown. Apart from this, they are sorted in the order of the first flagset: https://discord.com/channels/707636530424053791/1232477387724292209/1232711077415092295
**Example**
```shell
./dagger -m github.com/jpadams/chainloop@8374b22aee238452467bd712e874937b8e4254c9 call  init --help
OPTIONS
--token Secret               Chainloop API token [required]
--contract-revision string   Workflow Contract revision, default is the latest
--repository Directory       Path to …
```
> cli: visual cue for required flags

- ci/build/builder.go
- ci/consts/versions.go
- ci/engine.go
- ci/mage/engine.go
- ci/main.go
This PR adds the option of running the engine on top of the Wolfi base image.
There are some advantages to using Wolfi here:
- similarly small size to the Alpine image
- support for glibc
- support for GPU tools
This PR is really a work-in-progress, but I wanted to get some feedback. To test, I manually [set the base image in the struct](https://github.com/dagger/dagger/blob/main/ci/build/builder.go#L71), ran `hack/dev` then verified the engine container was running on-top of Wolfi.
Missing pieces:
- plumbing through setting the base image to allow user to choose wolfi/debian/alpine
- running tests (the suite is a bit overwhelming and I get failures with main)
Let me know if what I've done so far makes sense. 
It would be great to get some help with the remaining tasks, while they're not …
> ci: Add Wolfi base

- ci/cli.go
- ci/mage/cli.go
Bleh, I broke this in https://github.com/dagger/dagger/pull/7234.
Goreleaser needs this :(
> ci: ensure cli release has git dir

- docs/current_docs/manuals/administrator/cloud/413929-caching.mdx
- docs/current_docs/manuals/administrator/cloud/index.mdx
- docs/sidebars.ts
This commit adds a page to the admin manual about the Dagger Cloud cache, implementation and security.
> docs: Adds information on Dagger Cloud cache

- ci/sdk_elixir.go
Upgrading the Erlang/OTP to fix Erlang
https://github.com/erlang/otp/issues/8238 bug.
> fix(sdk/elixir): fix sdk:elixir:generate task crash

- .changes/unreleased/Changed-20240505-232946.yaml
- .changes/unreleased/Changed-20240505-234902.yaml
- cmd/dagger/call.go
- cmd/dagger/functions.go
- cmd/dagger/main.go
- docs/current_docs/reference/979596-cli.mdx
Follow up to:
- https://github.com/dagger/dagger/pull/7262#pullrequestreview-2038470837
- https://github.com/dagger/dagger/pull/7143
Part of:
- https://github.com/dagger/dagger/issues/6943
- Removed `COMMANDS` from the list of subcommands heading, in favor of just `FUNCTIONS`.
- Added `[arguments]` and `<function>` to the usage line when appropriate.
- Flags created for function arguments are split into its own `ARGUMENTS` section. So constructor arguments will now appear separately from call’s own flags.
> cli: use "functions" and "arguments" instead of "commands" and "options" in `dagger call --help`

- cmd/dagger/main.go
Every section was indented except for the examples.
Follow up to:
- https://github.com/dagger/dagger/pull/7286
Part of:
- https://github.com/dagger/dagger/issues/6943
> cli: indent examples in `--help`

- .github/workflows/_async_hack_make.yml
- .github/workflows/_hack_make.yml
- .github/workflows/cfg-runner.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/sdk-rust.yml
This switches all our GitHub workflows to use the second generation of Dagger Runners. They are based on [Run Dagger on Amazon EKS with GitHub Actions Runner and Karpenter](https://archive.docs.dagger.io/0.9/934191/eks-github-karpenter), currently running:
- AWS EKS `v1.28.7`
- Karpenter `v0.32.0`
As of today, we expose the following runner options:
- `dagger-v0-10-1`
- `dagger-v0-10-2`
- `dagger-v0-10-3`
- `dagger-v0-10-3-4c`
- `dagger-v0-10-3-8c`
- `dagger-v0-10-3-16c`
- `dagger-v0-11-0`
- `dagger-v0-11-0-4c`
- `dagger-v0-11-0-8c`
- `dagger-v0-11-0-16c`
- `dagger-v0-11-1`
- `dagger-v0-11-1-4c`
- `dagger-v0-11-1-4c-nvme`
- `dagger-v0-11-1-8c`
- `dagger-v0-11-1-8c-nvme`
- `dagger-v0-11-1-16c`
- `dagger-v0-11-1-16c-nvme`
- `dagger-v0-11-2`
- `dagger-v0-11-2-4c`
- `dagger-v0-11-2-4c-nvme`
- …
> Migrate to new ci runners

- core/schema/container.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Container.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Just a doc string update, but something odd is happening when I run `./hack/make sdk:elixir:generate` locally:
```
✘ DaggerElixirSdk.generate: Directory! 11.8s
! call function "Generate": process "/runtime" did not complete successfully: exit code: 2
┃ marshal: json: error calling MarshalJSON for type *dagger.Directory: input: container.from.withWorkdir.withDirectory.withExec.withExec.withExec.withServiceBinding.withEnvVariable.withMountedFile.withEnvVariable.withExec.withMountedSecret.withWorkd
┃                                                                                                                                                                                                                                                        
┃ Stdout: …
```
> core: clarify withMountedTemp docs that they are ephemeral

- go.mod
- go.sum
We really want these bug fixes for the next release but they are still in PR upstream, so we made [a fork of buildkit in the dagger org](https://github.com/dagger/buildkit) and I cherry-picked those fixes.
* This fork is only intended to be used on temporary bases for situations like this where we want bug fixes but upstream hasn't updated yet. Not intended to be used for any long term divergence.
The upstream PRs with cherry-picked commits are:
- https://github.com/moby/buildkit/pull/4887
- https://github.com/moby/buildkit/pull/4902
> chore: use temporary buildkit fork with bug fixes pending upstream merge

- install.sh
The XDG_DATA_HOME env var can be empty (expectedly), and it breaks the printed bash completion setup instructions. This little PR makes the install script use the default $HOME/.local/share location when the XDG_DATA_HOME is empty. See  https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
> install.sh - fix bash completion instructions

- engine/buildkit/executor.go
We collected this output but didn't actually put it in the error message, which left us with only an exit code to debug with.
Now the actual output is there, which is much more useful.
> ca certs: include output of failed update command

- core/container.go
- core/integration/container_test.go
- core/integration/images.go
always resolves to the target image platform to set the Container
platform. 
we're currently defaulting to the `defaultPlatform` if  `ContainerOpts.Platform` is not set when creating the container. 
ref: https://play.dagger.cloud/playground/uIkzqEKNG9J
> engine: use image target image platform

- .changes/unreleased/Added-20240506-172454.yaml
- cmd/codegen/generator/typescript/templates/src/object.ts.gtpl
- sdk/typescript/api/client.gen.ts
- sdk/typescript/context/context.ts
- sdk/typescript/test/connect.spec.ts
> feat(tssdk): expose GraphQL client

- .github/workflows/_hack_make.yml
> [!WARNING]
> Merging this depends on merging https://github.com/dagger/dagger.io/pull/3693 first
The final step necessary to deprecate our old CI infra is to move testdev away. To do this in the new CI, we've made a new runner set available called `dagger-<VERSION>-dind`. This runners run on the same nvme instances as other nodes but with 16c and 16Gi requests and the docker socket mounted on them. This allows the runner to use docker commands which are required for testdev.
---
TODO:
- ~~Fix dagger-runner-gerhard-production workflow dispatch (seems to mainly be a permissions issue)~~ https://github.com/dagger/dagger/pull/7300/commits/1b9ab84626e75c75cdaa0d2568e18822ea5585d9
> Add testdev job with v2-dind runners

- .changes/unreleased/Fixed-20240507-224849.yaml
- cmd/dagger/shell.go
Uses `ts.stdout` instead of `ts.stdin` to get terminal size.
Fixes #7282
> fix: fix terminal broken on Windows

- .changes/unreleased/Breaking-20240507-134020.yaml
- cmd/dagger/flags.go
Fixes https://github.com/dagger/dagger/issues/7220
Reverts dagger/dagger#6845 given that seems like it triggers some edge cases that we haven't spotted and we don't seem to have a better option for now
> Revert secret whitespace stripping

- ci/mage/engine.go
This found during port a `hack/dev` script into PowerShell, the `engine:dev` task produce a Windows binary but didn't append `.exe` to the file name, cause Windows didn't know that it's a binary.
> fix: mage engine:dev didn't add .exe for Windows binary

- core/directory.go
- core/integration/directory_test.go
- sdk/typescript/runtime/dagger.json
- sdk/typescript/runtime/main.go
The TS SDK was very subtly broken when used from a git ref due to the fact that the `Directory.diff` logic was way too fragile (has existed since the beginning of time). This fixes that logic and updates the TS SDK to be slightly simpler now that it doesn't need to try to avoid that fragility. 
Individual commits have more detailed messages.
---
We also need to add integ tests that use SDKs other than go sourced from git refs. Starting the effort now, will send out a separate PR if this one is merged by the time I'm done.
> core: make Directory.diff logic less fragile

- core/integration/module_call_test.go
- core/integration/module_config_test.go
While in theory SDKs should be agnostic of whether module source is
coming from git, local dirs, etc. a very subtle issue arose recently
that broke TS modules only when sourced from Git (related to
Directory.diff path handling).
That would have been caught by coverage of those SDKs used from git,
so adding tests here. Verified that tests pass with `./hack/dev` but the
TS one fails if run direct against v0.11.3, so it's working as intended.
---
Related: https://github.com/dagger/dagger/pull/7328
Test repo change: https://github.com/dagger/dagger-test-modules/commit/2cb6cb4b0dba52c1e65b3ff46dd1a4a8f9a02f94
> tests: add coverage for non-go SDKs used from git

- .github/workflows/publish.yml
We probably want Publish Engine & CLI to re-use _hack_make. The main benefit of doing that is that we control the dagger version being used in a single place and trigger all jobs with the same logic. However, we can to unblock jobs from main quickly since we deleted the legacy CI and now no jobs can be execute.
> Migrate Publish Engine & CLI to the new CI

- .github/workflows/_hack_make.yml
- .github/workflows/_new_release_notification.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/helm.yml
- .github/workflows/publish-helm-chart.yml
- RELEASING.md
- ci/engine.go
- ci/go.mod
- dagger.json
- docs/current_docs/guides/snippets/github-google-cloud/main.yml
- docs/current_docs/partials/_install-cli.mdx
- docs/current_docs/quickstart/822194-daggerize.mdx
- go.mod
Signed-off-by: Justin Chadwell <me@jedevc.com>
> Improve releasing during v0.11.3

- .changes/unreleased/Fixed-20240509-114653.yaml
- core/container.go
- core/integration/module_test.go
- core/query.go
- engine/buildkit/executor.go
- engine/server/buildkitcontroller.go
- engine/server/server.go
Fixes https://github.com/dagger/dagger/issues/7334
A few releases ago, client IDs were changed to be digests of the dagql.CurrentID in order to remove the number fields in our ftp_proxy hack and to consolidate client ID w/ module caller digest.
This is not entirely working as expected though (detailed below). Fortunately the new custom worker gives us a non-hacky path to set whatever IDs we want in containers without worrying about cache busting or the various problems caused by the ftp_proxy hack, which has been gone entirely as of last release.
This updates the engine to make client IDs random strings again.
The problem we're hitting is that when there are inputs to a Function of type Secret, the Functions seem to always run without any caching no matter what, even in the same dagger …
> engine: make client IDs fully random again

- telemetry/labels.go
- telemetry/labels_test.go
Fixes the issue described in #7323 (that wasn't the right fix though, since this occurs on a client - so we don't control the git version).
The `--porcelain` flag is very nice, but unfortunately, it's not present on older git versions. Since the client git version isn't controlled or managed by us, we should try and play nice with it, and not use any
features that are too new.
In this new approach, we create a new "refs/dagger/..." ref, and then update that (to avoid making changes to any other refs in the repo), and then delete it at the end.
> fix: refactor `GITHUB_REF` handling to use temp ref

- .changes/unreleased/Fixed-20240509-114745.yaml
- core/container.go
- core/integration/module_test.go
- core/modfunc.go
- core/typedef.go
- engine/buildkit/executor.go
When OTEL support was added, module functions were updated to set env vars with the OTEL traceparent values. These values appear to be random every time a function is invoked, even if coming from the same caller and making the call with the same inputs, etc.
That resulted in them busting the Buildkit cache every time.
Fortunately, most of the time the dagql cache within the context of a session prevented this from being noticeable, but in the case where dagql IDs were impure (which prevented dagql caching from being hit), then we'd run the Function every call without any cache hits at all.
The fix here just uses our new and improved mechanism for passing random IDs to containers without invalidating the cache, which was added for proxy env support but has been repeatedly paying dividends …
> core: don't bust cache with random OTEL values in function calls

- sdk/elixir/.changes/unreleased/Added-20240510-171513.yaml
- sdk/elixir/lib/dagger.ex
Introduce a new function to automatic open and close connection after execute a function. Here is an example
```elixir
Dagger.with_connection(fn client ->
client
|> Dagger.Client.container()
|> Dagger.Container.from("alpine")
|> Dagger.Container.with_exec(~w"echo hello")
|> Dagger.Container.stdout()
end)
|> IO.inspect() # Result: {:ok, "hello\n"}
```
> feat(sdk/elixir): introduce Dagger.with_connection/2

- ci/docs.go
Cause a linting failure if we generated a `.changes` file that isn't reflected in the `CHANGELOG.md`.
This happened because I missed a step during #7342. We can automate it, so this doesn't need to happen again :tada:
> ci: add linting check for changie

- docs/current_docs/quickstart/853930-directories.mdx
fix: `project` argument is named `source`.
> docs: fix wrong argument in directories quickstart readme

- ci/cli.go
https://github.com/dagger/dagger/pull/7264 updated to explicitly use go 1.21.7 everywhere.
However - the go releaser version we were using apparently only supports up to 1.21.4 - so we should update it, so that the failing publish job on `main` can pass: https://github.com/dagger/dagger/actions/runs/9064274083/job/24903799826
> ci: update goreleaser to v1.26.0

- core/integration/cacert_test.go
- engine/buildkit/executor.go
- sdk/typescript/runtime/main.go
A [recent commit that changed client IDs](https://github.com/dagger/dagger/pull/7335) to be random again accidentally made it so that commands run to update CA certificates (when a custom engine has those installed) hit errors about client tokens not matching when the exec being run was nested, which includes module function calls.
This was due to the fact that those commands run in the same container with the same client ID but the secret token was generated by the client each time it ran, which resulted in mismatches.
The fix here just updates those extra CA commands to never be nested execs since there's no purpose in that anyways and it's nothing but overhead.
* We just unset the relevant env var for those commands, which is a bit ugly but not any more than the existing ugliness. …
> core: fix custom CA certs in modules + add integ test coverage

- docs/current_docs/quickstart/883939-containers.mdx
`dagger call container` command output seems to be wrong, running the example following the docs gives a different output.
> docs: fix: dagger call container command output

- ci/consts/versions.go
- core/integration/images.go
From https://go.dev/doc/devel/release:
> go1.22.3 (released 2024-05-07) includes security fixes to the go command and the net package, as well as bug fixes to the compiler, the runtime, and the net/http package. See the [Go 1.22.3 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.3+label%3ACherryPickApproved) on our issue tracker for details.
Specifically, this allows dagger modules written with an explicit `go 1.22.3` directive to compile.
> chore: bump go images to 1.22.3

- sdk/typescript/runtime/dagger.json
- sdk/typescript/runtime/main.go
Found during working on #6967. The `name` in
`sdk/typescript/runtime/dagger.json` use PascalCase as a name but other SDK use kebab-case. This commit try renaming it to kebab-case to make it consistent.
> chore(sdk/typescript): rename typescript sdk runtime name

- core/container.go
- engine/buildkit/client.go
- engine/buildkit/telemetry.go
- telemetry/inflight/proxy.go
Follow-up to #6835 (found during hackery on #7272)
We used to use the magic `[internal]` prefix in buildkit vertex names to mark these as internal to the UI. However, we've since updated our TUI and cloud logic to instead pull this information from an OTEL span attribute (which makes much more sense). However, we didn't have a way of connecting buildkit vertices to this attribute.
This wasn't immediately obvious - because of how [our TUI logic doesn't show spans that last longer than 100 milliseconds](https://github.com/dagger/dagger/blob/e25ff72f7111d09800ffa208492f00e0d1b6c309/dagql/idtui/frontend.go#L433-L436), and because lots of these were very quick `[internal] merge`s, then we didn't see these most of the time. However, some of the longer ones, like our internal blob copying, could …
> feat: mark `[internal]` buildkit prefixes as internal

- sdk/typescript/.changes/unreleased/Fixed-20240514-210710.yaml
- sdk/typescript/entrypoint/load.ts
- sdk/typescript/introspector/test/invoke.spec.ts
- sdk/typescript/introspector/test/scan.spec.ts
- sdk/typescript/introspector/test/testdata/generate_expected_scan.ts
- sdk/typescript/introspector/test/testdata/list/expected.json
- sdk/typescript/introspector/test/testdata/list/index.ts
A regression was introduced by #6833 and listof nested object were not supported anymore.
This changes fixes the behaviour by using the correct referenced object when the type of an object property is a list
of object.
> fix(tssdk): correcly handle list of nested object

- .github/workflows/publish-sdk-go.yml
Follow-up to #7349
This should be "go", not "elixir". Looks like a bad case of copy-pasta.
> ci: fix typo in publish go sdk

- dagql/idtui/db.go
- dagql/idtui/frontend.go
- dagql/idtui/spans.go
- engine/buildkit/telemetry.go
- telemetry/attrs.go
- telemetry/span.go
Before this, we would display all the containerd/buildkit spans that relate to pulling an image. These are *super* unhelpful by default, so we want to hide them in the TUI (unless the parent command errors).
We already have this concept today with `telemetry.Encapsulate`. However, this is set on the parent (in our case, `Container.from`), which isn't quite what we want. Firstly, this would silence all output from this function (even if later we would want to add some more useful output of our own). Secondly, in some builds, these requests might not necessarily even occur as part of `Container.From` - we might end up lazily pulling the image later.
So, we add a new `telemetry.Encapsulated` property - this is exactly the same as the above, but is instead set on a child span. We can set this …
> fix: hide remotes.docker.resolver spans

- ci/docs-nginx.conf
- ci/docs.go
- ci/go.mod
- ci/go.sum
- dagger.json
Examples:
- Build the docs site: `dagger call --source=. site export --path=./docs-site`
- Build the docs server: `dagger call --source=. server`
- Run docs locally: `dagger call --source=. server as-service up`
- Run docs for a PR: `dagger call --source=https://github.com/dagger/dagger#pull/7382/head server as-service up`
> Build Dagger docs with Dagger

- .changes/unreleased/Changed-20240520-152502.yaml
- cmd/dagger/functions.go
- cmd/dagger/main.go
Fixes https://github.com/dagger/dagger/issues/7400
Note that `dagger call` still shows them, they're hidden only on function commands.
```
❯ dagger call sdk python --help
```
```
Develop the Dagger Python SDK
USAGE
dagger call sdk python <function>
FUNCTIONS
bump          Bump the Python SDK's Engine dependency
generate      Regenerate the Python SDK API
lint          Lint the Python SDK
publish       Publish the Python SDK
test          Test the Python SDK
INHERITED OPTIONS
-d, --debug             show debug logs and full verbosity
--json              Present result as JSON
-m, --mod string        Path to dagger.json config file for the module or a directory containing that file.
Either local path (e.g. "/path/to/some/dir") or a github repo (e.g. …
```
> cli: don't show inherited flags in function commands

- sdk/typescript/.changes/unreleased/Fixed-20240522-001342.yaml
- sdk/typescript/entrypoint/entrypoint.ts
- sdk/typescript/introspector/scanner/scan.ts
- sdk/typescript/introspector/test/scan.spec.ts
- sdk/typescript/introspector/test/testdata/invalid/index.ts
Fixes #6624 
Improve error message clarity.
Remove non-required `await`
> fix: throw error on invalid module registration

- helm/dagger/templates/_helpers.tpl
- helm/dagger/values.yaml
This is required in cases where labels are required to provide access, ETC. I.E.:
I need this change because I'd like to execute Terraform code in Dagger Runners under an Azure MSI context using aadPodIdentity in an AKS cluster. To provide the necessary access, the dagger-engine DaemonSet requires an `aadpodidentity` label for aadPodIdentity to attach an Azure MSI context to it.
> Add Values.engine.labels value to Helm Chart.

- .github/workflows/publish.yml
- sdk/typescript/package.json
- sdk/typescript/runtime/main.go
~~Fixes https://github.com/dagger/dagger/pull/7096#issuecomment-2125073758 issue by enabling corepack and setting yarn version to v4 in our provision tests~~
Fixes https://github.com/dagger/dagger/pull/7096#issuecomment-2125073758 by removing the `packageManager` field so corepack and yarn v4 isn't required to use the TS SDK, this let the changes introduced in #7096 to be backward compatible.
We're still gonna use corepack and yarn v4 in the TS module runtime though.
> tssdk: disable corepack requirement in TS SDK

- cmd/dagger/engine.go
- cmd/dagger/main.go
- core/integration/engine_test.go
- dagql/idtui/frontend.go
- engine/client/buildkit.go
- engine/client/client.go
- telemetry/init.go
- telemetry/logging.go
- telemetry/url.go
- telemetry/util.go
Continued progress exploration! I just kinda kept pulling on #7375, and kept finding more things to tidy up :tada:
Fixes:
- #7375
- #6643
This changes a few things about the initial connection:
- Changes timeouts, to provide a sane upper limit on the amount of time allowed to provision an engine, e.g. pulling+starting a docker container (10 minutes) 
- Splits up the `connect` step into separate parts - this allows for improved debugability if this step is hanging - we can see exactly which part is being slow.
- Removes noisy "OK!" message from session connection - this isn't really needed anymore, success is indicated by the completion of the span.
- Makes sure that `Connected to engine` messages correctly appear with our pretty progress (they weren't being displayed)
- Restores support …
> Improved connection progress

- core/schema/modulesource.go
`normalizeCallerLoadedSource` function can segfault if `withContextDirectory` returns an error, as we do not check for the returned error on the `withContextDirectory` call.
The following dagql calls can be executed: on the `dagger init`, for example, the `withName` gets called on my tests, and trigger the segfault.
It is currently (almost) never triggered, as there are two potential edge cases in which we return an error on `withContextDirectory`:
1. when the modulesourcekind is not local
2. when we fail to load the dir
> fix(core): check error on `normalizeCallerLoadedSource`

- .changes/unreleased/Changed-20240520-151710.yaml
- cmd/dagger/flags.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
- core/integration/module_call_test.go
Fixes https://github.com/dagger/dagger/issues/6608
Most common reason for not being able to call a function is unsupported flags. A function will be skipped if there's any required arguments with unsupported flags, but if the unsupported flags are only for optional arguments, they just won't be available to the CLI.
> cli: don’t show functions that can’t be called

- .changes/unreleased/Fixed-20240520-144206.yaml
- cmd/dagger/functions.go
- cmd/dagger/module.go
- core/integration/module_call_test.go
- core/integration/module_test.go
Fixes https://github.com/dagger/dagger/issues/7398
The `--help` flag is now global (interspersed). So the help will no longer be shown next to the command where it’s defined if there’s more to the right. It’s position in the chain no longer matters, it will be the same as adding it to the end. This was needed to look ahead and skip some validations while that flag wasn’t parsed yet, and while it was possible to preserve the previous behavior, making it global seems more consistent with CLI conventions, besides being simpler.
**Before**
```console
❯ dagger call cli --help file
Develop the Dagger CLI
USAGE
dagger call cli <function>
```
**After**
```console
❯ dagger call cli --help file
Build the CLI binary
USAGE
dagger call cli file [arguments] <function>
```
Did a bit of refactoring to …
> fix(cli): don't validate flags when requesting `--help`

- core/integration/module_typescript_test.go
- core/integration/testdata/modules/go/ifaces/test/.gitattributes
- sdk/typescript/.changes/unreleased/Added-20240527-231234.yaml
- sdk/typescript/entrypoint/invoke.ts
- sdk/typescript/entrypoint/load.ts
- sdk/typescript/introspector/registry/registry.ts
Fixes #7446 by loading the object as class if it exist inside the module.
If an object exists inside the module, it loads the class by calling his constructor so now public methods can be called inside the module.
> feat(ts): keep function prototype during loading

- engine/buildkit/containerimage.go
Reported by @nipuna-perera on [discord](https://discord.com/channels/707636530424053791/1120503349599543376/1245006420706070631):
> Ok now I'm definitely on 0.11.5, but I am still seeing the HTTP spans when doing a Publish. Did that get missed? 
>
> ![image](https://github.com/dagger/dagger/assets/7352848/f9e2f57b-bd77-4c92-b649-89c9aac94f89)
This was introduced in #7386, and made much more apparent in the plain progress from #7272.
We just need to make sure that we apply our magical telemetry context to the export steps as well, which I just missed.
Before:
```
❯ dagger call -v container-echo --string-arg=xyz publish --address=ttl.sh/jedevc-container-echo-1
✔ connect 1.0s
✔ starting engine 0.6s
✔ starting session 0.3s
✔ initialize 0.8s
✔ Foo.containerEcho(stringArg: "xyz"): Container! …
```
> fix: ensure we filter buildkit http spans from publishing

- ci/sdk.go
In v0.11.5, I've started seeing this hanging for some reason. However, CI continues to pass.
Not *entirely* sure what the cause is, but in the meantime, we should unblock being able to run these parts of our CI locally.
> ci: use dagger-engine service binding to install

- .golangci.yml
- ci/build/builder.go
dumb-init was accidentally always being built for the host platform, which meant if it was built on an x86 host the published arm64 image would incorrectly be x86.
This fixes that and also adds general purpose verification of all the binaries we build checking that they are of the expected target platform, to reduce the chances of this happening again.
---
Tested the verification logic by locally going back to building the dumb-init binary for the host platform and getting an error when I built for x86 on my arm host.
> ci: build dumb-init for target platform and add verification

- core/integration/services_test.go
- engine/buildkit/executor_spec.go
Draft pending:
- Added now, FTR the host dependency was whether or not the host's /etc/resolv.conf had a `search` setting or not. That ends up propagated to the engine container and to execs, but this bug was triggered when there was no `search` setting in the base resolv.conf, so it ended up being dependent on the resolv.conf of the host.
> executor: always include search setting in resolv.conf

- core/integration/proxy_test.go
- engine/buildkit/executor_spec.go
- engine/consts.go
- engine/sources/gitdns/cli.go
Otherwise, operations done by shelling out to git won't honor the proxy values.
The integ test added here runs a pipeline that triggers a git pull and then asserts that the squid proxy logs show a connection to github.com.
Fixes https://github.com/dagger/dagger/issues/7503
> engine: pass system proxy envs to git subcommands

- cmd/dagger/flags.go
- engine/client/filesync.go
Before this, file+dir arg values to dagger call on a Windows client were not converted from `\` format to `/` format, which resulted in calls like `filepath.Split` in the Linux engine container to not work as expected.
Now the CLI calls `filepath.ToSlash` before sending paths, which *helps* handle the paths better in the engine container; specifically enough to avoid at least one bug that resulted in the engine trying to find a path at e.g. `/C:\Foo\Bar`.
To be clear, this is probably not the end of our need for improved Windows path handling, but may be enough to at least squash this one bug.
---
Fixes https://github.com/dagger/dagger/issues/7505
TODO:
* Done, could successfully call both of these now
* `dagger.exe -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container with-file …
> cli: convert Windows paths to / slash format

- cmd/codegen/generator/go/templates/modules.go
Fixes #7524 (nice catch @yann-soubeyrand :tada:)
To do this, we lexigraphically sort our case names before creating the switch case. This ensures the same result between runs, which ideally should improve cache consistency as well.
This could have resulted in less-than-optimal caching performance.
> fix(go): ensure idempotency on switch-case

- ci/build/builder.go
v0.26.0 shipped today and breaks things for probably not interesting reasons since this is already working around convoluted dependency issues (we're blocked on runc, runc is blocked on Go)
> pin golang.org/x/net workaround to v0.25.0

- .github/workflows/_dagger_call.yml
- .github/workflows/_new_release_notification.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/publish.yml
- RELEASING.md
- ci/go.mod
- dagger.json
- docs/current_docs/partials/_install-cli.mdx
- go.mod
TODO:
- I had to do some careful grepping around (can't prefix with `v` to find the docs file, yamls use v0-11-5, etc.)
> improve releasing during v0.11.6

- .changes/unreleased/Breaking-20240605-112436.yaml
- cmd/introspect/main.go
- core/directory.go
- core/integration/module_config_test.go
- core/integration/module_test.go
- core/integration/testdata/modules/python/extended/src/main/__init__.py
- core/moddeps.go
- core/module.go
- core/schema/coremod.go
- core/schema/sdk.go
- core/schema/util.go
- engine/buildkit/blob.go
- engine/buildkit/filesync.go
- sdk/elixir/runtime/main.go
- sdk/python/runtime/main.go
- sdk/typescript/runtime/main.go
Before this, we were passing full introspection schema JSONs as strings as args to non-Go SDKs, which resulted in them being included in the full IDs for non-Go modules.
Those strings got huge and could appear multiple times in a single ID, which inflated their size, and also ended up in progress output (I think the source of `ETOOBIG`?) + telemetry.
This has been a known issue for a while but not harmful enough to be prioritized for a fix. However, my [other PR](https://github.com/dagger/dagger/pull/7315) that refactors a bunch of stuff around sessions ended up hitting this problem hard since it required including Module+FunctionCall IDs as HTTP headers, but then hitting limits on the max size of HTTP headers (go defaults to 1MB, which is pretty reasonable+generous).
* Some headers in …
> core: reduce module ID size by not including full schemas

- cmd/engine/main_oci_worker.go
stopgap fix for #7392. Increasing the GC keep size to more reasonable defaults
so users don't get cache evicted so aggresively.
> engine: bump default oci worker keep to 75%

- sdk/elixir/README.md
The runtime are not compatible with older dagger. It's need to specify a version in the `--sdk` option to make works.
> doc(sdk/elixir): warning user about runtime breaking changes

- sdk/typescript/runtime/main.go
tsx pushed a release an hour ago that caused all Typescript modules to break out of band with errors like:
```
Transforming JavaScript decorators to the configured target environment
("node21.3.0") is not supported yet
```
It broke out-of-band because our install of tsx was not pinned to any version. I pinned it now to the previous patch release and things work again.
Hopefully there's some better way of pinning this version since it's currently just a direct `npm install` call and not in a lock file, but this at least fixes the problem in the immediate term.
> ts: pin tsx version installed for modules

- engine/client/filesync.go
The `export` function does `chown` cause Windows crash due to it's unsupported. This commit fixed by skip `chown` operation when running in Windows.
Fixes #7558
> fix: fix File cannot export on Windows

- ci/sdk_typescript.go
- core/integration/module_call_test.go
- core/integration/module_functions_test.go
- core/integration/module_python_test.go
- core/integration/module_test.go
- core/integration/module_typescript_test.go
- engine/client/client.go
- sdk/typescript/api/test/api.spec.ts
- sdk/typescript/runtime/main.go
- sdk/typescript/test/connect.spec.ts
While debugging something nodejs-related in https://github.com/dagger/dagger/pull/7315 I noticed a bunch of problems with the TS tests and some related areas:
1. Fix missing awaits in TS tests that caused accidental parallelism + tidy up env restoration: https://github.com/dagger/dagger/commit/15c43aef428a74dbe9c18d3c08ae2feba1e4a2d6 https://github.com/dagger/dagger/commit/32638a4809cfca968ebacddfb4e2428d9d769fed
2. Fix bun image to be multiplatform and upgrade bun version to avoid SIGSEGV/SIGABRT crashes: https://github.com/dagger/dagger/commit/22653f1c951abec324440582b6c8eba31e12e3a7 https://github.com/dagger/dagger/commit/f884fe9dcd6010a1fbedb3c684760d4ce51d2db5
3. Fill in a bunch of module integ tests that were missing `t.Parallel()` calls …
> Various TS + general test fixes + improvements

- .github/workflows/sdk-go.yml
- .github/workflows/sdk-python.yml
- .github/workflows/sdk-typescript.yml
- ci/sdk_go.go
- ci/sdk_python.go
- ci/sdk_typescript.go
- ci/std/go/main.go
It's already installed.
And also, we should move all our dependency installation *out* of here, and into previous steps, this is generally a bad practice in the first place.
> ci: avoid installing git on wolfi

- RELEASING.md
- cmd/engine/telemetry.go
- core/integration/engine_test.go
- engine/client/client.go
- engine/consts.go
- engine/opts.go
- engine/server/buildkitcontroller.go
- engine/telemetry/labels.go
- engine/version.go
See the rationale in https://github.com/dagger/dagger/pull/7013, https://github.com/dagger/dagger/pull/7001#discussion_r1549487821. TL;DR, during the release of v0.11.0, we broke compatibility with older clients, but didn't really have the tooling to make sure that this *errored* cleanly out.
This PR ensures that this doesn't happen again - both the client and the server are able to specify a minimum version, defined in `engine/version.go`. If a client/server doesn't satisfy these constraints, an appropriate error is printed out. These checks are introduced into the client/server code *directly*, instead of into each SDK, which don't trigger in dagger module code (see commit messages for more detailed description of the exact logic used).
For example, during the release of v0.11.0, if …
> Introduce better versioning compatibility guarantees

- install.ps1
- install.sh
This allows installing an arbitrary commit from main, to make it easier to install versions from main for testing.
TODO:
> chore: add DAGGER_COMMIT option to install.sh

- ci/build/builder.go
- ci/build/sdk.go
- ci/consts/versions.go
- ci/std/go/main.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/engine_test.go
- core/integration/file_test.go
- core/integration/images.go
- core/integration/module_call_test.go
- core/integration/module_terminal_test.go
- core/integration/module_test.go
- core/integration/proxy_test.go
- core/integration/services_test.go
- engine/distconsts/consts.go
Revival of https://github.com/dagger/dagger/pull/7323.
This is motivated slightly by some of the issues in https://github.com/dagger/dagger/pull/7554 - running up-to-date software is pretty important.
> chore: update alpine base to 3.20

- docs/current_docs/integrations/snippets/tekton-dagger-task.yaml
- helm/dagger/templates/engine-daemonset.yaml
- helm/dagger/values.yaml
While we are keeping this default so that we don't break existing users, setting this value is something that we want to move away from.
The problem is that this setting limits how many operations can run in parallel. It is still possible for a single operation to max out all available cores. It is also known for a value of `2` to cause deadlocks, i.e. https://github.com/dagger/dagger/issues/6894
For now, we just allow this to be disabled with either `--set engine.args=''` or by explicitly setting this value to an empty list.
This started as https://github.com/dagger/dagger/pull/7395 which turned out to be too big of a change. We since scaled back the initial ambition & are taking a smaller step towards eventually phasing this out.
FWIW, all the Dagger Engines that we run inside the …
> helm: Allow disabling `--oci-max-parallelism num-cpu`

- engine/server/server.go
[This has been reported](https://github.com/dagger/dagger/issues/7592) to happen intermittently by a few users. [The error originates from gqlgen](https://github.com/99designs/gqlgen/blob/d9ba340552d1adb25e32584b2a4d3dfc9e254d24/graphql/handler/server.go#L119) and suggests that something in the http request is unhandled; it basically tries to find a matching pattern for gql requests based on http method and some headers.
It's unclear how this could happen only occasionally and I've never seen this myself yet, so I think our best bet is to log the parts of the request checked by gqlgen and wait for it to get hit again.
> engine: add logging to help debug "transport not supported"

- cmd/dagger/licenses.go
- cmd/dagger/main.go
- cmd/dagger/module.go
- cmd/dagger/run.go
- core/c2h.go
- core/healthcheck.go
- core/integration/module_up_test.go
- core/schema/query.go
- core/schema/service.go
- core/service.go
- core/telemetry.go
- dagql/idtui/frontend_plain.go
- dagql/idtui/frontend_pretty.go
- engine/buildkit/executor_spec.go
- engine/client/client.go
- engine/client/drivers/docker.go
- engine/session/h2c.go
- engine/slog/slog.go
- engine/slog/telemetry.go
- sdk/go/telemetry/logging.go
* Standardize on `slog` everywhere that we print output from the engine, instead of "faking" stdout/stderr in places.
* Goal: `SpanLogger` no longer leaves ambiguity as to whether caller needs to `Close()`. It _never_ does.
* We will no longer drain to ensure we get every last log, but this was never really an issue, doesn't seem worthwhile atm.
* Rename `telemetry.Logs` to `telemetry.SpanStdio` so its intentions are clearer.
* Goal: again, remove ambiguity as to whether caller needs to `Close()`. It _always_ does.
* Propagate client-side `NO_COLOR=true` and `--debug` through to the engine so `SpanLogger` can respect it.
* Goal: now that everything is `slog` we should respect the user's preferences.
* I needed this to get the `dagger up --random` test to pass without choking on ANSI …
> OTel log draining follow-ups

- engine/buildkit/executor.go
When an exec fails due to context canceled, we were dropping the cancelation error and just returning the exec error. I believe this got fat-fingered while updating the code from upstream to use fmt.Errorf instead of github.com/pkg/errors.
It's not clear if this is really meaningful, but noticed it changed while attempting to debug occurances of "exit code 137" in our CI, which plausibly could be related to all of this. It's possible there's calling code that tries to handle cancelation with errors.Is, which this would have broken. This is purely hypothetical at this point though.
---
This is the related upstream version of this code, if helpful https://github.com/moby/buildkit/blob/715276d7423f006dab1c96bd6910d4ca55faa230/executor/runcexecutor/executor.go#L374
> engine: fix context error wrapping in executor

- .changes/unreleased/Fixed-20240610-162518.yaml
- core/integration/container_test.go
- engine/buildkit/client.go
Fixes https://github.com/dagger/dagger/issues/7522.
When doing a nested frontend build - i.e. when dockerfile.v0 calls gateway.v0 (triggered by a syntax directive), we need to ensure that the second frontend gets the same secret translation as each prior layer.
To do this, we heavily refactor the filtering gateway and essentially have it pass itself into the frontend Solve - this propagates the filtering all the way down, so secrets can be correctly accessed.
Once we have the session cleanup and refactoring in https://github.com/dagger/dagger/pull/7315, hopefully this logic can go - but this is a quick fix we can get in for the next release.
> fix: ensure nested frontend builds get secret translation

- sdk/typescript/.changes/unreleased/Fixed-20240531-102026.yaml
- sdk/typescript/runtime/main.go
#7096 introduced a regression by using `yarn install --production`. If the field `packagaManager` is set, it might lead to failure because yarn post v1.22.11 doesn't support the `--production` flag anymore, it has been removed in favor of `yarn workspaces focus --production`.
However, depending on the yarn major version (v2, v3, v4), the options are different but also the results and the way they handle subdependencies.
~~It seems `npm` is the only package manager that actually force install all the sub dependencies, which ensure the TS SDK runtime properly works.~~
By initialiazing corepack inside the SDK installation, we ignore the field `packageManager` when installing dependencies with yarn, which will be compatible with any package manager version.
It's a nice way to keep yarn …
> fix(ts-sdk) set corepack inside of SDK install instead of global

- ci/engine.go
- ci/main.go
- ci/sdk.go
We were previously always putting a random id in the cache volume used for engines created in various CI functions, which meant none of them ever had any local cache. The main reason was that two engines can't use the same local cache at the same time.
We can't lift that limitation, but by using the engine version and private cache mounts we can get *best effort* re-use of these cache volumes, which is a simple enough performance improvement for some cases that we may as well take it.
> ci: enable best-effort cache reuse for nested engines

- sdk/elixir/.changes/unreleased/Fixed-20240510-225656.yaml
- sdk/elixir/mix.exs
`:inets` requires to start before using the SDK because of `:httpc` module.
> fix(sdk/elixir): add :inets to :extra_applications

- .changes/unreleased/Changed-20240611-113054.yaml
- engine/client/buildkit.go
we're changing the default minConnectTimeout and backoff settings since
in some cases, the `connect` happens before the engine is ready to
accept connections, causing the client to wait for the default
minConnectTimeout (20s) before retrying. This causes very long
connection times when the engine is not ready to accept connections.
> client: set a minimum connect timeout for buildkit

- .github/workflows/sdk-elixir.yml
- .github/workflows/sdk-go.yml
- .github/workflows/sdk-java.yml
- .github/workflows/sdk-python.yml
- .github/workflows/sdk-rust.yml
- .github/workflows/sdk-typescript.yml
https://github.com/dagger/dagger/pull/7315 made some simplifications that got rid of corner cases involving overlapping nested engine OTEL spans which were causing a lot of SDK test+lint workflows to hang on OTEL draining. 
This updates those workflows to use the dev engine+cli exclusively so that they can pick up those fixes before the next release.
There's little harm in doing this now and the long term, though I do question whether we can + should just make our whole CI more consistent in whether we always exclusively use the dev engine (only *building* it from stable) or continue to have a mix of workflows.
* However, in the short term this appears to fix the problem (sdk test + lint workflows passed 5 times in a row), so seems like the right move now
* There's also quite a few tricky …
> ci: run sdk lint+test using dev cli+engine

- ci/sdk_go.go
Fixes https://github.com/dagger/dagger/issues/7630.
Introduced in [`8421636` (#7554)](https://github.com/dagger/dagger/pull/7554/commits/8421636acaaa7cd312eb3546f6b3b1870090d83c).
This caused the https://github.com/dagger/dagger-go-sdk read-only copy to include the full dagger/dagger repo, instead of the filtered one.
> ci: fix git publish (for go and php)

- install.ps1
Changed the default install path from $env:HOMEPATH to $env:USERPROFILE as this includes the drive. Currently when calling the install script on the D: drive the transfer from the temp directory to the install path fails. This is not reported as an error and the install script appears to have worked correctly. This is because $env:HOMEPATH does not include the drive in the path. Changing this to $env:USERPROFILE has the same path but the path includes the drive, this fixes the issue.
> Fix powershell install script to work when on a different drive

- .github/workflows/_dagger_call.yml
https://github.com/dagger/dagger/pull/7349/files#diff-57d0a87a3ee76e3f54076848756b333683e6bdb5ae34463f3a5240b04942ce0b was a bad refactor.
See https://github.com/dagger/dagger/actions/runs/9481418789/job/26124166243#step:7:36.
Since the bad refactor, we've not been actually running the testdev tests in the dev container - we've been using the top-level one.
https://github.com/dagger/dagger/pull/7483 will replace the need for this.
> ci: make dind use with-dev

- core/integration/client_test.go
by waiting for logs to appear, instead of hoping they do
This should do a decent job at de-flaking, since the failure mode is just missing the log events before closing the client. If we wait to see them before making the more rigorous assertions (i.e. not seeing dupes, not seeing other clients) we should be OK.
> de-flake TestClientMultiSameTrace

- engine/version.go
[PR 7315](https://github.com/dagger/dagger/pull/7315) that reworked how sessions connect breaks client-server compat, mainly because the engine API is now just HTTP rather than gRPC-tunneled HTTP, so we need to update the min compatible versions.
> engine: update minimum engine+client version

- install.ps1
#7560 
- Added interactive install (validates paths + some inputs)
- Use [switch] for 'Interactive' behaviour `.\install.ps1 -Interactive`
- Ensures SemVer provided is valid & not higher than latest version
- Fixes amd64/arm64/armv7 versions to be correctly installed by checking arch of the system
- Optional: adds dagger.exe to the PATH (off by default)
- notice user where it's installed with a friendly full path i.e `C:\users\patrick\dagger`
- Uses `Path::GetTempFile()` to store the zip in the correct `temp` dir
- notice user to add to PATH if they instructed `(n)` on `-Interactive` install
- notice user if installing from non-windows machine (will install win binary)
- uses `exit 1` for non-successful termination
- Support GitCommit install (and basic sanity check on SHA length)
- Also …
> .\install.ps1 changes

- sdk/elixir/.changes/unreleased/Fixed-20240614-092810.yaml
- sdk/elixir/runtime/main.go
I found out that Elixir runtime cannot run on my Apple M1 machine and realize that the image in Elixir runtime has only amd64 architecture. :(
So I do fix by bump image to a new version that have both amd64 and aarch64 architectures.
> fix(sdk/elixir): fix runtime image cannot run on arm64

- .changes/unreleased/Added-20240613-221441.yaml
- cmd/dagger/module.go
- core/integration/module_test.go
This changes the  `dagger init` command to  not generate `LICENSE` if no code has been generated (when `--sdk`) is not specified.
It also generates a license if then `dagger develop` is executed with `--sdk` flag.
Fixes #6666
Close DEV-3989
> feat: improve license generation

- ci/build/builder.go
the v0.11.7 release bumped the base images that the engine uses which
caused a newer version of iptables to be used. This newer version of
iptables which uses nftables is still not widely supported and it's
currently causing issues for some users.
cc @iximiuz 
ref: https://discord.com/channels/707636530424053791/1251537699903639623
> ci: use legacy iptables instead of nf_tables

- .changes/unreleased/Fixed-20240617-161718.yaml
- dagql/idtui/db.go
- dagql/idtui/frontend.go
- dagql/idtui/frontend_plain.go
- dagql/idtui/frontend_pretty.go
Reported by @vito in an internal discord: https://discord.com/channels/707636530424053791/1250122361131499664/1250193357683163208
> huh, running that command with --debug or -vvv seems to cause the CLI to eat up all of my memory, seems like a bug with the call simplification code
>
> last time this came up it was because of a call simplifying to itself or something and ending up in a loop, all the memory usage is from trying to render the indentation
Turns out, the changes to call simplification to get `blob`s to never show was a little faulty.
For, example, on high verbosity settings, the following could happen:
- `moduleSource.resolveDependency` is an identity function (for git sources), taking an argument and returning it unmodified.
- Arguments in a call to …
> Fix forced simplification infinite progress loop on high verbosity settings

- .github/workflows/_sdk_check.yml
- .github/workflows/sdk.yml
- ci/sdk_elixir.go
- ci/sdk_rust.go
We originally started to run these in [`9bb57fc` (#7554)](https://github.com/dagger/dagger/pull/7554/commits/9bb57fcf8f8d0141acb91b286cf35ffaf169ae05) and [`8421636` (#7554)](https://github.com/dagger/dagger/pull/7554/commits/8421636acaaa7cd312eb3546f6b3b1870090d83c), however, I only fixed the `--dry-run` publishing for python, typescript and go.
In this PR, I've fixed it for elixir and rust as well, and enabled it for those (as well as PHP). This should hopefully help to avoid future release misfortunes.
> ci: run dry-run publishing for each sdk we publish

- .github/workflows/engine-and-cli-publish.yml
- .github/workflows/engine-and-cli.yml
Minor regression from #7483 - we don't such a powerful machine for this job.
> ci: use standard worker for scan-engine job

- cmd/dagger/flags.go
- cmd/dagger/module_test.go
Fixes https://github.com/dagger/dagger/issues/7684.
Previously, we didn't use to have a way to get the "default" branch - however, now we do, we can just do `.Head()` on a git repository. (note: this is just as lazy as all the other git calls).
So we don't need to assume "main" at any point.
> fix: don't make cli default to "main" branch

- core/integration/module_typescript_test.go
- sdk/typescript/.changes/unreleased/Fixed-20240618-195123.yaml
- sdk/typescript/introspector/scanner/utils.ts
- sdk/typescript/introspector/test/scan.spec.ts
- sdk/typescript/introspector/test/testdata/list/expected.json
- sdk/typescript/introspector/test/testdata/list/index.ts
- sdk/typescript/introspector/test/testdata/primitives/index.ts
Fixes https://github.com/dagger/dagger/issues/7687 by returning an explicit error in case the user uses primitive types in Typescript such as `String`, `Boolean` or `Number`.
The error returned will be of shape (example with `Boolean`):
```
Use of primitive Boolean type detected, did you mean boolean?
```
> feat(ts-sdk): throw explicit error on invalid primitive types

- core/integration/proxy_test.go
I couldn't repro this locally but there were occasional CI flakes in the proxy test that pulls a git repo and verifies the proxy logs show a connection to github.com (needed to verify that git ops correctly use proxy settings).
My best guess is that the squid logs were just not always flushed by the time they were read for the test assertion, so this updates the tests to explicitly start/stop the squid service and do some retries on reading the logs.
Will have to see if this actually fixes the problem. If not there's more complicated options like starting a separate custom git service, intercepting traffic and asserting there. Would prefer to avoid complicating these already complicated tests further if possible though.
> tests: attempt to deflake proxy tests

- .github/actions/call/action.yml
- .github/workflows/_sdk_check.yml
- .github/workflows/engine-and-cli.yml
- ci/mage/engine.go
- ci/mage/util/const.go
- ci/mage/util/dagger.go
- hack/dev
- hack/with-dev
As was discussed [here](https://github.com/dagger/dagger/pull/7483#discussion_r1636854755), since [#7628](https://github.com/dagger/dagger/pull/7628) got merged we are using dind runners for SDK jobs. Default dind runners have 32c and 16Gi, which for SDK jobs is excessive. Since we now have support for dynamically sized dind runners, we migrate SDK jobs to 4c (like we used to run it) and we leave testdev with 32c jobs.
> Use dynamically sized dind runners for SDK and testdev

- .github/actions/call/action.yml
We want each dev engine to be used only by the job it is being created. With arc, the name of the runner is the name of the pod and each pod runs a single dedicated job.
> Use runner.name as unique id for dev engine

- cmd/dagger/run.go
- docs/current_docs/reference/cli.mdx
Just found during testing dotnet-sdk. The single quote is missing after `/query` path.
> fix: fix missing quote in dagger run example

- engine/buildkit/client.go
- engine/buildkit/ref.go
Buildkit does all sorts of special context.Cause error handling but still sets all the errors to just be context.Canceled, only difference being wrapping them with hidden stack traces from the github.com/pkg/errors package.
To help debug where context canceled errors are coming from, it's useful to see these stack traces so we can get more than "context canceled". To do this we need to log the errors with the formatting directive %+v.
---
Related to https://github.com/dagger/dagger/issues/7699, have been banging my head trying to either repro this locally or figure out by reading buildkit solver code but neither is leading anywhere, so hoping that if we hit it again this will at least give us more chances of debugging it provided it occurs in a place in CI where the engine logs are …
> engine: log buildkit solve error stack traces

- cmd/dagger/main.go
- dagql/idtui/db.go
- dagql/idtui/frontend.go
- dagql/idtui/frontend_plain.go
- dagql/idtui/frontend_pretty.go
- dagql/idtui/spans.go
- dagql/idtui/types.go
- dagql/idtui/vterm.go
- go.mod
[![asciicast](https://asciinema.org/a/vdUEqRXX0K6Dw9zqLjkwlCxNc.svg)](https://asciinema.org/a/vdUEqRXX0K6Dw9zqLjkwlCxNc)
* ~~Now shows effects at their origin (`withExec`) rather than their unlazying point (`sync`).~~
* Moved to separate PR: #7686 
* Now supports navigation, instead of being stuck with the bottom of the visible region
* `hjkl` or arrow keys to move around
* `enter` to "zoom in" to the selected span
* `end` or `space` to follow the bottom of the screen
* `home` to go to beginning
* Instead of having spans disappear after a second, we just collapse them when they finish.
* Now supports mouse scroll wheel again
* I initially skipped this because I found it occasionally annoying for the TUI to steal mouse input. But you can just press Shift to bypass it.
* Now only renders …
> tui: navigation, scrolling, optimizations

- core/integration/module_terminal_test.go
- dagql/idtui/frontend_pretty.go
Fixes a test race/panic introduced by the combination of #7671 and the terminal support.
> synchronize terminal test on prompt, avoid panic

- sdk/python/src/dagger/mod/cli.py
This logs the exception stack trace for:
- https://github.com/dagger/dagger/issues/7662
> chore(sdk/python): force enable debug logging when main module can't be imported

- .github/dependabot.yml
Thanks to #6811, SDK dependencies are now updated in groups (bulk). This removes the need for ignoring patch releases.
> dependabot: Un-ignore patch bumps for SDKs

- docs/current_docs/manuals/developer/language-dependencies.mdx
I ran into the following error trying to regenerate the `requirements.lock` file as described [here](https://docs.dagger.io/manuals/developer/language-dependencies#lock-file) (under the Python tab). I think `--update-all` should be `--upgrade`.
Additionally, it might be worth adding the `--quiet` flag to the docs in the same vein as #7270.
```
❯ uv version
uv 0.2.13
❯ uv pip compile \
--generate-hashes \
--update-all \
-o requirements.lock \
pyproject.toml sdk/pyproject.toml
error: unexpected argument '--update-all' found
tip: to pass '--update-all' as a value, use '-- --update-all'
Usage: uv pip compile --generate-hashes <SRC_FILE>...
For more information, try '--help'.
```
> docs: Fix uv flag in language dependencies manual.

- cmd/engine/telemetry.go
- core/container.go
- core/query.go
- core/schema/host.go
- core/service.go
- core/telemetry.go
- dagql/idtui/db.go
- dagql/idtui/frontend.go
- dagql/idtui/frontend_plain.go
- dagql/idtui/spans.go
- dagql/idtui/types.go
- engine/buildkit/telemetry.go
- sdk/go/telemetry/attrs.go
The place where something becomes un-lazied is not that useful. Better to show effects at their point of origin instead. This is a bit of :sparkles: movie magic :sparkles:  but it's a lot more useful than telling "the truth" (arguably an implementation detail of our telemetry plumbing).
This also effectively works around a Buildkit bug that ends up associating LLB to incorrect spans[^1], which would sometimes put a failed span beneath a succeeding one, making it especially hard to find.
[^1]: possibly from [here](https://github.com/moby/buildkit/blob/master/solver/jobs.go#L696) which the race detector is also unhappy with)
* There's now a SpanProcessor that translates the attribute as described. New scheme:
* `vertex` -> `dagger.io/effect.id`
* `dagger.io/llb.digests` -> …
> tui: associate effects to their origin, not their unlazier

- .github/workflows/engine-and-cli-publish.yml
- ci/engine.go
This publishes two new image variants:
1. `*-wolfi`
2. `*-wolfi-gpu`
We want to take this through the paces - automated & manual tests - and check if it's feasible to consolidate all images into a single one: Wolfi with NVIDIA.
I have also made it clearer in workflow descriptions that this isn't a GPU image variant. While NVIDIA is the dominant GPU vendor today, Intel & AMD are still relevant and in some cases ahead (e.g. Aurora & Frontier supercomputers). A bunch of homelabbers (including myself) have Intel GPUs which we would expect the GPU variant to just work with. I don't think that's the case today.
While this doesn't close https://github.com/dagger/dagger/issues/5668, it's the second step in that direction.
cc @amouat
> Publish Wolfi Engine variants - with & without NVIDIA drivers support

- core/service.go
- core/services.go
- core/util.go
- engine/server/session.go
- engine/telemetry/pubsub.go
A few more fixes/simplifications for OTel + draining found in the process of working on #7532. With these changes I'm finally able to reliably run our instrumented integration tests without any spans "left behind" (even services).
```
✔ connect 0.2s
✔ initialize 13.0s
✔ prepare 0.8s
✔ ModuleSource.resolveFromCaller: ModuleSource! 0.1s
✔ ModuleSource.resolveDirectoryFromCaller(path: ".", viewName: "default"): Directory! 0.0s
✔ dagger(
source: ✔ ModuleSource.resolveDirectoryFromCaller(path: ".", viewName: "default"): Directory! 0.0s
): Dagger! 0.7s
✔ Dagger.test: DaggerTest! 0.3s
✔ DaggerTest.custom(run: "Container"): Void 3m37.6s
```
:smiling_face_with_tear:
> More OTel fixes, mostly service-related

- .github/actions/call/action.yml
- .github/workflows/_sdk_check.yml
- .github/workflows/docs.yml
- .github/workflows/engine-and-cli-publish.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/helm-publish.yml
- .github/workflows/helm-test.yml
- .github/workflows/sdk-elixir-publish.yml
- .github/workflows/sdk-go-publish.yml
- .github/workflows/sdk-php-publish.yml
- .github/workflows/sdk-python-publish.yml
- .github/workflows/sdk-rust-publish.yml
- .github/workflows/sdk-typescript-publish.yml
- ci/go.mod
- ci/go.sum
- dagger.json
- go.mod
Opening this against the `release-v0.11.9` branch for now. We will want to "forward-port" it to `main` also, will handle that along-side forward-porting https://github.com/dagger/dagger/pull/7745
* tbh I'm not 100% sure how necessary it is to merge this to the `release-v0.11.9` branch vs. only doing it to main, but doing it anyways during the first run-through of "publish from non-main branch" out of caution
TODOs (these are only strictly required for the `main` branch, so may end up just splitting out as separate commit there):
> Improve releasing during v0.11.9

- docs/current_docs/manuals/developer/module-structure.mdx
The Runtime Container documentation ([here](https://docs.dagger.io/manuals/developer/module-structure/#runtime-container) - Python tab.) has `[dagger.tool]` instead of `[tool.dagger]`. 
Per the discussion [in discord](https://discord.com/channels/707636530424053791/1250370138226819152/1250439736951308288) (and my testing) it should be the latter.
> docs: Fix 'tool.dagger' toml table name.

- .changes/unreleased/Breaking-20240625-151850.yaml
- cmd/codegen/main.go
- core/schema/query.go
- docs/docs-graphql/schema.graphqls
- engine/client/client.go
- go.mod
- go.sum
- sdk/elixir/lib/dagger.ex
- sdk/elixir/lib/dagger/gen/client.ex
- sdk/go/client.go
- sdk/go/dag/dag.gen.go
- sdk/go/dagger.gen.go
- sdk/go/internal/engineconn/engineconn.go
- sdk/php/generated/Client.php
- sdk/python/src/dagger/_engine/conn.py
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
- sdk/typescript/connect.ts
Part of #7640 and co.
With changes to how we do version compatibility checks, we no longer need this check in the engine. Thankfully - we can just remove it: all of the SDKs were treating this as a warning level, and not causing a fatal error - this means that if the method is removed, it should not cause a build to fail.
The Go SDK also removes the `WithoutVersionCompatibilityCheck` - since now this option is always the case.
> chore: remove `checkVersionCompatibility` field

- .changes/unreleased/Fixed-20240621-183433.yaml
- cmd/dagger/licenses.go
- cmd/dagger/module.go
- core/integration/module_test.go
- docs/current_docs/reference/cli.mdx
A `LICENSE` will only be generated now if `--sdk` is set on `dagger develop`, like in `dagger init`. It's also possible to explictly disable creating a license by providing an empty `--license=`.
Fixes #7703
It will be followed up by #7715 after discussion
> fix: dagger develop generate license only if --sdk is set

- .github/workflows/changelog.yml
This PR adds a check that if a PR is labelled with `needs/changelog`, then the job will fail and add a comment if no changelog was generated as part of the PR.
This should help us automate some of our changelog writing.
See an example run of this in https://github.com/jedevc/dagger/pull/5.
> ci: add actions check for checking changelog

- core/integration/module_typescript_test.go
- core/integration/testdata/modules/typescript/optional/index.ts
- sdk/typescript/.changes/unreleased/Fixed-20240625-191158.yaml
- sdk/typescript/entrypoint/register.ts
- sdk/typescript/introspector/scanner/abtractions/argument.ts
There was an issue that created an error when a non-primitive default value was set to a function like
```typescript
@object()
class Default {
@func()
a(
dir: Directory = dag.directory()
.withNewFile("/foo", "hello world")
): Container {
return dag.container().withMountedDirectory("/dir", dir)
}
}
```
This commit fixes the issue to ignore the default value registration if it's not a primitive type and let the TypeScript runtime resolve it during the execution.
It's a workaround to accomplish the result because resolving the value during the registration requires to run the TS code in a custom runtime that must contains all user's dependency which may be resource consumming + complex to resolve.
> fix(ts-sdk): correctly resolve non-primitive default value

- .changes/unreleased/Fixed-20240625-161626.yaml
- dagql/idtui/frontend_pretty.go
- engine/telemetry/url_test.go
Github actions doesn't support them :cry:
See https://github.com/openmeterio/openmeter/actions/runs/9572449099/job/26391770769?pr=1031#step:3:2161.
In the raw logs, we can see:
> 2024-06-18T21:40:49.1751535Z [1mFull trace at [0m]8;;https://dagger.cloud/\https://dagger.cloud/]8;;\ (rotate dagger.cloud token for full url)
We just can't have hyperlinks here, I missed this before.
---
I've also added a sanity test for the `DAGGER_CLOUD_TOKEN` format, since I was suspicious that this might not be doing the right thing.
> fix: plain progress should never use hyperlinks

- .github/workflows/sdk-python-publish.yml
- .github/workflows/sdk-typescript-publish.yml
- RELEASING.md
Updates to instructions on different process when releasing from non-main branch.
* Also have some small fixes for little things I noticed as extra commits
I also created separate issues for some of the non-trivial problems I hit during the release that are mentioned in these updated docs:
* https://github.com/dagger/dagger/issues/7756
* https://github.com/dagger/dagger/issues/7757
> docs: update RELEASING.md with non-main branch instructions

- .changes/unreleased/Fixed-20240625-110428.yaml
- cmd/engine/main.go
- engine/server/gc.go
When originally updating this in #7563, we only updated the default CLI option - however, this is confusing, and isn't exactly how that works - my suggested refactor wasn't actually correct.
Because we use `GlobalIsSet`, this default is never actually the one that's used. So, we can refactor this, and set a global const to define the default gc policy ourselves, outside of buildkit.
This also opens us up to modifying the gc policy in more detail in the future.
> fix: ensure gc policy percentage is correct

- cmd/dagger/cloud.go
this commits triggers the quickstart flow when the user which is login
in does not belong to any organization. It'll redirect the user to
Dagger Cloud so the organization creation flow can continue there.
> cli: add quickstart for for `dagger login`

- .changes/unreleased/Added-20240626-111327.yaml
- .changes/unreleased/Breaking-20240626-111038.yaml
#7586 introduces breaking changes, and adds features - so this should be changelogged.
> chore: add changelogs for attachable terminal sessions

- core/integration/module_up_test.go
This was introduced #7532 in, by adding a `t.Parallel` to these tests. However, the multiple assignment of `err` has been present from before that.
See the failure: https://dagger.cloud/dagger/traces/c71cecd3d42758687c7437e4b7ec98d1?span=6c83cd34e0be3b36&logs#6c83cd34e0be3b36:L1290
> tests: fix race in assigning to err in TestDaggerUp

- docs/current_docs/manuals/developer/module-structure.mdx
The command is invalid, and I suspect it's missing a space.
```
❯ dagger develop...
Error: unknown command "develop..." for "dagger"
```
> Fix invalid dagger develop command

- .changes/unreleased/Changed-20240628-141105.yaml
- cmd/dagger/call.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
- core/integration/module_call_test.go
- docs/current_docs/reference/cli.mdx
- hack/with-dev
- sdk/go/querybuilder/querybuilder.go
- sdk/go/querybuilder/querybuilder_test.go
Fixes https://github.com/dagger/dagger/issues/6514
Fixes https://github.com/dagger/dagger/issues/6515
Previously, when a `dagger call` chain ended in an object, the result was inconsistent and not very useful:
- Without any functions, it would show `--help`
- `Container`, `Directory` and `File` core types evaluated the pipeline and returned a "XXX evaluated." message
- For custom user types, an error was returned: "return type XXX requires a sub-command"
With this change, in all of those cases, **the CLI finds all functions without required arguments that return a scalar/primitive value, and prints them**. This includes a module's main object, when calling `dagger call` without any more arguments.
> [!NOTE]
> At minimum, a `_type` field is added to the response so there's always something …
> cli: print module object fields with `dagger call`

- .changes/unreleased/Breaking-20240529-181906.yaml
- cmd/dagger/call.go
- core/integration/container_test.go
- core/integration/directory_test.go
- core/integration/file_test.go
- core/integration/services_test.go
- core/schema/container.go
- core/schema/directory.go
- core/schema/file.go
- core/schema/schema_test.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/container.ex
- sdk/elixir/lib/dagger/gen/directory.ex
- sdk/elixir/lib/dagger/gen/file.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Container.php
- sdk/php/generated/Directory.php
- sdk/php/generated/File.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
- sdk/typescript/api/test/api.spec.ts
Fixes https://github.com/dagger/dagger/issues/7131
It's much more useful for `export` to return the absolute path on the host where the asset (Container, Directory, File) was exported to, rather than a boolean. The boolean wasn't useful at all because it's never false. It's either true or an error.
It's possibly a breaking change in Go if any user is assigning the return value (boolean), which is now a different type. However, since that boolean value is useless this is considered very low impact. Affected users (if any), aren't probably aware that it's never `false`.
> 💥 api: return absolute path on export instead of boolean

- sdk/rust/Cargo.lock
- sdk/rust/crates/dagger-codegen/src/rust/templates/object_tmpl.rs
- sdk/rust/crates/dagger-sdk/Cargo.toml
- sdk/rust/crates/dagger-sdk/examples/build-the-application/main.rs
- sdk/rust/crates/dagger-sdk/examples/caching/main.rs
- sdk/rust/crates/dagger-sdk/examples/existing-dockerfile/main.rs
- sdk/rust/crates/dagger-sdk/examples/first-pipeline/main.rs
- sdk/rust/crates/dagger-sdk/examples/logging/main.rs
- sdk/rust/crates/dagger-sdk/examples/multi-stage-build/main.rs
- sdk/rust/crates/dagger-sdk/examples/publish-the-application/main.rs
- sdk/rust/crates/dagger-sdk/examples/test-the-application/main.rs
- sdk/rust/crates/dagger-sdk/src/client.rs
- sdk/rust/crates/dagger-sdk/src/core/cli_session.rs
- sdk/rust/crates/dagger-sdk/src/core/engine.rs
- sdk/rust/crates/dagger-sdk/src/core/gql_client.rs
- sdk/rust/crates/dagger-sdk/src/errors.rs
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/rust/crates/dagger-sdk/tests/mod.rs
Add explicit cleanup for the dagger child process if started from the rust dagger sdk itself. This requires a breaking change to the connect, as we're missing a few features from rust that are currently only available on nightly.
BREAKING: change for the dagger sdk:
```rust
let client = dagger_sdk::connect().await?;
// use client
// breaking change to:
dagger_sdk::connect(|client| async move {
// use client
Ok(())
}).await?;
```
The reason for the breaking change is that we
didn't properly clean up the dagger session.
I initialy attempted an async drop functionality.
However it didn't work because async drop is nightly.
With a single threaded runtime we'd deadlock the thread.
Unlike sqlx which has the same behavior, I cannot count
on the dagger session being available after the last call. …
> feat: add explicit stop to dagger process

- sdk/rust/Cargo.lock
- sdk/rust/crates/dagger-bootstrap/src/cli_generate.rs
- sdk/rust/crates/dagger-codegen/Cargo.toml
- sdk/rust/crates/dagger-codegen/src/functions.rs
- sdk/rust/crates/dagger-codegen/src/rust/functions.rs
- sdk/rust/crates/dagger-codegen/src/rust/mod.rs
- sdk/rust/crates/dagger-codegen/src/rust/templates/enum_tmpl.rs
- sdk/rust/crates/dagger-codegen/src/rust/templates/heading_tmpl.rs
- sdk/rust/crates/dagger-codegen/src/rust/templates/mod.rs
- sdk/rust/crates/dagger-codegen/src/rust/templates/object_tmpl.rs
- sdk/rust/crates/dagger-codegen/src/utility.rs
- sdk/rust/crates/dagger-codegen/src/visitor.rs
- sdk/rust/crates/dagger-sdk/src/client.rs
- sdk/rust/crates/dagger-sdk/src/core/downloader.rs
- sdk/rust/crates/dagger-sdk/src/core/engine.rs
- sdk/rust/crates/dagger-sdk/src/core/gql_client.rs
- sdk/rust/crates/dagger-sdk/src/core/graphql_client.rs
- sdk/rust/crates/dagger-sdk/src/core/mod.rs
- sdk/rust/crates/dagger-sdk/src/core/session.rs
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/rust/crates/dagger-sdk/src/logging.rs
- sdk/rust/crates/dagger-sdk/src/querybuilder.rs
This fixes up some nasty code in the internal codegen of the rust sdk. It not only makes it more ideomatic, but also faster because of fewer allocations. 
I also yak shaved a bit as I went, so I removed all the warnings in the codebase that had been around for a while. Clippy sometimes adds new lints, which we can optionally implement. Some of them are more relevant than others.
> rust sdk/refactor/function warnings

- .github/workflows/changelog.yml
Fix https://github.com/dagger/dagger/pull/7750.
See run in https://github.com/dagger/dagger/actions/runs/9697150564/job/26760624393?pr=7744.
This wasn't caught in my example runs, since I was running a PR inside a single fork.
The issues fixed here:
- Added permissions to this workflow to mirror other workflows - we need to be able to write to the pull request to be able to add a comment
- Modified `GITHUB_HEAD_REF` to `GITHUB_REF` to get the current state of the PR as resolved by the merge.
> ci: fix changelog checking pr

- docs/current_docs/quickstart/conclusion.mdx
fixes https://linear.app/dagger/issue/DOCS-304/add-adopting-dagger-page-to-end-of-quickstart
> docs: make quickstart conclusion go to adopting dagger

- engine/cache/mountsync.go
- engine/cache/service.go
The cache manager leverages a check, provided by the cache service, to prevent pushing layers that were previously pushed. In this PR we implement the same behavior for cache mounts. If the cache mount already exists we skip pushing it. 
This will significantly reduce the time it takes to shut down an engine for orgs that have a high number of cache volumes, like ourselves.
> cache: skip uploading cache mounts that already exist

- .changes/unreleased/Added-20240702-171323.yaml
- core/integration/git_test.go
- core/schema/git.go
- core/schema/modulesource.go
- docs/docs-graphql/schema.graphqls
- sdk/elixir/lib/dagger/gen/git_repository.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/GitRepository.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
This is the draft implementation to support a new `git.Tags` API, with corresponding tests, which enables us to retrieve the tags of a remote.
It has been mostly adapted from https://github.com/dagger/dagger/pull/6187/commits/260bde5070780b3ce267bde79de3a66c73eca6a6 (from @vito)
**TODO**
- find a way to exec git with the mounted socket / use the gitdns.git implementation ?
cc @sipsma, I am a bit stuck on the auth part for this API. Does it have to live inside the core/schema implementation ? If yes, how to use the mounted auth socket inside the core/schema package ?
You referenced privately, and in the past, this BuildKit call: https://github.com/sipsma/dagger/blob/64f4aaa2f794f4cb92ae0a833b61a953bc63df6f/engine/sources/gitdns/source.go#L286-L286, but there is also a wrapper that exists …
> core(git): add git tags API

- core/container.go
- core/container_exec.go
- core/directory.go
- core/file.go
- core/git.go
- core/host.go
- core/moddeps.go
- core/modfunc.go
- core/query.go
- core/schema/container.go
- core/schema/directory.go
- core/schema/file.go
- core/schema/git.go
- core/schema/host.go
- core/schema/http.go
- core/schema/module.go
- core/schema/modulesource.go
- core/schema/platform.go
- core/schema/sdk.go
- core/schema/secret.go
- core/schema/service.go
- core/service.go
- core/terminal.go
- core/typedef.go
- engine/server/session.go
(Spinning this commit out of https://github.com/dagger/dagger/pull/7804 because it's super tedious+boring and bloating that other PR too much on top the actual interesting parts.)
To fully isolate client-specific resources within a session, we need to move off of storing things like the SecretStore as fields on Query. This is because the dagql cache is shared across a session, meaning it can return objects from other clients that should not be used.
I just went ahead and got rid of all the fields on Query and turned them into methods. *Technically* it wasn't necessary for all of them, but it's more consistent this way and sets us up for cross-session dagql caching if ever needed.
> engine: prevent dagql cache cross-talk of Query object

- docs/current_docs/quickstart/snippets/build/python/__init__.py
- docs/current_docs/quickstart/snippets/build/typescript/index.ts
- docs/current_docs/quickstart/snippets/daggerize/python/__init__.py
- docs/current_docs/quickstart/snippets/daggerize/typescript/index.ts
In the quickstart, the Go SDK example has the correct exposed Nginx port of 80, but the Python and TypeScript examples incorrectly have 8080.
This means that if a user follows the TS or Python examples and runs this as a service by following
`dagger call build --source=. as-service up --ports 8080:80`
They will never get to connect to Nginx from their local browser.
> fix: correct exposed port from 8080 to 80

- core/integration/container_test.go
- dagql/idtui/frontend.go
- dagql/idtui/frontend_plain.go
*Possibly* fixes, or at least helps, https://github.com/dagger/dagger/issues/7786 by avoiding https://github.com/actions/runner/issues/1031
> tests: avoid GHA slowdown from huge single line strings

- cmd/dagger/main.go
- dagql/idtui/frontend_plain.go
- dagql/idtui/frontend_pretty.go
Currently if you run with `--debug` the CLI will go into a loop constantly logging the same log line repeatedly until it's eventually just a bunch of `\\\\\\\\\\`s from escaping strings in strings.
This was introduced by the recent TUI changes which directed logs to go to the primary span rather than to a separate TUI-only pane. Unfortunately, as part of the log handling (TUI consumes logs), we were logging at debug level, hence `--debug` introducing an infinite loop for any log line printed.
I think I can live without these logs now that draining seems fixed (knock on wood) so we'll just remove them. This was already done for the plain TUI, just not the pretty one.
(Also, fixes `$CPUPROFILE` along the way, since it's been broken for a while.)
> fix infinite logging loop (and CPUPROFILE)

- core/integration/module_call_test.go
- core/integration/module_config_test.go
- core/integration/module_test.go
- core/integration/proxy_test.go
- core/modulesource.go
- core/schema/modulesource_test.go
- engine/vcs/vcs.go
- engine/vcs/vcs_test.go
This extends the integration tests to other VCS.
To do so, it relies on a mirror of dagger-module-tests:
- https://gitlab.com/dagger-modules/test/more/dagger-test-modules-public (auto-sync to-be-done)
- https://bitbucket.org/dagger-modules/dagger-test-modules-public/
(more could be added over time, but most use provider behavior is contained in GitHub, GitLab and Bitbucket)
Current implementation extends the test suite, fixes a few inconsistencies around the VCS URL (URL should almost never contain the .git if present in the ref, as providers do not like them).
It also contains a naive change `HTMLURL()` to make it compatible with all VCS. I wonder if we should not add an enum field representing the VCS inside the `gitSourceModule` type, what do you all think ? 
Now, all integration test …
> chore/fix(core): add integration tests to other VCS

- .github/workflows/sdk.yml
Based on https://github.com/dagger/dagger/pull/7483
Rework of https://github.com/dagger/dagger/pull/7628, that doesn't entirely disable these checks.
> ci: only enable sdk dev engine checks on main

- install.sh
Fixes https://github.com/dagger/dagger/issues/7769.
List of env variables to detect this from is pulled from out own telemetry code:
https://github.com/dagger/dagger/blob/a9155f4b4e68c264e673bbb2a0271701d76c5eb3/engine/telemetry/labels.go#L406-L410
> chore: install.sh should not prompt to install completions in ci

- cmd/dump-id/main.go
- core/terminal.go
- dagql/idtui/frontend.go
Previously, `DumpID` was producing bad output, after lots of refactors to the frontend. Specifically, we were no longer sending newlines after `renderCall` which meant that everything appeared on the same line (additionally, `DumpID` wasn't taking into account that the client terminal is in raw mode, so needs `\r` at each newline).
To resolve this, we create a new little helper struct called `Dump`, which allows configuration of basic options, and can be configured by the dagger engine to get some more readable output.
Before:
❯ dagger call container-echo --string-arg=x terminal
● Attaching terminal: container: Container!Container.from(address: "alpine:latest"): Container!Container.withExec(args: ["echo", "x"]): Container!
dagger / $
After:
❯ dagger call container-echo --string-arg=x …
> fix: ensure terminal dump id is readable

- docs/current_docs/integrations/kubernetes.mdx
mostly doing this since the results currently returned by the query
are not properly organized and curated.
> docs: move k8s integrations resources to the bottom

- engine/server/session.go
Noticed that while debugging some flakiness in https://github.com/dagger/dagger/pull/7804
https://github.com/dagger/dagger/commit/ae1175dbaf1026511403943eb49132012dc6a942 (merged earlier today) improved session shutdown to happen quicker by disconnecting the attachables right when `/shutdown` is called.
`/shutdown` isn't called by nested module clients. However, it's valid when using other nested execs with a full blown CLI for them to call `/shutdown`. This wasn't handled well by that change because we closed the new shutdownCh on any call to /shutdown, resulting in everyone's session attachables getting closed when any of the nested execs shutdown.
The fix is to just only close that shutdownCh when the main client caller calls /shutdown.
Somewhat fascinatingly, our existing tests seem …
> engine: close session shutdown chan only when main client is gone

- docs/current_docs/manuals/administrator/engine/custom-ca.mdx
- docs/current_docs/manuals/administrator/engine/index.mdx
- docs/current_docs/manuals/administrator/engine/proxy.mdx
- docs/sidebars.ts
(Not sure who to request reviews from while Vikram is on PTO, just chose a couple obvious candidates)
Filling in docs on this support now that it has baked with reports of successful usage for a bit.
NOTE: I'm purposely leaving out the experimental GOPROXY support from here for now since it's still in the "hacky _DAGGER_ENGINE_SYSTEMENV_GOPROXY" stage that is more of a bandaid than the http proxy+CA support, pending further work to formalize and stabilize it (https://github.com/dagger/dagger/issues/6599).
* If we're okay with including stuff like that in our official docs, happy to update this with it too
> docs: add docs for proxy+CA support

- cmd/dagger/call.go
- cmd/dagger/main.go
- cmd/dagger/module.go
- cmd/dagger/version.go
- core/integration/module_test.go
- dagql/idtui/frontend_plain.go
- engine/telemetry/cloud.go
This commit changes the CLI so it prints a custom Dagger Cloud trace URL
when the user is not logged in or no `DAGGER_CLOUD_TOKEN` has been set.
Additionally, a custom message gets printed at the end of `dagger init`
and fro any commands that the user supplied the `-v` or `--debug` flags.
Fixes [DEV-4269](https://linear.app/dagger/issue/DEV-4269) [DEV-4268](https://linear.app/dagger/issue/DEV-4268)
Here's some screenshots about how the feature looks:
Log-in message when `init` is called and CLI is not authenticated
Full logged out trace URL: 
Log-in message when `-v` is supplied: 
The custom `/traces/$id` URL will take the user to the quickstart flow which will create a Dagger Cloud organization after logging in.
> cli: add quickstart flow for new users

- cmd/dagger/call.go
commit f8849688129535ad6c2183d6cc7ddfd4f2319691 was accidentally
overriden by an unrebased PR. Bringint it back in.
> cli: bring back f8849688129535ad6c2183d6cc7ddfd4f2319691

- .changes/unreleased/Added-20240704-183832.yaml
- cmd/dagger/main.go
- dagql/idtui/frontend.go
- dagql/idtui/frontend_pretty.go
- docs/current_docs/reference/cli.mdx
CLI verbosity scheme is now:
* `-s`/`--silent`: total silence, no progress displayed ever
* `-q`/`--quiet`/`$DAGGER_QUIET`: show progress, clean up completed progress
* default: show progress, keep completed items
* `-v`: show internal and encapsulated progress
* `-vv`: show spammy progress, reveal digests
* `-d`/`--debug`: show everything, set debug log level, reveal span IDs and other misc things
WIth `$DAGGER_QUIET` set, use `-v` to achieve the original default, which also matches the v0.11.x behavior.
Some fixes along the way:
* Final render now respects `-s`
> tui: add `-q`/`$DAGGER_QUIET`, better durations + errors

- sdk/typescript/introspector/test/invoke.spec.ts
@jedevc raised an issue happening sometime in the TS test, it seems the `6000ms` timeout isn't correctly applied for multi tests cases.
This PR aims to fix that by adding the `timeout` to every specific cases.
> fix: ts sdk extend timeout

- dagql/idtui/frontend.go
- dagql/idtui/frontend_pretty.go
- dagql/idtui/spans.go
- dagql/idtui/types.go
Verbosity adjustments + a couple of tweaks to align the TUI with Cloud.
* `-v` expands completed items; `-vv` and `-vvv` now same as before
* use "active duration" (including effects) to calcualte span duration
* hide primary output on error (same as Cloud)
> tui: better durations, less spammy errors, tweak `-v`

- core/moddeps.go
- core/module.go
- core/modulesource.go
- core/schema/module.go
- dagql/testdata/introspection.json
- engine/server/session.go
Collection of various follow ups from #7759:
- Cloning issues - without doing cloning in the right way, we can get all sorts of fun issues, where deps are shared in confusing ways.
- Update golden testdata for dagql
- Elegantly handle a dagger.json without an `engineVersion` (assume it's from an older dagger version, before we had `engineVersion`)
> fix: various core dynamic schema follow-ups

- cmd/dagger/engine.go
- cmd/dagger/main.go
- core/container_exec.go
- core/integration/module_terminal_test.go
- core/modfunc.go
- core/service.go
- dagql/call/id.go
- docs/current_docs/reference/cli.mdx
- engine/buildkit/blob.go
- engine/buildkit/client.go
- engine/buildkit/executor.go
- engine/buildkit/ref.go
- engine/client/client.go
- engine/opts.go
- engine/server/session.go
Add a `--interactive` (`-i`) option to `dagger call` which will spawn
a terminal when a container execution fails
> Interactive Debugging

- .changes/unreleased/Fixed-20240708-120146.yaml
- core/healthcheck.go
Otherwise the exponential backoff can keep going indefinitely and wait too long.
Fixes https://github.com/dagger/dagger/issues/7775
> core: cap healthcheck retries at max of 10s interval

- sdk/typescript/.changes/unreleased/Changed-20240709-123212.yaml
- sdk/typescript/runtime/main.go
fixes #7433 
We'll need to bump to v22 in October 2024
Based on multiples Discord message, we cannot ignore this dependency issue anymore, I'm fixing this now so we do not hit this issue anymore.
> feat: downgrade ts runtime to LTS

- .changes/unreleased/Added-20240708-220148.yaml
- cmd/dagger/flags.go
- core/integration/module_call_test.go
In this PR, add expand tilde (`~`) to home directory on directory, file and secret file source argument. The home directory rely on `os.UserHomeDir()` that using `$HOME` for unix and `$env:USERPROFILE` on Windows. 
Ref for discussion: https://discord.com/channels/707636530424053791/1003718839739105300/1258097710851162145
> feat: expand tilde in secret, directory and file argument

- engine/telemetry/labels.go
- engine/telemetry/labels_test.go
This PR sets two basic Jenkins labels when the engine runs in a Jenkins context.
This is needed to complement missing Git metadata when case Jenkins runs [without an explicitly checked-out branch](https://www.jenkins.io/doc/pipeline/steps/git/#git-git) when running a [pipeline](https://www.jenkins.io/doc/book/pipeline/).
For more context on this see #7776 
- As opposed to the other package functions such as `WithGitHubLabels`, we cannot look up a `JENKINS=true` env variable, so the most appropriate and consistent label to identify Jenkins as the context Dagger is running on is `JENKINS_HOME`. 
- No other labels are being added as they are not needed for a basic integration with Dagger Cloud.
> feat: identify and set Jenkins metadata

- cmd/codegen/generator/go/templates/src/_types/object.go.tmpl
- cmd/codegen/generator/typescript/templates/src/method_solve.ts.gtpl
- sdk/go/dagger.gen.go
- sdk/typescript/api/client.gen.ts
Fixes https://github.com/dagger/dagger/issues/7788
Didn't affect just `sync`. Not sure if the affected fields in `Service` had issues before this.
> fix(codegen): load object when output needs to be converted from ID in Go and TypeScript

- core/integration/engine_test.go
- core/modulesource.go
- core/schema/module.go
- engine/version.go
As discussed in https://github.com/dagger/dagger/issues/7640.
This is a follow-up to https://github.com/dagger/dagger/pull/5315, which will allow us to add a backwards compatibility check if/when we make breaking changes to the module API, etc.
This uses the `engineVersion` field introduced in [`1377f13` (#6469)](https://github.com/dagger/dagger/pull/6469/commits/1377f132cfbf280c21f6e29af88451ecf8273c38).
> feat: add module versioning compat checks

- cmd/dagger/module.go
- docs/current_docs/reference/cli.mdx
Previously the `-m` help suggested that you could point to the `dagger.json` file, but we expect a path to the _directory_ containing that file. This PR fixes that.
Notice: `not a directory` below 👇 
```
/tmp ➤ dagger call -m ./foo/dagger.json container-echo --string-arg "hi" stdout
Full trace at https://dagger.cloud/dagger/traces/dc3b6b41e71da24f381266d02dede97f
✔ connect 1.3s
✔ connecting to engine 0.3s
✔ starting session 0.2s
✘ initialize 0.3s
! failed to get configured module: error trying to find config path for ./foo/dagger.json: failed to lstat foo/dagger.json/dagger.json: lstat foo/dagger.json/dagger.json: not a directory
Error: failed to get configured module: error trying to find config path for ./foo/dagger.json: failed to lstat foo/dagger.json/dagger.json: lstat …
```
> cli: correct mod cmd help to point to dir not file

- dev/README.md
From the context of the documentation I believe this is the right file to reference post-refactor (https://github.com/dagger/dagger/pull/7483).
Please let me know if you need anything else.
> Overlooked docs reference merged in PR #7483

- dev/README.md
Right now the dev shell sample returns a container, adding terminal makes this a one liner that someone can use to actually get into a shell.
> docs: chain terminal to dev shell example

- dev/dirdiff/dirdiff.go
This makes our pipelines slightly more efficient.
Signed-off-by: Solomon Hykes <solomon@dagger.io>
> pipelines: use apko instead of apk

- dagql/idtui/frontend_pretty.go
In some situations (in my case: terminal in Zed in Distrobox on Fedora with Sway) the `c: Cloud` key will work but dump a bunch of diagnostic output directly to `os.Stderr` in the process which breaks the TUI.
Now we'll buffer that output and only show it if opening the browser fails.
> prevent browser.OpenURL logs from breaking TUI

- cmd/dagger/cloud.go
- internal/cloud/auth/auth.go
Without this, we're just writing directly on top of the TUI, oops!
Before:
```
❯ dagger login jedevc
─   ←↑↓→: move  home: first  end: last  enter: zoom  +/-: verbosity=1  q: quit ────────────────────────
To authenticate, visit:
https://auth.dagger.cloud/activate?user_code=XHSW-TXFD
Success.
```
After, this all collapses down neatly.
> fix: print to otel span for dagger login

- cmd/dagger/cloud.go
- cmd/dagger/engine.go
- cmd/dagger/main.go
- dagql/idtui/frontend.go
- dagql/idtui/frontend_plain.go
- dagql/idtui/frontend_pretty.go
- docs/current_docs/reference/cli.mdx
- engine/client/client.go
this commit introduces the following changes:
- Keystroke for web visualization is now `w` for both logged-in and
logged-out clients.
- New `--web` global flag visualize trace in web browser.
- Trace URL display:
- logged in: URL gets printed at the top honoring -q and -s
flags
- logged out: Same as logged in with the ability to disable the
message by setting an environment variable.
Screenshots below:
<details>
<summary>Logged out</summary>
- dagger command with TUI shows `w` action
-  dagger command with TUI message lingers at the top
- dagger command `-q` with TUI  message is not printed
- dagger command `--progress plain` message is printed at the top
- setting env var skips logged out message
</details>
<details>
<summary>Logged in</summary>
-  dagger command with TUI message lingers …
> cli: improve UX to show cloud URL

- dagql/idtui/frontend_pretty.go
e.g. early/local failure like dagger login without selected org
without this, `dagger login` (no org) can fail silently:
> print primary output if err but no progress

- cmd/dagger/module.go
- core/integration/module_test.go
- core/modulesource.go
- core/schema/module.go
- dev/test.go
- engine/server/session.go
Some cherry-picks and pieces from #7858, since that one has some issues, and is risky!
Specifically:
- Fix the process of updating a `dagger.json` during `dagger develop` in certain edge cases with low engine versions (this was broken before, and now has some tests as well)
- The engine should serve the CLI the API that it's `clientVersion` indicates it has - this isn't super useful right now, but is quite nice in the context of #7858.
> Some very small version compat follow-ups

- cmd/codegen/generator/functions.go
- cmd/codegen/generator/go/generator.go
- cmd/codegen/generator/go/templates/functions.go
- cmd/codegen/generator/go/templates/module_objects.go
- cmd/codegen/generator/go/templates/modules.go
- cmd/codegen/generator/go/templates/src/_dagger.gen.go/module.go.tmpl
- cmd/codegen/generator/go/templates/src/_types/object.go.tmpl
- cmd/codegen/generator/go/templates/src/dag/dag.gen.go.tmpl
- cmd/codegen/generator/typescript/generator.go
- cmd/codegen/generator/typescript/templates/functions.go
- cmd/codegen/generator/typescript/templates/src/helper_test.go
- cmd/codegen/generator/typescript/templates/src/method_solve.ts.gtpl
- cmd/codegen/generator/typescript/templates/templates.go
- cmd/codegen/introspection/introspection.go
- cmd/dagger/functions.go
- cmd/dagger/module.go
- core/integration/legacy_test.go
- core/integration/localcache_test.go
- core/integration/module_test.go
- core/integration/testdata/modules/go/ifaces/dagger.json
- core/integration/testdata/modules/go/ifaces/main_test.go
- sdk/go/.changes/unreleased/Breaking-20240627-142405.yaml
- sdk/go/dagger.gen.go
- sdk/python/.changes/unreleased/Breaking-20240627-142254.yaml
- sdk/python/codegen/src/codegen/generator.py
- sdk/python/src/dagger/client/gen.py
- sdk/typescript/.changes/unreleased/Breaking-20240627-142448.yaml
- sdk/typescript/api/client.gen.ts
> [!WARNING]
> This is a **breaking change** in Go! 💥
Fixes https://github.com/dagger/dagger/issues/6868
When depending on a module's function that doesn't return a value (returns only error or nothing):
```go
func (m *SomeModule) DoSomething() error {
// do something that may return an error
}
```
Generated client bindings will now return only the error, and not the useless `Void` value (which is always an empty string):
```go
// ❌ before
_, err := dag.SomeModule().DoSomething(ctx)
// ✅ after
err := dag.SomeModule().DoSomething(ctx)
```
> 💥 codegen: don't return `Void`

- dagql/idtui/frontend_pretty.go
since there seem to be cases that the progress report don't cover
will bring this back along with more robust TUI error handling
> bring back redundant errors

- core/integration/module_test.go
- engine/server/session.go
Follow up from #7889
We should also serve generalized nested clients the right client API - and then have tests for this.
> fix: ensure we serve nested clients the correct schema version

- sdk/typescript/runtime/main.go
We keep seeing this error over-and-over: https://dagger.cloud/dagger/traces/fac54672078ee95878b8684af05a814b?span=4c9874e76c2371de#ca88400300bc5d96
Lots of things of the form:
```
error: moving "binary-extensions" to cache dir failed: PathAlreadyExists
From: .544670b85583f3c2binary-extensions
To: binary-extensions@2.3.0
```
Something doesn't seem very right there, but given it's flakiness, I suspect it's something to do with concurrent cache access - so we can just give bun access to Private cache.
> chore(ts): use private cache for bun

- dev/helm.go
- helm/dagger/Chart.yaml
Without this, the following steps from `RELEASING.md` create the wrong tag name:
```
export HELM_CHART_VERSION="$(awk '/^version: / { print $2 }' helm/dagger/Chart.yaml)"
git tag "helm/chart/v${HELM_CHART_VERSION:?must be set}" "${SDK_GIT_SHA:?must be set}"
```
This creates `helm/chart/vv0.12.0` (with two `v`s). According to https://helm.sh/docs/topics/charts/, the `version` field must be semver, no `v` prefix is allowed.
> chore: fix helm versions to keep semver in version field

- docs/current_docs/manuals/developer/module-dependencies.mdx
- docs/current_docs/manuals/user/artifacts/consumption/exec.mdx
- docs/current_docs/manuals/user/artifacts/consumption/export.mdx
- docs/current_docs/manuals/user/artifacts/consumption/publish.mdx
- docs/current_docs/manuals/user/artifacts/consumption/terminal.mdx
- docs/current_docs/manuals/user/artifacts/production/containers.mdx
- docs/current_docs/manuals/user/artifacts/production/directories.mdx
- docs/current_docs/manuals/user/artifacts/production/inspect.mdx
- docs/current_docs/manuals/user/functions/arguments.mdx
- docs/current_docs/manuals/user/functions/call.mdx
- docs/current_docs/manuals/user/functions/chaining.mdx
- docs/current_docs/manuals/user/host/host-env.mdx
- docs/current_docs/manuals/user/host/host-fs.mdx
Some modules in our docs aren't working in Dagger v0.12.0, most likely due to dev `engineVersion` (@shykes) or old Go version in `go.mod` (@kpenfound).
> chore(docs): update daggerverse modules

- sdk/elixir/dagger_codegen/lib/dagger/codegen/introspection/types/type.ex
- sdk/elixir/dagger_codegen/lib/dagger/codegen/introspection/types/type_ref.ex
- sdk/elixir/dagger_codegen/test/dagger/codegen/elixir_generator/object_renderer_test.exs
Some fields in introspection json are not guarantee to present when it's optional. It cause the codegen crash because it expected those fields to have it. Fixed by make it optional by getting it via `[key]` instead.
And in this fix, include update outdated snapshot tests.
> fix(sdk/elixir): fix codegen break the runtime

- .changes/unreleased/Fixed-20240711-221446.yaml
- core/integration/module_call_test.go
- core/schema/modulesource.go
Fixes https://github.com/dagger/dagger/issues/7762
Current implementation of parseRefString does not allow local refs to have @, as it considers this character as the module version separator
However, this is not supposed to be true for local refs, to which the notion of version is not relevant
> fix(core): allow local module ref with @

- dev/helm.go
- helm/dagger/Chart.yaml
- helm/dagger/templates/_helpers.tpl
Fixes #7916 (which is a regression from #7854), follow-up to #7906
We should ensure that both fields are semver, and have no "v" prefix - then we can add the v prefix ourselves in the templated code.
> fix(helm): ensure appVersion is always semver

- docs/current_docs/cookbook/snippets/continue-after-errors/typescript/index.ts
- docs/current_docs/manuals/developer/custom-types.mdx
- docs/current_docs/manuals/developer/snippets/chaining/typescript/index.ts
- docs/current_docs/manuals/developer/snippets/custom-types/typescript/index.ts
- docs/current_docs/manuals/developer/snippets/documentation/typescript/object.ts
- docs/current_docs/manuals/developer/snippets/entrypoint/typescript/default-object-in-field/index.ts
- docs/current_docs/manuals/developer/snippets/entrypoint/typescript/default-object/index.ts
- docs/current_docs/manuals/developer/snippets/state-functions/typescript/index.ts
- docs/current_docs/manuals/developer/state-functions.mdx
Follows up #7701 with a doc update
> docs: update ts docs field to `@func`

- cmd/dagger/version.go
Fixes #7914 (thanks @nipuna-perera!)
We were avoiding direct use of Stdout/Stderr *pretty* well, however, not for `dagger version`. If we write directly to it, it has the potential to overlap with the TUI, which can cause the output to be weirdly cleared.
> fix: ensure dagger version uses otel output

- helm/dagger/templates/_helpers.tpl
In https://github.com/dagger/dagger/commit/3bedee341e04a8d92a8c9161e6e72a8ad19e1170 we introduced a change that breaks the chart when installing it since it tries to create a label of `v"0.12.0"` which is not a valid value:
We don't need to apply the quote in this case, it will be treated as a string. With the fix I can install it successfully:
> Do not use `quote` in labels to make it a valid string

- docs/current_docs/integrations/snippets/Jenkinsfile
- docs/current_docs/integrations/snippets/actions.yml
- docs/current_docs/integrations/snippets/argo-workflow.yaml
- docs/current_docs/integrations/snippets/azure-pipelines.yml
- docs/current_docs/integrations/snippets/buildspec.yml
- docs/current_docs/integrations/snippets/circle.yml
- docs/current_docs/integrations/snippets/gitlab-docker.yml
- docs/current_docs/integrations/snippets/gitlab-kubernetes.yml
- docs/current_docs/integrations/snippets/tekton-dagger-task.yaml
- docs/current_docs/manuals/user/artifacts/consumption/export.mdx
- docs/current_docs/manuals/user/artifacts/production/directories.mdx
- docs/current_docs/manuals/user/artifacts/production/inspect.mdx
- docs/current_docs/manuals/user/functions/arguments.mdx
- docs/current_docs/manuals/user/functions/chaining.mdx
- docs/current_docs/manuals/user/host/host-fs.mdx
- docs/current_docs/manuals/user/remotes/remote-repositories.mdx
- docs/current_docs/manuals/user/visualization/cloud-get-started.mdx
We just updated https://github.com/kpenfound/dagger-modules/releases/tag/golang%2Fv0.2.0 and this PR updates the docs to use the new version.
Examples were tested as they were changed. 👍 
https://gist.github.com/jpadams/f3c851a129f879bbbb6990f5cf3ddde4
> docs: update golang module version

- dev/docs.go
- docs/static/api/reference/index.html
Since Daggerization of the CI, the API reference is not part of the docs update. It is however still exposed on our docs, and should follow the current API state: https://docs.dagger.io/api/reference/
This adds to the docs module a new `GenerateAPIReference` function, also added to the `Generate` function.
It also updates the index.html to the latest API reference
> ci: update API reference on new CI

- cmd/dagger/engine.go
- cmd/dagger/main.go
This goes someway towards fixing https://github.com/dagger/dagger/issues/7856.
Only commands that connect to a running engine upload telemetry, while commands that don't, like `version`, `login`/`logout`, and the top-level dagger command (as well as non-existent commands, like running `dagger nope-this-doesnt-exist`) won't initialize telemetry to send to cloud, or the frontend to display it.
> fix: only initialize telemetry when connecting to engine

- internal/cloud/auth/auth.go
Implements part 2 of @shykes' solution in https://github.com/dagger/dagger/issues/7920
We already integrate with the browser in other places, so why not extend it to `login`. This way we don't have to worry about whether the URL is clickable/selectable.
> login: open browser automatically

- .github/actions/call/action.yml
Seeing some runs that seem to hang for a while after they supposedly complete. Ideally we could do this for all jobs, not just `testdev`, but it's easy to start with it.
note: thought about making this only run on failure, but it seems like we can just do it always; the `.zip` is ~7MB for a successful run and afaik doesn't cost us anything.
> github: upload dev engine logs

- .github/dependabot.yml
- dev/ruff/build/Dockerfile
- dev/ruff/main.go
Ruff is a single binary that doesn't need Python to install or even use. 
It has a docker image which is the best way to install it with Dagger. 
Used a Dockerfile so that dependabot can help keep it up to date.
> chore(dev/ruff): refactor base image for ruff module

- cmd/dagger/main.go
- cmd/dagger/span_name.go
- dev/docs.go
- dev/engine.go
- dev/go/main.go
- dev/golangci/lint.go
- dev/main.go
- dev/sdk_go.go
- dev/sdk_python.go
- dev/sdk_typescript.go
- sdk/python/runtime/main.go
Noticed in https://github.com/dagger/dagger/pull/7872#discussion_r1680759963
There are two issues:
- Some errors have an empty "Severity" - not entirely sure why, but some of the code was handling this correctly, but Assert wasn't.
- The `GOLANGCI_LINT_CONFIG` doesn't seem to have been being respected, I can't find any reference to it. So we can just use the suggested use of from the docs.
> ci: fix go linter

- docs/current_docs/manuals/user/artifacts/consumption/export.mdx
- docs/current_docs/manuals/user/artifacts/production/files.mdx
- docs/current_docs/manuals/user/artifacts/production/inspect.mdx
- docs/current_docs/manuals/user/functions/chaining.mdx
These example had issues due to a change in the Dagger CI modules layout and an older dependency. Changed to using `ruff` module instead. Otherwise, very similar.
> docs: fixup linters examples with ruff

- .github/actions/call/action.yml
Updates our special telemetry-only token to use the new format, so we don't get *constantly* prompted to rotate our creds.
Thanks @marcosnils for the token :tada:
> ci: update DAGGER_CLOUD_TOKEN

- cmd/dagger/call.go
- cmd/dagger/functions.go
- core/integration/module_test.go
- core/schema/container.go
- core/schema/module.go
- docs/docs-graphql/schema.graphqls
- engine/server/session.go
- sdk/elixir/lib/dagger/gen/terminal.ex
- sdk/go/dagger.gen.go
- sdk/php/generated/Terminal.php
- sdk/python/src/dagger/client/gen.py
- sdk/rust/crates/dagger-sdk/src/gen.rs
- sdk/typescript/api/client.gen.ts
Fixes #7907.
The client is expecting a given API - loading a module *shouldn't* update the version of the API that it's served. This was a minor design mistake, and just doesn't make sense as is.
With that patch, there are now *no* fields on the `Terminal` type that are served to a v0.12 CLI. This is an issue, because now, nothing forces the evaluation of the type!
To avoid this, we add `Terminal.sync`, which allows the CLI to force execution of a `Terminal` type, with a special field just for this. The fact that this seemed to work before at all is pretty much coincidence (because we kept the `websocketEndpoint` field).
> fix: `Module.serve` should not modify the caller's core module

- .github/actions/call/action.yml
Followup to https://github.com/dagger/dagger/pull/7933 (cc @vito)
If a single workflow run contains multiple `dev-engine` jobs, then uploading the artifacts will fail. To do this, we can make them unique using the runner name.
See the failing job on main: https://github.com/dagger/dagger/actions/runs/9970998498/job/27551091011#step:3:5005
> ci: fix upload engine logs with multiple dev-engine jobs

- dev/cli.go
Follow-up to https://github.com/dagger/dagger/pull/7939
We need to use the entrypoint explicitly here, see https://github.com/dagger/dagger/actions/runs/9971938618/job/27554089721#step:8:453
> ci: fix broken cli publishing from upgrade to v0.12

- .changes/unreleased/Added-20240717-101724.yaml
- cmd/dagger/module.go
- core/integration/module_test.go
- docs/current_docs/reference/cli.mdx
We removed this last minute in https://github.com/dagger/dagger/pull/7759/#discussion_r1668419158.
However, it does seem like we need *something* here - so proposing this back in. Let the bikeshedding of naming/etc begin, I don't have particularly strong opinions here :tada:
> feat: add --compat flag to dagger to specify api version

- core/integration/cacert_test.go
- engine/buildkit/executor_spec.go
Fixes https://github.com/dagger/dagger/issues/7910
Custom CAs were not working with Terminal due to the fact that
installing custom CAs required running setup/teardown execs. Those execs
were getting inconsistent configuration that partly configured terminals
to be setup but also partially not (specifically, runc was told to setup
a tty but did not find /dev/tty).
The fix here is to just fully disable terminals on those setup/teardown
execs.
Majority of the diff here is to add integ test coverage, which starts a
terminal in a nested engine configured w/ custom CAs and does a curl of
a nginx server configured with those custom CAs. If the CAs aren't setup
or an error is hit the test fails too.
> engine: fix terminal in combination w/ custom CAs

- dev/cli.go
- dev/docs.go
- dev/engine.go
- dev/go/main.go
- dev/main.go
- dev/scripts.go
- dev/sdk.go
- dev/sdk_elixir.go
- dev/sdk_go.go
- dev/sdk_java.go
- dev/sdk_php.go
- dev/sdk_python.go
- dev/sdk_rust.go
- dev/sdk_typescript.go
- The source code of Dagger includes some Dagger pipelines
- Therefore our CI/CD pipelines sometimes process the source code of Dagger Modules - for example to lint them
- This processing sometimes requires invoking Dagger codegen against those modules - the equivalent of `dagger develop`
- So far our pipelines have done this on a case-by-case basis, but that makes the source code harder to read
- all access to the Dagger source code from any part of the pipeline, is gated by `DaggerDev.source()` which ~~*always*~~ optionally applies codegen on all dagger modules.
- The list of modules is manually maintained for now, but should be made dynamic in a follow-up improvement
- ~~This can probably be optimized (not all pipelines that access the dagger source code actually need codegen, but they …
> pipelines: streamline codegen

- .github/dependabot.yml
We no longer have a `website` dir since:
- https://github.com/dagger/dagger/pull/6164
It's been merged into `docs`.
> chore: fix dependabot for docs

- dev/dagger.json
I recently updated the docusaurus module to be compatible with v0.12, this commit updates it for this this project as well. I tested this out locally to make sure it is working as expected.
`dagger call -m dev --source . docs server as-service up`
> pipeline: bump docusaurus module

- dev/cli.go
`binary` is more intuitive than `file` (I kept both for backwards compat).
> pipelines: daggerDev().cli().binary()

- core/integration/container_test.go
- core/integration/module_test.go
While merging a lot of the things for v0.12.1, a few things got lost in the noise:
- `TestContainer/TestInsecureRootCapabilitesWithService` does docker network access, and so should be given the host's docker config if it can be found.
- `TestModuleDevelopVersion` has some duplication with `TestModuleSchemaVersion` - we can remove those, since all the permutations are tricky to handle in the develop test.
> Fix broken tests that got lost in the noise

- .github/actions/call/action.yml
A bunch of the SDK dev tests fail because different steps try to upload the dev engine logs but get an error since the logs artifact already exists.
I *think* that setting overwrite to true will avoid this, but can't know until I merge.
Example of failures: https://github.com/dagger/dagger/actions/runs/9997156850/job/27633082976
> ci: overwrite artifacts if already there

- docs/current_docs/index.mdx
v0.12 adds support for Git servers beyond Github. Updating docs to reflect this new capability.
> docs: Updating git language

- docs/current_docs/manuals/user/host/host-services.mdx
Support for unix sockets as function args was merged here: https://github.com/dagger/dagger/pull/7804 so it will be in the upcoming release.
I created a tiny demo module that I reference in the docs; it currently just lets you pass a host docker unix sock as an arg and then calls "docker version" on it: https://github.com/sipsma/daggerverse/blob/c19ee68f84b228942bac8047a9d8337fc22a3479/docker-client/main.go
**Should not be deployed until next release (0.12.1)**
> docs: doc support for unix socket args

- docs/current_docs/manuals/developer/entrypoint-function.mdx
- docs/current_docs/manuals/developer/snippets/entrypoint/typescript/default-object-in-field/index.ts
- docs/current_docs/manuals/developer/snippets/entrypoint/typescript/default-object/index.ts
There's no need to introduce `@func` in object properties in [Entrypoint Function](https://docs.dagger.io/manuals/developer/entrypoint-function#default-values-for-complex-types) since it hasn't been introduced yet. 
Only added confusion because it appears it's needed for the constructor.
🔎 [Preview](https://deploy-preview-7967--devel-docs-dagger-io.netlify.app/manuals/developer/entrypoint-function#default-values-for-complex-types)
> docs: fix typescript snippets in Entrypoint Function page

- .github/actions/call/action.yml
- .github/workflows/_sdk_check.yml
- .github/workflows/docs.yml
- .github/workflows/engine-and-cli-publish.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/helm-publish.yml
- .github/workflows/helm-test.yml
- .github/workflows/sdk-elixir-publish.yml
- .github/workflows/sdk-go-publish.yml
- .github/workflows/sdk-php-publish.yml
- .github/workflows/sdk-python-publish.yml
- .github/workflows/sdk-rust-publish.yml
- .github/workflows/sdk-typescript-publish.yml
- RELEASING.md
- dev/go.mod
- go.mod
More follow-ups once release is done:
- I attempted a fix for this here, details in commit message: https://github.com/dagger/dagger/pull/7983/commits/49670c60801087745951be532ad01a7184a4158a
> Improve releasing during v0.12.1

- cmd/dagger/engine.go
A silly var capture issue. :grimacing: 
If ever there were a time for a linter to help...
Fortunately the command itself still fails, so everyone's CI should be doing the right thing, but traces in Cloud and GitHub checks currently never fail.
> fix root span never failing

- helm/dagger/Chart.yaml
Not sure what's supposed to do this normally, but it was missed during the release process.
> bump Helm chart to v0.12.2

- .goreleaser.nightly.yml
- install.sh
So that we can reference it in our `runs-on` CI runner configurations.
Setting `DAGGER_COMMIT=head` will pull the latest CLI built from `main`. We are not templating the branch name on purpose. When we introduce release branches, we should revisit this. For now, we are keeping this as simple as possible for as long as possible.
After this gets merged:
---
Tested after running it locally against the release destination replica:
> ci: Publish nightly as `main/head`

- .changie.yaml
- helm/dagger/.changie.yaml
- sdk/elixir/.changie.yaml
- sdk/go/.changie.yaml
- sdk/php/.changie.yaml
- sdk/python/.changie.yaml
- sdk/rust/.changie.yaml
- sdk/typescript/.changie.yaml
This is part of an effort to start writing better changelogs! Just added some people to review who I've chatted to about this before :tada:
Changie supports multiline bodies, that looks something like this:
The idea is to have more extensive changelogs as we go forward, essentially *trying* to follow something like a "git commit" format:
- The first line should be a summary of the change
- Any other details afterward can provide more details about the contents of the change, e.g. for breaking changes, information on how to migrate
After allowing these multiline bodies, we also need to update the output format so that the author and PR appear on the first line, while the details appear below - essentially the format we used for v0.12.0 for the breaking changes (which I quite liked): …
> chore: encourage multiline changie bodies

- .changes/unreleased/Fixed-20240722-232708.yaml
- core/integration/module_test.go
- core/interface.go
- core/modfunc.go
- core/object.go
- engine/buildkit/executor.go
- engine/server/session.go
The recent change to isolate secrets+sockets works by tracking which resources a given client should have access to based on inputs+outputs to/from function calls.
Unfortunately, on the input-side, this only handled arg value inputs, but I missed the other source of inputs: fields set in the parent object. If you had a module object with a Secret (or a Container with an embedded Secret, etc.) field, then trying to use that Secret in chained function calls usually failed.
The fix is straightforward and re-uses existing plumbing to walk values and find all the IDs embedded in them; it's just now also called on the parent object fields (if any).
Also includes integ test coverage for this case.
---
Fixes https://github.com/dagger/dagger/issues/8010
> core: fix missing secrets+sockets from parent object fields

- .changes/unreleased/Fixed-20240718-223638.yaml
- cmd/engine/logger.go
- core/container_exec.go
- core/integration/client_test.go
- engine/buildkit/executor.go
- engine/buildkit/executor_spec.go
- engine/buildkit/filesync.go
- engine/client/client.go
- engine/client/stableid.go
- engine/opts.go
- engine/server/session.go
As detailed in #7900, certain obscure corner cases can result in
separate clients on separate hosts (or separate nested exec containers)
from re-using each others' filesync cache refs unexpectedly and, if
files happen to match metadata precisely, end up with incorrect
file contents being used in the sync.
The requirements for this to happen are as obscure as it gets, but it is
impacting our CI and causing flakes, so needs a fix. It is *technically*
possible for users to hit this too, so may as well solve it for them.
Previously part of the cause here was that we used hostname as a
semi-stable host identifier, but nested clients mostly have the same
default container hostname.
* There was much more to it than this, but this is the part we can
address.
The fix here replaces the hostname …
> Fix nested client filesync incorrect deduplication

- dagql/idtui/frontend_plain.go
Fixes https://github.com/dagger/dagger/issues/7913
This contains two main fixes:
- The first fixes context sampling, so that we always take everything *up to* the first call. This means we can keep `initializing module` under `initializing`.
- The second fixes the effect wake-up by removing it - we don't actually need it for plain progress, there should never be a case when the plain progress will *stop* rendering for a span (it's assumed to live forever really). This was causing a lot of wake-ups deep under `initialize`, which was causing the "increased verbosity" (introduced in [`14ae071` (#7686)](https://github.com/dagger/dagger/pull/7686/commits/14ae07195f6ac07b42792b38cfb6b060c4fc3101))
> Keep plain progress default verbosity neat

- dev/README.md
The existing dev module documentation instructs developers to run a test which doesn't exist. This PR updates the example to point at the renamed test, with the added side benefit of making it clear that many core/integration tests are subtests.
> fix dev module custom test running documentation

- .changes/unreleased/Added-20240723-171437.yaml
- cmd/dagger/functions.go
- core/integration/module_call_test.go
A while ago in Discord, a user expected that `dagger call` exited with the same exit code of the test suite tool they were using in the function. I thought why not, and it's easy to add.
> cli: propagate exit code from function

- core/integration/module_python_test.go
- sdk/python/.changes/unreleased/Added-20240723-134519.yaml
- sdk/python/src/dagger/mod/_module.py
- sdk/python/src/dagger/mod/_resolver.py
- sdk/python/src/dagger/mod/_utils.py
- sdk/python/tests/modules/test_utils.py
Name overrides were created as an escape hatch to allow using function, attribute, and parameter names that conflict with Python reserved words:
```python
from typing import Annotated
import dagger
@dagger.object_type
class Test:
from_: str = dagger.field(name="from")
@dagger.function(name="with")
def with_(self, import_: Annotated[str, dagger.Arg("import")] = "") -> str:
return import_
```
Since the convention in these cases is to add an underscore to the end, we can remove it automatically when registering the name with Dagger:
```python
import dagger
@dagger.object_type
class Test:
from_: str = dagger.field()
@dagger.function
def with_(self, import_: str = "") -> str:
return import_
```
This avoids the need to override the name in a way that's not documented.
It applies to names that …
> feat(sdk/python): normalize names to avoid escape hatch for reserved keywords

- core/terminal.go
When getting a terminal in Debian based containers, the working directory does not show up correctly:
This is especially visible when using non alpine golang or debian images.
To reproduce simply do `dag.Container().From("golang").Terminal()`
This change in PS1 does not use parameter expansion but `pwd` and `sed` to replicate the same behavior.
> fix: print current directory without parameter expansion

- cmd/codegen/generator/go/generator.go
This seems to have been accidentally added when removing go aliases (https://github.com/dagger/dagger/pull/7831/files#diff-9071102708f2192ab3f79607ad8aa444993a76461970710294b407e9db34289cR397-R399)
That was a mistake, and it shouldn't be there.
> chore: remove accidental Echo method

- .github/actions/call/action.yml
- .github/workflows/_sdk_check.yml
- .github/workflows/docs.yml
- .github/workflows/engine-and-cli-publish.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/helm-publish.yml
- .github/workflows/helm-test.yml
- .github/workflows/sdk-elixir-publish.yml
- .github/workflows/sdk-go-publish.yml
- .github/workflows/sdk-php-publish.yml
- .github/workflows/sdk-python-publish.yml
- .github/workflows/sdk-rust-publish.yml
- .github/workflows/sdk-typescript-publish.yml
- RELEASING.md
- dev/dagger.json
- dev/go.mod
- go.mod
TODOs after release is done:
- `find .github/ -type f -exec sed -i 's/0-12-2/0-12-3/g; s/0\.12\.2/0\.12\.3/g' {} +`
- Can do same for the dagger-for-github updates
- (Maybe if time) chisel away at one manual step, e.g. automate the SDK changelog generation + engine version bump in CLI docs so that the bump PR doesn't need extra pushes w/ manual changes
- Going to do this but decided to spin out to different PR after working on it since it has some meaningful changes in the `dev/` module that I don't want to block this PR on
- separate PR here https://github.com/dagger/dagger/pull/8043
> Improve releasing during v0.12.3

- .changes/unreleased/Fixed-20240729-234852.yaml
- core/integration/module_test.go
- core/schema/secret.go
The use case of:
1. Building Dockerfiles via the `Container.build` or `Directory.dockerBuild` APIs
2. That have secrets attached
3. That were created by modules and returned as `Container` values
Appears to have been broken for a while.
Before the secret isolation in v0.12.1, it was broken because these returned Dockerfiles were re-evaulated when the core ID was loaded after the function returned but the accessor was calculated again based on the *caller*, which resulted in a different secret value and thus missing secrets when the Dockerfile evaluation got unlazied.
After v0.12.1, the error changed to be a bit earlier, but still happened as the core ID for the returned Dockerfile build was being loaded. It now was happening because the `Container.build` implementation synchronously …
> core: fix dockerfile secrets in modules by making secret pure

- .github/workflows/_sdk_check.yml
- .github/workflows/docs.yml
- .github/workflows/engine-and-cli-publish.yml
- .github/workflows/engine-and-cli.yml
- .github/workflows/helm-publish.yml
- .github/workflows/helm-test.yml
- .github/workflows/sdk-elixir-publish.yml
- .github/workflows/sdk-go-publish.yml
- .github/workflows/sdk-php-publish.yml
- .github/workflows/sdk-python-publish.yml
- .github/workflows/sdk-rust-publish.yml
- .github/workflows/sdk-typescript-publish.yml
As of 2024-07-26 our g2 runners are production ready. This PR migrates away of the old runners for all workflows.
With g2 runners, we are introducing a few new runner types that can be useful for different pipelines. Our setup here is:
- 4c NVME runners will continue to be used for almost all pipelines
- 16c Single Tenant and On-Demand runners will be used for big pipelines, primarily engine-and-cli pipelines.
- 32c and 8c dind runners for testdev runs.
We have a single-tenant spot instance runner available as well, but so far I haven't found a good use case for it.
> Migrate CI pipelines to g2 runners

- dev/main.go
Fixes the following flake:
- Github actions: https://github.com/dagger/dagger/actions/runs/10149286653/job/28063879193
- Dagger trace: https://dagger.cloud/dagger/traces/3081ce038ac6bdc1af29ca8b3925a226
```
Error: response from query: input: daggerDev.engine.lint resolve: call function "Lint": process "/runtime" did not complete successfully: exit code: 2
Stdout:
invoke: input: dirdiff.assertEqual resolve: call function "AssertEqual": process "/runtime" did not complete successfully: exit code: 2
Stdout:
invoke: input: container.import.withMountedTemp.withMountedTemp.withWorkdir.withMountedDirectory.withMountedDirectory.withWorkdir.withExec.sync resolve: process "diff -r a b" did not complete successfully: exit code: 1
Stdout:
Only in b/dev: dagger.gen.go
Only in b/dev/dirdiff: …
```
> ci: fix linting flake from no clone issue

- engine/buildkit/secret_scrub.go
- engine/buildkit/secret_scrub_test.go
Fixes https://github.com/dagger/dagger/issues/8032, and other assorted issues.
Imagine we have a secret like `foo\n` - we should also attempt to censor it in the output if we see `foo`. However, this is trickier than it initially seems - if we see `foo\n`, we should replace it with `***` - not `***\n`.
To do this, we modify the secret scrubber to be greedy, instead of eager. We now keep track of matches, and keep looking for more, instead of immediately replacing it.
Additionally, I've reworked the trie implementation to be more memory efficient (since having similar key prefixes in the above was starting to strain the implementation). On the way, I also discovered a nasty bug in which sometimes values could be silently dropped from the trie - I've fixed that and added a new test.
More …
> fix: secret scrubber should remove whitespace-trimmed secrets

- .github/workflows/engine-and-cli.yml
We want to mirror the setup we have for SDK checks + test all but with dev-engines. This means making the current `dind` runners be shared and adding a new dind single tenant on-demand runner for testdev.
> Use single tenant on-demand runners for testdev

- sdk/php/composer.json
- sdk/php/composer.lock
- sdk/php/src/Command/EntrypointCommand.php
- sdk/php/src/Service/Serialisation/AbstractScalarHandler.php
- sdk/php/src/Service/Serialisation/AbstractScalarSubscriber.php
- sdk/php/src/Service/Serialisation/IdableHandler.php
- sdk/php/src/Service/Serialisation/IdableSubscriber.php
- sdk/php/src/Service/Serialisation/Serialiser.php
- sdk/php/tests/Unit/Service/Serialisation/SerialiserTest.php
Add support for custom objects in the PHP SDK runtime.
Tested this manually with the following three classes in a module called Potato:
```php
#[DaggerObject]
class Potato
{
#[DaggerFunction('Get Chips')]
public function getChips(): Chips
{
return new Chips(
dag()->container()->from('alpine:latest'),
dag()->defaultPlatform(),
new Sauce('mayo'),
);
}
}
```
```php
#[DaggerObject]
class Chips
{
public function __construct(
private readonly Container $container,
private readonly Platform $platform,
private readonly Sauce $sauce,
) {
}
#[DaggerFunction('Serve the chips')]
public function serve(): string
{
return $this->container
->withExec(['echo', sprintf(
'Chips with a side of %s, covered in %s',
$this->platform->getValue(),
$this->sauce->type,
)])
->stdout();
}
}
```
```php
final class …
```
> feat: Support custom objects in PHP SDK runtime

- .changes/.next
- .github/actions/call/action.yml
- .github/workflows/engine-and-cli-publish.yml
- .goreleaser.common.yml
- RELEASING.md
- cmd/codegen/generator/functions.go
- cmd/dagger/engine.go
- core/integration/engine_test.go
- core/integration/module_test.go
- core/modulesource.go
- core/schema/module.go
- core/schema/util.go
- dev/cli.go
- dev/engine.go
- dev/internal/build/builder.go
- dev/mage/engine.go
- dev/main.go
- dev/test.go
- dev/version.go
- engine/client/client.go
- engine/consts.go
- engine/distconsts/consts.go
- engine/server/session.go
- engine/version.go
- engine/version_test.go
Fixes https://github.com/dagger/dagger/issues/7760
Instead of just using commit hashes and directory IDs, which produces nearly incomprehensible versions (which is more of a pain, now that `engineVersion` is actually important). This makes it a *bit* clearer when and where a non-tagged build came from by using changie to get the last release we built.
Frustratingly, it seems non-trivial to do version comparison on these, so we keep skipping these. In the future, we should work out on compromise. For an example of why this is hard: suppose that we add a MinVersion of v0.12.0 - the next pre-release will end up being something like "v0.11.10-dev-240709191414-1ccb8772510a". So this version will fail these checks.
We could add a little piece of code to note what the *next* release will be - …
> chore: tag all releases with semver

- .github/workflows/engine-and-cli-publish.yml
- dev/cli.go
These values are commonly known, so don't need to be secrets.
This will prevent them from being censored in the logs.
> ci: update release secrets to release vars

- .changes/unreleased/Fixed-20240731-061239.yaml
- core/integration/module_config_test.go
- core/modulesource.go
- engine/vcs/vcs.go
- engine/vcs/vcs_test.go
When working on private SSH support, I realized that our support for Azure refs is broken on monorepos.
**Why ?**
Azure's handling of `go-get=1` is not foolproof:
1. `repoRootForImportPath` does work well on refs leading to a repo, infering properly the vcs provider used
2. But,  `go-get=1` returns a 500 when a subpath is included
3. Azure ref's style is explicit with the vcs being used: git is mentioned for a git based repo
If we are ok with this explicitness, we should not try to infer the vcs based on the go-get for Azure and rely on regexes
> fix: extend multi git server support to Azure devOps

- cmd/codegen/generator/typescript/templates/src/method_solve.ts.gtpl
- core/integration/module_test.go
:cherries: Cherry-picked out of #7438, since that one is kinda stalled, not really sure what to do with it.
In the process of the above PR, I'd attempted to add a required enum arg, which the typescript codegen hadn't previously covered - so I added this case.
While this isn't used by any API at the moment, it's useful to cover it anyway, so when we inevitably do, we don't spend any time on hunting down why it's not working.
> sdk(typescript): handle required enum options
