dagger/dagger

.github/workflows/engine-and-cli-publish.yml

Fixes the failing publish job on main: https://github.com/dagger/dagger/actions/runs/10196735570/job/28208078629 (introduced by merging #7858)
We need to strip the newline at the end, otherwise we end up with the trailing `tee` on a line by itself (which isn't what we want).

ci: fix multiline function calls

---

dev/cli.go
dev/sdk.go

Properly unset the tag, so that we don't attempt to generate release notes for a nightly release: https://github.com/dagger/dagger/actions/runs/10198799780/job/28214455568#step:10:510
Follow-up to #8075

ci: fix cli publish for untagged releases (take 2)

---

docs/_README.md

Add Netlify publishing steps for doc deploys
Fixes https://linear.app/dagger/issue/DOCS-306/add-documentation-in-the-docs-guide-on-how-to-push-to-production

Docs: Add publishing steps

---

.github/actions/call/action.yml
.github/workflows/_sdk_check.yml
.github/workflows/docs.yml
.github/workflows/engine-and-cli-publish.yml
.github/workflows/engine-and-cli.yml
.github/workflows/helm-publish.yml
.github/workflows/helm-test.yml
.github/workflows/sdk-elixir-publish.yml
.github/workflows/sdk-go-publish.yml
.github/workflows/sdk-php-publish.yml
.github/workflows/sdk-python-publish.yml
.github/workflows/sdk-rust-publish.yml
.github/workflows/sdk-typescript-publish.yml
RELEASING.md
dev/dagger.json
dev/go.mod
docs/current_docs/partials/_install-cli.mdx
go.mod
sdk/rust/.changie.yaml

This is a bit more of a restructure than usual, taking into account the changes introduced in https://github.com/dagger/dagger/pull/7705.
The big parts are:
- No more `bump-engine` PR
- Steps that were performed there are moved forwards to the new "prep" step.
- Now there's no tricky wait for CI to pass/etc, we can shave off a huge amount of time here now.
- Go SDK release is sped up a lot
- I realized we don't need to wait for our tests to pass in this specific step - the reason for this is, now we ourselves consume the modularized go SDK, not the external one. So technically this wasn't adding any coverage.
- The tests would already have fun on `main` before releasing - we're okay to skip it here.
- Added a tooling section to aggregate all the tooling that should be installed prior to …

Improve releasing during v0.12.4

---

dev/sdk_python.go
sdk/python/dev/src/main/__init__.py

This is a workaroud until the following is fixed:
- https://github.com/dagger/dagger/pull/8106
Not a part of that PR because it's needed for:
- https://github.com/dagger/dagger/pull/7744

chore(ci): Adjust dev module incorrectly detecting optional argument

---

sdk/python/.changes/unreleased/Deprecated-20240806-105313.yaml
sdk/python/docs/module.rst
sdk/python/src/dagger/__init__.py
sdk/python/src/dagger/mod/__init__.py
sdk/python/src/dagger/mod/_arguments.py
sdk/python/src/dagger/mod/_converter.py
sdk/python/src/dagger/mod/_module.py
sdk/python/src/dagger/mod/_resolver.py
sdk/python/src/dagger/mod/_utils.py
sdk/python/tests/modules/test_utils.py

This was split from https://github.com/dagger/dagger/pull/7744 in order to make the changes clearer in that PR, which includes a deprecation, but also a few more type checking fixes.
`Arg` as been deprecated in favor of `Name`, in preparation for supporting more metadata to arguments. The initial idea was to add them to `Arg`, but [there's a reason](https://peps.python.org/pep-0727/) for wanting a separate `Doc` and it's strange to have one specific metadata split from the others in `Arg`.
Note however that the use of `Arg` has been removed from the documentation for a while now, and after https://github.com/dagger/dagger/pull/8014, the need for `Name` has been greatly reduced. Users that have `Arg` because of reserved keywords should remove the explicit name override.

python: Deprecate `Arg` in modules

---

dev/main.go

Python's dev module is no longer broken.

chore(dev): remove python modules from list of modules to source

---

.changes/unreleased/Fixed-20240807-103813.yaml
core/directory.go
core/integration/directory_test.go
core/schema/directory.go
engine/buildkit/ref.go

> [!NOTE]
> 
> This is an alternative to https://github.com/dagger/dagger/pull/8108 - thanks @khrisrichardson for doing most of the hard investigation, but I think it was worth doing the restructuring of glob entirely, it needed doing here anyways. I've added you as a co-author to this PR :tada:
Fixes https://github.com/dagger/dagger/issues/7169
Globs weren't correctly working - the root issue here was that `IncludePatterns` is interpreted as relative to the `Path` passed into `ReadDir`.
This is kinda not great, since we keep the same `IncludePatterns`, but continually adjust `Path` to go deeper.
To fix the issue, we entirely restructure globbing - now the entire filesystem is only mounted once (hopefully a performance improvement in its own right), and we apply a custom walking function, …

fix: ensure glob works with subdir recursive entries

---

RELEASING.md

Subtle reordering and addition of a needed `--force` make these instructions better for releasing dagger-for-github.

chore: improve dagger-for-github releasing

---

dev/docs.go
docs/static/api/reference/index.html

@helderco noticed that https://github.com/dagger/dagger/pull/7937 introduced an issue in https://github.com/dagger/dagger/pull/7948#discussion_r1682570312:
> Is this now always producing a diff on generate due to random ids? Might make sense to discard changes if so.
This makes sure we actually run the docs generate step! (which it doesn't look like we've been doing enough!)
To do this though we need to use a temporary fork of spectaql that has reproducible example snippets. See https://github.com/anvilco/spectaql/issues/976 for the upstream PR.

ci: add linting for generated api snippets

---

.changes/unreleased/Added-20240629-000342.yaml
cmd/dagger/call.go
cmd/dagger/flags.go
cmd/dagger/functions.go
cmd/dagger/main.go
cmd/dagger/module.go
core/integration/module_call_test.go
core/schema/coremod.go
docs/current_docs/reference/cli.mdx
sdk/go/querybuilder/querybuilder.go
sdk/go/querybuilder/querybuilder_test.go

Fixes https://github.com/dagger/dagger/issues/6947
Current implementation uses a top-level command for core functions:
- `dagger core <function>`  → execute a function from the core API
- `dagger call -m <module> <function>` → execute a function from a module
Can be run from anywhere as it doesn't require a module to load:
```console
❯ dagger core version
[dev-fdc07a5bfb46ca6a37ae379d767210d54f141c4f](version: v0.12.5-010101000000-dev-8e3b1f29b72b)
```
Allows experimentation in the CLI without the need for a module
```console
❯ dagger core container from --address=alpine file --path=/etc/os-release contents
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.20.2
PRETTY_NAME="Alpine Linux v3.20"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issue …
```

cli: allow calling core functions directly

---

.changes/unreleased/Fixed-20240808-180607.yaml
cmd/dagger/flags.go
core/enum.go
core/integration/module_call_test.go
core/typedef.go

Reported by user in [Discord](https://discord.com/channels/707636530424053791/1266410249565372498).
> something changed, and ive been out of loop for some time as i was not paying full attention, i was defining a go type, to simulate an enum in some ways, i.e type lang = string and then lang = Go, lang = "Csharp" etc etc, I was then using this custom type (which still is a string) as part of the dagger function API, since upgrading it no longer works and ive just rid of that concept and used pure strings instead. I'm more of a c# person, but im still interested to know if it was expected?
>
> ```go
> type Language string
> 
> const (
>     CSharp Language = "CSharp"
>     Go     Language = "Go"
>     Java   Language = "Java"
>     Python Language = "Python"
> )
> 
> ...
> 
> …
```

Fix enum list in CLI

---

sdk/php/src/ValueObject/Argument.php
sdk/php/src/ValueObject/DaggerFunction.php
sdk/php/tests/Unit/ValueObject/ArgumentTest.php
sdk/php/tests/Unit/ValueObject/DaggerFunctionTest.php

Clearer exception messages whilst developing PHP Modules. Specifically, exceptions for missing typehints.
If you create a DaggerFunction, with an argument `source`, missing a typehint:
```
[ERROR] Dagger\ValueObject\Type::fromReflection(): Argument #1 ($type) must be 
of type ReflectionType, null given, called in                          
/src/sdk/php/dev/sdk/src/ValueObject/Argument.php on line 34
```
If you create a DaggerFunction `format` without a return type:
```
[ERROR] Dagger\ValueObject\Type::fromReflection(): Argument #1 ($type) must be 
of type ReflectionType, null given, called in                          
/src/sdk/php/dev/sdk/src/ValueObject/DaggerFunction.php on line 56 
```
If you create a DaggerFunction, with an argument `source`, missing a typehint:
```
[ERROR] Argument …
```

Add exceptions for missing typehints in PHP Module

---

.changes/unreleased/Fixed-20240809-125822.yaml
core/integration/module_test.go
core/object.go

When returning an object from a module function that contains a nil field, we can get the following error:
```
Error: response from query: input: test.hello resolve: failed to collect IDs from parent fields: failed to collect IDs for field "<name>": expected *ModuleObject, got <nil>
```
cc @sipsma

Fix `failed to collect IDs from parent fields`

---

RELEASING.md

Add mention of the required documentation step for our GitHub Actions release. See https://github.com/dagger/dagger/pull/8131 for past example.

Docs: Add docs step to GitHub Actions Release

---

sdk/php/runtime/template/README.md
sdk/php/runtime/template/src/Example.php

The other SDKs are all consistent in their naming of their autogenerated example methods - PHP should be the same.

chore(php): update php module example to match others

---

.changes/unreleased/Added-20240813-161514.yaml
.dagger/config.go
.dagger/engine.go

So that the Engine image already ships with the matching CLI, all configured and ready to go.
- It addresses the primary issues raised in https://github.com/dagger/dagger/issues/6887
This change adds an extra `27MB` to the final container image:
- `466MB` before this change
- `493MB` after this change (`~6%` larger)
- Use a `dagger query` to test the healthiness of the Engine in the Helm chart
- What would make a good default query?
- Tie this to https://github.com/dagger/dagger/issues/7733
- **Maybe** publish a CLI image with git preinstalled **DISCUSS**
- Close the initial issue

feat: Bundle CLI in the Engine image (a.k.a. One True Artefact)

---

sdk/elixir/.changes/unreleased/Added-20240814-172542.yaml
sdk/elixir/lib/dagger/global.ex
sdk/elixir/lib/dagger/mod.ex
sdk/elixir/runtime/template.exs
sdk/elixir/test/dagger/global_test.exs

~NOTE: This requires #8094 to be merge before review this PR.~
Instead of setting `dag` to the struct of the object type, use GenServer
to store it during invoke the function. 
This changeset still passing support using dag instance via a struct but the code from codegen changes to use `dag()` function and ignore the struct.
~This is another breaking changes, since user don't need to declare a struct 
that containing dag instance and function parameters is reduce to only 1 parameter.~

feat(sdk/elixir): make dag instance be global

---

core/integration/module_typescript_test.go
sdk/typescript/runtime/main.go

Fixes an issue raised by @marcosnils when using dagger ts SDK inside a ts repo that has a package.json at its root.

fix: ts sdk, ignore context dir during setup

---

.dagger/test.go
core/integration/module_typescript_test.go

This test creates a single client and uses it for 4 tests in parallel. Each test runs `dagger develop` at some point, and we're seeing this part hang in the export step:
Giving each test its own seems to work around the issue (0/2 runs hang with the fix, 2/2 hang without).
It doesn't seem to be a regression related to the test or the feature being tested, and it's better for each test to open its own client anyway so we don't leave one hanging around until they run.
tl;dr: it appears we've found a repro for #6355 🎉 - so after merging this PR we can just revert locally to investigate it.
Here are some runs that demonstrate the hang:
* https://dagger.cloud/dagger/traces/03b9d7e773d03d5323334f5d3da2177b?span=35610e5c887dc49e
* https://dagger.cloud/dagger/traces/10f31bb9e437e889577e7b61939a3df …

workaround hanging `TestTypeScriptPackageManagerDetection` test

---

.changes/unreleased/Fixed-20240813-152129.yaml
core/integration/module_test.go
core/module.go

Reported by @sagikazarmark in [Discord](https://discord.com/channels/707636530424053791/1123687185837740053/1270438030284689539).
Enum doesn't work in constructors:
```
Error: make request: input: failed to get schema: failed to get schema for module "test": failed to install constructor: failed to create function: failed to find mod type for function "" arg "status" type
```
See failing tests. Affects all SDKs, the problem is in core (modfunc).

fix using enum in constructor

---

.changes/unreleased/Fixed-20240813-170412.yaml
core/enum.go
core/integration/module_test.go
core/module.go

This was broken from the beginning when user-defined enums were introduced in #7498. `ModTypeFor` was refactored, and essentially always returned early before the handling of `typeDef.Optional`. This was incorrect, and meant that we ended up with `DynamicOptional`s during enum conversion - see https://github.com/dagger/dagger/pull/7498/files#diff-5eb7740241ddbf3efbef98d43f59b2081a4b6f7bfd00a3daba69d36f107d53bbL262-R287.
To resolve this, we can only return early when we've loaded the mod type directly from the deps - when we've executed the load ourselves, we need to complete the rest of the function.

fix: allow optional enum arguments in user functions

---

.changes/unreleased/Added-20240731-134929.yaml
core/integration/module_test.go
core/schema/sdk.go
sdk/php/runtime/template/src/Example.php

This allows users to use `elixir` to use the elixir SDK, and `php` to use the php SDK, without needing the full `github.com/dagger/dagger/sdk/<sdk>/runtime@<version>` URL which is very unieldy.
~~:warning: requires https://github.com/dagger/dagger/pull/7858 so that we can access `engine.Tag` which is the version of the release, so the v0.12.4 release will correctly point this to `github.com/dagger/dagger/sdk/<sdk>/runtime@v0.12.4`.~~

feat: add elixir/php sdk aliases

---

sdk/typescript/runtime/main.go

This is the node_modules equivalent for pnpm - we should never export it, just in our tests these can end up at 100MB, which causes our exports to sometimes hang.

chore(ts): don't export pnpm store

---

.dagger/build/builder.go
.dagger/engine.go
.dagger/sdk_all.go
cmd/codegen/generator/go/templates/module_interfaces.go
cmd/codegen/generator/go/templates/module_objects.go
cmd/codegen/generator/go/templates/module_types.go
cmd/codegen/generator/go/templates/modules.go
cmd/dagger/cloud.go
core/c2h.go
core/interface.go
core/moddeps.go
core/schema/module.go
core/schema/modulesource.go
core/services.go
core/services_test.go
dagql/builtins.go
dagql/idtui/frontend_plain.go
dagql/objects.go
dagql/server.go
engine/buildkit/cacerts/cacerts.go
engine/buildkit/client.go
engine/buildkit/executor_spec.go
engine/cache/mountsync.go
engine/server/session.go
engine/server/telemetry.go
modules/go/main.go
sdk/go/internal/engineconn/session.go
testctx/testctx.go

We've been using go 1.22 for a while now: #6637. However, this introduced some really interesting features, and we've not really converted any code to use it.
This PR starts using the two main changes in the language from https://go.dev/doc/go1.22:
- Use `range <int>` syntax wherever possible
- Avoid explicit loop capture, this is now the default
Hopefully, after #8150 lands, we can also start using the new func iterators :tada:

chore: use features introduced recently in go 1.22

---

cmd/codegen/generator/go/templates/modules.go

This error seems to appear as a weird little flake (see https://github.com/dagger/dagger/issues/8031#issuecomment-2260352601) - and never seems to appear legitimately.
Because of this, we should crank the verbosity up to try and understand what the go parser is *actually* seeing when this happens, which might give us a hint as to what is really going on.

chore: increase verbosity of codegen error

---

core/integration/module_test.go

Part of https://github.com/dagger/dagger/issues/8184, and split out of https://github.com/dagger/dagger/pull/8168, since my general approach there turns out to not be possible :cry: 
Somehow, we see weird timeouts because calls to the dagger cli aren't properly exiting out: https://dagger.cloud/dagger/traces/da4d9c2d21aef7f3eb8ff0856946c0c1#7e1bbffd12a2fbe1
This is it's own problem, but we shouldn't hang the test while waiting for this, we should actually exit and fail after a timeout.

tests: try killing subprocesses harder if they misbehave

---

.dagger/test.go
.github/actions/call/action.yml
.github/workflows/engine-and-cli.yml

> [!NOTE]
> While this PR started by splitting our Engine & CLI tests in `TestModule` and everything else, it has since been changed. We are keeping the existing test suite **as is**, while adding two new test suites:
> 1. `test-module`
> 2. `test-everything-else`
>
> This is meant to inform the next steps for:
> - https://github.com/dagger/dagger/issues/8184
---
This PR replaces the `test custom` subcommand with `test specific`, e.g.:
```console
dagger call --source=.:default test specific --skip=TestModule
```
In the example above, we run all tests **except** the `TestModule` ones. To **only** run `TestModule` tests, the command is:
```console
dagger call --source=.:default test specific --run=TestModule
```
Also, `test important` is now:
```console
dagger call --source=.:default test …
```

ci: Allow skipping specific tests - e.g. TestModule - or only run specific ones

---

.changie.yaml
helm/dagger/.changie.yaml
sdk/elixir/.changie.yaml
sdk/go/.changie.yaml
sdk/php/.changie.yaml
sdk/python/.changie.yaml
sdk/rust/.changie.yaml
sdk/typescript/.changie.yaml

It's pretty easily to accidentally add a full-stop at the end of a changelog line (e.g. https://github.com/dagger/dagger/pull/8163/files#diff-47044aed7a447d259a5a7a88046f34e4cc36740e18e64da88b4fa178a7349360L3).
We can trim this out during changelog generation pretty easily.

chore: trim full stop from end of first line of changelog

---

.dagger/sdk_elixir.go
.dagger/sdk_go.go
.dagger/sdk_java.go
.dagger/sdk_php.go
.dagger/sdk_python.go
.dagger/sdk_rust.go
.dagger/sdk_typescript.go

We don't need separate services for each sdk test/generate/lint step - they can just all share together :heart:

chore(ci): share dagger sdk services

---

engine/telemetry/labels.go

Fixes #7918.
This just moves the warning down to a debug log - this can happen legitimately if there is a git directory (initialized with `git init`), but no commits have been created.
We don't need to warn in this case, we can just log a debug error (since it might *still* be useful for debugging).

chore: remove noisy "failed to get repo HEAD" error

---

.dagger/cli.go
.github/actions/call/action.yml
RELEASING.md
docs/current_docs/faq.mdx
docs/current_docs/integrations/snippets/Jenkinsfile
docs/current_docs/integrations/snippets/azure-pipelines.yml
docs/current_docs/integrations/snippets/buildspec.yml
docs/current_docs/integrations/snippets/circle.yml
docs/current_docs/integrations/snippets/gitlab-docker.yml
docs/current_docs/integrations/snippets/gitlab-kubernetes.yml
docs/current_docs/integrations/snippets/tekton-dagger-task.yaml
docs/current_docs/partials/_install-cli.mdx

The install example has been broken for some time! `sudo` doesn't forward environment variables by default for security purposes, and requires the `-E` flag to do this correctly.

docs: fix sudo sh install example

---

core/integration/module_typescript_test.go

As discussed with @gerhard and it order to improve current CI, I'm making an experimentation by moving the TypeScript tests to its own suite so we can run it independently from other's suites.
The long term idea is to move group of tests into their suites so they can be run into different engine and hopefully remove flakes.
Local CI run: https://dagger.cloud/Quartz/traces/a2c3a4a24346f31efac7dc52f23b6137
I'll try to paralize some tests and see if it can also make it faster.
@gerhard I let you create a GA job to run this suite 🚀 
Local CI took 7minutes to exec tests (https://dagger.cloud/Quartz/traces/a2c3a4a24346f31efac7dc52f23b6137#7c9a8264d0620b45) (4 min setup on my local machine)

tests: move TypeScript test to its own suite

---

.changes/unreleased/Added-20240819-133821.yaml
cmd/dagger/engine.go
cmd/dagger/main.go
core/integration/module_terminal_test.go
docs/current_docs/manuals/developer/debugging.mdx
docs/current_docs/reference/cli.mdx
engine/buildkit/client.go
engine/buildkit/ref.go
engine/client/client.go
engine/opts.go
engine/server/session.go
go.mod

Adds the ability to override the default command (`/bin/sh`) when entering in interactive mode when something fails.
Fixes #7974
Note: I added shlex on the command so we can support fancy stuff like: `dagger call --interactive --interactive-command='sh -c "apk update && apk add bash && bash"'` (for example to setup the debug container with an external script).
Remaining:

feat: implements --interactive-command for overriding the default command used in interactive mode

---

.github/dependabot.yml

Like other SDKs. It'll update every week with `area/sdk/elixir` label.

Add dependabot configuration to update Elixir packages

---

core/integration/module_config_test.go
core/integration/module_test.go
core/integration/ssh_helper.go

Fixes https://github.com/dagger/dagger/issues/8204 and reintroduces #8191
This PR addresses a data race where goroutines were potentially accessing testing.T after test completion. The solution implements a controlled shutdown mechanism using context cancellation and a WaitGroup.
Key changes:
- Introduce context for cancellation signaling
- Use sync.WaitGroup to track goroutines
- Implement graceful shutdown in cleanup function
This resolves the race condition by:
1. Ensuring all goroutines complete before test finalization
2. Providing immediate shutdown signaling
3. Guaranteeing proper resource release order
The result is a thread-safe setup process that aligns with the test lifecycle, preventing any out-of-bounds operations.

chore(test): fix race on setupPrivateSSHKey

---

core/integration/module_test.go

Tiny thing I noticed while working on flakes, seems worth a quick fix.
I saw a test flake where these tests failed due to a 500 error from example.com (like the actual real website) when the go tooling was checking for imports from it:
```
reading https://example.com/test/internal/querybuilder?go-get=1: 500 Internal Server Error
```
https://dagger.cloud/dagger/traces/ac50bb3aba9c820618d222c1f8717528?span=95c8ed5aad3a2915#95c8ed5aad3a2915:L9
There's no need for us to be hitting example.com, so may as well remove this.

tests: don't use example.com as go mod name

---

go.mod
go.sum

Diff: https://github.com/moby/buildkit/compare/ffadc9ff1531c8573e8522b03611833811f4abdf...49f3d8f8294d40a3c37a1e2ea3053be7c88f47cb
This diff notably includes performance improvements from (either of these solves the root issue for us):
- https://github.com/moby/buildkit/commit/3c87ba1bd502986f627115c6756c257b4a0a66e9
- https://github.com/moby/buildkit/commit/157efce41a3c359f19b595699f5184c7986ac6ac
Previously a buildkit regression that I introduced in https://github.com/moby/buildkit/commit/ab17c1dd93abe1ece92d04b31cd4c0bc6711cebe caused all exec pipeline steps that included a secret mount to take much longer than they should due to unnecessary calculation of a content-hash over the root filesystem.
This should have a performance benefit for us, but not sure what it will immediately be.

chore: bump buildkit to master@49f3d8f8294d

---

cmd/codegen/generator/go/generator.go
cmd/codegen/generator/go/templates/modules.go
cmd/dagger/engine.go
cmd/engine/main.go
core/integration/module_test.go
core/integration/suite_test.go
sdk/go/go.mod
sdk/go/telemetry/init.go

* Pin `sdk/go` + module's `go.opentelemetry.io/otel/sdk/log` dependency to v0.3.0 (not a bump) to avoid `OnEmit` breaking API change (`log.Record` -> `*log.Record`).
* Alternatively we could bump the version but that's more work and doesn't fix the root problem - the logging SDK is pre-1.0, so we can expect turbulence like this. Despite the version in `go.mod` it seems that it's too easy to stray ahead to v0.5.0 which breaks everything. Pinning with a `replace` rule seems to be the solution until they ship v1.0.
* Undoes the `telemetry.Close` breaking change from #7996 
* Not actually necessary, so not worth the breakage.
* Fixes https://github.com/dagger/dagger/issues/8206

fix OTel `sdk/log` and `telemetry.Close` breaking changes

---

.github/workflows/benchmark.yml
.github/workflows/trace-workflows.yml

Using a freshly built dagger engine, for each of the Go, Python and Typescript SDK, benchmark the following operations:
- `dagger init`
- `dagger functions`
- `dagger functions` (**cached**)
- `dagger functions` (after modifying the source code)

Benchmark SDKs

---

cmd/codegen/generator/go/templates/modules.go
cmd/codegen/generator/go/templates/modules_test.go
core/integration/module_test.go
core/integration/testdata/modules/go/minimal/main.go

Our comment parsing code was previously very inflexible, and didn't handle carriage returns in the comment. I *originally* thought I fixed this in https://github.com/dagger/dagger/pull/7121, but I guess not :cry: 
This is because of this helpful little note in go's comment ast struct declaration:
// The Text field contains the comment text without carriage returns (\r) that
// may have been present in the source. Because a comment's end position is
// computed using len(Text), the position reported by [Comment.End] does not match the
// true source end position for comments containing carriage returns.
So calling `.End()` on a comment essentially returns absolutely nonsense when there are carriage returns - there is no good way of recovering these.
Instead, we switch to another approach …

fix: handle comment parsing with windows line endings

---

engine/client/drivers/docker.go

@sipsma @helderco Unsure how to test this since using the dev engine bypasses this code
Context: Over 1 second is lost on every dagger command (at least on macOS with d4m). Trying to fo figure out what's up. Example: https://dagger.cloud/dagger/traces/6642af8fb7e4308be318136ff67c83b5?span=e5599dec41cad509
Most of the time is spent in unaccounted parts of `starting engine` (there's only ~200ms out of ~900ms that are "spanned").

initialize: trace docker ps command

---

core/integration/module_test.go
core/modfunc.go
core/modulesource.go
core/schema/modulesource.go
engine/distconsts/go.mod
modules/go/go.mod
modules/golangci/lint-config.yml
modules/graphql/go.mod
modules/markdown/go.mod
modules/wolfi/go.mod

Fixes these issues on `main`: https://github.com/dagger/dagger/actions/runs/10596511181/job/29364633106, which was introduced in #8151.
Some of these lints had stopped working, since the paths had gotten mixed up - this was because we were taking loop references (which is safe in go 1.22 - but requires that all the modules actually *use* go 1.22 in their go.mods).
This fixes that issue by updating go.mods, disables the loop capture checker (since this isn't required anymore in go 1.22), and also fixes the linting issues that we hadn't been catching anymore!

chore: fix linting

---

cmd/codegen/generator/generator.go
cmd/codegen/generator/go/generator.go
cmd/codegen/generator/go/templates/modules.go
cmd/codegen/generator/go/templates/src/_dagger.gen.go/defs.go.tmpl
cmd/codegen/generator/go/templates/src/_dagger.gen.go/module.go.tmpl

Follow up to https://github.com/dagger/dagger/pull/8181 (as part of the investigation along https://github.com/dagger/dagger/issues/8207)
And some other weird fixes in the area that probably needed doing.

chore: increase verbosity of codegen error even more

---

sdk/elixir/lib/dagger/core/client.ex
sdk/elixir/lib/dagger/core/error.ex
sdk/elixir/lib/dagger/core/graphql/response.ex
sdk/elixir/lib/dagger/core/graphql_client.ex
sdk/elixir/lib/dagger/mod.ex
sdk/elixir/test/dagger/client_test.exs

In this patch, the Elixir SDK look up an extensions from GraphQL error and converting it to `ExecError` and then translate an error into readable message  like Go and TypeScript does. 
Consider this function:
```elixir
defn sample() :: Dagger.Container.t() do
dag()
|> Dagger.Client.container()
|> Dagger.Container.from("alpine:latest")
|> Dagger.Container.with_exec(~w"foobar")
end
```
Before this patch, the SDK returns an error that come from inspecting struct, which's quite hard to read:
But after this patch, it's returns an error like Go or TypeScript:
Closes #8187

feat(sdk/elixir): make error message be more readable

---

cmd/engine/main.go
core/c2h.go
core/service.go
core/services.go
core/socket.go
dagql/idtui/frontend_pretty.go
engine/buildkit/client.go
engine/buildkit/containerimage.go
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
engine/buildkit/filesync.go
engine/buildkit/linux_namespace.go
engine/cache/manager.go
engine/server/session.go
engine/session/terminal.go
engine/telemetry/heartbeat.go
sdk/go/internal/engineconn/session.go

There's a chance this could help us diagnose [ephemeral context canceled flakes](https://github.com/dagger/dagger/issues/7699). 
I have a[ similar change upstream in buildkit](https://github.com/moby/buildkit/pull/5278) that I think is much more likely to be useful, but this is a best practice anyways for providing more context to errors than "canceled" so may as well make this change in our code too.

chore: use ContextCause everywhere

---

core/integration/testdata/modules/python/extended/src/main/__init__.py
sdk/python/runtime/main.go

Attempts to fix https://github.com/dagger/dagger/issues/7662, follow-up to https://github.com/dagger/dagger/pull/8051.
I *think* https://github.com/dagger/dagger/pull/8051 was the right approach - however, the tests weren't the issue. The paths in the tests aren't actually part of the uv cache key, so the underlying issue remains.
The real fix for this needs to be in the python sdk runtime, where we can correctly set these paths - based on the module id (or some other "unique enough" id, that can guarantee that we're not going to get weird horrible conflicts).
cc @sipsma @helderco

fix(python): use unique module paths to avoid uv cache conflict

---

cmd/codegen/generator/go/templates/modules.go
cmd/codegen/generator/go/templates/src/_dagger.gen.go/defs.go.tmpl
cmd/codegen/generator/go/templates/src/_dagger.gen.go/module.go.tmpl
sdk/go/dagger.gen.go

This gets rid of the multiple levels of type aliasing used to be just one level.
This is a very mild simplification that worst case seems harmless, but the motivation right now is a shot in the dark attempt at seeing if it avoids [some of the flakes](https://github.com/dagger/dagger/issues/8207) we have been getting in the Go SDK with this object.
* Obviously if this *does* indeed get rid of the flakes then it's not great in that we've probably just temporarily avoided a bug, but at this point that seems worth it.
I have been running with this change in my deflaking PR for a while now and haven't seen the flake since, so figured it didn't hurt to spin out at this point.
* 90% of time I've said something like this in the past the flake suddenly reappears, so 🤞

sdk(go): simplify DaggerObject aliasing slightly

---

.changes/unreleased/Fixed-20240902-160036.yaml
core/schema/sdk.go

while working on a different [issue](https://github.com/dagger/dagger/issues/6655), I found what seems like we are not using `sdkVersion` when loading aliased sdk.

fix: use sdkVersion when loading aliased sdk

---

.changes/unreleased/Fixed-20240902-130323.yaml
.changes/unreleased/Fixed-20240902-130441.yaml
cmd/dagger/module.go
core/integration/git_test.go
core/schema/git.go
docs/current_docs/reference/cli.mdx

Fixes https://github.com/dagger/dagger/issues/8291, regression from https://github.com/dagger/dagger/pull/7708.
Previously, extracting the git tags from a URL skipped a level of url pre-processing that was in buildkit (essentially, one that allowed no protocols in URLs). We need to add this level of pre-processing manually.
Without this, parsing module refs of the form `github.com/<org>/<repo>@<version>` would fail with:
! failed to resolve git tags: select: git command failed: exit status 128
Error: failed to get module ref kind: input: moduleSource resolve: failed to resolve git tags: select: git command failed: exit status 128
stdout:
stderr: fatal: 'github.com/<org>/<repo>' does not appear to be a git repository
fatal: Could not read from remote repository.
This is because it's not a …

fix: make Git.tags url parsing consistent with Git.tree

---

core/integration/module_test.go
core/schema/modulesource.go
core/schema/sdk.go
core/schema/sdk_test.go

fixes #6655 
As discussed on the ticket, we are now using a static list of supported sdk to come up with the error msg (to keep it in sync with the actual builtin sdk's) and doing it on server side.
```
~/go/src/github.com/dagger/testme (cloud-docker/ap-south-1) 
$ ../dagger/hack/with-dev dagger init --name testme --sdk foobar
Full trace at https://dagger.cloud/rajatjindal/traces/ffb2887ad89ec3fb95c8d4c98f12ea6f
✔ connect 0.2s
✔ cache request: mkfile /schema.json 0.0s
✔ mkfile /schema.json 0.0s
✔ cache request: blob://sha256:2ba0e05274fd9ab3542a01e42193dedd3e2361419941dd4ac4f79022be14e000 0.0s
✔ blob://sha256:2ba0e05274fd9ab3542a01e42193dedd3e2361419941dd4ac4f79022be14e000 0.0s
✔ moduleSource(refString: "."): ModuleSource! 0.0s
✔ ModuleSource.kind: ModuleSourceKind! 0.0s
✔ …
```

chore: return more specific error when provided sdk is invalid

---

docs/current_docs/quickstart/daggerize.mdx

This change is based on feedback received in the docs survey

docs: Add module name warning in quickstart

---

sdk/elixir/dagger_codegen/lib/dagger/codegen/introspection/types/type.ex

Fix `Type.from_map/1` crash when the `description` may not present in the schema json file when that schema generated from module.

fix(sdk/elixir): fix from_map crash because of description can be optional

---

core/schema/module.go
core/schema/sdk.go
core/schema/sdk_test.go

I realized that the sdkVersion defaults to `engine.Tag` and in a released version it would be a semver release version. The unit tests didn't consider that in the original implementation.
The unit tests have now been modified to set an `engine.Tag` to simulate real usage, and validation logic has been fixed to account for that correctly. I have also added several additional tests to cover these scenarios.
This PR also modifies the function `parseSDKName` to include basic validation, which was done earlier in the `builtinSDK` function. Therefore, it also renames the function to `parseAndValidateBuiltinSDKName`.

fix: fix the parseBuiltinSDK function when engine.Tag is not empty value

---

.changes/unreleased/Fixed-20240904-191701.yaml
core/schema/coremod.go

Fixes https://github.com/dagger/dagger/issues/8326

fix void types from core incorrectly being seen as named scalar types

---

sdk/typescript/.changes/unreleased/Changed-20240827-020027.yaml
sdk/typescript/runtime/main.go

Reorder steps to not list all entries when configuring modules. Move install dependencies step & corepack init before mounting sources.
Add template after initializing dependencies.
It seems that it really improve the cache hit, putting the TS SDK near Go speed when cache hits.
I updated the sources between the 2 runs and we can see that initialize kept being quick! We need more tests but it looks really promising.

feat: optimize TS SDK runtime

---

.dagger/main.go

When loading the module from a git remote, .git is not available. This caused our default 'dagger call -m github.com/dagger/dagger` to fail for every function call.

chore: fix .git introspection in remote module

---

.dagger/config.go

Dagger v0.12.5 added a ulimit call in the engine entrypoint, breaking podman running in rootless.
This allows the call to fail with a warning (the ulimit can be done manually by the user if needed).
It's tricky to test because the latest version of dagger (v0.12.7) does not run on podman rootless (both root mode VMs do not share any data), so you cannot build the engine in rootless to test this change. I had to build the engine in rootful, export the `dagger-engine.dev` container, export it from a rootless VM and check the logs that the ulimit gracefully failed.
Fixes #8210

fix: allow engine entrypoint to fail to set ulimit fd limit

---

.changes/unreleased/Changed-20240909-113139.yaml
engine/client/buildkit.go

* The MinConnectTimeout was set to 1s which is good for a fast recovering from the situation that the engine is not ready to accept connections, while at the same time, it's too aggressive for a remote engine, eg. Dagger Engine on a Kubernetes [1], the engine may not complete the connect phase within the deadline and always failed in the connection checking loop [2].
Until the buildkit implements the better way of client creation [3], increase the timeout with a less aggressive 3s could mitigate this issue.
[1] https://docs.dagger.io/integrations/kubernetes
[2] https://github.com/dagger/dagger/blob/main/engine/client/buildkit.go#L45
[3] https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md

client: set less aggressive minimum connect timeout for buildkit

---

core/integration/module_test.go
core/modulesource.go

Remove `Include` usage in context directory to only use excludes negation since it seems it works.
Add a couple of tests to verify that behaviour.
Fixes #8287

fix: context directory ignore discrepency

---

.dagger/helm.go
helm/dagger/.changes/unreleased/Breaking-20240905-175439.yaml
helm/dagger/Chart.yaml
helm/dagger/templates/_helpers.tpl
helm/dagger/templates/engine-daemonset.yaml
helm/dagger/values.yaml
modules/golangci/lint.go

Now that the chart version moves in lock-step with the app version, we want to remove the app version so that we minimize the change for incompatibilities, as was the case in https://github.com/dagger/dagger/issues/8301.
The options are:
A. You want a custom app image. You need to ensure that the chart is compatible with this image.
B. You use the default image. We are responsible for ensuring compatibility with the chart.
The third option is to use this YAML as inspiration, and manage your own raw manifests, which give you full control, and also responsibility.
Fixes https://github.com/dagger/dagger/issues/8301

💥 Breaking(helm): Remove appVersion - this is now the chart version

---

core/integration/testdata/nested-c2c/main.go
engine/distconsts/consts.go
go.mod
modules/go/main.go

Addresses a high severity stdlib vulnerability that could cause panics in deeply nested gob decoding. Trivy flagged this in our engine image scan.
We do not seem to be relying on it, but this triggers a Trivy scan

chore: bump Go to 1.23.1 to fix CVE-2024-34156

---

sdk/elixir/.changes/unreleased/Added-20240907-173230.yaml
sdk/elixir/lib/dagger/mod.ex
sdk/elixir/lib/dagger/mod/function.ex
sdk/elixir/lib/dagger/mod/object.ex
sdk/elixir/test/dagger/client_test.exs
sdk/elixir/test/dagger/mod/module_test.exs
sdk/elixir/test/dagger/mod/object_test.exs
sdk/elixir/test/dagger/mod_test.exs
sdk/elixir/test/support/object_mod.ex

This changeset add support for optional argument when user defined type of the argument as `AType | nil`.  Let see the example:
```elixir
defmodule Potato do
@moduledoc """
Potato module
"""
use Dagger.Mod.Object, name: "Potato"
defn hello(name: String.t() | nil) :: String.t() do
if is_nil(name) do
"Please give me a name. 😊"
else
"Hello, #{name}"
end
end
end
```
When calling `hello` function without argument:
```
wingyplus@WINGYMOMO ~/s/g/d/d/s/e/potato (optional-arg)> dagger call hello
Full trace at https://dagger.cloud/dagger-elixir-sdk/traces/25e8d8da160122f5d108996adad14d01
✔ connect 1.8s
✔ initialize 15.7s
✔ prepare 0.0s
✔ potato: Potato! 0.0s
✔ Potato.hello: String! 7.3s …
```

feat(sdk/elixir): add support for optional argument

---

.dagger/consts/versions.go
go.mod
go.sum

Updates to https://github.com/opencontainers/runc/releases/tag/v1.1.14, which includes a fix for https://github.com/opencontainers/runc/security/advisories/GHSA-jfvp-7x6p-h2pv.
Low severity, but no reason to not take this.

chore: update runc to v1.1.14

---

.changes/unreleased/Added-20240905-154130.yaml
core/directory.go
core/integration/directory_test.go
core/interface.go
core/modulesource.go
core/schema/directory.go
core/schema/module.go
core/schema/modulesource.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/directory.ex
sdk/elixir/lib/dagger/gen/module_source.ex
sdk/go/dagger.gen.go
sdk/php/generated/Directory.php
sdk/php/generated/ModuleSource.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Builds on #8114, adding `Digest` to `Directory` and `ModuleSource`.
The original need for these is internal, see the discussion in https://github.com/dagger/dagger/pull/8245#discussion_r1733172781. However, there's still a use for these in the public API as well, and it's just generally good consistency :tada:
I guess this actually validates our idea of keeping the digest with the metadata as the default - since it doesn't really make sense to compute a `Directory.digest` *without* metadata, so we can just leave off that parameter.

feat: add `Directory.digest` and `ModuleSource.digest`

---

.changes/unreleased/Fixed-20240911-102046.yaml
dagql/idtui/frontend_plain.go
dagql/idtui/vterm_lite.go
dagql/idtui/vterm_lite_test.go

Fixes https://github.com/dagger/dagger/issues/8259
This was incorrectly rendering some carriage return output (outside of certain test cases). To handle this, we need to track a proper cursor, which is a bit annoying, but unavoidable.
The approach in https://github.com/dagger/dagger/issues/7653 wasn't *quite* right (since `\r\n` would essentially wipe the entire contents of the line). But also, what silly unix tool would produce windows-style newlines like that? (apt, that's who)

fix: correctly handle carriage returns for plain progress

---

.changes/unreleased/Fixed-20240911-101724.yaml
core/enum.go
core/integration/module_test.go
core/json.go
core/object.go
core/platform.go
core/typedef.go
dagql/builtins.go
dagql/types.go

Previously, if a field access was made immediately after the default constructor was called, then the access would fail (because the field had not been set).
So, in this case, we try and convert a nil value, to get the default value for this.
---
Genuinely not quite sure how we never managed to hit this before, it's very easy - I just found it while playing around with some tests in #8149.

fix: allow field access with default constructor

---

.changes/unreleased/Fixed-20240911-105222.yaml
core/integration/module_test.go
core/modfunc.go
engine/server/client_resources.go
engine/server/session.go

Thanks @sagikazarmark for the original bug report :tada: (I *think* this is the same issue? it does have a slightly different error message).
```
invoke: input: dep.secretMount.mount resolve: failed to add client resources from ID: failed to add secret: secret xxh3:bc7dcced26cc08c7 not found in other store
```
The issue appears to be that the `SecretMount.Secret` is marked as `// +private` - if this is removed, the test appears to pass with no issues. I'm *guessing* that what's happening is that because the field is marked as private, it's not appearing as a field in the typedef.
Then, when we iterate to `CollectCoreIDs`, we don't manage to see this field:
https://github.com/dagger/dagger/blob/3c52de5cd5daf202f57d4879f914dac3d2bc3ccf/core/object.go#L103
I think that makes rough sense - …

fix: various cross-module secret sharing issues

---

.changes/unreleased/Added-20240909-192538.yaml
cmd/dagger/main.go
dagql/dagui/opts.go
dagql/idtui/frontend_pretty.go
docs/current_docs/reference/cli.mdx

Allows you to poke around the DAG after the command completes, rather than closing. Just a quick feature that helped me out while working on the TUI itself.

TUI: add `--no-exit`/`-E` to keep TUI open on completion

---

helm/dagger/.changes/unreleased/Breaking-20240911-114157.yaml
helm/dagger/values.yaml

This may result in a surprising behaviour, as captured in:
- https://github.com/dagger/dagger/pull/7395
You can still set this if needed, we are just removing it as the default option.
---
Follow-up to:
- https://github.com/dagger/dagger/pull/8348#discussion_r1750138175
---
> [!NOTE]
> The more I think about this, it's not **technically** a breaking change. We change the default behaviour of the Engine provisioned with the Helm chart. We are emphasising the importance of this change, but it's not breaking. OK to leave as is, just clarifying for anyone that might stumble across this PR and wonder what exactly is breaking.

💥 Breaking(helm): Remove default oci-max-parallelism num-cpu

---

.dagger/cli.go

While this is hacky, it's necessary as it Fixes the Go v1.23.1 requirement when publishing the CLI: https://dagger.cloud/dagger/traces/5b2e5658cf5f372fc6efb57b385f608a#309ba7d23cd65cbd:L84
As soon as https://github.com/goreleaser/goreleaser/pull/5126 ships in GoReleaser `v2.3.0`, we can upgrade to that and remove this change.
---
Follow-up to:
- https://github.com/dagger/dagger/pull/8371

chore: Upgrade Go to v1.23.1 in GoReleaser Pro

---

cmd/codegen/generator/go/templates/functions.go
cmd/codegen/generator/go/templates/src/_types/object.go.tmpl
cmd/codegen/generator/typescript/templates/functions.go
cmd/codegen/introspection/introspection.go
core/integration/legacy_test.go
core/integration/module_test.go
dagql/introspection/query.go
sdk/go/.changes/unreleased/Breaking-20240805-181259.yaml

- Part of https://github.com/dagger/dagger/issues/6749
- Fixes https://github.com/dagger/dagger/issues/6964
> [!warning]
> This is a breaking change for **Go SDK** users when depending on a module that has a non-null function argument with a default value. With this change, the argument will change from required to optional in the client bindings (`dagger.gen.go`).
If a Go Module depends on another Module that has a non-null Function argument with a default value, the generated client bindings would consider that argument required because it didn’t consider having a default, just that it was nullable or not:
```go
// ❌ Before v0.13.0 it's a required argument
dag.Greeter("Dagger").Greeting(ctx)
// ✅ After v0.13.0 it's an optional argument
dag.Greeter().Greeting(ctx) …
```

fix(sdk/go): consider default values when grouping optional arguments in codegen

---

.github/workflows/engine-and-cli-publish.yml

This needs to match the bun version that we use in the SDK code.
Fixes the failing `main` provision tests: https://discord.com/channels/707636530424053791/1280818249633890365/1283423301762551916
This likely broke after merging #8237.

ci: bump bun version to v1.1.x

---

.github/workflows/engine-and-cli-publish.yml

`1.0.x` works. `1.1.x` doesn't. https://github.com/dagger/dagger/actions/runs/10813822787/job/29999504355
:cry:

ci: bump bun version to v1.1.26

---

.github/workflows/engine-and-cli-split.yml
.github/workflows/engine-and-cli.yml

So that we can compare the two different workflows side-by-side. This is something that we have learned ~2 weeks after the last test suite split:
- https://github.com/dagger/dagger/pull/8212
We know that the split suites are faster & more reliable, but without this change, we cannot compare the two workflows side-by-side. All that we know is that the Engine & CLI workflow is failing more often (flakes are now 2x as likely to happen). This change will show us how all the tests, but split differently, compare.
This is part of a wider effort captured in:
- https://github.com/dagger/dagger/issues/8184

ci: Move the Engine & CLI split test suites to a separate workflow

---

.dagger/main.go

right now this is uploading everything which takes quite a while

.dagger: fix gitDir glob pattern to ignore all but `.git`

---

.github/workflows/trace-workflows.yml

We added a bunch of new workflows that we have not been tracing. This fixes it. Follow-up to:
- https://github.com/dagger/dagger/pull/8407
- https://github.com/dagger/dagger/pull/8241

ci: Trace missing workflows

---

.github/workflows/engine-and-cli.yml

During https://github.com/dagger/dagger/pull/8212, `testdev` was refactored and I missed these important test suites. This puts them back. We should expect it to get slower and more flaky, but at least the coverage will be the same as before.
We were still running the same tests in the split `testdev-module-runtimes`, so were not really missing on anything test
coverage-wise, just the comparison between the original `testdev` and the split one was less accurate.

ci: Restore testdev to the same coverage as it had before #8212

---

.changes/unreleased/Added-20240913-122008.yaml
core/modulesource.go

Fixe based https://github.com/dagger/dagger/pull/8369 and @helderco feedbacks
**Without this fix**
```
dagger call -m github.com/wingyplus/dagger/sdk/php/runtime@cd3a3e724aa5a2ce259fe6b217f0efe5abaaabcb source-dir
_type: Directory
digest: sha256:4efcbbc3978405e30f078b41ff5acb6a0d1f6084906a42d3cf32d4377190a414
entries:
- .changes
- .changie.yaml
- .gitattributes
- .gitignore
- .php-cs-fixer.dist.php
- CHANGELOG.md
- LICENSE
- README.md
- composer.json
- composer.lock
- dev
- docker
- docker-compose.yml
- generated
- phpcs.xml
- phpunit.xml.dist
- psalm.xml
- runtime
- scripts
- src
- tests
```
**With that fix**
```
dagger call -m github.com/wingyplus/dagger/sdk/php/runtime@cd3a3e724aa5a2ce259fe6b217f0efe5abaaabcb source-dir
_type: Directory
digest: …
```

feat: apply ignore pattern on context directory git source

---

sdk/typescript/.changes/unreleased/Fixed-20240916-201247.yaml
sdk/typescript/graphql/client.ts

Rawcode spotted an issue https://discord.com/channels/707636530424053791/1284180822135406656 where traces where no longer published to traces.
The issue is introduced by a change of the type from a plain JSON object to `Headers` which break the current opentelemetry propagator. This PR fixes that issue by using a custom injector to set the `traceparent` header

fix: TS regression introduce by grapql-request dep bump

---

engine/client/client.go
engine/clientdb/log.go
engine/clientdb/models.go
engine/clientdb/queries.sql
engine/clientdb/queries.sql.go
engine/clientdb/schema.sql
engine/clientdb/span.go
engine/server/session.go
engine/server/telemetry.go
engine/telemetry/logs.go
sdk/go/telemetry/init.go
sdk/go/telemetry/logging.go
sdk/go/telemetry/transform.go

Previously OTLP log data recorded into the client's SQLite database was dropping somewhat important information such as the OTel resource that generated the logs. I noticed this while investigating duplicate logs in Cloud, since half of them had a blank resource, and half of them didn't - the root cause of that ended up being https://github.com/open-telemetry/opentelemetry-go/issues/5782 but that blank resource value seemed worth fixing anyway, and led to a few other refactors which I'll explain inline.
(No behavior change is expected here - just some housekeeping)

clientdb: preserve more OTLP data

---

core/schema/modulesource.go
core/util.go

change includeSet and excludeSet to use a slice without duplicates given
that the order of the globs is important when calling buildkit.

engine: set include and exclude globs deterministically

---

.changes/unreleased/Fixed-20240913-110529.yaml
core/directory.go
core/file.go
core/integration/directory_test.go
core/modfunc.go
core/schema/directory.go
engine/buildkit/llbdefinition.go
engine/buildkit/ref.go

Fixes https://github.com/dagger/dagger/issues/8441

fix: `Directory.digest` should not panic on scratch directory

---

engine/client/client.go

*Partially* fix for https://github.com/dagger/dagger/issues/8329.
The `:mem:` host here is *really* weird, I don't know the logic for it, but it makes for some very confusing error messages, so we should fix it to something more reasonable and recognizable.

chore: change DirectConn host to "dagger"

---

.changes/unreleased/Fixed-20240913-134016.yaml
.changes/unreleased/Fixed-20240913-134354.yaml
core/container_exec.go
core/enum.go
core/integration/module_test.go
core/interface.go
core/modfunc.go
core/modtypes.go
core/object.go
core/query.go
core/schema/coremod.go
core/typedef.go
dagql/server.go
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
engine/buildkit/ref.go
engine/server/client_resources.go
engine/server/resource/id.go
engine/server/session.go

This PR contains a few fixes, extracted out of #8149, and others.
Added two changelogs, since there are two distinct fixes here, but not worth splitting them out into separate PRs, since they're both part of the same effort here :laughing: 
Both issues were introduced in https://github.com/dagger/dagger/pull/7804.
---
There's a rather nasty bug with `// +private` fields (and the equivalent in python/typescript). If an ID is stored in there, we have no way of knowing it's there.
As discussed [in discord](https://discord.com/channels/707636530424053791/1281246101487353917), it's not feasible to expose each private field to the API - there may be data in there that cannot be exposed to the API (e.g. today maps are a big case), but there may definitely be others. For backwards-compat reasons, …

Fix secret transfer issues between modules

---

cmd/dagger/session.go
engine/client/client.go
engine/client/drivers/docker.go
engine/client/drivers/driver.go

See https://github.com/dagger/dagger/pull/8232 for context
Alternative of #8340
This is a much simpler alternative that works as follows:
- If the `docker-image://` contains a digest, it uses that as the container ID (same behavior as before)
- Otherwise, it will use the image tag as container ID (as opposed to reaching out to a registry to convert tag to digest)

docker driver: Use tags instead of digests to avoid registry lookups

---

sdk/php/runtime/template/src/Example.php

Indents first level of indentation to 4 spaces,
This level of indentation matches standards: PSR2, PSR12, PER2
Was indented to 5 spaces for some reason. 
_Downside of leaving it at 5 spaces:_ it confuses a lot of IDE's and new code is misaligned until you manually correct the whole file.

Indent Php template correctly

---

cmd/dagger/flags.go
core/integration/module_test.go
engine/buildkit/executor_spec.go
engine/client/client.go
engine/client/pathutil.go
engine/client/pathutil_test.go

Fixes #8337 AND fixes some relative path issues
This PR addresses issues with SSH_AUTH_SOCK handling and improves test coverage:
1. Expands shell variables in SSH_AUTH_SOCK path
2. Make SSH_AUTH_SOCK path absolute
3. Adds integration tests for shell expansion handling and relative path calls
https://discord.com/channels/707636530424053791/1281294189463732244/1281294189463732244
The decision to avoid making the SSH_AUTH_SOCK path relative is based on several factors:
Users have been complaining of some parsing issues regarding the SSH_AUTH_SOCK. After some digging in the codebase, it seems better not to handle it relatively:
On the engine side, we [URL encode](https://github.com/dagger/dagger/blob/main/core/socket.go#L174-L189) the socket Path in order to forward it from the client to the …

core: make `SSH_AUTH_SOCK` absolute + handle shell expansion in `SSH_AUTH_SOCK` env var

---

sdk/python/runtime/discovery.go
sdk/python/runtime/main.go

This hopefully reduces the chance for cache invalidation by not including `.venv` inside the context directory on `ModuleRuntime`.

chore(python): optimize creating virtual env outside of context dir

---

.changes/unreleased/Added-20240823-124355.yaml
.changes/unreleased/Added-20240913-134900.yaml
core/container.go
core/directory.go
core/integration/container_test.go
core/integration/directory_test.go
core/schema/container.go
core/schema/directory.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/container.ex
sdk/elixir/lib/dagger/gen/directory.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/php/generated/Directory.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Continuing on from #6475, we should have `withoutFiles`, just as we have `withFiles`.
Ended up wanting this for working on an internal test, so decided to just add it :tada:

feat: add withoutFiles on Container and Directory

---

sdk/elixir/dagger.json
sdk/elixir/runtime/go.mod
sdk/elixir/runtime/main.go

Make Elixir SDK consistent with PHP (in #8369), the include patterns is now moved to `+ignore` directive.

feat(sdk/elixir): apply `+ignore` to sdkSourceDir

---

sdk/python/runtime/dagger.json
sdk/python/runtime/main.go

See https://github.com/dagger/dagger/pull/8245#discussion_r1733172781 for context.
The previous module ID hashing just really isn't very stable - we can hash the contents for *way* better results.

fix(python): use ModuleSource.digest for stable unique path

---

.dagger/checks.go
.dagger/main.go
.dagger/sdk.go
.dagger/sdk_all.go

Extended the checks api, so now we have `sdk/go` (and others), which contain `sdk/go/lint`, `sdk/go/test` and `sdk/go/test-publish`.

ci: cleanup and extend checks api

---

sdk/elixir/runtime/main.go

* Move `deps.get` out of the entrypoint.
* Add `--only dev` to `deps.get` to ensure we have only necessary dependencies for invoke a function. entrypoint.

fix(sdk/elixir): separate deps.get and dagger.invoke

---

.changes/unreleased/Fixed-20240918-182949.yaml
cmd/dagger/version.go

This isn't set up right - it ends up stranded, establishing itself as the root span of its own trace.
I'm not sure if we got much from this span, but if we want to bring it back we might need to wait to do it until after we set up the frontend + root span (in `cmd/dagger/engine.go`).

remove 'check for updates' span

---

.changes/unreleased/Fixed-20240919-130124.yaml
go.mod
go.sum

Dependabot erroneously bumped this to a _lower_ version - what a jerk
This sort of breakage will be prevented in the future via the test suite introduced in #8442

re-bump midterm to fix double linebreaks

---

cmd/dagger/version.go

tested manually locally:
```
dagger on  fix-version-nag [$] via 🐹 v1.23.1 
❯ go build -ldflags "-X github.com/dagger/dagger/engine.Version=v0.13.2 -X github.com/dagger/dagger/engine.Tag=v0.13.2" -o ./bin ./cmd/dagger
dagger on  fix-version-nag [$] via 🐹 v1.23.1 took 2s 
❯ ./bin/dagger version
dagger v0.13.2 (registry.dagger.io/engine:v0.13.2) linux/amd64
dagger on  fix-version-nag [$] via 🐹 v1.23.1 
❯ ./bin/dagger core version
✔ connect 0.3s
✔ initialize 0.4s
✔ prepare 0.0s
✔ version: String! 0.0s
Full trace at https://dagger.cloud/dagger/traces/26922b4f39051af2af9dd68bd93f9640
v0.13.2
dagger on  fix-version-nag [$] via 🐹 v1.23.1 
❯ gst
On branch fix-version-nag
nothing to commit, working tree clean
dagger on  fix-version-nag [$] via 🐹 v1.23.1 
❯ gst
On branch fix-version-nag
nothing …
```

fix version nag

---

dagql/idtui/frontend_pretty.go

On a US keyboard, `-` does not require shift to be pressed, but `+` does (on the `=` key).  This makes it annoying to adjust the verbosity quickly.  This adds `=` as an alias for `+` so either can be used to increase the verbosity, and you can avoid using the shift key altogether.
This has been a paper cut for me as I try to turn up the verbosity to learn what dagger is doing and then trying to dial it back down to the default.

allow '=' to also increase verbosity

---

core/schema/service.go

this helps to easily open tunnel http endpoints from the terminal

chore: print http url for tunneled services

---

sdk/python/.readthedocs.yaml

The `sdk/python/.readthedocs.yaml` isn't being used yet. It's meant to replace the [one at the root](https://github.com/dagger/dagger/blob/5ec03a604d50b721aaa65ba7c4db8c875696ac72/.readthedocs.yaml), but needs this fix before switching.

fix readthedocs command

---

docs/current_docs/integrations/snippets/gitlab-runner-config.yml

When using config from docs, got this error:
[31;1mFATAL: Could not handle configuration merging from template file[0;m  [31;1merror[0;m=couldn't load configuration template file: toml: line 2 (last key "runners.environment"): expected a comma (',') or array terminator (']'), but got '='
Based on other vars set in the array, the last item seems to have 2 additional "

Fix syntax error in environment config

---

docs/current_docs/manuals/user/remotes/remote-repositories.mdx

These have been fixed by https://github.com/dagger/dagger/pull/8365

docs: remove deprecated parts of ref docs

---

.changes/unreleased/Fixed-20240923-134323.yaml
core/container.go
core/integration/container_test.go

Fixes https://github.com/dagger/dagger/issues/6999 (actually this time).
This PR follows-up on https://github.com/dagger/dagger/pull/8409, and ensures annotations are correctly attached for `Container.Export` and `Container.AsTarball` as well.

fix: annotations on `Container.Export` and `Container.AsTarball`

---

sdk/php/dev/src/PhpSdkDev.php
sdk/php/runtime/scripts/init-template.sh
sdk/php/runtime/template/src/Example.php
sdk/php/src/Attribute/Argument.php
sdk/php/src/Attribute/DaggerFunction.php
sdk/php/src/Attribute/Doc.php
sdk/php/src/Command/EntrypointCommand.php
sdk/php/src/ValueObject/Argument.php
sdk/php/src/ValueObject/DaggerFunction.php
sdk/php/src/ValueObject/DaggerObject.php
sdk/php/tests/Unit/Fixture/DaggerObjectWithDaggerFunctions.php
sdk/php/tests/Unit/Fixture/NoDaggerFunctions.php
sdk/php/tests/Unit/ValueObject/ArgumentTest.php
sdk/php/tests/Unit/ValueObject/DaggerFunctionTest.php
sdk/php/tests/Unit/ValueObject/DaggerObjectTest.php

Apologies, my previous PR closed and I can't seem to reopen it even with the branch having the commit re-added.
Related to https://github.com/dagger/dagger/pull/8411#discussion_r1764090130
Deprecate Argument attribute.
Doc attribute has a single responsibility and is reusable.
Objects can have descriptions now. [Demonstrated on this example module](https://daggerverse.dev/mod/github.com/charjr/dagger-modules/test-php-doc@150bdd93729eb4cf2769f88f1f577487ea25a6a8#TestPhpDoc)
Support description for base module. #8495

Add Doc Attribute

---

sdk/elixir/lib/dagger/mod/function.ex
sdk/elixir/lib/dagger/mod/object.ex
sdk/elixir/lib/dagger/mod/object/defn.ex
sdk/elixir/lib/dagger/mod/object/meta.ex
sdk/elixir/test/dagger/mod/object_test.exs
sdk/elixir/test/support/object_mod.ex

~⚠️ Needs #8367~ 
The function arguments can now annotate metadata by using a tuple
(`{}`). The current metadata now support only:
* `:doc` - The argument description.
* `:default_path` - The context directory.
* `:ignore` - The ignore patterns.
The default value is not included in this commit.

 feat(sdk/elixir): type argument can now annotate the metadata

---

sdk/typescript/entrypoint/entrypoint.ts

To have a better understanding of https://github.com/dagger/dagger/issues/8524 this PR display the `cause` field from the error object.
Test function:
```typescript
@func()
error(): string {
throw new Error("foo", { cause: new Error("bar") })
return 'a'
}
```
Before
```
$ dagger call error
Stderr:
Error: foo
```
Now: 
```
$ dagger call error
Stderr:
Error: foo, Error: bar
```

feat: ts-sdk now print error cause in error case

---

engine/buildkit/client.go
engine/buildkit/ref.go

Related to https://github.com/dagger/dagger/issues/7699
Two related commits here:
---
[engine: log buildkit errors in right place to reveal stack traces](https://github.com/dagger/dagger/commit/64a236448dac51b92d35f2f35899aa3a38b3d079)
Previously we started logging buildkit solve errors with a `%+v` in
order to reveal the stack traces embedded in the errors by buildkit's
usage of github.com/pkg/errors, which in many places in buildkit is the
only way to get any extra information on where an error is actually
coming from (needed for debugging "context cancelled" errors
specifically).
This did not quite work for a pretty dumb reason: it turns out that if
you wrap an error from github.com/pkg/errors using fmt.Errorf (i.e. the
standard library) then the trick for extracting the stack trace …

Enhanced debugging errors for `context cancelled` from Buildkit

---

.changes/unreleased/Fixed-20240925-131536.yaml
core/modulesource.go

Based on https://discord.com/channels/707636530424053791/1003718839739105300/1288200722948558922
Tested on https://github.com/TomChv/dagger-git-ctx-dir
**Before**:
```
dagger call -m https://github.com/TomChv/dagger-git-ctx-dir/go rel
_type: Directory
digest: sha256:d2a243922ee5ddef94022fdaf7f6159020750476eae9fb9784df5c9362aa0904
entries:
- go
```
**After**:
```
dagger call -m https://github.com/TomChv/dagger-git-ctx-dir/go rel
_type: Directory
digest: sha256:b013fc11f9f38ad24478c1c3b011fd376856cb2ddf9573e3ee21186eae1c3a42
entries:
- LICENSE
- dagger.json
- src
```

fix: correctly resolve relative path for git module

---

core/integration/module_test.go

Closes #8571
When testing the TestSSHAuthSockPathHandling, Alex encountered rightfully a flake on this test, leading to this error:
```
Error: module at source dir "" doesn't exist or is invalid
```
It turns out that the error comes from the tests being run in parallel whilst relying on the same client
More context [here](https://github.com/dagger/dagger/issues/8571#issuecomment-2375333486). After the change, no flake after 30 runs on my side
> Still a bit surprised that in a nested environment, when interacting with the host, the same client cannot be used in parallel. Is it my test / setup that is wrong or is it by-design / expected ? 
The very reason that it sometimes work would be that one of the test sets the nested SESSION's env vars prior the second one's erasing the HOME var, or …

fix: flake on TestSSHAuthSockPathHandling test

---

core/moddeps.go

Saw this while looking into https://github.com/dagger/dagger/pull/8568
These types can't actually be constructed, but we're still putting them in the codegen for modules. We don't need to, so we can just remove these to tidy things up.
When this API was originally added, we missed these types out: https://github.com/dagger/dagger/pull/7767/files#diff-66495f543507cb3a2373d8c23981491184d26ffe1bd45140faab4445bb3a5177R28

chore: remove other engine types from codegen

---

.github/workflows/engine-and-cli-publish.yml
version/git.go

See #8564.
Engine publish is failing - https://github.com/dagger/dagger/actions/runs/11058428600/job/30724413276. We can remove those extra steps though, since now the version module handles this (the commit timestamp is used, so we get the right results here).
Also, I can't run `dagger call` locally - this is because, my repo is already unshallowed, so calling `unshallow` causes a failure. There's a neat way to do this though - we just set the `--depth` to the max int32 value, as specified in the git docs here: https://git-scm.com/docs/shallow
> The special depth 2147483647 (or 0x7fffffff, the largest positive number a signed 32-bit integer can contain) means infinite depth.
This should only deeper the current branch, instead of unshallowing *everything*.

More fixups from `version` split fallout

---

core/schema/module.go
sdk/php/src/Command/EntrypointCommand.php
sdk/python/src/dagger/mod/_resolver.py
sdk/typescript/entrypoint/register.ts

This refactor makes the engine enforce `withOptional(true)` on function arguments that use `defaultPath`. Otherwise it's a footgun for the SDKs to ensure, especially since `withOptional` is incorrectly named.
Context:
- https://github.com/dagger/dagger/pull/8411#discussion_r1775675521
- https://github.com/dagger/dagger/issues/6749

chore(refactor): make engine set optional on defaultPath so SDKs don't have to

---

core/integration/module_test.go
core/integration/module_up_test.go

Noticed in https://dagger.cloud/dagger/traces/b3d53b83e726ac25892517310b0ee9d2#2e580acd7b4b57ea:L3.
This doesn't help the output for our flakes when this does flake - we see multiple interrupts, which isn't right.
`cleanupExec` is already called as part of `hostDaggerCommand`.

tests: avoid calling cleanup-exec twice

---

docs/current_docs/manuals/developer/snippets/documentation/python/main.py

As discovered by @kpenfound during friday demos

docs: remove confusing inline docs in python examples

---

version/git.go
version/main.go

If an empty directory was passed to the version module, then `.git` wouldn't be available, and so all the git operations would fail. The fix is to detect it before running any of the commands.
But to do that, we need a context and an error - so we just move all this operation straight into the constructor, which also avoids a ton of extra calls to the `Git` function anyways.

ci: fix version module when no git metadata is available

---

docs/current_docs/manuals/developer/snippets/state-functions/go/main.go

docs: remove redundant default pragma from Go struct

---

.dagger/cli.go
core/integration/testdata/nested-c2c/main.go
dagger.json
engine/distconsts/consts.go
go.mod
modules/go/main.go

I was getting ephemeral panics from the Go runtime on my OTEL metrics PR that (seemingly?) disappeared when I upgraded to the new version of Go. Not sure precisely which change fixed it (they were "invalid pointer found in heap" errors) but there were a few fixes to the runtime and open issues that seemed possibly related, so worth an upgrade.

chore: upgrade go to 1.23.2

---

docs/current_docs/cookbook/snippets/cache-dependencies/typescript/index.ts
docs/current_docs/quickstart/snippets/daggerize/go/main.go
docs/current_docs/quickstart/snippets/daggerize/python/__init__.py
docs/current_docs/quickstart/snippets/daggerize/typescript/index.ts
docs/current_docs/quickstart/snippets/env/go/main.go
docs/current_docs/quickstart/snippets/env/python/__init__.py
docs/current_docs/quickstart/snippets/env/typescript/index.ts
sdk/rust/crates/dagger-sdk/examples/caching/main.rs

Mounting a cache volume at `node_modules` within the workdir can cause major issues for a lot of npm apps, especially if the volume is used for multiple projects or multiple sessions.  Because of this, its better to mount the volume to npm's cache directory and let npm pull from the cache itself.
This best practice applies to all usage of cache volumes, however the examples we have for Go and Python already work this way.

docs: use npm cache instead of node_modules for cache volumes

---

cmd/engine/logger.go

The intention here should be to initialize a slice with a capacity of len(x) rather than initializing the length of this slice.

fix: fix slice init length

---

.github/workflows/engine-and-cli.yml

I was benchmarking alternative CI runners and noticed that these jobs were being CPU starved. They are 25% - 40% faster when given an adequate number of CPUs.
| Job | Before | After |
| :- | -: | -: |
| engine / lint | `8m 7s` | `4m 8s` |
| engine / test-publish | `6m 44s` | `3m 14s` |
| engine / scan-engine | `3m 37s` | `?` |

ci: Bump CPU for a few jobs which were CPU starved

---

sdk/typescript/graphql/client.ts

Following up with #8549, it seems the issue is caused by the native `fetch`. I'm trying to replace the client with `node-fetch` which is a more optimized version of `fetch` for server-side request.

feat: ts-sdk replace `fetch` with `node-fetch`

---

.changes/unreleased/Added-20240916-192525.yaml
.dagger/sdk_php.go
core/container_exec.go
core/integration/container_test.go
core/schema/container.go
core/schema/schema_test.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/dev/dagger.json
sdk/php/dev/src/PhpSdkDev.php
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

This adds expanding environment variables in `WithNewFile`.  ref: #7951. If this looks OK, I will add similar changes to other API's in this same PR.

feat(engine): support expanding variables in more functions

---

.dagger/engine.go
.dagger/main.go
.dagger/sdk.go
.dagger/test.go

Fixes https://github.com/dagger/dagger/issues/8644
Expecting it to fix the following error:
Fatal errorinit error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error
GET https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2: TOOMANYREQUESTS: retry-after: 566.363µs, allowed: 44000/minute
---
Follow-up to:
- https://github.com/dagger/dagger/pull/8643

ci: Bump & sha256 pin aquasec/trivy image

---

core/integration/engine_test.go
core/schema/module.go
engine/client/client.go
engine/server/session.go
engine/version.go
engine/version_test.go

Fixes https://github.com/dagger/dagger/issues/8562.
Previously, these could be a little tricky to read, so we rephrase them to make them a little easier to read.
The new error is something like:
```
Error: input: moduleSource.withContextDirectory.asModule resolve: failed to create module: select: module requires dagger v0.13.8, but you have v0.13.4
```

chore: enhance version error messages

---

.changes/unreleased/Fixed-20240926-132311.yaml
core/integration/module_config_test.go
core/schema/modulesource.go
engine/buildkit/filesync.go

Fixes https://github.com/dagger/dagger/issues/8136
Note: I switched the order in the UI to show includes before excludes because that's the order that buildkit applies them.

fix include/exclude from dependencies not prefixed correctly

---

.changes/unreleased/Added-20241008-125457.yaml
core/container_exec.go
core/healthcheck.go
core/integration/images.go
core/integration/services_test.go
core/integration/testdata/counter/main.go
core/integration/testdata/relay/main.go
core/schema/service.go
core/service.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
engine/distconsts/consts.go
engine/sources/gitdns/source.go
engine/sources/httpdns/source.go
network/hosts.go
sdk/elixir/lib/dagger/gen/service.ex
sdk/go/dagger.gen.go
sdk/php/generated/Service.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Allows you to manually configure a hostname for a service, which will be automatically namespaced within the module. This ability allows you to express circular service dependencies, which was previously impossible with content-addressed hostnames.
Implementation notes:
* New API: `Service { withHostname(hostname: String!): Service! }`
* Sets a custom hostname to be used instead of the regular content-addressed (query ID -derived) hostname
* When a service has a custom hostname its FQDN will be `<host>.<module id>.<session id>.dagger.local`
* The `<module id>` is a new component to ensure two modules setting the same hostname don't conflict
* A `withExec` always installs its calling `<module id>.<session id>.dagger.local` to its list of search domains
* In other words, it will always be …

add Service.WithHostname

---

engine/buildkit/cacerts/distros.go

since those are CentOS based, this already works with the current rhel
installer

engine: add support to install certs in amazon linux

---

cmd/dagger/main.go
dagql/dagui/dot.go
dagql/dagui/opts.go
dagql/idtui/frontend_plain.go
dagql/idtui/frontend_pretty.go

This is a slightly cleaned up version of what I did at Dagger's recent team hackathon, differences being:
1. Code is *slightly* improved from hackathon-quality (just so it can be easier to build off of and not complete throwaway)
2. No exec metrics yet (like disk usage) since that PR is still pending merge
3. It's controlled via hidden top-level dagger CLI flags now (instead of inlined consts):
* `--dot-output=<path>` will trigger writing a `.dot` formatted file to the given path
* `--dot-focus-field=<gql field name>` gives some very crude filtering ability by resulting in only calls for the given field name and their descendents being shown
* `--dot-show-internal` results in calls under internal spans showing up too (they are hidden by default).
E.g. to look at the DAG for running a set …

cli: internal tooling for graphviz output

---

.changes/unreleased/Added-20241008-154901.yaml
core/container.go
core/container_exec.go
core/integration/container_test.go
core/schema/container.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

fixes #8573, at least partially
this pr adds a size parameter to withMountedTemp and passes that down to buildkit's mount initialization.
I had many questions that @sipsma answered in the comments.
1. I don't particularly like the structure of the test, adding a whole additional test that's 99% repeated code, but it seems hard to parameterize around optional params; putting 2 WithMountedTemps in parallel creates a marshaling-into-struct ambiguity that's unresolvable.... should I be chaining or something? 
2. Is the "size" parameter in the appropriate place in the graphql schema? it can only be supplied for tmpfses, but it lives on the same level. do we want errors if folks try to supply sizes for other mounts? where would one add that logic?
3. corollary question, should we be adding a …

feat: support tmpfs size in withMountedTemp

---

sdk/typescript/package.json
sdk/typescript/telemetry/attributes.ts
sdk/typescript/yarn.lock

Same as #8525, I update the TS SDK to use HTTP client instead of gRPC.
Example:
```ts
import { dag, Container, object, func } from "@dagger.io/dagger"
import { getTracer } from "@dagger.io/dagger/telemetry";
@object()
class Test {
@func()
async echo(stringArg: string = "hello"): Promise<Container> {
return getTracer().startActiveSpan("yolo", async (span) => {
return dag.container().from("alpine:latest").withExec(["echo", stringArg]).sync();
});
}
}
```
The trace: https://dagger.cloud/Quartz/traces/649fab3c45a524d6eb8169a214b70f3a#fd4cfcdc7bdb7d9e
It seems like it works well like that. @helderco Is there anything more I should change in the SDK?

feat: update ts SDK telemetry

---

.changes/unreleased/Added-20241008-171908.yaml
core/container_exec.go
core/integration/container_test.go
core/schema/container.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

Dagger automatically injects an init process in withExecs in order to avoid surprising behavior around processes being PID 1. I have generally gathered that this is the right default behavior, to the point that I've seen some docker maintainers say that they wish docker had defaulted to this same behavior.
However, there are less common use cases that do call for user processes being PID 1, such as when they want very custom init behavior or are testing init systems (i.e. testing systemd in a container).
For a long time this was impossible because of the shim but after we moved to the executor, which operates entirely in the engine process, it became technically optional to have an init process injected into the container (even if the right default).
This change adds an option to …

core: support disabling automatic init in withExec

---

.dagger/README.md

see https://github.com/dagger/dagger/pull/8652#pullrequestreview-2355647374 where @sipsma noticed this documentation gap.

docs: add instructions to generate all sdks if you've made GQL schema changes

---

core/schema/sdk.go

While working on metrics stuff I realized the go build step was writing 19MB for trivial modules, thanks to Go's well known large binary size.
I tried stripping DWARF debug symbols with -ldflags='-s -w' and found it saved about 6MB.
This is not the biggest disk space hog in CI by any means, but saving 6MB per module across the 100+ we build for test runs seems like an easy marginal win given there's no real downside to dropping these debug symbols at this time (right? I can't think of any).

go: strip runtime binaries to save disk space

---

core/integration/legacy_test.go
core/schema/git.go

Follow-up for https://github.com/dagger/dagger/pull/8318.
A few issues:
- Accidentally, support was enabled for `keepGitDir` as the default on v0.13.0+ (due to merge timing issues) - this should only have been enabled for versions v0.13.4+.
- As reported by @sagikazarmark [here](https://discord.com/channels/707636530424053791/1120503349599543376/1293606367692849202), when calling `treeLegacy`, then we would attempt to unmarshal into a private field (which is invalid). This wasn't tested by our tests.
This fixes the original issue, but ideally we can add some better tests to ensure that all the schema is actually unmarshalable - this shouldn't be possible to hit.

fix: git schema issues

---

docs/src/theme/NotFound/Content/index.tsx
docs/src/theme/NotFound/index.tsx

swizzle docusaurus NotFound component so we can add a custom header for
better tracking users that land in a 404 page

docs: swizzle 404 page

---

.dagger/sdk.go
RELEASING.md
dagger.json

We couldn't do this before because we needed https://github.com/sagikazarmark/daggerverse/pull/183.
Now we can mark SDK release notes as *never* the latest, so we can just automatically publish these without going through draft.

ci: automatically publish release notes for sdks

---

.github/workflows/engine-and-cli.yml

The spot-instance version of these nodes are having trouble existing right now, we want to move off spot instances anyways so just updating these right now to unblock these jobs hopefully.

ci: use on-demand instances for lint+test-publish

---

.github/.github/.gitattributes
.github/dagger.json
.github/main.go
.github/workflows/engine-and-cli-publish.yml
.github/workflows/engine-and-cli-split.yml
.github/workflows/engine-and-cli.yml
.github/workflows/helm-publish.yml
.github/workflows/sdk-elixir-publish.yml
.github/workflows/sdk-go-publish.yml
.github/workflows/sdk-php-publish.yml
.github/workflows/sdk-python-publish.yml
.github/workflows/sdk-rust-publish.yml
.github/workflows/sdk-typescript-publish.yml

> [!NOTE]
> Already includes changes from https://github.com/dagger/dagger/pull/8643
They are getting disrupted often, and that becomes annoying after a few weeks of turbulence.
Before we can merge this, need to introduce `dind-od` instances.

ci: Stop using spot instances

---

docs/current_docs/manuals/user/visualization/cloud-get-started.mdx

This pull request aims to mention `dagger login` at [Dagger Cloud Introduction](https://docs.dagger.io/manuals/user/cloud-get-started/#connect-from-your-local-development-host) documentation.
After the `dagger login` there was no mentions about `dagger login` on Dagger Cloud Introduction documentation.
The idea is to add it (`dagger login`) as a new way to connect to Dagger Cloud.
Closes #7734

docs: add mention about dagger login on cloud-get-started documentation

---

sdk/php/src/Command/EntrypointCommand.php
sdk/php/src/Service/DecodesValue.php
sdk/php/src/Service/NormalizesClassName.php
sdk/php/src/ValueObject/Type.php
sdk/php/tests/Unit/Service/NormalizesClassNameTest.php
sdk/php/tests/Unit/ValueObject/TypeTest.php

- Extracts logic for normalizing class names before registering them with Dagger.
- Adds tests for the extracted logic.
[sdk/php/src/Command/EntrypointCommand.php](https://github.com/dagger/dagger/compare/main...charjr:add-normalize-classname?expand=1#diff-9a9bae0159266493bd51c77501f9e9bfa8e1ef6d4ae998719e760c57cada1e58) is tied heavily to the dagger engine and cannot easily be tested in isolation. [This service](https://github.com/dagger/dagger/pull/8607/files#diff-55deae05ce0b3d6698fb01c4636faf6ca1f4e203ac81f53f9f28310a7a1e4d78) extracts logic from the EntrypointCommand [to make it testable](https://github.com/dagger/dagger/pull/8607/files#diff-c2bf4fe664d08669a2dee5d8de256c7a37326eea951b68dc95943358030479df) in isolation.
It also reduces the repetition of classes that require duplicate …

PHP SDK: Extract logic from entrypoint to test in isolation

---

cmd/codegen/generator/go/generator.go
cmd/codegen/main.go
cmd/codegen/trace/trace.go

context: While working on the otel metrics stuff I saw the codegen steps sometimes writing several hundred MB to disk for seemingly no reason, so went off on a tangent looking into that. Still not sure, but on that tangent followed a subtangent around `packages.Load` taking an absurd amount of time (also seemingly randomly).
---
The call to packages.Load, which does the syntax parsing + type checking needed for go module codegen seems to be a pretty big bottleneck in terms of time. It's often at least half of the time spent in the codegen bin when building modules and I see cases where it's taking more like 18s out of the 20s codegen runs for.
* It's possible that it's downloading deps and thus saving work later, but it's not clear to me that's true yet.
This adds a trace around …

go: trace loadPackages + optimize slightly

---

core/integration/module_call_test.go
core/integration/module_cli_test.go
core/integration/module_config_test.go
core/integration/module_test.go

Follow-up of https://github.com/dagger/dagger/issues/8385#issuecomment-2406128224
Attempting the same fix to all the tests: a few were missing + unifying how we cleanup the cancel()

fix: SSH flake on integration test suite

---

.github/workflows/engine-and-cli-publish.yml

Still getting problems starting colima: https://github.com/dagger/dagger/actions/runs/11298598079/job/31428172736#step:3:192
Based on various issues around github, getting this to work is an utter shitshow, so we're not alone.
Found this relevant issue: https://github.com/lima-vm/lima/issues/1742
Which lead to a linked issue that showed a successful setup of installing docker, trying it out here.

Fix macos docker install in CI

---

.changes/unreleased/Fixed-20241014-161755.yaml
core/enum.go
core/integration/module_type_test.go
core/module.go
core/typedef.go
dagql/objects.go
dagql/types.go

Fixes https://github.com/dagger/dagger/pull/8673#issuecomment-2407223417
`false` and `true` values are always decoded by gqlparser as booleans - however, this might not always be the case: a standalone value *might* potentially be decodable as an enum instead.
The solution for this is to just add another case for decoding booleans in enums.
> [!NOTE]
>
> There's really no way to avoid this hack from what I can tell - you can put a `false`/`true` value as an enum value, but when you come to parse it, the parse tree you *should* construct is dependent on the types that you declare inside the parse tree :cry: Not actually sure if there exists a general class of parser that can correctly parse these :laughing:

fix: allow decoding enums that overlap with bool types

---

.dagger/engine.go
.dagger/main.go
.dagger/sdk.go

This allows sharing the engine cache locally across `dagger call dev`
calls which results quite convenient when testing different engine
versions
i.e `dagger -m github.com/dagger/dagger@pull/8728/head call dev --shared-cache terminal`

ci: allow to share engine cache across dev calls

---

.changes/unreleased/Fixed-20241018-124913.yaml
core/object.go
core/schema/sdk.go

Spending today looking into why `initialize` is so slow. Starting out with why it takes multiple seconds in our CI even when everything is completely cached.
Two quick fixes here:
* We weren't even getting telemetry for SDK module calls, now we do
* We weren't caching SDK constructor calls, now we do
Tested by running `dagger -m 'github.com/dagger/dagger@1adf268ec84693f6543d291083ee8b856a277be5' functions` repeatedly and seeing how long `initialize` took when everything was cached and no local changes were present:
* Before: 2.3s - 2.6s
* After: 1.5s - 1.9s
So an improvement of ~1s. This is obviously not life-changing yet, but these marginal improvements should stack up.
* Next up is to figure out why resolving some images that are cached and pinned by SHA involves network requests and is …

engine: cache internal sdk constructor calls

---

core/schema/module.go
core/schema/sdk.go

Been getting a better understanding of why initialize is slow in the uncached and partially cached cases. The fixes are a bit more involved than the other quick fixes today so still WIP. Just sending out a few easily separable fixes from that effort in the meantime.
Main change to split initialize up into more subspans, which makes it much much easier to tell what the hell is going on in the initialization timing in the trace UIs.
Other one is just a fix for something misc I noticed while working on the go sdk: we have been leaving shared cache mounts in the final runtime container, so all Go functions have been capable of doing IPC with each other across sessions 😄 Super obscure but worth fixing.

engine: split module initialize into more spans

---

.dagger/sdk.go
dagger.json

Follow-up to https://github.com/dagger/dagger/pull/8673 - this wasn't *quite* right, since `true`/`false`/`null` are "special" words.
We need https://github.com/dagger/dagger/pull/8682 to be released in v0.13.6 before the original works *properly*.

hack(ci): use enum values that don't clash with booleans

---

.changes/unreleased/Fixed-20241018-153744.yaml
core/container.go
core/schema/container.go
core/schema/util.go
core/terminal.go
dagql/server.go

There's two interrelated improvements here.
---
First, before this change we were always making network requests for image metadata even in the case where the image ref had a digest (and was thus immutable) *and* the image was already cached locally.
That was wasteful since there's no need to query registries for metadata on immutable images we already have locally.
That's fixed by using the "PreferLocal" resolve mode on images with a digest, which tells buildkit to check the local cache before checking a registry.
---
Second, before this change even though we always resolved image ref digests (if they didn't already have one), the actual ID for container.From still included the unresolved image ref the user provided. That had some subtle but significant side effects.
For example, while …

engine: optimize+stabilize container.From with digests

---

version/main.go

Follow-up from #8749.
Oops, turns out, if there are multiple authorization sections in `.git` then we have issues! We attach multiple authorization headers (https://github.com/git-lfs/git-lfs/issues/4031)
https://github.com/dagger/dagger/actions/runs/11463663592/job/31898032845
The "right" solution for this is to have our versioning module ignore the github-generated `.git/config`.

ci: fix go/php git publishing

---

.changes/unreleased/Added-20241022-224954.yaml
dagql/idtui/frontend.go
engine/buildkit/resources/cpustat.go
engine/buildkit/resources/formats.go
engine/buildkit/resources/iostat.go
engine/buildkit/resources/sampler.go
sdk/go/telemetry/metrics.go

Only displaying CPU pressure time in TUI right now since that's what I'm most interested in, but other CPU usage is plumbed  now too. Need to rework metrics display before adding more since it's starting to get to be too long a line.
---
Fun fact: when initializing our CI module from empty cache and a go codegen step takes a long time (~30s), up to half the time is spent shows up as full CPU pressure (which means every thread in the container is blocked waiting for a CPU to be available)... This on my 8 core m1 macbook.
Working on some fixes there (go build doesn't de-dupe parallel ongoing work across processes) but these metrics were useful to prove the problem was w/ cpu contention, so spinning out in the meantime.

engine: add cpu stat/pressure metrics

---

.changes/unreleased/Fixed-20241023-130813.yaml
.dagger/build/sdk.go
core/integration/proxy_test.go
core/schema/sdk.go

Spent today working on fixing the bottleneck in uncached Go module initialization time, which turns out to be due largely to CPU contention between go list/build processes (go does not de-dupe concurrent builds/module downloads across processes; dedupe only happens after builds/downloads finish and are written to cache).
* See description on [PR that added cpu pressure metrics](https://github.com/dagger/dagger/pull/8750)
I went all the way to "daggerizing" go build by turning each individual go package build that makes up a single `go build` call into separate dagger `withExec`s. While viable in the long term, it turns out that the engine itself becomes a bottleneck in that case since it doesn't appear to handle *huge* DAGs (i.e. 300+ vertexes and thousands of edges) well at all for …

Uncached module initialization time improvements

---

.changes/unreleased/Breaking-20241021-160603.yaml
cmd/dagger/module.go
core/integration/module_call_test.go
core/integration/module_cli_test.go
core/integration/module_config_test.go
core/integration/module_go_test.go
core/integration/module_python_test.go
core/integration/module_test.go
core/integration/module_typescript_test.go

use '.dagger' as source dir during 'init' and 'develop' when current dir is not empty

---

.dagger/docs.go
version/git.go
version/go.mod
version/main.go

More follow-up needed to https://github.com/dagger/dagger/pull/8756:
https://github.com/dagger/dagger/actions/runs/11474521348/job/31930585026
```
error=couldn't get remote URL: fatal: No remote configured to list refs from.
```
Goreleaser really seems to need a remote - not really sure why, but we should be filling in our remote in `version/git.go` anyways.

ci: manually set remote on git checkout

---

sdk/elixir/.changes/unreleased/Added-20241024-153531.yaml
sdk/elixir/lib/mix/tasks/dagger.entrypoint.invoke.ex
sdk/elixir/runtime/main.go
sdk/elixir/runtime/template.exs

Before this changeset, the invoke task living inside a user defined module. This is confuses for someone who read the module source code.
So, this changeset move the invoke task to the `dagger_sdk` and modify the runtime to use this task instead.
And the runtime is no longer generate mix task anymore.

feat(sdk/elixir): move entrypoint invoke task to dagger_sdk

---

.changes/unreleased/Fixed-20241021-150717.yaml
core/integration/git_test.go
engine/sources/gitdns/cli.go
engine/sources/gitdns/source.go

Fixes https://github.com/dagger/dagger/issues/8584 (upstream fix in https://github.com/moby/buildkit/pull/5441, but we have a vendored copy of the relevant files to handle our custom DNS for services).

fix: allow cloning commit shas not referenced by branch/tag

---

core/integration/cacert_test.go
core/integration/module_python_test.go
core/integration/module_test.go
core/integration/module_type_test.go
core/integration/testdata/modules/python/id/arg/main.py
core/integration/testdata/modules/python/id/fn/main.py
sdk/python/.changes/unreleased/Removed-20241014-154722.yaml
sdk/python/src/dagger/__init__.py
sdk/python/src/dagger/mod/__init__.py
sdk/python/src/dagger/mod/_arguments.py
sdk/python/src/dagger/mod/_module.py
sdk/python/tests/modules/test_registration.py
sdk/python/tests/modules/test_results.py

Fixes https://github.com/dagger/dagger/issues/8394
These were deprecated before v0.13, but haven't been removed yet:
- `Arg` was deprecated in [v0.12.5](https://github.com/dagger/dagger/releases/tag/sdk%2Fpython%2Fv0.12.5)
- Top-level functions were deprecated in [v0.12.4](https://github.com/dagger/dagger/releases/tag/sdk%2Fpython%2Fv0.12.4)
Besides, these features exist for a very long time but undocumented, so no user impact is expected.

chore(python): remove deprecations

---

core/integration/module_python_test.go
sdk/python/runtime/Dockerfile

Follow up to https://github.com/dagger/dagger/pull/8744 which was merged prematurely.

python: fix failing test from dependabot update

---

.changes/unreleased/Fixed-20241024-152529.yaml
core/container_exec.go
core/integration/container_test.go
core/modfunc.go
engine/buildkit/executor.go

User reported unexpected cache invalidation here: https://discord.com/channels/707636530424053791/1299094006592049262/1299094006592049262
Funnily enough, I had today ran into the exact same problem but in the context of our Go SDK's internal `codegen` exec, so we also need this fix (among others) to improve module initialization speed 😄
---
Before this, when nesting was enabled for an exec we would always scope the cache key with the dagql call digest for that exec.
This is important for the case of a module function call since it results in the cache key being scoped to that function's args and receiver.
However, this was also happening for non-function nested execs (i.e. use of the ExperimentalPrivilegedNesting flag). For those execs, this was unnecessary. It also resulted in excessive …

engine: fix excessive cache invalidation for non-function nested execs

---

install.sh

See discussion in https://github.com/dagger/dagger-for-github/pull/151#discussion_r1810958146.

chore: allow "latest" in DAGGER_VERSION parameter for `install.sh`

---

cmd/codegen/generator/go/templates/functions.go
cmd/codegen/generator/go/templates/module_funcs.go
cmd/codegen/generator/go/templates/module_types.go
cmd/codegen/generator/go/templates/src/_dagger.gen.go/module.go.tmpl
cmd/codegen/generator/go/templates/src/_types/enum.go.tmpl
cmd/dagger/config.go
cmd/dagger/flags.go
cmd/dagger/functions.go
cmd/dagger/module.go
core/integration/container_test.go
core/integration/engine_test.go
core/integration/future_test.go
core/integration/legacy_test.go
core/integration/module_test.go
core/integration/module_type_test.go
core/integration/remotecache_test.go
core/integration/services_test.go
sdk/go/.changes/unreleased/Changed-20241010-122112.yaml
sdk/go/dagger.gen.go

In go, enum values are top-level to the package (unlike in typescript/python/etc where they are members of the type itself). Because of this, it's very easily possible to clash - two different enum types might have the same value.
To prevent this clash, we should scope the enum value with the name of the enum it's from - this is pretty standard go practice, and should be familiar.
We keep the old consts around, but alias them to the new consts, and deprecate them (to remove in v0.14.0).

chore(go): deprecated unscoped enum values

---

engine/buildkit/resources/cpustat.go

fixes #8806 
tested locally by looking for the error message in the logs

fix(engine): correct cpu.stat path

---

.changes/unreleased/Fixed-20241103-221720.yaml
core/integration/git_test.go
engine/sources/gitdns/cli.go
engine/sources/gitdns/source.go

Bitbucket Cloud requires a specific auth format for Git operations using tokens, where the username must be 'x-token-auth'. This fixes token authentication for Bitbucket while maintaining compatibility with other Git providers like GitHub and GitLab, and Azure.
Our implementation for Bitbucket Cloud authentication is based on the [Repository Access Tokens Documentation](https://support.atlassian.com/bitbucket-cloud/docs/using-access-tokens/), which specifically covers Git operations. While Bitbucket's [HTTP Access Tokens Documentation](https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html) suggests using Bearer authentication for some cases, this appears to only be working for to REST API calls (upon personal tests).
For Git operations, the documentation …

core(gitdns-fix): ensure that gitdns support token support works with all Git server providers

---

engine/server/telemetry.go

Some users are still hitting 'database is locked' errors despite SQLite being tuned properly as far as I can tell. We really don't need transactions for this, so just remove them.

don't bother with transactions for client DB

---

core/integration/module_python_test.go
sdk/python/.changes/unreleased/Deprecated-20241103-124649.yaml
sdk/python/runtime/discovery.go
sdk/python/runtime/extension.go

[uv v0.4.23](https://github.com/astral-sh/uv/releases/tag/0.4.23) changed the settings for index urls:
```diff
-[tool.uv]
-index-url = "https://pypi.acme.org/simple"
+[[tool.uv.index]]
+url = "https://pypi.acme.org/simple"
+default = true
```
```diff
-[tool.uv]
-index-extra-url = "https://pypi.acme.org/simple"
+[[tool.uv.index]]
+url = "https://pypi.acme.org/simple"
```
\ping @ClifHouck

python: update uv index url config

---

.changes/unreleased/Breaking-20241008-181543.yaml
core/container.go
core/integration/legacy_test.go
core/schema/container.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

> [!WARNING]
>
> Only merge for v0.14.0!
I have no idea why we didn't remove these before - they've been deprecated since https://github.com/dagger/dagger/pull/6835. They should've gone when we got rid of `pipeline` as well, but looks like it got missed.
This is *technically* a breaking change, so maybe needs to wait till v0.14.0.

chore: remove `withFocus`/`withoutFocus`

---

sdk/php/composer.lock
sdk/php/dev/composer.lock

Our engine image scans started failing with:
```
{
"Target": "sdk/php/composer.lock",
"Class": "lang-pkgs",
"Type": "composer",
"Vulnerabilities": [
{
"VulnerabilityID": "CVE-2024-51736",
"PkgID": "symfony/process@v7.1.3",
"PkgName": "symfony/process",
"PkgIdentifier": {
"PURL": "pkg:composer/symfony/process@v7.1.3",
"UID": "b6476f8141579de1"
},
"InstalledVersion": "v7.1.3",
"FixedVersion": "5.3.0, 6.1.0, 5.0.0, 5.2.0, 5.4.46, 6.2.0, 6.3.0, 4.0.0, 5.1.0, 6.4.0, 7.1.0, 7.1.7, 3.0.0, 5.4.0, 6.4.14",
"Status": "fixed",
"Layer": {},
"PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-51736",
"DataSource": {
"ID": "php-security-advisories",
"Name": "PHP Security Advisories Database",
"URL": "https://github.com/FriendsOfPHP/security-advisories"
},
"Title": "CVE-2024-51736: Command execution …
```

php: update symfony/process to avoid CVE

---

docs/ARCHIVING.md
docs/archived_docs/assets/0.9/api/snippets/concepts/query1.gql
docs/archived_docs/assets/0.9/api/snippets/concepts/query2.gql
docs/archived_docs/assets/0.9/api/snippets/concepts/query3.gql
docs/archived_docs/assets/0.9/api/snippets/concepts/query4.gql
docs/archived_docs/assets/0.9/api/snippets/concepts/query5.gql
docs/archived_docs/assets/0.9/api/snippets/concepts/query6.gql
docs/archived_docs/assets/0.9/quickstart/snippets/build/index.mjs
docs/archived_docs/assets/0.9/quickstart/snippets/build/main.go
docs/archived_docs/assets/0.9/quickstart/snippets/build/main.py
docs/current_docs/api/playground.mdx
docs/src/scripts/replace-embeds.go

The 0.9.x docs archive includes "live" code snippets which rely on the API Playground. Once the Playground is decommissioned, those snippets will neither display nor execute in the 0.9.x docs archive. 
The solution we have agreed on is to replace the "live" code snippets with static code snippets in the 0.9.x docs archive, so that users browsing the docs archive are not impacted by this change. This PR provides the instructions, scripts and assets needed to reliably rebuild the 0.9 docs archive with the above change. Refer to ARCHIVING.md for full details.
This PR also includes a static information page noting the decommissioning and providing alternative resources. All future API Playground requests may be redirected to this page. The URL of this static information page will be …

docs: Add instructions and assets for rebuilding the 0.9 docs archive without embeds

---

docs/src/scripts/replace-embeds.go

@marcosnils [noticed this and fixed in a separate PR](https://github.com/dagger/dagger/pull/8568/commits/31a0f52fadda73feb139aa38b32da158ef7f0343), but want it sooner than we are merging that one so splitting out to its own PR

fix replace-embeds golangci-lint issues

---

cmd/dagger/shell.go

"The '⋈' symbol, known as the bowtie, has deep roots in relational databases and set theory, where it denotes a join operation. This makes it especially fitting for a DAG environment, as it suggests the idea of dependencies, intersections, and points where separate paths or data sets come together."

shell: change prompt to '⋈'

---

core/schema/host.go
engine/buildkit/resources/cpustat.go

I noticed a few easy fix issues while perusing engine logs from a test run earlier today. They technically aren't related but combining them into one PR for convenience.
--- 
[engine: ignore missing cpu.stat/cpu.pressure files](https://github.com/dagger/dagger/commit/cca2f47d4427108494d391bbaef63c51d8822c64)
We already ignored missing cgroup files for io.stat/io.pressure but
missed that for cpu files. These files can be missing if the engine
doesn't support cgroups for execs and result in a ton of useless log
noise in that case.
---
[engine: fix cache volume re-use when sourced from builtinContainer](https://github.com/dagger/dagger/commit/adc5b6a5c4facc0e480abf1750086eba62ccd07b)
I noticed that there were a bunch of engine logs about not being …

Fix cgroup error logs + cache volume re-use in go SDK

---

.dagger/test.go
core/integration/container_test.go
core/integration/engine_test.go
core/integration/gitcredential_test.go
core/integration/module_call_test.go
core/integration/module_terminal_test.go
core/integration/module_test.go
core/integration/module_up_test.go

Was getting annoyed with digging through tons of test output today, couple quick improvements here
---
[tests: remove --debug flag from integ test cli invocations](https://github.com/dagger/dagger/commit/7eefd6273fc1f7cd079aae509684aa7440aeb758)
This increases verbosity quite a bit but doesn't really help debug the
vast majority of the time. If ever needed for debugging it's also very
easy to add locally, so makes sense to not do by default.
---
[tests: disable go test verbosity by default](https://github.com/dagger/dagger/commit/0d29f6343fd98ad9984edd177a860d763407f955)
the -v flag on go test results in all output being printed, whereas the
default behavior only shows output when a test fails.
The majority of the time we only care about output …

tests: reduce excessive verbosity

---

dagql/idtui/frontend.go
go.mod

this PR makes the tui print human-readable byte and duration values. 
any suggestions on how to manually test the pressure duration printing? I never have these print on `dagger call check`.
bytes, however, are confirmed working and looking good: `exec sh -c git checkout -q $(git rev-parse HEAD) 0.4s | Disk Read Bytes: 45 MB | Disk Write Bytes: 12 kB`

feat(engine): make metrics in ui more readable

---

cmd/dagger/call.go
cmd/dagger/cloud.go
cmd/dagger/functions.go
cmd/dagger/main.go
cmd/dagger/module.go
cmd/dagger/shell.go
cmd/dagger/typedefs.graphql
core/integration/module_shell_test.go

Closes https://github.com/dagger/dagger/issues/8831
**Main object + Constructor**
```console
> .doc
```
**Return type of a function**
```console
> test | .doc
```
**More details on a function, if return type is an object**
```console
> test | .doc unit
```
**Same with core functions, this documents `Container`**
```console
> .container | .doc
```
**For the arguments to `Query.container`, use `.help`**
```console
> .help .container
```
```console
> .doc
TYPE: OBJECT
DaggerDev - A dev environment for the DaggerDev Engine
CONSTRUCTOR
.config [options]
OPTIONAL ARGUMENTS
--source Directory    (default: "/")
--docker-cfg Secret
AVAILABLE FUNCTIONS
version               -
tag                   -
mod-codegen           When set, module codegen is automatically applied when retrieving the Dagger …
```

shell: add `.doc` builtin command

---

cmd/dagger/call.go
cmd/dagger/functions.go
cmd/dagger/shell.go
core/integration/module_shell_test.go

Closes https://github.com/dagger/dagger/issues/8890
Fixes https://github.com/dagger/dagger/issues/8542
This is essential to be able to run `dagger shell` without a module, for example to run core functions.

feat(shell): make module loading optional

---

docs/current_docs/configuration/cache.mdx

Adds docs for https://github.com/dagger/dagger/pull/8725 - somehow I missed doing this, even after adding the `needs/docs` label.

docs: add info on new cache policy

---

sdk/elixir/.changes/unreleased/Added-20241109-103555.yaml
sdk/elixir/lib/dagger/core/graphql_client.ex
sdk/elixir/lib/dagger/core/graphql_client/httpc.ex

This revive #6962 
In this changeset, add opentelemetry to setup `TRACEPARENT` from env variable to the current context and injecting it HTTP headers once request starting.
Since this support, it change the TUI from returning `Void` to correct type and can show step details inside a function correctly.
Before: the output from release 0.13.7:
```
✔ Potato.containerEcho(stringArg: "hello"): Container! 3.9s
┃ ==> nimble_options
┃ Compiling 3 files (.ex)
┃ Generated nimble_options app
┃ ==> jason
┃ Compiling 10 files (.ex)
┃ Generated jason app
┃ ==> dagger
┃ Compiling 106 files (.ex)
┃ Generated dagger app
┃ ==> potato
┃ Compiling 1 file (.ex)
┃ Generated potato app
✔ exec mix cmd --cd /src/sdk/elixir/potato/potato mix dagger.entrypoint.invoke Potato 3.9s | CPU Pressure (some): 128886µs | …
```

feat(sdk/elixir): support TRACEPARENT

---

.dagger/engine.go
.dagger/go.mod
.dagger/main.go
.github/actions/call/action.yml
.github/dagger.json
.github/main.go
.github/workflows/daggerverse-preview.gen.yml
.github/workflows/docs.gen.yml
.github/workflows/engine-and-cli-split.yml
.github/workflows/engine-and-cli.yml
.github/workflows/github.gen.yml
.github/workflows/helm-test.yml
.github/workflows/publish.yml
.github/workflows/sdk-rust-publish.yml
.github/workflows/sdks.gen.yml
RELEASING.md
core/integration/module_test.go
dagger.json
go.mod

Just autogenerated stuff here. 
FTR, hit lots of things big and small but will split them out to follow ups so this isn't blocked too long:
- daggerverse preview never ran 
- this link is broken in ts autogenerated release notes https://docs.dagger.io/reference/typescript/modules/api_client_gen
- https://github.com/dagger/dagger/pull/8901
- Fix dynamic optional error hit during SDK publishes
- Fix python publish error (being handled by Helder)
- Updates to RELEASING.md needed
- updating `.changes/.next` is in wrong order (shouldbe included in a commit that's pushed)
- "Open a PR with the title Improve Releasing during $ENGINE_VERSION" is a duplicate of previous instruction, seems like a typo

chore: bump internal tooling to v0.14.0

---

core/container.go
core/integration/container_test.go
core/integration/images.go
core/schema/container.go

This test started failing out of band in our CI on amd64 hosts.
Justin noticed that the published arm64v8/alpine image had changed from a single manifest to a multiplatform oci index w/ a single platform-specific manifest.
This broke the test because previously in the "single manifest" case the platform we tried to resolve the image with was completely ignored. After switching to the oci index, the platform actually mattered.
We were defaulting the platform to the host's platform when resolving the image, but this test purposely attempts to pull an image for a different platform.
After some discussion we decided erroring in the case is expected and the simplest behavior. If users want to pull images that don't match their host's platform, they need to explicitly request that platform in …

engine: account for oci index in TestFromImagePlatform

---

.dagger/sdk_java.go
sdk/java/pom.xml

`engine-scan` started failing with a transitive dependency, so hopefully this mass bump fixes it

sdk/java: add bump-deps, bump deps to fix engine scan

---

engine/buildkit/cleanup.go
engine/buildkit/executor_spec.go

Fixes https://github.com/dagger/dagger/issues/8934
I haven't tracked down why, but it appears that sometimes in our test
workflows the "shutdown otel proxy" cleanup step takes over 10s, hits
its timeout and then causes the exec to fail.
It shouldn't take that long, but in the meantime there's no reason for
this to be fatal to the exec. The error is now just logged.
---
@vito let me know what you think of this workaround. I'm a bit mystified and concerned why shutting down the otel proxy server is taking >10s sometimes. The only recent change I can think of that's plausibly related is getting rid of the transactions, which I suppose could *somehow* be causing the http handlers take longer? Maybe? Pretty shot in the dark guess.
But for now it at least stops this from breaking user execs.

engine: make otel proxy shutdown error non-fatal

---

core/integration/sequential_test.go
core/integration/services_test.go
engine/buildkit/executor_spec.go

attempt at fixing #8585. 
This PR sets a host name for every netns to avoid buildkits netns pooling, which leaks changes to netnses across the pool. This is only relevant to insecure privileged containers, but can lead to very unpredictable network behavior when users modify the network namespace. 
This fix does come with a perf hit, at least on macos. See below for benchmarks. The perf hit has been mitigated by only avoiding pooling for privileged containers.

fix(engine): isolate netnses so insecure-root-added iptables rules dont leak through the bk cni pool [DEV-4584]

---

_dagger_on_depot_cli_provisioned.yml
_dagger_on_depot_pre-provisioned_with_cache.yml
alternative-ci-runners.yml

The workflow runs a good mix of jobs, including jobs that:
- take more than 20 minutes to run
- finish in a few minutes and cache well
- don't cache at all
- require a handful of vCPUs
- require 32 vCPUs
- put a lot of disk I/O pressure
Tests were performed on a temporary repo since new workflows cannot run until they exist on the `main` branch. More details in the PR.
This change is an alternative to:
- https://github.com/dagger/dagger/pull/8792
---

ci: Add nightly workflow on Depot runners

---

.dagger/README.md
.dagger/main.go

steps I missed in #8652, bundled all together.
added a top level dev function "generate" intended to all code generation in one go. 
as an aside: writing this with the heading "GraphQL schema changes" immediately gave me the urge to write the typical warnings regarding backwards-incompatible changes to graphql schemas that you've got to drumbeat in a more typical SaaS graphql deployment (nullables can't be made non-nullable, renames must be duplicated and deprecated, etc) but it occurs to me that maybe our release structure is less sensitive to backwards incompatibility? how concerned are we with breaking clients via engine api changes?

dev: add blurb for necessary steps following GraphQL schema changes

---

.changes/unreleased/Fixed-20241112-151649.yaml
cmd/dagger/flags.go

https://github.com/dagger/dagger/pull/8782#discussion_r1828846725 spotted an issue where ignore patterns where not applied when pulling a directory from git.
This PR fixes that issue.
Results now:
```shell
dagger call copy-directory-with-exclusions --source=https://github.com/dagger/dagger#main directory --path=/src entries
.changes
.dagger
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
RELEASING.md
core
dagql
docs
hack
helm
modules
sdk
```

fix: use ignore pattern when pulling dir from git

---

.github/workflows/trace-workflows.yml

We had some redundant ones & were missing other important ones such as SDKs & the new Alternative CI Runners.

ci: Update the workflows that we trace

---

install.ps1
install.sh

```
Usage: ./install.sh
Install:
./install.sh
Install to <path/to/dir>:
BIN_DIR=<path/to/dir> ./install.sh
Install specified version <vX.Y.Z>:
DAGGER_VERSION=<vX.Y.Z> ./install.sh
Install latest nightly build:
DAGGER_COMMIT=head ./install.sh
Install specified nightly build <commit sha>:
DAGGER_COMMIT=<commit sha> ./install.sh
```
These options need to be documented - since I keep forgetting what's valid/what's not.

chore: add help for install.sh

---

.changes/unreleased/Added-20241114-123823.yaml
dagql/idtui/frontend.go
dagql/idtui/golden_test.go
engine/buildkit/executor_spec.go
engine/buildkit/resources/netstat.go
engine/buildkit/resources/sampler.go
sdk/go/telemetry/metrics.go

does what it says on the tin, using BK's network namespace "Sample" function.
note this prints % dropped, not % loss. packet loss is harder to instrument, especially on the rx side. if we feel the need, we could probably get stats about tcp retransmissions, but that is out-of-scope here.

feat(engine): telemetry for netns bytes rx and tx, plus packet drops

---

sdk/php/.changes/unreleased/Added-20241109-103911.yaml
sdk/php/src/Connection.php

Inject `Traceparent` headers into client when `TRACEPARENT` env variable is presents.
Before:
```
✔ Potato.containerEcho(stringArg: "hello"): Container! 1.2s
✔ exec /src/sdk/php/potato/entrypoint.php 1.1s | CPU Pressure (some): 163µs | CPU Pressure (full): 148µs
✔ Void.stdout: String! 0.0s
✔ cache request: pull docker.io/library/alpine:latest@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d 0.0s
✔ load cache: exec echo hello 0.0s
```
After:
```
✔ Potato.containerEcho(stringArg: "hello"): Container! 2.3s
✔ exec /src/sdk/php/potato/entrypoint.php 2.2s | CPU Pressure (some): 210µs | CPU Pressure (full): 209µs
✔ Container.from(address: "alpine:latest"): Container! 2.0s
✔ resolving docker.io/library/alpine:latest 2.0s
✘ remotes.docker.resolver.HTTPRequest 0.8s
✘ HTTP …
```

feat(sdk/php): support TRACEPARENT

---

.dagger/sdk_elixir.go
dagger.json
sdk/elixir/dev/.gitattributes
sdk/elixir/dev/.gitignore
sdk/elixir/dev/dagger.json
sdk/elixir/dev/elixir_sdk_dev/.formatter.exs
sdk/elixir/dev/elixir_sdk_dev/.gitignore
sdk/elixir/dev/elixir_sdk_dev/README.md
sdk/elixir/dev/elixir_sdk_dev/lib/elixir_sdk_dev.ex
sdk/elixir/dev/elixir_sdk_dev/mix.exs
sdk/elixir/dev/elixir_sdk_dev/mix.lock
sdk/elixir/dev/elixir_sdk_dev/test/elixir_sdk_dev_test.exs
sdk/elixir/dev/elixir_sdk_dev/test/test_helper.exs

Add a dev module to dogfood the Elixir SDK by implements `test` function and convert `ElixirSDK` to `test` function instead.
The `test` function also reduce complexity by removing test matrix and use same image as runtime uses.

feat(sdk/elixir): introduce elixir dev module

---

core/schema/module.go

This fix comes from accidentally add a leading slash in the generated paths during fix the Elixir issue like this:
```go
modName := "potato" // assume the name is this.
dag.GeneratedCode(directory).
WithVCSGeneratedPaths([]string{"/src/"+modName+"/lib/mix/tasks/dagger.invoke.ex"})
```
The `.gitattributes` produces as:
```
//src/potato/...
```
It's happens because the API prepending it without detecting the path that user given. This fixes by dropping it if the path already contained.

fix(core): drop leading slash from paths in withVCSGeneratedPaths API

---

engine/buildkit/linux_namespace.go
engine/buildkit/unimplemented_namespace.go
engine/sources/gitdns/source_linux.go
engine/sources/gitdns/source_unimplemented.go

see https://github.com/dagger/dagger/issues/8956 for error logs. this PR makes it so we can build our test packages (at least tui and core/integration) on macOS, by adding panic(unimplemented) impls hidden behind conditional build directives.

fix(test): make go test work on macOS

---

.changes/unreleased/Fixed-20241113-221407.yaml
core/integration/legacy_test.go
core/integration/module_terminal_test.go
engine/buildkit/executor_spec.go

While debugging an unrelated PR I realized that our terminal tests were not working as expected and that the Directory.terminal feature just didn't work at all:
---
[tests: fix terminal tests not asserting as expected](https://github.com/dagger/dagger/commit/a708114f344e0d10e75d600028d6956fa5e7ddf0)
Our terminal tests were not actually working how we thought they were.
Many of them were not waiting for prompts and instead just matching on
strings right away, which ended up including all the progress output
before the terminal was opened.
This broke a few of them since the string they were expecting happened
to also show up in the progress output, which isn't what we actually
wanted to assert on.
This updates the tests to correctly wait for prompts (doing some
terminal escape sequence …

Fix broken terminal tests and broken Directory.terminal feature

---

docs/current_docs/quickstart/index.mdx

Maybe this is obvious, but the prerequisites don't actually mention that the container runtime should also be running.

Mention container runtime should be running in quickstart

---

.dagger/sdk_python.go
sdk/python/dev/src/main/main.py
sdk/python/pyproject.toml

But also:
- Added tests for Python 3.13
- Offloaded leftovers in `.dagger/sdk_python.go` to `sdk/python/dev`
- Updated library package metadata (license is not necessary since the build backend picks it up automatically from the `sdk/python/LICENSE` file

python: replace hatch with uv in tooling

---

version/git.go

The dirty detection wasn't working with the pattern `:(exclude)**/.dagger` - we need to also exclude all subpaths, i.e. `:(exclude)**/.dagger/**`.`
This appeared when adding a module into `dagger/cmd` in #8870, and the pattern detected that the module file contents were deleted, and so even fresh commits would be marked as dirty.

ci: fix dirty detection by excluding subpaths as well

---

cmd/dagger/call.go
cmd/dagger/functions.go
cmd/dagger/module.go
cmd/dagger/shell.go
core/integration/module_shell_test.go

Closes https://github.com/dagger/dagger/issues/8932
Since we can now load different modules within the same session, the prompt now shows the default module (global), if loaded:
In order to be easier to spot, errors are now shown in red:
Thanks to @cwlbraa for this idea, the prompt symbol (⋈) is also turned red if the last command errored. It's green otherwise.
- A few core functions like `.cache-volume` weren't showing, that's now fixed
- Module description is now shown when using `.doc` on the main object, and constructor output improved
- A non existing function won't fallback to core anymore since core functions are readily available with the `.` prefix

feat(shell): load module dynamically

---

.github/workflows/alternative-ci-runners.yml

They have been failing days in a row since they require at least 2x the CPU resources that are made available by default. We could bump the timeout, but that will only result in higher infra costs and not provide much value - we already know about the limitations & current behaviour.
We are also only keeping pipelines for a subset of SDKs. The goal is to have decent coverage, not be exhaustive.
**Also** run the workflow twice so that we test the caching efficiency.

ci(alt nightly): Disable our heaviest pipelines on alternative runners & run twice daily

---

core/integration/module_type_test.go
core/json.go
core/modtypes.go
core/platform.go
core/typedef.go
core/void.go
dagql/builtins.go
dagql/objects.go
dagql/types.go

Follow-up to https://github.com/dagger/dagger/pull/8682, and starts to do some of #6749.
`null` should be allowed as an argument to optional args - but nowhere else. When it is provided, it should indicate that the default value **should not be used**.
Also, `null` (and `true` and `false`) are now never valid values for enums - we never allow decoding these.

fix: handle explicit `null`s, and stop allowing weird overlapped enums

---

.dagger/test.go

with new reserved keywords, including verbose, passing -vvv on the command line will give:
```
error: parse selections: parse field "specific": init arg "verbose" value as dagql.DynamicOptional (Boolean) using dagql.DynamicOptional: cannot create Boolean from int64
```
this changes the dagger call test boolean variable for verbose test output (passed to go test) to be called "testVerbose" instead to avoid this collision.
originally noticed and reported in discord [here](https://discord.com/channels/707636530424053791/1003718839739105300/1306399688810827817)

fix(test): -vvv when running dagger call test commands

---

.changes/unreleased/Added-20241026-123323.yaml
cmd/dagger/main.go
cmd/dagger/module.go
core/integration/module_cli_test.go
core/modulesource.go
core/schema/git_test.go
core/schema/module.go
core/schema/modulesource.go
docs/current_docs/reference/cli.mdx
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/module_source.ex
sdk/go/dagger.gen.go
sdk/php/generated/ModuleSource.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/api/client.gen.ts

add a `dagger uninstall` command. Following test scenarios are covered:
-  ✅  if local dependency is not available in dagger.json. it should error out. works
-  ✅  local dependency is not used - works.
-  ⚠️ local dependency is used - (The code gives compile error as the dependency usage is still there in module).
-  ✅ git dependency is not used - it should error out. works
-  ⚠️ git dependency is used - (The code gives compile error as the dependency usage is still there in module)
-  ✅ git dependency uninstall by git repo url + version - works
-  ✅ git dependency uninstall by git repo url only - works
-  ✅  git dependency uninstall by name - works
-  ✅ dependency source does not exist (git or local) e.g. folder removed or git repo deleted - What should be the expected behavior here?

feat(cli): add dagger uninstall command

---

.changes/unreleased/Fixed-20241120-160241.yaml
core/integration/module_terminal_test.go
core/terminal.go
engine/buildkit/client.go
engine/buildkit/ref.go

Fixes https://github.com/dagger/dagger/issues/8554
While running some tests locally for the (unrelated) filesync PR I accidentally stumbled on a set of tests to run that coincidentally repro'd the flake in #8554 pretty consistently locally:
```
./hack/with-dev go test -v -run='TestModule/TestDaggerTerminal|TestModule/TestDaggerUp' -count=10 -parallel=8 ./core/integration/
```
I would hit the flake where the `on_failure` test hung after 3-4 counts pretty consistently. The set of tests most likely just happens to tweak timing on my machine in just the right way that the race conditions it was caused by would get triggered more often.
There were multiple problems from the test case down through the engine, described in the commit below.
With this fix in place I can't repro the flake locally …

engine: fix goroutine leaks + deadlock in terminal

---

.github/workflows/_dagger_on_depot_local_engine.yml
.github/workflows/_dagger_on_depot_remote_engine.yml
.github/workflows/alternative-ci-runners.yml

Also:
- fix schedule syntax (it did not trigger as expected)
- remove all jobs which are unlikely to run on a regular basis
- increase runner size for jobs which timed out in the last run
Outcome:
The failing test was captured in:
- https://github.com/dagger/dagger/issues/9023
---
Follow-up to the session with @jacobwgillespie

ci(alt runners): Use common terminology

---

cmd/dagger/shell.go

More functions popped up since this was first introduced. To avoid new functions appearing here that we don't want to, makes more sense to include the ones we do want rather than exclude.

shell: limit core functions in `.help`

---

.changes/unreleased/Fixed-20241121-211357.yaml
core/integration/module_terminal_test.go
engine/buildkit/ref.go

Reported in discord here: https://discord.com/channels/707636530424053791/1294027305231974480/1309270204806725664
The code for interactive debug containers was skipping over any mounts that weren't "normal layers" (cache mounts, tmpfs, etc.). Now it correctly handles those.

engine: fix cache volumes not being mounted into debug containers

---

.dagger/sdk_elixir.go
sdk/elixir/dev/elixir_sdk_dev/lib/elixir_sdk_dev.ex

~⚠️ Needs #8962~
Implements `lint` function to `elixir-sdk-dev` and uses it in
`ElixirSDK` main module.

feat(sdk/elixir): implements lint to elixir-sdk-dev 

---

.dagger/cli.go
.github/workflows/publish.yml
.goreleaser.nightly.yml

This invalidates the cloudfront cache for `install.sh` and `install.ps1` after publishing.
Also, we change some secrets to vars, while we're here.

ci: invalidate install scripts cache after publishing

---

.changes/unreleased/Fixed-20241121-155915.yaml
core/container.go

Follow-up to https://github.com/dagger/dagger/pull/8466.
Some tools (like `git checkout`) return valid 128 exit codes.
We only exclude the range 128+<n>, because this is the exit code for a process that was terminated by signal(<n>). 0 isn't a valid signal number (they all start from 1). So there's no reason to not handle 128.

fix: allow Container.withExec to intercept exit code 128

---

engine/buildkit/executor_spec.go

This is printing strings upwards of 200kb in some scenarios, which causes some log systems to choke, leading to a SIGPIPE and the engine dying.

silence incredibly verbose call ID from logs

---

cmd/dagger/engine.go
cmd/dagger/main.go
dagql/dagui/db.go
dagql/idtui/golden_test.go

This allows an operator to set arbitrary resource attributes for annotating traces, using the standard [`OTEL_RESOURCE_ATTRIBUTES`](https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_resource_attributes) env.

feat(cli): detect OTel resource attributes

---

cmd/codegen/generator/go/templates/src/_dagger.gen.go/module.go.tmpl
cmd/dagger/main.go
cmd/engine/telemetry.go
dagql/idtui/golden_test.go
sdk/go/telemetry/init.go

Fixes breakage on `main` in telemetry tests 🙏
Tests failed because now we use the OTel detectors (via #9054), but we haven't actually been using the appropriate version of semconv for the version of OTel we're using, which OTel whines about, even though they're both semantically v1.x.x. This whole thing is pretty annoying for a package that's meant to just be a bunch of canonical names for common attributes. But, that's life.

bump seconv to v1.25.0 to match otel v1.27.0

---

core/schema/modulesource.go

Instead, use `telemetry.Internal`.
See @vito's comment here: https://github.com/dagger/dagger/pull/8818#discussion_r1861051922
`parseRefString` is indeed showing up in weird places, and is noisy :cry:

chore: avoid direct use of `trace.SpanKindInternal`

---

install.sh

Remove the duplicate functions `os_uname` and `os_arch` on lines 258 and 268, which are duplicated with lines 65 and 74.
Fixes #9077

fix(install.sh): remove duplicate functions

---

.dagger/sdk_typescript.go
core/integration/module_typescript_test.go
sdk/typescript/.changes/unreleased/Changed-20241129-174122.yaml
sdk/typescript/dev/node/src/index.ts
sdk/typescript/runtime/main.go

Node.js 18 is in maintenance mode, Node.js 22 is the current LTS. Updating the default version to `lts-alpine` ensures that the current (active) LTS is used by default.

feat: use lts-alpine as the default node tag

---

cmd/dagger/engine.go
engine/telemetry/cloud.go
go.mod

working now with https://github.com/dagger/dagger.io/pull/4071 merged!
I did also drive through a refactor to extract a refreshingSpanExporter generic base struct, but it's honestly worse than the existing copy-pasta implementation because of the way token auth configuration leverages composition, so it's not included here.

feat(cli): enable metrics forwarding to dagger cloud

---

core/integration/module_test.go
core/object.go
engine/server/session.go

intended to fix #8935, turns out this was a problem with constructor purity

fix(engine): secrets created inside module constructor fail on repeated accesses

---

.dagger/docker.go

Adds a utility to easily start a dev engine without needing `./hack/dev`:
```
$ dagger call engine load-to-docker --name dagger-engine.dev --docker /var/run/docker.sock start
```

ci: allow exporting engine directly to the host

---

.changes/unreleased/Added-20241207-013627.yaml
.dagger/docker.go
.dagger/mage/engine.go
core/modules/config.go
docs/static/reference/dagger.schema.json
engine/client/drivers/docker.go

Made a mistake in #8801. While `pin` is required on git sources, it's not on local sources.
So we end up with https://github.com/dagger/dagger/blob/e6bbc047dd19692eb9d6d65cb20d2c53853078b2/dagger.json#L5-L10
with an empty `pin` field, which is kinda meh.
So we should relax the `pin` output, and omit it if it's empty.

chore: omit empty dependency pin in dagger.json

---

core/integration/module_python_test.go
sdk/python/.changes/unreleased/Breaking-20241209-120336.yaml
sdk/python/runtime/discovery.go
sdk/python/runtime/extension.go

This removes a deprecation from [v0.14.0](https://github.com/dagger/dagger/releases?q=tag%3Asdk%2Fpython%2Fv0):
- https://github.com/dagger/dagger/pull/8772
```diff
-[tool.uv]
-index-url = "https://pypi.acme.org/simple"
+[[tool.uv.index]]
+url = "https://pypi.acme.org/simple"
+default = true
```
```diff
-[tool.uv]
-index-extra-url = "https://pypi.acme.org/simple"
+[[tool.uv.index]]
+url = "https://pypi.acme.org/simple"
```
\ping @ClifHouck

python: remove deprecated index-url in tool.uv

---

.github/workflows/engine-and-cli.yml
core/integration/container_test.go
core/integration/provision_test.go
engine/client/drivers/docker.go

Follow-up to #9130.
There's a few issues in the merged PR:
- ~~Committed a built binary~~ (fixed by rewriting git history)
- Hardcoded string in too many places
- Overly complex logic
- Unnecessary logs
- Manual string comparisons instead of `strconv.ParseBool`
- No tests
I've fixed all these, and simplified the code. I've also renamed the variable to `_EXPERIMENTAL_DAGGER_LEAVE_OLD_ENGINE`, since I think this is more inline with other variables that we use in dagger. But happy to leave it as is.

Follow-up from changes to `DAGGER_LEAVE_OLD_ENGINE`

---

.github/workflows/publish.yml
RELEASING.md
modules/daggerverse/dagger.json
modules/daggerverse/main.go

Upgrades Dagger version for Daggerverse in:
- GitHub workflows
- Daggerverse modules
- Daggerverse app
- Infra config
It also deploys a Daggerverse preview environment with a development version of Dagger (this implies the version that we are upgrading to).
This now runs automatically part of the publish workflow. When no `--from` is specified, it looks inside the `.changes` directory and picks the one but last version (n-1).
Updated the publish workflow runs-on to only use our own runners. This workflow is never meant to run in forks.
https://github.com/user-attachments/assets/615b688c-65b9-4eb2-91f1-eb4d74a84e48

ci: Bump Dagger version in Daggerverse after publishing a new release

---

cmd/dagger/call.go
cmd/dagger/functions.go
cmd/dagger/modconf.graphql
cmd/dagger/module.go
cmd/dagger/shell.go
core/integration/module_shell_test.go
core/schema/module.go
core/schema/modulesource.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/module_source.ex
sdk/go/dagger.gen.go
sdk/php/generated/ModuleSource.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

Implements first part of https://github.com/dagger/dagger/issues/9035
Fixes https://github.com/dagger/dagger/issues/9129
- documentation for a module and its constructor/entrypoint:
```diff
-.load <module> | .doc
+.doc <module>
```
- documentation for a module’s main object:
```diff
-.load <module> | .config <required arguments>... | .doc
+<module> <required arguments>... | .doc
```
- set a module as the default for current session:
```diff
-.load <module> | .use
+.use <module>
```
- execute a stdlib function (disambiguated)
```diff
-.version
+.stdlib | version
```
- execute any core function
```diff
-.default-platform
-.core default-platform
+.core | default-platform
```
- https://github.com/dagger/dagger/issues/8969
- https://github.com/dagger/dagger/issues/9019
- …

shell: reimplement module loading and execution according to new model

---

dagql/idtui/testdata/TestTelemetry/TestGolden/cached-execs
dagql/idtui/testdata/TestTelemetry/TestGolden/custom-span
dagql/idtui/testdata/TestTelemetry/TestGolden/docker-build
dagql/idtui/testdata/TestTelemetry/TestGolden/docker-build-fail
dagql/idtui/testdata/TestTelemetry/TestGolden/encapsulate
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-effect
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-log
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-log-native
dagql/idtui/testdata/TestTelemetry/TestGolden/hello-world
dagql/idtui/testdata/TestTelemetry/TestGolden/pending
dagql/idtui/testdata/TestTelemetry/TestGolden/use-cached-exec-service
dagql/idtui/testdata/TestTelemetry/TestGolden/use-exec-service
dagql/idtui/testdata/TestTelemetry/TestGolden/use-no-exec-service
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/broken/broken
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/python/custom-span
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/python/pending
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/typescript/custom-span
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/typescript/pending

Should have been included in https://github.com/dagger/dagger/pull/9097.
Will fix the failing `test-everything-else` job on `main`.

chore: update telemetry golden tests

---

.dagger/mage/engine.go
.dagger/main.go
core/integration/suite_test.go

for profiling and fast dev loops, it's often useful to run tests on your host machine aimed at a `./hack/dev`-built engine. 
```
./hack/dev go test -count=1 -v -run TestModule/TestLots ./core/integration
```
on MacOS, many tests won't run locally because we often upload a local dagger CLI binary as part of the test. 
this PR teaches dev-export to copy the engine container's linux binary to ./bin/dagger-linux, then wires that path out through mage/engine.go so it can be consumed by ./core/integration/suite_test.go as the desired binary to upload to test-created containers.
this _does not_ make all or nearly all the tests pass successfully when running on macOS. many tests still rely on running inside of dagger, as @vito noted in `./hack/most-tests`. re-cataloguing which tests those are …

enable more integration tests to run on raw macOS

---

.changes/unreleased/Fixed-20241211-195735.yaml
dagql/dagui/db.go
dagql/dagui/opts.go
dagql/dagui/spans.go
dagql/idtui/frontend.go

Some of the recent changes to telemetry span handling resulted in most metrics not showing up in the TUI (other than those for services).
This fixes the display by tracking+displaying metrics based on their associated Call ID digest, which avoids the relative complication of all the various spans we create in different parts of the engine and associated logic on which are actually rendered in the TUI.

fix metrics display via tracking by call ID digest

---

docs/current_docs/configuration/cache.mdx

[discussed in discord](https://discord.com/channels/707636530424053791/1003718839739105300/1316174724744871977), these commands are otherwise undocumented and `dagger core engine local-cache prune` can be useful for performance testing.

docs: add cli instructions to cache documentation

---

.github/workflows/publish.yml

I *thought* I updated this in https://github.com/dagger/dagger/pull/9175.
Apparently not. This updates the `publish.yml` workflow as well to include this.

ci: call publish-metadata in publish workflow

---

cmd/dagger/functions.go
cmd/dagger/shell.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/9120
Included a refactor to remove some duplication. Simplified usage of `handleResponse` because:
- The shell doesn't use the `-o,--output` flag convenience
- Adding the fake `_type` field when result is an object is not necessary since you can add `... | .doc` to get the type

shell: expand state arguments in commands

---

cmd/dagger/shell.go
cmd/dagger/shell_completion.go
cmd/dagger/shell_completion_test.go

This PR introduces support for shell autocompletion. We allow auto-completing module commands, chained commands, builtins, arg flags, etc.
<a href="https://asciinema.org/a/WYvfoe6VCH66c8Nlb3YHzuuZ6" target="_blank"><img src="https://asciinema.org/a/WYvfoe6VCH66c8Nlb3YHzuuZ6.svg" /></a>
There's still some important functionality missing, but this is a good first pass. Some things we should maybe come back and do:
- We should allow autocompletion of args, such as `File`s and `Directory`s to paths on the host, and autocompletion of enums to their list of allowed values
- We should allow partial parse tree - so that we can handle cases like `.container | \t` to auto-complete functions on the container type. Currently, we need to have at least one character inserted.
---
TODO:
- This probably …

feat: shell autocomplete

---

docs/current_docs/integrations/snippets/github-ghcr.yml
docs/current_docs/integrations/snippets/github-hello.yml
docs/current_docs/integrations/snippets/github-test-build.yml
docs/current_docs/integrations/snippets/google-cloud-run/main.yml

following RELEASING.md, this looks like it might've been skipped previously.

docs: bump dagger-for-github to v7

---

core/directory.go
core/modulesource.go
engine/sources/httpdns/source.go
modules/golangci/lint-config.yml

Happened across an instance of incorrectly returning nil when err was set while working on stuff. This fixes that and enables the nilerr linter for catching these things, which revealed another occurence.
As far as I can tell these haven't been actively hurting us most likely (the error cases are extremely unlikely to happen) but worth preventing these spooky typos from happening again going forward.

fix "return nil on err" cases and enable related linter

---

docs/current_docs/configuration/custom-runner.mdx
docs/current_docs/configuration/engine.mdx
docs/current_docs/faq.mdx
docs/netlify.toml

This is branched off https://github.com/dagger/dagger/pull/9022 so should be merged after.

docs: Move content on rootless mode from operator manual

---

docs/current_docs/integrations/snippets/argo-workflow.yaml

`dagger call` works as expected with 0.15.1.
Closes https://linear.app/dagger/issue/DOCS-388/argo-workflows-integration-page-update

docs: Update dagger version in Argo Workflows snippet

---

docs/current_docs/integrations/snippets/Jenkinsfile

`dagger call` works as expected with 0.15.1.
closes https://linear.app/dagger/issue/DOCS-387/jenkins-integration-page-update

docs: Update dagger version in Jenkins snippet

---

sdk/elixir/test/dagger/client_test.exs

* https://github.com/aquasecurity/trivy-operator/issues/933
* Tests failing randomly as well, see if this fixes

elixir tests: update alpine version to 3.20.2 due to CVE

---

cmd/dagger/shell.go
core/integration/module_shell_test.go

This allows saving a pipeline in a variable and reuse it later:
```console
⋈ CTR=$(container | from alpine)
⋈ $CTR | with-exec echo foobar | stdout
foobar
```
Previously you had to echo the output yourself (with the added caveat that interpreter builtins like `echo`  are prefixed with `..` to avoid a conflict with function names):
```console
⋈ CTR=$(container | from alpine)
⋈ ..echo $CTR | with-exec echo foobar | stdout
foobar
```
Or you can define a function for a more natural usage:
```console
⋈ ctr() { container | from alpine; }
⋈ ctr | with-exec echo foobar | stdout
foobar
```

shell: support state result

---

docs/current_docs/configuration/engine.mdx

Follow-up to https://github.com/dagger/dagger/pull/9022
This makes the switch to a different tab global across the page, similar to how we do languages right now.

docs: use groups for engine config mechanisms

---

sdk/elixir/dev/dagger.json
sdk/elixir/dev/elixir_sdk_dev/lib/elixir_sdk_dev.ex
sdk/elixir/dev/elixir_sdk_dev/mix.exs
sdk/elixir/runtime/main.go

This is follow-ups changeset comment in https://github.com/dagger/dagger/pull/8962
Changes to `dev` module:
* Bump image to Elixir 1.17.2 with OTP 27.2.
* Add a function named `sync-image` to sync between dev and runtime so we can change image only in dev module then it'll modify automatically after calling this function.
* Bump engineVersion to the latest version (0.15.1).
* Run mix format.
Changes to `runtime` modules:
* Bump image to Elixir 1.17.2 with OTP 27.2 by using `sync-image` from `dev` module.

feat(sdk/elixir): bump dev & runtime image

---

.dagger/engine.go

`Distro` wasn't a proper enum type :( I got the syntax wrong when adding it.
The enum members need to be *explicitly* declared to be of the distro type to apply.

ci: fix distro to be a real enum

---

core/container_exec.go
core/integration/container_test.go

Fixes https://github.com/dagger/dagger/issues/9095.
This fixes a bug where if the directory passed as a context directory had an exec *anywhere* in its history, it could not be built with an old syntax pragma (including docker/dockerfile:1.10 and before).
This is because a new `exec.validexitcode` capability was added when using `llb.ValidExitCodes` - which we were unconditionally using in every `WithExec` regardless of whether we actually need it or not. When passing this result to an old dockerfile frontend, it would not recognize this capability and fail out.
The solution here is to avoid unnecessarily attaching this capability - we only need to use `llb.ValidExitCodes` when actually working with values of `Expect` that are not `Success`. Now, this issue will only appear when using an …

fix: allow using old dockerfile pragmas

---

dagql/idtui/frontend.go
dagql/idtui/golden_test.go
dagql/idtui/testdata/TestTelemetry/TestGolden/cached-execs
dagql/idtui/testdata/TestTelemetry/TestGolden/custom-span
dagql/idtui/testdata/TestTelemetry/TestGolden/docker-build
dagql/idtui/testdata/TestTelemetry/TestGolden/docker-build-fail
dagql/idtui/testdata/TestTelemetry/TestGolden/encapsulate
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-effect
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-log
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-log-native
dagql/idtui/testdata/TestTelemetry/TestGolden/hello-world
dagql/idtui/testdata/TestTelemetry/TestGolden/pending
dagql/idtui/testdata/TestTelemetry/TestGolden/use-cached-exec-service
dagql/idtui/testdata/TestTelemetry/TestGolden/use-exec-service
dagql/idtui/testdata/TestTelemetry/TestGolden/use-no-exec-service
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/broken/broken
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/python/custom-span
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/python/pending
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/typescript/custom-span
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/typescript/pending

Fixes #9242.
We'll now only recommend using the prefixed environment variable `DAGGER_NO_NAG` - no more randomly cycling through. However, we'll keep supporting the old environment variables, in case users are using that to silence this output. We can deprecate those in the future.
Some light rephrasing of the message is required to fit the extra `DAGGER_` characters in - it's important we keep this line under 80 characters, so it fits nicely into standard sized 80x24 terminals.

fix: silence trace setup messages using descriptive env name

---

.github/main.go
.github/workflows/benchmark.yml
.github/workflows/daggerverse-preview.gen.yml
.github/workflows/docs.gen.yml
.github/workflows/engine-and-cli.yml
.github/workflows/github.gen.yml
.github/workflows/publish.yml
.github/workflows/sdk-rust-publish.yml
.github/workflows/sdks.gen.yml

`dagger-g2-*` runners are often over-provisioned, primarily due to how we request resources internally and how Karpenter allocates instances (full deep-dive of our setup can be seen [here](https://dagger.io/blog/argo-cd-kubernetes)) . Each instance type has a defined set of resources, however, not all of those resources are considered allocatable by Karpenter. An instance with 8 cores and 32Gi of RAM might only have 7 cores and 28Gi of RAM available for use. When we requested resources, we were requesting the exact number. If a new runner showed up and request 8 cores, instead of allocating an 8 core machine we would double and go for 16 cores. This, multiplied by the amount of PRs are created in dagger/dagger and the size of our runners, lead to a not so cost-effective CI.
In `g3` we …

ci: bump dagger runners generation to g3

---

.github/workflows/engine-and-cli.yml
helm/.dagger/main.go
helm/dagger.json
helm/dagger/.changes/unreleased/Added-20241220-193552.yaml
helm/dagger/templates/engine-statefulset.yaml
helm/dagger/values.yaml

This adds a new property - `kind` - which defaults to `DaemonSet`. It means that nothing will change for existing users: one Engine per K8s node.
For users that want to deploy **multiple** Engines per K8s node, set `kind: StatefulSet`, and the chart will take care of the rest.
This opens the door to experimenting with runtimes such as firecracker-containerd, gVisor, etc. for putting a sandbox around the Engine - should help address some of the `CAP_SYS_ADMIN` concerns.
Paired with @ioboi @chrira from [puzzle.ch](https://puzzle.ch)

helm: Enable deploying multiple Engines per node

---

.changes/unreleased/Added-20241127-183919.yaml
cmd/json-schema/main.go
core/integration/module_config_test.go
core/modules/config.go
core/modulesource.go
core/schema/module.go
docs/static/reference/dagger.schema.json

Closes https://github.com/dagger/dagger/issues/8967
Took a first swing at allowing $schema in the parsed config, and writing it back _if_ it exists.
It does not write a value by default, nor does it actually enforce that the json file abides by the schema (technically the URI could point to a completely random schema, or not resolve in the first place).
Primarily for the benefit of local development, because IDEs can help with descriptions and autocompletion if a $schema property is available

config: Allow $schema in dagger.json

---

cmd/dagger/main.go
cmd/dagger/module.go
core/integration/module_cli_test.go
core/modulesource.go
core/schema/module.go
core/schema/modulesource.go
docs/current_docs/reference/cli.mdx
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/module_source.ex
sdk/go/dagger.gen.go
sdk/php/generated/ModuleSource.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

This PR adds the `dagger update` command. Based on discussion in this ticket, we have decided not to update the version of the dependency (unless explicitly asked) but instead move the pin to the latest commit of the current version.
e.g. 
given current dependency of `<github.com/path/name>@<branch/tag>`:
- if the update command is `dagger update github.com/path/name`, it will update the `pin` to latest commit of the branch/tag. 
- however, if the update command is `dagger update github.com/path/name@<diff-version>`, it will update the `pin` to the latest commit for `<diff-version>` branch/tag.
potentially also fixes #8821

feat(cli): add dagger update command

---

.dagger/build/builder.go
.dagger/consts/versions.go
cmd/init/main.go
core/integration/module_terminal_test.go
core/integration/provision_test.go
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
engine/client/client.go
engine/client/filesync.go
engine/client/socket.go
engine/distconsts/consts.go
engine/server/bk_session.go
engine/session/h2c.go

(Was working on this day before vacation, sending out in a spare moment but won't revisit before I'm back in 2 weeks)
---
This change replaces dumb-init with a custom one written in go that also serves session attachables for nested execs.
One motivation is to avoid a few minor headaches around cross-compiling C code (which dumb-init) is written in. Cross-compiling the new go implementation is trivial.
More than that, this allows transplants session attachables from the executor to this init process, which greatly reduces the hardship involved in adding new session attachables.
* See this thread https://github.com/dagger/dagger/pull/8730#issuecomment-2552079719
Rather than having to figure out how to get each attachable to work both in the CLI and in the executor (which involves …

switch to custom init that also handles nested exec sessions

---

sdk/java/dagger-codegen-maven-plugin/src/main/java/io/dagger/codegen/introspection/Helpers.java
sdk/java/dagger-codegen-maven-plugin/src/main/java/io/dagger/codegen/introspection/ObjectVisitor.java

Javadoc comments are wrapped between HTML `<p>` tags. In this case `&` is not a valid entity and generates the following error:
error: bad HTML entity
* <p><br/>Set chart & app version<br/></p>
This happen when you generate the documentation using `mvnw package -Pjavadoc`
This commit escapes the `&` char and also call the `Helpers.escapeJavadoc` method for type and arg descriptions in addition to the already done field one.
---
The fix is quite basic, just for `&`. Maybe we need something more resilient, like to use some kind of escape html, but at least that solves this one issue.
cc @jcsirot

fix(sdk/java): handle & inside javadoc

---

.changes/unreleased/Changed-20250106-153156.yaml
core/integration/cache_test.go
core/schema/cache.go
dagql/server.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/client.ex
sdk/go/dag/dag.gen.go
sdk/go/dagger.gen.go
sdk/php/generated/Client.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

fixes #7211 
This PR namespaces the cache volumes so that across the modules they have different keys.

feat(engine): ensure cache volumes are namespaced

---

.github/dependabot.yml

This is pretty useful - I think maybe the `directories` option is new? Otherwise, I feel like I would have caught it before when doing all this. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories
Anyways, this will let us bump the sdk/go and the top-level directory go.mods together, so we won't need to do horrendous dependency resolution ourselves hopefully (like in https://github.com/dagger/dagger/pull/9187#issuecomment-2548200615).
While in the area, we can bump the docker update together as well.

ci: merge several dependabot configs into one

---

docs/current_docs/api/chaining.mdx

While technically true, the implication is that the produced tarball is gzip-compressed, which it is not! This updates the docs to clarify that the file produced is a raw `tar` archive.

Update chaining docs

---

cmd/init/main.go
sdk/php/dev/dagger.json

We were pinned to an old version of the php sdk that didn't have the proper OTEL work that allowed us to actually observe errors happening.
By unpinning it, we'll always get the same version as the engine.

ci: un-pin php sdk to use same version as engine tag

---

.dagger/build/builder.go
.dagger/cli.go
.dagger/engine.go
.goreleaser.common.yml

Internal ticket: https://linear.app/dagger/issue/DEV-4839
It's better to use the dagger-built binaries as part of our goreleaser release, instead of having goreleaser build them itself. This has a few advantages:
- Consistency. The fewer process differences between local builds and release builds, the better.
- Extensibility. At some point in the future, we want to bundle the engine *into* the CLI - this will require the CLI release build to use dagger, instead of being a simple `go build` command that goreleaser can do.
- Security. By splitting out the building and releasing steps, we're now no longer beholden to the release cadence of goreleaser before we can upgrade go versions.

ci: use dagger-built binaries in goreleaser

---

sdk/php/src/Connection/CliDownloader.php
sdk/php/src/Connection/ProcessSessionConnection.php

This is an attempt to fix the PHP flake from https://github.com/dagger/dagger/issues/9346.
What *appears* to be happening is that despite confirming that the output we read has `session_token` in it, we're somehow decoding a JSON object that doesn't have the `port` property.
Not really sure how this can possibly be happening - but assuming that the PHP library works as intended (not unreasonable), and that the `dagger session` code is good (we don't see any other flakes like this for other SDKs), then something is wrong here. Having mixed progress output into the stdout (which happens when a PTY is used) could *potentially* be the cause here? It would also explain why this seems flaky, since it depends on timing of writing to a buffer.
Anyways, probably worth a go, no other SDK opens a …

Attempt to fix PHP flake with more lax session output parsing

---

.github/actions/call/action.yml
.github/workflows/_dagger_on_depot_remote_engine.yml
.github/workflows/_dagger_on_magicache_remote_engine.yml
.github/workflows/_dagger_on_namespace_remote_engine.yml
.github/workflows/alternative-ci-runners-3.yml

We want to see the delta between jobs getting dequeued and calls actually starting, because in some cases cold Engines can add minutes to the job execution time.

ci: Warm up Engines before `dagger call` in Alternative Runners

---

.github/main.go
.github/workflows/docs.gen.yml
.github/workflows/trace-workflows.yml

So that it matches the filter when comparing the duration of this job in alternative runners.

ci: Rename Docs job to docs

---

cmd/dagger/module_inspect.go

don't defer the telemetry finalization so it doesn't account for the
initializeModuleConfig function

cli: fix module initialize span duration calculation

---

core/container.go
core/container_exec.go
core/integration/container_test.go
core/integration/git_test.go
core/integration/http_test.go
core/integration/module_test.go
core/integration/services_test.go
core/schema/container.go
sdk/elixir/test/dagger/client_test.exs

this addresses the issue introduced in v0.15.0 where services will hang
to start if neither CMD or ENTRYPOINT is used.
fixes #9190

engine: return error if services don't have a command set

---

core/integration/legacy_test.go
core/integration/module_up_test.go
core/schema/service.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/container.ex
sdk/go/dagger.gen.go
sdk/php/generated/Container.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

Follow-up from #8865, and handles part of the issue in https://github.com/dagger/dagger/issues/9190.
This PR makes two distinct changes:
- Fix the `Container.up` to always use the user-expected version of `Container.asService`. This makes sense, since the former is just sugar for the latter. This was pretty hard to run into in-practice, since it requires that you call `Container.up` *inside* a module.
- Add all the args from `Container.asService` to `Container.up` - we should be able to set args like `insecureRootCapabilities` on `Container.up`, otherwise, there's really no other place to put them. I *think* this was just an oversight.

`Container.up` consistency with `Container.asService`

---

core/integration/module_cli_test.go
core/schema/module.go
core/schema/modulesource.go

Previously, calling `dagger install` with no name would bizarrely insert it into the beginning of the `dagger.json` `dependencies` field. Then calling `dagger develop` would fix it.
This was an absurd little pet-peeve, so took some time to fix it - it will be nice when we can clean up `ModuleSource.resolveFromCaller`, since trying to understand that for this bug was by far the trickiest bit to actually understand and track.
This is what was happening:
- We call `updateDeps` to update our dependencies.
- We were calling `ModuleSource.dependencies` (which merges `withDependencies` nicely) and getting all ordered dependencies.
- However, no name was specified in the `withDependencies` call, so the name was actually the empty string - so was appearing first in the lexigraphic sort.
- Then, …

fix: insert `Module.withDependencies` in correct order

---

sdk/php/dagger.json
sdk/php/dev/dagger.json
sdk/php/dev/src/PhpSdkDev.php

Thanks to the `:expect` flag on calls to `withExec`
The custom-module _always-exec_ used in the PhpSdkDev is now obsolete.
This PR removes the depedency on the custom module _always-exec_.

fix: Replace custom module in PhpSdkDev

---

core/integration/module_up_test.go
core/schema/service.go

Quick follow-up to https://github.com/dagger/dagger/pull/9231 before v0.15.2.
First, a fix to a flake that could occasionally occur when there was a host port conflict :scream:
Then, `Container.up` should also be marked as impure, just like `Service.up`, since it modifies host state.

More `Container.up` consistencies

---

cmd/codegen/generator/typescript/templates/functions.go
cmd/codegen/generator/typescript/templates/src/method_solve.ts.gtpl
sdk/typescript/src/api/client.gen.ts
sdk/typescript/src/common/context.ts

💡 This is purely an internal code improvement PR 💡 
Replace the manual ID loading with a call to `client.loadXXXFromID` to remove boilerplate.
Add `copy` method to context.
Simplify codegen and remove big boilerplates specially when loading arrays.
This saves around 400 lines of codegen and even more when dependencies are involved 🚀 
**NOTE**: Originally, we discussed about that idea with @helderco and wanted to move the loading logic inside `Context` but it's not possible since we need to call it from `dag` to do this and it will:
- 1: create a circular dependency issue between codegen & context.
- 2: if used as a library, `dag` is different than the client used by the user. 
So instead, I choose to simplify improve the codegen.

chore: ts sdk simplify codegen ideable loader

---

core/schema/cache.go
core/schema/sdk.go

Without this, we can end up accidentally using the wrong module by default! This means we end up with distinct cache volumes for these, when they should be shared *everywhere*.
(split out of #9389)

fix: ensure the go sdk uses namespaced volumes

---

.github/workflows/sdks.gen.yml
sdk/dotnet/dev/dagger.json
sdk/elixir/dev/dagger.json
sdk/php/dagger.json
sdk/php/dev/dagger.json

- Fix `DAGGER_VERSION` on dotnet job
- Fix inconsistency in runner machine configuration
- Fix dagger version in modules

chore: fix dotnet dagger version in workflow

---

cmd/dagger/shell.go
dagql/idtui/frontend.go
dagql/idtui/frontend_plain.go
dagql/idtui/frontend_pretty.go

This fixes the following data race when setting the `CustomExit` in the REPL:
```
==================
WARNING: DATA RACE
Read at 0x00c0003eb6e8 by goroutine 34:
github.com/dagger/dagger/dagql/idtui.(*frontendPretty).recalculateViewLocked()
/Users/helder/Projects/dagger/dagql/idtui/frontend_pretty.go:518 +0x54
github.com/dagger/dagger/dagql/idtui.FrontendSpanExporter.ExportSpans.deferwrap2()
/Users/helder/Projects/dagger/dagql/idtui/frontend_pretty.go:340 +0x34
runtime.deferreturn()
/Users/helder/.local/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/src/runtime/panic.go:605 +0x5c
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans()
/Users/helder/.local/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.27.0/trace/batch_span_processor.go:277 +0x30c …
```

shell: fix data race coordinating with the bubbletea program

---

cmd/dagger/functions.go
cmd/dagger/shell.go
core/integration/module_call_test.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/9264
Fixes https://github.com/dagger/dagger/issues/8893
```shell
❯ dagger core --silent container from --address alpine with-exec --args ls,wat stdout
Error: input: container.from.withExec.stdout process "ls wat" did not complete successfully: exit code: 1
```
```shell
⋈ container | from alpine | with-exec ls wat | stdout
Error: input: container.from.withExec.stdout process "ls wat" did not complete successfully: exit code: 1
⋈ 
```
```shell
❯ dagger core --silent container from --address alpine with-exec --args ls,wat stdout
Error: input: container.from.withExec.stdout process "ls wat" did not complete successfully: exit code: 1
ls: wat: No such file or directory
exit status 1
```
```shell
⋈ container | from alpine | with-exec ls wat | stdout …
```

shell: fix stderr from failed execs not showing

---

cmd/dagger/module_inspect.go
cmd/dagger/shell.go
cmd/dagger/shell_commands.go
cmd/dagger/shell_exec.go
cmd/dagger/shell_state.go
core/integration/module_shell_test.go

Fixes an important issue reported by @jedevc where you can’t run multiple Dagger functions in a script (i.e., encoded shell state). 
Also fixes another issue where even if you have multiple commands, their output is only shown at the very end, when the interpreter’s runner has finished.
Previously, all output from a run was getting buffered and then analyzed has a whole after the runner had finished. However, if there were multiple commands returning state that needs to make an API request to resolve, could be ignored except for the first one:
```
⋈ container; directory
defaultArgs: []
entrypoint: []
mounts: []
platform: linux/arm64
user: ""
workdir: ""
```
Notice that only the container is shown.
Now, queries are resolved as the runner is executing and attempting to write the final …

shell: fix running multiple top-level queries

---

sdk/php/.changes/unreleased/Added-20250118-002701.yaml
sdk/php/src/Command/EntrypointCommand.php
sdk/php/src/Service/DecodesValue.php
sdk/php/src/ValueObject/Type.php
sdk/php/tests/Unit/ValueObject/TypeTest.php

This PR follow up #9396.
I create a module named `potato` and put the following code to `src/Potato.php`:
```php
<?php
declare(strict_types=1);
namespace DaggerModule;
use Dagger\Attribute\DaggerFunction;
use Dagger\Attribute\DaggerObject;
use Dagger\Attribute\Doc;
use Dagger\Container;
use Dagger\Directory;
use function Dagger\dag;
#[DaggerObject]
#[Doc('A generated module for Potato functions')]
class Potato
{
#[DaggerFunction]
public function acceptFloat(float $value): float {
return $value;
}
}
```
Then run `dagger call accept-float --value=1.245`, the cli will output:
```
✔ connect 0.3s
✔ load module 16.8s
✔ parsing command line arguments 0.0s
✔ potato: Potato! 0.0s
✔ .acceptFloat(value: 1.245000): Float! 0.5s
1.245
```

feat(sdk/php): support float type

---

sdk/elixir/dagger.json
sdk/elixir/dev/dagger.json
sdk/elixir/runtime/go.mod
sdk/elixir/runtime/go.sum
sdk/elixir/runtime/main.go

This changeset remove `/root/.mix` cache volume out of the runtime because sometimes, the `mix local.hex --force` got cached, cause `/root/.mix` cache volume got empty.
And also update dev module to use latest version of `elixir` SDK and bump `engineVersion` in dagger.json.

fix(sdk/elixir): fix Hex is missing because `local.hex` cached

---

modules/gha/steps.go

See discussion in https://discord.com/channels/707636530424053791/1323311418325471315/1328681959211274323, raised by @wingyplus.
This fixes the issue where an dagger version will be treated as if we should try and install the dev version of dagger.

fix: ensure modules/gha handles empty dagger version

---

core/integration/provision_test.go

The image we use here by default is the image built off of main - but that may actually not have been built, which is sad, and causes flakes in this test.
The solution here is to just avoid the image pull step, by pre-loading the image.

tests: avoid image pull in docker driver provision test

---

cmd/dagger/shell.go
cmd/dagger/shell_commands.go
cmd/dagger/shell_exec.go
core/integration/module_shell_test.go

Something I've wanted to do for a while. Instead of `..`, should use `_` for interpreter builtins:
https://github.com/dagger/dagger/blob/6d0fd95302bfdfca7446aec2b8155b1949a1e88f/cmd/dagger/shell.go#L254-L265
```
..echo foo & ..echo bar & ..wait
```
```
_echo foo & _echo bar & _wait
```

shell: change prefix for interpreter builtins

---

cmd/dagger/shell_exec.go

Fixes https://github.com/dagger/dagger/issues/9423
```
⋈ modules/alpine -h
Usage of alpine:
--arch string
--branch string
--distro string
--packages strings
Error: constructor: pflag: help requested
```
```
⋈ modules/alpine -h
Usage of alpine:
--arch string
--branch string
--distro string
--packages strings
Error: constructor: unknown shorthand flag: "-h"
```

shell: fix flag parsing of `-h` and `--help`

---

cmd/engine/main.go
core/cache.go
core/container.go
core/container_exec.go
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
engine/buildkit/worker.go
engine/cache/manager.go
engine/cache/mountsync.go
engine/server/server.go

Currently cache volumes are being synchronized during engine startup. For organizations that have large cache volumes (or a large amount) this dramatically slows down their pipelines. Similar to what we do for layers, we want cache mounts to be synced on-demand.
When a container gets executed we will download the cache volumes that will be used for it. This will only happen once per cache volume during the lifetime of the engine.
> [!CAUTION]
> This change will make individual `dagger call` operations slower since cache mounts now gets downloaded and applied while the call itself happens. This is something we want to explicitly communicate to our users.
Thanks to @sipsma [guide](https://discord.com/channels/707636530424053791/1265063659424583700/1265063660955373730) on how to approach …

engine: sync cache volumes on-demand

---

core/integration/module_test.go
core/schema/modulesource.go

Fixes https://github.com/dagger/dagger/issues/9068.
We need to take into account that dependencies have a *different* relative context directory. The fact this was working before, was that generally, we were only invoking modules from the same location as the `dagger.json` - however, if invoked from above or below, then we'd fail to apply the correct transformation and we'd get the wrong context directory.
Thankfully, it's fairly simple - all we need to do is mirror the logic that modifies the `refString` and apply it to `relHostPath` as well.

fix: relatively resolve dependency context directories

---

.dagger/sdk_rust.go

[v0.13.1](https://github.com/killercup/cargo-edit/releases/tag/v0.13.1) was released, and requires a more recent version of rust than we're currently using.

chore: pin cargo-edit version

---

.github/workflows/publish.yml

Follow up to #9356.
Ooops.
https://github.com/dagger/dagger/actions/runs/12953852890/job/36134451106

ci: fix typo in --image flag

---

docs/current_docs/cookbook/snippets/builds/dockerfile/python/main.py

Follow-up from https://github.com/dagger/dagger/pull/9446.
This is currently causing the python linter to fail.

docs: remove unneccessary import in python dockerfile snippet

---

.dagger/checks.go
.dagger/docs.go
.dagger/engine.go
.dagger/main.go
.dagger/scripts.go
.dagger/sdk_all.go
.dagger/sdk_elixir.go
.dagger/sdk_go.go
.dagger/sdk_php.go
.dagger/sdk_python.go
.dagger/sdk_rust.go
.dagger/sdk_typescript.go

This causes some very hard-to-read CI failures when we use this - this means that instead of waiting for *everything* to finish, we bail quickly on the first error. E.g. when linting, we error out on the first lint failure, instead of waiting for all the checks to pass or fail.
For example, of a hard-to-read failure see https://v3.dagger.cloud/dagger/traces/168ed3748bb12bdb7d858df98a9adb94

ci: avoid use of `errgroup.WithContext` in checks

---

cmd/engine/main.go
core/cache.go
core/container.go
core/container_exec.go
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
engine/buildkit/worker.go
engine/cache/manager.go
engine/cache/mountsync.go
engine/server/server.go

This reverts commit f2c5dc5d2908ecbafaf6dbe4c5663791161a40a8. The main reason why we're revering #8323 is because some strange behaviors that we haven't had the time to test and we prefer to take this out of the upcoming release so we can take the proper time to diagnose.

Revert "engine: sync cache volumes on-demand (#8323)"

---

releaser/main.go

:scream: https://github.com/dagger/dagger/pull/9443 didn't catch everything.
We really need a better way of type-checking this kind of thing - wonder if dagger shell could do this.

ci: fix typo in cloud front distribution flag

---

dagql/idtui/golden_test.go

The previous version was able to catch things like:
- `1m2.345s`
- `12.34s`
But wasn't able to catch:
- `1m23s`
But it looks like it happens, sometimes:
```
+++ actual
@@ -11,7 +11,7 @@
│ ✔ starting session X.Xs
-✔ load module X.Xs
+✔ load module 1m13s
│ ✔ finding module configuration X.Xs
-│ ✔ initializing module X.Xs
+│ ✔ initializing module 1m12s
│ ✔ inspecting module metadata X.Xs
│ ✔ loading type definitions X.X
```
For instance: https://v3.dagger.cloud/dagger/traces/d3cd71a1531096b0071621d896b3ebe6?span=f3e3b1f9b2b1f4aa&logs#f3e3b1f9b2b1f4aa

fix duration scrubber for golden tests

---

sdk/php/dev/src/PhpSdkDev.php
sdk/php/runtime/go.mod
sdk/php/runtime/go.sum

The custom module `always-exec` had been removed from the dev module but I mistakenly left it's usage in one of the less frequently used methods.
This removes it and fixes the method.
Also upon using 0.15.2 it automatically updated a few Go dependencies, which I assume are okay to commit.

Fix format stdout

---

core/container.go
core/integration/container_test.go
core/integration/directory_test.go

Fixes https://github.com/dagger/dagger/issues/9448.
The code that propagates operations to a container's underlying directory wasn't quite correct. It was incorrectly making the assumption that combining `filepath.Dir` + `filepath.Base` gives you the original path.
However, when passing a path with a trailing slash to `filepath.Dir`, you actually get the entire input - instead of going up a level. So, instead, we should avoid this, and instead `filepath.Clean` the input so that we ensure we never have a trailing slash. We can also make these methods consistent, and use `filepath.Split` as well (while we're in the area, this doesn't actually have a behavior change).

fix: ensure trailing slashes in `Container.WithFiles` doesn't change behavior

---

docs/package.json
docs/yarn.lock

ref: https://github.com/dagger/dagger/security/dependabot/966

chore: bump path-to-regexp to address dependabot advisory

---

engine/telemetry/labels.go

Checks if the `TF_BUILD` environment variable is set and marks the run as CI with the vendor as Azure.
@vito asking for your review as you most recently edited 😄

Check for TF_BUILD on Azure Pipelines

---

sdk/elixir/runtime/main.go

Before this PR, the function call was not getting cache because the compilation occurred every time it ran the `mix run` command. In this PR, add a compilation step before trigger the entrypoint to ensure a function will compile only once during initialization.
The `dagger functions` takes around 3 seconds each run and the `container-echo` function call takes around 11 seconds
I noticed that `dagger functions` is a bit slower on the first run (~15 seconds) but it gets faster on the second round at around 1-2 seconds
The `container-echo` function call uses under 10 seconds and it get faster on the second run.

perf(sdk/elixir): optimize function call time

---

sdk/go/go.mod
sdk/go/go.sum
sdk/go/querybuilder/marshal.go

The experimental functions in `golang.org/x/exp/slices` have been included in the standard library as of Go 1.21.
Reference: https://go.dev/doc/go1.21#slices

refactor(sdk/go): replace `golang.org/x/exp/slices` with `slices`

---

core/cachekey.go
core/interface.go
core/moddeps.go
core/object.go
core/schema/cache.go
core/schema/host.go
core/schema/module.go
core/telemetry.go
core/typedef.go
dagql/objects.go
dagql/server.go
dagql/types.go

We previously needed to make function calls impure to handle various
corner cases around Secrets (covered by TestModule/TestSecretNested) in #8358.
However, recently sometime this resulted in us getting duped telemetry
output for calls. It makes sense in that a call may often get
re-evaluated (i.e. it's a base image for multiple vtxs in a DAG). It's
not clear why this only started happening recently though.
Either way, we can fix it by having function calls be cached per-client
via a custom cache key func.
This fixes duped output as repro'd by running:
```
dagger -m github.com/vito/bass call integration --runtime Buildkit
```
* Previously you'd see multiple apko->wolfi outputs appear, now it only
shows up once as expected.
But keeping the caching per-client rather than fully cached allows …

Cache function calls per-client to avoid duped telemetry 

---

docs/current_docs/configuration/custom-ca.mdx

The `docker run` command in this page  does not work: the engine container image version must be prefixed by `v` otherwise an error occurs
`Error: initializing source docker://registry.dagger.io/engine:0.15.3: reading manifest 0.15.3 in registry.dagger.io/engine: manifest unknown`

Fix typo in docker run command in custom-ca.mdx

---

.github/workflows/_dagger_on_x1_nvme.yml
.github/workflows/_dagger_on_x1_tmpfs.yml
.github/workflows/alternative-ci-runners-4.yml
.github/workflows/trace-workflows.yml

Experimental (X1) runners on always-on infrastructure:
- CPU: EPYC 9454P
- MEM: 256GB DDR5 ECC
- NVMe: MZQL21T9HCJR-00A07
- NET: 10G

ci: Add alternative CI Runners 4

---

.github/workflows/publish.yml

v16 of the action we're using has a fix for the error we're seeing on main https://github.com/dagger/dagger/actions/runs/13067469981/job/36462427359:
```
Updating Homebrew
Error: Unknown option: --preinstall
Usage: brew update, up [options]
Fetch the newest version of Homebrew and all formulae from GitHub using git(1)
and perform any necessary migrations.
--merge                      Use git merge to apply updates (rather than
git rebase).
--auto-update                Run on auto-updates (e.g. before brew
install). Skips some slower steps.
-f, --force                      Always do a slower, full update check (even
if unnecessary).
-q, --quiet                      Make some output more quiet.
-v, --verbose                    Print the directories checked and git
operations performed.
-d, …
```

ci: fix macos install docker step

---

.github/workflows/publish.yml
releaser/report.md.tmpl

Oops, https://github.com/dagger/dagger/actions/runs/13177476543/job/36780091370.
Looks like the grep expression wasn't right.
The report looks mostly nice though (also pushed a fix to tidy up the link header formatting):

ci: fix report filtering

---

cmd/dagger/run.go

Without this change, any OTel instrumentation within the wrapped command will be invisible to the TUI. With this change, we set up an OTel proxy that just delegates to the CLI, so all received OTLP data goes to both the TUI and any other configured OTel exporters (including Cloud).

`dagger run`: configure OTel proxy

---

cmd/dagger/shell.go

Noticed some people expect to be able to type "exit" to leave the shell REPL.
There's an `exit` builtin and at first I just delegated to it, but it requires the interp runner to run, only to exit right after. So this feels simpler and snappier. Builtin is still available at `_exit`, but it won't exit the REPL. I tried that but got tangled with knowing the difference between exiting a prompt vs exiting the REPL.

shell: allow "exit" in the repl

---

cmd/dagger/run.go
engine/buildkit/executor_spec.go
engine/consts.go

This was bad, since the CLI is built for Windows, but our buildkit package uses Unix constants.
We can just move the offending environment variable names into `engine`, which is safe to import from the CLI.

fix: avoid importing buildkit to the CLI

---

core/schema/sdk.go
dagql/idtui/testdata/TestTelemetry/TestGolden/viztest/broken/broken

if you're digging on SDK/module init performance, these spans make it much harder to get confused about which step you're in, and child spans of these steps dominate module init runtime and look similar --- you'll see the codegen binary invoked by the go SDK and then again by your module SDK, for example. 
These spans also make it very clear where Codegen ends and Runtime begins, which can be confusing bc at least in for ts, the tail end of codegen installs runtime dependencies like corepack, and in a flat trace the corepack download looks like it could be part of either SDK interface method.
I'm open to suggestions on other places one might add spans to make these steps clearer.

obs: add spans for go/module sdk runtime and codegen methods

---

sdk/java/pom.xml
sdk/java/runtime/template/pom.xml

fixes vulnerability inside transitive dependency:
org.eclipse.parsson:parsson │ CVE-2023-7272
io.netty:netty-handler | CVE-2025-24970
This should fix the `scan` CI issue on other PRs

sdk/java: fix vulnerabilities in deps

---

modules/go/main.go

This allows the engine to correctly setup certificates in case there's
any custom certs configured

ci: add ca-certificates package to the Go module

---

core/modulesource.go

Fixes https://github.com/dagger/dagger/issues/9524.
`LoadContext` could easily produce a `Directory` that's dependent on a `Secret`. We have logic to ensure that `Secret`s are all correctly transferred between various clients.
The underlying bug was occurring because of this chain of events:
- Main client session loads all the dependencies, and we inject git credentials
- We enter the top-level module `A` client session, and call the target function `ContainerEcho`, which calls `B`'s `ContainerEcho`, which in turn calls `LoadContext` to load the contextual argument from the dependency git context
- `B` returns a value dependent on the loaded git context, which then triggers the secret transfer code to try and transfer the git credential secret from `B` back to `A`.
- However! :warning: …

fix: transfer secret during `LoadContext`

---

engine/buildkit/executor_spec.go

This avoids the annoying `"can not add field "call_id"` messages that can appear in our logs.
```
time="2025-02-11T12:05:08Z" level=debug msg="starting container" logrus_error="can not add field \"call_id\"" ...
```
See the logic in logrus that generates this error: https://github.com/sirupsen/logrus/blob/d1e6332644483cfee14de11099f03645561d55f8/entry.go#L140

chore: get call id digest before attaching to logrus

---

sdk/java/pom.xml
sdk/java/runtime/template/pom.xml

net.minidev:json-smart │ CVE-2024-57699
fixed in version 2.5.2

sdk/java: fix json-smart vuln

---

.github/workflows/daggerverse-preview.gen.yml
.github/workflows/docs.gen.yml
.github/workflows/engine-cli.gen.yml
.github/workflows/github.gen.yml
.github/workflows/helm.gen.yml
.github/workflows/sdks.gen.yml
modules/gha/scripts/install-dagger.sh
modules/gha/steps.go

We've actually been installing the wrong version here :thinking: 
See: https://github.com/dagger/dagger/actions/runs/13289937745/job/37107902281
In the install step, we install v0.15.4 - but we haven't yet updated to it.
This whole step should be better daggerized, but delaying that at least until the work for `hack/build` is done, see https://github.com/dagger/dagger/pull/9555.

fix: gha module dev dagger step

---

sdk/java/dagger-java-annotation-processor/src/main/java/io/dagger/annotation/processor/DaggerModuleAnnotationProcessor.java

This PR adds two checks in the annotation processor for Java modules. It verifies that Objects (annotated with `@Object`) and Functions (annotated with `@Function`) are declared as public.
This prevents runtime exceptions such as `java.lang.IllegalAccessException` or `java.lang.NoSuchMethodException` when calling module functions.

Ensure that java module objects and functions are public

---

core/integration/localcache_test.go
core/query.go
core/schema/engine.go
engine/server/gc.go
engine/server/server.go

prevents a panic from happening when starging the engine with local cache GC disabled.

engine: fix panic when starting engine with local cache GC disabled

---

sdk/php/composer.json
sdk/php/composer.lock

We started relying on functionality introduced in v1.14.1 of php-graphql-client. But we failed to bump to v0.14.0.
This wasn't caught during testing, but only when upgrading an older module to the latest version of dagger.

fix(php): bump graphql dependency

---

.dagger/sdk_php.go
sdk/php/dev/src/PhpSdkDev.php

Instead of passing PHP SDK source directory to every functions in `dev` module, set it at constructor and use `DefaultPath` to load parent directory by default.
In the Dagger module, modify the `SDKPHP` to set PHP SDK source directory to module initialization instead of function call.

chore(sdk/php): use DefaultPath to SDK source directory in dev module

---

docs/current_docs/api/custom-functions.mdx
docs/current_docs/api/snippets/functions/functions-complex/php/src/MyModule.php

If you check the preview on custom functions You will notice this part doesn't have a PHP snippet: 
```md
<DaggerModuleInit />
```
But I do add that part in the #9541

docs: Add PHP snippet to custom functions

---

docs/current_docs/api/enumerations.mdx

Enums will be supported in the future, however they are unsupported currently. This informs users who visit the page that the PHP SDK does not currently support enums.

docs: Explain enums are not supported by PHP SDK

---

sdk/go/telemetry/transform.go

These fields are technically optional with OTel logging (logs aren't always associated to a trace or span), so these would panic trying to convert `nil` to a fixed-length array.
Context: [Discord](https://discord.com/channels/707636530424053791/1333326734506070066/1339956738874671165)

telemetry: handle log records with no trace/span

---

cmd/dagger/module.go
core/integration/legacy_test.go
core/integration/module_test.go
docs/current_docs/reference/cli.mdx

Fixes https://github.com/dagger/dagger/issues/9576.
We need to add this into our calls to `AsModule` to get the engine version to update.

fix: ensure that all commands that update dagger.json bump engineVersion

---

.changes/unreleased/Breaking-20250205-162857.yaml
.dagger/config.go
.dagger/engine.go
.dagger/mage/engine.go
.dagger/mage/util/const.go
.dagger/main.go
.dagger/test.go
cmd/engine/config.go
cmd/engine/main.go
docs/current_docs/configuration/engine.mdx
engine/config/config.go
engine/server/server.go

This PR has a little collection of fixes:
- Avoid use of `engine.toml` for our own CI *where possible* (it's still needed for configuring registries now, patch incoming for that soon hopefully).
- Simplifies our own CIs construction of engine config + args.
- Fixes https://github.com/dagger/dagger/issues/9009 by requiring `security.insecure` to explicitly be *unset* if it's not being used.

Use less `engine.toml`

---

helm/.dagger/main.go

Due to details in our version comparisons, the recent min version bump to v0.16 has caused our helm job to start breaking. See https://github.com/dagger/dagger/actions/runs/13409473465/job/37456077136.
This is because the helm job starts an image from *main*. This is not ideal, and the versions between these are kind of mutually incompatible. We might want to loosen these at some point a bit, but I don't really have the time to reason through the implications of that *right* now - so this should quickly unblock that job from passing.

ci: fix failing helm job with version incompat

---

docs/current_docs/configuration/engine.mdx

docs: remove note about default engine.toml

---

core/interface.go
core/moddeps.go
core/modfunc.go
core/object.go
core/schema/modulesource.go
core/telemetry.go
dagql/objects.go

Should fix https://github.com/dagger/dagger/issues/9619, can run `BenchmarkLotsOfDeps` locally now without excessive memory usage.
---
Recently, function calls were "upgraded" from being tainted (i.e. never
cached) to cached-per-client in terms of dagql caching. This helped
fixed a problem with duplicated telemetry.
However, we currently have two layers of caching between dagql and
buildkit and this cache-per-client logic inadvertently ended up also
applying to the buildkit cache key, which increased the amount of cache
invalidation there.
This surprisingly didn't have a super noticeable effect on performance
at least as far as our tests that always run go.
However, the benchmark tests Connor added did end up hitting this,
specifically in BenchmarkLotsOfDeps, which creates a complicated …

make function calls cached session-wide

---

.dagger/build/sdk.go
.dagger/go.mod
dagger.json
sdk/typescript/runtime/go.mod
sdk/typescript/runtime/main.go
sdk/typescript/runtime/tsdistconsts/consts.go

with a cold cache, this shaves ~7-10 seconds off TS module init with a hello world-ish module. prior to this change, it'd take ~31s on my machine and after it's somewhere in the 24s range. it makes my dev image marginally larger, which is a bit of a tradeoff, but the dev image is already 449Mb and tsx ends up being like 5mb additional. 
~sidenote: mucking with module-sdk "runtime" go.mod dependencies is pretty error-prone in its current state... it matters quite a bit for module init performance that the go-SDK-based SDKs share exact dependencies with the go SDK, and blindly adding `require`s or naively `go mod tidy`-ing can mess that up... i think the intent is that we use `dagger develop` to make things match? that seemed to work decently well, although things may still be off by …

bundle tsx in the engine image to speed up the TS sdk's node-runtime module init

---

.dagger/cli.go
.dagger/engine.go
releaser/main.go

Based off of @gerhard's work in [`2273cd2` (#9504)](https://github.com/dagger/dagger/pull/9504/commits/2273cd29a5283f35a767f18a532a7b7c9ff0f3ff).
We should be able to merge this directly to `main`, and once `llm` is rebased, the tagging should work a bit easier.

ci: allow tagging arbitrary pre-releases

---

.changes/unreleased/Added-20250218-113020.yaml
helm/dagger/templates/engine-daemonset.yaml
helm/dagger/templates/engine-statefulset.yaml
helm/dagger/values.yaml

This PR enables setting `imagePullSecrets` making it easier to use private custom Dagger images.

helm: Enable setting imagePullSecrets

---

.dagger/cli.go
.goreleaser.prerelease.yml
releaser/main.go

Follow-up to https://github.com/dagger/dagger/pull/9626.
When we do pre-releases, like for our LLM branch, we should avoid publishing to our homebrew tap, etc. To handle this, we create a new config and use that for our pre-releases.
(this also includes some nice changes to make it easier to `--dry-run` and debug the cli publish step, by returning the `dist` directory, and having optional secrets)

ci: add goreleaser pre-release config

---

sdk/java/dagger-java-annotation-processor/src/main/java/io/dagger/annotation/processor/DaggerModuleAnnotationProcessor.java
sdk/java/dagger-java-annotation-processor/src/test/resources/io/dagger/gen/entrypoint/entrypoint.java
sdk/java/dagger-java-annotation-processor/src/test/resources/io/dagger/java/module/DaggerJava.java

While working on the Java SDK documentation, I realized `float` type is not correctly handled.
This fixes it and adds it to the main test to ensure we can generate the code.

fix(sdk/java): handle float type (and others)

---

.github/workflows/publish.yml

We need coverage of module loading on arm64 to catch problems where x86 artifacts (built by our x86 ci runners) accidentally end up in arm64 images.
This is a quick update to our provision tests to give us that additional coverage. Just runs `dagger call -m ... --help` to trigger a module load for the SDKs covered here.

Add arm64 coverage and module loading to provision tests

---

.goreleaser.prerelease.yml

Otherwise this will append v to versions when publishing to S3, which we do not want.

ci(publish): Do not overwrite version for pre-releases

---

.changes/unreleased/Fixed-20250220-153742.yaml
cmd/dagger/module_inspect.go
core/integration/module_call_test.go
core/integration/module_cli_test.go
hack/with-dev

Calling `dagger functions` or `dagger call` was panicking rather than erroring cleanly due to an oversight in `initializeModule`. Now it errors nicely.

fix panic when dagger call/functions called in dir with no modules

---

.goreleaser.prerelease.yml

Previously we tried removing this, but then it switched to goreleaser's default template:
{{ incpatch .Version }}-{{ .ShortCommit }}-nightly
What we really want is the tag, sans "v" - turns out there's a [`trimprefix` template function](https://github.com/goreleaser/goreleaser/blob/4f1b7c81d2ee48af5b804d67cec8c74f44d66ff3/www/docs/customization/templates.md?plain=1#L165) for exactly that.

use tag without "v" prefix for prerelease versions

---

.changes/unreleased/Fixed-20250220-163221.yaml
core/integration/module_test.go
core/schema/modulesource.go

There was some leftover logic that resulted in the full source root dir
being loaded when no dagger.json was found, which in the case of
`dagger` commands being run in a dir w/ no module present could result
in lots of files being loaded.
This just removes that logic. This is most important for the shell,
which is totally valid to use outside a module dir, but also allows the
CLI to error out faster for `call`, `functions`, etc.

fix load of full dir when no dagger.json 

---

sdk/java/runtime/main.go

Before the built dependencies were copied, replace it by a cache and re-use the same container. This improve the performances when creating multiple modules for instance.

sdk/java: use cache to store maven dependencies

---

.goreleaser.prerelease.yml

Nope, `Tag` is not set in this context helpfully, so instead just use `v` + Version here.

ci: fix goreleaser prereleases (again again)

---

sdk/php/runtime/main.go

This reverts https://github.com/dagger/dagger/pull/9625 - looks like the PHP tests have started failing after it, not sure why.
cc @carnage @charjr 
Example failure: https://v3.dagger.cloud/dagger/traces/1e0e5e64a1c90d597a534d6e8a6faf82?span=1f0ea2d68e44a4e2&logs
The tests that are failing:
https://github.com/dagger/dagger/blob/bf712c4d46992979e9b92a1b9728413b0565e928/core/integration/module_php_test.go#L18-L31
These only started failing on `main` because these tests fetch the version of the PHP SDK from main. While these checks are somewhat important, we should probably have a test for the commit - similar to how it's done for `TestJava`.

Revert "PHP: Ensure up to date dependencies of the generated code"

---

.changes/unreleased/Added-20250218-190012.yaml
core/integration/directory_test.go
core/integration/file_test.go
core/schema/directory.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/directory.ex
sdk/go/dagger.gen.go
sdk/php/generated/Directory.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

Based on https://discord.com/channels/707636530424053791/1336739628350439454.
This PR adds a function `name` to the Directory API to retrieve the latest name of the branch.
Fixes #9522

feat: add `name` in Directory API

---

sdk/typescript/package.json

I was having trouble loading the type declaration file in my project. I noticed that the "types" path in the package.json didn't match the actual location of the declaration file. I tried updating it with a `yarn patch` operation in my project and the issue was gone!

[Typescript SDK] Fix type declaration path in package.json

---

cmd/dagger/main.go
cmd/dagger/module.go
cmd/dagger/shell.go
docs/current_docs/reference/cli.mdx

This brings the shell to the root command. Also added "Experimental" on the welcome message when entering the interpreter mode:
```console
❯ dagger -c version
v0.16.0-010101000000-dev-4a017b8bfbc1
❯ dagger
Experimental Dagger interactive shell. Type ".help" for more information. Press Ctrl+D to exit.
. ⋈
```

shell: run from root command

---

engine/server/session.go

There's a problem upstream where a canceled context during `batchSpanProcessor.ForceFlush` leaks a goroutine. I saw this actually happen while testing stuff and it's extra bad because it leaks quite a substantial amount of memory that's indirectly referenced in our various span processors.
For now, this just mitigates it. I have [an upstream fix](https://github.com/open-telemetry/opentelemetry-go/pull/6363) that we will hopefully pick up someday after it's released and we've upgraded.
cc @vito I don't really love the mitigation of just giving this a long timeout, but not sure what's better, let me know if you can think of anything better.

mitigate upstream otel goroutine leak in telemetry flush

---

docs/current_docs/integrations/snippets/github-ghcr.yml
docs/current_docs/integrations/snippets/github-hello.yml
docs/current_docs/integrations/snippets/github-test-build.yml

Complies with new GH Actions immutable actions style
We likely can relax this to `@8.0` or `@8` or `@v8`, but being strictly correct for the launch of immutable actions.

docs: Update GH action version x.y.z

---

docs/current_docs/api/arguments.mdx

This commit attempts to improve discoverability of documentation for default paths and filters for users of directory/file arguments, by cross-linking the relevant pages. It is a further iteration on the proposal in #9534 based on https://discord.com/channels/707636530424053791/1162025276872609832/1343607950090178743

docs: Cross-link directory/file argument pages

---

core/integration/module_php_test.go

Adds a test which takes the local `./sdk/php` to test if the current changes work.
This is to help avoid issues like [this](https://github.com/dagger/dagger/pull/9692).

PHP: Add Integration Test for initializing a module from local files

---

docs/docusaurus.config.ts

part of Java SDK work, but doesn't need to wait

docs: Add Java syntax highlighting

---

sdk/java/runtime/template/pom.xml

The VS Code java plugin is missing some features for years: the ability to code complete based on the target/generated-sources files. This allows to explicitly instruct maven/vs code by adding the generated source directories as source directories so that code completion can happen.
Also added some comments to the pom.xml file to help understand which are the critical parts of the file that shouldn't be touched by the user.

fix(sdk/java): code completion on VS Code

---

.dagger/cli.go
.goreleaser.common.yml
.goreleaser.nightly.yml
.goreleaser.prerelease.yml
.goreleaser.yml

We build the binaries outside of goreleaser now, so this hook isn't required - additionally it makes the build fail in cases when the goreleaser version is a little bit old.
While I'm here:
- Update goreleaser
- And fix a little bit of the tag detection logic that was making it annoying to test the changes with

Fix failing goreleaser + do random chores in the area

---

helm/dagger/templates/_helpers.tpl

The Helm `app.kubernetes.io/version` label is not sanitized. This can lead to incorrect template generation on some system updating the version.
For example with flux, we need to use an OCI registry as the source of the helm chart (because HEAD requests on `registry.dagger.io/dagger-helm/dagger:<tag>` fails with 403 unauth, preventing usage of HelmRepository resource). The default behavior of flux is [to append the digest](https://fluxcd.io/flux/components/helm/helmreleases/#chart-reference) to the version: `<version>+<digest[0:12]>`.

fix(helm): sanitize version label

---

core/integration/module_elixir_test.go
sdk/elixir/lib/dagger/mod.ex

Instead of convert input arguments from `FunctionCallArgValue` to atom.
Convert argument name in argument definition to string instead.

fix(sdk/elixir): fix sdk crash due because of String.to_existing_atom

---

cmd/dagger/shell_commands.go
cmd/dagger/shell_help.go
core/integration/module_shell_test.go

Now `.help` without arguments shows available "commands", not just builtins, including top level functions and dependencies.
```console
❯ dagger shell -c .help
BUILTIN COMMANDS
.core         Load any core Dagger type
.deps         Dependencies from the module loaded in the current context
.help         Show documentation for a command, a module, or a function
.install      Install a dependency
.login        Log in to Dagger Cloud
.logout       Log out from Dagger Cloud
.stdlib       Standard library functions
.uninstall    Uninstall a dependency
.update       Update a dependency
.use          Set a module as the default for the session
AVAILABLE MODULE FUNCTIONS
version               -
tag                   -
mod-codegen           When set, module codegen is automatically applied when …
```

shell: consolidate `.doc` and `.help`

---

.dagger/sdk_java.go
sdk/java/runtime/main.go

Align `.dagger/sdk_java` with `sdk/java`.
Fix disable SVE on arm64 machines so we can use java 23 everywhere (align maven and jre images).
Update maven and jre images, smaller, alpine based, less vulnerabilities.

chore(sdk/java): bump maven/java images

---

cmd/dagger/module.go
core/integration/module_cli_test.go
core/schema/modulesource.go

The fallback behavior of these commands when failing to load a module meant that even if a dagger.json was found but completely invalid, we silently went ahead and skipped the module load. The intention was to only fallback when no module was found though.
Those commands now error out as expected in that case.

error out in dagger query/listen if dagger.json totally invalid

---

core/integration/provision_test.go

These had some temp changes that can be cleaned up now that v0.16.1 is out. *Meant* to include this in https://github.com/dagger/dagger/pull/9681 but forgot to force push and it got merged 😄

Update provision tests that use dagger query

---

core/dagop.go
core/integration/container_test.go
core/interface.go
core/object.go
core/schema/container.go
core/schema/middlewares.go
core/schema/wrapper.go
dagql/builtins.go
dagql/call/id.go
dagql/dagql_test.go
dagql/objects.go
dagql/server.go
dagql/types.go
engine/buildkit/containerimage.go
engine/buildkit/op.go
engine/buildkit/worker.go
engine/opts.go
engine/server/server.go
engine/server/session.go

Fixes #6927, enables #9098, and continues the project of rebuilding the Ship of Theseus :tada:
This PR introduces a new way of marrying dagger's dagql and buildkit's LLB. Currently, dagql is used to query the graphql API schema, while LLB is used to query the buildkit dag. dagql is much more flexible and easy to extend, while LLB has significantly better caching behavior.
`DagOp` allows us to combine the best of both worlds. Essentially, it allows us to execute a graphql selection *as a buildkit op* - caching it exactly as a native buildkit operation.
- We inject custom "LLB" by piggybacking on the `Description` map of an existing LLB operation. Then during `ResolveOp`, we transform this into a magical `CustomOpWrapper`. This LLB is very hacky, but such is life :shrug: Without entirely …

feat: add dagop

---

core/contenthash.go

The previous fix in [`867eed9` (#9697)](https://github.com/dagger/dagger/pull/9697/commits/867eed9655330d5f190a98f9ba7efbb9ba6281c1) to use the subdir in the call to `bkcontenthash.Checksum` was actually only a partial fix.
We need to include the subdir in the singleflight group, or we can end up colliding various operations incorrectly and getting the wrong result.
This was the probably cause of the flake in https://v3.dagger.cloud/dagger/traces/e9e01fff1fc51a3a32f60045c0e39d29?span=87741006fe3539fb#87741006fe3539fb:L912
```
Error Trace:    /app/core/integration/module_test.go:4728
/go/pkg/mod/github.com/dagger/testctx@v0.0.4/testctx.go:295
/go/pkg/mod/github.com/dagger/testctx/oteltest@v0.0.2/log.go:37
/go/pkg/mod/github.com/dagger/testctx/oteltest@v0.0.2/trace.go:80 …
```

fix: ensure subdir is used in contenthash singleflight key

---

core/cache.go
core/container.go
core/error.go
core/file.go
core/git.go
core/service.go
core/socket.go
core/typedef.go

These don't *seem* to be used, and also... conceptually, they shouldn't be. For the most part, these structs shouldn't be getting directly serialized, but the labels imply that they are.
We're really inconsistent with this anyways (as noted multiple times previously), so let's just remove them.

chore: remove cargo-culted json labels on core types

---

docs/current_docs/cookbook/cookbook.mdx
docs/current_docs/cookbook/snippets/clone-git-repository/php/.gitattributes
docs/current_docs/cookbook/snippets/clone-git-repository/php/.gitignore
docs/current_docs/cookbook/snippets/clone-git-repository/php/composer.json
docs/current_docs/cookbook/snippets/clone-git-repository/php/composer.lock
docs/current_docs/cookbook/snippets/clone-git-repository/php/dagger.json
docs/current_docs/cookbook/snippets/clone-git-repository/php/entrypoint.php
docs/current_docs/cookbook/snippets/clone-git-repository/php/src/MyModule.php
docs/current_docs/cookbook/snippets/copy-dir/php/.gitattributes
docs/current_docs/cookbook/snippets/copy-dir/php/.gitignore
docs/current_docs/cookbook/snippets/copy-dir/php/composer.json
docs/current_docs/cookbook/snippets/copy-dir/php/composer.lock
docs/current_docs/cookbook/snippets/copy-dir/php/dagger.json
docs/current_docs/cookbook/snippets/copy-dir/php/entrypoint.php
docs/current_docs/cookbook/snippets/copy-dir/php/src/MyModule.php
docs/current_docs/cookbook/snippets/copy-modify-dir/php/.gitattributes
docs/current_docs/cookbook/snippets/copy-modify-dir/php/.gitignore
docs/current_docs/cookbook/snippets/copy-modify-dir/php/composer.json
docs/current_docs/cookbook/snippets/copy-modify-dir/php/composer.lock
docs/current_docs/cookbook/snippets/copy-modify-dir/php/dagger.json
docs/current_docs/cookbook/snippets/copy-modify-dir/php/entrypoint.php
docs/current_docs/cookbook/snippets/copy-modify-dir/php/src/MyModule.php

Adds PHP snippet examples to the cookbook page.
Here are the steps I'm using to create the snippets - maybe verbose but would be worth looking at making this a Dagger function to automate in the future?
1. Run the following
```bash
cd docs/current_docs/cookbook/snippets/<example_name>
mkdir php
cd php
dagger init --sdk php --name my-module
```
2. Update the example to match the other languages
3. Remove the following files: `docs/current_docs/cookbook/snippets/<example_name>/php/README.md`
> Note: If you are running `yarn run start` you might get compilation errors (below) from the `vendor` dir README.md
<details>
</details>

docs: add PHP examples to cookbook

---

core/integration/testdata/nested-c2c/main.go
core/schema/wrapper.go
dagger.json
dagql/idtui/frontend_pretty.go
dagql/objects.go
engine/distconsts/consts.go
go.mod
go.sum
modules/go/main.go

Should fix #9759 (temporarily, hopefully go 1.24.1 will have a fix for this).
Not a simple revert commit, since we've started using new features :cry: (however, this PR should be easily revertable later on)

chore: revert back to using go 1.23

---

core/integration/module_test.go
core/schema/git.go
engine/session/gitcredential.go

I don't really have context for why this was added (somewhere in https://github.com/dagger/dagger/pull/8805), but it's definitely not right, resulting in *always* setting a completely incorrect auth token.
See the following:
$ GIT_TERMINAL_PROMPT=0 SSH_ASKPASS=echo git credential fill <<EOF
protocol=https
host=github.com
EOF
protocol=https
host=github.com
username=Username for 'https://github.com':
password=Password for 'https://Username%20for%20%27https%3A%2F%2Fgithub.com%27%3A%20@github.com':
This outputs the prompts into the username/password fields, instead of *correctly* erroring out, and not attaching this as an authentication token.
I'm not actually sure if this was causing user-facing bugs, but I hit this while working on a total refactor of the git implementation.

fix: don't set `SSH_ASKPASS` to `echo`

---

modules/alpine/main.go

Wolfi made a change that causes glibc triggers to require busybox triggers having already run:
https://github.com/wolfi-dev/os/commit/8229c0379cada98fb9504dd19a068dbbe2bd0d98
This isn't obviously wrong, but our current alpine module likely runs triggers in a slightly different order and we thus end up with a glibc trigger running, trying to execute /usr/bin/sh and then failing because the busybox symlink (created in its trigger) hasn't been installed yet.
The fix here is a quick hack to unblock. Will look at something more robust to follow up with.

quick fix to wolfi build errors to unblock failing engine builds

---

.dagger/sdk_java.go
core/integration/testdata/modules/java/construct/dagger.json
core/integration/testdata/modules/java/construct/pom.xml
core/integration/testdata/modules/java/defaults/dagger.json
core/integration/testdata/modules/java/defaults/pom.xml
core/integration/testdata/modules/java/fields/dagger.json
core/integration/testdata/modules/java/fields/pom.xml
sdk/java/runtime/main.go
sdk/java/runtime/template/pom.xml
sdk/java/runtime/template/src/main/java/io/dagger/modules/daggermodule/DaggerModule.java
sdk/java/runtime/template/src/main/java/io/dagger/modules/daggermodule/package-info.java

Improve versioning to prepare the publication of the different components to maven central.
Related to #9194 
> [!WARNING]
> **Breaking change**
> This requires some changes in your module source code.
>
> In order to allow the build of the module to be successful, you need to define a property in the module's `pom.xml` to set the different versions:
> - set the property `dagger.module.deps` (the value can be anything at first, a `dagger develop` will update it)
>
>     ```xml
>     <dagger.module.deps>0.16.3-template-module</dagger.module.deps>
>     ```
>
> - set the version of `io.dagger:dagger-java-sdk` and `io.dagger:dagger-java-annotation-processor` to this property. Be careful, the `dagger-java-annotation-processor` is set two times, one time as a dependency, one time as the …

chore(sdk/java): improve versioning

---

modules/alpine/main.go

Did a bit more research and realized [the hack](https://github.com/dagger/dagger/pull/9800) to ensure busybox symlinks exist in time for glibc's trigger actually may be necessary to get compatibility w/ apko's behavior.
Basically, it turns out that apko
1. [doesn't run scripts](https://github.com/chainguard-dev/apko/blob/3e63d01bb69480954b6040f5470197aead3f81da/pkg/apk/apk/implementation.go#L587-L589)
2. [has it's own little hack to create busybox symlinks](https://github.com/chainguard-dev/apko/blob/3e63d01bb69480954b6040f5470197aead3f81da/pkg/build/build_implementation.go#L181-L189)
Which is why https://github.com/wolfi-dev/os/commit/8229c0379cada98fb9504dd19a068dbbe2bd0d98 broke us but not apko.
Change here just updates the comment and cleans up the code, since it seems like it …

alpine: update busybox symlink install hack

---

docs/docusaurus.config.ts

All of the links from X look like the below image, this change uses the new dagger-factory.jpg icon for social sharing to make the links posted on X look more interesting. Hopefully this makes the link more interesting to capture the users attention.
1. Adds default descriptions and image urls for social sharing
2. Sets default metadata description - default is to use the second heading (e.g. the docs landing page description is "what is Dagger"). Individual markdown pages can still override the description using markdown front matter
3. Updates the default image URL to be complete as it's better for links (I believe its actually required)
Sharing docs links on X screenshot:
Updated links will look like the following:

docs: Improves metadata and tags for better social sharing and SEO

---

README.md

Adds cloud-trace.gif to the README to provide a visual representation of Dagger Cloud tracing.

Add Dagger Cloud GIF to README for visualization

---

.github/dagger.json
.github/main.go
.github/workflows/engine-cli.gen.yml

We spoke about this with Erik, Justin & Connor a few times in the last few weeks, and the consensus is that we want all Engine tests to run against **dev** Engines (the next version that ships), and there is marginal value in running them against an already released version.
The thinking goes that if all tests continue running the same (or better) in the next version of Dagger, then we are confident in the upcoming release.
While we might want to do the same for all other jobs in this workflow, we want to take a smaller step since we are planning to try out a different CI runner type.

ci: Run all Engine & CLI tests against a dev engine only

---

docs/current_docs/index.mdx

Adds cloud-trace.gif to the introduction to provide a visual representation of Dagger Cloud tracing.

Add Dagger Cloud GIF to intro for visualization

---

core/dagop.go
core/git.go
core/schema/git.go
core/schema/wrapper.go

This was *probably* causing flakes, and had the potential to cause big issues. Should hopefully fix the issue noted in https://github.com/dagger/dagger/pull/9730#discussion_r1989264862.
Essentially, for remote operations we were caching twice:
- The DagOp for the `Git.tree` operation (with a cache key of the git ID)
- The underlying git operation (with a cache key of the git commit) This was very confusing to think about, and probably could have resulted in lots of weird cache issues.
The simple fix here is to just remove the extra DagOp layer when caching remote git sources, and to take more manual control over DagOp caching in this case.
Ideally! We would have core interfaces, which would then allow us to have different specializations of `GitRef` and `GitRepository` at the dagql …

fix: prevent double buildkit caching on remote git operations

---

modules/compatcheck/go.mod
modules/compatcheck/go.sum
modules/compatcheck/main.go

`golang.org/x/exp/rand` has been deprecated and scheduled to be deleted.
Reference: golang/exp@f9890c6
Reference: https://go.dev/doc/go1.22#math_rand_v2

chore(modules/compatcheck): replace `golang.org/x/exp/rand` with `math/rand/v2`

---

core/llm_test.go

it checks all the current supported variables are being parsed correctly as well as the fact that the file://.env is being parsed also

llm: add basic tests to check llm config loading

---

docs/current_docs/agents.mdx
docs/docusaurus.config.ts

Touching up some small paper cuts:
1. Adds meta tags to make LinkedIn shares more visually appealing (https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdocs.dagger.io%2F)
2. Adds descriptions to key pages for better SEO

docs: add linkedin meta tags, description to ai agents

---

docs/current_docs/agents.mdx

Adds a link to the technical-content-summarizer example agent.

docs: add technical-content-summarizer example agent

---

sdk/typescript/dev/dagger.json
sdk/typescript/dev/node/dagger.json
sdk/typescript/dev/node/src/commands.ts
sdk/typescript/dev/node/src/index.ts
sdk/typescript/dev/src/index.ts

Update Typescript `dev` & `node` modules
- Correctly set `useEntrypoint`
- Update version
- Correctly export class
I tested it with https://docs.dagger.io/ci/quickstart/simplify using `dagger call publish --source=https://github.com/dagger/hello-dagger` and it works fine.

fix: typescript dev node modules

---

.changes/unreleased/Added-20250302-205618.yaml
core/integration/module_typescript_test.go
docs/current_docs/configuration/modules.mdx
sdk/typescript/runtime/main.go

Adds support for the bun.lock text format released in Bun 1.2.0 [bun.sh/blog/bun-v1.2#introducing-bun-lock](bun.sh/blog/bun-v1.2#introducing-bun-lock). This is Bun's new default.
I can't seem to get the test suite and SDK generation working, I've tried from the docs.
```sh
dagger call sdk typescript generate export --path=.
```
Running `go test` in `src/core` passes though.
Any advice on finishing up the PR would be appreciated, I'll look at the changie stuff and commit that shortly.

Include support for bun.lock (text based) that was released in Bun 1.2.0

---

.dagger/build/builder.go
modules/go/main.go

While in the area and trying to get debugging symbols back in, realized that this would be pretty useful.

chore: use go module for building dagger engine

---

.changes/unreleased/Changed-20250317-102936.yaml
.dagger/config.go
cmd/dialstdio/main.go
cmd/engine/config.go
cmd/engine/main.go
core/integration/engine_test.go
docs/current_docs/ci/integrations/argo-workflows.mdx
docs/current_docs/ci/integrations/snippets/argo-workflow.yaml
docs/current_docs/ci/integrations/snippets/gitlab-runner-config.yml
docs/current_docs/ci/integrations/snippets/tekton-dagger-task.yaml
engine/consts.go
helm/dagger/templates/engine-daemonset.yaml
helm/dagger/templates/engine-statefulset.yaml
modules/compatcheck/main.go
modules/daggerverse/main.go

For less confusion and more consistency in naming, this updates the engine listener to use `unix:///run/dagger/engine.sock`.
For now, I'm leaving around the old `unix:///run/buildkit/buildkitd.sock` too to avoid backwards incompatibility. The two socks are just different listeners for the same server so there's no harm in both existing for now.
This updates everywhere I could find `buildkitd.sock` across Helm charts, various docs on integrations, etc. So it's worth a double check those all look correct to others now.

update default engine unix sock to /run/dagger/engine.sock

---

docs/current_docs/agents.mdx

Getting rid of dagger/agents links so we can archive that repo

move agent examples from dagger/agents to {owner}/agents

---

docs/current_docs/agents.mdx

Removes the laravel-assistant link to avoid confusion until a complete example and video are available.

docs: remove the laravel-assistant link

---

.github/actions/call-ci-alt-runner/action.yml
.github/workflows/_dagger_on_depot_local_engine.yml
.github/workflows/_dagger_on_depot_remote_engine.yml
.github/workflows/_dagger_on_magicache_remote_engine.yml
.github/workflows/_dagger_on_namespace_local_engine.yml
.github/workflows/_dagger_on_namespace_remote_engine.yml
.github/workflows/_dagger_on_x1_nvme.yml
.github/workflows/_dagger_on_x1_tmpfs.yml

After all Alternative CI jobs started failing since #9673, this introduces a separate `call` action which is only used by these alternative CI runners. We want something simpler that has a separate lifecyle from the main `call` action that we use in the primary CI runners.
The problem with the current `call` action logging config is that GitHub Actions UI breaks, as well as the Namespace UI, so troubleshooting the source of this issue is very difficult.
I even downloaded the logs locally, which did not make it easier to find the issue. FTR:
~/Downloads/logs_35440011783 on ☁️
❯ ls -lah
total 264M
drwx------ 11 gerhard staff        352 Mar 10 19:24  .
drwxr-xr-x 59 gerhard _lpoperator 1.9K Mar 10 19:24  ..
-rw-rw-r--  1 gerhard staff        28M Nov 30  1979 …

ci: Add a simpler `call` action for Alternative CI Runners

---

docs/current_docs/cookbook/snippets/continue-after-errors/go/main.go

This should have been done with https://github.com/dagger/dagger/pull/8669, but looks like this change was missed.
Glancing through the cookbook, I can't see any other examples like this.
Thanks to @vikram-dagger for flagging :pray:

docs: use scoped enum in continue-after-errors snippets

---

.github/dagger.json
.github/main.go
.github/workflows/daggerverse-preview.gen.yml
.github/workflows/docs.gen.yml
.github/workflows/engine-cli.gen.yml
.github/workflows/github.gen.yml
.github/workflows/sdks.gen.yml
dagql/idtui/testdata/TestTelemetry/TestGolden/use-no-exec-service

Considering how well this worked for that one job, this PR made the change for all other `testdev-*` jobs in the `Engine & CLI` workflow. FTR:
| Job Name | Before (P99) | After |
|---------|-------------------|-------------------|
| testdev-everything-else | 1220s (20m 20s) | 973s (16m 13s) |
| testdev-cgroupsv2 | 1199s (19m 59s) | 383s (6m 23s) |
| testdev-module-runtimes | 753s (12m 33s) | 770s (12m 50s) |
| testdev-modules | 695s (11m 35s) | 631s (10m 31s) |
| testdev-container | 513s (8m 33s) | 460s (7m 40s) |
| testdev-cli-engine | 505s (8m 25s) | 446s (7m 26s) |
---
LGTM 👍
---
As a follow-up, we might want to fallback to the original runners if the initial runner was to fail for any reason. While I don't think that will mitigate high queue times, it would add a retry mechanism, …

ci: Run testdev-cgroupsv2 in larger & faster CI runners

---

.github/workflows/alternative-ci-runners-1.yml

We have plenty of data re performance characteristics and now want to cost-optimise and stay within a $100/month budget.
Before:
After:

ci: Reduce the jobs that run in Alternative CI Runners 1

---

.changes/unreleased/Changed-20250319-123632.yaml
cmd/dagger/main.go
cmd/dagger/shell.go
cmd/dagger/shell_commands.go
cmd/dagger/shell_completion_test.go
dagql/idtui/frontend_pretty.go
docs/current_docs/reference/cli.mdx

Removed the "Experimental" annotation in `dagger shell` (was shown in `--help`) but kept it hidden to avoid confusion over using `dagger shell` vs `dagger`. May want to expose it anyway.
Hid the following shell builtins:
- Filesystem navigation: `.cd`, `.ls`, `.pwd`
- Scoping: `.stdlib`, `.deps`, `.core`
- Cobra subprocesses: `.install`, `.update`, `.upgrade`, `.login`, `.logout`
This is what remains:
Removed the "Experimental" notice when you start an interactive session (REPL). Could consider the TUI in interactive mode still experimental, while not the entire shell.

shell: bring shell out of experimental

---

dagql/idtui/golden_test.go
dagql/idtui/testdata/TestTelemetry/TestGolden/use-no-exec-service

Follow up from https://github.com/dagger/dagger/pull/9887#discussion_r2002117267.
Looks like it just needed the newline at the end :tada:

tests: scrub redis memory overcommit warning

---

docs/current_docs/examples.mdx
docs/sidebars.ts

Add a new top-level page in docs to list all our examples.

add examples page

---

sdk/python/src/dagger/telemetry.py

This avoids https://github.com/open-telemetry/opentelemetry-python/issues/4461 until https://github.com/open-telemetry/opentelemetry-python/pull/4462 is released.
Fixes https://github.com/dagger/dagger/issues/9764

python: avoid telemetry shutdown issue from upstream

---

.dagger/config.go
.dagger/engine.go
cmd/engine/config.go
cmd/engine/main.go
core/integration/engine_test.go
engine/consts.go
engine/distconsts/consts.go
modules/compatcheck/main.go
modules/daggerverse/main.go

We were using `/var/run/dagger/engine.sock` in a couple of places (after https://github.com/dagger/dagger/pull/9866), so this patch removes those.
Some of them just need to be renamed, but others should be entirely removed - the `--addr` flag shouldn't ever need to manually append the socket, we should automatically always add it.

Ensure consistent `/run/dagger/engine.sock` path

---

cmd/engine/main.go
docs/current_docs/ci/integrations/argo-workflows.mdx
docs/current_docs/ci/integrations/snippets/argo-workflow.yaml
docs/current_docs/ci/integrations/snippets/gitlab-runner-config.yml
docs/current_docs/ci/integrations/snippets/tekton-dagger-task.yaml
helm/.dagger/main.go
helm/dagger/.changes/unreleased/Added-20250314-104048.yaml
helm/dagger/templates/engine-config.yaml
helm/dagger/templates/engine-daemonset.yaml
helm/dagger/templates/engine-statefulset.yaml
helm/dagger/values.yaml

I added a bunch of configuration options that my org is using and I'm hoping to get them into main so that we don't have to rely on my fork moving forward. 
I tried to make sure the values made sense for both statefulset and daemonset modes but I may have missed the mark there. Definitely open to feedback and let me know if I need to break up the PR I know there are a lot of changes.
Summary of changes:
- add support for configuring the Dagger engine via the `engine.json` file.
- Add container port and optionally bind to a host port.
- Add nodeSelector
- Add arbitrary volume mounts
- Add lifecycle preStop hook
- Add podManagementPolicy
- Add option to disable hostPath mount for run and data volumes.
- Add option to use pvc for data volume in StatefulSet

extend dagger helm chart

---

cmd/dagger/shell_commands.go
cmd/dagger/shell_help.go
core/integration/module_shell_test.go

This is an experiment to see if including a module's top-level functions in `.help <module>` makes sense.
Some people asked why `.help <module>` didn’t show top level functions. Short answer is to keep it consistent with `.help <function>` since a `<module>` is basically the first **function** in a module, or its entrypoint (aka, constructor).
The list of a module’s functions comes from the object type that the entrypoint returns: the main object. This is like an object type returned by any other function where you list its functions with:
```shell
<function> | .help
```
So similarly, for a module’s functions:
```shell
<module> | .help
```
If we add the list of functions in a function’s “Returns” section, it’ll distract from the main part of `.help <function> | <module>` which is its …

shell: show available functions in `.help <module>`

---

docs/current_docs/agents.mdx

Uses the default install partial on the agents installation section.

docs: add install partial to agents page

---

core/integration/legacy_test.go
engine/session/git.go
engine/version.go

We haven't actually changed any details of the API - and it's pretty easy to give this as a fallback so that we don't need to bump any engine versions anywhere.
Noted this failure in https://github.com/dagger/dagger.io/pull/4328, where we got the following error while crawling a private module:
```
get module signature: input: moduleSource.asModule failed to get module runtime: failed to query git config: Unimplemented: unknown service Git
```

chore: add git attachable fallback and bump minimum client version

---

docs/sidebars.ts

The Engine API page should live under the Dagger API section, instead of its current location under the Custom Functions section.

docs: Move Engine page one level up in nav

---

cmd/dagger/llm.go
cmd/dagger/shell.go
core/llm.go
core/llm_env.go
core/schema/llm.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
sdk/elixir/lib/dagger/gen/llm.ex
sdk/go/dagger.gen.go
sdk/php/generated/LLM.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

A few experiments:
* Add `LLM.withQuery` for making the whole Query schema available to the LLM
* `loadFooFromID` fields are skipped
* CLI prompt starts from `Query` so you can jump right into action, with module + deps available
* CLI automatically sets `$_` as the current value after a prompt is done
* Inspired by Ruby `irb` which sets `_` to the last value
* Ideally we would do this in shell mode too, not sure how yet
* Un-deprecate `loop`, `withFoo` setters, and `foo` getters for now
* Jury is still out on these, deprecating is a bit harsh (makes them hard to read in Zed)

LLM: `Query` access, `$_` setting, un-deprecate APIs

---

core/integration/module_typescript_test.go
sdk/typescript/runtime/bin/__deno_config_updator.ts
sdk/typescript/runtime/main.go
sdk/typescript/runtime/tsdistconsts/consts.go
sdk/typescript/src/index.ts

Setup to use deno with Dagger:
```
deno init
dagger init --name=test --sdk=typescript --source=.
```
Dagger will automatically update the `deno.json` to support the SDK library.
Integration tests are added.
We do not directly run the test on the library since it's not useful, deno already ensure compatibility with node.
Minimum required `deno.json` to support `dagger`:
```json
{
"imports": {
"@dagger.io/dagger": "./sdk/src/index.ts",
"@dagger.io/telemetry": "./sdk/src/telemetry/index.ts"
},
"workspace": [
"./sdk"
],
"unstable": [
"bare-node-builtins",
"sloppy-imports",
"node-globals",
"byonm"
],
"compilerOptions": {
"experimentalDecorators": true // require for compability with node decorator
},
"nodeModulesDir": "auto"
}
```

feat: add deno support on Typescript SDK

---

docs/current_docs/ci/integrations/podman.mdx
docs/current_docs/troubleshooting.mdx

I faced this issue when running Podman Desktop on my mac. 
Debugging the logs on the container led to an error updating the iptables and this was the fix.
The issue is already documented but it wasn;t obvious it effected me.

Update docs to highlight Podman Desktop on Mac issue

---

.github/main.go
.github/workflows/engine-cli.gen.yml

The first change should make testdev-everything-else complete quicker (it's currently ~17mins).
The second change should make testdev-module-runtimes complete quicker (it's currently ~14mins).

ci: Extract testdev-client-generator + more resources to testdev-module-runtimes

---

docs/sidebars.ts

Removes the double links in the nav to the examples docs page.

docs: remove duplicate examples in nav

---

cmd/dagger/engine.go
cmd/dagger/module.go
core/integration/llm_test.go
core/integration/llmtest/allow-llm.golden
core/integration/llmtest/go-programmer/main.go
core/llm.go
engine/buildkit/client.go
engine/server/session.go
engine/session/prompt.go

this PR adds tests for the `--allow-llm` flag and its associated policies.
in the process of writing these tests I found and fixed a bug in nested client allow-llm propagation that made ExperimentalPrivilegedNesting clients always try to prompt the user  and did a little refactoring to make the code easier to navigate. 
As part of this PR, I intend to:

add TestLLM/TestAllowLLM, TestLLM/TestAPILimit, and fix bug in nested client --allow-llm metadata propagation

---

docs/recorder/main.go

This PR fixes the gif generator module for the documentation. Prior to this fix, the gifs showed a Rust error.
Initially, I thought it was due to a glibc version mismatch between the build and the runtime container, but after some brute force line-by-line debugging, I narrowed it down to the one in this PR.
I don't fully understand why that caused the problem, but it did (along with a number of other issues).

fix: docs recorder runtime rust panic

---

core/integration/module_php_test.go
core/integration/testdata/modules/php/object-kind/built-in-to-dagger/.gitattributes
core/integration/testdata/modules/php/object-kind/built-in-to-dagger/.gitignore
core/integration/testdata/modules/php/object-kind/built-in-to-dagger/composer.json
core/integration/testdata/modules/php/object-kind/built-in-to-dagger/dagger.json
core/integration/testdata/modules/php/object-kind/built-in-to-dagger/entrypoint.php
core/integration/testdata/modules/php/object-kind/built-in-to-dagger/src/BuiltInToDagger.php

Adds 2 tests asserting that the PHP SDK can:
1. Receive an object (built-into-dagger) as an argument.
2. Modify the object.
3. Return the object.
First test asserts it receive and return a `File` with its contents capitalized.
Second test asserts it can receive and return a `Directory` with a new `File` added to it.

test: PHP Object signatures for built-in types

---

core/integration/module_php_test.go
core/integration/testdata/modules/php/object-kind/built-in-to-dagger/dagger.json

Change the test module to _correctly_ point to the local sdk.
This is to assert that the current branch passes tests. 
Also a non-behavioural change, in `module_php_test.go`.

PHP: Small amendments to test data.

---

core/llm_env.go

This was a bit of a halfway measure and is currently detrimental to consistent model behavior.
For example, I've observed:
* needless calls to `readVariable`
* attemps to pass variables as function args
With this change it will instead be 100% focused on objects and their functions. String variables are always just prompt vars, never exposed to the model.

llm: avoid exposing the model to "variables" concept

---

dagql/idtui/frontend_pretty.go

Don't think this is even needed anymore with the scrollback changes. I'm already seeing a blank line beneath it.

remove rogue \n escape

---

core/environment.go
core/llm.go
core/llm_env.go
core/mcp.go

Naively split LLMEnv into two types:
- MCP (LLM-facing frontend)
- Environment (LLM-agnostic backend)
This split is done naively, for the most superficial change possible. The intent is to get this merged quickly, then follow-up with API polish.
TODO:
- Merge variables and bindings
- Bring back function mask (ideally attached to the `Binding` type0

Environment API, part 1

---

core/llm.go

With this change you no longer need to specify the exact model name, you may use either "claude" or "anthropic" in lieu of claude-3-5-sonnet-latest.
Same for other LLM providers.

llm: allow specifying aliases for LLM models

---

cmd/dagger/shell.go
cmd/dagger/shell_fs.go

this lets prompt users `dagger install` modules on the CLI and then manipulate them in prompt mode as though the LLM was acting "inside" the `dagger -m` toplevel module.
there's a alternate approach where we do a bit more and call
```go
def, err := h.getOrInitDef(cfg.Digest, func() (*moduleDef, error) {
return initializeModule(ctx, h.dag, cfg.Source)
})
```
for each dep to initialize it, but at least in my naive implementation that didn't seem to add any additional functionality. @TomChv speculated that that route might allow us to wire in shell completions. Not sure which way is more correct, thoughts @helderco?
i want to automated-test this, but it's proving difficult because of conflicting requirements between needing a TTY to manipulate prompt mode, but also needing historyJSON from …

serve dependences for shell prompt mode

---

core/llm.go
core/llm_openai.go
core/llm_test.go

Some engines are not able to managed tools and streaming at the same time, like llama.cpp.
This allows to define an environment variable to disable streaming:
OPENAI_DISABLE_STREAMING
This uses strconv.ParseBool so 1, t, T, TRUE, true, True will set disable the streaming while 0, f, F, FALSE, false, False will keep it.
By default streaming is not disabled.
Streaming will be disabled only if tools are used. If a query doesn't define any tools, streaming will be used.
Fixes #9969

allow to disable streaming on OpenAI compatible engines

---

go.mod
go.sum

https://github.com/openai/openai-go/releases/tag/v0.1.0-beta.3
Full changelog: https://github.com/openai/openai-go/compare/v0.1.0-beta.2...v0.1.0-beta.3

deps: bump openai-go to v0.1.0-beta.3

---

engine/client/secretprovider/libsecret.go
engine/client/secretprovider/secretprovider.go
go.mod
go.sum

This was scratching an itch :laughing: 
On my laptop, I use GNOME, which provides `gnome-keyring` for storing passwords/keys, etc - it's fairly neat, and integrates with the desktop environment to prompt for the unlock password, etc. I can use it to store encrypted passwords for things like API keys, etc.
To do this, we can integrate with `libsecret`, which allows accessing this info. This is pretty much as close to a standard as there is across Linux desktop environments, it's also supported in KDE by KWallet for example (though I haven't personally tried that).

feat: add libsecret provider

---

docs/current_docs/api/llm.mdx

Add the missing end backquote around `Write()` in LLM environments
Before:

add missing backquote around write

---

.changes/unreleased/Fixed-20250331-125002.yaml
cmd/dagger/shell.go
cmd/dagger/shell_exec.go
cmd/dagger/shell_state.go
core/integration/module_shell_test.go

Reported in [Discord](https://discord.com/channels/707636530424053791/1354863326907334736/1355202111171985558).
This fixes an issue where state was getting deleted when using a variable in the same run (same prompt or in non-interactive mode):
```console
❯ dagger -c 'dir=$(directory); $dir | entries; $dir | name'
Error: tried to access non-existent state "R2MDGQFTJ74TAAXBA26SBGHZXF"
```

shell: fix state getting deleted when using a var in the same run

---

.changes/unreleased/Fixed-20250331-161142.yaml
cmd/dagger/main.go
core/integration/module_shell_test.go
docs/current_docs/reference/cli.mdx

Fixes https://github.com/dagger/dagger/issues/10009
If the root command has positional arguments we check if it’s an existing file. If it isn’t, return an error before passing it on to `dagger shell`. This way we can still offer suggestions on a subcommand typo:
```
❯ dagger qery
Error: unknown command or file "qery" for "dagger"
Did you mean this?
query
exit status 1
```
Note that I added “or file” to the error that the root command returned by default.

shell: fix executing a script from the root command

---

core/mcp.go
core/object.go

Manual test so far by just asking an LLM what tools it has available when given an object that has a bunch of fields:
```go
type Toy struct {
Foo *dagger.Container
Bar *dagger.Directory
Baz *dagger.File
}
func New() Toy {
return Toy{
// Build a base container optimized for Go development
Foo: dag.Container().
From("golang").
WithDefaultTerminalCmd([]string{"/bin/bash"}).
WithMountedCache("/go/pkg/mod", dag.CacheVolume("go_mod_cache")).
WithWorkdir("/app"),
Bar: dag.Directory(),
Baz: dag.Directory().WithNewFile("hello.txt", "Hello, world!").File("hello.txt"),
}
}
func (m *Toy) Echo(stringArg string) *dagger.Container {
return dag.Container().From("alpine:latest").WithExec([]string{"echo", stringArg})
}
```
When asked what tools it has says:
```
│🤖 I'll explain all the tools available to …
```

automatically mask fields on user module objects from mcp tools

---

core/llm.go

Fixes 10032. Initializes `once` when LLM is created

fix nil dereference issue on LLM type

---

dagql/idtui/frontend_pretty.go

Currently the prompt has a blank line above it and then the keymap to the right of it. So this fixes that. (Tested locally.)

tui: fix yes/no prompt linebreak location

---

core/env.go

With this fix, `env | with-file-output foo description | output name` now returns `foo` instead returning an empty result.

env: fix missing output binding key

---

docs/current_docs/features/llm.mdx
docs/current_docs/features/mcp.mdx
docs/current_docs/quickstart/basics/index.mdx
docs/current_docs/quickstart/ci/index.mdx
docs/netlify.toml

This commit
- changes /quickstart/basics to /quickstart
- adds a redirect for the above
- adds a redirect for all /ci/quickstart/* URLs to /quickstart/ci
- ~~adds a redirect for /features/llm to /features/large-language-model~~ updates existing page URL from /features/large-language-model to previous URL /features/llm

docs: Add redirects and fix some URLs

---

cmd/dagger/mcp.go

This enables the user to run `dagger mcp` without specifying the progress option -- and adds safeguards on user progress flags mismatch:
- Fails if `progress=tty` in non-tty environment:
```shell
➜  dagger_dev mcp --progress tty -m github.com/shykes/hello | cat
Error: cannot use tty progress output: it interferes with mcp stdio
```
- Enforce progress plain when `tty=auto` 
```shell
➜  dagger_dev mcp -m github.com/shykes/hello                     
overriding 'auto' progress mode to 'plain' to avoid interference with mcp stdio
```
cc @tiborvass

mcp: override 'auto' progress mode to 'plain'

---

.dagger/docker.go
core/llm.go
core/mcp.go
dagql/idtui/frontend_pretty.go
engine/buildkit/client.go
engine/session/prompt.go
engine/session/prompt.pb.go
engine/session/prompt.proto
hack/build

Now when a model ends its turn without returning the requested outputs, and the user has passed `-i`, we'll prompt the user to help the model out.
(Credit to @cwlbraa who started on this in #9978 - preserved a sign-off on the commit!)

llm: support `-i`/`--interactive`

---

core/llm_google.go

Fixes https://discord.com/channels/707636530424053791/1326978746703548416/1356698322399789309
The Google Gemini API returns a googleapi: Error 400 if the request includes an empty tools declaration (e.g., [{ FunctionDeclarations: [] }]). Previously, the code always included the tools parameter, even if there were no functions to declare, resulting in invalid requests.
This fix ensures the tools parameter is only sent when there is at least one valid function declaration. This change resolves the API error and aligns with Gemini’s request format.
cc @tiborvass

fix(llm): Avoid sending empty tool declarations to Gemini API

---

.changes/unreleased/Changed-20250403-130048.yaml
cmd/dagger/shell_exec.go
cmd/dagger/shell_state.go
core/integration/module_shell_test.go

Fixes https://github.com/dagger/dagger/issues/7678
Also allows nested quotes, as reported in [Discord](https://discord.com/channels/707636530424053791/1356989954676363557).
**Spread commas**
```
✔ container | from alpine | with-exec -- echo trivy fs --scanners vuln,misconfig,secret | stdout 2.4s
trivy fs --scanners vuln misconfig secret
```
**Nested quotes**
```
✘ container | from alpine | with-exec -- sh -c 'echo "hello world"' | stdout
! function "with-exec": invalid argument "echo \"hello world\"" for "--args" flag: parse error on line 1, column 6: bare " in non-quoted-field
```
```
✔ container | from alpine | with-exec -- echo trivy fs --scanners vuln,misconfig,secret | stdout 1.2s
trivy fs --scanners vuln,misconfig,secret
✔ container | from alpine | with-exec -- sh -c 'echo "hello …
```

shell: skip CSV flag parsing when spreading `with-exec` positional arguments

---

engine/client/buildkit.go

due to what it seems to be a bug in the buildkit client initialization
when using stdio (TBC), bumping the default connect timeout from 3s to 10s
so ssh connections work

client: bump min connect timeout to 10s

---

helm/dagger/templates/engine-daemonset.yaml

Fixed the indentation in `helm/dagger/templates/engine-daemonset.yaml` for the `secretRef` block
Fixes #10065

fix: use correct indentation for magicache.secretName

---

.dagger/sdk_java.go

As of today, the file created by the `Generate` function is never used and needs to be removed by hand.
This commit removes the creation of those useless schema.json files.

chore(sdk/java) skip generation of schema.json files

---

core/integration/legacy_test.go
core/schema/service.go
core/service.go
core/services.go
core/services_test.go

Found while working on some improved tests in #9381, when I discovered that some tests were mistakenly missing from `LegacyTest`.
Essentially, what I wanted to test was - `AsService.Up` works, and `Container.Up` works. But in this test, I end up calling these within the *same* session. I think at some point maybe this *used* to work, but now we have this logic: https://github.com/dagger/dagger/blob/504787f4370a4032788161af0defdcb8b64bd17f/core/services.go#L145-L148
The key we use for started services is the session ID - but a started tunnel is local to the client. So the call to `Up` succeeds the second time it's called, but a new tunnel is never actually created.
The solution here is:
- Use the `SessionID` for keying normal Services.
- Use the `ClientID` for keying tunnels (which are …

Use ClientID for keying started tunnels

---

core/schema/directory.go

Follow-up from https://github.com/dagger/dagger/pull/9118.
When we mixed in slashes here, we *should* have ensured that we updated the view. Otherwise, we could encounter the following scenario:
- Module A uses v0.16.0 (no trailing slashes), and calls `Directory.entries` on a directory.
- Module B uses v0.17.0 (has trailing slashes), and calls `Directory.entries` on the same directory.
If this all occurs within the same session (or across the whole engine once https://github.com/dagger/dagger/pull/9682 is merged), then these calls will generate the same ID - and the wrong result will leak between these (in a racy way).
The correct way to solve this problem is to ensure that these generate different IDs (which we can do by manually using `dagql.AllVersion`).

fix: ensure that we use views with trailing slash methods

---

core/integration/client_test.go
core/integration/container_test.go
core/integration/dind_test.go
core/integration/directory_test.go
core/integration/file_test.go
core/integration/secret_test.go
core/integration/services_test.go
core/integration/suite_test.go
internal/testutil/query.go

The new util is a bit more ergonomic in many situations by using generics to return results directly.
This was mostly done by Claude, with human touch-ups.
Follow-up from here: https://github.com/dagger/dagger/pull/9682#discussion_r2021729577

replace integ test Query usage w/ QueryWithClient

---

cmd/dagger/mcp.go

Fixes #10097
When exposing a module over mcp, dagger didn't expose the module type's actual description to the MCP client. The fix now shows the actual module description
- What do we want to show when there is no module description ?
cc @tiborvass

mcp: show proper description for top-level module

---

.github/main.go
.github/workflows/engine-cli.gen.yml

So that we see how the initial infrastructure compares to the new runners after a week (or two?).
| Job Name | Before | After |
|---------|-------------------|-------------------|
| testdev-cli-engine | 7m 56s | 8m 45s |
| testdev-client-generator | 8m 29s | 8m 25s |
| testdev-container | 8m 51s | 8m 48s |
| testdev-everything-else | 14m 13s | 14m 51s |
| testdev-LLM | 5m 59s | 6m 47s |
| testdev-module-runtime | 12m 42s | 14m 12s |
| testdev-modules | 11m 34s | 11m 27s |
---
As discussed with @sipsma @jedevc earlier today.

ci: Switch back Engine & CLI to initial CI runners

---

cmd/dagger/shell_completion.go
cmd/dagger/shell_completion_test.go

Fixes https://github.com/dagger/dagger/issues/10107.
This is my first PR, please let me know if I am missing something. 
This PR addresses bug where the shell was crashing due to a slice bounds out of range [1:0] error in `dispatchCall`, caused by accessing `args[0]` when `call.Args` is empty.

fix: handle empty argument case in shell completion

---

docs/current_docs/cookbook/snippets/mount-dir/python/main.py
docs/current_docs/cookbook/snippets/mount-dir/typescript/index.ts
docs/current_docs/cookbook/snippets/mount-file/python/main.py
docs/current_docs/cookbook/snippets/mount-file/typescript/index.ts

Follow-up from https://github.com/dagger/dagger/pull/10074
This is currently broken on `main`:
- https://v3.dagger.cloud/dagger/traces/978148f6e9e50d1e5eb8b427067a3de5
- https://v3.dagger.cloud/dagger/traces/acb32e58ce53918ea8591cd952ae23c9

docs: fix linting in new python/typescript snippets

---

.changes/unreleased/Added-20250410-180705.yaml
cmd/dagger/mcp.go
cmd/dagger/module_inspect.go

This adds a `--core` flag to the MCP command, allowing the env to optionally expose the core API as an MCP server
| Module Present | Core Present | Exposed Tools     | Outcome       |
|----------------|--------------|------------------------|----------------|
| ✅             | ✅           | SDK + Core             | ✅ Success      |
| ✅             | ❌           | SDK only               | ✅ Success      |
| ❌             | ✅           | Core only              | ✅ Success      |
| ❌             | ❌           | None                   | ❌ Error        |
Co-authored-by: @tiborvass 
`dagger_dev mcp --core`
cc @jpadams

mcp: add ability to expose core API as tools

---

cmd/dagger/mcp.go

When rebasing #10090 (and fixing the conflicts), I mistakenly removed the fix from #10111.
cc @tiborvass

fix: mcp module description regression

---

.changes/unreleased/Added-20250410-190818.yaml
core/integration/module_cli_test.go
core/schema/modulesource.go

Fixes #9203
- Fixes panics and errors on operations made on modules initialized with no sdk
Co-authored-by @tiborvass

core(fix): load a module with no SDK

---

docs/current_docs/cookbook/cookbook.mdx

The snippets tab shows Python code for SSH in both cases. This updates the sample code tab to show the correct code.

docs: Edit python clone-git-repo shown in code tab

---

core/integration/secret_test.go
engine/client/secretprovider/secretprovider.go
engine/client/secretprovider/vault.go

This PR adds the support for ttl in secrets provider. Currently it is only supported for vault (as we are caching only vault secrets at the moment).
Also, I noticed we support only kv based secrets in vault, and we can possibly extend the secrets provider to also support dynamic cred engines such as `aws`, `postgres` etc, but that is out of scope for this work item, so just putting it out here for the record.
This PR still needs a design review/approval from the team. cc @marcosnils

feat(engine/secret): add support for ttl for vault

---

cmd/codegen/generator/go/templates/src/_types/object.go.tmpl
cmd/codegen/introspection/introspection.go
sdk/go/dagger.gen.go

Fixes #10084.
Since we do special opts structs for go, this only applies for this special case - we don't need it in typescript or python.

feat: add default value comments for go

---

.changes/unreleased/Fixed-20250415-174815.yaml
cmd/dagger/shell_exec.go
cmd/dagger/shell_fs.go
core/integration/module_shell_test.go

Reported by user in [Discord](https://discord.com/channels/707636530424053791/1361372104083378176/1361372104083378176).
`Directory` and `File` arguments weren't resolving relative paths correctly before passing on to the flag.

shell: fix relative arguments in Directory and File flags

---

.dagger/README.md

accidentally removed in #10172

ci: bring back docs instructions to ci README

---

docs/current_docs/api/llm.mdx
docs/current_docs/quickstart/agent/index.mdx
docs/current_docs/quickstart/agent/snippets/go/dagger.json
docs/current_docs/quickstart/agent/snippets/go/main.go
docs/current_docs/quickstart/agent/snippets/java/dagger.json
docs/current_docs/quickstart/agent/snippets/java/src/main/java/io/dagger/modules/codingagent/CodingAgent.java
docs/current_docs/quickstart/agent/snippets/php/dagger.json
docs/current_docs/quickstart/agent/snippets/php/src/CodingAgent.php
docs/current_docs/quickstart/agent/snippets/python/dagger.json
docs/current_docs/quickstart/agent/snippets/python/src/coding_agent/main.py
docs/current_docs/quickstart/agent/snippets/typescript/dagger.json
docs/current_docs/quickstart/agent/snippets/typescript/src/index.ts

As of 0.18.3 the core types like `Container` are more reliable to use directly. This removes the need to use something like `toy-workspace` for a simple agent like the quickstart.
For more advanced agents a focused tools module is still important. This will come up in the new agent quickstarts part 2 and 3.
Test with:
```
dagger call -m github.com/dagger/dagger/docs@pull/10167/head server up
```

simplify agent quickstart to not require toy-workspace

---

.github/workflows/publish.yml

There's currently a bug in v0.18.3 that frequently causes the publish job to error out due to some unhandled cases involving cross-session cache hits and `+private` state.
This will be fixed separately, but in order to avoid this problem during the release of v0.18.4 this change moves the Publish job to run on a single-tenant engine so that it doesn't have any other sessions connected that can cause the bug.
Generally speaking, running the Publish job on a single-tenant engine is probably a safer setup anyways since failures during publish can be particularly painful, so I think this is probably a good change to keep around even after v0.18.4.

run publish job on single-tenant engine

---

engine/buildkit/client.go
engine/buildkit/ref.go
engine/session/terminal.go
engine/session/terminal.pb.go
engine/session/terminal.proto

Partial fix for https://github.com/dagger/dagger/issues/10129, by improving the error message - it still doesn't work, but actually informs the user that it isn't supported.
Previously, we were often returning invalid terminals from the `OpenTerminal` function. This could happen because gRPC does not actually wait for the call to `Session` to complete - instead, any errors returned (like the one that reports that the user can't open a terminal in a `--progress=plain` session) is actually returned on the first call to `Recv`.
To handle this, we now send a void `Ready` message, and wait to receive that - this allows us to correctly receive the error, which we can then correctly propagate upwards to inform the user what really went wrong.

fix: graceful failure when opening terminals

---

docs/current_docs/features/security.mdx

Just a typo in the `Security - Secrets` documentation.

fix(docs): secrets typo

---

cmd/init/main.go
sdk/elixir/test/dagger/client_test.exs

Technically, we *are* error handling, we should take these errors and print them nicely, and exit correctly.
We've had bug reports that mention the `panic`, and interpret it as being a dagger internal error. This seems fair, `panic` should be reserved for exceptional + unrecoverable scenarios (not ones that can be caused by users by passing bad input, like trying to execute a program that's not in the `PATH`).

fix: don't panic in cmd/init

---

.changes/unreleased/Fixed-20250416-105341.yaml
core/integration/cross_session_test.go
core/schema/llm.go
dagql/cachekey.go

`Query.llm` had no custom cache key, so it was getting cached across sessions after v0.18.3 added the engine-wide dagql cache. This mean that per-session config like `*_MODEL` env vars, model keys, etc. could get re-used if one session was open and another came in and tried to use `llm` too.
This updates the cache key of `llm` to be per-session. Also added integ test coverage for this now.

cache llm APIs per session to avoid cross-session reuse of config

---

engine/distconsts/consts.go
modules/go/main.go

A bunch of `TestClientGenerator` tests started consistently failing out of band, turns out this is because:
1. gqlgen did a [release](https://github.com/99designs/gqlgen/releases/tag/v0.17.71) 19h ago where their [go.mod specifies go 1.23.8](https://github.com/99designs/gqlgen/blob/master/go.mod#L3)
2. dagger's go toolchains are on go 1.23.6
3. Some of the `TestClientGenerator` tests init an empty go.mod
4. The custom client generator code doesn't make any attempt to pin to our go sdk dep versions, it runs `go mod tidy` and thus picks up latest releases for everything 
5. We then error out at the point of trying to use the go.mod
We obviously need a fix to the client generator code to handle this better, but wasn't immediately obvious so sending out this quick and easy PR to unblock …

upgrade go 1.23.6->1.23.8

---

docs/current_docs/_examples_agents.mdx

Updates the 404 link on Melvin to the right repository.

docs: update melvin link

---

.dagger/build/builder.go

When running Dagger with Kata Containers one will want to avoid using virtio-fs and direct attach a block volume to the container, which will then require `e2fsprogs` in order to properly `mkfs.XYZ ...` the block device before getting it to actually be mounted and used ae `/var/lib/dagger`.
Of course, this is far from a "normal" use-case, but right now there's no way to use the Dagger engine without either modifying Kata Containers itself or re-building the Dagger image ... and both options are less optimal than simply adding `e2fsprogs` to the engine image.

build: Add e2fsprogs to the dagger image

---

.changes/unreleased/Fixed-20250421-145347.yaml
cmd/init/main.go
engine/buildkit/executor.go
engine/buildkit/executor_spec.go
engine/server/session.go

Follow-up to https://github.com/dagger/dagger/pull/10162
Still saw an occurrence of the flake, but this time it's because the healthcheck failed 2 times in a row rather than closed early due to a bug: https://v3.dagger.cloud/dagger/traces/64ca948ee08ce288105b158ab8889321?span=8960846c5fe9627d&logs#8960846c5fe9627d:L245
At first I tried disabling the grpc healthchecks entirely, but that just peeled back another layer and revealed more problems where grpc was calling the dialer multiple times (not good when we are just operating off a single pre-made conn); I suspect that the grpc healthchecks were inadvertently acting as something like a keep-alive and/or otherwise tweaking something about the grpc connection state that resulting in it never being closed.
Either way, all that nonsense is …

connect nested session attachables through http API

---

.changes/unreleased/Fixed-20250421-145534.yaml
core/container_exec.go
core/integration/module_test.go
core/modfunc.go
core/schema/module.go
core/schema/modulesource.go
engine/buildkit/executor.go
engine/server/session.go

Module initialization (when we ask the runtime for what type defs it has) previously got just enough data to support checking the current module name, but basically nothing else. This is because the module is not yet fully constructed during initialization.
This update results in as much of the module being available during init as is possible. This should cover various cases like:
1. access to dag.CurrentModule().Source()
2. creating execs during module initialization (which previously panicked because the instance ID was empty)
* also check for that condition that created a panic and error instead, just in case that codepath can be triggered some other way

fix current module during initialization

---

.changes/unreleased/Fixed-20250421-174513.yaml
core/llm.go

Fixes https://github.com/dagger/dagger/issues/10151
`withModel` was not loading env vars from the main client in the same way that the `llm` constructor was, so calling `withModel` didn't result in any auth being loaded along with the reset model.
This updates `withModel` to load the router in the same way as the constructor so API keys are loaded consistently.
---
Tested manually so far since I don't *believe* our integ tests support any actual calls with real API auth keys.
Tested by repro'ing the original report in discord:
```go
package main
import (
"context"
"dagger/test/internal/dagger"
)
type Test struct{}
func (m *Test) Broke(ctx context.Context, model string) (string, error) {
return dag.LLM().WithModel(model).WithPrompt("testing").LastReply(ctx)
}
func (m *Test) Works(ctx …
```

fix `llm.withModel` usage from a module

---

.changes/unreleased/Fixed-20250421-145654.yaml
core/integration/cross_session_test.go
core/interface.go
core/modfunc.go
core/module.go
core/object.go
dagql/call/argument.go
dagql/objects.go
dagql/server.go
dagql/types.go

Replacement for https://github.com/dagger/dagger/pull/10175 as this PR solves the problem there plus some more general ones w/ a completely different approach.
New case of contextual dirs causing cache problems was noticed by @cwlbraa where he was hitting old local code when running integ tests w/ `test specific`
* See `TestCrossSessionContextualDirChange` integ test added in this PR for a minimal repro of that situation
The only real fix for this is to tackle the problem of contextual dirs not actually counting towards the cache key of function calls, which turns out to not be a very obscure case after all. Solving this problem also fixes the issue w/ `+private`.
Gist of the problem:
* Contextual dirs+files aren't loaded until the actual implementation of module function invocation
* …

make contextual dir vals count towards cache key

---

.changes/unreleased/Fixed-20250421-163041.yaml
.changes/unreleased/Fixed-20250421-180136.yaml
.changes/unreleased/Fixed-20250421-193832.yaml
core/integration/cross_session_test.go
core/integration/module_call_test.go
core/integration/secret_test.go
core/postcall.go
core/schema/sdk.go
core/secret.go
engine/server/client_resources.go

Bundling together a few tangentially related fixes for secret transfer here:
* Fix for issue brought up in [discord](https://discord.com/channels/707636530424053791/1363438107722125382) where trying to load a module sourced from a private git repo could fail when the cache is hit
* Fix for "buildkit session not found" errors when calling `.Plaintext` on a URI-based secret from a module function call
* Fix for handling of empty plaintext secrets (previously we incorrectly assumed when no plaintext it was a URI-based secret)
I split these up by commit, so see individual commits w/ changelog+tests for more context

secret transfer fixes

---

core/integration/testdata/modules/typescript/ifaces/impl/tsconfig.json
core/integration/testdata/modules/typescript/ifaces/test/tsconfig.json
dagql/idtui/viztest/typescript/tsconfig.json
docs/current_docs/api/snippets/modules/testing/typescript/tsconfig.json
docs/current_docs/quickstart/agent/snippets/typescript/tsconfig.json
sdk/typescript/.changes/unreleased/Added-20250418-045435.yaml
sdk/typescript/dev/node/tsconfig.json
sdk/typescript/dev/tsconfig.json
sdk/typescript/runtime/bin/__tsclientconfig.updator.ts
sdk/typescript/runtime/bin/__tsconfig.updator.ts
sdk/typescript/runtime/template/tsconfig.json
sdk/typescript/src/module/registry.ts

* strict mode prevents a lot of bugs allowed with default typescript settings and is recommended for all typescript projects.
* skipLibCheck is generally recommended to improve typescript speed by not typechecking dependencies
* fixed a type issue in the `@argument` decorator that was caught by strict mode

chore: Enable strict and skipLibCheck settings in tsconfigs

---

.github/dagger.json
.github/main.go
.github/workflows/evals.gen.yml
modules/evaluator/workspace/main.go
modules/gha/workflow.go

* only run when relevant files change (currently running on every merge :money_with_wings:)
* stop testing `gpt-4o` (4.1 effectively replaces it, not worth 2x cost)

rein in evals cost

---

.dagger/build/sdk.go
.github/workflows/benchmark.yml
sdk/python/.changes/unreleased/Fixed-20250423-175445.yaml
sdk/python/runtime/discovery.go
sdk/python/runtime/main.go

Fix older modules using `requirements.lock`, not vendoring the client library appropriately. This created a breaking change (sorry about that!).
To mitigate this affected users can **either**:
- Continue on v0.18.3 or older and wait for v0.18.5
- Migrate to uv (`uv add --editable ./sdk`)
- Add the following section to `pyproject.toml`:
```toml
[tool.uv.sources]
dagger-io = { path = "sdk", editable = true }
```
Fixed a typo that prevented the codegen executable to be bundled correctly. It's not a problem because it's a new thing, but it also means no one is taking advantage of it.
Also decided to revert the pinning based on engine version. Need more time to flush it and test it. Shouldn't cause any issue for users because the vendoring ignores the version constraint.
Finally, noticed that …

python: fix issues in v0.18.4

---

docs/current_docs/ci/adopting.mdx

The URL is 'community-sdk' singular.
I hope this is helpful. Dagger looks great!

docs: Fix link on 'Day 2' page

---

core/client_resource.go
core/integration/cross_session_test.go
core/integration/secret_test.go

The module digest mixed into the cache key for secrets created in function calls was not stable (per-client), this fixes it to be the stable module source digest. This ensures that secrets created in function calls don't invalidate cache of anything they are included in every call.

use stable module digest for secrets created in functions

---

sdk/elixir/dagger.json
sdk/elixir/dev/lib/elixir_sdk_dev.ex
sdk/elixir/dev/mix.lock
sdk/elixir/runtime/main.go

Changes to `elixir-sdk` module:
* Bump Elixir to 1.18.3 with Erlang/OTP 27.3.3.
* Run `dagger develop`.
Changes to `elixir-sdk-dev` module:
* Bump Elixir to 0.18.3 with Erlang/OTP 27.3.3
* Reformat code in `elixir-sdk-dev` module.
* Run `dagger develop`.

feat(sdk/elixir): bump Elixir image to 1.18.3

---

docs/current_docs/ci/integrations/kubernetes.mdx

https://deploy-preview-10262--devel-docs-dagger-io.netlify.app/ci/integrations/kubernetes/#tested-configurations
I validated SUSE RKE2 on SLE Micro 6.1 on AWS with our Helm chart in standard daemonset config.
-idempotent `helm upgrade`s
-`helm uninstall` and then re-install
-`dagger` tests including modules, shell, LLM
Previously I had validated Helm install on Rancher Desktops Kubernetes as well
Noted our continuous test of the Helm chart with K3s in CI
Also noted our success with EKS

docs: tested kubernetes section

---

dagql/idtui/frontend.go

This was displaying using the dark style when in light mode, which was giving unreadable results.
Before:
After:

fix: highlight shell content based on current theme

---

cmd/dagger/engine.go
dagql/dagui/opts.go
dagql/idtui/frontend_plain.go
dagql/idtui/frontend_pretty.go

handles better the case where the client gets an error when sending
telemetry. If the --debug flag is supplied, all errors are displayed as
they were before this change
before:
after:

don't spam the output when sending telemetry upload fails

---

docs/current_docs/configuration/engine.mdx

The page about engine configuration currently gives the engine container image as `registry.dagger.io/engine:0.18.4`.
This PR changes it to `registry.dagger.io/engine:v0.18.4`
See the snippet:
```bash
docker run --rm \
-v /var/lib/dagger \
-v $HOME/.config/dagger/engine.json:/etc/dagger/engine.json \
--name dagger-engine-custom \
--privileged \
registry.dagger.io/engine:0.18.4
```
From: https://docs.dagger.io/configuration/engine/

docs: fix engine image tag

---

engine/vcs/vcs_test.go

This fixes a failing test on `main`, see the first failure on https://github.com/dagger/dagger/commit/9fc751cd479a784828f7ea7a449bb2927997ff13: https://v3.dagger.cloud/dagger/traces/ec1bf6d77b4fdcf9253779adf8b6d5fa?showHidden=5b532095ad9f9342#726a64406e7856a2:L81
```
--- FAIL: TestRepoRootForImportPath (1.56s)
vcs_test.go:300: RepoRootForImportPath("git.sr.ht/~jacqueline/tangara-fw/lib"): unrecognized import path "git.sr.ht/~jacqueline/tangara-fw/lib"
```
SourceHut looks to have added go-away, which adds a challenge to all pages - including the `?go-get` query pages used by go tooling to determine repos. This seems(?) to have entirely broken access to `git.sr.ht` when using `GOPRIVATE` (to disable the go proxy).
This seems to be a breaking change that prevents all go modules on source hut …

tests: skip source hut tests

---

docs/src/components/VideoPlayer.tsx

Instead of manually capturing events, this commit switches to use PostHog's autocapture to automatically track clicks on the play/pause button, with additional metadata for the video file and title. This also eliminates video click events appearing twice in the PostHog activity log.
https://posthog.com/docs/product-analytics/autocapture

docs: Use autocapture for video player

---

core/integration/client_generator_test.go
sdk/typescript/runtime/bundled_static_export/module/index.ts
sdk/typescript/runtime/clientgen.go
sdk/typescript/runtime/config.go
sdk/typescript/runtime/sdk_module_fs.go

I noticed during a demo that if a module source is `.` and  implements functions and also generate a client, the `sdk/index.ts` file will not expose the generated client in the `sdk` folder because it doesn't expect it to be there.
I changes the logic in the runtime to handle this specific edge case and updated integrations tests.
This behaviour could be handled in the codegen binary ideally but it's a quick fixes for now.

fix: typescript clien gen conflict with module

---

.github/main.go
.github/workflows/engine-cli.gen.yml

We have seen a speed-up after the initial switch https://github.com/dagger/dagger/pull/9887, and a slow-down after we went back https://github.com/dagger/dagger/pull/10086.
If we still see a speed-up after this switch, we are likely to want to stick with this for more than a few weeks.
As discussed with @sipsma in the last sync.
---
| Job Name | Before (P90 2w) | After (single run) |
|:--------|-------------------|-------------------|
| testdev-everything-else | 1016s (16m 56s) | `TODO` [FYI](https://github.com/dagger/dagger/pull/10248#issuecomment-2839991924) |
| testdev-module-runtimes | 851s (14m 11s) | 817s (13m 37s) |
| testdev-container | 768s (12m 48s) | 459s (7m 39s) |

ci: Switch a subset of Engine & CLI jobs to alt CI runners

---

.changes/unreleased/Fixed-20250430-111645.yaml
cmd/dagger/functions.go
core/integration/module_call_test.go

Closes https://github.com/dagger/dagger/issues/10298 [^1]
This fixes a regression introduced in https://github.com/dagger/dagger/pull/7417 where conflicting flags no longer throw an error in `dagger call`. 
Full explanation in https://github.com/dagger/dagger/issues/10298#issuecomment-2840466435.
[^1]: Fixes the missing error to clear confusion but the underlying problem of supporting a conflicting flag is in another duplicate [issue](https://github.com/dagger/dagger/issues/7032).

cli: fix regression in dagger call when a function argument conflicts with an existing flag

---

sdk/java/runtime/main.go

Set the sharing mode of the maven cache volume to lock.
This ensure there's no concurrent write to the cache that should limit
the risk of corruption of maven files, as concurrent access to the maven
local repository is not supported.
Error looks like:
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-install-plugin:3.1.2:install
(default-install) on project dagger-sdk-parent: Failed to install
metadata io.dagger:dagger-sdk-parent/maven-metadata.xml:
Could not parse metadata
/root/.m2/repository/io/dagger/dagger-sdk-parent/maven-metadata-local.xml:
in epilog non whitespace content is not allowed but got 0 (position:
END_TAG seen ...</metadata>\n0... @13:2)
To lock the cache might have an impact in term of performances in case
of concurrent access, but it will keep good …

sdk/java: lock concurrent access to maven cache

---

core/mcp.go

fixes https://github.com/dagger/dagger/issues/10328
in the future we'll probably want to add this back in and make it configurable, but we can wait for user requirements to clarify in the absence of a default truncation, and maybe introduce `.contents(line-number ranges)` or native grep apis in the mean time.

remove llm tool result truncation

---

core/env.go
core/integration/client_generator_test.go
core/moddeps.go
core/schema/query.go
core/schema/sdk.go
dagql/types.go

Update `__schema` to take as argument optional
types thay may be hidden from the API.
Update `schemIntrospectionJSONFile` to hide `Host` when generating for module.
Add host call tests in client generator.

feat: expose Host in generated client

---

core/integration/cross_session_test.go
dagql/idtui/testdata/TestTelemetry/TestGolden/use-no-exec-service
dagql/idtui/viztest/main.go

This was causing flakiness in tests when the detector went off (e.g. https://v3.dagger.cloud/dagger/traces/1df689be91b6f1d837af53ff3cd62b41?span=4acfd90e58c43f70&logs)

fix `err` overwrite causing data race detector failures in integ tests

---

.dagger/sdk_elixir.go
sdk/elixir/dev/.formatter.exs
sdk/elixir/dev/lib/elixir_sdk_dev.ex

Changes to `elixir-sdk-dev` module:
* Introduce the `init` function that accepts the SDK source directory and the container.
* Convert all functions to accept self object and uses it.
* Add `.formatter.exs` file to add formatting option.
Changes to dagger `ElixirSDK`:
* Modify to uses new `elixir-sdk-dev` module.
* Drop base method since it's moved to `elixir-sdk-dev` module.
* Drop Elixir version matrix. It doesn't uses for a long time.
* Remove unused constant.

feat(sdk/elixir): dogfooding Elixir SDK self object

---

sdk/elixir/dev/lib/elixir_sdk_dev.ex

The ElixirSdkDev set the working directory `/sdk` while the `t.Dagger.Source` is `/sdk/elixir` cause a publish function write to incorrect place.
Tested by add a terminal debugger before calling `hex.publish and call `dagger call sdk elixir publish --tag=0.18.6 --dry-run`, then cat the `mix.exs` file, the `@version` must be updated to 0.18.6.

fix(sdk/elixir): fix publish failure on 0.18.6

---

.github/workflows/alternative-ci-runners-4.yml

The current runners are giving us results around 4 minutes for the first job.  Those specific runners are using nested virt atop of Intel SPR or EMR.
We're now switching to using nested virt atop of AMD CPUs, as we're getting results closer to 3m30s with those, instead of the Intel ones.
Let's switch the runners for now to use the AMD ones, while we keep working on shaving the time down more and more with different approaches. :-).
cc @gerhard

ci: alt-runners-4: Update the runner

---

docs/current_docs/configuration/modules.mdx

This is implemented [here](https://github.com/dagger/dagger/blob/3af6558837398cd3377013d4a54712441eb080f5/sdk/typescript/runtime/config.go#L333).

docs(deno): deno is selected as runtime if deno.lock is present

---

core/integration/testdata/nested-c2c/main.go
engine/distconsts/consts.go
go.mod
modules/go/main.go

Take 2! go 1.24.3 has the fix for SIGSEGV in `vgetrandomPutState`.
Fixes https://github.com/dagger/dagger/issues/9759.
Related:
- first take to 1.24.0: https://github.com/dagger/dagger/pull/9673
- reversion back to 1.23: https://github.com/dagger/dagger/pull/9766

chore: bump go to 1.24.3

---

docs/current_docs/api/constructors.mdx

This moves an important, and often overlooked, note on making struct fields public in Go and Typescript to before the code example - not after. 
This helps clarify the docs to resolve https://github.com/dagger/dagger/issues/10347

docs: reorg note on public fields for visibility

---

dagql/idtui/golden_test.go

Fixes https://github.com/dagger/dagger/issues/10233
The `CACHED` label for container constructor calls are extremely uninteresting and can easily be CACHED or not based on whether anything else connected to the engine is using `Container`s (these are dagql in memory cache hits), so just attempting to scrub it.

scrub whether container constructor is cached from telemetry tests

---

engine/version.go

We now use the `IncludeDependencies` arg unconditionally in the CLI (see https://github.com/dagger/dagger/pull/10118) - but this arg was only introduced in v0.18.6, so we should error cleanly if there's a mismatch here.

chore: bump minimum engine version to v0.18.6

---

core/integration/module_call_test.go
core/integration/module_shell_test.go

As we discovered recently, errors can cache between two sessions when they're active at the same time. This is a pain, and should probably be considered a bug - see #10320.
However, these tests shouldn't be failing - we've had this behavior *forever*, it's not a new failure. It's also not what we're testing, the flakes just add to our CI noise - we're aware it's an issue, and we should fix it (and add a test specifically for it).

tests: avoid flake from error caching

---

cmd/dagger/engine.go
cmd/dagger/main.go
cmd/dagger/mcp.go
cmd/dagger/run.go
dagql/idtui/frontend.go
dagql/idtui/frontend_plain.go
dagql/idtui/frontend_pretty.go
engine/client/client.go

This makes debugging MCP in certain environments easier by providing a way to log the dagger cli's stdin/stdout/stderr.

mcp: log std{in,out,err} to files specified by DAGGER_LOG_STD{IN,OUT,ERR} envvars

---

docs/plugins/llms-txt-plugin/index.ts

I found #10089 bring llms-full.txt into doc site. But some link in llms-full.txt not right. So this pr correct it.

docs: improve llms-full.txt with right site path

---

.dagger/main.go
cmd/dagger/llm.go
core/llm.go
core/schema/llm.go
dagger.json

fixes https://github.com/dagger/dagger/issues/10356
~this also uncomments the evals so we can run `dagger call evals` now that the appropriate APIs are released. note these don't build a dagger-in-dagger dev engine so you usually wanna use em with `./hack/dev`.~ commented again because we keep changing the api :)
TODO:

lazy LLM api key loading/model selection

---

sdk/python/.changes/unreleased/Fixed-20250512-152354.yaml
sdk/python/codegen/src/codegen/generator.py
sdk/python/tests/codegen/test_generator.py

This fixes a regression, reported in [Discord](https://discord.com/channels/707636530424053791/1369680570917060740).
If user had a function named "sync" returning a leaf value in a dependency, it was getting generated as the special case "sync" functions we have in core.
Dependency:
```python
from dagger import function, object_type
@object_type
class Dep:
@function
def sync(self) -> str:
return "hello world"
```
Caller module:
```python
from dagger import dag, function, object_type
@object_type
class MyModule:
@function
async def test(self) -> str:
return await dag.dep().sync()
```
Calling:
```
❯ dagger -c test
```
Result:
```diff
- ! Coroutine factory method dagger.client.gen.Dep.sync() return <dagger.Dep object at 0xffff6ff73610> was expected to be of type <class 'str'>.
+ hello world …
```

python: fix incorrectly generated "sync" function in codegen

---

.github/actions/call/action.yml

Follow-up to https://github.com/dagger/dagger/pull/10395

ci: fix publish job to use v0.18.7

---

cmd/engine/.dagger/build/builder.go
cmd/engine/.dagger/main.go
modules/go/main.go

Was staring a lot at engine build traces today for unrelated reasons and noticed a few pieces of extremely low-hanging fruit in our various modules related to building the engine. Together they trim ~5-10s from an engine build based on some local runs, so not life-changing but enough to send out quick.
See individual commit messages for details.

Minor engine build optimizations

---

sdk/elixir/dagger_codegen/lib/dagger/codegen/introspection/types/field.ex
sdk/elixir/dagger_codegen/lib/dagger/codegen/introspection/types/type_ref.ex
sdk/elixir/dagger_codegen/lib/mix/tasks/dagger.codegen.ex
sdk/elixir/dagger_codegen/test/support/renderer_case.ex

Replace all `:json` with Elixir `JSON` standard library and drop `:null` handling because the `JSON` convert to `nil` automatically.
Updates #7444

refactor(sdk/elixir): replace :json with JSON in dagger_codegen

---

cmd/dagger/module.go

Running `dagger develop path/to/module` is an easy typo - however, it's not valid, you need to use the `-m` flag. This didn't error out though, we just accepted any additional args and ignored them.
We should explicitly forbid args to these functions if we're not using them, which will help prevent typos.

fix: ensure dagger develop/publish do not take args

---

cmd/dagger/engine.go
cmd/dagger/functions_cloud_test.go
cmd/dagger/main.go
engine/client/drivers/cloud.go
internal/cloud/client.go

> [!WARNING]
> This is a highly **EXPERIMENTAL** feature. One day, all Dagger Cloud users **might** be able to use this. We expect this to change before it becomes available to everyone.
This flag requires that the CLI:
- is connected to Dagger Cloud
- has an org set (e.g. `dagger login <YOUR_CLOUD_ORG>`)
- that org must have the `CLOUD_ENGINES` feature enabled (or be a `Dagger-Internal` org)
This flag provisions a Cloud Engine just-in-time, connects to it and then runs all subsequent operations in it. **ALL** commands will work exactly the same, just that they will run against this Cloud Engine which is configured with:
- `16 vCPUs`
- `32GB RAM`
- `100GB NVMe storage`
> [!NOTE]
> If the CLI is a development version, the Engine provisioned will be `main` (a.k.a. latest development).
By …

cli: Add --cloud flag (EXPERIMENTAL)

---

.changes/unreleased/Fixed-20250521-235914.yaml
cmd/dagger/shell_exec.go
core/integration/module_shell_test.go

You could previously prefix anything with an underscore and it would just be stripped out. So `_container` would execute `container`. However this was only intended to give access to the interpreter's own builtins, like `_echo`. Now `_container` should error since it doesn't exist.

shell: fix usage of `_` prefix not being reserved for interpreter builtins

---

.dagger/sdk_rust.go
sdk/rust/crates/dagger-bootstrap/src/cli_generate.rs

This changeset changes the `dagger-bootstrap` to generate code from `codegen` introspection.json instead of fetch it from Dagger directly.

refactor(sdk/rust): use introspection.json from codegen binary

---

core/cache.go
core/container.go
core/directory.go
core/env.go
core/file.go
core/llm.go
core/mcp.go
core/service.go
core/util.go

We can use a lot of the functions from the new slices/maps packages, and a lot of these patterns have other ways of doing them in more modern go.
Some of this is just dead code as well.

chore: cleanup core/util.go

---

docs/current_docs/quickstart/agent/inproject.mdx
docs/current_docs/quickstart/agent/snippets/part2/agent/go/agent.go.snippet
docs/current_docs/quickstart/agent/snippets/part2/agent/java/agent.java.snippet
docs/current_docs/quickstart/agent/snippets/part2/agent/php/agent.php.snippet
docs/current_docs/quickstart/agent/snippets/part2/agent/python/agent.py.snippet
docs/current_docs/quickstart/agent/snippets/part2/agent/typescript/agent.ts.snippet
docs/current_docs/quickstart/agent/snippets/part2/workspace/go/main.go
docs/current_docs/quickstart/agent/snippets/part2/workspace/java/src/main/java/io/dagger/modules/workspace/Workspace.java
docs/current_docs/quickstart/agent/snippets/part2/workspace/php/src/Workspace.php
docs/current_docs/quickstart/agent/snippets/part2/workspace/python/src/workspace/main.py
docs/current_docs/quickstart/agent/snippets/part2/workspace/typescript/src/index.ts
docs/current_docs/quickstart/agent/snippets/part3/agent/python/agent.py.snippet
docs/current_docs/quickstart/ci/index.mdx
docs/current_docs/quickstart/ci/snippets/python/__init__.py

here's the change i'll be pushing to the 'agents in an existing project' guide today https://github.com/kpenfound/hello-dagger-py/pull/3
context:
- we will not have self-calling shipped before the workshop and hack night next week
- agent reliability with privileged env is not great,
- copying the existing test function into the workspace and removing the privileged env greatly increases reliability even though it is not a very clean solution (the agent is no longer using "the same tools" that devs use)

docs: agent guide: use test func in workspace instead of privileged env

---

.dagger/sdk_elixir.go
core/integration/module_elixir_test.go
core/integration/testdata/modules/elixir/constructor-function/.formatter.exs
core/integration/testdata/modules/elixir/constructor-function/.gitattributes
core/integration/testdata/modules/elixir/constructor-function/.gitignore
core/integration/testdata/modules/elixir/constructor-function/dagger.json
core/integration/testdata/modules/elixir/constructor-function/lib/constructor_function.ex
core/integration/testdata/modules/elixir/constructor-function/mix.exs
core/integration/testdata/modules/elixir/constructor-function/mix.lock
sdk/elixir/.changes/unreleased/Added-20250522-003959.yaml
sdk/elixir/dev/dagger.json
sdk/elixir/lib/dagger/mod.ex
sdk/elixir/lib/dagger/mod/module.ex
sdk/elixir/test/dagger/mod/module_test.exs
sdk/elixir/test/dagger/mod/object_test.exs
sdk/elixir/test/support/object_mod.ex

Once `init` function is define, the SDK turns that function into constructor function.
And also improve test coverage on converting an Elixir module into Dagger module.
Closes #10437

feat(sdk/elixir): add support for constructor function

---

core/container.go
core/dagop.go
core/git.go
core/schema/container.go
core/schema/wrapper.go
core/telemetry.go
core/util.go
engine/buildkit/op.go
engine/buildkit/output.go

This PR extends the dagop concept introduced in https://github.com/dagger/dagger/pull/9395 to a `ContainerDagOp` which allows using dagops on containers, mapping all mounts correctly :tada:
See example usage in https://github.com/jedevc/dagger/compare/container-dagop...jedevc:dagger:container-dagop-magic?expand=1.
Intended to be used in:
- https://github.com/dagger/dagger/pull/10435
- https://github.com/dagger/dagger/pull/10457

feat: add container dagop

---

.dagger/main.go
.github/main.go
.github/workflows/daggerverse-preview.gen.yml
.github/workflows/docs.gen.yml
.github/workflows/engine-cli.gen.yml
.github/workflows/github.gen.yml
.github/workflows/helm.gen.yml
.github/workflows/sdks.gen.yml

We have been hitting networking issues in AWS, this should address them and also speed things up. Let's check this before merging.
Also, use the platform cache across the SDK jobs since it seems to speed **each** job up by a good few minutes.
---
Note: wait for these results before merging (approve is fine).

ci: Migrate the remaining jobs to an alternative CI runner

---

cmd/dagger/shell_commands.go
cmd/dagger/shell_env.go
core/integration/module_shell_test.go

Adds a new builtin command for `.printenv` that optional accepts an argument of the specific variable to show. If no argument is provided, it will print all available env vars in the shell using the interpreter.
Resolves #10021

shell: add .printenv builtin command for showing env variables

---

dagql/idtui/golden_test.go

This is just the minimum viable change to fix the data race on `main`.
We currently lock in the _user_ of the `dagui.DB` instead of in the `dagui.DB` itself; in practice this race doesn't occur since it's guarded by the mutex in the `Frontend`.
It could be worth considering pushing this down into the `DB` but I've been here before and previously decided it's better to let the `DB` consume things as fast as possible and trust the caller to synchronize more coarsely.
So, this change just continues the status quo and adds a lock to the OTLP receiver in the tests.

idtui: fix data race in TestTelemetry

---

core/container.go
core/directory.go
core/file.go
core/schema/container.go
core/schema/git.go
core/schema/http.go
core/service.go
core/services.go

No need to track these separately.

chore: use dagql.Instance in service binding

---

sdk/elixir/.changes/unreleased/Fixed-20250603-024039.yaml
sdk/elixir/mix.exs

ex_doc uses `:source_url` and `:source_ref` for deducing source links but it was not relative to the `sdk/elixir` folder
using `:source_url_pattern` seems to solve this issue #10515

fix(sdk/elixir): exdoc source_url now pointing to correct link

---

core/integration/directory_test.go
core/schema/directory.go

WithSymlink didn't correctly pass along the directory path which would cause the directory to reset to /

fix: WithSymlink didn't store the dir path

---

docs/.dagger/main.go
docs/dagger.json

This includes fixes for various hacks, and drastically improves the caching - now it actually works, so it won't trigger a whole build from scratch every single time.
See:
- https://github.com/levlaz/daggerverse/pull/14 https://github.com/levlaz/daggerverse/pull/15
- https://github.com/levlaz/daggerverse/pull/13

ci: update docusaurus module

---

docs/current_docs/api/snippets/services/use-endpoint/typescript/index.ts

Failures came from https://github.com/dagger/dagger/pull/10492.
See https://dagger.cloud/dagger/traces/9f28b4b977d3ee22b55842681c312e13#578a2f8af50a3c52.
```
/docs/current_docs/api/snippets/services/use-endpoint/typescript/index.ts
12:9   error  'endpoint' is never reassigned. Use 'const' instead                       prefer-const
12:44  error  Replace `"port":·80,·"scheme":·"http"` with `·port:·80,·scheme:·"http"·`  prettier/prettier
✖ 2 problems (2 errors, 0 warnings)
2 errors and 0 warnings potentially fixable with the `--fix` option.
```

docs: fix ts linting

---

dagql/dagui/db.go

Previously we used links to represent cause and effect, and we always wanted to see the effect (exec) status/logs represented by the causal span instead (Container.withExec).
Now links are multi-purpose, and we don't want to unilaterally skip showing spans that have links. At this point this check is entirely redundant since all the spans we don't want to see already mark themselves `passthrough`. (following https://github.com/dagger/dagger/pull/8442)

dagui: fix outdated link logic

---

core/directory.go
core/schema/service.go
core/util.go
dagql/introspection/types.go
dagql/server.go

Importantly! It's *never* correct to use this `View` to determine how to do compat. The view there is used as the default for graphql queries, but everything else uses the `ID.View` or the `Selector.View`.
To understand why, imagine the following scenario:
- In server A (using version A), we call a field and get back an ID which has `ID.View = A`
- Later on, in server B (using version B), we attempt to load this ID.
While we make sure that we select the field+inputs correctly according to view `A` in this case, *if the result is not cached and we need to recompute it*, the actual implementation will see a server that is using version `B`. Previously, it seems like we may have been getting away with this, just because of caching.
However, when I started adding versioning to the typedefs …

fix: use the current id view for version compat decisions

---

cmd/engine/.dagger/build/builder.go
core/integration/cacert_test.go
engine/distconsts/consts.go

Fixes the failing `scan` check on main, which is detecting that we're building our CNI binaries with an old go version.
To do this, we need to update alpine, since the older version we're on doesn't have a supported version of go.

ci: ensure cni binaries are built with latest go version

---

core/telemetry.go
dagql/dagui/db.go
dagql/idtui/golden_test.go
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-encapsulated
dagql/idtui/viztest/main.go
sdk/go/telemetry/span.go

Currently there are two issues that lead to bubbling up errors beneath the `connect` span:
1. The error hoisting logic should only continue through `UNSET` spans when we're beneath a failed path
1. The `connect` span, and all other spans using `telemetry.End`, has an `UNSET` status - they should have `OK`
* `UNSET` should only correspond to bare `defer span.End()` usage where the intent is to measure duration without having any impact on success/failure status

ui: fix error hoisting logic and `UNSET` status handling

---

.github/dependabot.yml

Docs: https://docs.astral.sh/uv/guides/integration/dependency-bots/#dependabot
It's GA but there's quite a few open issues:
- https://github.com/dependabot/dependabot-core/issues/10478
- https://github.blog/changelog/2025-03-13-dependabot-version-updates-now-support-uv-in-general-availability/
- https://github.com/astral-sh/uv/issues/2512
- https://github.com/dependabot/dependabot-core/issues?q=is%3Aissue%20state%3Aopen%20uv

python: try new uv.lock support in dependabot

---

core/schema/git.go

Follow up to https://github.com/dagger/dagger/pull/10271.
See @sipsma's comment here: https://discord.com/channels/707636530424053791/1382699979805556798/1384363853764104233

fix: ensure we compute the same cache key for different git auth

---

core/schema/git.go

Reverts https://github.com/dagger/dagger/pull/10599.
Yeah something is pretty dreadfully wrong here. Will properly investigate, but wanna get `main` green again.
See a failed trace: https://dagger.cloud/dagger/traces/8d0c91263b13a3e0b54c636e6bb9af1a

Revert "fix: ensure we compute the same cache key for different git auth

---

.changes/unreleased/Fixed-20250624-133301.yaml
cmd/dagger/shell_exec.go
core/integration/module_shell_test.go

Reported in:
- https://github.com/dagger/dagger/issues/10538#issuecomment-2997207108
Test was using `echo` but it was not properly testing it, so testing with `exit`.
```
❯ dagger -M <<'.'
exit_code=$(container | from alpine | with-exec --expect ANY -- sh -c "exit 5" | exit-code)
.echo "Exited with status code $exit_code"
.exit $exit_code
.
▶ connect 0.4s
● loading type definitions 0.4s
● container: Container! 0.0s
$ .from(address: "alpine"): Container! 1.6s CACHED
● .withExec(args: ["sh", "-c", "exit 5"], expect: ANY): Container! 0.2s
▶ .exitCode: Int! 0.3s
Exited with status code 5
✗ echo $?
5
```

shell: fixed interpreter builtin arguments not being resolved

---

.changes/unreleased/Fixed-20250624-140402.yaml
dagql/idtui/frontend_plain.go

[Comparison](https://gist.github.com/vito/00947008407bebd6c61c8d23eedb77f3) (213 => 53 lines)
This change simply brings the code in line with the pretty frontend. Not sure if this regressed or was always out of sync. :thinking:

fix plain output being way too verbose

---

.changes/unreleased/Fixed-20250625-151600.yaml
dagql/objects.go

The fact that these are happening concurrently is a little smelly, but we should at least avoid the deadlock.

dagql: fix Server.Schema <-> Class.Extend deadlock

---

.changes/unreleased/Changed-20250626-161512.yaml
cmd/engine/main.go
core/integration/cacert_test.go
engine/buildkit/cacerts/cacerts.go
modules/alpine/main.go

[OrbStack will by default automatically put a CA cert in containers](https://docs.orbstack.dev/features/https#between-containers),
including the dagger engine if the user is running on MacOS w/ OrbStack.
This results in the engine seeing a custom CA cert and deciding to
automatically install it in every container. While this works it
introduces performance overhead for a case that is unlikely to be of any
utility.
This therefore disables automatic CA cert installation when the only CA
cert found is the OrbStack one, keeping the default path case for
OrbStack users simpler and more performant.
---
@TomChv noticed this after pulling down [this change](https://github.com/dagger/dagger/pull/10645), so the first commit here also improves some busybox symlink handling in the alpine module. …

ignore CA cert automatically installed by OrbStack

---

core/integration/legacy_test.go
core/integration/module_type_test.go
core/interface.go
core/moddeps.go
core/modfunc.go
core/module.go
core/object.go
core/schema/coremod.go
core/schema/module.go
core/schema/modulesource.go
core/typedef.go

Follow-up to #9518.
- There was an issue where old dagger versions would create an invalid typedef when the enum `name` equaled the enum `value`
Reported by @nipuna-perera in [discord](https://discord.com/channels/707636530424053791/1387452929157632094/1387466805374881863).
- There was an issue where `--help` for enum default values was incorrect.
Reported in #10644.

Various enum member followups

---

cmd/codegen/generator/go/templates/modules.go
core/integration/module_go_test.go

Fixes a regression from https://github.com/dagger/dagger/pull/10594 where the `+default` value itself has a `+`, which was getting parsed incorrectly and resulting in panics like:
```
9   : ┆ ┆ ┆ [0.5s] | internal error during module code generation: runtime error: slice bounds out of range [50:28]
9   : ┆ ┆ ┆ [0.5s] | goroutine 1 [running]:
9   : ┆ ┆ ┆ [0.5s] | runtime/debug.Stack()
9   : ┆ ┆ ┆ [0.5s] | 	/usr/lib/go/src/runtime/debug/stack.go:26 +0x5e
9   : ┆ ┆ ┆ [0.5s] | runtime/debug.PrintStack()
9   : ┆ ┆ ┆ [0.5s] | 	/usr/lib/go/src/runtime/debug/stack.go:18 +0x13
9   : ┆ ┆ ┆ [0.5s] | github.com/dagger/dagger/cmd/codegen/generator/go/templates.goTemplateFuncs.moduleMainSrc.func1()
9   : ┆ ┆ ┆ [0.5s] | 	/app/cmd/codegen/generator/go/templates/modules.go:88 +0x6a
9   : ┆ ┆ ┆ [0.5s] | …
```

go: fix parsing of pragma default with `+` in it

---

core/container_exec.go
core/schema/container.go
core/schema/directory.go
core/schema/git.go
core/schema/http.go
core/schema/wrapper.go
dagql/idtui/testdata/TestTelemetry/TestGolden/docker-build-fail
engine/buildkit/executor_spec.go
engine/buildkit/ref.go

...and other little fixes.
@sipsma points out that this is a code smell: https://github.com/dagger/dagger/blob/14ff07af8b91c091e1f1e7afbf0e01316142f8ca/core/schema/container.go#L918
Reaching into and modifying the instance isn't a great practice, and will become impossible in https://github.com/dagger/dagger/pull/10620. However, we don't *really* need to be returning instances directly from dagop, there's no hard dependency, so we can simplify some of the code here.
The other little fixes are:
- Removing an unused arg from `DagOpContainer`
- Removing stdin from the meta mount - we don't need to smuggle this through that mount anymore, since we control the call site - this lets us clean up the meta mount init (and just reset it to nil).
- Use the simpler wrappers for git ops where …

chore: make DagOp helpers return non-instances

---

sdk/php/src/ValueObject/ListOfType.php
sdk/php/tests/Unit/ValueObject/ListOfTypeTest.php

This is a very small fix that allows
```php
#[ReturnsListOfTypes(new ListOfType('string'))]
public function myCustomFunction(): array { }
```

Fix ListOfType::getSubType can accept ReturnsListOfTypes

---

sdk/typescript/.changes/unreleased/Fixed-20250702-222014.yaml
sdk/typescript/src/module/entrypoint/entrypoint.ts
sdk/typescript/src/telemetry/init.ts

Raised by @marcosnils on Discord: https://discord.com/channels/707636530424053791/708371226174685314/1389235734166114424
Fixed by correctly awaiting `sdk.shutdown` and closing telemetry when an error is thrown since the process is exiting early meaning it's not properly closed by the `connection` finaly logic.

fix: typescript telemetry correctly flush spans on failure

---

core/dagop.go
core/schema/http.go
core/schema/wrapper.go

This wasn't very generic, and was really only for http. We can just call with the internal args there.
FYI @alexcb

chore: remove DagOpData param

---

core/schema/git.go

Reapplies https://github.com/dagger/dagger/pull/10599, should fix https://github.com/dagger/dagger/issues/10638.

Reapply "fix: ensure we compute the same cache key for different git auth"

---

core/integration/client_generator_test.go
sdk/typescript/runtime/clientgen.go
sdk/typescript/runtime/config.go
sdk/typescript/src/api/client.gen.ts

Fix for an issue that I noticed while I was testing the TS SDK in a monorepo setup.
Basically, if your context dir is `/root` and your module that generate the client is in `/root/foo/bar`, the generated content would be in `/root` instead of `/root/foo/bar` (only happens in TypeScript).
This PR fixes that behaviour :)

fix: typescript generated client directory issue

---

dagql/idtui/frontend_plain.go

This prevents output from API calls like `Foo.contents` from showing up in the plain output, where the signal:noise ratio is very poor. (Prior art from the `dots` frontend: https://github.com/dagger/dagger/pull/10617)

plain: ignore verbose logs from API responses

---

cmd/dagger/shell_exec.go

this was causing the deeper error to be hidden, don't think the effect is intended
before:
after:
not really sure if we need that `passthrough=false` flag either, but leaving that one alone since it's at least not harmful (besides the extra noise) and is probably needed for some edge case I'm not aware of

shell: fix errors being hidden by `reveal` attribute

---

cmd/dagger/.dagger/publish.go

And update goreleaser for good measure.
Nix requires cp from coreutils (for reasons, it's annoying). Thankfully, we can just install those. This was added on Friday last week to the nix install script. See an example failure of our pipeline here: https://dagger.cloud/dagger/traces/609f2073c478a1b3e9d3c2fc1787c015#7438f59d4bf0ce5d:EL9

chore: fix broken nix install

---

.changes/unreleased/Fixed-20250709-184653.yaml
core/dagop.go
core/query.go
core/schema/container.go
core/schema/coremod.go
core/schema/directory.go
core/schema/module.go
core/schema/modulesource.go
core/sdk/go_sdk.go
core/sdk/loader.go
core/sdk/module.go
core/sdk/module_client_generator.go
core/sdk/module_code_generator.go
core/sdk/module_runtime.go
dagql/server.go
dagql/session_cache.go
dagql/session_cache_test.go
engine/server/session.go

If the session cache Release method was called while some calls were still running, it was possible for them to only be appended to the list of results after Release was already done, in which case they'd stay in the underlying cache and leak forever.
This adds handling to track when the session cache is closed and release any results that show up after that.
---
This seemed to be resulting in memory leaks. It wasn't perfectly repro-able, but was able to see leaks fairly often just after running tests and canceling them in the middle. I suspect that dag-op refs were more prone to it, likely just due to the timing of their execution in the bk solver, which is extra bad since that also results in leaks of on-disk cache refs.
After this change I can't repro that anymore. Also added some unit …

dagql: fix case where session cache refs are never closed

---

core/git.go
core/integration/git_test.go

Looks like this was a "simple" case of the conditional being the wrong way round. I missed this when working on the conversion to dagop in #9980.
Fixing that though means we need a better way of ensuring that we `doFetch` correctly.
Also realized, we couldn't actually *send* a `depth=0` value using the go sdk :cry: so actually, that entire functionality was just broken (woops, no tests). So instead, we'll also allow negative values here.
TODO:

fix: correctly propagate depth arg to remote clone

---

core/integration/module_test.go
core/modfunc.go
engine/buildkit/errors.go
engine/buildkit/ref.go

We were re-using the same code path for stdout/stderr collection which enforces a 100kb size limit. Applying this to the error extraction resulted in the Error ID also being truncated, which led to errors falling back to the unhelpful `process "/runtime" failed with exit status 2`-esque error.
Example: https://dagger.cloud/dagger/traces/9c9ac34fec07079afbc9b6a737ffacaa
Now we only enforce the limit for stdout/stderr and allow the Error ID to be arbitrarily large.
@sipsma I know you mentioned last time that there's probably a much more elegant way to return errors to avoid the filesystem plumbing, but I didn't quite clock it at the time. This might be a good opportunity to do that instead, but I could use some help with that. If you have a clear idea in mind and it's not too much work feel …

fix Error ID extraction becoming truncated

---

cmd/dagger/main.go

A teeny tiny QoL improvement for when you run Dagger from Claude Code. Right now it uses the plain format which is too overwhelming. It seems to handle `--progress=report` really well.

`CLAUDECODE=1` sets `--progress=report`

---

dagql/dagui/spans.go
dagql/idtui/golden_test.go

Noticed the v3 UI was choking on traces generated by dev engines, because `encoding/gob` can't handle `[]any`. `SpanSnapshot`s get sent over the wire with `encoding/gob` for performance reasons; it's generally safe because we control both sides (client + server), so we don't need to worry about schemas and compatibility drift, but it does restrict what types we can feed into it.

dagui: use `json.RawMessage` for extra attrs

---

sdk/typescript/yarn.lock

See https://avd.aquasec.com/nvd/cve-2025-7783.
Fixes the failing `scan` check on main https://dagger.cloud/dagger/traces/bb970b092c345c761dbd619de5b126de#63e5bbe9c59ba8bd:EL331

chore: update form-data to v4.0.4

---

cmd/dagger/main.go
dagql/dagui/db.go
dagql/dagui/opts.go
dagql/dagui/types.go
dagql/idtui/golden_test.go
dagql/idtui/testdata/TestTelemetry/TestGolden/broken-dep/use-broken
dagql/idtui/testdata/TestTelemetry/TestGolden/broken/broken
dagql/idtui/testdata/TestTelemetry/TestGolden/call-bubbling-dep
dagql/idtui/testdata/TestTelemetry/TestGolden/fail-log
dagql/idtui/testdata/TestTelemetry/TestGolden/typescript/fail-log

* error origins could sometimes not be wired up depending on span receiving order
* engine version scrubber choked on the `v` in `-dev`

fix a couple of `TestTelemetry` flakes

---

cmd/codegen/generator/go/templates/module_enums.go
cmd/codegen/generator/go/templates/src/_types/enum.go.tmpl
core/integration/module_call_test.go
core/integration/module_go_test.go
core/integration/module_type_test.go
sdk/go/dagger.gen.go

Fixes https://github.com/dagger/dagger/issues/10715.
This doesn't mean these values have become allowed, the engine will *still* reject them. However, now, they can correctly be used in private fields again, like they used to be.

fix: allow serializing/deserializing empty strings as enums

---

engine/cache/cache.go

CI hit an error in the cache unit tests, locally I could repro it in ~2 runs when running w/ `-count=100000`, so unclear if it was really causing any genuine problems.
Was a legit problem though; with the right timing it was possible to remove a call from internal maps when there were waiters remaining, which would result in extra calls appearing.

fix race condition in cache when context canceled

---

core/schema/modulesource.go

Fixes #10785 
Repro script for reference:
```
set -e
mkdir repro
cd repro
cat >dagger.json <<'.'
{
"name": "test",
"engineVersion": "v0.18.14",
"blueprint": {
"name": "not-main",
"source": "github.com/shykes/x/not-main@test",
"pin": "6b29f8aa297117bc06181050cab1b067c4927c6d"
}
}
.
dagger call -q hello
dagger update
dagger call -q hello
cat dagger.json
```

bugfix: preserve git ref and subdirectory when updating blueprint

---

core/integration/module_elixir_test.go
core/integration/testdata/modules/elixir/defaults/lib/defaults.ex
sdk/elixir/.changes/unreleased/Fixed-20250729-002032.yaml
sdk/elixir/lib/dagger/mod/object/defn.ex

This changeset fix default value in Elixir doesn't set properly when default value declared via `:default` option.
Now if user declare a signature like:
```elixir
defn sample(hello: {String.t(), default: "world"}) :: String.t() do
hello
end
```
The `defn` will transform into:
```elixir
def sample(hello \\ "world") do
hello
end
```
Closes #9744

fix(sdk/elixir): fix default argument doesn't set to Elixir

---

.changes/unreleased/Added-20250722-180740.yaml
cmd/dagger/flags.go
cmd/dagger/functions.go
core/integration/module_call_test.go

This allows passing build args to a docker build via the CLI.
Example
```
host | directory . | docker-build --platform darwin/arm64 --build-args BIN_NAME=docker-run,NO_ARCHIVE=true --target export-bin | export .
```
\cc @eunomie

cli: add support for a []BuildArg flag

---

core/client_resource.go
core/container.go
core/llm.go
core/modfunc.go
core/module.go
core/object.go
core/schema/cache.go
core/schema/module.go
core/schema/modulesource.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
engine/server/session.go
sdk/elixir/lib/dagger/gen/module.ex

Fixes https://github.com/dagger/dagger/issues/10434. These fields can easily be constructed and be nullable.
Before:
```
❯ echo "{module{name,runtime,source}}" | dagger query
▶ connect 0.2s
● moduleSource(refString: ".", allowNotExists: true): ModuleSource! 0.0s
▶ .configExists: Boolean! 0.0s
● module: Module! 0.0s
● .name: String! 0.0s
● Module.runtime: Container! 0.0s
● Module.source: ModuleSource! 0.0s
Full trace at https://dagger.cloud/jedevc/traces/cbb397e127bbea9e419db824de5fb8d9
Error: make request: input: module.runtime panic while resolving Module.runtime: runtime error: invalid memory address or nil pointer dereference
goroutine 51275962 [running]:
runtime/debug.Stack()
/usr/lib/go/src/runtime/debug/stack.go:26 +0x5e
github.com/dagger/dagger/dagql.(*Server).resolvePath.func1() …
```

fix: make various module fields nullable

---

cmd/codegen/generate_client.go
cmd/codegen/generator/config.go
cmd/codegen/generator/go/generate_client.go
cmd/codegen/generator/go/generate_library.go
cmd/codegen/generator/go/generate_module.go
cmd/codegen/generator/go/generator.go
cmd/codegen/generator/go/loader.go
cmd/codegen/modsourcedeps.graphql
core/integration/client_generator_test.go
core/sdk/go_sdk.go

Previously, the following operations were failing:
```
mkdir test && cd test
dagger init
dagger client install go
```
Because the go client generator assumed that the module was aside a go module, same as module generation before we generate a default go.mod.
This PR fixes that issue by: generating a default go.mod based on the module name if no go.mod exist in the current directory. This allows an user to create a submodule in a go project and import the client from there.
Also fixes an issue where the client installation failed if no go file were found in the module directory.
Add integration tests to verify the new behaviour.

fix: go client generator now works on empty dir

---

engine/distconsts/consts.go
modules/go/main.go

Alpine Linux 3.22 updated their Go package from 1.24.4 to 1.24.6-r0 on 2025-08-08. This change updates the Go version constant to match the available package, fixing the build error when building the dev version of the engine:
```shell
go-1.24.6-r0.apk disqualified because "1.24.6-r0" does not
satisfy "go~1.24.4"
```
The constraint "go~1.24.4" specifically requires version 1.24.4.x, but Alpine no longer provides this version: https://pkgs.alpinelinux.org/package/v3.22/community/x86_64/go

fix: update Go version to match Alpine 3.22 package

---

.changes/unreleased/Added-20250811-130142.yaml
core/git.go
core/integration/git_test.go
core/schema/directory.go
core/schema/git.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
docs/static/reference/php/Dagger/GitRef.html
docs/static/reference/php/doc-index.html
docs/static/reference/php/doctum-search.json
sdk/elixir/lib/dagger/gen/git_ref.ex
sdk/go/dagger.gen.go
sdk/php/generated/GitRef.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts
util/gitutil/cli_helpers.go

This is pretty much the main reason we need our own `Git` implementation in `version/git.go` (which is slow).
See https://github.com/dagger/dagger/pull/10801 for more context.
We can implement this ourselves (with a reasonable amount of reshuffling and refactoring).

feat: add `git.commonAncestor`

---

cmd/codegen/generator/go/templates/modules.go
cmd/codegen/generator/typescript/templates/functions.go
cmd/codegen/introspection/introspection.go
core/enum.go
core/interface.go
core/module.go
core/modulesource.go
core/object.go
core/schema/modulesource.go
core/typedef.go
dagql/server.go
dagql/testdata/introspection.json
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
docs/static/reference/php/Dagger/SourceMap.html
docs/static/reference/php/doc-index.html
docs/static/reference/php/doctum-search.json
sdk/elixir/lib/dagger/gen/enum_type_def.ex
sdk/elixir/lib/dagger/gen/enum_value_type_def.ex
sdk/elixir/lib/dagger/gen/field_type_def.ex
sdk/elixir/lib/dagger/gen/function.ex
sdk/elixir/lib/dagger/gen/function_arg.ex
sdk/elixir/lib/dagger/gen/interface_type_def.ex
sdk/elixir/lib/dagger/gen/object_type_def.ex
sdk/elixir/lib/dagger/gen/source_map.ex
sdk/go/dagger.gen.go
sdk/php/generated/SourceMap.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

Sparked by a bug reported by @jasonmccallister.
1. Essentially, not every SDK supports generating/displaying sourcemaps, so these fields must be nullable.
2. We weren't displaying sourcemaps for modules loaded from directories / git (we were only doing local).
- We can very reasonably display for these cases.
- We just need to construct an HTML URL!

Source map improvements

---

modules/evals/build_multi.go
modules/evals/responses.go
modules/evaluator/workspace/main.go

* avoid using names since names aren't actually exposed, LLM may confuse for filenames
* don't be over-precise for withEnvVariable tool naming convention
* bring Gemini down from 10 to 3 in parallel - we're hitting rate limits now, seems like they wisened up

evals: slight tweaks

---

.changes/unreleased/Fixed-20250819-081619.yaml
core/git.go
core/integration/git_test.go
core/integration/services_test.go
util/gitutil/cli.go
util/gitutil/config_env.go
util/gitutil/config_env_test.go

Fixes https://discord.com/channels/707636530424053791/1397694731496067194/1397694731496067194
Previously, HTTP(S) authentication worked only for the parent repository clone. Submodule clones failed because the auth header (http.<scheme>://<host>/.extraheader) passed via CLI args (-c) wasn’t inherited by nested Git processes (git submodule update). By injecting the header through the GIT_CONFIG_* environment variables instead, the auth configuration propagates to submodules automatically, fixing the inheritance issue and ensuring consistent authentication.
Since opening this PR, I’ve made a few adjustments:
- Implemented shallow fetch fallback:
> Now we always attempt git submodule update with --depth=1 first. If the server doesn’t support shallow clones (fatal: dumb http transport does …

fix(core/git): ensure HTTP auth is propagated to submodules

---

core/integration/cloud_test.go
engine/cache/cachemanager/manager.go
engine/client/client.go
engine/server/server.go
engine/telemetry/cloud.go
engine/telemetry/url.go
internal/cloud/auth/auth.go
internal/cloud/auth/auth_test.go
internal/cloud/client.go

The problem: public repositories must expose their credentials if they wish to send telemetry Dagger Cloud. We expose our DAGGER_CLOUD_TOKEN in this repository. Since its only telemetry we don't worry much. But as we introduce compute-related features its critical that we have a secure mechanism to authenticate against api.dagger.cloud without exposing sensitive credentials.
To fix this issue we implement an OIDC authentication flow against our cloud API. To use this mechanism users need to specify `DAGGER_CLOUD_TOKEN=oidc` and be in a context where environment variables are correctly set for the supported providers. At the moment we only support GitHub as a provider. On top of specifying `DAGGER_CLOUD_TOKEN=oidc` users need to add the `id-token: write` permission to their workflow so …

feat: support OIDC auth with the Dagger Cloud API

---

docs/netlify.toml

Note: this depends on changes in https://github.com/dagger/dagger/pull/10879 and should be merged after.
This is a follow-up to #10731 
The strategy adopted to update these redirects is as follows:
- Review current (version 0.18) and new docs sitemap and create specific redirects for each modified page
- Update existing specific redirects already in place (for documentation versions >0.9 and <0.18) 
- For very old documentation (versions 0.9, 0.2, and 0.1), redirect URLs to the external archival site, archive.docs.dagger.io
- Where feasible, apply wildcard redirects (*) for older URL patterns, to reduce the number of specific redirects. These are intentionally placed at the end of the file to ensure that more specific redirects are processed first.

docs: update redirects

---

.dagger/sdk.go

Like in https://dagger.cloud/dagger/traces/3d6e590c8188182a11f03e03e1007809.

ci: avoid throwing an absolutely massive error

---

core/modfunc.go
core/modulesource.go
dagql/idtui/testdata/TestTelemetry/TestGolden/path-args

Fixes https://github.com/dagger/dagger/issues/10913
Ideally, we'd just call `host.file` here, but then we'd have to reproduce all of the other logic in `LoadContext`, which doesn't sound incredibly fun.
So this is a quick fix!

fix: speed up loading contextual files

---

.github/workflows/_dagger_on_depot_local_engine.yml
.github/workflows/_dagger_on_depot_remote_engine.yml
.github/workflows/benchmark-engine.yml
.github/workflows/publish.yml

Follow-up to #10852.
We still need the checkout step (annoyingly), but we should be directly invoking the dagger module, for the reasons explained there.

ci: directly call with module in more cases

---

cmd/dagger/engine.go
core/schema/service.go
core/service.go
core/services.go
core/services_test.go
core/terminal.go
dagql/call/id.go
dagql/dagui/extract.go
dagql/dagui/spans.go
dagql/idtui/frontend.go
dagql/idtui/frontend_dots.go
dagql/idtui/frontend_plain.go
dagql/idtui/frontend_pretty.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
docs/static/reference/php/Dagger/Service.html
docs/static/reference/php/doc-index.html
docs/static/reference/php/doctum-search.json
sdk/elixir/lib/dagger/gen/service.ex
sdk/go/dagger.gen.go
sdk/php/generated/Service.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

This PR adds improved TUI debugging, by allowing a new `T` hotkey to open a terminal on a span.
[![asciicast](https://asciinema.org/a/jhVkugQYzGpLM6rzjmoMvPLTM.svg)](https://asciinema.org/a/jhVkugQYzGpLM6rzjmoMvPLTM)
This is supported for existing terminal functions on `Container` and `Directory`, as well as on `Service`, where `Service.terminal` has now been added as well!
Related:
- https://github.com/dagger/dagger/issues/10923

Improved TUI debugging

---

sdk/typescript/.changes/unreleased/Fixed-20250817-225411.yaml
sdk/typescript/package.json
sdk/typescript/yarn.lock

Fixes a critical build failure in the TypeScript SDK caused by a missing OpenTelemetry Jaeger exporter dependency. The `@opentelemetry/sdk-node` package dynamically imports `@opentelemetry/exporter-jaeger` but this dependency was not included in the package.json, causing webpack and other bundlers to fail during build.
Projects consuming `@dagger.io/dagger` would encounter the following build error:
```
Module not found: Can't resolve '@opentelemetry/exporter-jaeger' in 
'/path/to/node_modules/@opentelemetry/sdk-node/build/src'
```
The dependency chain was:
```
@dagger.io/dagger
└── @opentelemetry/sdk-node@0.202.0
└── (dynamically imports) @opentelemetry/exporter-jaeger ❌ NOT INSTALLED
```
The `@opentelemetry/sdk-node` package attempts to require the Jaeger exporter when …

fix(sdk/typescript): add missing @opentelemetry/exporter-jaeger dependency

---

cmd/introspect/introspect.go
core/directory.go
core/enum.go
core/interface.go
core/mcp.go
core/modfunc.go
core/module.go
core/object.go
core/schema/coremod.go
core/schema/directory.go
core/schema/git.go
core/schema/module.go
core/schema/modulesource.go
core/schema/service.go
core/telemetry.go
core/util.go
dagql/call/id.go
dagql/dagql_test.go
dagql/directives.go
dagql/introspection/types.go
dagql/objects.go
dagql/server.go
dagql/types.go
engine/server/session.go

- Cherry-pick of [`06126db` (#10946)](https://github.com/dagger/dagger/pull/10946/commits/06126db402643e8a402b3e18657fce0e2e19707a)
- And also a change to move the `View` type into `dagql/call`, so `ID.View` can directly return a rich type, which avoids the need to convert it later, a fiddly and annoying thing.

Little view chores

---

dagql/call/id.go
dagql/idtui/golden_test.go
dagql/objects.go
engine/sources/local/hash.go

Needed to debug some perf regressions in https://github.com/dagger/dagger/pull/10761; while doing so I found a lot of extremely low hanging fruit. Just gonna group them together rather than send out 5+ separate PRs.
Draft because I'm pushing more commits here still. Pushing them one-by-one so I can verify they independently fix individual bottlenecks (i.e. don't make each other redundant) and don't have any dependency on #10761 
---
[dagql: optimize InputSpecs.Inputs](https://github.com/dagger/dagger/pull/10965/commits/d68a30b39ac99a33890e0d87f12e65f400f25e13)
Before this, a pprof cpu profile of the engine while running TestTelemetry showed that 7-10% of our cpu time was spent in dagql.InputSpecs.Inputs. Most of this was due to the `seen` map creation and read/writes.
Given the small size …

Grab bag of engine optimizations

---

cmd/codegen/generator/go/templates/module_funcs.go
core/git.go
core/integration/module_test.go
core/integration/services_test.go
core/modfunc.go
core/modulesource.go
core/schema/git.go
core/schema/module.go
core/schema/modulesource.go
core/typedef.go
sdk/java/dagger-java-annotation-processor/src/main/java/io/dagger/annotation/processor/DaggerModuleAnnotationProcessor.java
sdk/python/src/dagger/mod/_arguments.py
sdk/typescript/dev/node/src/commands.ts
sdk/typescript/dev/src/index.ts
sdk/typescript/src/module/entrypoint/register.ts
sdk/typescript/src/module/registry.ts

Fixes #8520. Follow-up to https://github.com/dagger/dagger/pull/10195.
This allows a module to get git information about itself - it can do this through the core `Git` type.
The `defaultPath` annotation is extended to allow setting a default value for a `GitRepository`/`GitRef` parameter. If the caller does not provide a value, the method uses the specified default - either a local path (e.g., `"./.git"`) or a remote repository URL (e.g., `"https://github.com/dagger/dagger.git"`).

feat: add contextual git

---

docs/current_docs/extending/modules/module-dependencies.mdx
docs/current_docs/extending/modules/remote-repositories.mdx

https://github.com/dagger/dagger/pull/10960 should vastly simplify installation of private dependencies.
It's now easier to just skip the explicit `https`/`ssh` proto, since it can be automagically determined in more cases. I've updated the docs to make this clearer.
I've also moved the info on private repos directly next to the info on installing other dependencies, instead of living in remote repositories, where I don't really expect it to be.

Improve docs on private dependencies

---

core/integration/legacy_test.go
core/modulesource.go
core/schema/host.go
dagql/idtui/testdata/TestTelemetry/TestGolden/path-args

As discussed with @jedevc, this PR ensure that module with version < `v0.18.18` are not automatically loading .gitignore
so that we don't break compatibility.
I'm waiting for a clear response on https://discord.com/channels/707636530424053791/1413511775546118215/1414520241912021062 before applying any fixes on disabling gitignore for specific arguments

fix: git ignore backward compatibility

---

core/integration/services_test.go
core/service.go

this commit fixes the issue where running `dagger call svc up` only runs
the service once even if used by different clients.
Fixes #11014

avoids starting service twice when used by different clients

---

.changes/unreleased/Added-20250915-142940.yaml
core/directory.go
core/host.go
core/integration/directory_test.go
core/integration/host_test.go
core/schema/directory.go
core/schema/host.go
core/schema/modulesource.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
docs/static/reference/php/Dagger/Directory.html
docs/static/reference/php/Dagger/Host.html
docs/static/reference/php/doc-index.html
docs/static/reference/php/doctum-search.json
sdk/elixir/lib/dagger/gen/directory.ex
sdk/elixir/lib/dagger/gen/host.ex
sdk/go/dagger.gen.go
sdk/php/generated/Directory.php
sdk/php/generated/Host.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

[Schema diff](https://github.com/dagger/dagger/pull/10956/files#diff-6d45938d3a99ad730e8d639cd2218f57c90828f1deeaad17c073cad22bfd0b50)
This adds support for executing a "findup" search, like for example looking for the nearest `.git`, `dagger.json` etc.
It is available in `Directory` and `Host`

findup API: find a file or directory by walking up the directory tree

---

dagql/dagui/extract.go
dagql/dagui/spans.go
dagql/idtui/frontend_pretty.go

See the following command:
$ dagger core -E container from --address=alpine with-mounted-directory --path=/src --source=. with-exec --args ls,-lh,src stdout
(this is the issue I observed during a live demo last week lol)
We need to make sure to preserve the IDs that we actually observe!

fix: preserve call ids during id extraction

---

cmd/dagger/client.go
core/integration/client_generator_test.go
core/schema/modulesource.go
core/sdk/utils.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
docs/static/reference/php/Dagger/ModuleSource.html
docs/static/reference/php/doc-index.html
docs/static/reference/php/doctum-search.json
sdk/elixir/lib/dagger/gen/module_source.ex
sdk/go/dagger.gen.go
sdk/php/generated/ModuleSource.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

Add `dagger client update` command so you can update external client generator.
Add `WithUpdatedClients` to `ModuleSource` to update one or more clients.
Add integration tests.
Additional changes:
- Small fix on client install to clean the path in the generator is a local module

feat: add dagger client update command

---

.github/workflows/alternative-ci-engines-1.yml
internal/cloud/auth/auth.go

We want to test the performance and reliability of the new cloud engines. In the past we've always introduced changes to our CI using "alternative-*" workflows. This is so that we can easily compare the performance of the new CI changes against our current baseline. We are initially using 4 jobs: `testdev-everything-else`, `testdev-module-runtimes`, `go` and `php`. This were picked because, in the case of Engine & CLI, they are the slowest and least reliable jobs as can be seen [here](https://ui.honeycomb.io/dagger/environments/experimental/board/tXGtVxx7uVP/Is-Dagger-Dagger-production-ready):
We don't expect any performance improvements on the individual jobs themselves since its the same underlying infrastructure. The only difference is caching, we did not have any before and we do now. …

infra: setup alternative workflows to test cloud engines

---

.github/actions/call/action.yml

This was causing dependent pipelines, like publish, to fail with:
> Error: /home/runner/_work/dagger/dagger/./.github/actions/call/action.yml: (Line: 16, Col: 14, Idx: 290) - (Line: 16, Col: 17, Idx: 293): While parsing a quoted scalar, find unknown escape character.

infra: fix action.yml version formatting

---

cmd/dagger/main.go
dagql/dagui/opts.go
dagql/idtui/frontend_pretty.go

Adds a subtle indicator in the keymap section of the TUI for when a cloud engine is being used. For the other progress methods we will have a new span that will say "connecting to remote engine" and is a part of #10790 since an indicator that sticks doesn't really make sense in that context. Here is what it looks like:

cli: add TUI indicator when using cloud engines

---

sdk/php/.changes/unreleased/Changed-20250923-100314.yaml
sdk/php/runtime/main.go

See https://github.com/dagger/dagger/pull/10991#issuecomment-3257828892
This image is maintained by the same maintainer as the official docker image.
The difference is this image is ~75Mb smaller,
it is designed specifically for copying the binary.

PHP: Use "official" composer image

---

cmd/engine/.dagger/build/sdk.go
core/integration/git_test.go
core/integration/module_test.go
engine/distconsts/consts.go

Fixes CI
`TestPrivateDeps/golang` started failing in CI due to Alpine's recent security update in 3.22.1, addressing [CVE-2025-4575](https://security.alpinelinux.org/vuln/CVE-2025-4575) (details here: https://alpinelinux.org/posts/Alpine-3.19.8-3.20.7-3.21.4-3.22.1-released.html).
Erik below realized that the real fix is to manually install the `openssl` lib conjointly with the `openssh` one

fix: bump alpine base to 3.22.1 + manually install `openssl`

---

cmd/engine/main.go

the current VersionPrinter was printing some old buildkit constants
which are not relevant anymore since we're slowly moving a bunch of
those pats into the Dagger codebase

print engine version when starting

---

core/dotenv/dotenv.go
core/dotenv/dotenv_test.go
core/envvars.go
core/integration/envfile_test.go
core/integration/suite_test.go
core/schema/envfile.go
docs/docs-graphql/schema.graphqls
docs/static/api/reference/index.html
docs/static/reference/php/Dagger/EnvFile.html
sdk/elixir/lib/dagger/gen/env_file.ex
sdk/go/dagger.gen.go
sdk/php/generated/EnvFile.php
sdk/python/src/dagger/client/gen.py
sdk/rust/crates/dagger-sdk/src/gen.rs
sdk/typescript/src/api/client.gen.ts

- Evaluate quotes by default: `foo="a b c"`
- Support default values in variables: `foo=${bar:-baz}`
- Cleaner implementation, with a low-level go package
- Lots of tests
- Optional "raw" mode

EnvFile: better dotenv compatibility, more tests

---

cmd/dagger/shell.go
core/integration/llmtest/allow-llm.golden
core/integration/llmtest/api-limit.golden
core/integration/llmtest/hello-world.golden
core/llm_anthropic.go
core/mcp.go
core/openrouter/openrouter.go
core/prompts/basics.md
core/prompts/outputs.md
core/prompts/writable.md
dagql/dagui/ordered_set.go
docs/current_docs/reference/cli/index.mdx
docs/current_docs/reference/configuration/llm.mdx
modules/evals/main.go
modules/evals/mcp_server.go
modules/evals/responses.go
modules/evals/writable.go
modules/evaluator/main.go
modules/evaluator/workspace/main.go

This started off as a simple bump to Claude Sonnet 4.5, which was released today: https://www.anthropic.com/news/claude-sonnet-4-5
But in doing so I wanted to make sure the evals were solid, which led to fixing a bunch of things, mostly driven by Gemini's limitations. I tried bumping Gemini to 2.5 Flash instead of 2.0 Flash, but it consistently hits `MALFORMED_FUNCTION_CALL` specifically for the MCP server case. That led me to un-namespacing the tool names, as one way that can happen is Gemini calling an unknown tool. That fixed things for 2.0 Flash, but 2.5 Flash continues to return the same error, with absolutely no indication as to why, even after inspecting the tool schemas. Incredibly frustrating.
Along the way it became clear that the recently added `Writable` eval was very …

llm: bump Sonnet to 4.5, grab bag of fixes + eval improvements

---

cmd/dagger/.dagger/main.go

This allows to build Go apps that use vendoring, using Dagger's Go module. Useful when making local modifications to vendored libraries.

go: allow vendor/* files through

---

sdk/elixir/test/dagger/client_test.exs
sdk/go/examples_test.go
sdk/python/tests/client/test_integration.py

Otherwise, they run all over each other and create weird flakes.

test: use unique cache volume per sdk test

---

helm/dagger/templates/engine-daemonset.yaml
helm/dagger/templates/engine-statefulset.yaml
helm/dagger/values.yaml

this enables users that need to access the metrics server for example to
be able to expose ports to scrape them
coming from: https://discord.com/channels/707636530424053791/708371226174685314/1415154356332007474

allow setting additional container ports to the Dagger Engine container

---

core/telemetry.go

Tiny tweak to avoid this behavior: https://dagger.cloud/vito/traces/1dcacb86a7f118f881acdeab4af72d38?span=63724b6fc580ade5
Post-fix: https://dagger.cloud/vito/traces/1489bd1c14f3efb73b4af764d9b6bf11?span=8ec435fcdc2ee4b3

telemetry: don't print IDs

---

core/dagop.go
engine/buildkit/op.go

cc @marcosnils 
Got this far investigating the weird `nil` issues.
I think this is due to something wrong in a dagop somewhere. I *suspect* `LLB` and `Result` on a single `Directory` are somehow ending up `nil`, but I can't *quite* work out what that is.
This should help debug the issue though:
- We'll get an error, which should propagate to a specific schema handler, so we're able to reproduce more easily.
- We'll get some more detailed logs.

chore: lift nil output detection to custom op

---

cmd/dagger/call.go
cmd/dagger/function_name.go
cmd/dagger/function_name_test.go
cmd/dagger/functions.go
cmd/dagger/shell.go
engine/client/client.go
engine/client/drivers/cloud.go
engine/client/drivers/driver.go
internal/cloud/client.go

We send the module, function name and command being executed to the API and let it make the decision for how to provision an engine. The function name parsing function added only supports commands when flags are set using the `--cloud=true` format. If flags do not use `=` to set values we do not set the function name. This was discussed on Monday's meeting and agreed as a good enough stop gap given current constraints. See the `spanName` function for a deeper explanation on why this is a stop gap.

feat: capture contextual information for provisioning PARC engines

---

docs/.dagger/main.go

this speeds up module loading considerably when you have dirty files
in your working directory

ingore unnecessary files in docs context

---

docs/current_docs/reference/deployment/kubernetes.mdx
docs/current_docs/reference/deployment/openshift.mdx
docs/netlify.toml

During https://github.com/dagger/dagger/pull/11128, we moved the Kubernetes and OpenShift pages to a new Deployment section, which fits them better. See the justification here: https://github.com/dagger/dagger/pull/11128#discussion_r2379448890.
However, I didn't update the slugs, so the pages were still at the same place.
This patch moves them to the new locations, and updates the redirects.

docs: move kubernetes and openshift to deployment url

---

dagql/idtui/chroma.go
dagql/idtui/frontend.go

Reapplies https://github.com/dagger/dagger/pull/10266.
This seems to have been removed in #10907, which sadly makes light mode unusable again.

Fix light mode in shell

---

sdk/php/.gitignore
sdk/php/dagger.json
sdk/php/phpunit.xml.dist

Tweaks PHPUnit config to use a .cache/ directory
The idea is to transition each CI tool's cache to this directory, minimizing boilerplate ignores and excludes elsewhere (i.e. dagger.jsons, Ignore decorators, .gitignores)

PHP: Store test results in .cache directory

---

.changes/unreleased/Fixed-20251007-171917.yaml
core/integration/services_test.go
core/service.go

Fixes #11195 
The terminal implementation was not providing a session group when creating new mounts. This meant that if an input mount was derived from a still-lazy private image, no auth was available and pulling the image would fail.
This was exacerbated by a missing check for `err != nil`, which meant we went ahead and tried to start the container even though all the mounts were nil, which crashed the engine.
---
Added integ test coverage now too

fix handling of private images in terminal
